### ISSUE TITLE
Getting ERROR when we run ssl as true in Logstash 5.0 with elasticsearch output config ?

### ISSUE THREAD

**Issue by jain108shubhamtbt** [elastic/logstash#10037]
Getting ERROR when we run ssl as true in Logstash 5.0 with elasticsearch output config ?

Logstash Logs : 

[2018-10-03T15:43:17,789][WARN ][logstash.outputs.elasticsearch    ] UNEXPECTED POOL ERROR {:e=>#<Manticore::UnknownException: Unrecognized SSL message, plaintext connection?>}

[2018-10-03T15:43:17,790][ERROR][logstash.outputs.elasticsearch    ] An unknown error occurred sending a bulk request to Elasticsearch. We will retry indefinitely {:error_message=>"Unrecognized SSL message, plaintext connection?", :error_class=>"Manticore::UnknownException", :backtrace=>["/opt/user/monitors/agent/agent/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:37:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "/opt/user/monitors/agent/agent/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/response.rb:79:in `call'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:40:in `perform_request'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:239:in `perform_request_to_url'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:221:in `perform_request'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:324:in `with_connection'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:220:in `perform_request'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:228:in `post'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:66:in `bulk'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/common.rb:182:in `safe_bulk'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/common.rb:105:in `submit'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/common.rb:72:in `retrying_submit'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/common.rb:23:in `multi_receive'", "org/jruby/RubyArray.java:1653:in `each_slice'", "/opt/user/monitors/agent/agent/vendor/local_gems/71a5254b/logstash-output-elasticsearch-5.0.1-java/lib/logstash/outputs/elasticsearch/common.rb:22:in `multi_receive'", "/opt/user/monitors/agent/agent/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:12:in `multi_receive'", "/opt/user/monitors/agent/agent/logstash-core/lib/logstash/output_delegator.rb:42:in `multi_receive'", "/opt/user/monitors/agent/agent/logstash-core/lib/logstash/pipeline.rb:310:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/user/monitors/agent/agent/logstash-core/lib/logstash/pipeline.rb:309:in `output_batch'", "/opt/user/monitors/agent/agent/logstash-core/lib/logstash/pipeline.rb:258:in `worker_loop'", "/opt/user/monitors/agent/agent/logstash-core/lib/logstash/pipeline.rb:231:in `start_workers'"]} 

Use output Configure :

elasticsearch {
             log_type => "%{type}"
             action => "index"
             index => "${INDEX_PREFIX:att_lle}-%{+yyyy-MM-dd}"
             ssl => true
             hosts => ["${OUTPUT_HOST1:localhost}:${OUTPUT_PORT1:9200}"]
             manage_template => false
}

**Comment by jain108shubhamtbt** [comment]
Please help me out .

**Comment by programagor** [comment]
First of all, please use the https://discuss.elastic.co/c/logstash forum to resolve configuration issues. This tracker is used for bugs in the Logstash product.
Second of all, make sure your output configuration contains the following:
```
hosts => ["https://${OUTPUT_HOST1:localhost}:${OUTPUT_PORT1:9200}"] #note the https
cacert => "certificate_authority.crt" #if you are using your own CA (alternatively, look into trust-stores)
```
And lastly, make sure to have SSL enabled on the HTTP component of your Elasticsearch nodes, not just on the Transport.
