### ISSUE TITLE
Monitoring metric shipment error/retry improvements

### ISSUE THREAD

**Issue by acchen97** [elastic/logstash#10049]
The shipment of Logstash monitoring metrics could have improved retry policy and error message. Today, when monitoring is enabled and the ES monitoring endpoint is unavailable, LS will exhibit continuous error messages like the one below, which is a bad user experience.

```
[2018-10-10T14:15:25,520][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"http://elasticsearch:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://elasticsearch:9200/][Manticore::ResolutionFailure] elasticsearch"}
```

Requested enhancements:
1. Implement incremental backoff for retries when the ES monitoring endpoint is unavailable.
2. Update the error message to be more accurately descriptive. For example: "Logstash monitoring is enabled, but health metrics are not currently being sent as the Elasticsearch monitoring endpoint is unreachable. Please check the availability of your Elasticsearch monitoring cluster."

**Comment by acchen97** [comment]
@jsvd any chance we can get this prioritized? I'd consider this important for the overall getting started experience with our Logstash default build.

**Comment by jsvd** [comment]
After speaking with @acchen97, we have a plan forward:

While the Metrics input is gated by the license checker, we should take this one step further and prevent the monitoring pipeline to boot until we have validated the license, this way we would reduce the amount of error messages by just saying "license checker failed to retrieve license, we won't be starting the monitoring pipeline". Starting the monitoring pipeline without license checker should be considered a bug.

Alongside this, we can change the logging messages of the licensereader so that instead of:

```
[2018-10-18T12:43:06,921][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://instance:9200"]}
[2018-10-18T12:43:07,010][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://instance:9200/]}}
[2018-10-18T12:43:07,011][INFO ][logstash.licensechecker.licensereader] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>https://instance:9200/, :path=>"/"}
[2018-10-18T12:43:07,018][WARN ][logstash.licensechecker.licensereader] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://instance:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://instance:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
[2018-10-18T12:43:07,044][WARN ][logstash.licensechecker.licensereader] Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [https://instance:9200/][Manticore::SocketException] Connection refused (Connection refused) {:url=>https://instance:9200/, :error_message=>"Elasticsearch Unreachable: [https://instance:9200/][Manticore::SocketException] Connection refused (Connection refused)", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
[2018-10-18T12:43:07,054][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"Elasticsearch Unreachable: [https://instance:9200/][Manticore::SocketException] Connection refused (Connection refused)", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError", :backtrace=>["/tmp/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:293:in `perform_request_to_url'", "/tmp/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:278:in `block in perform_request'", "/tmp/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:373:in `with_connection'", "/tmp/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:277:in `perform_request'", "/tmp/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:285:in `block in get'", "/tmp/logstash-6.4.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-elasticsearch-9.2.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:162:in `get'", "/tmp/logstash-6.4.2/x-pack/lib/license_checker/license_reader.rb:28:in `fetch_xpack_info'", "/tmp/logstash-6.4.2/x-pack/lib/license_checker/license_manager.rb:40:in `fetch_xpack_info'", "/tmp/logstash-6.4.2/x-pack/lib/license_checker/license_manager.rb:27:in `initialize'", "/tmp/logstash-6.4.2/x-pack/lib/license_checker/licensed.rb:37:in `setup_license_checker'", "/tmp/logstash-6.4.2/x-pack/lib/monitoring/inputs/metrics.rb:56:in `register'", "/tmp/logstash-6.4.2/logstash-core/lib/logstash/pipeline.rb:242:in `register_plugin'", "/tmp/logstash-6.4.2/logstash-core/lib/logstash/pipeline.rb:253:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/tmp/logstash-6.4.2/logstash-core/lib/logstash/pipeline.rb:253:in `register_plugins'", "/tmp/logstash-6.4.2/logstash-core/lib/logstash/pipeline.rb:396:in `start_inputs'", "/tmp/logstash-6.4.2/logstash-core/lib/logstash/pipeline.rb:294:in `start_workers'", "/tmp/logstash-6.4.2/logstash-core/lib/logstash/pipeline.rb:200:in `run'", "/tmp/logstash-6.4.2/logstash-core/lib/logstash/pipeline.rb:160:in `block in start'"]}
```

we should only see a shorter version of the last log entry, like:

```
[2018-10-18T12:43:07,054][ERROR][logstash.licensechecker.licensereader] Unable to retrieve license information from license server {:message=>"Elasticsearch Unreachable: [https://instance:9200/][Manticore::SocketException] Connection refused (Connection refused)"
```

**Comment by acchen97** [comment]
Additionally, we've decided to take a phased approach to resolve this:

1. As mentioned above by @jsvd, we will, as a first phase, enhance the behavior so that the metrics pipeline only starts after a successful license check. This will solve the error message spam from the ES output in the metrics pipeline.
2. This unfortunately doesn't solve the spam from the ES output in the license checker for connection pooling. For this to be more configurable (i.e. incremental backoff), we will need to replace the ES output with a custom ES client for more control as a second phase.
