### ISSUE TITLE
filebeat -> logstash: pipelines java.io.Exception when transfer starts

### ISSUE THREAD

**Issue by fenchu** [elastic/logstash#10066]
Hi
when I push data from filebeat, it crashes at the beginning, the wait (probably reconnect) and all is fine.
until next time I run filebeat on the server, this happened after I moved to pipelines other than default ':main'

- Version:
Starting Logstash {"logstash.version"=>"6.4.2"}
filebeat version 6.4.2 (amd64), libbeat 6.4.2 [e193f6d68b25b7ddbe3a3ed8d60bc07fea1ef800 built 2018-09-26 12:41:59 +0000 UTC]
- Operating System:
Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
- Config File (if you have sensitive info, please remove it):
on windows client I issue:
`7zip.exe e -so logs\*.gz* | .\filebeat.exe -once -c .\filebeat.yml`
on linux I issue:
`zcat logs/*.gz* | .\filebeat -once -c .\filebeat.yml`

filebeatconfig, just pushes to logstash
```
filebeat.inputs:
- type: stdin
  enabled: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 3
output.logstash:
  hosts: ["<mylogstashserver>:5044"]
logging.level: debug
```
Logstash config:
```
bash-4.2$ cat /usr/share/logstash/config/logstash.yml
http.host: 0.0.0.0

bash-4.2$ cat /usr/share/logstash/config/pipelines.yml
- pipeline.id: heartbeat
  path.config: "/usr/share/logstash/pipeline/heartbeat.conf"
- pipeline.id: proxylogs
  path.config: "/usr/share/logstash/pipeline/proxylogs.conf"

bash-4.2$ cat /usr/share/logstash/pipeline/proxylogs.conf
# input proxylogs from filebeat
input {
  beats {
    port => 5044
    type => "frombeats"
 }
}
filter {
    if [type] == "frombeats" {
     # grok-filters, works fine in logstash -f proxylogs.conf
   }
}
output {
    if [type] == "frombeats" {
        stdout { codec => rubydebug }
    }
}
```
Errorlog:
```
[2018-10-24T11:50:10,375][INFO ][logstash.agent           ] Pipelines running {:count=>2, :running_pipelines=>[:heartbeat, :proxylogs], :non_running_pipelines=>[]}
[2018-10-24T11:50:10,493][INFO ][org.logstash.beats.Server] Starting server on port: 5044
[2018-10-24T11:50:11,272][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-10-24T11:51:44,957][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.2.0.41:57918] Handling exception: Connection reset by peer
[2018-10-24T11:51:44,958][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.read0(Native Method) ~[?:1.8.0_181]
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39) ~[?:1.8.0_181]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223) ~[?:1.8.0_181]
        at sun.nio.ch.IOUtil.read(IOUtil.java:192) ~[?:1.8.0_181]
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380) ~[?:1.8.0_181]
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```
Then all my log-lines come in all fine

- Sample Data:
<just input any data> 
- Steps to Reproduce:
This happens any time zcat anyting via filebeat.

So the caveat is a slight timeout around 10sec and a ioexception in the log each time cron/scheduler hits.

I use `docker.elastic.co/logstash/logstash:6.4.2` docker image

**Comment by MorrieAtElastic** [comment]
Identical stack trace seen in logstash 7.5.1 in environment with many many beats processes funneling data to 2 logstash processes. Unclear at this time if this is the same problem.

**Comment by andsel** [comment]
I've tried locally this way:
- created a simple text file and zipping it, `echo "bla bla" > sample.txt; gzip sample.txt`
- launched a local instance of LS with `bin/logstash -e "input { beats {port => 5044 } } output { stdout { codec => rubydebug } }" --java-execution=true`
- started filebeat to send data: `zcat sample.txt.gz | filebeat --path.config . --path.data . --path.logs . -c ./filebeat.yml` with `filebeat.yml` as 
```
filebeat.inputs:
- type: stdin
  enabled: true
output.logstash:
  hosts: ["127.0.0.1:5044"]
logging.level: debug
```

And no error appened. If I don't override the `--path.config .` then filebeat load `filebeat.yml` from `/etc/filebeat/filebeat.yml`. Could you try to verify your connection from filebeat with `filebeat --path.config . --path.data . --path.logs . -c ./filebeat.yml test output` if it's able to connect to your Logstash?
However this is issue should be opened to https://github.com/logstash-plugins/logstash-input-beats
