### ISSUE TITLE
Logstash Plugin RSS - Error: Failed to open TCP connection to www.examlpes.com:80 (initialize: name or service not known)

### ISSUE THREAD

**Issue by barepset** [elastic/logstash#10267]
Logstash Plugins RSS, I'll try to implement the RSS plugin in Logstash, but i found some error in
log /var/log/syslog

the error is : 
~~~
Jan  9 13:23:26 log-rss logstash[1673]:   Error: Failed to open TCP connection to www.example.com:80 (initialize: name or service not known)
Jan  9 13:23:26 log-rss logstash[1673]:   Exception: Faraday::ConnectionFailed
Jan  9 13:23:26 log-rss logstash[1673]:   Stack: org/jruby/ext/socket/RubyTCPSocket.java:137:in `initialize'
Jan  9 13:23:26 log-rss logstash[1673]: org/jruby/RubyIO.java:1154:in `open'
Jan  9 13:23:26 log-rss logstash[1673]: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:885:in `block in connect'
Jan  9 13:23:26 log-rss logstash[1673]: org/jruby/ext/timeout/Timeout.java:149:in `timeout'
Jan  9 13:23:26 log-rss logstash[1673]: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:883:in `connect'
Jan  9 13:23:26 log-rss logstash[1673]: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:868:in `do_start'
Jan  9 13:23:26 log-rss logstash[1673]: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:857:in `start'
Jan  9 13:23:26 log-rss logstash[1673]: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1409:in `request'
Jan  9 13:23:26 log-rss logstash[1673]: uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/net/http.rb:1167:in `get'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:80:in `perform_request'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/faraday-0.9.2/lib/faraday.rb:99:in `method_missing'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-rss-3.0.5/lib/logstash/inputs/rss.rb:42:in `run'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:409:in `inputworker'
Jan  9 13:23:26 log-rss logstash[1673]: /usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:403:in `block in start_input'
~~~
==================================================================
in another condition the site www.example.com rss is normal if i open in browser.
- Version:
- Operating System: Debian Server 9
- Logstash version : 6.4.2
- Java Version : 
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)

Thanks Before

**Comment by yaauie** [comment]
It looks like your question is better suited for our [forum](https://discuss.elastic.co/c/logstash); if and when a bug is identified with clear reproducible steps, you'll likely want to file it against the [RSS Input Plugin](https://github.com/logstash-plugins/logstash-input-rss).

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
>
> _[...]_
>
> Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 
>
> [ISSUE_TEMPLATE.md](https://github.com/elastic/logstash/edit/master/.github/ISSUE_TEMPLATE.md)
