### ISSUE TITLE
Test Failure: xpack LogStash::Inputs::Metrics 

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#10371]
This spec has timing related issues that are extremely hard to nail because they don't reproduce locally and they happen sometimes during jenkins build.

This is in the `x-pack-unit` job, typically around
```
   LogStash::Inputs::Metrics
      integration
        with pipeline execution
          after the pipeline is setup
            should store the agent3s]
          #update
            state event
```
Where some condition are not met.

One example:

```
15:24:10     Failures:
15:24:10 
15:24:10       1) LogStash::Inputs::Metrics integration with pipeline execution #update #build_event data event has the correct schema
15:24:10          Failure/Error: wait(60).for { stats_events.empty? }.to be_falsey
15:24:10          
15:24:10            expected: falsey value
15:24:10                 got: true
15:24:10          # /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `block in handle_matcher'
15:24:10          # /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `block in handle_matcher'
15:24:10          # /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
15:24:10          # /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `block in to'
15:24:10          # /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `block in with_wait'
15:24:10          # /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
15:24:10          # /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
15:24:10          # /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
15:24:10          # ./spec/monitoring/inputs/metrics_spec.rb:153:in `block in (root)'
15:24:10          # /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
15:24:10          # /opt/logstash/lib/bootstrap/rspec.rb:13:in `<main>'
15:24:10 
15:24:10     Finished in 1 minute 13.57 seconds (files took 4.5 seconds to load)
15:24:10     141 examples, 1 failure
15:24:10 
15:24:10     Failed examples:
15:24:10 
15:24:10     rspec ./spec/monitoring/inputs/metrics_spec.rb:152 # LogStash::Inputs::Metrics integration with pipeline execution #update #build_event data event has the correct schema
15:24:10 
15:24:10     Randomized with seed 21453
```

**Comment by yaauie** [comment]
The underlying specs have gotten pretty tangled, and end up doing a whole lot of waiting/checking.

I'm going to take a stab at rewriting the specs from scratch to re-capture the original intent.

**Comment by colinsurprenant** [comment]
➕ 1️⃣
