### ISSUE TITLE
Line codec unit tests consistently fail on Windows 

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#10441]
Windows builds are currently failing due to an issue with the [Line Codec unit tests]( https://github.com/elastic/logstash/blob/master/logstash-core/src/test/java/org/logstash/plugins/codecs/LineTest.java)

```
19:13:25 
19:13:25 org.logstash.plugins.codecs.LineTest > testEncodeWithUtf8 FAILED
19:13:25     org.junit.ComparisonFailure: expected:<MÃ[¼nchen å®‰è£…ä¸­æ–‡è¾“å…¥æ³•]z> but was:<MÃ[ƒÂ¼nchen Ã¥Â®â€°Ã¨Â£â€¦Ã¤Â¸Â­Ã¦â€“â€¡Ã¨Â¾â€œÃ¥â€¦Â¥Ã¦Â³â€¢]z>
19:13:25         at org.junit.Assert.assertEquals(Assert.java:115)
19:13:25         at org.junit.Assert.assertEquals(Assert.java:144)
19:13:25         at org.logstash.plugins.codecs.LineTest.testEncodeWithUtf8(LineTest.java:311)
19:13:25 
19:13:25 
19:13:25 org.logstash.plugins.codecs.LineTest > testClone FAILED
19:13:25     java.lang.AssertionError: array lengths differed, expected.length=2 actual.length=4
19:13:25         at org.junit.Assert.fail(Assert.java:88)
19:13:25         at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:76)
19:13:25         at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:37)
19:13:25         at org.junit.Assert.internalArrayEquals(Assert.java:532)
19:13:25         at org.junit.Assert.assertArrayEquals(Assert.java:341)
19:13:25         at org.junit.Assert.assertArrayEquals(Assert.java:352)
19:13:25         at org.logstash.plugins.codecs.LineTest.testClone(LineTest.java:397)
19:13:25 
19:13:25 
19:13:25 org.logstash.plugins.codecs.LineTest > testEncodeWithCharset FAILED
19:13:25     java.lang.AssertionError: array lengths differed, expected.length=1 actual.length=3
19:13:25         at org.junit.Assert.fail(Assert.java:88)
19:13:25         at org.junit.internal.ComparisonCriteria.assertArraysAreSameLength(ComparisonCriteria.java:76)
19:13:25         at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:37)
19:13:25         at org.junit.Assert.internalArrayEquals(Assert.java:532)
19:13:25         at org.junit.Assert.assertArrayEquals(Assert.java:341)
19:13:25         at org.junit.Assert.assertArrayEquals(Assert.java:352)
19:13:25         at org.logstash.plugins.codecs.LineTest.testEncodeWithCharset(LineTest.java:365)
19:13:25 
19:13:25 
19:13:25 org.logstash.plugins.codecs.LineTest > testDecodeAcrossMultibyteCharBoundary FAILED
19:13:25     java.lang.AssertionError
19:13:25         at org.junit.Assert.fail(Assert.java:86)
19:13:25         at org.junit.Assert.assertTrue(Assert.java:41)
19:13:25         at org.junit.Assert.assertTrue(Assert.java:52)
19:13:25         at org.logstash.plugins.codecs.LineTest.testDecodeAcrossMultibyteCharBoundary(LineTest.java:128)
19:13:25 
```

**Comment by robbavey** [comment]
Closing, dupe of #10388
