### ISSUE TITLE
Elasticsearch input plugin: Parse Error invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by matteogrolla** [elastic/logstash#10516]
I have a document in Elasticsearch that crashes Logstash elasticsearch inputplugin when it tries to read it
the document is reported at the end of the message with the error log reported by logstash.
I'm using logstash to migrate documents from Elasticsearch to Mongo, but when logstash encounters the critical document the input plugin is restarted and starts from the beginning.
I'd like at least to skip the documents that can't be parsed, but I can't find a way to do so.
Can you help me?

P.S. If I create a new document in ES using curl and the textual representation of the critical document given here, I don't get parse error from logstash on this new document

-------Error log-------

~~~
[2019-03-06T12:43:47,696][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::Elasticsearch index=>"fulltextmg_33", id=>"3d2d80a0e02debd1b54d39b3e6b88b54a1ea45fe2c8ae8ddf2b0ec42e080ff61", hosts=>["pbauci01"], query=>"{ \"query\": { \"term\": { \"_id\": \"http://www.facebook.com/114701051917886_2073179089403396\"} } }", enable_metric=>true, codec=><LogStash::Codecs::JSON id=>"json_149580ae-80e8-4f8f-8728-66db3890cf1f", enable_metric=>true, charset=>"UTF-8">, size=>1000, scroll=>"1m", docinfo=>false, docinfo_target=>"@metadata", docinfo_fields=>["_index", "_type", "_id"], ssl=>false>
  Error: invalid byte sequence in UTF-8
  Exception: MultiJson::ParseError
  Stack: /opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/jrjackson-0.4.6-java/lib/jrjackson/jrjackson.rb:91:in `is_time_string?'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/jrjackson-0.4.6-java/lib/jrjackson/jrjackson.rb:36:in `load'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/multi_json-1.13.1/lib/multi_json/adapters/jr_jackson.rb:11:in `load'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/multi_json-1.13.1/lib/multi_json/adapter.rb:21:in `load'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/multi_json-1.13.1/lib/multi_json.rb:122:in `load'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/serializer/multi_json.rb:24:in `load'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/base.rb:322:in `perform_request'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/client.rb:131:in `perform_request'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/elasticsearch-api-5.0.5/lib/elasticsearch/api/actions/search.rb:183:in `search'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/logstash-input-elasticsearch-4.2.1/lib/logstash/inputs/elasticsearch.rb:200:in `do_run'
/opt/logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/logstash-input-elasticsearch-4.2.1/lib/logstash/inputs/elasticsearch.rb:188:in `run'
/opt/logstash-6.6.1/logstash-core/lib/logstash/pipeline.rb:426:in `inputworker'
/opt/logstash-6.6.1/logstash-core/lib/logstash/pipeline.rb:420:in `block in start_input'
~~~

----- critical document----

~~~
{
                    "domain": "facebook.com",
                    "insert_date": "2019-01-29T09:58:57+00:00",
                    "shared_url": "https://youtu.be/kQwFVi5mP3Y",
                    "photo": "https://external.xx.fbcdn.net/safe_image.php?d=AQAOKxdkOmvZNldH&w=130&h=130&url=https%3A%2F%2Fi.ytimg.com%2Fvi%2FkQwFVi5mP3Y%2Fmaxresdefault.jpg&cfs=1&sx=269&sy=0&sw=720&sh=720&_nc_hash=AQDjSJLoI_T1GZPi",
                    "site": "facebook.com",
                    "video": "https://www.youtube.com/embed/kQwFVi5mP3Y?autoplay=1",
                    "message": "NUOVO VIDEO ON LINE !!!!! ADESSO SU YOUTUBE!!! DA CESSO A FIGA!!! ADDIO BRUFOLI, PUNTI NERI e IMPERFEZIONI DAL VISO!!!! 👸💯 ❤ CLICCA QUI PER VEDERLO: https://youtu.be/kQwFVi5mP3Y",
                    "extract": "NUOVO VIDEO ON LINE !!!!! ADESSO SU YOUTUBE!!! DA CESSO A FIGA!!! ADDIO BRUFOLI, PUNTI NERI e IMPERFEZIONI DAL VISO!!!! 👸💯 ❤ CLICCA QUI PER VEDERLO: https://youtu.be/kQwFVi5mP3Y DA CESSO A FIGA!!! ADDIO BRUFOLI, PUNTI NERI e IMPERFEZIONI DAL VISO!!!! 👸💯 👸👍Iscrivetevi ed attivate le notifiche qua sopra ↑ cliccando sulla campanella 🔔 ⬇ APRI E LEGGI QUI SOTTO ⬇ __________________ Ciao Family! \ufffd\ufffd\ufffd...",
                    "id": "114701051917886_2073179089403396",
                    "stats": {
                        "score": 53,
                        "reach": 145442,
                        "weight": 53
                    },
                    "author": {
                        "username": "114701051917886",
                        "name": "Carlitadolce Official",
                        "likes": 145442,
                        "profile_image_url": "https://scontent.xx.fbcdn.net/v/t1.0-1/c1.0.200.200/p200x200/13418712_1066400113414637_5127970903263322072_n.png?oh=d50247bcc915fccc33bfb965410ab1d7&oe=597D056A",
                        "id": "114701051917886"
                    },
                    "last_update": "2019-01-29T09:58:57+00:00",
                    "text": "NUOVO VIDEO ON LINE !!!!! ADESSO SU YOUTUBE!!! DA CESSO A FIGA!!! ADDIO BRUFOLI, PUNTI NERI e IMPERFEZIONI DAL VISO!!!! 👸💯 ❤ CLICCA QUI PER VEDERLO: https://youtu.be/kQwFVi5mP3Y DA CESSO A FIGA!!! ADDIO BRUFOLI, PUNTI NERI e IMPERFEZIONI DAL VISO!!!! 👸💯 👸👍Iscrivetevi ed attivate le notifiche qua sopra ↑ cliccando sulla campanella 🔔 ⬇ APRI E LEGGI QUI SOTTO ⬇ __________________ Ciao Family! 👸👍POLLICE IN SU AL...",
                    "type": "facebook",
                    "description": "👸👍Iscrivetevi ed attivate le notifiche qua sopra ↑ cliccando sulla campanella 🔔 ⬇ APRI E LEGGI QUI SOTTO ⬇ __________________ Ciao Family! 👸👍POLLICE IN SU AL...",
                    "host": "facebook",
                    "content_type": "video",
                    "date": "2019-01-28T13:05:41+00:00",
                    "from": "facebook",
                    "lang": "it",
                    "name": "DA CESSO A FIGA!!! ADDIO BRUFOLI, PUNTI NERI e IMPERFEZIONI DAL VISO!!!! 👸💯",
                    "url": "http://www.facebook.com/114701051917886_2073179089403396",
                    "caption": "youtube.com"
                }
~~~

**Comment by matteogrolla** [comment]
I fixed the problem modifying
logstash-6.6.1/vendor/bundle/jruby/2.3.0/gems/jrjackson-0.4.6-java/lib/jrjackson/jrjackson.rb

from

def is_time_string?(json_source)
       json_source =~ TIME_REGEX
     rescue => e
       raise JrJackson::ParseError, e.message
     end

to


def is_time_string?(json_source) 
  json_source =~ TIME_REGEX
  rescue => e
    nil
 end

**Comment by matteogrolla** [comment]
I don't like hot jrJackson handles that input
but at least 
I think the exception from jrJackson should be handled differently from logstash

**Comment by yaauie** [comment]
> Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

I've moved this issue to logstash-plugins/logstash-input-elasticsearch#101
