### ISSUE TITLE
threads rescue & ensure behaviour 

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#10612]
While investigating #10611 I noticed that `rescue` and `ensure` handling in threads has different behaviours across JRuby (and Ruby) versions.

This affects how we handle or should handle the bubbling up of exception from, for example, a worker thread, back to a pipeline thread, into the agent thread and possibly in the main thread. 

First the test script I am using:

```ruby
Thread.abort_on_exception = true
begin
  Thread.report_on_exception = false
rescue
  puts("Thread.report_on_exception is unsupported")
end
STDOUT.sync = true

def start_thread(name, &block)
  Thread.new(name, block) do |name, block|
    begin
      puts("in #{name}")
      block.call
    rescue => e
      puts("rescue #{name}")
      raise e
    ensure
      puts("ensure #{name}")
    end
  end
end

begin
  puts("in main")
  # start_t1.join
  t1 = start_thread("1") do
    t2 = start_thread("2") do
      t3 = start_thread("3") do
        sleep(1)
        raise(StandardError, "foobar")
      end
      t3.join
    end
    t2.join
  end
  t1.join
rescue => e
  puts("rescue main")
  raise e
ensure
  puts("ensure main")
end
```

Basically, the `start_thread` method  creates a thread with its block wrapped in a `begin/rescue/ensure` block and 3 nested threads are created with the inner most "3" that raises an exception and all `rescue` and `ensure` blocked are traced. 

I will go ahead and list the different traces for different rubies:

### MRI Ruby 2.5.5

> ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-darwin18]

On MRI 2.5.5 I see 2 different behaviours:

- The first where every `rescue` and `ensure` are called:

```sh
in main
in 1
in 2
in 3
rescue 3
ensure 3
rescue 2
ensure 2
rescue main
rescue 1
ensure main
ensure 1
Traceback (most recent call last):
	1: from t.rb:13:in `block in start_thread'
t.rb:30:in `block (3 levels) in <main>': foobar (StandardError)
```

- The second where `rescue 1` does not happen.

```sh
in main
in 1
in 2
in 3
rescue 3
ensure 3
rescue main
rescue 2
ensure main
ensure 2
ensure 1
Traceback (most recent call last):
	1: from t.rb:13:in `block in start_thread'
t.rb:30:in `block (3 levels) in <main>': foobar (StandardError)
```

### JRuby 9.1.13.0 (logstash v6 up to 6.6.2)

> jruby 9.1.13.0 (2.3.3) 2017-09-06 8e1c115 Java HotSpot(TM) 64-Bit Server VM 25.144-b01 on 1.8.0_144-b01 +jit [darwin-x86_64]

 On JRuby 9.1.13.0 all `ensure` blocks are called but `rescue 1` and `rescue 2` are never called.

```
Thread.report_on_exception is unsupported
in main
in 1
in 2
in 3
rescue 3
ensure 3
ensure 2
ensure 1
rescue main
ensure main
StandardError: foobar
          block in t.rb at t.rb:30
  block in start_thread at t.rb:13
```

### JRuby 9.2.6.0 (logstash 6.7.0 and up)

> jruby 9.2.6.0 (2.5.3) 2019-02-11 15ba00b Java HotSpot(TM) 64-Bit Server VM 25.144-b01 on 1.8.0_144-b01 +jit [darwin-x86_64]

- On JRuby 9.2.6.0, `rescue main` is never called

```sh
in main
in 1
in 2
in 3
rescue 3
ensure 3
rescue 2
ensure 2
rescue 1
ensure 1
ensure main
StandardError: foobar
          t.rb at t.rb:30
  start_thread at t.rb:13
```

### Conclusion

I don't have a conclusion yet, I am still investigating and running more tests and see if anything else can influence the execution flow, in particular when joining thread or not.

IMO the expected behaviour would be to have all `rescue` and `ensure` blocks executed.

**Comment by headius** [comment]
I can reproduce your reported behavior on JRuby 9.2 master, although I did have at least one run that successfully fired all rescues and all ensures. There's still some non-determinism on 9.2, even though the result is closer to what we hope for.

I've looked at the `join` and `abort_on_exception` logic a bit.

When a thread shuts down due to an exception, it does two things in this order:

1. It sends an exception to the main thread if `abort_on_exception` is true.
2. It sets its own `exitingException` to that exception.

When code joins on a thread, it does the following, in this order:

1. It waits for the thread to terminate.
2. It checks if `exitingException` has been set for the thread, raising it directly if so.
3. It checks its own thread events.

The `exitingException` field and the fields used to publish thread events are all volatile, so I would expect them to be published by the time the thread has completed.

Unsure at the moment why the outermost `rescue` doesn't always fire.

**Comment by headius** [comment]
Aha, I think I might have it.

* Thread n bubbles out, puts a raise event on the main thread, and sets its exiting exception for join
* Thread n-1 joins, bubbles out, puts a raise event on the main thread, and sets its exiting exception for join
* ...
* Eventually we get back to the main thread calling join, which raises the exception we've been bubbling out.
* Because the join did not check thread events before `exitingException`, at some point in the future it will see those events and raise an additional time. This is likely happening just after entering the `rescue` block.

This would at least explain why the outer rescue gets missed. I do not have an explanation for the times where it fires.

From a looping version of the original script:

```
[] ~/projects/jruby $ jruby blah.rb
in main
in 1
in 2
in 3
rescue 3
ensure 3
rescue 2
ensure 2
rescue 1
ensure 1
rescue main
ensure main
in main
in 1
in 2
in 3
rescue 3
ensure 3
rescue 2
ensure 2
rescue 1
ensure 1
ensure main
StandardError: foobar
       blah.rb at blah.rb:29
  start_thread at blah.rb:13
```

**Comment by headius** [comment]
I can confirm that checking thread events before `exitingException` makes the script always work as expected, with all `rescue` and `ensure` blocks firing... ALMOST.

It takes many iterations but I do still see the outer rescue skipped sometimes with the following patch:

```diff
diff --git a/core/src/main/java/org/jruby/RubyThread.java b/core/src/main/java/org/jruby/RubyThread.java
index 42d3224f1f..14acb3a1a7 100644
--- a/core/src/main/java/org/jruby/RubyThread.java
+++ b/core/src/main/java/org/jruby/RubyThread.java
@@ -1149,6 +1149,10 @@ public class RubyThread extends RubyObject implements ExecutionContext {
             currentThread.exitSleep();
         }
 
+        // Check events before exitingException, to avoid triggering a later raise that should have fired now.
+        // See https://github.com/elastic/logstash/issues/10612
+        currentThread.pollThreadEvents(context);
+
         final Throwable exception = this.exitingException;
         if (exception != null) {
             if (exception instanceof RaiseException) {
@@ -1160,9 +1164,6 @@ public class RubyThread extends RubyObject implements ExecutionContext {
             Helpers.throwException(exception);
         }
 
-        // check events before leaving
-        currentThread.pollThreadEvents(context);
-
         if (threadImpl.isAlive()) {
             return context.nil;
         } else {
```

**Comment by headius** [comment]
Interesting output here:

```
in main
in 1
in 2
in 3
rescue 3
ensure 3
rescue 2
ensure 2
rescue 1ensure main

ensure 1
StandardError: foobar
       blah.rb at blah.rb:29
  start_thread at blah.rb:13
```

Again, there's some complex interaction of thread events, `abort_on_exception`, `join`, and `exitingException`. Also throw in that issuing the `raise` event to the main thread attempts to also interrupt whatever the main thread is doing. I'm not yet convinced this code can be made 100% reliable.

**Comment by headius** [comment]
A version of the script using `Thread.handle_interrupt` to defer the `abort_on_exception` raise events. This script runs exactly as you want on JRuby 9.2.6, 9.2.7, and CRuby 2.5.3 and 2.6.1.

```ruby
Thread.abort_on_exception = true
begin
  Thread.report_on_exception = false
rescue
  puts("Thread.report_on_exception is unsupported")
end
STDOUT.sync = true

def start_thread(name, &block)
  Thread.new(name, block) do |name, block|
    begin
      puts("in #{name}")
      block.call
    rescue => e
      puts("rescue #{name}")
      raise e
    ensure
      puts("ensure #{name}")
    end
  end
end

Thread.handle_interrupt(StandardError => :never) do
  begin
    puts("in main")
    t1 = start_thread("1") do
      t2 = start_thread("2") do
        t3 = start_thread("3") do
          sleep(0.01)
          raise(StandardError, "foobar")
        end
        t3.join
      end
      t2.join
    end
    t1.join
    Thread.handle_interrupt(StandardError => :immediate)
  rescue => e
    puts("rescue main")
  ensure
    puts("ensure main")
  end while true
end
```

Note an interesting behavioral difference: if the `while true` is moved to the last `end`, outside the `handle_interrupt` block, JRuby still runs forever while MRI raises immediately. I suspect they re-check the thread events on the tail end of that block invocation, which would be a bug in JRuby to not do the same.

**Comment by headius** [comment]
I think your best course of action at this point would be to bring this to a CRuby issue so we can all agree on what is expected behavior for the various edges here.
