### ISSUE TITLE
Unable to start Logstash throwing an ][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "" hasn't been registered>, :backtrace

### ISSUE THREAD

**Issue by Savagepony** [elastic/logstash#10625]
My system details: 

- logstash-6.5.4
- Operating System: RHEL 7
- Config File (if you have sensitive info, please remove it):
input {
     beats {
        port => 5044
        ${var: default value}

    }
}

filter {
  if [type] == "smaccess" {
    ## SiteMinder Policy Server Access logs
            grok {
                break_on_match => true
                match => ["message", "%{WORD:smeventcommand}%{SPACE}%{WORD:smeventserver}%{SPACE}\[%{HTTPDATE:smeventtimestamp}]%{SPACE}%{QUOTEDSTRING:smeventuser}%{SPACE}%{QUOTEDSTRING:smeventagent}%{SPACE}%{NOTSPACE}%{SPACE}%{NOTSPACE}%{SPACE}%{NOTSPACE}%{SPACE}%{GREEDYDATA:smeventmessage}"]
                match => ["message", "%{WORD:smeventcommand}%{SPACE}%{WORD:smeventserver}%{SPACE}\[%{HTTPDATE:smeventtimestamp}]%{SPACE}%{GREEDYDATA}"]

            }
            # Use date filter to plug the timestamp of the event into the timestamp used to post the message into ElasticSearch
            # SMACCESS smeventtimestamp format: 01/Jun/2015:08:36:40 -0500
            date {
               match => ["smeventtimestamp", "dd/MMM/YYYY:HH:mm:ss Z"]
            #   match => ["smeventtimestamp", "ISO8601"]
               timezone => "America/New_York"
               target => "@timestamp"
            }
  } else if [type] == "smps" {
    ## SiteMinder Policy Server logs
            #first pattern handle XPS based messages (extra field)
            #second pattern handles all other messages
            grok {
                match => ["message", "%{SYSLOG5424SD:smeventservicerequest}%{SYSLOG5424SD:smeventtimestamp}%{SYSLOG5424SD}%{SYSLOG5424SD}%{SYSLOG5424SD:smeventtype}%{SYSLOG5424SD:smeventsource}%{SPACE}%{GREEDYDATA:smeventmessage}"]
                match => ["message", "%{SYSLOG5424SD:smeventservicerequest}%{SYSLOG5424SD:smeventtimestamp}%{SYSLOG5424SD}%{SYSLOG5424SD:smeventtype}%{SYSLOG5424SD:smeventsource}%{SPACE}%{GREEDYDATA:smeventmessage}"]

            }
            # Use date filter to plug the timestamp of the event into the timestamp used to post the message into ElasticSearch
            # SMPS smeventtimestamp format: [Thu Jun 11 2015 20:10:36]
            date {
                match => ["smeventtimestamp", "[EEE MMM dd YYYY HH:mm:ss]"]
                timezone => "America/New_York"
                target => "@timestamp"
            }

            mutate {
                # remove all brakets from parsed fields
                gsub => ["smeventtimestamp", "\[|\]", ""]
                gsub => ["smeventsource", "\[|\]", ""]
                gsub => ["smeventtype", "\[|\]", ""]
                gsub => ["smeventcommand", "\[|\]", ""]
            }

  } else if [type] == "agent" {
    ## SiteMinder Application Web Agent logs (same as SMPS logs)
            grok {
                break_on_match => true
                match => ["message", "%{SYSLOG5424SD:smeventservicerequest}%{SYSLOG5424SD:smeventtimestamp}%{SYSLOG5424SD}%{SYSLOG5424SD:smeventtype}%{SYSLOG5424SD:smeventsource}%{SPACE}%{GREEDYDATA:smeventmessage}"]
                match => ["message", "%{SYSLOG5424SD:smeventservicerequest}%{SYSLOG5424SD:smeventtimestamp}%{SYSLOG5424SD}%{SYSLOG5424SD:smeventtype}%{SPACE}%{GREEDYDATA:smeventmessage}"]
                match => ["message", "%{SYSLOG5424SD:smeventservicerequest}%{SYSLOG5424SD:smeventtimestamp}%{SPACE}%{GREEDYDATA:smeventmessage}"]
            }

            # Use date filter to plug the timestamp of the event into the timestamp used to post the message into ElasticSearch
            # SMPS smeventtimestamp format: [Thu Jun 11 2015 20:10:36]
            date {
                match => ["smeventtimestamp", "[EEE MMM dd YYYY HH:mm:ss]"]
                # Presently the app servers and proxies (agents) are in the Central time zone
                # timezone => "America/New_York"
                timezone => "America/Chicago"
                target => "@timestamp"
            }

            mutate {
                # remove all brakets from parsed fields
                gsub => ["smeventtimestamp", "\[|\]", ""]
                gsub => ["smeventsource", "\[|\]", ""]
                gsub => ["smeventtype", "\[|\]", ""]
                gsub => ["smeventmessage", "\[|\]", ""]
            }

  } else if [type] == "agenttrace" {
    ## SiteMinder Application Web Agent Trace logs
            #drop the Header lines -
            #     NOTE: if columns listed in the WebAgentTrace.conf file changes, need to up the following drop filter and the grok filter.

if [message] == "[Date][Time][Pid][Tid][SrcFile][Function][TransactionID][IPAddr][IPPort][AgentName][Resource][User][Message]" or
               [message] == "[====][====][===][===][=======][========][=============][======][======][=========][========][====][=======]"
               {
                drop {}
            }

            grok {
                break_on_match => true
                match => ["message", "\[%{DATE:smeventdate}]\[%{TIME:smeventtime}]%{SYSLOG5424SD:smeventprocessid}%{SYSLOG5424SD:smeventtraceid}%{SYSLOG5424SD:smeventsrcfile}%{SYSLOG5424SD:smeventfunction}%{SYSLOG5424SD:smeventtranid}%{SYSLOG5424SD:smeventipaddress}%{SYSLOG5424SD:smeventport}%{SYSLOG5424SD:smeventagentname}%{SYSLOG5424SD:smeventresource}%{SYSLOG5424SD:smeventuser}%{SYSLOG5424SD:smeventmessage}"]
            }

            # Create a timestamp field from the smeventdate and smeventtime fields
            mutate {
                add_field => {
                   "smeventtimestamp" => "%{smeventdate} %{smeventtime}"
                }
            }

            mutate {
                # remove all brakets from parsed fields
                gsub => ["smeventprocessid", "\[|\]", ""]
                gsub => ["smeventtraceid", "\[|\]", ""]
                gsub => ["smeventsrcfile", "\[|\]", ""]
                gsub => ["smeventfunction", "\[|\]", ""]
                gsub => ["smeventtranid", "\[|\]", ""]
                gsub => ["smeventipaddress", "\[|\]", ""]
                gsub => ["smeventport", "\[|\]", ""]
                gsub => ["smeventagentname", "\[|\]", ""]
                gsub => ["smeventresource", "\[|\]", ""]
                gsub => ["smeventuser", "\[|\]", ""]
                gsub => ["smeventmessage", "\[|\]", ""]
            }

            # Use date filter to plug the new timestamp of the event into the timestamp used to post the message into ElasticSearch
            date {
                match => ["smeventtimestamp", "MM/dd/YYYY HH:mm:ss"]
                # Presently the app servers and proxies are in the Central time zone
                # timezone => "America/New_York"
                timezone => "America/Chicago"
                target => "@timestamp"

          }
  }
}

output {
#   if [type] == "smaccess" or [type] == "smps" {
#      elasticsearch {
#         hosts => localhost
#         index => "policyserver-%{+YYYY.MM.dd}"
#      }
#   } else if [type] == "agent" or [type] == "agenttrace" {
#      elasticsearch {
#         hosts => localhost
#         index => "agent-%{+YYYY.MM.dd}"
#      }
   if [type] == "smaccess" or [type] == "smps" or [type] == "agent" or [type] == "agenttrace" {
     stdout { codec => rubydebug }
         elasticsearch {
         hosts => localhost:9200
         index => "siteminder-%{+YYYY.MM.dd}"
      }
   } else {
      elasticsearch {
         hosts => localhost
      }
   }
}

- Sample Data:
- Steps to Reproduce: not really much steps to reproduce) this is while starting the logstash it would not start and throws the below error

[root@mrkdlvaiaas3701 bin]# ./logstash -f /etc/xuv0/apps/elk/logstash-6.5.4/config/Logstash_inputFilebeat.conf
Sending Logstash logs to /etc/xuv0/apps/elk/logstash-6.5.4/logs which is now configured via log4j2.properties
[2019-04-02T15:27:17,062][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "" hasn't been registered>, :backtrace=>["/etc/xuv0/apps/elk/logstash-6.5.4/logstash-core/lib/logstash/settings.rb:36:in `get_setting'", "/etc/xuv0/apps/elk/logstash-6.5.4/logstash-core/lib/logstash/settings.rb:69:in `set_value'", "/etc/xuv0/apps/elk/logstash-6.5.4/logstash-core/lib/logstash/settings.rb:88:in `block in merge'", "org/jruby/RubyHash.java:1343:in `each'", "/etc/xuv0/apps/elk/logstash-6.5.4/logstash-core/lib/logstash/settings.rb:88:in `merge'", "/etc/xuv0/apps/elk/logstash-6.5.4/logstash-core/lib/logstash/settings.rb:137:in `validate_all'", "/etc/xuv0/apps/elk/logstash-6.5.4/logstash-core/lib/logstash/runner.rb:278:in `execute'", "/etc/xuv0/apps/elk/logstash-6.5.4/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/etc/xuv0/apps/elk/logstash-6.5.4/logstash-core/lib/logstash/runner.rb:237:in `run'", "/etc/xuv0/apps/elk/logstash-6.5.4/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/etc/xuv0/apps/elk/logstash-6.5.4/lib/bootstrap/environment.rb:73:in `<main>'"]}
[2019-04-02T15:27:17,077][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit

Your help is appreciated.

Thanks

**Comment by Savagepony** [comment]
I resolved it, it needed a space after between one of the setting and its value. As the YAML doesn't recognize the structure. For example:

My setting previously was (issue occured)
path.logs:../elk/logs/logstash

Changed it to this (issue resolved) basically added a space after path.logs: 
path.logs: ../elk/logs/logstash

Thanks
