### ISSUE TITLE
"Test and exit" mode does not work with Java plugins

### ISSUE THREAD

**Issue by danhermann** [elastic/logstash#10843]
- Version: Logstash 6.8.0+
- Operating System: Any
- Steps to Reproduce:

Include any Java plugin such as `java_stdin` in a Logstash config file and invoke Logstash with the `-t` option. The following error is produced:

```
[2019-06-03T09:23:29,160][FATAL][logstash.runner          ] The given configuration is invalid. Reason: Cannot start the Java plugin 'java_stdin' in the Ruby execution engine. The Java execution engine is required to run Java plugins.
[2019-06-03T09:23:29,170][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```

**Comment by yehudagiv** [comment]
I encounter the exact same issue.
For some reason while filter constructor invoked it throw NPE while try to get the first configuration field.

Version: 7.0.1
OS: Mac OS X

stack trace:
java.lang.NullPointerException
	at org.logstash.plugins.ConfigurationImpl.get(ConfigurationImpl.java:38)
	at org.logstash.javaapi.AuthToken.<init>(AuthToken.java:86)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.logstash.plugins.PluginFactoryExt$Plugins.plugin(PluginFactoryExt.java:289)
	at org.logstash.plugins.PluginFactoryExt$Plugins.plugin(PluginFactoryExt.java:184)
	at usr.share.logstash.logstash_minus_core.lib.logstash.pipeline.RUBY$method$plugin$0(/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:71)

**Comment by danhermann** [comment]
@yehudagiv, that looks to me like a different problem. If you can supply some additional details about your filter plugin, I can look into it further.
