### ISSUE TITLE
Condition using double quotes does not work with Java execution

### ISSUE THREAD

**Issue by immon** [elastic/logstash#10842]
In LS 7.1.1 a config using `if` condition not using any comparison operator prevents LS to start.
In the example below the condition `if "[mytype][abc]"` triggers exception and does not allow LS to start. Other variants work: `if [mytype][abc]` or `if "[mytype][abc]" != ""`.
Disabling java exec mode with `--java-execution false` option is a workaround and all works as expected.

Pipeline config:
```
input {
    tcp {
        port => 12345
        codec => json
    }
}


filter {
    if "[mytype][abc]" {
        mutate {
            add_field => { "b" => 1 }
        }
    }
}

output {
    stdout {
        codec => rubydebug
    }
}
```
Error:
```
[2019-06-03T15:22:37,192][INFO ][logstash.javapipeline    ] Pipeline started {"pipeline.id"=>"test"}
warning: thread "[test]>worker0" terminated with exception (report_on_exception is true):
org.logstash.config.ir.compiler.EventCondition$Compiler$UnexpectedTypeException: Unexpected input type class org.logstash.config.ir.expression.ValueExpression
	at org.logstash.config.ir.compiler.EventCondition$Compiler.truthy(org/logstash/config/ir/compiler/EventCondition.java:193)
	at org.logstash.config.ir.compiler.EventCondition$Compiler.buildCondition(org/logstash/config/ir/compiler/EventCondition.java:101)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.lambda$compileDependencies$4(org/logstash/config/ir/CompiledPipeline.java:388)
	at java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)
	at java.util.stream.ReferencePipeline$2$1.accept(java/util/stream/ReferencePipeline.java:177)
	at java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)
	at java.util.Iterator.forEachRemaining(java/util/Iterator.java:133)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(java/util/Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java/util/stream/ReduceOps.java:913)
	at java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(java/util/stream/ReferencePipeline.java:511)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.compileDependencies(org/logstash/config/ir/CompiledPipeline.java:400)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.flatten(org/logstash/config/ir/CompiledPipeline.java:361)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.filterDataset(org/logstash/config/ir/CompiledPipeline.java:287)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.lambda$compileDependencies$4(org/logstash/config/ir/CompiledPipeline.java:379)
	at java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)
	at java.util.stream.ReferencePipeline$2$1.accept(java/util/stream/ReferencePipeline.java:177)
	at java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)
	at java.util.Iterator.forEachRemaining(java/util/Iterator.java:133)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(java/util/Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java/util/stream/ReduceOps.java:913)
	at java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(java/util/stream/ReferencePipeline.java:511)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.compileDependencies(org/logstash/config/ir/CompiledPipeline.java:400)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.flatten(org/logstash/config/ir/CompiledPipeline.java:361)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.lambda$compile$1(org/logstash/config/ir/CompiledPipeline.java:270)
	at java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:195)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(java/util/ArrayList.java:1494)
	at java.util.stream.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:484)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:474)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(java/util/stream/ReduceOps.java:913)
	at java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(java/util/stream/ReferencePipeline.java:511)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.compile(org/logstash/config/ir/CompiledPipeline.java:271)
	at org.logstash.config.ir.CompiledPipeline$CompiledExecution.<init>(org/logstash/config/ir/CompiledPipeline.java:251)
	at org.logstash.config.ir.CompiledPipeline.buildExecution(org/logstash/config/ir/CompiledPipeline.java:103)
	at org.logstash.execution.WorkerLoop.<init>(org/logstash/execution/WorkerLoop.java:46)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(jdk/internal/reflect/NativeConstructorAccessorImpl.java:62)
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(jdk/internal/reflect/DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:488)
	at org.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/JavaConstructor.java:247)
	at org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:915)
	at org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)
	at home.imo.Cases.tmp.logstash_minus_7_dot_1_dot_1.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/home/imo/Cases/tmp/logstash-7.1.1/logstash-core/lib/logstash/java_pipeline.rb:235)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:295)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:270)
	at java.lang.Thread.run(java/lang/Thread.java:844)
```

Tested on Ubuntu 18.04, java 9.0.4

---
The above is minimal config to reproduce the issue.
I observed other symptoms when LS monitoring and `xpack.monitoring.collection.pipeline.details` are enabled. I tried a config like below, where there are two `if` conditions nested, an outer is correct, and the inner is problematic.

```
filter {
    if "[mytype][abc]" == "abc" {
        if "[xyz][abc]" {
            mutate {
                add_field => { "b" => 711 }
            } 
        }
    }
}
```

LS starts with this configuration however the error message like below is logged. This is because monitoring endpoint at `localhost:9600/_node/stats/pipelines?pretty` returns an output with null `reloads` field.

Error logged:
```
[2019-06-03T15:48:39,415][ERROR][logstash.inputs.metrics  ] Failed to create monitoring event {:message=>"undefined method `[]' for nil:NilClass", :error=>"NoMethodError", :backtrace=>["/home/imo/Cases/tmp/logstash-7.1.1/x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb:23:in `block in format_pipelines_info'", "org/jruby/RubyHash.java:1419:in `each'", "org/jruby/RubyEnumerable.java:833:in `map'", "/home/imo/Cases/tmp/logstash-7.1.1/x-pack/lib/monitoring/inputs/metrics/stats_event/pipelines_info.rb:12:in `format_pipelines_info'", "/home/imo/Cases/tmp/logstash-7.1.1/x-pack/lib/monitoring/inputs/metrics/stats_event_factory.rb:22:in `make'", "/home/imo/Cases/tmp/logstash-7.1.1/x-pack/lib/monitoring/inputs/metrics.rb:116:in `update_stats'", "/home/imo/Cases/tmp/logstash-7.1.1/x-pack/lib/monitoring/inputs/metrics.rb:108:in `update'", "/home/imo/Cases/tmp/logstash-7.1.1/x-pack/lib/monitoring/inputs/metrics.rb:62:in `block in configure_snapshot_poller'", "/home/imo/Cases/tmp/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'", "com/concurrent_ruby/ext/SynchronizationLibrary.java:232:in `synchronize'", "/home/imo/Cases/tmp/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'", "/home/imo/Cases/tmp/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/timer_task.rb:312:in `execute_task'", "/home/imo/Cases/tmp/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:24:in `block in execute'", "com/concurrent_ruby/ext/SynchronizationLibrary.java:232:in `synchronize'", "/home/imo/Cases/tmp/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/safe_task_executor.rb:19:in `execute'", "/home/imo/Cases/tmp/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/ivar.rb:169:in `safe_execute'", "/home/imo/Cases/tmp/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/scheduled_task.rb:285:in `process_task'", "/home/imo/Cases/tmp/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/timer_set.rb:166:in `block in process_tasks'", "/home/imo/Cases/tmp/logstash-7.1.1/vendor/bundle/jruby/2.5.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/java_executor_service.rb:85:in `run'"]}
```

Monitoring endpoint output:
```
{
  "host" : "lake",
  "version" : "7.1.0",
  "http_address" : "127.0.0.1:9600",
  "id" : "6ec1b551-1b55-432d-ace9-339fa4f68e04",
  "name" : "lake",
  "pipelines" : {
    "test" : {
      "events" : {
        "filtered" : 0,
        "out" : 0,
        "duration_in_millis" : 0,
        "queue_push_duration_in_millis" : 0,
        "in" : 0
      },
      "plugins" : {
        "inputs" : [ {
          "id" : "419b64a7a6593542859054bd1a7a7f4f4381bf15818ee0613837d6ecc11b0e90",
          "name" : "tcp",
          "events" : {
            "out" : 0,
            "queue_push_duration_in_millis" : 0
          }
        } ],
        "filters" : [ {
[...]
        } ]
      },
      "reloads" : null,
      "queue" : {
        "type" : "memory"
      }
    },
```

**Comment by yaauie** [comment]
While this shouldn't cause a hard crash, it almost certainly isn't doing what you are expecting; quoted values are _string literals_, not _field references_.

The following tests the hard-coded string value `[mytype][abc]`, which is not a sensible stand-alone clause.

~~~
if "[mytype][abc]" {
~~~

Additionally, it doesn't particularly make sense to compare two hard-coded strings to each other either:

~~~
if "[mytype][abc]" == "abc" {
~~~

Here we are testing the literal hard-coded string value `[mytype][abc]` against the literal hard-coded string value `abc` for equality, which will never be true (the string `[mytype][abc]` is not equal to the string `abc`).

***

If we are looking to test the event's contents in field `[mytype][abc]` for equality with the hard-coded string `abc`, we would do:

~~~
if [mytype][abc] == "abc" {
~~~

***

If we are looking to test the event's contents in field `[mytype][abc] against its contents in field `abc`, we would do:

~~~
if [mytype][abc] == [abc] {
~~~

***

Separately,
