### ISSUE TITLE
`pipelines.yml` without flattened keys fails to load

### ISSUE THREAD

**Issue by nkakouros** [elastic/logstash#10879]
- Version: 7.1.1
- Operating System: Ubuntu 18.04
- Config File (if you have sensitive info, please remove it):

`logstash.yml`
```
---
http:
  host: 127.0.0.1
  port: 9600
node:
  name: earth-elk
```

`pipelines.yml`
```
---
- pipeline:
     id: main
  path:
    config: '/etc/logstash/conf.d/beat-input.conf'
```

- Sample Data: ~
- Steps to Reproduce:

The two files are created and placed under `/etc/logstash/` using ansible dicts and tasks. When I do `systemctl restart logstash`, then `journalctl -u logstash` shows:

```
Jun 20 19:12:45 earth-elk logstash[26415]: Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
Jun 20 19:12:46 earth-elk logstash[26415]: [2019-06-20T19:12:46,278][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.1.1"}
Jun 20 19:12:47 earth-elk logstash[26415]: [2019-06-20T19:12:47,425][ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>ArgumentError, :message=>"Setting \"pipeline\" hasn't been registered", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:36:in `get_setting'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:69:in `set_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `block in merge'", "org/jruby/RubyHash.java:1419:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:88:in `merge'", "/usr/share/logstash/logstash-core/lib/logstash/config/source/multi_local.rb:18:in `block in pipeline_configs'", "org/jruby/RubyArray.java:2577:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/config/source/multi_local.rb:17:in `pipeline_configs'", "/usr/share/logstash/logstash-core/lib/logstash/config/source_loader.rb:61:in `block in fetch'", "org/jruby/RubyArray.java:2572:in `collect'", "/usr/share/logstash/logstash-core/lib/logstash/config/source_loader.rb:60:in `fetch'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:148:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:96:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
Jun 20 19:12:47 earth-elk logstash[26415]: [2019-06-20T19:12:47,442][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>RuntimeError, :message=>"Could not fetch the configuration, message: Setting \"pipeline\" hasn't been registered", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/agent.rb:155:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:96:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
Jun 20 19:12:47 earth-elk logstash[26415]: [2019-06-20T19:12:47,882][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
Jun 20 19:12:52 earth-elk logstash[26415]: [2019-06-20T19:12:52,657][INFO ][logstash.runner          ] Logstash shut down.
```

If I convert `pipelines.yml` to:

```
---

- pipeline.id: main
  path.config: '/etc/logstash/conf.d/beat-input.conf'
```

then logstash start successfully. 

I know that the documentation only has examples with flattened keys but this is a `yml` file and, I think, it should support normal yaml syntax.

**Comment by yaauie** [comment]
This is currently by design.

The [YAML specification](https://yaml.org/spec/1.2/spec.html) contains no specification for using dots in field names as a short-hand for nested objects, and this project makes no attempt to add this behaviour on top of the YAML documents that it parses.

The keys required in these yaml files are literally the strings specified in documentation and example configurations, and although there may be some commonality in prefix for organisational purposes, any attempt to infer structure that is not present is not guaranteed to work.
