### ISSUE TITLE
Deploying a pipeline configuration causes confusing and nonsensical errors

### ISSUE THREAD

**Issue by AnInanimateCarbonRod** [elastic/logstash#10896]
I have been trying to deploy Logstash in a Docker container via Compose. The below is the relevant portion of my Compose file, note that I am bind mounting a host directory to completely replace the `/usr/share/logstash/pipeline` directory with my own configuration as specified in [the documentation](https://www.elastic.co/guide/en/logstash/6.6/docker-config.html).

```
version: '3.3'
services:
  logstash:
    build:
      context: ./opt/docker/logstash
    volumes:
      - ./modules/logstash:/usr/share/logstash/pipeline:ro
    depends_on:
      - elasticsearch
      - rabbitmq
      - mongodb
```

The host directory contains three files, a `pipelines.yml` config:

```
- pipeline.id: first
  path.config: "/usr/share/logstash/pipeline/first.conf"
- pipeline.id: second
  path.config: "/usr/share/logstash/pipeline/second.conf"
```

And two configuration files, `first.conf`:

```
input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch"
    index => "my-index"
  }
}
```

`second.conf`:

```
input {
  rabbitmq {
    host => "rabbitmq"
    queue => "logstash-queue"
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  mongodb {
    uri => "mongodb://mongodb"
    collection => "logs"
    database => "logs"
  }
}
```

When performing `docker-compose up`, Logstash fails to start:

```
logstash_1             | Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
logstash_1             | [2019-03-06T13:13:43,127][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/usr/share/logstash/data/queue"}
logstash_1             | [2019-03-06T13:13:43,143][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/usr/share/logstash/data/dead_letter_queue"}
logstash_1             | [2019-03-06T13:13:43,965][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.6.1"}
logstash_1             | [2019-03-06T13:13:44,017][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"05111c59-04fb-49ad-8238-7a644db27eb4", :path=>"/usr/share/logstash/data/uuid"}
logstash_1             | [2019-03-06T13:13:44,976][WARN ][logstash.monitoringextension.pipelineregisterhook] xpack.monitoring.enabled has not been defined, but found elasticsearch configuration. Please explicitly set `xpack.monitoring.enabled: true` in logstash.yml
logstash_1             | [2019-03-06T13:13:46,446][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elasticsearch:9200/]}}
logstash_1             | [2019-03-06T13:13:46,966][WARN ][logstash.licensechecker.licensereader] Restored connection to ES instance {:url=>"http://elasticsearch:9200/"}
logstash_1             | [2019-03-06T13:13:47,095][INFO ][logstash.licensechecker.licensereader] ES Output version determined {:es_version=>6}
logstash_1             | [2019-03-06T13:13:47,102][WARN ][logstash.licensechecker.licensereader] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type{:es_version=>6}
logstash_1             | [2019-03-06T13:13:47,315][INFO ][logstash.monitoring.internalpipelinesource] Monitoring License OK
logstash_1             | [2019-03-06T13:13:47,318][INFO ][logstash.monitoring.internalpipelinesource] Validated license for monitoring. Enabling monitoring pipeline.
logstash_1             | [2019-03-06T13:13:48,169][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, input, filter, output at line 15, column 1 (byte 176) after ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:149:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:22:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:43:in `block in execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:94:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:94:in `exclusive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:39:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:327:in `block in converge_state'"]}
logstash_1             | [2019-03-06T13:13:48,463][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, input, filter, output at line 15, column 1 (byte 176) after ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:149:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:22:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:43:in `block in execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:94:in `block in exclusive'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:94:in `exclusive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:39:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:327:in `block in converge_state'"]}
logstash_1             | [2019-03-06T13:13:53,277][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"document_type", :plugin=><LogStash::Outputs::ElasticSearch bulk_path=>"/_xpack/monitoring/_bulk?system_id=logstash&system_api_version=2&interval=1s", hosts=>[http://elasticsearch:9200], sniffing=>false, manage_template=>false, id=>"51f66c9ec66feb8fd59be1157c335c1ddc5fb856d2b248254ae6add289cea7b7", document_type=>"%{[@metadata][document_type]}", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_f98631f6-a740-4706-b2e3-7fa50d8a40f4", enable_metric=>true, charset=>"UTF-8">, workers=>1, template_name=>"logstash", template_overwrite=>false, doc_as_upsert=>false, script_type=>"inline", script_lang=>"painless", script_var_name=>"event", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, ilm_enabled=>false, ilm_rollover_alias=>"logstash", ilm_pattern=>"{now/d}-000001", ilm_policy=>"logstash-policy", action=>"index", ssl_certificate_verification=>true, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>}
logstash_1             | [2019-03-06T13:13:53,345][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>".monitoring-logstash", "pipeline.workers"=>1, "pipeline.batch.size"=>2, "pipeline.batch.delay"=>50}
logstash_1             | [2019-03-06T13:13:53,442][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elasticsearch:9200/]}}
logstash_1             | [2019-03-06T13:13:53,482][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://elasticsearch:9200/"}
logstash_1             | [2019-03-06T13:13:53,492][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>6}
logstash_1             | [2019-03-06T13:13:53,493][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}
logstash_1             | [2019-03-06T13:13:53,521][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["http://elasticsearch:9200"]}
logstash_1             | [2019-03-06T13:13:53,615][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>".monitoring-logstash", :thread=>"#<Thread:0x77775 run>"}
logstash_1             | [2019-03-06T13:13:54,067][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
```

The container exits after the last line. The same configuration (with directories modified in the pipelines.yml file to correctly point to the configuration files) works fine on the host (macOS 10.14.3) with Logstash 6.6.1. If I bind-mount the configuration elsewhere (so Logstash starts in the container with the default configuration and does not immediately exit), I can run Logstash within the container with the `-f` parameter pointing to each configuration file, ruling out an actual configuration issue. I did note that the error references the default 'main' pipeline which should not be configured in my setup (or, at least the documentation suggests this):

```
:action=>LogStash::PipelineAction::Create/pipeline_id:main
```

The content of the error message is not useful at all:

```
Expected one of #, input, filter, output at line 15, column 1 (byte 176) after 
```

Only one of the files (`second.conf`) has enough lines for a line 15 to be relevant, and that line 15 is `output {`, one of the directives the error specifies is expected but missing.

Is there configuration that's missing or invalid here causing this issue that isn't documented or not in line with what the documentation suggests? Additionally, I think this error message needs to be improved significantly as it is impossible to understand what exactly is the issue. I've given up on pipelining for now and have returned to a single configuration using tags and if-conditions to separate logic, which does work.

**Comment by lukaszbulak** [comment]
Hi, 
I faced very similar issue, when declared volumes: pipeline to /usr/share/logstash/pipeline/, and pipelines.yml to /usr/share/logstash/pipelines.yml.

The solution was to declare pipelines.yml just where it was expected, i.e. to /usr/share/logstash/config/pipelines.yml. Then it worked as expected, there was separate pipelines working.

**Comment by gangofnuns** [comment]
As a follow up, the following two lines from debugging output may be a clue: 

```
[2020-02-16T18:21:52,583][WARN ][logstash.monitoringextension.pipelineregisterhook] xpack.monitoring.enabled has not been defined, but found elasticsearch configuration. Please explicitly set `xpack.monitoring.enabled: true` in logstash.yml
[2020-02-16T18:21:53,359][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://elasticsearch:9200/]}}
```

It seems like my logstash.yml file, which is under /etc/logstash/conf.d, is somehow being disregarded.
