### ISSUE TITLE
Logstash health api fails when heavy load comes

### ISSUE THREAD

**Issue by jenishshah671993** [elastic/logstash#11024]
Hi Team,

Health API start giving error cannot fetch configuration when load on logstash increased.

Can you provide a workaround for this situation

**Comment by burghategaurao** [comment]
We are getting below Error when calling health api for pipelines.
With Normal processing load, Health API works. But in case of heave load on logstash, we get below error.

 Internal API server error {:status=>500, :request_method=>"GET", :path_info=>"//_node/stats/pipelines", :query_string=>"pretty", :http_version=>"HTTP/1.1", :http_accept=>nil, :error=>"Unexpected Internal Error", :class=>"LogStash::Instrument::MetricStore::MetricNotFound", :message=>"For path: events. Map keys: [:reloads]", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:225:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/usr/share/logstash/logstash-core/lib/logstash/instrument/metric_store.rb:235:in `block in get_recursively'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/lo
