### ISSUE TITLE
Unable to restart the non-running pipeline

### ISSUE THREAD

**Issue by derekha2010** [elastic/logstash#11034]
Hi all

I'm going to use multiple pipeline feature. In some cases, I would like to stop a pipeline for maintenance purpose. In multiple pipeline guide, it state that it can stop/resume pipeline by editing pipeline.yml. I've tried this feature in my environment and I can confirm that it can stop the pipeline correctly when I comment out the pipeline. However, when I try to un-comment the pipeline, it cannot resume unless I change the pipeline config. It seems that this behavior is not expected, at least for me.

- Version: Logstash 6.8.2
- Operating System: CentOS Linux release 7.6.1810 (Core)
- Config File:
```
pipeline.yml:
 - pipeline.id: test1
   path.config: "/tmp/test1.conf"
 - pipeline.id: test2
   path.config: "/tmp/test2.conf"

test1.conf:
input {beats {port => 5044}} output {stdout{}}

test2.conf:
input {beats {port => 5045}} output {stdout{}}
```
- Steps to Reproduce:

run logstash with auto reload feature
```
bash> ./logstash -r

logstash-plain.log:
[2019-08-02T21:52:11,075][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.8.2"}
[2019-08-02T21:52:25,436][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"test1", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2019-08-02T21:52:26,570][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"test2", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2019-08-02T21:52:27,738][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2019-08-02T21:52:27,777][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5045"}
[2019-08-02T21:52:27,856][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"test2", :thread=>"#<Thread:0xeb0be7f run>"}
[2019-08-02T21:52:27,884][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"test1", :thread=>"#<Thread:0x4f520493 run>"}
[2019-08-02T21:52:28,102][INFO ][logstash.agent           ] Pipelines running {:count=>2, :running_pipelines=>[:test1, :test2], :non_running_pipelines=>[]}
[2019-08-02T21:52:28,301][INFO ][org.logstash.beats.Server] Starting server on port: 5044
[2019-08-02T21:52:28,306][INFO ][org.logstash.beats.Server] Starting server on port: 5045
[2019-08-02T21:52:28,998][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
```
It successfully started 2 pipeline as expected. Now I comment out one of the pipeline for maintenance.
```
pipeline.yml:
# - pipeline.id: test1
#   path.config: "/tmp/test1.conf"
 - pipeline.id: test2
   path.config: "/tmp/test2.conf"
   
logstash-plain.log:
[2019-08-02T21:52:51,586][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{"other"=>[{"thread_id"=>27, "name"=>"[test1]<beats", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/logstash-input-beats-5.1.8-java/lib/logstash/inputs/beats.rb:212:in `run'"}, {"thread_id"=>23, "name"=>"[test1]>worker0", "current_call"=>"[...]/logstash-core/lib/logstash/pipeline.rb:333:in `read_batch'"}]}}
[2019-08-02T21:52:51,588][ERROR][org.logstash.execution.ShutdownWatcherExt] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2019-08-02T21:52:52,872][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"test1", :thread=>"#<Thread:0x4f520493 run>"}
[2019-08-02T21:52:52,911][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:test2], :non_running_pipelines=>[:test1]}
```
Very good, pipeline test1 stopped. After maintenance, I would like to resume the pipeline by un-comment the target pipeline
```
pipeline.yml:
 - pipeline.id: test1
   path.config: "/tmp/test1.conf"
 - pipeline.id: test2
   path.config: "/tmp/test2.conf"
   
logstash-plain.log:
(nothing change)
```
Nothing happened in the log file, the pipeline test1 cannot resume as expected.

I tired something more, if I edit path.config of test1
```
pipeline.yml:
 - pipeline.id: test1
   path.config: "//tmp/test1.conf"
 - pipeline.id: test2
   path.config: "/tmp/test2.conf"

logstash-plain.log:   
[2019-08-02T21:53:47,268][INFO ][logstash.pipelineaction.reload] Reloading pipeline {"pipeline.id"=>:test1}
[2019-08-02T21:53:47,452][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"test1", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2019-08-02T21:53:47,500][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2019-08-02T21:53:47,509][INFO ][org.logstash.beats.Server] Starting server on port: 5044
[2019-08-02T21:53:47,510][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"test1", :thread=>"#<Thread:0x53c5b5be run>"}
[2019-08-02T21:53:47,546][INFO ][logstash.agent           ] Pipelines running {:count=>2, :running_pipelines=>[:test1, :test2], :non_running_pipelines=>[]}
```
It did the trick. Pipeline test1 start again!

However, what I expect is logstash will start the pipeline again when I un-comment the pipeline. I'm thinking this is a bug or not.

Thanks

**Comment by jsvd** [comment]
This is indeed a bug, it seems that, because the configuration of the pipeline didn't change, then it is ignored, and we don't flip the status of the pipeline back to online. Thanks for the report!

**Comment by Transrian** [comment]
Agree, tested and replicated on Logstash 6.8.x and 7.3.x, and it is really annoying in the case of there's lots of pipeline changes

**Comment by insukcho** [comment]
I hit the same bug on this issue. Any progress or plan to fix it?

**Comment by percygrunwald** [comment]
Can confirm that we are seeing the same behavior in `logstash 7.4.2`, a fix would be greatly appreciated.

**Comment by cameronkerrnz** [comment]
Still an issue with 7.10.2. It is particularly relevant when a pipeline is shutdown due to downstream systems being unavailable. In my case, I couldn't write to Kafka because Schema Registry wasn't accepting connections at the time when Logstash was started at boot.

I can also report the following clarification:

It is not enough to touch the pipelines.yml, _or_ simply to touch a conf.d/ file; you need to actually change the content (eg. 'echo >> ..../conf.d/example.conf')

But even then you only get:

```
[INFO ] 2021-02-23 16:43:11.411 [Converge PipelineAction::Reload<main>] reload - Reloading pipeline {"pipeline.id"=>:main}
```

... which is *not* enough, it seems, to get the input restarted (in this case, I am expecting the Beats port 5044 to start again, but no such luck).

**Comment by cameronkerrnz** [comment]
Currently I'm working around this kind of issue using the follow cron task that runs every couple of minutes. This does make the assumption that you are using systemd and that you have logstash logs being swallowed by journald (my deployment _is_ different to a default one), so you might need to just use a `systemctl -q is-active logstash.service && tail -1 /var/log/logstash/.... | grep -q ... && systemctl restart logstash` instead

`systemctl -q is-active logstash.service && journalctl -n1 -u logstash.service | grep -q 'javapipeline - Pipeline terminated' && systemctl restart logstash`
