### ISSUE TITLE
xpack cannot be disabled

### ISSUE THREAD

**Issue by Kegsay** [elastic/logstash#11094]
- Version: 7.3.0
- Operating System: Mac (Sierra)
- Config File (if you have sensitive info, please remove it):
```
input {
 file {
  path => "/redacted/file.xml"
  start_position => beginning
  codec => multiline
  {
   pattern => "^<\?xmldata .*\>"
   negate => true
   what => "previous"
  }
 }
}

filter {
  xml {
   store_xml => false
   source => "message"
   xpath =>
   [
    "/Event@Id/text()", "event_id",
   ]
  }
}

output {
    stdout { codec => rubydebug }
    elasticsearch {
        codec => json
        index => "logstash-xml"
        hosts => ["https://redacted.eu-west-1.es.amazonaws.com:443/"]
        document_id => "%{[event_story_id]}"
        document_type => "xmlfiles"
    }
}
```

- Steps to Reproduce:
  * Start an AWS ES instance (which doesn't support xpack)
  * `brew install logstash`
  * Try to insert a file, produces the error:
```
[2019-08-29T11:28:41,451][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>7}
[2019-08-29T11:28:41,455][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2019-08-29T11:28:41,479][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://redacted.eu-west-1.es.amazonaws.com:443/"]}
[2019-08-29T11:28:41,561][INFO ][logstash.outputs.elasticsearch] Using default mapping template
[2019-08-29T11:28:41,637][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Got response code '401' contacting Elasticsearch at URL 'https://redacted.eu-west-1.es.amazonaws.com:443/_xpack'", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError", :backtrace=>["/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80:in `perform_request'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:291:in `perform_request_to_url'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:278:in `block in perform_request'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:373:in `with_connection'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:277:in `perform_request'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:285:in `block in Pool'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:162:in `get'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:378:in `get_xpack_info'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/ilm.rb:57:in `ilm_ready?'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/ilm.rb:28:in `ilm_in_use?'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/template_manager.rb:14:in `install_template'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/common.rb:130:in `install_template'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/common.rb:51:in `block in setup_after_successful_connection'"]}
warning: thread "Ruby-0-Thread-5: :1" terminated with exception (report_on_exception is true):
LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError: Got response code '401' contacting Elasticsearch at URL 'https://redacted.eu-west-1.es.amazonaws.com:443/_xpack'
                    perform_request at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80
             perform_request_to_url at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:291
                    perform_request at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:278
                    with_connection at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:373
                    perform_request at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:277
                               Pool at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:285
                                get at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:162
                     get_xpack_info at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:378
                         ilm_ready? at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/ilm.rb:57
                        ilm_in_use? at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/ilm.rb:28
  setup_after_successful_connection at /usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/common.rb:52
[2019-08-29T11:28:41,812][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError: LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError>, :backtrace=>["/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:80:in `perform_request'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:291:in `perform_request_to_url'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:278:in `block in perform_request'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:373:in `with_connection'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:277:in `perform_request'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:285:in `block in Pool'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:162:in `get'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client.rb:378:in `get_xpack_info'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/ilm.rb:57:in `ilm_ready?'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/ilm.rb:28:in `ilm_in_use?'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/common.rb:52:in `block in setup_after_successful_connection'"]}
[2019-08-29T11:28:41,876][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```

Why is logstash trying to insert xpack templates? Trying to disable xpack in logstash via:
```
xpack.monitoring.enabled: false
```
produces the following:
```
$ logstash -f logstash-xml.conf

Thread.exclusive is deprecated, use Thread::Mutex
Sending Logstash logs to /usr/local/Cellar/logstash/7.3.0/libexec/logs which is now configured via log4j2.properties
[2019-08-29T11:32:37,411][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.enabled" hasn't been registered>, :backtrace=>["/usr/local/Cellar/logstash/7.3.0/libexec/logstash-core/lib/logstash/settings.rb:36:in `get_setting'", "/usr/local/Cellar/logstash/7.3.0/libexec/logstash-core/lib/logstash/settings.rb:69:in `set_value'", "/usr/local/Cellar/logstash/7.3.0/libexec/logstash-core/lib/logstash/settings.rb:88:in `block in merge'", "org/jruby/RubyHash.java:1419:in `each'", "/usr/local/Cellar/logstash/7.3.0/libexec/logstash-core/lib/logstash/settings.rb:88:in `merge'", "/usr/local/Cellar/logstash/7.3.0/libexec/logstash-core/lib/logstash/settings.rb:137:in `validate_all'", "/usr/local/Cellar/logstash/7.3.0/libexec/logstash-core/lib/logstash/runner.rb:283:in `execute'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/local/Cellar/logstash/7.3.0/libexec/logstash-core/lib/logstash/runner.rb:242:in `run'", "/usr/local/Cellar/logstash/7.3.0/libexec/vendor/bundle/jruby/2.5.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/local/Cellar/logstash/7.3.0/libexec/lib/bootstrap/environment.rb:73:in `<main>'"]}
[2019-08-29T11:32:37,426][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```

**Comment by apoliukh** [comment]
Seems like logstash - 6.8.X is the last version that supports sending to AWS ES. Started from version >7.X, Elastic added logic that prevent you from using AWS ES with Elastic products, as you unable to install x-pack to AWS ES. Due to license requirement [you will never see x-pack on AWS ES](https://forums.aws.amazon.com/message.jspa?messageID=873098#874980)

You can try to use other plugin in your output - https://github.com/awslabs/logstash-output-amazon_es. It could help.

**Comment by mordowiciel** [comment]
@pol-alex Could you please elaborate more on this subject? I've browsed through release notes and breaking changes of Logstash/Elasticsearch 7.x and didn't find any info concerning default XPack monitoring being enabled, and being impossible for it to be removed/disabled.

**Comment by yaauie** [comment]
First, a workaround: when running the default distribution of Logstash, it is possible to use only OSS-licensed features by exporting `OSS=true` environment variable.

****

It looks like you have hit a bug with the Elasticsearch Output Plugin, in which an Elastic-licensed Logstash is _erroring_ while checking for the downstream Elasticsearch's license. Under Logstash 7.x this is supposed to be a _WARN_ situation, so I will file a bug on the plugin and follow up shortly.

**Comment by manelpb** [comment]
We fixed this by adding this to the elasticsearch output
 ```ilm_enabled => false```

**Comment by azin634** [comment]
I'm running into this even though I'm using the logstash-oss docker image

**Comment by scrisenbery** [comment]
@yaauie Based on what you say it sounds like the OSS distribution should not have this issue at all, but I run into the issue on the OSS Docker image like @azin634 (and also on OSS distribution of the Beats, see https://github.com/elastic/beats/issues/8086). I don't see why the OSS distribution even checks for X-Pack since the point of using the OSS distribution is not to have those features.

I can confirm that the workaround that @manelpb posted works for the OSS docker image, though.

**Comment by azin634** [comment]
It does seem like a bug with the ilm feature. I can confirm disabling ilm worked for me as well.

**Comment by onlydole** [comment]
Thank you so much, @manelpb! That saved my bacon 🥓 😄

**Comment by erniechapman** [comment]
Confirmed that this workaround allows you to proceed with the ingestion.  Thanks!

**Comment by gibati** [comment]
> `ilm_enabled => false`

Thanks for you help @manelpb , its really works.

**Comment by liam102** [comment]
> We fixed this by adding this to the elasticsearch output
> `ilm_enabled => false`

Give this man an OSCAR!!! Thanks @manelpb! You made my day!

**Comment by ldormoy** [comment]
Let's note that default Logstash will soon be incompatible with AWS Elasticsearch anyway, so the OSS tip from @yaauie makes sense:

> DEPRECATION WARNING: Connecting to an OSS distribution of Elasticsearch using the default distribution of Logstash will stop working in Logstash 8.0.0. Please upgrade to the default distribution of Elasticsearch, or use the OSS distribution of Logstash

**Comment by nikolas** [comment]
I got this working by adding this to my `filebeat.yml`:
```
setup.ilm:
  enabled: false
```

**Comment by cmkim** [comment]
> We fixed this by adding this to the elasticsearch output
> `ilm_enabled => false`

Thank you very much!

**Comment by raymondsugiarto** [comment]
> We fixed this by adding this to the elasticsearch output
> `ilm_enabled => false`

@manelpb Thanks you, its great

**Comment by changhyuni** [comment]
> We fixed this by adding this to the elasticsearch output
> `ilm_enabled => false`

thanks you !!
