### ISSUE TITLE
NoMethodError: undefined method `new' for :@via:Symbol

### ISSUE THREAD

**Issue by chrissound** [elastic/logstash#11095]
`logstash-6.5.1` (according to the systemd unit file)

```
[root@XenonKiloCranberry:~]# cat /etc/os-release 
NAME=NixOS
ID=nixos
VERSION="18.09.2574.a7e559a5504 (Jellyfish)"
VERSION_CODENAME=jellyfish
VERSION_ID="18.09.2574.a7e559a5504"
PRETTY_NAME="NixOS 18.09.2574.a7e559a5504 (Jellyfish)"
HOME_URL="https://nixos.org/"
SUPPORT_URL="https://nixos.org/nixos/support.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"

[root@XenonKiloCranberry:~]# uname -a
Linux XenonKiloCranberry 4.14.118 #1-NixOS SMP Fri May 10 15:53:15 UTC 2019 x86_64 GNU/Linux
```

```
Aug 29 12:45:54 XenonKiloCranberry logstash[10669]: [ERROR] 2019-08-29 12:45:54.355 [[main]-pipeline-manager] pipeline - Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<NoMethodError: undefined method `new' for :@via:Symbol
Aug 29 12:45:54 XenonKiloCranberry logstash[10669]: Did you mean?  next>, :backtrace=>["/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/vendor/bundle/jruby/2.3.0/gems/mail-2.6.6/lib/mail/configuration.rb:26:in `delivery_method'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-email-4.1.1/lib/logstash/outputs/email.rb:125:in `block in register'", "org/jruby/RubyBasicObject.java:1691:in `instance_eval'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/vendor/bundle/jruby/2.3.0/gems/mail-2.6.6/lib/mail/mail.rb:107:in `defaults'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/vendor/bundle/jruby/2.3.0/gems/logstash-output-email-4.1.1/lib/logstash/outputs/email.rb:124:in `register'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:102:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:46:in `register'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:242:in `register_plugin'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:253:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:253:in `register_plugins'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:594:in `maybe_setup_out_plugins'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:263:in `start_workers'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:200:in `run'", "/nix/store/vwk0xx9ni5r6zrv92bv0fcccpqj0mlik-logstash-6.5.1/logstash-core/lib/logstash/pipeline.rb:160:in `block in start'"], :thread=>"#<Thread:0x5b7ca45d run>"}
Aug 29 12:45:54 XenonKiloCranberry logstash[10669]: [ERROR] 2019-08-29 12:45:54.407 [Converge PipelineAction::Create<main>] agent - Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
```

My config:

```
input {
  # Read from journal
udp {
  port => 25826
  buffer_size => 1452
  codec => collectd { }
  tags => ['collectd']
}
# file {
#   codec => "json"
#   path => ["/root/nginxProxy/nginxLogs/access.log"]
#   tags => ['nginx_access']
# }
# file {
#   type => "text"
#   path => ["/root/nginxProxy/nginxLogs/error.log"]
#   tags => ['nginx_error']
# }
file {
  type => "text"
  path => ["/tmp/wtfchris"]
  tags => ['chrisdebug']
}
file {
  type => "text"
  path => ["/root/client_r/data/exception.log"]
  tags => ['client_r_error']
}
file {
  type => "text"
  path => ["/root/blog/data/exception.log"]
  tags => ['chris_error']
}

}

filter {
  if 'nginx_access' in [tags] {
  mutate {
    convert => [ "status","integer" ]
    convert => [ "size","integer" ]
    convert => [ "upstreamtime","float" ]
    remove_field => "message"
  }
  geoip {
      source => "ip"
  }
}

}

output {
  if [collectd_type] =~ /.+/ {
  elasticsearch {
    index => "metrics-%{+xxxx.ww}"
  }
}
if 'nginx_access' in [tags] {
  elasticsearch {
      index => "logstash-nginx-access-%{+YYYY.MM.dd}"
  }
}
if 'nginx_error' in [tags] {
  elasticsearch {
      index => "logstash-nginx-errors-%{+YYYY.MM.dd}"
  }
}
if 'chrisdebug' in [tags] {
  stdout { }
  elasticsearch {
      index => "chris-debug"
  }
  email {
    to => 'removed'
    from => 'removed'
    subject => 'Alert - %{title}'
    body => "Tags: %{tags}\\n\\Content:\\n%{message}"
    domain => 'smtp.mailgun.org'
    username => 'removed'
    password => 'removed'
    use_tls => true
    port => 25
  }
}
if 'chris_error' in [tags] {
  stdout { }
  elasticsearch {
      index => "chris-error"
  }
}
if 'client_r_error' in [tags] {
  stdout { }
  elasticsearch {
      index => "client_r-error"
  }
}

}
```

**Comment by kares** [comment]
... did not try reproducing but maybe you tried latest LS 7.5 and it was doing fine?

**Comment by jsvd** [comment]
Closing here due to inactivity. If you land here please create a new issue.
