### ISSUE TITLE
Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.

### ISSUE THREAD

**Issue by liuqu11** [elastic/logstash#11116]
Hello there,
    Recently I have encountered such a problem, logstash will die on its own every day. My logstash is taken from kafka and stored in es. The error message is as follows:

```
[2019-09-03T18:18:12,570][ERROR][org.logstash.execution.WorkerLoop] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
org.jruby.exceptions.SystemCallError: (SystemCallError) Unknown error (SystemCallError) - <STDOUT>
	at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1472) ~[jruby-complete-9.2.7.0.jar:?]
	at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1429) ~[jruby-complete-9.2.7.0.jar:?]
	at DATA.logstash_minus_7_dot_3_dot_0.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/DATA/logstash-7.3.0/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:43) ~[?:?]
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1792) ~[jruby-complete-9.2.7.0.jar:?]
	at DATA.logstash_minus_7_dot_3_dot_0.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/DATA/logstash-7.3.0/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:42) ~[?:?]
	at DATA.logstash_minus_7_dot_3_dot_0.logstash_minus_core.lib.logstash.outputs.base.multi_receive(/DATA/logstash-7.3.0/logstash-core/lib/logstash/outputs/base.rb:87) ~[?:?]
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multi_receive(org/logstash/config/ir/compiler/OutputStrategyExt.java:118) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multi_receive(org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:101) ~[logstash-core.jar:?]
	at DATA.logstash_minus_7_dot_3_dot_0.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/DATA/logstash-7.3.0/logstash-core/lib/logstash/java_pipeline.rb:239) ~[?:?]
[2019-09-03T18:18:22,444][ERROR][org.logstash.execution.WorkerLoop] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
org.jruby.exceptions.SystemCallError: (SystemCallError) Unknown error (SystemCallError) - <STDOUT>
	at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1472) ~[jruby-complete-9.2.7.0.jar:?]
	at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1429) ~[jruby-complete-9.2.7.0.jar:?]
	at DATA.logstash_minus_7_dot_3_dot_0.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/DATA/logstash-7.3.0/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:43) ~[?:?]
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1792) ~[jruby-complete-9.2.7.0.jar:?]
	at DATA.logstash_minus_7_dot_3_dot_0.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/DATA/logstash-7.3.0/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:42) ~[?:?]
	at DATA.logstash_minus_7_dot_3_dot_0.logstash_minus_core.lib.logstash.outputs.base.multi_receive(/DATA/logstash-7.3.0/logstash-core/lib/logstash/outputs/base.rb:87) ~[?:?]
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multi_receive(org/logstash/config/ir/compiler/OutputStrategyExt.java:118) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multi_receive(org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:101) ~[logstash-core.jar:?]
	at DATA.logstash_minus_7_dot_3_dot_0.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/DATA/logstash-7.3.0/logstash-core/lib/logstash/java_pipeline.rb:239) ~[?:?]
[2019-09-03T18:23:16,643][ERROR][org.logstash.execution.WorkerLoop] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
org.jruby.exceptions.SystemCallError: (SystemCallError) Unknown error (SystemCallError) - <STDOUT>
	at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1472) ~[jruby-complete-9.2.7.0.jar:?]
	at org.jruby.RubyIO.write(org/jruby/RubyIO.java:1429) ~[jruby-complete-9.2.7.0.jar:?]
	at DATA.logstash_minus_7_dot_3_dot_0.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/DATA/logstash-7.3.0/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:43) ~[?:?]
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1792) ~[jruby-complete-9.2.7.0.jar:?]
	at DATA.logstash_minus_7_dot_3_dot_0.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_stdout_minus_3_dot_1_dot_4.lib.logstash.outputs.stdout.multi_receive_encoded(/DATA/logstash-7.3.0/vendor/bundle/jruby/2.5.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:42) ~[?:?]
	at DATA.logstash_minus_7_dot_3_dot_0.logstash_minus_core.lib.logstash.ou

```

- Version:  7.3.0
- Operating System: centos7.3

**Comment by Divine1** [comment]
Hi,
```
logstash 7.8.1 
Ubuntu 18.04 64 bit
```
This is my workflow `filebeat -> logstash -> elasticsearch -> kibana`

My logstash keeps getting shutdown unexpectedly after running successfully for sometime with below error
i'm not able to identify the reason for this error to look for solutions.
Kindly help me on this

![image](https://user-images.githubusercontent.com/10482177/90412540-de8cb380-e0ca-11ea-9c4c-9804d3398e05.png)

**Comment by Hossamyh** [comment]
Hello,

Any updates on this? @Divine1 @liuqu11

**Comment by Divine1** [comment]
@Hossamyh  

i'm not able to run `logstash` in background mode (i have installed logstash is in `baremetal` way).
 i have tried several approaches to fix this problem, but it doesn't work. 

For my usecase, i had to load some data from `filebeat`. On the need basis, i run the `logstash` process by connecting to ssh and then fire this command `bin/logstash -f config/pipelines/pipeline-final.conf` to start `logstash` process. but the disadvantage is when my ssh terminates, the logstash process terminates as well. so i reinitiate it whenever required.

i'm planning to install logstash via docker as i can run the `logstash-container` in background mode. this will definitely fix my issue

**Comment by Hossamyh** [comment]
Hello @Divine1,

When I ran Logstash in the background using './logstash &', I was having the same issue.

I've tried now to run Logstash using 'nohup ./logstash &' to save logstash output to "nohup.out" file, so when I close the SSH session, I can 'tail' on the nohup.out file to get the output of logstash. I don't know how and why, but this has let logstash to work fine even after terminating the SSH session.

Please try this and let me know if it works for you too.

**Comment by Divine1** [comment]
@Hossamyh nohup doesnot work for me. it gets terminated when the ssh session gets terminated.

**Comment by RajendraDesai** [comment]
Hello..can someone help on the same issue: logstash keeps getting shutdown unexpectedly with following error

[ERROR] 2020-10-01 06:37:43.688 [[main]-pipeline-manager] javapipeline - Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-mongodb-0.4.1/lib/logstash/inputs/mongodb.rb:99:in `init_placeholder'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-mongodb-0.4.1/lib/logstash/inputs/mongodb.rb:113:in `get_placeholder'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-mongodb-0.4.1/lib/logstash/inputs/mongodb.rb:160:in `block in update_watched_collections'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-mongodb-0.4.1/lib/logstash/inputs/mongodb.rb:158:in `update_watched_collections'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-mongodb-0.4.1/lib/logstash/inputs/mongodb.rb:182:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:191:in `block in register_plugins'", "org/jruby/RubyArray.java:1792:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:190:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:280:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:244:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:145:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:104:in `block in start'"], :thread=>"#<Thread:0x1681d245 run>"}

**Comment by Divine1** [comment]
@Hossamyh @liuqu11 


i moved from logstash barebone software installation to docker image.
As i expected, the docker container keeps running in the background without the issues that i have mentioned on my comments above.


This is the command i use to run the logstash as a docker image 
``
docker run -d -p 9600:9600 -p 5044:5044 -v /home/elkuser/elkstack/softwares/logstash_file_docker/logstash.yml:/usr/share/logstash/config/logstash.yml -v /home/elkuser/elkstack/softwares/logstash_file_docker/pipeline-final.conf:/usr/share/logstash/pipeline/logstash.conf cc67e625d974
```

This is the only solution i have right now for this issue.
i apologize for the delay.

**Comment by hbbdgyb** [comment]
[2023-08-24T20:29:05,593][ERROR][org.logstash.execution.WorkerLoop] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
org.jruby.exceptions.ArgumentError: (ArgumentError) string contains null byte
	at org.jruby.RubyProcess.spawn(org/jruby/RubyProcess.java:1567) ~[jruby-complete-9.2.7.0.jar:?]
	at org.jruby.RubyKernel.spawn(org/jruby/RubyKernel.java:1646) ~[jruby-complete-9.2.7.0.jar:?]
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.open3.popen_run(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/open3.rb:202) ~[?:?]
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.open3.popen3(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/open3.rb:98) ~[?:?]
	at www.logstash_minus_7_dot_2_dot_1.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_exec_minus_3_dot_1_dot_4.lib.logstash.outputs.exec.receive(/www/logstash-7.2.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-exec-3.1.4/lib/logstash/outputs/exec.rb:51) ~[?:?]
	at www.logstash_minus_7_dot_2_dot_1.logstash_minus_core.lib.logstash.outputs.base.multi_receive(/www/logstash-7.2.1/logstash-core/lib/logstash/outputs/base.rb:89) ~[?:?]
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1792) ~[jruby-complete-9.2.7.0.jar:?]
	at www.logstash_minus_7_dot_2_dot_1.logstash_minus_core.lib.logstash.outputs.base.multi_receive(/www/logstash-7.2.1/logstash-core/lib/logstash/outputs/base.rb:89) ~[?:?]
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multi_receive(org/logstash/config/ir/compiler/OutputStrategyExt.java:118) ~[logstash-core.jar:?]
	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multi_receive(org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:101) ~[logstash-core.jar:?]
	at www.logstash_minus_7_dot_2_dot_1.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/www/logstash-7.2.1/logstash-core/lib/logstash/java_pipeline.rb:239) ~[?:?]
warning: thread "[main]>worker2" terminated with exception (report_on_exception is true):
java.lang.IllegalStateException: org.jruby.exceptions.ArgumentError: (ArgumentError) string contains null byte
	at org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:85)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:440)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:304)
	at www.logstash_minus_7_dot_2_dot_1.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/www/logstash-7.2.1/logstash-core/lib/logstash/java_pipeline.rb:239)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:295)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:270)
	at java.lang.Thread.run(java/lang/Thread.java:748)
Caused by: org.jruby.exceptions.ArgumentError: (ArgumentError) string contains null byte
	at org.jruby.RubyProcess.spawn(org/jruby/RubyProcess.java:1567)
	at org.jruby.RubyKernel.spawn(org/jruby/RubyKernel.java:1646)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.open3.popen_run(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/open3.rb:202)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.open3.popen3(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/open3.rb:98)
	at www.logstash_minus_7_dot_2_dot_1.vendor.bundle.jruby.$2_dot_5_dot_0.gems.logstash_minus_output_minus_exec_minus_3_dot_1_dot_4.lib.logstash.outputs.exec.receive(/www/logstash-7.2.1/vendor/bundle/jruby/2.5.0/gems/logstash-output-exec-3.1.4/lib/logstash/outputs/exec.rb:51)
	at www.logstash_minus_7_dot_2_dot_1.logstash_minus_core.lib.logstash.outputs.base.multi_receive(/www/logstash-7.2.1/logstash-core/lib/logstash/outputs/base.rb:89)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1792)
	at www.logstash_minus_7_dot_2_dot_1.logstash_minus_core.lib.logstash.outputs.base.multi_receive(/www/logstash-7.2.1/logstash-core/lib/logstash/outputs/base.rb:89)
	at org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multi_receive(org/logstash/config/ir/compiler/OutputStrategyExt.java:118)
	at org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multi_receive(org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:101)
	at www.logstash_minus_7_dot_2_dot_1.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/www/logstash-7.2.1/logstash-core/lib/logstash/java_pipeline.rb:239)
[2023-08-24T20:29:05,746][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>java.lang.IllegalStateException: org.jruby.exceptions.ArgumentError: (ArgumentError) string contains null byte, :backtrace=>["org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:85)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:440)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:304)", "www.logstash_minus_7_dot_2_dot_1.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/www/logstash-7.2.1/logstash-core/lib/logstash/java_pipeline.rb:239)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:295)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:274)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:270)", "java.lang.Thread.run(java/lang/Thread.java:748)"]}
[2023-08-24T20:29:05,814][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
怎么解决啊7.2.1
