### ISSUE TITLE
Logstash Errors Too Challenging to resolve.

### ISSUE THREAD

**Issue by lukelee1987** [elastic/logstash#11209]
```
[ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:logstash_main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, -, \", ', } at line 13, column 18 (byte 159) after filter{\n      grok {\n      match => { ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2577:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:151:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:24:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}
[2019-10-11T17:26:43,551][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:logstash_main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of #, -, \", ', } at line 13, column 18 (byte 159) after filter{\n      grok {\n      match => { ", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:41:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:49:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `block in compile_sources'", "org/jruby/RubyArray.java:2577:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:10:in `compile_sources'", "org/logstash/execution/AbstractPipelineExt.java:151:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:24:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}
```

Dear all, I have this in my log file. Unable to know how to resolve this. Don't really understand this. Previously I installed on the wrong dir, which is /etc/logstash, and now we are moving into /usr/share/logstash. Now these causing these errors.

**Comment by fktkrt** [comment]
There is a syntax error in one of you config files for your pipeline. Its location is depends on you filters in the `conf.d` folder. Your error message above indicates this position:
```
... message=>"Expected one of #, -, \", ', } at line 13, column 18 (byte 159) after filter{\n ...
```
But if you happen to have multiple filters, this could be somewhere else, because Logstash has a single event pipeline, therefor it combines all of your `.conf` files in the given folder.

To troubleshoot this, you can investigate them separately like this:
```
logstash -f /etc/logstash/conf.d/01-filter.conf --config.debug --log.level debug --config.test_and_exit
``` 

Which will give you the proper position of syntax error.

**Comment by nrrpinto** [comment]
@fktkrt your comment is very useful, thanks so much.
