### ISSUE TITLE
Add example of running ingest-convert.sh against a Beats module

### ISSUE THREAD

**Issue by n0othing** [elastic/logstash#11213]
Logstash ships with a nifty tool [1] that makes it easier to convert ingest node pipelines configs. Users may want to try running the tool against the various pipeline definitions included with a Beats module, so it would be helpful to show an example of how you would do this specific to Beats (e.g where you might locate the definition file for a given module).

```
/usr/share/filebeat/module/apache
├── access
│   ├── config
│   │   └── access.yml
│   ├── ingest
│   │   └── default.json <---
│   └── manifest.yml
├── error
│   ├── config
│   │   └── error.yml
│   ├── ingest
│   │   └── pipeline.json <---
│   └── manifest.yml
└── module.yml
```

[1] https://www.elastic.co/guide/en/logstash/7.4/ingest-converter.html#ingest-converter

**Comment by Daniel314** [comment]
An update to this request: could the docs also be updated to indicate that the Beat ingest modules are no longer JSON but YAML?  (... -> module -> iis -> access -> ingest -> pipeline.yml )

**Comment by cameronkerrnz** [comment]
The documentation at https://www.elastic.co/guide/en/logstash/current/ingest-converter.html makes no mention of how to get the  ingest pipeline (and what schema is expected). I used GET /_ingest/pipelines/filebeat-7.10.2-iis-access as well as copying the pipeline definition from a (7.10.2) Kibana, but the schema is different and produces the error shown below. I suspect the author of that page/tool was expecting the file to come from filebeat assets.

In particular, it seems that you need something that looks like this (shortened to just show the first processor):

```
{
  "description":"Pipeline for parsing IIS access logs with our custom log format",
  "processors": [
    {
      "set": {
        "field": "event.ingested",
        "value": "{{_ingest.timestamp}}"
      }
    }
  ]
}
```

But the pipeline that is visable via the API or via Kibana has only the value of the '.processors' key of that document.

```
[
    {
      "set": {
        "field": "event.ingested",
        "value": "{{_ingest.timestamp}}"
      }
    }
]
```

This causes an unhelpful error:

```
# /usr/share/logstash/bin/ingest-convert.sh --input file:///tmp/iis.access.ingest.json --output file:///tmp/iis.access.logstash.conf --append-stdio
Warning: Nashorn engine is planned to be removed from a future JDK release
Exception in thread "main" javax.script.ScriptException: TypeError: Cannot read property "map" from undefined in <eval> at line number 78
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:477)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:399)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeFunction(NashornScriptEngine.java:197)
	at org.logstash.ingest.JsUtil.convert(JsUtil.java:104)
	at org.logstash.ingest.Pipeline.main(Pipeline.java:35)
Caused by: <eval>:78 TypeError: Cannot read property "map" from undefined
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.Undefined.get(Undefined.java:161)
	at jdk.scripting.nashorn.scripts/jdk.nashorn.internal.scripts.Script$Recompilation$24$44AA$\^eval\_.ingest_pipeline_to_logstash(<eval>:78)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:659)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513)
	at jdk.scripting.nashorn/jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:527)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.ScriptObjectMirror.callMember(ScriptObjectMirror.java:202)
	at jdk.scripting.nashorn/jdk.nashorn.api.scripting.NashornScriptEngine.invokeImpl(NashornScriptEngine.java:393)
	... 3 more
```

This is with Logstash 7.10.2 running on openjdk version "11.0.9.1" 2020-11-04 LTS

**Comment by epsilon-jpage** [comment]
As of 7.14.0 there are only 4 modules still using a pipeline.json (misp / mysql / osquery / redis) in the filebeat modules directory structure.  It would be incredibly helpful if this script worked and converted the yaml as well.  Elastic should either update the script or take a hard stance and tell users to configure Logstash to send to Elasticsearch pipelines only for default supported modules.

Since this has been open since October of 2019, I'll not hold my breath.
