### ISSUE TITLE
Couldn't find any output plugin named 'java_sink'

### ISSUE THREAD

**Issue by DaveyDevOps** [elastic/logstash#11214]
- Version: 7.3.0

Followed version docs to setup java_sink output
https://www.elastic.co/guide/en/logstash/7.3/plugins-outputs-java_sink.html
Pretty sure I configured it correctly (since there is no configuration). 

```
[2019-10-11T16:04:50,052][ERROR][logstash.agent           ] 
Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:iib_esb3, 
:exception=>"LogStash::PluginLoadingError", 
:message=>"Couldn't find any output plugin named 'java_sink'. Are you sure this is correct? Trying to load the java_sink output plugin resulted in this error: no such file to load -- logstash/outputs/java_sink", 
:backtrace=>["/data/software/logstash-7.3.0/logstash-core/lib/logstash/plugins/registry.rb:221:in `lookup_pipeline_plugin'", 
"/data/software/logstash-7.3.0/logstash-core/lib/logstash/plugin.rb:143:in `lookup'",
"org/logstash/plugins/PluginFactoryExt.java:203:in `plugin'",
"org/logstash/plugins/PluginFactoryExt.java:140:in `buildOutput'",
"org/logstash/execution/JavaBasePipelineExt.java:50:in `initialize'", 
"/data/software/logstash-7.3.0/logstash-core/lib/logstash/java_pipeline.rb:24:in `initialize'", 
"/data/software/logstash-7.3.0/logstash-core/lib/logstash/pipeline_action/create.rb:36:in `execute'", 
"/data/software/logstash-7.3.0/logstash-core/lib/logstash/agent.rb:325:in `block in converge_state'"]}
```

Examining `logstash-plugin list` found that null output plugin is still available. This is not referenced in the documentation.

**Comment by haridev22** [comment]
@DaveyDevOps : I am not sure if you are still working on this but still proving a solution for everyone's benefit

Instead of java_sink, use sink. For example

output {
  sink {
      id => "your_plugin_id"
  }
}

**Comment by DaveyDevOps** [comment]
Thanks for update, like #11675 seems like documentation issue.
