### ISSUE TITLE
Logstash 7.4.1 + JDBC + MS SQL Server + OpenJDK 11 = Fail to load

### ISSUE THREAD

**Issue by nunorcenteio** [elastic/logstash#11268]
Hi all,

I'm new to Logstash but I think there is some problem.

Here is my logstash conf file:

> input {
>   jdbc {
>     jdbc_driver_library => "D:\Microsoft JDBC Driver 7.4 for SQL Server\sqljdbc_7.4\enu\mssql-jdbc-7.4.1.jre12.jar"
> 	jdbc_driver_class => "com.microsoft.sqlserver.jdbc.SQLServerDriver"    
> 	jdbc_connection_string => "jdbc:sqlserver://localhost;databaseName=mydatabase;"
> (...)

When I start logstash I got this:

> [2019-10-24T12:01:41,512][ERROR][logstash.javapipeline    ][main] A plugin had an unrecoverable error. Will restart this plugin.
>   Pipeline_id:main
>   Plugin: <LogStash::Inputs::Jdbc jdbc_user=>"creator", jdbc_password=><password>, statement=>"SELECT * FROM vwInteractionHistoryInboundMaster", jdbc_driver_library=>"D:\\Microsoft JDBC Driver 7.4 for SQL Server\\sqljdbc_7.4\\enu\\mssql-jdbc-7.4.1.jre12.jar", jdbc_connection_string=>"jdbc:sqlserver://localhost;databaseName=mydatabase;", id=>"3e660433cb83ddb45b0a38fec5c7019f2065bc0edeb1198578744674076050a2", jdbc_driver_class=>"com.microsoft.sqlserver.jdbc.SQLServerDriver", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_99bca959-3d6f-49e0-b9c0-6c43d5cf7f20", enable_metric=>true, charset=>"UTF-8">, jdbc_paging_enabled=>false, jdbc_page_size=>100000, jdbc_validate_connection=>false, jdbc_validation_timeout=>3600, jdbc_pool_timeout=>5, sql_log_level=>"info", connection_retry_attempts=>1, connection_retry_attempts_wait_time=>0.5, plugin_timezone=>"utc", last_run_metadata_path=>"C:\\Users\\NB15664/.logstash_jdbc_last_run", use_column_value=>false, tracking_column_type=>"numeric", clean_run=>false, record_last_run=>true, lowercase_column_names=>true, use_prepared_statements=>false>
>   Error: com.microsoft.sqlserver.jdbc.SQLServerDriver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library?
>   Exception: LogStash::PluginLoadingError
>   Stack: D:/logstash-7.4.1/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/plugin_mixins/jdbc/jdbc.rb:190:in `open_jdbc_connection'
> D:/logstash-7.4.1/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/plugin_mixins/jdbc/jdbc.rb:253:in `execute_statement'
> D:/logstash-7.4.1/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/inputs/jdbc.rb:309:in `execute_query'
> D:/logstash-7.4.1/vendor/bundle/jruby/2.5.0/gems/logstash-input-jdbc-4.3.16/lib/logstash/inputs/jdbc.rb:281:in `run'

This is my Java:

> PS D:\logstash-7.4.1> java -version
> openjdk version "13.0.1" 2019-10-15
> OpenJDK Runtime Environment (build 13.0.1+9)
> OpenJDK 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)

I've tried a lot of combinations but I'm not able to start the JDBC driver :(.

Can someone help me understand what might be wrong here?

Thanks

**Comment by yaauie** [comment]
Logstash currently supports Java 8 and Java 11.

**Comment by nunorcenteio** [comment]
Hi @yaauie .

```
PS D:\logstash-7.4.1> java -version
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

Same thing with Java 11 :(

**Comment by yaauie** [comment]
You may have better luck getting to a solution using the forums:

> Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash).
> Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.
>
> -- [Logstash Issue Template](https://raw.githubusercontent.com/elastic/logstash/master/.github/ISSUE_TEMPLATE.md)

In the past, I've seen people have problems with spaces in Windows file paths when loading jars; you may want to move the jar library to a shorter path without spaces and try again.

**Comment by robbavey** [comment]
This should have been fixed by https://github.com/logstash-plugins/logstash-input-jdbc/pull/356 in the `4.3.18` release of the JDBC input plugin

**Comment by Priyashukla** [comment]
[2024-09-18T08:14:53,817][ERROR][logstash.javapipeline    ][main][50be11d03f9da195438d7fe63e27b428df9c4f2eaf55975fa6167d8633715187] A plugin had an unrecoverable error. Will restart this plugin.
2024-09-18 13:44:53   Pipeline_id:main
2024-09-18 13:44:53   Plugin: <LogStash::Inputs::Jdbc jdbc_user=>"doris", last_run_metadata_path=>"/usr/share/logstash/.logstash_jdbc_last_run", jdbc_paging_enabled=>true, jdbc_page_size=>50000, tracking_column_type=>"numeric", use_prepared_statements=>false, record_last_run=>true, plugin_timezone=>"utc", tracking_column=>"ID", use_column_value=>true, schedule=>"* * * * *", jdbc_password=><password>, statement=>"SELECT * FROM doris.DATABASECHANGELOG", clean_run=>false, jdbc_driver_library=>"/usr/share/logstash/pipeline/mysql-connector-java-8.0.30.jar", jdbc_connection_string=>"jdbc:mysql://localhost:3306/doris**;**", id=>"50be11d03f9da195438d7fe63e27b428df9c4f2eaf55975fa6167d8633715187", jdbc_driver_class=>"java:com.mysql.cj.jdbc.Driver", lowercase_column_names=>true, enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_23c5ef9f-91d7-41d7-a0ff-18dec6121b4e", enable_metric=>true, charset=>"UTF-8">, jdbc_validate_connection=>false, jdbc_validation_timeout=>3600, jdbc_pool_timeout=>5, sql_log_level=>"info", connection_retry_attempts=>1, connection_retry_attempts_wait_time=>0.5>
2024-09-18 13:44:53   Error: Java::java:com.mysql.cj.jdbc.Driver not loaded. Are you sure you've included the correct jdbc driver in :jdbc_driver_library? ["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/sequel-5.51.0/lib/sequel/adapters/jdbc.rb:68:in `load_driver'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.1.8/lib/logstash/plugin_mixins/jdbc/common.rb:33:in `load_driver'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.1.8/lib/logstash/inputs/jdbc.rb:294:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:409:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:400:in `block in start_input'"]
2024-09-18 13:44:53   Exception: LogStash::PluginLoadingError
2024-09-18 13:44:53   Stack: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.1.8/lib/logstash/plugin_mixins/jdbc/common.rb:42:in `load_driver'
2024-09-18 13:44:53 /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-integration-jdbc-5.1.8/lib/logstash/inputs/jdbc.rb:294:in `run'
2024-09-18 13:44:53 /usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:409:in `inputworker'
2024-09-18 13:44:53 /usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:400:in `block in start_input'
2024-09-18 13:44:54 [2024-09-18T08:14:54,819][ERROR][logstash.javapipeline    ][main][50be11d03f9da195438d7fe63e27b428df9c4f2eaf55975fa6167d8633715187] A plugin had an unrecoverable error. Will restart this plugin.

Getting this issue with conf file

input {
  jdbc {
    jdbc_driver_library => "/usr/share/logstash/pipeline/mysql-connector-java-8.0.30.jar"  
    jdbc_driver_class =>"com.mysql.cj.jdbc.Driver"  
    jdbc_connection_string => "jdbc:mysql://localhost:3306/******;**"
    jdbc_user => "****"
    jdbc_password => "******"
    schedule => "* * * * *"
    tracking_column => "ID"
    use_column_value => true
    statement => "SELECT * FROM ****"
    jdbc_paging_enabled => "true"
    jdbc_page_size => "50000"  
    use_column_value => true
    plugin_timezone => "utc"
    last_run_metadata_path => "/usr/share/logstash/.logstash_jdbc_last_run"
    tracking_column => "ID"
    tracking_column_type => "numeric"
    use_column_value => true
    clean_run => false
    record_last_run => true
    lowercase_column_names => true
    use_prepared_statements => false  
  }
}
 
output {
  elasticsearch {
    hosts => ["https://elastic-1:9200"]
    user => "elastic"
    password => "****"
    index => "logstash_index1"
    ssl => true
    cacert => "/usr/share/elasticsearch/config/certificates/ca/ca.crt"
  }
  stdout {
    codec => json
  }
}
