### ISSUE TITLE
w

### ISSUE THREAD

**Issue by liminghua999** [elastic/logstash#11357]
1

**Comment by liminghua999** [comment]
```
logstash01  | [2019-11-29T08:29:08,010][WARN ][logstash.licensechecker.licensereader] Restored connection to ES instance {:url=>"https://elastic:xxxxxx@es02:9200/"}
logstash01  | [2019-11-29T08:29:08,287][WARN ][logstash.licensechecker.licensereader] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://elastic:xxxxxx@es03:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://elastic:xxxxxx@es03:9200/][Manticore::ClientProtocolException] Invalid CertificateVerify signature"}
logstash01  | [2019-11-29T08:29:08,971][INFO ][logstash.monitoring.internalpipelinesource] Monitoring License OK
logstash01  | [2019-11-29T08:29:08,976][INFO ][logstash.monitoring.internalpipelinesource] Validated license for monitoring. Enabling monitoring pipeline.
logstash01  | [2019-11-29T08:29:12,873][INFO ][org.reflections.Reflections] Reflections took 192 ms to scan 1 urls, producing 20 keys and 40 values
logstash01  | [2019-11-29T08:29:13,878][INFO ][logstash.licensechecker.licensereader] Elasticsearch pool URLs updated {:changes=>{:removed=>[https://elastic:xxxxxx@es01:9200/, https://elastic:xxxxxx@es02:9200/, https://elastic:xxxxxx@es03:9200/], :added=>[https://elastic:xxxxxx@172.25.0.2:9200/, https://elastic:xxxxxx@172.25.0.3:9200/, https://elastic:xxxxxx@172.25.0.4:9200/]}}
logstash01  | [2019-11-29T08:29:14,171][WARN ][logstash.licensechecker.licensereader] Error while performing sniffing {:error_message=>"Host name '172.25.0.2' does not match the certificate subject provided by the peer (CN=es01)", :class=>"Manticore::UnknownException", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:37:in `block in initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:79:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:74:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:291:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:245:in `block in healthcheck!'", "org/jruby/RubyHash.java:1417:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:241:in `healthcheck!'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:341:in `update_urls'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:157:in `sniff!'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:146:in `block in start_sniffer'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:128:in `until_stopped'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.1.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:144:in `block in start_sniffer'"]}

```
