### ISSUE TITLE
Flaky failing test on JRuby thread clean check

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#11484]
With a previous PR was introduced a test to check that `nil` is returned as JRuby Thread's id when the underlying Java thread is collected.

https://github.com/elastic/logstash/blob/master/logstash-core/spec/logstash/util_spec.rb#L78-L87

This leverage the fact that full GC scattered by `System.gc()` clean the WeakReference to Java's native Thread from JRuby's ThreadLike; but probably due to parallel GCing or by the implementation of `System.gc()` it's not a STW pause, so the test code goes to next lines and the reference is still alive.

Example of failed test:
```
16:04:35 
16:04:35       1) LogStash::Util.get_thread_id when a (native) thread is collected returns nil as id
16:04:35          Failure/Error: expect(LogStash::Util.get_thread_id(thread)).to be nil
16:04:35          
16:04:35            expected nil
16:04:35                 got #<Integer:2563> => 1281
16:04:35          # ./logstash-core/spec/logstash/util_spec.rb:85:in `block in <main>'
16:04:35          # ./spec/spec_helper.rb:51:in `block in /opt/logstash/spec/spec_helper.rb'
16:04:35          # ./logstash-core/lib/logstash/util.rb:27:in `set_thread_name'
16:04:35          # ./spec/spec_helper.rb:50:in `block in /opt/logstash/spec/spec_helper.rb'
16:04:35          # ./spec/spec_helper.rb:43:in `block in /opt/logstash/spec/spec_helper.rb'
16:04:35          # ./vendor/bundle/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/vendor/bundle/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
16:04:35          # ./lib/bootstrap/rspec.rb:15:in `<main>'
```

**Comment by kares** [comment]
we tried our best at https://github.com/elastic/logstash/pull/11483 (to possibly allow for reaching a safe-point for gc)
if we're still see failures we should remove the specs as suggested by the comment:
https://github.com/elastic/logstash/pull/11483/files#diff-44d243d2c6fb1e9225eef2e7ba8514c4R85
