### ISSUE TITLE
Logstash Beats Input remote: undefined on SSL Errors 

### ISSUE THREAD

**Issue by cbryanvest** [elastic/logstash#11494]
While tracking down a beats client with a bad SSL certificate I constantly ran into `[2020-01-08T22:25:58,724][DEBUG][org.logstash.beats.BeatsHandler][main] [local: 0.0.0.0:5044, remote: undefined]`. This makes it difficult to track down the client with the bad SSL certificate. Very randomly this would show the IP address but there was no consistent pattern.

This seems like it is a race condition between BeatsHandler trying to get the IP address and netty closing the socket. 

The interesting find here is that if I enable `log.level: trace` in the logstash.yml it does produce the IP's but enabling trace through the logstash API does not have this effect, the undefined error is still present.

Enabling trace through the API produces this `[2020-01-08T22:25:58,714][TRACE][org.logstash.beats.BeatsHandler][main] [local: 0.0.0.0:5044, remote: undefined] Channel Active`

With `log.level: trace` in the logstash.yml the exact same test produces this result `[2020-01-08T22:28:04,668][TRACE][org.logstash.beats.BeatsHandler][main] [local: 192.168.2.135:5044, remote: 192.168.2.201:38720] Channel Active`

- Version: 
Beats 7.5.1 
Logstash 7.5.1
Logstash Beats Plugin 6.0.3

- Operating System: 
Ubuntu 18.04 LTS

- Steps to Reproduce: 
Install logstash and metricbeat on the same host or different hosts either will work. Enable SSL on the logstash beats input but do not enable it on the beat .This will produce the error `OPENSSL_internal:WRONG_VERSION_NUMBER` which leads to the log entries above. 

Enable Trace through the API with 
<pre>
root@ls-1-prod:/etc/logstash# curl -XPUT 'localhost:9600/_node/logging?pretty' -H 'Content-Type: application/json' -d'
{
    "logger" : "TRACE"
}
'
</pre>
All other trace logging seems to work but IP will still be undefined

Set `log.level: trace` and restart logstash. This should produce the error with the IP addresses. 

### Addition:
Further testing shows that `log.level: trace` does not always work. It does seem to depend on the speed of the logstash server. Though it never works when enabled through the API.

**Comment by richard-mauri** [comment]
+1

**Comment by nullpanda** [comment]
+1 Having a similar issue with seemingly no known source, tcpdump would indicate that all traffic flowing into the system is from known-good configuration filebeats clients properly using SSL. I am seeing a similar error to those posted above: 
`[local: 0.0.0.0:5044, remote: undefined] Handling exception: io.netty.handler.codec.DecoderException: io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record:
<sanitized>
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) [netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-all-4.1.49.Final.jar:4.1.49.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.49.Final.jar:4.1.49.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?] `

**Comment by kares** [comment]
thanks for the updates, seems like an issue with Netty. the plugin does not control what we retrieve.
gone through the changelogs since Netty 4.1.49 but nothing that would mention remote address retrieval from the channel.

I think this is open to PRs as to how to potentially improve remote detection, when [channel does not have the address](https://github.com/logstash-plugins/logstash-input-beats/blob/v6.1.0/src/main/java/org/logstash/beats/BeatsHandler.java#L118).

also I think we would eventually want to move this issue to the [plugin tracker](https://github.com/logstash-plugins/logstash-input-beats/issues)

**Comment by kares** [comment]
since logstash-input-beats **6.1.4** (https://github.com/logstash-plugins/logstash-input-beats/pull/424) the 'verbose' logging on connection resets has been reduced, closing this issue as defunct please open a new against the plugin if something does still not feel right.
