### ISSUE TITLE
Getting exception in threads dump and cpu consuming high in logstash 5.0?

### ISSUE THREAD

**Issue by shubhamjain108-lab** [elastic/logstash#11542]
Please let me know, why is this behabiour occuring?

Threads dump;

"Ruby-0-Thread-40: /home/local1/monitors/local/localagent/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/server.rb:296" #89 daemon prio=5 os_prio=0 tid=0x00007f5c20008800 nid=0x2550 runnable [0x00007f5d9b3f3000]
java.lang.Thread.State: RUNNABLE
at java.lang.Throwable.fillInStackTrace(Native Method)
at java.lang.Throwable.fillInStackTrace(Throwable.java:783)
- locked <0x00000000f8720350> (a java.lang.Exception)
at java.lang.Throwable.(Throwable.java:250)
at java.lang.Exception.(Exception.java:54)
at java.lang.Thread.getStackTrace(Thread.java:1556)
at org.jruby.runtime.backtrace.TraceType$Gather.getBacktraceData(TraceType.java:215)
at org.jruby.runtime.backtrace.TraceType.getBacktrace(TraceType.java:47)
at org.jruby.RubyException.prepareBacktrace(RubyException.java:226)
at org.jruby.exceptions.RaiseException.preRaise(RaiseException.java:215)
at org.jruby.exceptions.RaiseException.preRaise(RaiseException.java:196)
at org.jruby.exceptions.RaiseException.(RaiseException.java:111)
at org.jruby.Ruby.newRaiseException(Ruby.java:3905)
at org.jruby.Ruby.newErrnoEBADFError(Ruby.java:3453)
at org.jruby.Ruby.newIOErrorFromException(Ruby.java:3825)
at org.jruby.util.io.SelectBlob.goForIt(SelectBlob.java:105)
at org.jruby.RubyIO.select_static(RubyIO.java:3709)
at org.jruby.RubyIO.select(RubyIO.java:3705)
at org.jruby.RubyIO$INVOKER$s$0$3$select.call(RubyIO$INVOKER$s$0$3$select.gen)
at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:667)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:139)
at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:187)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)
at org.jruby.ast.VCallNode.interpret(VCallNode.java:88)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
at org.jruby.runtime.Block.call(Block.java:101)
at org.jruby.RubyProc.call(RubyProc.java:300)
at org.jruby.RubyProc.call(RubyProc.java:230)
at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
at java.lang.Thread.run(Thread.java:745)

Locked ownable synchronizers:
- None

"Ruby-0-Thread-39: /home/local1/monitors/local/localagent/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:187" #88 daemon prio=5 os_prio=0 tid=0x00007f5c20007000 nid=0x254f in Object.wait() [0x00007f5d9b4f5000]
java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at org.jruby.RubyThread.sleep(RubyThread.java:1002)
- eliminated <0x00000000e34d3670> (a org.jruby.RubyThread)
- locked <0x00000000e34d3670> (a org.jruby.RubyThread)
at org.jruby.RubyKernel.sleep(RubyKernel.java:803)
at org.jruby.RubyKernel$INVOKER$s$0$1$sleep.call(RubyKernel$INVOKER$s$0$1$sleep.gen)
at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:667)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
at org.jruby.runtime.Block.call(Block.java:101)
at org.jruby.RubyProc.call(RubyProc.java:300)
at org.jruby.RubyProc.call(RubyProc.java:230)
at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
at java.lang.Thread.run(Thread.java:745)

Locked ownable synchronizers:
- None

"Ruby-0-Thread-38: /home/local1/monitors/local/localagent/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:216" #87 daemon prio=5 os_prio=0 tid=0x00007f5c20005000 nid=0x254d in Object.wait() [0x00007f5d9b5f6000]
java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at org.jruby.RubyThread.sleep(RubyThread.java:1002)
- eliminated <0x00000000e34da508> (a org.jruby.RubyThread)
- locked <0x00000000e34da508> (a org.jruby.RubyThread)
at org.jruby.RubyKernel.sleep(RubyKernel.java:803)
at org.jruby.RubyKernel$INVOKER$s$0$1$sleep.call(RubyKernel$INVOKER$s$0$1$sleep.gen)
at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:667)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
at org.jruby.runtime.Block.call(Block.java:101)
at org.jruby.RubyProc.call(RubyProc.java:300)
at org.jruby.RubyProc.call(RubyProc.java:230)
at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
at java.lang.Thread.run(Thread.java:745)

Locked ownable synchronizers:
- None

"Ruby-0-Thread-37: /home/local1/monitors/local/localagent/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/reactor.rb:142" #86 daemon prio=5 os_prio=0 tid=0x00007f5c20003800 nid=0x254b runnable [0x00007f5d9b6f7000]
java.lang.Thread.State: RUNNABLE
at java.lang.Throwable.getStackTraceElement(Native Method)
at java.lang.Throwable.getOurStackTrace(Throwable.java:827)
- locked <0x00000000f85e2f00> (a java.lang.Exception)
at java.lang.Throwable.getStackTrace(Throwable.java:816)
at java.lang.Thread.getStackTrace(Thread.java:1556)
at org.jruby.runtime.backtrace.TraceType$Gather.getBacktraceData(TraceType.java:215)
at org.jruby.runtime.backtrace.TraceType.getBacktrace(TraceType.java:47)
at org.jruby.RubyException.prepareBacktrace(RubyException.java:226)
at org.jruby.exceptions.RaiseException.preRaise(RaiseException.java:215)
at org.jruby.exceptions.RaiseException.preRaise(RaiseException.java:196)
at org.jruby.exceptions.RaiseException.(RaiseException.java:111)
at org.jruby.Ruby.newRaiseException(Ruby.java:3905)
at org.jruby.Ruby.newErrnoEBADFError(Ruby.java:3453)
at org.jruby.Ruby.newIOErrorFromException(Ruby.java:3825)
at org.jruby.util.io.SelectBlob.goForIt(SelectBlob.java:105)
at org.jruby.RubyIO.select_static(RubyIO.java:3709)
at org.jruby.RubyIO.select(RubyIO.java:3705)
at org.jruby.RubyIO$INVOKER$s$0$3$select.call(RubyIO$INVOKER$s$0$3$select.gen)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
at rubyjit.Puma::Reactor$$run_internal_9b3c548ef031cc1470bd839c282ebd5629ff06981802906423.chained_1_rescue_2$RUBY$SYNTHETIC__file__(/home/local1/monitors/local/localagent/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/reactor.rb:29)
at rubyjit.Puma::Reactor$$run_internal_9b3c548ef031cc1470bd839c282ebd5629ff06981802906423.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/home/local1/monitors/local/localagent/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/reactor.rb:28)
at rubyjit.Puma::Reactor$$run_internal_9b3c548ef031cc1470bd839c282ebd5629ff06981802906423.file(/home/local1/monitors/local/localagent/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/reactor.rb:27)
at rubyjit.Puma::Reactor$$run_internal_9b3c548ef031cc1470bd839c282ebd5629ff06981802906423.file(/home/local1/monitors/local/localagent/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/reactor.rb)
at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:141)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
at org.jruby.ast.VCallNode.interpret(VCallNode.java:88)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
at org.jruby.runtime.Block.call(Block.java:101)
at org.jruby.RubyProc.call(RubyProc.java:300)
at org.jruby.RubyProc.call(RubyProc.java:230)
at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
at java.lang.Thread.run(Thread.java:745)

Locked ownable synchronizers:
- None

**Comment by yaauie** [comment]
You may want to consider upgrading your Logstash, as Logstash 5.x reached end-of-life in early 2019 when Logstash 7.0 landed (we simultaneously maintain three major branches at any given time -- NEXT, CURRENT, and PREVIOUS).

Since you are running Logstash 5.0 (released October 2016), you may benefit from at least upgrading to [Logstash 5.6.16](https://www.elastic.co/downloads/past-releases/logstash-5-6-16), which is backwards-compatible with all prior versions of 5.x and includes all available fixes on the 5.x series.

As per our issue template and issue guidelines, the Github issue tracker isn't the place for general debugging questions, so I am closing this issue. Please use the [logstash forum](https://discuss.elastic.co/c/logstash) moving forward.
