### ISSUE TITLE
[logstash.inputs.udp      ][syslog] Exception in inputworker {"exception"=>#<ArgumentError: invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by ninjape** [elastic/logstash#11758]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:
- Operating System:
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

**Comment by ninjape** [comment]
[2020-04-07T09:14:40,314][ERROR][logstash.inputs.udp      ][syslog] Exception in inputworker {"exception"=>#<ArgumentError: invalid byte sequence in UTF-8>, "backtrace"=>["org/jruby/RubyString.java:4075:in `split'", "org/logstash/common/BufferedTokenizerExt.java:58:in `extract'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-codec-line-3.0.8/lib/logstash/codecs/line.rb:38:in `decode'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-udp-3.3.4/lib/logstash/inputs/udp.rb:151:in `inputworker'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-input-udp-3.3.4/lib/logstash/inputs/udp.rb:63:in `block in run'"]}

Here is the whole error. Can anyone help me solve it? logstash version 7.6.2

**Comment by kares** [comment]
these kind of errors depend on the payload - reading data from the UDP inputs it has assumed UTF-8 encoding on the bytes
but some of the bytes were invalid.
