### ISSUE TITLE
error=>Worker loop initialization error, "Missing Filter End Vertex"

### ISSUE THREAD

**Issue by StefanSa** [elastic/logstash#11899]
Hi there,
Run the latest version of Logstash in Kube here.
logstash crashes when starting due to pipline problem.

- Version:
v7.7.0
- Operating System:
elastic docker image

- Config File (if you have sensitive info, please remove it):

`apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-logstash-configmap
  namespace: elastic-monitoring
data:
    
  logstash.yml: |
    xpack.monitoring.enabled: true
    xpack.monitoring.elasticsearch.username: ${ELASTICSEARCH_USERNAME}
    xpack.monitoring.elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
    xpack.monitoring.elasticsearch.hosts: ["https://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}"]
    xpack.monitoring.elasticsearch.ssl.certificate_authority: /mnt/elastic/tls.crt    

  pipelines.yml: |
    - pipeline.id: azureeventhubs
      path.config: "/usr/share/logstash/azureeventhubs.cfg"
  
  azureeventhubs.cfg: |
    input {
    }
    filter {
    }
    output {
      elasticsearch {
        hosts => [ "sample-elasticsearch:9200" ]
        user => "elastic"
        password => "Password1$"
        index => "azureeventhub-%{+YYYY.MM.dd}"
      }
    }

  logstash.conf: |`
- Sample Data:
`[2020-05-15T07:25:28,885][INFO ][logstash.javapipeline    ][azureeventhubs] Starting pipeline {:pipeline_id=>"azureeventhubs", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, "pipeline.sources"=>["/usr/share/logstash/azureeventhubs.cfg"], :thread=>"#<Thread:0x5f4a4b81 run>"}
[2020-05-15T07:25:28,889][ERROR][logstash.javapipeline    ][azureeventhubs] Worker loop initialization error {:pipeline_id=>"azureeventhubs", :error=>"Missing Filter End Vertex", :exception=>Java::JavaLang::IllegalStateException, :stacktrace=>"org.logstash.config.ir.CompiledPipeline$CompiledExecution.lambda$compileFilters$1(org/logstash/config/ir/CompiledPipeline.java:400)\njava.util.Optional.orElseThrow(java/util/Optional.java:408)\norg.logstash.config.ir.CompiledPipeline$CompiledExecution.compileFilters(org/logstash/config/ir/CompiledPipeline.java:400)\norg.logstash.config.ir.CompiledPipeline$CompiledExecution.<init>(org/logstash/config/ir/CompiledPipeline.java:382)\norg.logstash.config.ir.CompiledPipeline$CompiledUnorderedExecution.(org/logstash/config/ir/CompiledPipeline.java:342)\norg.logstash.config.ir.CompiledPipeline.buildExecution(org/logstash/config/ir/CompiledPipeline.java:160)\norg.logstash.execution.WorkerLoop.(org/logstash/execution/WorkerLoop.java:63)\njdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)\njdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(jdk/internal/reflect/NativeConstructorAccessorImpl.java:62)\njdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(jdk/internal/reflect/DelegatingConstructorAccessorImpl.java:45)\njava.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:490)\norg.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/JavaConstructor.java:253)\norg.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:939)\norg.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)\nusr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.init_worker_loop(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:500)\nusr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$init_worker_loop$0$__VARARGS__(usr/share/logstash/logstash_minus_core/lib/logstash//usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb)\nusr.share.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:268)\norg.jruby.RubyProc.call(org/jruby/RubyProc.java:318)\njava.lang.Thread.run(java/lang/Thread.java:834)", :thread=>"#"}
[2020-05-15T07:25:28,894][ERROR][logstash.javapipeline    ][azureeventhubs] Pipeline aborted due to error {:pipeline_id=>"azureeventhubs", :exception=>#<RuntimeError: Some worker(s) were not correctly initialized>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:271:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:170:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:125:in `block in start'"], "pipeline.sources"=>["/usr/share/logstash/azureeventhubs.cfg"], :thread=>"#"}
[2020-05-15T07:25:28,905][ERROR][logstash.agent           ] Failed to execute action {:id=>:azureeventhubs, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<azureeventhubs>, action_result: false", :backtrace=>nil}`

**Comment by muhalif** [comment]
I am receiving the same error on Windows 10 and Java 11.

**Comment by FireDrunk** [comment]
I've just 'fixed' this error because there was an empty .conf file in the logstash configuration folder. We're using the yml file, but the .conf wasn't properly deleted.

**Comment by kares** [comment]
somewhere along LS 7.10 empty .conf files issue got fixes and LS reads them properly, please let us know if it's still an issue ...
