### ISSUE TITLE
Fix integration tests run with PQ enabled and out of Docker

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#11924]
In the current master if we run the integration tests with FEATURE_FLAG=persistent_queue 
```
FEATURE_FLAG=persistent_queues ci/integration_tests.sh
```
we get some errors:
```
Failures:

1) Test Logstash Pipeline id should write logs with plugin name
   Failure/Error: expect(IO.read(plainlog_file) =~ /\[sleep_filter_123\] Sleeping {:delay=>1}/).to be > 0
         
     expected: > 0
          got:   nil
   # ./specs/plugin_name_log_spec.rb:61:in `block in <main>'
   # /home/andrea/workspace/logstash_andsel/build/qa/integration/vendor/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in <main>'
   # ./rspec.rb:32:in `<main>'

2) Test Monitoring API can retrieve queue stats
   Failure/Error: Unable to find matching line from backtrace
   
   KeyError:
     key not found: "data"

3) Test Logstash Pipeline id should not create separate pipelines log files if not enabled
   Failure/Error: expect(File.exists?(deprecation_log_file)).to be true

     expected true
          got false
   # ./specs/deprecation_log_spec.rb:63:in `block in <main>'
   # /home/andrea/workspace/logstash_andsel/build/qa/integration/vendor/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in <main>'
   # ./rspec.rb:32:in `<main>'

4) Test Logstash Pipeline id should write logs with pipeline.id
   Failure/Error: expect(IO.read(plainlog_file) =~ /\[logstash.javapipeline\s*\]\[#{pipeline_name}\]/).to be > 0

     expected: > 0
          got:   nil
   # ./specs/pipeline_log_spec.rb:62:in `block in <main>'
   # /home/andrea/workspace/logstash_andsel/build/qa/integration/vendor/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in <main>'
   # ./rspec.rb:32:in `<main>'

5) Test Logstash Pipeline id should separate pipeline output in its own log file
   Failure/Error: expect(File.exists?(pipeline_log_file)).to be true
   
     expected true
          got false
   # ./specs/pipeline_log_spec.rb:105:in `block in <main>'
   # /home/andrea/workspace/logstash_andsel/build/qa/integration/vendor/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in <main>'
   # ./rspec.rb:32:in `<main>'

Finished in 53 minutes 21 seconds (files took 3.01 seconds to load)
55 examples, 5 failures, 4 pending

Failed examples:

rspec ./specs/plugin_name_log_spec.rb:50 # Test Logstash Pipeline id should write logs with plugin name
rspec ./specs/monitoring_api_spec.rb:87 # Test Monitoring API can retrieve queue stats
rspec ./specs/deprecation_log_spec.rb:51 # Test Logstash Pipeline id should not create separate pipelines log files if not enabled
rspec ./specs/pipeline_log_spec.rb:51 # Test Logstash Pipeline id should write logs with pipeline.id
rspec ./specs/pipeline_log_spec.rb:93 # Test Logstash Pipeline id should separate pipeline output in its own log file
```

**Comment by andsel** [comment]
Point 1, 3, 4, 5 are solved by  #11929 while 2 by #11923
