### ISSUE TITLE
Numerous JDK integration tests failing because of path construction

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#11932]
A number of integration tests run in the JDK matrix are failing because of the way Jenkins constructs paths when testing in a matrix - creating paths including directories such as `centos-7&&immutable`. This is causing a number of [test failures](https://logstash-ci.elastic.co/job/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA=adoptopenjdk11,os=ubuntu-18.04&&immutable/53/console)

These errors include: 

```
14:26:00     rspec '/var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/specs/beats_input_spec.rb[1:2:2:1]' # Beat Input With TLS Mutual auth successfully send events
14:26:00     rspec '/var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/specs/beats_input_spec.rb[1:2:1:1]' # Beat Input With TLS Server auth successfully send events
14:26:00     rspec '/var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/specs/beats_input_spec.rb[1:1:1]' # Beat Input Without TLS successfully send events
14:26:00     rspec /var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/specs/01_logstash_bin_smoke_spec.rb:147 # Test Logstash instance gets the right version when asked
14:26:00     rspec /var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/specs/deprecation_log_spec.rb:51 # Test Logstash Pipeline id should not create separate pipelines log files if not enabled
14:26:00     rspec /var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/specs/es_output_how_spec.rb:34 # Test Elasticsearch output can ingest 37K log lines of sample apache logs
14:26:00     rspec /var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/specs/kafka_input_spec.rb:36 # Test Kafka Input can ingest 37 
```

This manifests with such errors as:

```
              ChildProcess::LaunchError:
14:26:00                 Cannot run program "/var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/services/installed/filebeat/filebeat" (in directory "/var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration"): error=2, No such file or directory
```

or

```
        1.2) Failure/Error: filebeat_service.stop
14:26:00               
14:26:00               NoMethodError:
14:26:00                 undefined method `stop' for nil:NilClass
14:26:00               # /var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/services/filebeat_service.rb:64:in `stop'
14:26:00               # /var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/specs/beats_input_spec.rb:33:in `block in <main>'
14:26:00               # /var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/build/qa/integration/vendor/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in <main>'
14:26:00               # /var/lib/jenkins/workspace/elastic+logstash+7.x+multijob-matrix-jdk-unix-integration-pq-1/LS_RUNTIME_JAVA/adoptopenjdk11/os/ubuntu-18.04&&immutable/qa/integration/rspec.rb:32:in `<main>'
14:26:00 
```

**Comment by robbavey** [comment]
Issue no longer present
