### ISSUE TITLE
Logstash giving Exception while running in command prompt

### ISSUE THREAD

**Issue by tushar1402** [elastic/logstash#12015]
Please post all product and debugging questions on our [forum](https://discuss.elastic.co/c/logstash). Your questions will reach our wider community members there, and if we confirm that there is a bug, then we can open a new issue here.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Logstash Plugins are located in a different organization: https://github.com/logstash-plugins. For bugs on specific Logstash plugins, for example, if Redis Output has a defect, please open it in the respective Redis Output repository. 

For all general issues, please provide the following details for fast resolution:

- Version:7.1.1
- Operating System: Windows 10
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce:

Hi, Earlier my logstash was working fine but suddenly it started giving me some exception. I uninstalled it and then installed again but the exception is still there. I am not able to figure out the exception and how to resolve it. Can you please help me out ASAP. I am posting the exception in below lines:

**EXCEPTION:**

C:\elastic_stack\logstash-7.7.1\logstash-7.7.1\bin>logstash.bat -f logstash.conf
Exception in thread "main" java.lang.ExceptionInInitializerError
        at org.apache.logging.log4j.core.util.WatchManager.<init>(WatchManager.java:53)
        at org.apache.logging.log4j.core.config.AbstractConfiguration.<init>(AbstractConfiguration.java:135)
        at org.apache.logging.log4j.core.config.NullConfiguration.<init>(NullConfiguration.java:32)
        at org.apache.logging.log4j.core.LoggerContext.<clinit>(LoggerContext.java:85)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.createContext(ClassLoaderContextSelector.java:179)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.locateContext(ClassLoaderContextSelector.java:153)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:78)
        at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.getContext(ClassLoaderContextSelector.java:65)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:148)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:581)
        at org.logstash.Logstash.<clinit>(Logstash.java:42)
Caused by: java.lang.ArrayIndexOutOfBoundsException
        at java.lang.System.arraycopy(Native Method)
        at org.apache.logging.log4j.core.util.UuidUtil.<clinit>(UuidUtil.java:81)
        ... 13 more

**Comment by jsvd** [comment]
Looking at https://issues.apache.org/jira/browse/LOG4J2-2650, this seems to be a bug in versions up to 2.12.0 of log4j and in systems where ipv6 is the default ip stack.
what was the version you had before 7.7.1, and did anything changed in the windows 10 deployment in that upgrade?

**Comment by tushar1402** [comment]
Hi,
I was using the version 7.7.1 earlier also. I have fixed the issue by changing the path of JAVA_HOME there was some issue there. I just pasted the same path again in environment variable and it started running fine do not know how.

I am facing a new error in my other machine where I am trying to run the logstash.
The error is: **Error: Could not find or load main class Stack\logstash-7.7.1\logstash-7.7.1\logstash-core\lib\jars\animal-sniffer-annotations-1.14.jar;C:\ELK**

Can you help me with this or should I open a new topic for this? Thanks for your quick response

**Comment by kares** [comment]
closing as defunct, if the issue still persist please open a new one using latest 7.x version
