### ISSUE TITLE
REE: newline at end of conf file fragment corrupts next conf file

### ISSUE THREAD

**Issue by yaauie** [elastic/logstash#12155]
Validated on Logstash 7.7.1, [7.x@{2020-07-30T00:00:00Z}](https://github.com/elastic/logstash/tree/7df59fbe762d2422b2107e4f7e4d4af5d833644d).

When:
 - the Ruby execution engine is selected (e.g., `--java-execution=false`); AND
 - the `--path.config` specifies a wildcard pattern matching multiple pipeline config fragments; AND
 - _any_ of those fragments ends with a trailing newline

The pipeline fails to start when attempting to determine the id of the _first_ plugin in the _next_ source file, e.g.:

~~~
[2020-07-30T20:33:33,096][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Could not determine ID for filter/mutate", :backtrace=>["org/logstash/plugins/factory/PluginFactoryExt.java:175:in `plugin'", "org/logstash/plugins/factory/PluginFactoryExt.java:161:in `plugin'", "/Users/yaauie/src/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:95:in `plugin'", "(eval):37:in `initialize'", "org/jruby/RubyKernel.java:1048:in `eval'", "/Users/yaauie/src/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:69:in `initialize'", "/Users/yaauie/src/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:114:in `initialize'", "/Users/yaauie/src/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52:in `execute'", "/Users/yaauie/src/elastic/logstash/logstash-core/lib/logstash/agent.rb:357:in `block in converge_state'"]}
~~~

This is caused by an off-by-one error, in which a `SourceWithMetadata` cannot be found in the graph because the graph has the entry for the plugin indexed as `line: 2, column: 3`, while the search is for `line: 3, column: 3` for the affected fragment:

> ~~~
> filter {
>   mutate {
>     add_field => { "003" => "THREE" }
>   }
> }
> ~~~

# Known Workaround:

Remove trailing newlines from each config fragment file

**Comment by yaauie** [comment]
@andsel: I think that the root issue is that we use `String#split` to count the lines:

> ~~~ java
>         this.linesCount = text.split("\\n").length;
> ~~~
> -- [logstash-core/src/main/java/org/logstash/common/SourceWithMetadata.java@v7.7.1:90](https://github.com/elastic/logstash/blob/v7.7.1/logstash-core/src/main/java/org/logstash/common/SourceWithMetadata.java#L90)

But:

> Trailing empty strings are therefore not included in the resulting array.
> -- [`String#split(String)`](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#split-java.lang.String-)

**Comment by andsel** [comment]
We could count the number of newlines character, something like:
```java
"Hello\nWorld\n\n\n\n".chars().filter(x -> x == '\n').count();
```
but if we have `\r` or `\r\n` we could think to use the Matcher to count:

```java
Matcher m = Pattern.compile("\r\n|\r|\n").matcher("Hello\nWorld\n\n\n");
int linesCount = 0;
while (m.find()) {
    linesCount++;
}
```

**Comment by yaauie** [comment]
I created a patch that used `String#split(String, int)` with `-1` for the second argument, which caused it to include an empty entry when there was a trailing newline, but on second thought, it is _weird_ for `SourceWithMetadata#getLinesCount()` to return `2` for the input `input { stdin {} }\n` because the newline is usually considered to be a part of the line.

Instead I am trying a fix that addresses the _concatenation_ of source files for our internal representation that joins sources on newline whether or not they already had a trailing newline, by pre-normalizing to chomp trailing newlines before we perform the concatenation.
