### ISSUE TITLE
Logstash config_init problem with 

### ISSUE THREAD

**Issue by arichiardi** [elastic/logstash#12332]
Hi everybody I am new to ruby and logstash but I might have found an issue with the plugin code. 

Please feel free to disregard if not :smile: Also, sorry if you see me spamming on IRC :wink: 

I was working on a contribution to `logstash-output-mongo` and I have by mistake inputted the following as one of my config params:

`{"$inc" => {"quantity": 1}}`

This causes the following to be triggered at instance creation (`LogStash::Outputs::Mongodb.new(config)`):

```
     Failure/Error: subject! { LogStash::Outputs::Mongodb.new(config) }
     
     RuntimeError:
       can't add a new key into hash during iteration
     # /src/logstash/logstash-core/lib/logstash/util/substitution_variables.rb:35:in `block in deep_replace'
     # /src/logstash/logstash-core/lib/logstash/util/substitution_variables.rb:34:in `deep_replace'
     # /src/logstash/logstash-core/lib/logstash/util/substitution_variables.rb:35:in `block in deep_replace'
     # /src/logstash/logstash-core/lib/logstash/util/substitution_variables.rb:34:in `deep_replace'
     # /src/logstash/logstash-core/lib/logstash/config/mixin.rb:99:in `block in config_init'
     # /src/logstash/logstash-core/lib/logstash/config/mixin.rb:98:in `config_init'
     # /src/logstash/logstash-core/lib/logstash/outputs/base.rb:76:in `initialize'
     # ./spec/outputs/mongodb_config_validation_spec.rb:13:in `block in subject'

```

It all works well with  `{"$inc" => {"quantity"=> 1}}` instead.

I am running inside the [logstash-plugin-dev](https://github.com/cameronkerrnz/logstash-plugin-dev) Docker container and that should have the following:

- Version: [`--branch 7.9`](https://github.com/cameronkerrnz/logstash-plugin-dev/blob/master/Dockerfile#L68)
- Operating System: ` centos:7`

- Sample Data:
- Steps to Reproduce:  in any pluging add `config :filter, :validate => :hash, :required => false, :default => {}` and assign `{"$inc" => {"quantity": 1}}` to it.

Thanks a lot in advance.

**Comment by andsel** [comment]
Hi @arichiardi thanks for the test, in the [documentation of Logstash](https://www.elastic.co/guide/en/logstash/current/configuration.html) the parameters maps are always defined with `=>`, so the first `{"$inc" => {"quantity": 1}}` is correct that Logstash doesn't parse it. 
Are your concerns about the error reporting? 
Do you mean it should raise a " configuration exception" instead of a RuntimeError?

**Comment by jhass** [comment]
https://github.com/elastic/logstash/blob/ecbad2a2305a6fb92544d75b8b46f4200ef205b8/logstash-core/lib/logstash/util/substitution_variables.rb#L34-L36

The above attempts to normalize to string keys, bad fails so at it. So yes, either input should be properly validated or the above should be fixed using for example https://rubyapi.org/2.7/o/hash#method-i-transform_keys

**Comment by arichiardi** [comment]
@andsel yes error reporting can definitely be improved but as @jhass says above, it seems something else is going on.

I am a Ruby novice so I cannot really help more in this case. Sorry about that!

**Comment by andsel** [comment]
@arichiardi could you share your pipeline config file?

**Comment by arichiardi** [comment]
I would have to craft it for a repro that's why I extracted the bit above, I will try my best for a smaller chunk

**Comment by andsel** [comment]
We have the `mutate` filter that accepts hashes as params, (for example the `rename` operation) if you are able to reproduce with a simple mutate configuration would be great

**Comment by arichiardi** [comment]
@andsel I tried what you said but it seems that fails in a different way:

```
Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"=>\" at line 12, column 32 (byte 202) after filter 
```

with

```
rename => { "delta" => { "testme" => "%{hostname[0]}" }}
```

It seems the conf does not accept a nested hash?

**Comment by andsel** [comment]
Yes that results in a compilation error, that's why I asked for your configuration, probably related to the plugin code, I suppose, else it should give the same compilation error.

**Comment by jhass** [comment]
By the way none of this changes anything about my statement above, that the above code is inherently unable to fulfill its apparent intent of normalizing the hash to string keys :) Here's a minimal production of the error: https://carc.in/#/r/9ut6

**Comment by andsel** [comment]
@jhass you are right, but I would like to know how to reproduce it in the context of plugin configuration. If the the configuration compiler avoid to have nested maps, that error shouldn't happen

**Comment by arichiardi** [comment]
Oh I actually understood you wanted a repro with mutate.

I will be sending Mongo config and sample error.

Thanks!
