### ISSUE TITLE
Inability to express a single backslash in the pipeline configuration

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#12423]
from recent attempts I wasn't able to express in the logstash configuration a single backslash.
The use case is, for example, in the mutate filter replacing two backslashes with one. Without surprises, the following should work:

```
input { tcp {  port => 3333 } }
filter {
  mutate { gsub => [ "message", "\\\\", "\\" ] }
}
output { stdout { } 
```

But this creates an error while trying to parse the third element of gsub, the single backslash:

```
[2020-11-07T16:47:49,350][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Expected one of [ \\t\\r\\n], \"#\", \"{\", \",\", \"]\" at line 3, column 42 (byte 83) after filter {\n  mutate { gsub => [ \"message\", \"\\\\\\\\\", \"", :backtrace=>["/private/tmp/logstash-7.9.3/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:183:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:69:in `initialize'", "/private/tmp/logstash-7.9.3/logstash-core/lib/logstash/pipeline_action/reload.rb:53:in `execute'", "/private/tmp/logstash-7.9.3/logstash-core/lib/logstash/agent.rb:357:in `block in converge_state'"]}
```

Using single quotes also doesn't allow this to work. Enabling `config.support_escapes` also doesn't solve the problem.

**Comment by yaauie** [comment]
Related: https://github.com/elastic/logstash/issues/9701
