### ISSUE TITLE
logstash fails to log configuration error message

### ISSUE THREAD

**Issue by kares** [elastic/logstash#12484]
there's a common pattern some plugins follow: `raise LogStash::ConfigurationError` and assume it will be logged by LS.

here's a difference of running LS with beats input which [fails on a configuration issue](https://github.com/logstash-plugins/logstash-input-beats/blob/v6.0.11/lib/logstash/inputs/beats.rb#L142):

7.6.0
```
[2020-11-30T11:46:55,196][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.6.0"}
[2020-11-30T11:46:58,666][INFO ][org.reflections.Reflections] Reflections took 53 ms to scan 1 urls, producing 20 keys and 40 values 
[2020-11-30T11:46:59,384][WARN ][org.logstash.instrument.metrics.gauge.LazyDelegatingGauge][main] A gauge metric of an unknown type (org.jruby.RubyArray) has been create for key: cluster_uuids. This may result in invalid serialization.  It is recommended to log an issue to the responsible developer/development team.
[2020-11-30T11:46:59,410][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>16, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>2000, "pipeline.sources"=>["/home/kares/workspace/work/elastic/plugins/logstash-input-beats/logstash-tls.conf"], :thread=>"#<Thread:0xad1fe10 run>"}
[2020-11-30T11:47:00,864][ERROR][logstash.javapipeline    ][main] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<LogStash::ConfigurationError: Using `verify_mode` set to PEER or FORCE_PEER, requires the configuration of `certificate_authorities`>, :backtrace=>["/home/kares/workspace/work/elastic/logstash-7.6.0/vendor/bundle/jruby/2.5.0/gems/logstash-input-beats-6.0.4-java/lib/logstash/inputs/beats.rb:148:in `register'", "/home/kares/workspace/work/elastic/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:200:in `block in register_plugins'", "org/jruby/RubyArray.java:1814:in `each'", "/home/kares/workspace/work/elastic/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:199:in `register_plugins'", "/home/kares/workspace/work/elastic/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:310:in `start_inputs'", "/home/kares/workspace/work/elastic/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:270:in `start_workers'", "/home/kares/workspace/work/elastic/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:154:in `run'", "/home/kares/workspace/work/elastic/logstash-7.6.0/logstash-core/lib/logstash/java_pipeline.rb:109:in `block in start'"], "pipeline.sources"=>["/home/kares/workspace/work/elastic/plugins/logstash-input-beats/logstash-tls.conf"], :thread=>"#<Thread:0xad1fe10 run>"}
[2020-11-30T11:47:00,911][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2020-11-30T11:47:01,509][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2020-11-30T11:47:06,399][INFO ][logstash.runner          ] Logstash shut down.
```

7.8.1 (and >=)
```
[2020-11-30T11:47:37,247][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.8.1", "jruby.version"=>"jruby 9.2.11.1 (2.5.7) 2020-03-25 b1f55b1a40 Java HotSpot(TM) 64-Bit Server VM 25.171-b11 on 1.8.0_171-b11 +indy +jit [linux-x86_64]"}
[2020-11-30T11:47:38,719][INFO ][org.reflections.Reflections] Reflections took 25 ms to scan 1 urls, producing 21 keys and 41 values 
[2020-11-30T11:47:39,092][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>16, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>2000, "pipeline.sources"=>["/home/kares/workspace/work/elastic/plugins/logstash-input-beats/logstash-tls.conf"], :thread=>"#<Thread:0x67287766 run>"}
[2020-11-30T11:47:39,881][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2020-11-30T11:47:40,042][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2020-11-30T11:47:45,093][INFO ][logstash.runner          ] Logstash shut down.
```
... not knowing what was wrong (printing a message of the configuration error on level >= INFO) has impacted user experience

for the record, it's probably best to handle logging at Beats plugin's end but LS should still at least print a message.

**Comment by kares** [comment]
potentially related issue: https://github.com/elastic/logstash/issues/11756

**Comment by kares** [comment]
great investigation @andsel - indeed we do have some logging since [the change](https://github.com/elastic/logstash/pull/12307/files#diff-f1d310cd201ca9fcfad2f54ecdfd588cc476eb5ecee6939e330547eed0476208R140) in #12307
