### ISSUE TITLE
Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 1, column 1 (byte 1)

### ISSUE THREAD

**Issue by ZoolYe** [elastic/logstash#12495]
`logstash 7.10.0`
- logstash.conf(UTF-8)
```
input { stdin { } }
output {
  elasticsearch { hosts => ["192.168.2.98:9200"] }
  stdout { codec => rubydebug }
}
```
### Startup failed with the following error
---
<?
[2020-12-03T07:58:12,602][ERROR][logstash.agent ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of [ \\t\\r\\n], \"#\", \"input\", \"filter\", \"output\" at line 1, column 1 (byte 1)", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:32:in `compile_imperative'", "org/logstash/execution/AbstractPipelineExt.java:184:in `initialize'", "org/logstash/execution/JavaBasePipelineExt.java:69:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:47:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:365:in `block in converge_state'"]}

**Comment by jsvd** [comment]
I can't reproduce that issue. looking at your configuration it seems to have some non-expected characters in the first line, like the error message says (it's neither a new line, a comment, or one of the input/filter/output sections).

This doesn't seem to be a bug. I apologize for the inconvenience, but this is a usage question, and should be asked at https://discuss.elastic.co.
