### ISSUE TITLE
[7.13] GeoIP multiple instances cause Bad file descriptor 

### ISSUE THREAD

**Issue by kaisecheng** [elastic/logstash#13072]
Logstash version: 7.13.2
geoip-filter version: 7.1.3
java version: openjdk 11.0.10
OS: macOS Catalina

Although geoip plugin has disabled the database auto-download, it is still suffered from multiple instances copying the database to the same path. User sometimes observes "Bad file descriptor" or  "The database provided is invalid or corrupted" error when the plugin failed to initialize databases in `$logstash_home/data/plugins/filters/geoip/*.mmdb`. 

A workaround is to start Logstash with a single `geoip { }` config.  Once the databases are copied successfully, user will not encounter the error again. User can enable multiple `geoip { }` after the first run.

There is a similar issue #12856.  7.14 has fixed multiple instances issues.

Sample config
```
input { heartbeat { message => '1.1.1.1' interval => 10 } } 
filter {  geoip { source => 'message'} geoip { source => 'message'}  } 
output { stdout { codec => dots } }
```

Exception Log
```
:exception=>#<Errno::EBADF: Bad file descriptor - Bad file descriptor>, :backtrace=>["org/jruby/RubyIO.java:4351:in `copy_stream'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1388:in `block in copy_file'", "org/jruby/RubyIO.java:1158:in `open'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1387:in `block in copy_file'", "org/jruby/RubyIO.java:1158:in `open'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1386:in `copy_file'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1354:in `copy'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:474:in `block in copy_entry'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1485:in `wrap_traverse'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:471:in `copy_entry'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:449:in `block in cp_r'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1558:in `block in fu_each_src_dest'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1567:in `block in fu_each_src_dest0'", "org/jruby/RubyArray.java:1809:in `each'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1565:in `fu_each_src_dest0'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:1556:in `fu_each_src_dest'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/fileutils.rb:448:in `cp_r'", "/usr/share/logstash/x-pack/lib/filters/geoip/database_manager.rb:75:in `prepare_cc_db'", "/usr/share/logstash/x-pack/lib/filters/geoip/database_manager.rb:36:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-geoip-7.1.3-java/lib/logstash/filters/geoip.rb:180:in `select_database_path'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-filter-geoip-7.1.3-java/lib/logstash/filters/geoip.rb:109:in `register'", "org/logstash/config/ir/compiler/AbstractFilterDelegatorExt.java:75:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:228:in `block in register_plugins'", "org/jruby/RubyArray.java:1809:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:227:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:586:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:240:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:185:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:137:in `block in start'"]
```

**Comment by kaisecheng** [comment]
fixed in 7.13.4
