### ISSUE TITLE
Logstash monitoring endpoint should handle exceptions if no pipeline is currently running

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/logstash#13258]
**Logstash information**:

Please include the following information:

1. **Logstash version (e.g. `bin/logstash --version`)** 7.13+ (but previous versions might be affected, too)
2. **Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)** Not relevant
3. **How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)** Not relevant

**Description of the problem including expected versus actual behavior**:

When using Pipeline central management and no pipeline is found, when we access the Monitoring Endpoint it triggers the exception, returning an invalid response.

Rest API response has error code 500 with the exception:
```
{"status":500,"request_method":"GET","path_info":"/_node/stats","query_string":"","http_version":"HTTP/1.1","http_accept":"*/*","error":"Unexpected Internal Error","class":"LogStash::Instrument::MetricStore::MetricNotFound","message":"For path: events. Map keys: [:reloads]","backtrace":["/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'","org/jruby/RubyArray.java:1809:in `each'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'","org/jruby/RubyArray.java:1809:in `each'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'","org/jruby/ext/thread/Mutex.java:164:in `synchronize'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'","org/jruby/RubyArray.java:1809:in `each'","org/jruby/RubyEnumerable.java:1126:in `inject'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:57:in `events_payload'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in NodeStats'","org/jruby/RubyMethod.java:115:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'","org/jruby/RubyKernel.java:1189:in `catch'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'","org/jruby/RubyArray.java:1809:in `each'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'","org/jruby/RubyKernel.java:1189:in `catch'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'","org/jruby/RubyKernel.java:1189:in `catch'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'","org/jruby/RubyArray.java:1809:in `each'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:718:in `handle_request'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:472:in `process_client'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:328:in `block in run'","/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/thread_pool.rb:134:in `block in spawn_thread'"]}%
```

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Setup Logstash with `xpack.management.enabled: true` and pipeline ID pointing to non-existing pipelines, e.g. `xpack.management.pipeline.id: ["some*"]`
 2. Start Logstash
 3. Run `curl http://localhost:9600/_node/stats

**Provide logs (if relevant)**:

```
[2021-09-30T11:28:36,233][DEBUG][logstash.agent           ] 2021-09-30 11:28:36 - LogStash::Instrument::MetricStore::MetricNotFound - For path: events. Map keys: [:reloads]:
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'
	org/jruby/RubyArray.java:1809:in `each'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'
	org/jruby/RubyArray.java:1809:in `each'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'
	org/jruby/ext/thread/Mutex.java:164:in `synchronize'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'
	org/jruby/RubyArray.java:1809:in `each'
	org/jruby/RubyEnumerable.java:1126:in `inject'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:57:in `events_payload'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in NodeStats'
	org/jruby/RubyMethod.java:115:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'
	org/jruby/RubyKernel.java:1189:in `catch'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'
	org/jruby/RubyArray.java:1809:in `each'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	org/jruby/RubyKernel.java:1189:in `catch'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	org/jruby/RubyKernel.java:1189:in `catch'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'
	org/jruby/RubyArray.java:1809:in `each'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:718:in `handle_request'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:472:in `process_client'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:328:in `block in run'
	/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
[2021-09-30T11:28:36,236][ERROR][logstash.agent           ] Internal API server error {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats", :query_string=>"", :http_version=>"HTTP/1.1", :http_accept=>"*/*", :error=>"Unexpected Internal Error", :class=>"LogStash::Instrument::MetricStore::MetricNotFound", :message=>"For path: events. Map keys: [:reloads]", :backtrace=>["/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:241:in `block in get_recursively'", "org/jruby/RubyArray.java:1809:in `each'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:251:in `block in get_recursively'", "org/jruby/RubyArray.java:1809:in `each'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:240:in `get_recursively'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:111:in `block in get'", "org/jruby/ext/thread/Mutex.java:164:in `synchronize'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:110:in `get'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:124:in `get_shallow'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:173:in `block in extract_metrics'", "org/jruby/RubyArray.java:1809:in `each'", "org/jruby/RubyEnumerable.java:1126:in `inject'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/instrument/metric_store.rb:149:in `extract_metrics'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/service.rb:45:in `extract_metrics'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/base.rb:37:in `extract_metrics'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/commands/stats.rb:73:in `events'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:57:in `events_payload'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/modules/node_stats.rb:37:in `block in NodeStats'", "org/jruby/RubyMethod.java:115:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1675:in `block in compile!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1032:in `route_eval'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1013:in `block in route!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1061:in `block in process_route'", "org/jruby/RubyKernel.java:1189:in `catch'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1059:in `process_route'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1011:in `block in route!'", "org/jruby/RubyArray.java:1809:in `each'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1008:in `route!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1129:in `block in dispatch!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'", "org/jruby/RubyKernel.java:1189:in `catch'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1124:in `dispatch!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'", "org/jruby/RubyKernel.java:1189:in `catch'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/null_logger.rb:11:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:74:in `block in call'", "org/jruby/RubyArray.java:1809:in `each'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/urlmap.rb:58:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:74:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/logstash-core/lib/logstash/api/rack_app.rb:48:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/rack-2.2.3/lib/rack/builder.rb:244:in `call'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:718:in `handle_request'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:472:in `process_client'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/server.rb:328:in `block in run'", "/Users/x/Elastic/Products/logstash-7.13.3/vendor/bundle/jruby/2.5.0/gems/puma-4.3.8-java/lib/puma/thread_pool.rb:134:in `block in spawn_thread'"]}
[2021-09-30T11:28:36,237][ERROR][logstash.agent           ] API HTTP Request {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats", :query_string=>"", :http_version=>"HTTP/1.1", :http_accept=>"*/*"}
```

**Comment by andsel** [comment]
This happen because the path `[:stats, :events]` in the metric tree doesn't exits, it contains only `:reloads`. The point where those metrics are populated is maybe in the PipelineRunner, a solution could be to initialize that metric outside the runner so that it's accessible also if no pipelines is running, with a default 0 value.

**Comment by yaauie** [comment]
@andsel I would prefer that the query API is _resilient_ to a metric not being populated, as proposed in #13424. While it may be worthwhile to pre-seed these metrics with zeroes in advance of the API starting up, we will invariably run into the issue again if we introduce a new metric in that namespace and fail to also pre-seed it.
