### ISSUE TITLE
Plugin Install Fails on 7.15.1 or later

### ISSUE THREAD

**Issue by Evesy** [elastic/logstash#13404]
**Logstash information**:

Please include the following information:

1. Logstash version: >= 7.15.1 
2. Logstash installation source: Tar archive
3. How is Logstash being run: Docker

1. JVM version: 11.0.11
2. JVM installation source: Tar archive

**OS version**: CentOS 8

**Description of the problem including expected versus actual behavior**:

When installing the `google_cloud_storage` input plugin in a docker image via `bin/logstash-plugin install logstash-input-google_cloud_storage` we see the below error on versions 7.15.1 or 7.15.2:

```
Step 12/24 : RUN bin/logstash-plugin install logstash-input-google_cloud_storage
 ---> Running in 5ebb3ec7c600
Using JAVA_HOME defined java: /usr/lib/jvm/adoptopenjdk-11-hotspot
WARNING, using JAVA_HOME while Logstash distribution comes with a bundled JDK
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Validating logstash-input-google_cloud_storage
Resolving mixin dependencies
Installing logstash-input-google_cloud_storage
Error Bundler::InstallError, retrying 1/10
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/mimemagic-0.4.3/ext/mimemagic
/usr/share/logstash/vendor/jruby/bin/jruby -I/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems -rrubygems /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rake-12.3.3/exe/rake RUBYARCHDIR\=/usr/share/logstash/vendor/bundle/jruby/2.5.0/extensions/universal-java-11/2.5.0/mimemagic-0.4.3 RUBYLIBDIR\=/usr/share/logstash/vendor/bundle/jruby/2.5.0/extensions/universal-java-11/2.5.0/mimemagic-0.4.3
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Bundler::GemNotFound: Could not find gem 'logstash-input-google_cloud_storage' in locally installed gems.

  verify_gemfile_dependencies_are_found! at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/resolver.rb:278
                                    each at org/jruby/RubyArray.java:1820
  verify_gemfile_dependencies_are_found! at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/resolver.rb:253
                                   start at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/resolver.rb:50
                                 resolve at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/resolver.rb:23
                                 resolve at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/definition.rb:262
                             materialize at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/definition.rb:483
                               specs_for at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/definition.rb:234
                                   setup at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/runtime.rb:18
                                   setup at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler.rb:149
                                  <main> at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/setup.rb:20
                              with_level at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/ui/shell.rb:136
                                 silence at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/ui/shell.rb:88
                                  <main> at /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/setup.rb:20
                                 require at org/jruby/RubyKernel.java:974
                                 require at /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:83

rake failed, exit code 1

Gem files will remain installed in /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/mimemagic-0.4.3 for inspection.
Results logged to /usr/share/logstash/vendor/bundle/jruby/2.5.0/extensions/universal-java-11/2.5.0/mimemagic-0.4.3/gem_make.out

  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:99:in `run'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/rake_builder.rb:30:in `build'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:169:in `block in build_extension'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/monitor.rb:237:in `block in mon_synchronize'
  org/jruby/RubyThread.java:759:in `handle_interrupt'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/monitor.rb:236:in `block in mon_synchronize'
  org/jruby/RubyThread.java:759:in `handle_interrupt'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/monitor.rb:233:in `mon_synchronize'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:165:in `build_extension'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:210:in `block in build_extensions'
  org/jruby/RubyArray.java:1820:in `each'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:207:in `build_extensions'
  /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/installer.rb:844:in `build_extensions'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/rubygems_gem_installer.rb:66:in `build_extensions'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/source/rubygems.rb:189:in `install'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/installer/gem_installer.rb:54:in `install'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/installer/gem_installer.rb:21:in `install_from_spec'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/worker.rb:62:in `apply_func'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/worker.rb:57:in `block in process_queue'
  org/jruby/RubyKernel.java:1442:in `loop'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/worker.rb:54:in `process_queue'
  /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.28/lib/bundler/worker.rb:91:in `block in create_threads'

An error occurred while installing mimemagic (0.4.3), and Bundler cannot continue.

In Gemfile:
  logstash-input-google_cloud_storage was resolved to 0.11.1, which depends on
    mimemagic
Error Bundler::InstallError, retrying 2/10
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
```

This works OK on versions 7.15.0 or earlier.

It looks like it may be related to the change introduced in https://github.com/elastic/logstash/pull/13268

**Steps to reproduce**:

1. Create a simple Dockerfile like the below (Our actual image is quite different, below is minimal I could create to reproduce):
```
FROM centos:8

ARG ES_VERSION=7.15.0
RUN curl -Lo - https://artifacts.elastic.co/downloads/logstash/logstash-$ES_VERSION-linux-x86_64.tar.gz | \
    tar zxf - -C /usr/share && \
    mv /usr/share/logstash-$ES_VERSION /usr/share/logstash && \
    ln -s /usr/share/logstash /opt/logstash

RUN yum clean all && yum install -y shared-mime-info

RUN /usr/share/logstash/bin/logstash-plugin install logstash-input-google_cloud_storage
```

 2. Run `docker build .` -- This will succeed
 3. Update `ES_VERSION` to `7.15.1` and run the build again, it will fail with the above error

**Comment by kaisecheng** [comment]
@Evesy Thanks for reporting the bug! I confirmed it is a problem from #13268 :(
A workaround now is to install the plugin with no verify flag
`bin/logstash-plugin install --no-verify logstash-input-google_cloud_storage`

**Comment by Evesy** [comment]
Thanks @kaisecheng for getting back so quickly (and for fixing so quickly too)!

Can confirm the install works with `--no-verify` on `7.15.2`

**Comment by kaisecheng** [comment]
This issue is fixed in v7.17.0

**Comment by abirsi** [comment]
> This issue is fixed in v7.17.0 @kaisecheng 

This issue is not fixed in 7.17.0, same problem exactly is still accruing.

**Comment by lshahar** [comment]
checked now with 8.0.2 and also not working...

**Comment by kaisecheng** [comment]
@abirsi @lshahar I download a fresh v7.17.0 and install the plugin successfully `bin/logstash-plugin install logstash-input-google_cloud_storage`

What is your error message? What is your OS?

@lshahar v8.0.2 is not released yet.

**Comment by Evesy** [comment]
I've actually found that even on `7.15.1` I can no longer actually successfully install the GCS plugin:

```
#10 [ 5/13] RUN bin/logstash-plugin install --no-verify logstash-input-google_cloud_storage
#10 0.597 Using JAVA_HOME defined java: /opt/java/openjdk
#10 0.597 WARNING: Using JAVA_HOME while Logstash distribution comes with a bundled JDK.
#10 0.597 DEPRECATION: The use of JAVA_HOME is now deprecated and will be removed starting from 8.0. Please configure LS_JAVA_HOME instead.
#10 0.807 OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
#10 8.347 Installing logstash-input-google_cloud_storage
#10 30.80 Error Bundler::InstallError, retrying 1/10
#10 30.80 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#10 30.80 
#10 30.80     current directory: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/mimemagic-0.4.3/ext/mimemagic
#10 30.80 /usr/share/logstash/vendor/jruby/bin/jruby -I/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems -rrubygems /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rake-12.3.3/exe/rake RUBYARCHDIR\=/usr/share/logstash/vendor/bundle/jruby/2.5.0/extensions/universal-java-11/2.5.0/mimemagic-0.4.3 RUBYLIBDIR\=/usr/share/logstash/vendor/bundle/jruby/2.5.0/extensions/universal-java-11/2.5.0/mimemagic-0.4.3
#10 30.80 OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
#10 30.80 rake aborted!
#10 30.80 Could not find MIME type database in the following locations: ["/usr/local/share/mime/packages/freedesktop.org.xml", "/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/opt/local/share/mime/packages/freedesktop.org.xml", "/usr/share/mime/packages/freedesktop.org.xml"]
#10 30.80 
#10 30.80 Ensure you have either installed the shared-mime-info package for your distribution, or
#10 30.80 obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to the location
#10 30.80 of that file.
#10 30.80 /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/mimemagic-0.4.3/ext/mimemagic/Rakefile:15:in `locate_mime_database'
#10 30.80 /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/mimemagic-0.4.3/ext/mimemagic/Rakefile:26:in `block in <main>'
#10 30.80 /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rake-12.3.3/exe/rake:27:in `<main>'
#10 30.80 Tasks: TOP => default
#10 30.80 (See full trace by running task with --trace)
#10 30.80 
#10 30.80 rake failed, exit code 1
#10 30.80 
#10 30.80 Gem files will remain installed in /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/mimemagic-0.4.3 for inspection.
#10 30.80 Results logged to /usr/share/logstash/vendor/bundle/jruby/2.5.0/extensions/universal-java-11/2.5.0/mimemagic-0.4.3/gem_make.out
#10 30.80 
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:99:in `run'
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/rake_builder.rb:30:in `build'
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:169:in `block in build_extension'
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/monitor.rb:237:in `block in mon_synchronize'
#10 30.80   org/jruby/RubyThread.java:759:in `handle_interrupt'
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/monitor.rb:236:in `block in mon_synchronize'
#10 30.80   org/jruby/RubyThread.java:759:in `handle_interrupt'
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/monitor.rb:233:in `mon_synchronize'
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:165:in `build_extension'
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:210:in `block in build_extensions'
#10 30.80   org/jruby/RubyArray.java:1821:in `each'
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/ext/builder.rb:207:in `build_extensions'
#10 30.80   /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems/installer.rb:844:in `build_extensions'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/rubygems_gem_installer.rb:28:in `install'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/source/rubygems.rb:194:in `install'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:54:in `install'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/installer/gem_installer.rb:21:in `install_from_spec'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/worker.rb:62:in `apply_func'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/worker.rb:57:in `block in process_queue'
#10 30.80   org/jruby/RubyKernel.java:1442:in `loop'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/worker.rb:54:in `process_queue'
#10 30.80   /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.2.33/lib/bundler/worker.rb:91:in `block in create_threads'
#10 30.80 
#10 30.80 An error occurred while installing mimemagic (0.4.3), and Bundler cannot continue.
#10 30.80 
#10 30.80 In Gemfile:
#10 30.80   logstash-input-google_cloud_storage was resolved to 0.11.1, which depends on
#10 30.80     mimemagic
```

**Comment by kaisecheng** [comment]
@Evesy I did a quick check on a fresh v7.15.1 and I cannot see error with `--no-verify`
You seem to run the command in Dockerfile. I notice that your JAVA_HOME has changed.
Can you share your Dockerfile or any steps for reproduction?

**Comment by Evesy** [comment]
Apologies, seems I now need to install `shared-mime-info` in my image. I checked the images we build from and it was never explicitly installed in there, but there's a chance it was pulled in as a dependency by something that has since been removed.

For me I can confirm the install works in `7.17.0` without `--no-verify`

**Comment by lshahar** [comment]
> @abirsi @lshahar I download a fresh v7.17.0 and install the plugin successfully `bin/logstash-plugin install logstash-input-google_cloud_storage`
> 
> What is your error message? What is your OS?
> 
> @lshahar v8.0.2 is not released yet.

Sorry it tested with 
docker.elastic.co/logstash/logstash:8.0.1
docker.elastic.co/logstash/logstash:7.17.2

only with docker.elastic.co/logstash/logstash:7.15.2 the installation works.

here is our Dockerfile
```
FROM docker.elastic.co/logstash/logstash:7.15.2
RUN bin/logstash-plugin install --no-verify logstash-input-google_cloud_storage
ADD pipeline /usr/share/logstash/pipeline/
ADD config /usr/share/logstash/config/
```

**Comment by kaisecheng** [comment]
@lshahar Thanks for providing the Dockerfile. I can reproduce the problem in docker. The original fix delivered in 7.17.0 work in centos, ubuntu, tarball but fail in docker. Sadly, starting from 7.17.0, `--no-verify` does not work in docker as well. We need to create a new issue to trace the problem.

Thanks everyone for testing the feature and reporting the issue.

**Comment by abirsi** [comment]
@kaisecheng 
The bottom line is that the bug is not fully resolved and still happening in Docker environment.
In the newer version of Logstash 7.17.* you can't install the plugin **even when using the --no-verify flag**.
Can we reopen this issue?

The Dockerfile:
```
FROM logstash:7.17.1

RUN bin/logstash-plugin install --no-verify logstash-input-google_cloud_storage
```
The error:
```
#5 48.47 An error occurred while installing mimemagic (0.4.3), and Bundler cannot continue.
#5 48.47
#5 48.47 In Gemfile:
#5 48.47   logstash-input-google_cloud_storage was resolved to 0.11.1, which depends on
#5 48.47     mimemagic
#5 59.73 Error Bundler::InstallError, retrying 4/10
#5 59.73 Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
#5 59.73
#5 59.73     current directory: /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/mimemagic-0.4.3/ext/mimemagic
#5 59.73 /usr/share/logstash/vendor/jruby/bin/jruby -I/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/rubygems -rrubygems /usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/rake-12.3.3/exe/rake RUBYARCHDIR\=/usr/share/logstash/vendor/bundle/jruby/2.5.0/extensions/universal-java-11/2.5.0/mimemagic-0.4.3 RUBYLIBDIR\=/usr/share/logstash/vendor/bundle/jruby/2.5.0/extensions/universal-java-11/2.5.0/mimemagic-0.4.3
#5 59.73 OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
#5 59.73 rake aborted!
#5 59.73 Could not find MIME type database in the following locations: ["/usr/local/share/mime/packages/freedesktop.org.xml", "/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/opt/local/share/mime/packages/freedesktop.org.xml", "/usr/share/mime/packages/freedesktop.org.xml"]
```

**Comment by yaauie** [comment]
The error that you are seeing is similar to, bit different than the one that was solved in 7.17 series. It indicates that the mime type database cannot be found, and indicates where it looked. It is possible that manually installing the `shared-mime-info` package (which contains such a database) as a part of your container definition is required, as s it appears that this is a dependency of the Google cloud storage input plugin. 

~~~
sudo apt-get install shared-mime-info
~~~

**Comment by kaisecheng** [comment]
@abirsi The dependency on `freedesktop.org.xml` by `mimemagic` is not managed by Logstash. In other words, Logstash/ bundler/ Google cloud storage plugin do not know `mimemagic` requires a particular XML in the host system to work. Therefore, logstash plugin script cannot help to resolve this issue.

To install it, you need to download  `freedesktop.org.xml` from [freedesktop.org](https://cgit.freedesktop.org/xdg/shared-mime-info/plain/freedesktop.org.xml.in?h=Release-1-15) and make your Dockerfile
```
FROM docker.elastic.co/logstash/logstash:8.0.1
COPY freedesktop.org.xml /usr/share/mime/packages/freedesktop.org.xml
RUN bin/logstash-plugin install logstash-input-google_cloud_storage
```

**Comment by kaisecheng** [comment]
you can also install `share-mime-info` and `google_cloud_storage` plugin by the following steps
```
FROM docker.elastic.co/logstash/logstash:8.0.1
USER root
RUN apt-get install -y shared-mime-info
USER logstash
RUN bin/logstash-plugin install logstash-input-google_cloud_storage
```

**Comment by abirsi** [comment]
@kaisecheng This is what I eventually did.

I believe that it will be better if `share-mime-info` will be already installed in the Logstash base image.
(Or only `freedesktop.org.xml` file will be added to it)
This way people could install this plugin without adding any dependencies.

I don't know what is the approach in Logstash,
But I believe that I should be able to install any plugin using only the installation script :)
