### ISSUE TITLE
ConcurrencyError: interrupted waiting for mutex

### ISSUE THREAD

**Issue by dyladan** [elastic/logstash#13514]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)

This has happened with several versions, most recently `logstash-oss-7.5.2`

2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)

Expanded from tar archive

3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)

`bin/logstash -f ../logstash.conf --log.level debug`

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

`logstash-input-generator` and `logstash-output-dynatrace

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)

`openjdk version "1.8.0_265"`

2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).

Operating system package manager

3. Value of the `LS_JAVA_HOME` environment variable if set.

unset

**OS version** (`uname -a` if on a Unix-like system):

`Linux 0c105238fd21 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

We are using the generator plugin to generate lines to integration test the Dynatrace output plugin. Sometimes after the generator plugin finishes, we receive the error `ConcurrencyError: interrupted waiting for mutex` during shutdown. More complete error log below:

```
[2021-12-11T21:31:50.536Z] [2021-12-11T21:31:50,460][DEBUG][logstash.agent           ] Shutting down all pipelines {:pipelines_count=>0}
[2021-12-11T21:31:50.537Z] [2021-12-11T21:31:50,462][DEBUG][logstash.agent           ] Converging pipelines state {:actions_count=>0}
[2021-12-11T21:31:50.537Z] warning: thread "Ruby-0-Thread-10: :1" terminated with exception (report_on_exception is true):
[2021-12-11T21:31:50.537Z] ConcurrencyError: interrupted waiting for mutex
[2021-12-11T21:31:50.537Z]          lock at org/jruby/ext/thread/Mutex.java:101
[2021-12-11T21:31:50.537Z]   synchronize at org/jruby/ext/thread/Mutex.java:158
[2021-12-11T21:31:50.537Z]          trim at /home/jenkins/agent/workspace/ucket_logstash-plugin-tests_main/logstash-7.5.2/vendor/bundle/jruby/2.5.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:154
[2021-12-11T21:31:50.537Z]        start! at /home/jenkins/agent/workspace/ucket_logstash-plugin-tests_main/logstash-7.5.2/vendor/bundle/jruby/2.5.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:189
[2021-12-11T21:31:50.794Z] [2021-12-11T21:31:50,614][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ConcurrencyError: interrupted waiting for mutex>, :backtrace=>["org/jruby/ext/thread/Mutex.java:101:in `lock'", "org/jruby/ext/thread/Mutex.java:158:in `synchronize'", "/home/jenkins/agent/workspace/ucket_logstash-plugin-tests_main/logstash-7.5.2/vendor/bundle/jruby/2.5.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:154:in `trim'", "/home/jenkins/agent/workspace/ucket_logstash-plugin-tests_main/logstash-7.5.2/vendor/bundle/jruby/2.5.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:189:in `block in start!'"]}
[2021-12-11T21:31:50.794Z] [2021-12-11T21:31:50,719][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
```

There is no way we have found to reliably reproduce the problem. The dynatrace output plugin does not use mutexes in any way, leading us to believe this is most likely caused by logstash not the plugin. If we are causing this, I would appreciate any help with how to prevent this.

**Comment by yaauie** [comment]
Are the backtraces consistently from Puma? The Logstash http API uses Puma web server, and is the only use of Puma across the default plugin set. It looks like we upgraded Puma from the 2.x series to 4.x in Logstash 7.6 (merged December 2019 https://github.com/elastic/logstash/commit/1c874854d9223c5c0e2c3c2862406edb958e0c94), and it is possible that doing so fixed the issue you are experiencing.

***

Are these the only two plugins your pipeline uses? Any with grok or kv filters (which use timeouts and therefore rely on interrupts)? If so, what versions of the plugins and is the JVM configured to [handle those interruptions](https://github.com/elastic/logstash/blob/726b142a67fcfd292b7297903a1163e41bbc5e68/config/jvm.options#L53)?

***

It has been about 2 years since 7.5.1 was released, and 7.5 is no longer receiving fixes or security updates (7.16 is the current maintained branch if the 7.x series). I would recommend upgrading if you are able.

**Comment by dyladan** [comment]
Yes the backtraces are consistently puma related.

These are the only two plugins used in the pipeline. It is a very simple pipeline.

I maintain the Dynatrace plugin and this is a part of our nightly integration test suite. Many versions including old ones are tested.

We keep the pipeline as simple as possible in order to ensure our tests are not affected by outside factors. We use the generator to build a log line and export it with the Dynatrace plugin, then check to make sure it was correctly exported. There are no other plugins because we are only testing to make sure logs are correctly exported. This bug has occurred in multiple versions, but I don't have a list of versions it has occurred on.

**Comment by yaauie** [comment]
I would recommend upgrading through _at least_ 7.6 where we made substantial changes to our puma dependency where your issue is occurring. For a pipeline this simple, really upgrading through to an actively maintained branch like 7.16 would likely be simple and would add features like the ability to turn off the HTTP API (introduced as `http.enabled: false`, but is `api.enabled: false` moving forward).

**Comment by dyladan** [comment]
We can't really upgrade versions, but we can either ignore the error in our tests for old versions or drop those versions from our tests. Thanks for your help.
