### ISSUE TITLE
logstash error at start

### ISSUE THREAD

**Issue by maheus** [elastic/logstash#13569]
**Logstash information**:

Please include the following information:

1. Logstash version: 5.6.16
2. Logstash installation source: DEB
3. How is Logstash being run: systemd

**Plugins installed**: (`bin/logstash-plugin list --verbose`)
```
logstash-codec-cef
logstash-codec-collectd
logstash-codec-dots
logstash-codec-edn
logstash-codec-edn_lines
logstash-codec-es_bulk
logstash-codec-fluent
logstash-codec-graphite
logstash-codec-json
logstash-codec-json_lines
logstash-codec-line
logstash-codec-msgpack
logstash-codec-multiline
logstash-codec-netflow
logstash-codec-plain
logstash-codec-rubydebug
logstash-filter-cidr
logstash-filter-clone
logstash-filter-csv
logstash-filter-date
logstash-filter-dissect
logstash-filter-dns
logstash-filter-drop
logstash-filter-fingerprint
logstash-filter-geoip
logstash-filter-grok
logstash-filter-json
logstash-filter-kv
logstash-filter-metrics
logstash-filter-mutate
logstash-filter-ruby
logstash-filter-sleep
logstash-filter-split
logstash-filter-syslog_pri
logstash-filter-throttle
logstash-filter-translate
logstash-filter-urldecode
logstash-filter-useragent
logstash-filter-uuid
logstash-filter-xml
logstash-input-beats
logstash-input-couchdb_changes
logstash-input-dead_letter_queue
logstash-input-elasticsearch
logstash-input-exec
logstash-input-file
logstash-input-ganglia
logstash-input-gelf
logstash-input-generator
logstash-input-graphite
logstash-input-heartbeat
logstash-input-http
logstash-input-http_poller
logstash-input-imap
logstash-input-irc
logstash-input-jdbc
logstash-input-kafka
logstash-input-log4j
logstash-input-lumberjack
logstash-input-pipe
logstash-input-rabbitmq
logstash-input-redis
logstash-input-s3
logstash-input-snmptrap
logstash-input-sqs
logstash-input-stdin
logstash-input-syslog
logstash-input-tcp
logstash-input-twitter
logstash-input-udp
logstash-input-unix
logstash-input-xmpp
logstash-output-cloudwatch
logstash-output-csv
logstash-output-elasticsearch
logstash-output-file
logstash-output-graphite
logstash-output-http
logstash-output-irc
logstash-output-kafka
logstash-output-nagios
logstash-output-null
logstash-output-pagerduty
logstash-output-pipe
logstash-output-rabbitmq
logstash-output-redis
logstash-output-s3
logstash-output-sns
logstash-output-sqs
logstash-output-statsd
logstash-output-stdout
logstash-output-tcp
logstash-output-udp
logstash-output-webhdfs
logstash-output-xmpp
logstash-patterns-core
```

**JVM** (e.g. `java -version`):

1. JVM version:  1.8.0_292 (AdoptOpenJDK)
2. JVM installation source: DEB

**OS version** (`uname -a` if on a Unix-like system):
bullseye

**Steps to reproduce**:

 1. start logstash with default conf

**Provide logs (if relevant)**:
```
An unexpected error occurred! {:error=>#<TypeError: cannot convert instance of class org.jruby.RubyString to class java.net.URI>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/runner.rb:309:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:204:in `run'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}
```

the error is provided by /usr/share/logstash/logstash-core/lib/logstash/runner.rb   line 309 
```
@data_path_lock = FileLockFactory.obtainLock(java.nio.file.Paths.get(setting("path.data")).to_absolute_path, ".lock")
```
if i log path.data it is ok but if i try to log  `FileLockFactory.obtainLock(java.nio.file.Paths.get(setting("path.data"))` i have a same error

**Comment by yaauie** [comment]
The 5.x series is past its end-of-life and no longer maintained. Can you replicate your issue with a later version of Logstash?

> if i log path.data it is ok

When you log the effective value of the `path.data` setting, what is its value? My best guess is that assumptions about debian that held true when Logstash 5.x was released some 4 years ago no longer hold true with the most recent debian bullseye that was released this month. Setting a `path.data` to a path that is readable/writable by the `logstash` user may help get around this problem.

**Comment by maheus** [comment]
hi @yaauie , thanks for your response .
version 6.0.1 fix the problem
