### ISSUE TITLE
Failed to execute index operation

### ISSUE THREAD

**Issue by AhmadManzoor** [elastic/logstash#13967]
**Logstash information**:

Please include the following information:

1. Logstash version: logstash 8.1.1
2. Logstash installation source expended from tar.gz
3. How is Logstash being run: via command line

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`) : 
OpenJDK Runtime Environment 18.9 (build 11.0.14.1+1-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.14.1+1-LTS, mixed mode, sharing)

3. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
came with tar.gz
5. Value of the `LS_JAVA_HOME` environment variable if set.

**OS version** (`uname -a` if on a Unix-like system):

Linux ip-xx-xx-xxx.us-west-2.compute.internal 3.10.0-1062.1.2.el7.x86_64

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

I am sending data to elastic app search engine. it works fine but sometimes I see this error in logs
there are two types of errors listed below
and data is also missing on elastic app search engine

[2022-03-31T14:52:36,632][ERROR][logstash.outputs.elasticappsearch][main][37ece3e7ab4f6b002f87f52e6f79b6580122b8dea7d9d53973f7362456f7077a] Failed to execute index operation. Retrying.. {:exception=>Elasticsearch::Transport::Transport::Errors::InternalServerError, :reason=>"[500] {\"errors\":[\"Internal server error. Please check your application server logs for more details and contact Elastic support if the problem persists\"]}", :resolved_engine=>"xx-xxxx", :backtrace=>["/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.17.1/lib/elasticsearch/transport/transport/base.rb:218:in `__raise_transport_error'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.17.1/lib/elasticsearch/transport/transport/base.rb:341:in `perform_request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.17.1/lib/elasticsearch/transport/transport/http/faraday.rb:36:in `perform_request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.17.1/lib/elasticsearch/transport/client.rb:197:in `perform_request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elastic-enterprise-search-7.16.0/lib/elastic/enterprise-search/request.rb:57:in `request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elastic-enterprise-search-7.16.0/lib/elastic/app-search/api/index_documents.rb:41:in `index_documents'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-integration-elastic_enterprise_search-2.2.1/lib/logstash/outputs/elastic_app_search.rb:136:in `block in index'", "org/jruby/RubyHash.java:1415:in `each'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-integration-elastic_enterprise_search-2.2.1/lib/logstash/outputs/elastic_app_search.rb:128:in `index'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-integration-elastic_enterprise_search-2.2.1/lib/logstash/outputs/elastic_app_search.rb:95:in `block in multi_receive'", "org/jruby/RubyArray.java:1863:in `each_slice'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-integration-elastic_enterprise_search-2.2.1/lib/logstash/outputs/elastic_app_search.rb:90:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:143:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in `multi_receive'", "/home/centos/logstash-8.1.1/logstash-core/lib/logstash/java_pipeline.rb:299:in `block in start_workers'"]}

2nd type of errors
[2022-03-31T14:31:55,966][ERROR][logstash.outputs.elasticappsearch][main][37ece3e7ab4f6b002f87f52e6f79b6580122b8dea7d9d53973f7362456f7077a] Failed to execute index operation. Retrying.. {:exception=>Faraday::TimeoutError, :reason=>"Net::ReadTimeout", :resolved_engine=>"stg-product", :backtrace=>["/home/centos/logstash-8.1.1/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:181:in `rbuf_fill'", "/home/centos/logstash-8.1.1/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:157:in `readuntil'", "/home/centos/logstash-8.1.1/vendor/jruby/lib/ruby/stdlib/net/protocol.rb:167:in `readline'", "/home/centos/logstash-8.1.1/vendor/jruby/lib/ruby/stdlib/net/http/response.rb:40:in `read_status_line'", "/home/centos/logstash-8.1.1/vendor/jruby/lib/ruby/stdlib/net/http/response.rb:29:in `read_new'", "/home/centos/logstash-8.1.1/vendor/jruby/lib/ruby/stdlib/net/http.rb:1504:in `block in transport_request'", "org/jruby/RubyKernel.java:1189:in `catch'", "/home/centos/logstash-8.1.1/vendor/jruby/lib/ruby/stdlib/net/http.rb:1501:in `transport_request'", "/home/centos/logstash-8.1.1/vendor/jruby/lib/ruby/stdlib/net/http.rb:1474:in `request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:152:in `block in request_via_request_method'", "/home/centos/logstash-8.1.1/vendor/jruby/lib/ruby/stdlib/net/http.rb:914:in `start'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:146:in `request_via_request_method'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:131:in `request_with_wrapped_block'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/faraday-1.9.3/lib/faraday/adapter.rb:50:in `connection'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/faraday-1.9.3/lib/faraday/rack_builder.rb:154:in `build_response'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/faraday-1.9.3/lib/faraday/connection.rb:516:in `run_request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.17.1/lib/elasticsearch/transport/transport/http/faraday.rb:50:in `block in perform_request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.17.1/lib/elasticsearch/transport/transport/base.rb:288:in `perform_request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.17.1/lib/elasticsearch/transport/transport/http/faraday.rb:36:in `perform_request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-7.17.1/lib/elasticsearch/transport/client.rb:197:in `perform_request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elastic-enterprise-search-7.16.0/lib/elastic/enterprise-search/request.rb:57:in `request'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/elastic-enterprise-search-7.16.0/lib/elastic/app-search/api/index_documents.rb:41:in `index_documents'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-integration-elastic_enterprise_search-2.2.1/lib/logstash/outputs/elastic_app_search.rb:136:in `block in index'", "org/jruby/RubyHash.java:1415:in `each'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-integration-elastic_enterprise_search-2.2.1/lib/logstash/outputs/elastic_app_search.rb:128:in `index'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-integration-elastic_enterprise_search-2.2.1/lib/logstash/outputs/elastic_app_search.rb:95:in `block in multi_receive'", "org/jruby/RubyArray.java:1863:in `each_slice'", "/home/centos/logstash-8.1.1/vendor/bundle/jruby/2.5.0/gems/logstash-integration-elastic_enterprise_search-2.2.1/lib/logstash/outputs/elastic_app_search.rb:90:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:143:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in `multi_receive'", "/home/centos/logstash-8.1.1/logstash-core/lib/logstash/java_pipeline.rb:299:in `block in start_workers'"]}

**Comment by yaauie** [comment]
The first error indicates that Elasticsearch's bulk API endpoint returned an HTTP 500 error, indicating that Elasticsearch had a fault and was unable to satisfy the request. Our log message indicates that the entire bulk request will be retried.

The second error indicates that Elasticsearch's bulk API endpoint failed to respond in a reasonable amount of time, and that the entire request will be retried.

In both cases, the requests are retried by the Elasticsearch Output Plugin until they succeed, with limited exponential back-off. While the worker is retrying the batch, it is unable to pick up more work from the pipeline's queue, which may result in back-pressure to the pipeline's input (if the [Persistent Queue](https://www.elastic.co/guide/en/logstash/current/persistent-queues.html) is enabled and not already full, this back-pressure may be absorbed).
