### ISSUE TITLE
Alias Registry causing Intermittent Failures in x-pack-integration tests

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#13996]
There are currently two different intermittent test failures in the x-pack integration tests, both seemingly originating out of the AliasRegistry:

<details>
<summary>From: https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-integration/5105/console</summary>
```
Failures:
12:37:37 
12:37:37       1) Multiple hosts defined metrics records metrics on es
12:37:37          Failure/Error:
12:37:37            @logstash_service = logstash("bin/logstash -e '#{config}' -w 1", {
12:37:37              :settings => {
12:37:37                "xpack.monitoring.elasticsearch.hosts" => ["http://localhost:9200", "http://localhost:9200"],
12:37:37                "xpack.monitoring.collection.interval" => "1s",
12:37:37                "queue.type" => "persisted",
12:37:37                "xpack.monitoring.elasticsearch.username" => "elastic",
12:37:37                "xpack.monitoring.elasticsearch.password" => elastic_password
12:37:37              }, # will be saved in the logstash.yml
12:37:37              :belzebuth => {
12:37:37                :wait_condition => /Pipelines running/,
12:37:37          
12:37:37          Belzebuth::ExecutionTimeout:
12:37:37            `bin/logstash -e 'input { generator { count => 100 } tcp { port => 6000 } } output { null {} }' -w 1 --path.settings /tmp/studtmp-8ae5ffc93bf52f07cfe3a17078e19c552e7d54f536217422815e88dffdce --path.data /tmp/studtmp-52eb244344a5b6a878e5c83fd0392be1902183bdffa41bd84b579bbdde03` took too much time to execute (timeout: 300) Reponse: 
12:37:37            stdout:
12:37:37            [2022-04-13T16:22:17,833][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600, :ssl_enabled=>false}
12:37:37          
12:37:37            [2022-04-13T16:22:18,873][INFO ][org.reflections.Reflections] Reflections took 204 ms to scan 1 urls, producing 120 keys and 419 values 
12:37:37          
12:37:37            [2022-04-13T16:22:18,884][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:.monitoring-logstash, :exception=>"Java::JavaUtil::NoSuchElementException", :message=>"No line found", :backtrace=>["java.base/java.util.Scanner.nextLine(Scanner.java:1651)", "org.logstash.plugins.AliasRegistry$YamlWithChecksum.load(AliasRegistry.java:69)", "org.logstash.plugins.AliasRegistry$YamlWithChecksum.access$100(AliasRegistry.java:64)", "org.logstash.plugins.AliasRegistry$AliasYamlLoader.loadAliasesDefinitionsFromInputStream(AliasRegistry.java:134)", "org.logstash.plugins.AliasRegistry$AliasYamlLoader.loadAliasesDefinitions(AliasRegistry.java:130)", "org.logstash.plugins.AliasRegistry.<init>(AliasRegistry.java:179)", "org.logstash.plugins.factory.PluginFactoryExt.<init>(PluginFactoryExt.java:86)", "org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:73)", "org.logstash.execution.JavaBasePipelineExt$INVOKER$i$1$0$initialize.call(JavaBasePipelineExt$INVOKER$i$1$0$initialize.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:837)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1169)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuperSplatArgs(IRRuntimeHelpers.java:1156)", "org.jruby.ir.targets.InstanceSuperInvokeSite.invoke(InstanceSuperInvokeSite.java:39)", "opt.logstash.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$initialize$0(/opt/logstash/logstash-core/lib/logstash/java_pipeline.rb:47)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:333)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)", "org.jruby.RubyClass.newInstance(RubyClass.java:939)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", "opt.logstash.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0(/opt/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:50)", "opt.logstash.logstash_minus_core.lib.logstash.pipeline_action.create.RUBY$method$execute$0$__VARARGS__(/opt/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:49)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:80)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:70)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:207)", "opt.logstash.logstash_minus_core.lib.logstash.agent.RUBY$block$converge_state$2(/opt/logstash/logstash-core/lib/logstash/agent.rb:381)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)", "org.jruby.runtime.Block.call(Block.java:139)", "org.jruby.RubyProc.call(RubyProc.java:318)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", "java.base/java.lang.Thread.run(Thread.java:829)"]}
12:37:37          
12:37:37            [2022-04-13T16:22:19,251][INFO ][org.logstash.ackedqueue.QueueUpgrade] No PQ version file found, upgrading to PQ v2.
12:37:37          
12:37:37            [2022-04-13T16:22:19,280][INFO ][logstash.javapipeline    ] Pipeline `main` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
12:37:37          
12:37:37            [2022-04-13T16:22:19,342][WARN ][logstash.javapipeline    ][main] 'pipeline.ordered' is enabled and is likely less efficient, consider disabling if preserving event order is not necessary
12:37:37          
12:37:37            [2022-04-13T16:22:19,413][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, "pipeline.sources"=>["config string"], :thread=>"#<Thread:0x3ac991f0 run>"}
12:37:37          
12:37:37            [2022-04-13T16:22:20,119][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>0.7}
12:37:37          
12:37:37            [2022-04-13T16:22:20,312][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
12:37:37          
12:37:37            [2022-04-13T16:22:20,324][INFO ][logstash.inputs.tcp      ][main][5f9752f3d96a2eb100377fcfe2c1a9513c9e5b24b0e585d003310bc101d32aae] Starting tcp input listener {:address=>"0.0.0.0:6000", :ssl_enable=>false}
12:37:37          
12:37:37            stderr
12:37:37            OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
12:37:37          
12:37:37            TimerTask timeouts are now ignored as these were not able to be implemented correctly
12:37:37          
12:37:37            TimerTask timeouts are now ignored as these were not able to be implemented correctly
12:37:37          
12:37:37            TimerTask timeouts are now ignored as these were not able to be implemented correctly
12:37:37          
12:37:37            TimerTask timeouts are now ignored as these were not able to be implemented correctly
12:37:37          Shared Example Group: "record monitoring data to es" called from ./qa/integration/monitoring/persisted_queue_is_enabled_spec.rb:30
12:37:37          # /opt/logstash/vendor/bundle/jruby/2.5.0/gems/belzebuth-0.2.3/lib/belzebuth/process.rb:63:in `block in run'
12:37:37          # /opt/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.11/lib/bundler.rb:394:in `block in with_clean_env'
12:37:37          # /opt/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.11/lib/bundler.rb:698:in `with_env'
12:37:37          # /opt/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.11/lib/bundler.rb:394:in `with_clean_env'
12:37:37          # /opt/logstash/vendor/bundle/jruby/2.5.0/gems/belzebuth-0.2.3/lib/belzebuth/process.rb:47:in `run'
12:37:37          # /opt/logstash/vendor/bundle/jruby/2.5.0/gems/belzebuth-0.2.3/lib/belzebuth/process.rb:30:in `run'
12:37:37          # ./qa/integration/support/helpers.rb:165:in `logstash_with_empty_default'
12:37:37          # ./qa/integration/support/helpers.rb:150:in `logstash'
12:37:37          # ./qa/integration/monitoring/persisted_queue_is_enabled_spec.rb:15:in `block in <main>'
12:37:37          # /opt/logstash/lib/bootstrap/rspec.rb:36:in `<main>'
```
</details>

<details>
<summary>From https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-integration/5076/console:</summary>

```
09:21:16     Failures:
09:21:16 
09:21:16       1) Read configuration from elasticsearch security is enabled fetches the configuration from elasticsearch
09:21:16          [31mFailure/Error: [0m@logstash_service = logstash([31m[1;31m"[0m[31mbin/logstash -w 1[1;31m"[0m[31m[0m, logstash_options)[0m
09:21:16          [31m[0m
09:21:16          [31mBelzebuth::ExecutionTimeout:[0m
09:21:16          [31m  `bin/logstash -w 1 --path.settings /tmp/studtmp-c3000970d200317866cc63e190d0c0387c3580ce58484b61ecb0b3bba27d --path.data /tmp/studtmp-114187cc62d783494ebc4709cdbd3363f45904873d344110f1fdf25a6fe5` took too much time to execute (timeout: 300) Reponse: [0m
09:21:16          [31m  stdout:[0m
09:21:16          [31m  [2022-04-07T13:00:24,192][WARN ][logstash.configmanagement.elasticsearchsource] Attempt to fetch ES version from Central Management failed. Sleeping for 0.02 {:fail_count=>1, :exception=>"Elasticsearch Unreachable: [http://localhost:19200/][Manticore::SocketException] Connect to localhost:19200 [localhost/127.0.0.1] failed: Connection refused (Connection refused)"}[0m
09:21:16          [31m[0m
09:21:16          [31m  [2022-04-07T13:00:25,275][INFO ][org.reflections.Reflections] Reflections took 239 ms to scan 1 urls, producing 120 keys and 419 values [0m
09:21:16          [31m[0m
09:21:16          [31m  [2022-04-07T13:00:25,285][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:.monitoring-logstash, :exception=>"Java::JavaLang::NullPointerException", :message=>"Inflater has been closed", :backtrace=>["java.base/java.util.zip.Inflater.ensureOpen(Inflater.java:740)", "java.base/java.util.zip.Inflater.inflate(Inflater.java:377)", "java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153)", "java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)", "java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)", "java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)", "java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)", "java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)", "java.base/java.io.Reader.read(Reader.java:189)", "java.base/java.util.Scanner.readInput(Scanner.java:882)", "java.base/java.util.Scanner.findWithinHorizon(Scanner.java:1796)", "java.base/java.util.Scanner.nextLine(Scanner.java:1649)", "org.logstash.plugins.AliasRegistry$YamlWithChecksum.load(AliasRegistry.java:69)", "org.logstash.plugins.AliasRegistry$YamlWithChecksum.access$100(AliasRegistry.java:64)", "org.logstash.plugins.AliasRegistry$AliasYamlLoader.loadAliasesDefinitionsFromInputStream(AliasRegistry.java:134)", "org.logstash.plugins.AliasRegistry$AliasYamlLoader.loadAliasesDefinitions(AliasRegistry.java:130)", "org.logstash.plugins.AliasRegistry.<init>(AliasRegistry.java:179)", "org.logstash.plugins.factory.PluginFactoryExt.<init>(PluginFactoryExt.java:86)", "org.logstash.execution.JavaBasePipelineExt.initialize(JavaBasePipelineExt.java:73)", "org.logstash.execution.JavaBasePipelineExt$INVOKER$i$1$0$initialize.call(JavaBasePipelineExt$INVOKER$i$1$0$initialize.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:837)", "org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:1169)", "org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:84)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:86)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:73)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:85)", "org.jruby.RubyClass.newInstance(RubyClass.java:939)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:333)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:87)", "org.jruby.ir.instructions.CallBase.interpret(CallBase.java:549)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:361)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)", "org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:92)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:191)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:178)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)", "opt.logstash.logstash_minus_core.lib.logstash.agent.RUBY$block$converge_state$2(/opt/logstash/logstash-core/lib/logstash/agent.rb:381)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:138)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:58)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:52)", "org.jruby.runtime.Block.call(Block.java:139)", "org.jruby.RubyProc.call(RubyProc.java:318)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:105)", "java.base/java.lang.Thread.run(Thread.java:829)"]}[0m
09:21:16          [31m[0m
09:21:16          [31m  [2022-04-07T13:00:25,295][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::Create<.monitoring-logstash>`"}[0m
09:21:16          [31m[0m
09:21:16          [31m  [2022-04-07T13:00:25,439][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<LogStash::Error: Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::Create<.monitoring-logstash>`>, :backtrace=>["org/logstash/execution/ConvergeResultExt.java:135:in `create'", "org/logstash/execution/ConvergeResultExt.java:60:in `add'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:394:in `block in converge_state'"]}[0m
09:21:16          [31m[0m
09:21:16          [31m  [2022-04-07T13:00:25,465][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit[0m
09:21:16          [31m[0m
09:21:16          [31m  org.jruby.exceptions.SystemExit: (SystemExit) exit[0m
09:21:16          [31m[0m
09:21:16          [31m  	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:747) ~[jruby.jar:?][0m
09:21:16          [31m[0m
09:21:16          [31m  	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:710) ~[jruby.jar:?][0m
09:21:16          [31m[0m
09:21:16          [31m  	at opt.logstash.lib.bootstrap.environment.<main>(/opt/logstash/lib/bootstrap/environment.rb:91) ~[?:?][0m
09:21:16          [31m[0m
09:21:16          [31m  stderr[0m
09:21:16          [31m  OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.[0m
09:21:16          [31m[0m
09:21:16          [31m  TimerTask timeouts are now ignored as these were not able to be implemented correctly[0m
09:21:16          [31m[0m
09:21:16          [31m  TimerTask timeouts are now ignored as these were not able to be implemented correctly[0m
09:21:16          [31m[0m
09:21:16          [31m  TimerTask timeouts are now ignored as these were not able to be implemented correctly[0m
09:21:16          [31m[0m
09:21:16          [31m  TimerTask timeouts are now ignored as these were not able to be implemented correctly[0m
09:21:16          [31m[0m
09:21:16          [31m  warning: thread "Converge PipelineAction::Create<.monitoring-logstash>" terminated with exception (report_on_exception is true):[0m
09:21:16          [31m[0m
09:21:16          [31m  LogStash::Error: Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::Create<.monitoring-logstash>`[0m
09:21:16          [31m[0m
09:21:16          [31m            create at org/logstash/execution/ConvergeResultExt.java:135[0m
09:21:16          [31m[0m
09:21:16          [31m               add at org/logstash/execution/ConvergeResultExt.java:60[0m
09:21:16          [31m[0m
09:21:16          [31m    converge_state at /opt/logstash/logstash-core/lib/logstash/agent.rb:394[0m
09:21:16          [36m# /opt/logstash/vendor/bundle/jruby/2.5.0/gems/belzebuth-0.2.3/lib/belzebuth/process.rb:63:in `block in run'[0m
09:21:16          [36m# /opt/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.11/lib/bundler.rb:394:in `block in with_clean_env'[0m
09:21:16          [36m# /opt/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.11/lib/bundler.rb:698:in `with_env'[0m
09:21:16          [36m# /opt/logstash/vendor/bundle/jruby/2.5.0/gems/bundler-2.3.11/lib/bundler.rb:394:in `with_clean_env'[0m
09:21:16          [36m# /opt/logstash/vendor/bundle/jruby/2.5.0/gems/belzebuth-0.2.3/lib/belzebuth/process.rb:47:in `run'[0m
09:21:16          [36m# /opt/logstash/vendor/bundle/jruby/2.5.0/gems/belzebuth-0.2.3/lib/belzebuth/process.rb:30:in `run'[0m
09:21:16          [36m# ./qa/integration/support/helpers.rb:165:in `logstash_with_empty_default'[0m
09:21:16          [36m# ./qa/integration/support/helpers.rb:150:in `logstash'[0m
09:21:16          [36m# ./qa/integration/management/read_configuration_spec.rb:39:in `start_services'[0m
09:21:16          [36m# ./qa/integration/management/read_configuration_spec.rb:52:in `block in <main>'[0m
09:21:16          [36m# /opt/logstash/lib/bootstrap/rspec.rb:36:in `<main>'[0m
```

</details>

Both of these seem to come from the same line:

```
{:action=>LogStash::PipelineAction::Create/pipeline_id:.monitoring-logstash, :exception=>"Java::JavaUtil::NoSuchElementException", :message=>"No line found", :backtrace=>["java.base/java.util.Scanner.nextLine(Scanner.java:1651)", "org.logstash.plugins.AliasRegistry$YamlWithChecksum.load(AliasRegistry.java:69)", "org.logstash.plugins.AliasRegistry$YamlWithChecksum.access$100(AliasRegistry.java:64)", "org.logstash.plugins.AliasRegistry$AliasYamlLoader.loadAliasesDefinitionsFromInputStream(AliasRegistry.java:134)", "org.logstash.plugins.AliasRegistry$AliasYamlLoader.loadAliasesDefinitions(AliasRegistry.java:130)", "org.logstash.plugins.AliasRegistry.<init>(AliasRegistry.java:179)", "org.logstash.plugins.factory.PluginFactoryExt.<init>(PluginFactoryExt.java:86)", 
```

```
Java::JavaLang::NullPointerException", :message=>"Inflater has been closed", :backtrace=>["java.base/java.util.zip.Inflater.ensureOpen(Inflater.java:740)", "java.base/java.util.zip.Inflater.inflate(Inflater.java:377)", "java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:153)", "java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)", "java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)", "java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)", "java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)", "java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)", "java.base/java.io.Reader.read(Reader.java:189)", "java.base/java.util.Scanner.readInput(Scanner.java:882)", "java.base/java.util.Scanner.findWithinHorizon(Scanner.java:1796)", "java.base/java.util.Scanner.nextLine(Scanner.java:1649)", "org.logstash.plugins.AliasRegistry$YamlWithChecksum.load(AliasRegistry.java:69)", "org.logstash.plugins.AliasRegistry$YamlWithChecksum.access$100(AliasRegistry.java:64)", "org.logstash.plugins.AliasRegistry$AliasYamlLoader.loadAliasesDefinitionsFromInputStream(AliasRegistry.java:134)", "org.logstash.plugins.AliasRegistry$AliasYamlLoader.loadAliasesDefinitions(AliasRegistry.java:130)", "org.logstash.plugins.AliasRegistry.<init>(AliasRegistry.java:179)", , "org.logstash.plugins.factory.PluginFactoryExt.<init>(PluginFactoryExt.java:86)"
```

**Failure history**:

https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-integration/5105/
https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-integration/5097/
https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-x-pack-integration/5076/

**Comment by robbavey** [comment]
Closed by #14002
