### ISSUE TITLE
Null pointer and logstash stops working

### ISSUE THREAD

**Issue by ayoldi-bshg** [elastic/logstash#1423]
Hi guys,

Im getting the following exception after some hours of running logstash:

```
Exception in thread "elasticsearch[logstash-PMPWCN000082-10604-4170][generic][T#14]" java.lang.NullPointerException
        at org.elasticsearch.action.bulk.TransportBulkAction.setResponseFailureIfIndexMatches(TransportBulkAction.java:178)
        at org.elasticsearch.action.bulk.TransportBulkAction.access$100(TransportBulkAction.java:65)
        at org.elasticsearch.action.bulk.TransportBulkAction$1.onFailure(TransportBulkAction.java:137)
        at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$2.run(TransportAction.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "elasticsearch[logstash-PMPWCN000082-10604-4172][generic][T#8]" java.lang.NullPointerException
        at org.elasticsearch.action.bulk.TransportBulkAction.setResponseFailureIfIndexMatches(TransportBulkAction.java:178)
        at org.elasticsearch.action.bulk.TransportBulkAction.access$100(TransportBulkAction.java:65)
        at org.elasticsearch.action.bulk.TransportBulkAction$1.onFailure(TransportBulkAction.java:137)
        at org.elasticsearch.action.support.TransportAction$ThreadedActionListener$2.run(TransportAction.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

I couldnt find any information about this error on the Internet, and browsing the code doesnt give me any information at all. Im not worried about the error itself (its not really important if one event is not succesfully parsed), but its very very annoying as i am not able to run logstash for a long time (the only way to get it alive is restarting it!).

This is my config file (simplified version):

```
input {

	######### WD FARM 205, 206, 207, 208 #########

	file {
		path => ["W:/Logfiles/A0P_30_ex0_201406*.log","X:/Logfiles/A0P_30_ex0_201406*.log","Y:/Logfiles/A0P_30_ex0_201406*.log","Z:/Logfiles/A0P_30_ex0_201406*.log"]
		add_field => { "system_name" => "A0P" }
		start_position => "end"
		sincedb_path => "C:/tmp/a0d_logs/since/sourcedb-a0p.txt"		
	}

	file {
			path => ["W:/Logfiles/X3P*.log","X:/Logfiles/X3P*.log","Y:/Logfiles/X3P*.log","Z:/Logfiles/X3P*.log"]
			add_field => { "system_name" => "X3P" }
			start_position => "end"
		}


}

filter {
	grok {
			match => { "message" => "%{DATA:timestamp_raw} %{URIHOST:wd_host} %{INT:wd_port:int} %{URIHOST:source_ip} %{DATA:method} %{DATA:resource} %{DATA:protocol_version} %{WORD:protocol} %{INT:duration_ms:int} %{INT:status:int} %{INT:bytes_sent:int} ; %{URIHOST:request_host} ; %{DATA:request_referer} ; %{DATA:user_agent} ; "  }
			add_tag => [ "succesfully_parsed" ]	
	}
	date {
		match => [ "timestamp_raw" , "[dd/MMM/yyyy:HH:mm:ss Z]" ]
	}
	fingerprint {
		source => ["message"]
		target => "fingerprint"
		key => "78787878"
		method => "SHA1"
		concatenate_sources => true
	}
}


output {
	# request from ACE
	if [resource] =~ "\/swd\/swd_alive_.*" {
		# do nothing
	}
	# request from ACE
	else if [resource] == "/index.html" and [user_agent] == "-"{
		# do nothing
	}
	else if "succesfully_parsed" in [tags]{	
		elasticsearch {
			host => "xxxxxxxx.com"
			index => 'logstash-%{+YYYY.MM}'	
			workers => 2
			document_id => "%{fingerprint}" # !!! prevent duplication
			#protocol => "http"
		}
	}
	else {
		file {path => "bad_parsed_entries.txt"}
	}
	
	
  
}
```
Any idea?? Thanks a lot in advance!

Regards,

**Comment by purbon** [comment]
@ayoldi-bshg do you still see this ? is this issue still meaningful ?

**Comment by ayoldi-bshg** [comment]
I started using Logstash forwarder to index the logs themselves and send them to Logstash…I found it much more stable. So I cannot say if the issue is still there. Sorry about that :S


Kind regards,
Alberto Yoldi

BSH Electrodomésticos España, S.A.
Application Services (CIT-RIIOA)

Itaroburua, 1
31620 Huarte - Pamplona
Tel.: 948425359
Mobile: 649712743
Alberto.Yoldi@bshg.com<mailto:Alberto.Yoldi@bshg.com>
www.bsh-group.com<http://www.bsh-group.com>

BSH Electrodomésticos España, S.A.
Inscrita en el Registro Mercantil de Navarra, Tomo 96, Folio 42, Hoja NA - 1841, Inscripción 4ª - CIF A-28-893550
Registered Office: C/ Itaroburua, 1 - 31620 Huarte - Pamplona (Navarra) - ESPAÑA

This message is for the sole use of the intended recipient(s) and may contain trade secrets or other confidential and privileged information. Any unauthorized use, copy, disclosure or distribution is prohibited. If you are not the intended recipient, please inform us immediately by reply email and delete this message, including any attachment or copies thereof, from your system.
Please consider the environment before printing this e-mail.

**Comment by purbon** [comment]
ok, so closing this issue for now. If it resurfaces we can reopen.
