### ISSUE TITLE
Pipeline reload not happening after "The shutdown process appears to be stalled due to busy or blocked plugins" error

### ISSUE THREAD

**Issue by ferdose7** [elastic/logstash#14332]
Hi Team,

We see issue with Logstash. We are using Logstash 7.15.2 version.
Please refer to the following details.

Reproduction steps:
1. Deploy Logstash which sends events to Search engine using elasticsearch plugin. We have following pipelines running in logstash
`[2022-05-31T02:07:49.049Z][INFO ][logstash.agent ] Pipelines running {:count=>2, :running_pipelines=>[:logstash, :elasticsearch], :non_running_pipelines=>[]}`. 
We are using "--config.reload.automatic" to enable automatic config reloading.
2. Deploy Elsatic search.
3. Deploy Loggen which sends log events to Logstash input plugin.
4. Scale down Search engine instances to 0.
5. Renew certificates. This will update logstash.conf file and reload logstash pipelines. Since, the elasticsearch output is blocked, we see following error while reloading pipelines.
`[2022-05-31T02:25:59.059Z][ERROR][org.logstash.execution.ShutdownWatcherExt] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.`
7. After this error, when we update logstash.conf file, the logstash pipelines are not reloading. The pipeline reload is not happening even if the Search engine is UP and running. We see following logs in logstash.
`[2022-05-31T02:26:04.004Z][WARN ][org.logstash.execution.ShutdownWatcherExt] {"inflight_count"=>0, "stalling_threads_info"=>{["LogStash::Filters::Drop", {"id"=>"b3520a1ba97eea26b1ac8124ecc402abe8368cd073482b72f0995944da016d91"}]=>[{"thread_id"=>39, "name"=>"[elasticsearch]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch.rb:301:in `sleep'"}, {"thread_id"=>40, "name"=>"[elasticsearch]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch.rb:301:in `sleep'"}]}}`

Could you please check the reason for not reloading the pipelines.

We also tried using pipeline.unsafe_shutdown: true. But elasticsearch pipeline reloading fails with the following error.

[2022-06-24T10:12:06.006Z][FATAL][org.logstash.execution.ShutdownWatcherExt] Forcefully quitting Logstash ...
[2022-06-24T10:12:06.006Z][ERROR][logstash.agent ] Failed to execute action {:action=>LogStash::PipelineAction::Reload/pipeline_id:elasticsearch, :exception=>"SystemExit", :message=>"exit", :backtrace=>["org/logstash/execution/ShutdownWatcherExt.java:209:in `force_exit'", "org/logstash/execution/ShutdownWatcherExt.java:178:in `start'", "/opt/logstash/logstash-core/lib/logstash/java_pipeline.rb:453:in `wait_for_shutdown'", "/opt/logstash/logstash-core/lib/logstash/java_pipeline.rb:448:in `shutdown'", "/opt/logstash/logstash-core/lib/logstash/pipeline_action/reload.rb:69:in `block in execute'", "/opt/logstash/logstash-core/lib/logstash/pipelines_registry.rb:213:in `reload_pipeline'", "/opt/logstash/logstash-core/lib/logstash/pipeline_action/reload.rb:64:in `execute'", "/opt/logstash/logstash-core/lib/logstash/agent.rb:391:in `block in converge_state'"]}

[2022-06-24T11:56:13.013Z][INFO ][logstash.pipelineaction.reload] Reloading pipeline {"pipeline.id"=>:elasticsearch}
[2022-06-24T11:56:15.015Z][WARN ][logstash.outputs.elasticsearch] Error while performing resurrection {:error_message=>"readHandshakeRecord", :class=>"Manticore::UnknownException", :backtrace=>["/opt/logstash/vendor/bundle/jruby/2.5.0/gems/manticore-0.7.1-java/lib/manticore/response.rb:36:in `block in initialize'", "/opt/logstash/vendor/bundle/jruby/2.5.0/gems/manticore-0.7.1-java/lib/manticore/response.rb:79:in `call'", "/opt/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:74:in `perform_request'", "/opt/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:317:in `perform_request_to_url'", "/opt/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:260:in `health_check_request'", "/opt/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:269:in `block in healthcheck!'", "org/jruby/RubyHash.java:1415:in `each'", "/opt/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:265:in `healthcheck!'", "/opt/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:243:in `block in start_resurrectionist'", "/opt/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:138:in `until_stopped'", "/opt/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-10.8.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:242:in `block in start_resurrectionist'"]}

Could you please check this issue. Please let us know if any details required
[logtransformer-restart.log](https://github.com/elastic/logstash/files/9061532/logtransformer-restart.log)

**Comment by rado-van** [comment]
Same here
