### ISSUE TITLE
gzip input error with the embedded JDK

### ISSUE THREAD

**Issue by camiyu1** [elastic/logstash#14541]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
  -  **8.4.1**
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
  - **zip archive (Linux)**
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes): Via command line
  - **bin/logstash -f logstash.conf**

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

**JVM** (e.g. `java -version`): **openjdk 11.0.16 2022-07-19**

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

**OS version** (`uname -a` if on a Unix-like system): 
`Linux b6af878aada7 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Description of the problem including expected versus actual behavior**:

When I tried ingesting gzipped log files with the default installation of logstash 8.4.1, it ended up with a failure. 

I attach the error message as follows.

```
camiyu1@b6af878aada7:/home/camiyu1/logstash-8.4.1$ bin/logstash -f logstash-fwlog.conf
Using bundled JDK: /home/camiyu1/logstash-8.4.1/jdk
Sending Logstash logs to /home/camiyu1/logstash-8.4.1/logs which is now configured via log4j2.properties
..........
[2022-09-19T19:47:28,199][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/home/camiyu1/logstash-8.4.1/logstash-fwlog.conf"], :thread=>"#<Thread:0x30f25a47 run>"}
[2022-09-19T19:47:28,683][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>0.48}
[2022-09-19T19:47:28,725][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2022-09-19T19:47:28,789][INFO ][filewatch.observingread  ][main][43616dcef2f593c90775e543ffa39eb45dd9f7042300c12e094cd8ea4a22eae9] START, creating Discoverer, Watch with file and sincedb collections
[2022-09-19T19:47:28,798][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2022-09-19T19:47:29,389][ERROR][logstash.javapipeline    ][main][43616dcef2f593c90775e543ffa39eb45dd9f7042300c12e094cd8ea4a22eae9] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::File mode=>"read", start_position=>"beginning", path=>["/Workspace/fwlog_backup/sas/fw.log-202208*.gz"], id=>"43616dcef2f593c90775e543ffa39eb45dd9f7042300c12e094cd8ea4a22eae9", type=>"gzip", file_completed_action=>"log", sincedb_path=>"/tmp/gzip.db", file_completed_log_path=>"/tmp/log.log", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_62fa74fe-911c-4960-904f-b968f385faa0", enable_metric=>true, charset=>"UTF-8">, stat_interval=>1.0, discover_interval=>15, sincedb_write_interval=>15.0, delimiter=>"\n", close_older=>3600.0, sincedb_clean_after=>1209600.0, file_chunk_size=>32768, file_chunk_count=>140737488355327, file_sort_by=>"last_modified", file_sort_direction=>"asc", exit_after_read=>false, check_archive_validity=>false>
  Error: wrong number of arguments (given 1, expected 2)
  Exception: ArgumentError
  Stack: /home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/filewatch/read_mode/handlers/read_zip_file.rb:32:in `handle_specifically'
/home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/filewatch/read_mode/handlers/base.rb:26:in `handle'
/home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/filewatch/read_mode/processor.rb:25:in `read_zip_file'
/home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/filewatch/read_mode/processor.rb:88:in `block in process_active'
org/jruby/RubyArray.java:1865:in `each'
/home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/filewatch/read_mode/processor.rb:73:in `process_active'
/home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/filewatch/read_mode/processor.rb:31:in `process_all_states'
/home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/filewatch/watch.rb:70:in `iterate_on_state'
/home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/filewatch/watch.rb:44:in `subscribe'
/home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/filewatch/observing_read.rb:12:in `subscribe'
/home/camiyu1/logstash-8.4.1/vendor/bundle/jruby/2.6.0/gems/logstash-input-file-4.4.3/lib/logstash/inputs/file.rb:370:in `run'
/home/camiyu1/logstash-8.4.1/logstash-core/lib/logstash/java_pipeline.rb:410:in `inputworker'
/home/camiyu1/logstash-8.4.1/logstash-core/lib/logstash/java_pipeline.rb:401:in `block in start_input'
[2022-09-19T19:47:30,412][INFO ][filewatch.observingread  ][main][43616dcef2f593c90775e543ffa39eb45dd9f7042300c12e094cd8ea4a22eae9] QUIT - closing all files and shutting down.
[2022-09-19T19:47:30,413][INFO ][filewatch.observingread  ][main][43616dcef2f593c90775e543ffa39eb45dd9f7042300c12e094cd8ea4a22eae9] START, creating Discoverer, Watch with file and sincedb collections
```

So, as a workaround, I changed a logstash bundled jdk folder name `jdk` to `jdkdk` to be disabled.
So OpenJDK 11, not bundled JDK but installed with APT would be used instead. 

It was working fine after I changed it.

I attach the logstash.conf as follows too.

```
input {
  file {
    type => "gzip"
    mode => "read"
    path => "/Workspace/fwlog_backup/sas/fw.log-202208*.gz"
    start_position => "beginning"
    file_completed_action => "log"
    file_completed_log_path => "/tmp/log.log"
    sincedb_path => "/tmp/gzip.db"
  }
}

output {
  elasticsearch {
    hosts => ["https://elasticsearch:9200"]
    index => "firewall"
    pipeline => "palo_general"
    user => "elastic"
    password => "**********"
  }
}
```
I hope it would be helpful to pinpoint the issue and correct it.

**Comment by yaauie** [comment]
Thank you for bringing this to our attention.

This is resolved in version 4.4.4 of the File Input plugin, which can be updated on its own using the plugin manager, and will be included in future releases of Logstash.

Separately, the official way to use your own Java instead of the one bundled with Logstash is to set the `LS_JAVA_HOME` environment variable. There is no need to modify your installation, and doing so is likely to produce unpredictable results.
