### ISSUE TITLE
After config error, Logstash doesn't seem to restart broken pipeline with new config from Central Management

### ISSUE THREAD

**Issue by roaksoax** [elastic/logstash#14739]
See https://github.com/elastic/logstash/issues/14739#issuecomment-1310469742 for latest reproducible steps.

**Logstash information**:

Please include the following information:

1. Logstash version: 8.5.0
2. Logstash installation source: deb
3. How is Logstash being run: systemd

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

Default plugins

**JVM** (e.g. `java -version`):

Bundled

**OS version** (`uname -a` if on a Unix-like system): Ubuntu 20.04

**Description of the problem including expected versus actual behavior**

When using Logstash Central management, I came across an issue where Logstash would fail due to a configuration error, and after the failure, it would stop attempting to get new configuration from Central Management. Hence, I had to manually restart Logstash to be able to proceed after fixing the issue.

Ideally, I would have expected Logstash to attempt to get the configuration again. This is because I would have expected Logstash to be failure proof when configuring pipelines through Central Management.

**Steps to reproduce**:

 1. Install the stack, 8.5 should do, and configure central management.
 2. Configure the following pipeline in central Management:

```
input {
 <whatever you want>
}
output {
    elasticsearch {
        cloud_id => "<your cloud id>"
        api_key => "<your api key>"
    }
    stdout{}
}
```

 3. Logstash will then get the configuration an fail with the following error (see a full log below):
 
 `<LogStash::ConfigurationError: Using api_key authentication requires SSL/TLS secured communication using the `ssl => true` option>`
 
 more details:
 
 ```
Nov 04 09:57:06 file-1 logstash[18048]: [2022-11-04T09:57:06,833][INFO ][logstash.javapipeline    ] Pipeline `test` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
Nov 04 09:57:06 file-1 logstash[18048]: [2022-11-04T09:57:06,850][INFO ][logstash.outputs.elasticsearch][test] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//127.0.0.1"]}
Nov 04 09:57:06 file-1 logstash[18048]: [2022-11-04T09:57:06,856][ERROR][logstash.javapipeline    ][test] Pipeline error {:pipeline_id=>"test", :exception=>#<LogStash::ConfigurationError: Using api_key authentication requires SSL/TLS secured communication using the `ssl => true` option>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/plugin_mixins/elasticsearch/common.rb:48:in `validate_authentication'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/plugin_mixins/elasticsearch/common.rb:26:in `build_client'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch.rb:279:in `register'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:131:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:68:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:232:in `block in register_plugins'", "org/jruby/RubyArray.java:1821:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:231:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:589:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:244:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:189:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:141:in `block in start'"], "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x20500192 run>"}
Nov 04 09:57:06 file-1 logstash[18048]: [2022-11-04T09:57:06,858][INFO ][logstash.javapipeline    ][test] Pipeline terminated {"pipeline.id"=>"test"}
Nov 04 09:57:06 file-1 logstash[18048]: [2022-11-04T09:57:06,861][ERROR][logstash.agent           ] Failed to execute action {:id=>:test, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Reload<test>, action_result: false", :backtrace=>nil}
```
 
 4. Fix the configuration issue in Central Management
 5. Logstash will not try to get the new configuration, and will have to be restarted manually.

NOTE: IF USING A LATER VERSION OF THE ES OUTPUT PLUGIN, THIS ISSUE WONT BE REPRODUCE-ABLE BECAUSE THE UNRELATED ISSUE WAS FIXED IN THE PLUGIN.

**Provide logs (if relevant)**:

```
[2022-11-04T09:52:00,746][INFO ][logstash.javapipeline    ] Pipeline `test` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2022-11-04T09:52:00,770][INFO ][logstash.outputs.elasticsearch][test] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//127.0.0.1"]}
[2022-11-04T09:52:00,797][INFO ][logstash.outputs.elasticsearch][test] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://2d729cb9e78b47d9a75e5552c82fea6d.us-east4.gcp.elastic-cloud.com:443/]}}
[2022-11-04T09:52:01,039][WARN ][logstash.outputs.elasticsearch][test] Restored connection to ES instance {:url=>"https://2d729cb9e78b47d9a75e5552c82fea6d.us-east4.gcp.elastic-cloud.com:443/"}
[2022-11-04T09:52:01,082][INFO ][logstash.outputs.elasticsearch][test] Elasticsearch version determined (8.5.0) {:es_version=>8}
[2022-11-04T09:52:01,090][WARN ][logstash.outputs.elasticsearch][test] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>8}
[2022-11-04T09:52:01,148][INFO ][logstash.outputs.elasticsearch][test] Config is compliant with data streams. `data_stream => auto` resolved to `true`
[2022-11-04T09:52:01,151][WARN ][logstash.outputs.elasticsearch][test] Elasticsearch Output configured with `ecs_compatibility => v8`, which resolved to an UNRELEASED preview of version 8.0.0 of the Elastic Common Schema. Once ECS v8 and an updated release of this plugin are publicly available, you will need to update this plugin to resolve this warning.
[2022-11-04T09:52:01,150][INFO ][logstash.outputs.elasticsearch][test] Config is compliant with data streams. `data_stream => auto` resolved to `true`
[2022-11-04T09:52:01,166][WARN ][logstash.javapipeline    ][test] 'pipeline.ordered' is enabled and is likely less efficient, consider disabling if preserving event order is not necessary
[2022-11-04T09:52:01,192][INFO ][logstash.javapipeline    ][test] Starting pipeline {:pipeline_id=>"test", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x6dd4db2d run>"}
[2022-11-04T09:52:01,253][INFO ][logstash.outputs.elasticsearch][test] Using a default mapping template {:es_version=>8, :ecs_compatibility=>:v8}
[2022-11-04T09:52:01,381][INFO ][logstash.javapipeline    ][test] Pipeline Java execution initialization time {"seconds"=>0.17}
[2022-11-04T09:52:01,407][INFO ][logstash.javapipeline    ][test] Pipeline started {"pipeline.id"=>"test"}
[2022-11-04T09:52:01,419][INFO ][logstash.agent           ] Pipelines running {:count=>2, :running_pipelines=>[:test_filebeat, :test], :non_running_pipelines=>[]}
[2022-11-04T09:52:01,422][INFO ][filewatch.observingtail  ][test][df38b7e37e1833c61dea872d68681887a916816ca8db8b65efaa395c30405bdc] START, creating Discoverer, Watch with file and sincedb collections
[2022-11-04T09:57:04,409][INFO ][logstash.pipelineaction.reload] Reloading pipeline {"pipeline.id"=>:test}
[2022-11-04T09:57:04,433][INFO ][filewatch.observingtail  ] QUIT - closing all files and shutting down.
[2022-11-04T09:57:05,590][INFO ][logstash.javapipeline    ][test] Pipeline terminated {"pipeline.id"=>"test"}
[2022-11-04T09:57:06,833][INFO ][logstash.javapipeline    ] Pipeline `test` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2022-11-04T09:57:06,850][INFO ][logstash.outputs.elasticsearch][test] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//127.0.0.1"]}
[2022-11-04T09:57:06,856][ERROR][logstash.javapipeline    ][test] Pipeline error {:pipeline_id=>"test", :exception=>#<LogStash::ConfigurationError: Using api_key authentication requires SSL/TLS secured communication using the `ssl => true` option>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/plugin_mixins/elasticsearch/common.rb:48:in `validate_authentication'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/plugin_mixins/elasticsearch/common.rb:26:in `build_client'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-elasticsearch-11.4.1-java/lib/logstash/outputs/elasticsearch.rb:279:in `register'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:131:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:68:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:232:in `block in register_plugins'", "org/jruby/RubyArray.java:1821:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:231:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:589:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:244:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:189:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:141:in `block in start'"], "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x20500192 run>"}
[2022-11-04T09:57:06,858][INFO ][logstash.javapipeline    ][test] Pipeline terminated {"pipeline.id"=>"test"}
[2022-11-04T09:57:06,861][ERROR][logstash.agent           ] Failed to execute action {:id=>:test, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Reload<test>, action_result: false", :backtrace=>nil}
[2022-11-04T10:25:18,565][WARN ][logstash.runner          ] SIGTERM received. Shutting down.
[2022-11-04T10:25:18,814][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:test}
[2022-11-04T10:25:25,326][INFO ][logstash.javapipeline    ][test_filebeat] Pipeline terminated {"pipeline.id"=>"test_filebeat"}
[2022-11-04T10:25:26,380][INFO ][logstash.runner          ] Logstash shut down.
```

**Comment by andsel** [comment]
Have tested with following pipeline, and wasn't able to reproduce:
```
input {
  tcp {
    port => 1234
  }
}

output {
  elasticsearch {
    cloud_id => "<cloud_id>"
    api_key => "<api key>"
    index => "andsel_test"
    ssl => true
  }
  stdout{}
}
```

1. started Logstash configuring also the `xpack.management` in `config/logstash.yml` as:
```
xpack.management.enabled: true
xpack.management.pipeline.id: ["test*"]
xpack.management.elasticsearch.cloud_id: "<same cloud id used in the config>"
xpack.management.elasticsearch.cloud_auth: "<cloud auth>"
```
2. verified the pipeline was able to receive data and push into the cloud instance, the `ssl` setting was removed, testing no input was processed and the configuration error was reported on the log.
3. reinserted the `ssl` setting in the pipeline configuration, checked is was reloaded and was able to start processing data.


<details>
<summary>Logs during all the experiment</summary>

```
[2022-11-08T14:19:21,163][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600, :ssl_enabled=>false}
[2022-11-08T14:19:21,318][WARN ][logstash.configmanagement.elasticsearchsource] Restored connection to ES instance {:url=>"https://elastic:xxxxxx@0dd6ff36d79b455885db73ba390220cf.europe-west1.gcp.cloud.es.io:443/"}
[2022-11-08T14:19:21,364][INFO ][logstash.configmanagement.elasticsearchsource] Elasticsearch version determined (8.5.0) {:es_version=>8}
[2022-11-08T14:19:21,365][WARN ][logstash.configmanagement.elasticsearchsource] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>8}
[2022-11-08T14:19:21,484][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:19:26,625][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:19:31,611][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:19:36,602][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:19:41,601][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:19:46,610][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:19:51,606][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:19:56,608][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:20:01,611][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:20:06,609][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2022-11-08T14:20:11,936][INFO ][org.reflections.Reflections] Reflections took 63 ms to scan 1 urls, producing 125 keys and 438 values
[2022-11-08T14:20:12,184][INFO ][logstash.javapipeline    ] Pipeline `test_remote_1` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2022-11-08T14:20:12,217][INFO ][logstash.outputs.elasticsearch][test_remote_1] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//127.0.0.1"]}
[2022-11-08T14:20:12,233][INFO ][logstash.outputs.elasticsearch][test_remote_1] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://0dd6ff36d79b455885db73ba390220cf.europe-west1.gcp.cloud.es.io:443/]}}
[2022-11-08T14:20:12,442][WARN ][logstash.outputs.elasticsearch][test_remote_1] Restored connection to ES instance {:url=>"https://0dd6ff36d79b455885db73ba390220cf.europe-west1.gcp.cloud.es.io:443/"}
[2022-11-08T14:20:12,490][INFO ][logstash.outputs.elasticsearch][test_remote_1] Elasticsearch version determined (8.5.0) {:es_version=>8}
[2022-11-08T14:20:12,491][WARN ][logstash.outputs.elasticsearch][test_remote_1] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>8}
[2022-11-08T14:20:12,604][INFO ][logstash.outputs.elasticsearch][test_remote_1] Config is not compliant with data streams. `data_stream => auto` resolved to `false`
[2022-11-08T14:20:12,604][INFO ][logstash.outputs.elasticsearch][test_remote_1] Config is not compliant with data streams. `data_stream => auto` resolved to `false`
[2022-11-08T14:20:12,606][WARN ][logstash.outputs.elasticsearch][test_remote_1] Elasticsearch Output configured with `ecs_compatibility => v8`, which resolved to an UNRELEASED preview of version 8.0.0 of the Elastic Common Schema. Once ECS v8 and an updated release of this plugin are publicly available, you will need to update this plugin to resolve this warning.
[2022-11-08T14:20:12,614][WARN ][logstash.javapipeline    ][test_remote_1] 'pipeline.ordered' is enabled and is likely less efficient, consider disabling if preserving event order is not necessary
[2022-11-08T14:20:12,646][INFO ][logstash.javapipeline    ][test_remote_1] Starting pipeline {:pipeline_id=>"test_remote_1", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x79c72f07 run>"}
[2022-11-08T14:20:12,689][INFO ][logstash.outputs.elasticsearch][test_remote_1] Using a default mapping template {:es_version=>8, :ecs_compatibility=>:v8}
[2022-11-08T14:20:13,044][INFO ][logstash.javapipeline    ][test_remote_1] Pipeline Java execution initialization time {"seconds"=>0.4}
[2022-11-08T14:20:13,150][INFO ][logstash.javapipeline    ][test_remote_1] Pipeline started {"pipeline.id"=>"test_remote_1"}
[2022-11-08T14:20:13,156][INFO ][logstash.inputs.tcp      ][test_remote_1][28e48b7824106d93da1879f98ba1470e234bb1ceb80b34fd654457f3df891535] Starting tcp input listener {:address=>"0.0.0.0:1234", :ssl_enable=>false}
[2022-11-08T14:20:13,202][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:test_remote_1], :non_running_pipelines=>[]}
{
       "message" => "test remote nc 1",
    "@timestamp" => 2022-11-08T13:20:27.625983Z,
      "@version" => "1",
         "event" => {
        "original" => "test remote nc 1"
    }
}
[2022-11-08T14:21:06,758][INFO ][logstash.pipelineaction.reload] Reloading pipeline {"pipeline.id"=>:test_remote_1}
[2022-11-08T14:21:11,593][INFO ][logstash.javapipeline    ][test_remote_1] Pipeline terminated {"pipeline.id"=>"test_remote_1"}
[2022-11-08T14:21:11,913][INFO ][logstash.javapipeline    ] Pipeline `test_remote_1` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2022-11-08T14:21:11,917][INFO ][logstash.outputs.elasticsearch][test_remote_1] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//127.0.0.1"]}
[2022-11-08T14:21:11,920][ERROR][logstash.javapipeline    ][test_remote_1] Pipeline error {:pipeline_id=>"test_remote_1", :exception=>#<LogStash::ConfigurationError: Using api_key authentication requires SSL/TLS secured communication using the `ssl => true` option>, :backtrace=>["/home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/logstash-output-elasticsearch-11.9.0-java/lib/logstash/plugin_mixins/elasticsearch/common.rb:53:in `validate_authentication'", "/home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/logstash-output-elasticsearch-11.9.0-java/lib/logstash/plugin_mixins/elasticsearch/common.rb:26:in `build_client'", "/home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/logstash-output-elasticsearch-11.9.0-java/lib/logstash/outputs/elasticsearch.rb:296:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:68:in `register'", "/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:234:in `block in register_plugins'", "org/jruby/RubyArray.java:1865:in `each'", "/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:233:in `register_plugins'", "/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:600:in `maybe_setup_out_plugins'", "/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:246:in `start_workers'", "/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:191:in `run'", "/home/andrea/workspace/logstash_andsel/logstash-core/lib/logstash/java_pipeline.rb:143:in `block in start'"], "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x5e3481c9 run>"}
[2022-11-08T14:21:11,921][INFO ][logstash.javapipeline    ][test_remote_1] Pipeline terminated {"pipeline.id"=>"test_remote_1"}
[2022-11-08T14:21:11,929][ERROR][logstash.agent           ] Failed to execute action {:id=>:test_remote_1, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Reload<test_remote_1>, action_result: false", :backtrace=>nil}




[2022-11-08T14:21:47,114][INFO ][logstash.pipelineaction.reload] Reloading pipeline {"pipeline.id"=>:test_remote_1}
[2022-11-08T14:21:47,167][INFO ][logstash.javapipeline    ] Pipeline `test_remote_1` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2022-11-08T14:21:47,169][WARN ][org.logstash.execution.AbstractPipelineExt] Metric registration error: `input_throughput` could not be registered in namespace `[:stats, :pipelines, :test_remote_1, :flow]`
[2022-11-08T14:21:47,170][WARN ][org.logstash.execution.AbstractPipelineExt] Metric registration error: `filter_throughput` could not be registered in namespace `[:stats, :pipelines, :test_remote_1, :flow]`
[2022-11-08T14:21:47,170][WARN ][org.logstash.execution.AbstractPipelineExt] Metric registration error: `output_throughput` could not be registered in namespace `[:stats, :pipelines, :test_remote_1, :flow]`
[2022-11-08T14:21:47,170][WARN ][org.logstash.execution.AbstractPipelineExt] Metric registration error: `queue_backpressure` could not be registered in namespace `[:stats, :pipelines, :test_remote_1, :flow]`
[2022-11-08T14:21:47,170][WARN ][org.logstash.execution.AbstractPipelineExt] Metric registration error: `worker_concurrency` could not be registered in namespace `[:stats, :pipelines, :test_remote_1, :flow]`
[2022-11-08T14:21:47,172][INFO ][logstash.outputs.elasticsearch][test_remote_1] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//127.0.0.1"]}
[2022-11-08T14:21:47,185][INFO ][logstash.outputs.elasticsearch][test_remote_1] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://0dd6ff36d79b455885db73ba390220cf.europe-west1.gcp.cloud.es.io:443/]}}
[2022-11-08T14:21:47,432][WARN ][logstash.outputs.elasticsearch][test_remote_1] Restored connection to ES instance {:url=>"https://0dd6ff36d79b455885db73ba390220cf.europe-west1.gcp.cloud.es.io:443/"}
[2022-11-08T14:21:47,476][INFO ][logstash.outputs.elasticsearch][test_remote_1] Elasticsearch version determined (8.5.0) {:es_version=>8}
[2022-11-08T14:21:47,476][WARN ][logstash.outputs.elasticsearch][test_remote_1] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>8}
[2022-11-08T14:21:47,540][INFO ][logstash.outputs.elasticsearch][test_remote_1] Config is not compliant with data streams. `data_stream => auto` resolved to `false`
[2022-11-08T14:21:47,540][INFO ][logstash.outputs.elasticsearch][test_remote_1] Config is not compliant with data streams. `data_stream => auto` resolved to `false`
[2022-11-08T14:21:47,541][WARN ][logstash.outputs.elasticsearch][test_remote_1] Elasticsearch Output configured with `ecs_compatibility => v8`, which resolved to an UNRELEASED preview of version 8.0.0 of the Elastic Common Schema. Once ECS v8 and an updated release of this plugin are publicly available, you will need to update this plugin to resolve this warning.
[2022-11-08T14:21:47,549][WARN ][logstash.javapipeline    ][test_remote_1] 'pipeline.ordered' is enabled and is likely less efficient, consider disabling if preserving event order is not necessary
[2022-11-08T14:21:47,566][INFO ][logstash.javapipeline    ][test_remote_1] Starting pipeline {:pipeline_id=>"test_remote_1", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x3f56ec0b run>"}
[2022-11-08T14:21:47,591][INFO ][logstash.outputs.elasticsearch][test_remote_1] Using a default mapping template {:es_version=>8, :ecs_compatibility=>:v8}
[2022-11-08T14:21:47,610][INFO ][logstash.javapipeline    ][test_remote_1] Pipeline Java execution initialization time {"seconds"=>0.04}
[2022-11-08T14:21:47,617][INFO ][logstash.javapipeline    ][test_remote_1] Pipeline started {"pipeline.id"=>"test_remote_1"}
[2022-11-08T14:21:47,625][INFO ][logstash.inputs.tcp      ][test_remote_1][28e48b7824106d93da1879f98ba1470e234bb1ceb80b34fd654457f3df891535] Starting tcp input listener {:address=>"0.0.0.0:1234", :ssl_enable=>false}
[2022-11-08T14:21:47,633][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:test_remote_1], :non_running_pipelines=>[]}
{
       "message" => "test remote nc 2",
    "@timestamp" => 2022-11-08T13:21:51.452091Z,
      "@version" => "1",
         "event" => {
        "original" => "test remote nc 2"
    }
}

```

</details>

**Comment by roaksoax** [comment]
To follow up, we did a second test where:

 1. Install the stack, 8.5 should do, and configure central management.
 2. Configure the following pipeline in central Management:

```
input {
 <whatever you want>
}
output {
    elasticsearch {
        cloud_id => "<your cloud id>"
        api_key => "<your api key>"
    }
    stdout{}
}
```

 3. Logstash will then get the configuration an fail with the following error (see a full log below):
 
 `<LogStash::ConfigurationError: Using api_key authentication requires SSL/TLS secured communication using the `ssl => true` option>`

**Comment by andsel** [comment]
Looking in the error, the problem is due to a deadlock.

From an high point of view the flow is the following:
- the [reload action commands a `shutdown`](https://github.com/elastic/logstash/blob/e121650e56d7e79d9692ba34f117ce683f9e5f7c/logstash-core/lib/logstash/pipeline_action/reload.rb#L67) of the existing pipeline
  -  it [stops the input threads](https://github.com/elastic/logstash/blob/e121650e56d7e79d9692ba34f117ce683f9e5f7c/logstash-core/lib/logstash/java_pipeline.rb#L456) 
  - uses the ShutdwonWatcher to [wait for termination of the pipeline](https://github.com/elastic/logstash/blob/e121650e56d7e79d9692ba34f117ce683f9e5f7c/logstash-core/lib/logstash/java_pipeline.rb#L462).
- the [pipeline's thread](https://github.com/elastic/logstash/blob/e121650e56d7e79d9692ba34f117ce683f9e5f7c/logstash-core/lib/logstash/java_pipeline.rb#L146) wait for input and worker threads to terminate to later execute the `stop` callback method on each output plugin.
  - [wait for termination of inputs](https://github.com/elastic/logstash/blob/e121650e56d7e79d9692ba34f117ce683f9e5f7c/logstash-core/lib/logstash/java_pipeline.rb#L204)
  - then [request the shutdown](https://github.com/elastic/logstash/blob/e121650e56d7e79d9692ba34f117ce683f9e5f7c/logstash-core/lib/logstash/java_pipeline.rb#L475) of the workers, setting a flag that's [monitored by the `WorkerLoop`](https://github.com/elastic/logstash/blob/e121650e56d7e79d9692ba34f117ce683f9e5f7c/logstash-core/src/main/java/org/logstash/execution/WorkerLoop.java#L80) thread  after every event batch processing.
  - then after the worker [threads has joined](https://github.com/elastic/logstash/blob/e121650e56d7e79d9692ba34f117ce683f9e5f7c/logstash-core/lib/logstash/java_pipeline.rb#L479) it invokes the `stop` method on every [output plugin's instance](https://github.com/elastic/logstash/blob/e121650e56d7e79d9692ba34f117ce683f9e5f7c/logstash-core/lib/logstash/java_pipeline.rb#L482-L483).
- at the same time the ES output plugin is on a stoppable sleep, waiting that it can proceed with the execution of the `multi_receive` method, keeping locked the WorkerLoop in its execute phase.
  - the `multi_receive` [is blocked](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/25aedb6e448997c6831839b97221959028917583/lib/logstash/outputs/elasticsearch.rb#L372) on a [stoppable sleep](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/25aedb6e448997c6831839b97221959028917583/lib/logstash/outputs/elasticsearch.rb#L420) 
  - it's waiting that the connection pool resurrect a connection, but this could never happen because the error reported is not a transient error, the credentials never become valid, but it's receiving a 401 and and keeps retrying. [Wait to complete the post-register phase](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/25aedb6e448997c6831839b97221959028917583/lib/logstash/outputs/elasticsearch.rb#L311) to unlock the execution of `multi_receive`.
  - however the [`stoppable_sleep`](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/25aedb6e448997c6831839b97221959028917583/lib/logstash/plugin_mixins/elasticsearch/common.rb#L214) can't exit because the guard flag `@stopping` can't [become true](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/25aedb6e448997c6831839b97221959028917583/lib/logstash/outputs/elasticsearch.rb#L434) because the `stop` method on the plugin would be invoked only after all the pipeline's worker are existed.

**Comment by andsel** [comment]
Reopen because was automatically closed by PR https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1119

**Comment by roaksoax** [comment]
Closing issue as the PRs fixing it have now been complete and merged:

 - https://github.com/elastic/logstash-filter-elastic_integration/pull/28
 - https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/1119
