### ISSUE TITLE
Murmurhash3 0.1.7 doesn't provide java version

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#14831]
**Build scan**:

**Repro line**:
```
./gradlew installDefaultGems
```

**Reproduces locally?**:
yes

**Applicable branches**:
`main`, e4dc82a9b319625f79582730e173c8736d5a1ba6

**Failure history**:

**Failure excerpt**:
```
Error Bundler::InstallError, retrying 1/10
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/murmurhash3-0.1.7/ext/murmurhash3
/home/andrea/.sdkman/candidates/java/11.0.15-tem/bin/java -cp :/home/andrea/.gradle/caches/jars-9/4b7ea7ee921889f32773847de07d0ab6/snakeyaml-1.29.jar:/home/andrea/.gradle/caches/jars-9/466e6dbe9ac6d19b03a1f3c7e06e9799/gradle-download-task-4.0.4.jar:/home/andrea/.gradle/caches/jars-9/e47ff9aeec92c7ee54aefd6c530ecbae/jruby-complete-9.3.9.0.jar org.jruby.Main -I uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib -r ./siteconf20230109-99722-vy7131.rb extconf.rb
Exception in thread "main" java.lang.NoClassDefFoundError: org/gradle/internal/classpath/Instrumented
        at com.headius.options.Option.loadProperty(Option.java:400)
        at com.headius.options.IntegerOption.reloadValue(IntegerOption.java:38)
        at com.headius.options.IntegerOption.reloadValue(IntegerOption.java:20)
        at com.headius.options.Option.reload(Option.java:431)
        at com.headius.options.Option.load(Option.java:422)
        at org.jruby.util.cli.Options.<clinit>(Options.java:95)
        at org.jruby.util.log.LoggerFactory.<clinit>(LoggerFactory.java:36)
        at org.jruby.Main.<clinit>(Main.java:86)
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.classpath.Instrumented
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 8 more

extconf failed, exit code 1

Gem files will remain installed in /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/murmurhash3-0.1.7 for inspection.
Results logged to /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/extensions/universal-java-11/2.6.0/murmurhash3-0.1.7/gem_make.out

  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:93:in `run'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/ext_conf_builder.rb:47:in `block in build'
  org/jruby/ext/tempfile/Tempfile.java:242:in `open'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/ext_conf_builder.rb:26:in `build'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:159:in `build_extension'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:193:in `block in build_extensions'
  org/jruby/RubyArray.java:1865:in `each'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/ext/builder.rb:190:in `build_extensions'
  uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/installer.rb:837:in `build_extensions'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/source/rubygems.rb:207:in `install'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/installer/gem_installer.rb:54:in `install'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/worker.rb:62:in `apply_func'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/worker.rb:57:in `block in process_queue'
  org/jruby/RubyKernel.java:1507:in `loop'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/worker.rb:54:in `process_queue'
  /home/andrea/workspace/logstash_andsel/vendor/bundle/jruby/2.6.0/gems/bundler-2.3.18/lib/bundler/worker.rb:91:in `block in create_threads'

An error occurred while installing murmurhash3 (0.1.7), and Bundler cannot continue.

In Gemfile:
  logstash-filter-anonymize was resolved to 3.0.6, which depends on
    murmurhash3
```

**Comment by andsel** [comment]
Notified to `murmurhash3` repository with https://github.com/funny-falcon/murmurhash3-ruby/issues/11
