### ISSUE TITLE
[Test Failure] 7.17 ruby unit test agent_spec is failing

### ISSUE THREAD

**Issue by kaisecheng** [elastic/logstash#14961]
ci 
[169](https://logstash-ci.elastic.co/job/elastic+logstash+7.17+multijob--ruby-unit-tests/169/) 
[170](https://logstash-ci.elastic.co/job/elastic+logstash+7.17+multijob--ruby-unit-tests/170/)

flicking test in 7.17.9, agent_spec.rb, `when reloading a good config`

```
10:42:49     Failures:
10:42:49 
10:42:49       1) LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the last reload error
10:42:49          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
10:42:49          
10:42:49          LogStash::Error:
10:42:49            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::Reload<main>`
10:42:49          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:579
10:42:49          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
10:42:50          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
10:42:50          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
```

```
19:20:54     Failures:
19:20:54 
19:20:54       1) LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config resets the pipeline metric collector
19:20:54          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
19:20:54          
19:20:54          LogStash::Error:
19:20:54            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::Reload<main>`
19:20:54          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:579
19:20:54          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
19:20:54          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
19:20:54          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
19:20:54 
19:20:54       2) LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config does not reset the global event count
19:20:54          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
19:20:54          
19:20:54          LogStash::Error:
19:20:54            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::Reload<main>`
19:20:54          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:579
19:20:54          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
19:20:54          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
19:20:54          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
19:20:54 
19:20:54       3) LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config increases the successful reload count
19:20:54          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
19:20:54          
19:20:54          LogStash::Error:
19:20:54            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::Reload<main>`
19:20:54          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:579
19:20:54          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
19:20:54          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
19:20:54          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
19:20:54 
19:20:54       4) LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the last reload error
19:20:54          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
19:20:54          
19:20:54          LogStash::Error:
19:20:54            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::Reload<main>`
19:20:54          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:579
19:20:54          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
19:20:54          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
19:20:54          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
19:20:54 
19:20:54       5) LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the last reload error
19:20:54          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
19:20:54          
19:20:54          LogStash::Error:
19:20:54            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::StopAndDelete<main>`
19:20:54          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:573
19:20:54          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
19:20:54          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
19:20:54          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
19:20:54 
19:20:54       6) LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the failure reload timestamp
19:20:54          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
19:20:54          
19:20:54          LogStash::Error:
19:20:54            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::StopAndDelete<main>`
19:20:54          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:573
19:20:54          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
19:20:54          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
19:20:54          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
19:20:54 
19:20:54       7) LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config increases the successful reload count
19:20:54          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
19:20:54          
19:20:54          LogStash::Error:
19:20:54            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::StopAndDelete<main>`
19:20:54          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:573
19:20:54          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
19:20:54          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
19:20:54          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
19:20:54 
19:20:54     Finished in 16 minutes 5 seconds (files took 11.71 seconds to load)
19:20:54     2918 examples, 7 failures, 20 pending
19:20:54 
19:20:54     Failed examples:
19:20:54 
19:20:54     rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:1]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config resets the pipeline metric collector
19:20:54     rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:2]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config does not reset the global event count
19:20:54     rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:3]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config increases the successful reload count
19:20:54     rspec './logstash-core/spec/logstash/agent_spec.rb[1:2:1:11:1:6]' # LogStash::Agent using persisted queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the last reload error
19:20:54     rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:6]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the last reload error
19:20:54     rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:4]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the failure reload timestamp
19:20:54     rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:3]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config increases the successful reload count
19:20:54 
19:20:54     Randomized with seed 7908
```

**Comment by kaisecheng** [comment]
The failure can replicate locally `SPEC_OPTS="-fd -P logstash-core/spec/logstash/agent_spec.rb" ./gradlew :logstash-core:rubyTests --tests org.logstash.RSpecTests`
Fail path: [reload.rb old_pipeline.shutdown](https://github.com/elastic/logstash/blob/v7.17.9/logstash-core/lib/logstash/pipeline_action/reload.rb#L69) -> [java_pipeline.rb wait_for_shutdown](https://github.com/elastic/logstash/blob/v7.17.9/logstash-core/lib/logstash/java_pipeline.rb#L453)
