### ISSUE TITLE
Logstash in Openshift can't start if output is AWS S3

### ISSUE THREAD

**Issue by wenlinhe** [elastic/logstash#15092]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)
8.5.3 and 8.8.0
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)
From docker.io: image: 'logstash:8.5.3'
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)
Installed by helm chart in Openshift 
**Plugins installed**: (`bin/logstash-plugin list --verbose`)

**JVM** (e.g. `java -version`):

If the affected version of Logstash is 7.9 (or earlier), or if it is NOT using the bundled JDK or using the 'no-jdk' version in 7.10 (or higher), please provide the following information:

1. JVM version (`java -version`)
2. JVM installation source (e.g. from the Operating System's package manager, from source, etc).
3. Value of the `LS_JAVA_HOME` environment variable if set.
The logstash pod can't start so can't execute the command in the pod. Here is the log that may help:
Sending Logstash logs to /usr/share/logstash/logs which is now configured via log4j2.properties
[2023-06-16T03:04:37,829][INFO ][logstash.runner          ] Log4j configuration path used is: /usr/share/logstash/config/log4j2.properties
[2023-06-16T03:04:37,840][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"8.5.3", "jruby.version"=>"jruby 9.3.9.0 (2.6.8) 2022-10-24 537cd1f8bc OpenJDK 64-Bit Server VM 17.0.5+8 on 17.0.5+8 +indy +jit [x86_64-linux]"}
[2023-06-16T03:04:37,843][INFO ][logstash.runner          ] JVM bootstrap flags: [-Xms1g, -Xmx1g, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djruby.compile.invokedynamic=true, -Djruby.jit.threshold=0, -XX:+HeapDumpOnOutOfMemoryError, -Djava.security.egd=file:/dev/urandom, -Dlog4j2.isThreadContextMapInheritable=true, -Dls.cgroup.cpuacct.path.override=/, -Dls.cgroup.cpu.path.override=/, -Djruby.regexp.interruptible=true, -Djdk.io.File.enableADS=true, --add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED, --add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED, --add-opens=java.base/java.security=ALL-UNNAMED, --add-opens=java.base/java.io=ALL-UNNAMED, --add-opens=java.base/java.nio.channels=ALL-UNNAMED, --add-opens=java.base/sun.nio.ch=ALL-UNNAMED, --add-opens=java.management/sun.management=ALL-UNNAMED]

**OS version** (`uname -a` if on a Unix-like system):
Openshiift Server Version: 4.10.60
Kubernetes Version: v1.23.17+16bcd69
**Description of the problem including expected versus actual behavior**:
Logstash in Openshift can't start if output is AWS S3.  But with the same setting there is no problem if running Logstash binary directly in a VM

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem,
including (e.g.) pipeline definition(s), settings, locale, etc.  The easier
you make for us to reproduce it, the more likely that somebody will take the
time to look at it.

 1. Use helm chart (no matter from Elastic or Bitnami or the raw statefulset yaml) to install Logstash to Openshift cluster. With my own config file. Will show in the end.
 2. The Logstash pod can't start with below error:
[2023-06-16T03:04:45,063][INFO ][logstash.codecs.json     ] ECS compatibility is enabled but `target` option was not specified. This may cause fields to be set at the top-level of the event where they are likely to clash with the Elastic Common Schema. It is recommended to set the `target` option to avoid potential schema conflicts (if your data is ECS compliant or non-conflicting, feel free to ignore this message)
[2023-06-16T03:04:45,160][INFO ][logstash.codecs.json     ] ECS compatibility is enabled but `target` option was not specified. This may cause fields to be set at the top-level of the event where they are likely to clash with the Elastic Common Schema. It is recommended to set the `target` option to avoid potential schema conflicts (if your data is ECS compliant or non-conflicting, feel free to ignore this message)
[2023-06-16T03:04:45,199][INFO ][logstash.javapipeline    ] Pipeline `main` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2023-06-16T03:04:45,291][ERROR][logstash.javapipeline    ][main] Pipeline error {:pipeline_id=>"main", :exception=>#<Errno::ENOENT: No such file or directory - /logstash-config/logstash-aws-secret>, :backtrace=>["org/jruby/RubyIO.java:1227:in `sysopen'", "org/jruby/RubyFile.java:362:in `initialize'", "org/jruby/RubyClass.java:911:in `new'", "org/jruby/RubyIO.java:1146:in `open'", "/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/psych.rb:582:in `unsafe_load_file'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-integration-aws-7.0.0/lib/logstash/plugin_mixins/aws_config/v2.rb:51:in `aws_credentials'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-integration-aws-7.0.0/lib/logstash/plugin_mixins/aws_config/v2.rb:20:in `aws_options_hash'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-integration-aws-7.0.0/lib/logstash/outputs/s3.rb:277:in `full_options'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-integration-aws-7.0.0/lib/logstash/outputs/s3.rb:335:in `bucket_resource'", "/usr/share/logstash/vendor/bundle/jruby/2.6.0/gems/logstash-integration-aws-7.0.0/lib/logstash/outputs/s3.rb:207:in `register'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:68:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:234:in `block in register_plugins'", "org/jruby/RubyArray.java:1865:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:233:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:600:in `maybe_setup_out_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:246:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:191:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:143:in `block in start'"], "pipeline.sources"=>["/logstash-config/config/logstash.conf"], :thread=>"#<Thread:0x38416e57 run>"}
[2023-06-16T03:04:45,293][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-06-16T03:04:45,318][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: PipelineAction::Create<main>, action_result: false", :backtrace=>nil}
[2023-06-16T03:04:45,409][INFO ][logstash.runner          ] Logstash shut down.
[2023-06-16T03:04:45,424][FATAL][org.logstash.Logstash    ] Logstash stopped processing because of an error: (SystemExit) exit
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:790) ~[jruby.jar:?]
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:753) ~[jruby.jar:?]
	at usr.share.logstash.lib.bootstrap.environment.<main>(/usr/share/logstash/lib/bootstrap/environment.rb:91) ~[?:?]

**Provide logs (if relevant)**:
My pipline config is:

```
input {
  kafka {
    bootstrap_servers => "<AWS MSK broker endpoint>"
    topics => ["xxx","xxxx"]
    security_protocol => "SSL"
    ssl_key_password => "xxxx"
    ssl_keystore_location => "/logstash-config/config/store.keys"
    ssl_keystore_password => "xxxx"
    ssl_truststore_location => "/logstash-config/config/kafka.client.truststore.jks"
    codec => json
  }
}
filter {
  json {
    source => "message"
  }
  grok {
    match => { "logSourceCRN" => "crn:[^:]+:[^:]+:[^:]+:[^:]+:[^:]+:[^:]+:%{UUID:tenant}" }
  }
}
filter {
  ruby {
    code => '
      require "json"
      require "/logstash-config/config/decodeData.rb"
      if event.include?("dataObj")
        dataobj_value = event.get("dataObj")
        decoded_value = decode_data(dataobj_value)
        event.set("decoded_dataobj", decoded_value)
      end
    '
  }
}
output {
  if [tenant] == "c7312436-xxxx-xxxxxx" {
    s3 {
      aws_credentials_file => "/logstash-config/secret/logstash-aws-secret"
      region => "us-east-1"
      bucket => "bucket-from-terraform-loki-demo-001"
      retry_count => 3
      temporary_directory => "/tmp/c7312436-xxxx-xxxxxx"
      rotation_strategy => "size_and_time"
      size_file => 5242880
      time_file => 5
      codec => "json"
    }
  } else if [tenant] == "c7312436-xxxxx-4xxxxxx" {
    s3 {
      aws_credentials_file => "/logstash-config/logstash-aws-secret"
      region => "us-east-1"
      bucket => "bucket-xxxxx"
      retry_count => 3
      temporary_directory => "/tmp/c7312436-xxxx-xxxxxx"
      rotation_strategy => "size_and_time"
      size_file => 5242880
      time_file => 5
      codec => "json"
    }
  }
}

```

My AWS S3 secret content is:
```
[default]
aws_access_key_id = xxxxxxx
aws_secret_access_key = xxxxxxx
```
I also tried below format, no help either:
```
:access_key_id: "xxxxx"
:secret_access_key: "xxxxx"
```

**Comment by wenlinhe** [comment]
Closing it as I re-installed with Elastic Helm and it works.
