### ISSUE TITLE
Pipeline terminated after `Tried to write to a closed queue.` error.

### ISSUE THREAD

**Issue by mashhurs** [elastic/logstash#15159]
**Logstash information**:

Please include the following information:

1. Logstash version: `8.4.1` and above (`8.8.2`)
2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker): clone the Logstash repo and run from source or run `8.4.1`
3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes): command line `./bin/logstash`

**Plugins installed**: (`bin/logstash-plugin list --verbose`)

**JVM** (e.g. `java -version`): `openjdk 17.0.4.1 2022-08-12 LTS`
**OS version** (`uname -a` if on a Unix-like system): `Darwin mashhurs.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64`

**Description of the problem including expected versus actual behavior**:
Current behavior is upstream pipeline gets terminated. Expected behavior, the upstream pipeline shouldn't get terminated.

**Steps to reproduce**:

Use Central Pipeline Management and deploy pipelines.

 1. create `upstream` and `downstream` pipelines, config provided below with screenshots. Also do not forget to enable PQ (`queue.type: persisted`) in `logstash.yml` and decrease PQ page capacity (`queue.page_capacity: 512kb`) to easier reproducing;
 2. use `ruby-filter` in downstream pipeline to make slower output-throughput, using either `raise` exception or `sleep`
 3. after sometime, remove `ruby-filter` (or just add a code which doesn't blocks pipeline, `puts 'Hi!'` example) and deploy
 4. you will see the error

- `upstream` pipeline view in CPM:
<img width="502" alt="image" src="https://github.com/elastic/logstash/assets/99575341/7f7cfa46-05e0-40bf-9a8f-17fd0996f03d">

- `downstream` pipeline view in CPM:
<img width="483" alt="image" src="https://github.com/elastic/logstash/assets/99575341/942b6b39-6fd0-489a-a7f8-994efb840ca7">

**Provide logs (if relevant)**:
```

[2023-07-09T09:52:24,717][INFO ][logstash.javapipeline    ][downstream] Pipeline terminated {"pipeline.id"=>"downstream"}
[2023-07-09T09:52:24,720][ERROR][logstash.javapipeline    ][upstream] Pipeline worker error, the pipeline will be stopped {:pipeline_id=>"upstream", :error=>"Tried to write to a closed queue.", :exception=>Java::JavaLang::IllegalStateException, :backtrace=>["org.logstash.ext.JrubyAckedWriteClientExt.ensureOpen(org/logstash/ext/JrubyAckedWriteClientExt.java:94)", "org.logstash.ext.JrubyAckedWriteClientExt.doPush(org/logstash/ext/JrubyAckedWriteClientExt.java:77)", "org.logstash.ext.JRubyWrappedWriteClientExt.push(org/logstash/ext/JRubyWrappedWriteClientExt.java:102)", "Users.mashhur.Dev.elastic.logstash.logstash_minus_core.lib.logstash.plugins.builtin.pipeline.input.internalReceive(Users/mashhur/Dev/elastic/logstash/logstash_minus_core/lib/logstash/plugins/builtin/pipeline//Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb:67)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:309)", "org.jruby.javasupport.Java$ProcToInterface.callProc(org/jruby/javasupport/Java.java:1237)", "org.jruby.javasupport.Java$ProcToInterface.access$300(org/jruby/javasupport/Java.java:1214)", "org.jruby.javasupport.Java$ProcToInterface$ConcreteMethod.call(org/jruby/javasupport/Java.java:1275)", "java.util.stream.ForEachOps$ForEachOp$OfRef.accept(java/util/stream/ForEachOps.java:183)", "java.util.stream.ReferencePipeline$3$1.accept(java/util/stream/ReferencePipeline.java:197)", "java.util.Spliterators$ArraySpliterator.forEachRemaining(java/util/Spliterators.java:992)", "java.util.stream.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:509)", "java.util.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:499)", "java.util.stream.ForEachOps$ForEachOp.evaluateSequential(java/util/stream/ForEachOps.java:150)", "java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(java/util/stream/ForEachOps.java:173)", "java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:234)", "java.util.stream.ReferencePipeline.forEach(java/util/stream/ReferencePipeline.java:596)", "jdk.internal.reflect.GeneratedMethodAccessor25.invoke(jdk/internal/reflect/GeneratedMethodAccessor25)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:457)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:318)", "Users.mashhur.Dev.elastic.logstash.logstash_minus_core.lib.logstash.plugins.builtin.pipeline.input.internalReceive(Users/mashhur/Dev/elastic/logstash/logstash_minus_core/lib/logstash/plugins/builtin/pipeline//Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb:65)", "org.logstash.plugins.pipeline.PipelineBus.lambda$sendEvents$1(org/logstash/plugins/pipeline/PipelineBus.java:76)", "java.util.concurrent.ConcurrentHashMap.forEach(java/util/concurrent/ConcurrentHashMap.java:1603)", "org.logstash.plugins.pipeline.PipelineBus.sendEvents(org/logstash/plugins/pipeline/PipelineBus.java:64)", "jdk.internal.reflect.GeneratedMethodAccessor24.invoke(jdk/internal/reflect/GeneratedMethodAccessor24)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:487)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:342)", "Users.mashhur.Dev.elastic.logstash.logstash_minus_core.lib.logstash.plugins.builtin.pipeline.output.multi_receive(Users/mashhur/Dev/elastic/logstash/logstash_minus_core/lib/logstash/plugins/builtin/pipeline//Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/plugins/builtin/pipeline/output.rb:39)", "org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.invokeOutput(org/logstash/config/ir/compiler/OutputStrategyExt.java:153)", "org.logstash.config.ir.compiler.OutputStrategyExt$SimpleAbstractOutputStrategyExt.doOutput(org/logstash/config/ir/compiler/OutputStrategyExt.java:279)", "org.logstash.config.ir.compiler.OutputStrategyExt$SharedOutputStrategyExt.output(org/logstash/config/ir/compiler/OutputStrategyExt.java:312)", "org.logstash.config.ir.compiler.OutputStrategyExt$AbstractOutputStrategyExt.multiReceive(org/logstash/config/ir/compiler/OutputStrategyExt.java:143)", "org.logstash.config.ir.compiler.OutputDelegatorExt.doOutput(org/logstash/config/ir/compiler/OutputDelegatorExt.java:102)", "org.logstash.config.ir.compiler.AbstractOutputDelegatorExt.multi_receive(org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121)", "org.logstash.generated.CompiledDataset1.compute(org/logstash/generated/CompiledDataset1)", "org.logstash.config.ir.CompiledPipeline$CompiledOrderedExecution.compute(org/logstash/config/ir/CompiledPipeline.java:319)", "org.logstash.config.ir.CompiledPipeline$CompiledOrderedExecution.compute(org/logstash/config/ir/CompiledPipeline.java:306)", "org.logstash.execution.WorkerLoop.run(org/logstash/execution/WorkerLoop.java:87)", "jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)", "jdk.internal.reflect.NativeMethodAccessorImpl.invoke(jdk/internal/reflect/NativeMethodAccessorImpl.java:77)", "jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)", "java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)", "org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:427)", "org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:294)", "Users.mashhur.Dev.elastic.logstash.logstash_minus_core.lib.logstash.java_pipeline.start_workers(Users/mashhur/Dev/elastic/logstash/logstash_minus_core/lib/logstash//Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:300)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:309)", "java.lang.Thread.run(java/lang/Thread.java:833)"], :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 sleep>"}
[2023-07-09T09:52:24,729][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:25,331][INFO ][logstash.javapipeline    ] Pipeline `downstream` is configured with `pipeline.ecs_compatibility: v8` setting. All plugins in this pipeline will default to `ecs_compatibility => v8` unless explicitly configured otherwise.
[2023-07-09T09:52:25,333][WARN ][logstash.javapipeline    ][downstream] 'pipeline.ordered' is enabled and is likely less efficient, consider disabling if preserving event order is not necessary
[2023-07-09T09:52:25,337][INFO ][logstash.javapipeline    ][downstream] Starting pipeline {:pipeline_id=>"downstream", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x79270825 run>"}
[2023-07-09T09:52:25,347][INFO ][logstash.javapipeline    ][downstream] Pipeline Java execution initialization time {"seconds"=>0.01}

[2023-07-09T09:52:25,735][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:26,741][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:27,748][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:28,754][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:29,758][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:30,763][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:31,770][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:32,773][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:33,778][WARN ][logstash.javapipeline    ][upstream] Waiting for input plugin to close {:pipeline_id=>"upstream", :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:34,806][ERROR][logstash.javapipeline    ][upstream] Pipeline error {:pipeline_id=>"upstream", :exception=>#<RuntimeError: Unable to stop input plugin(s)>, :backtrace=>["/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:370:in `block in monitor_inputs_and_workers'", "org/jruby/RubyKernel.java:1507:in `loop'", "/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:341:in `monitor_inputs_and_workers'", "/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:200:in `run'", "/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/java_pipeline.rb:142:in `block in start'"], "pipeline.sources"=>["central pipeline management"], :thread=>"#<Thread:0x1c0ee0b1@/Users/mashhur/Dev/elastic/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:52 run>"}
[2023-07-09T09:52:34,807][INFO ][logstash.javapipeline    ][upstream] Pipeline terminated {"pipeline.id"=>"upstream"}
```

**Comment by yaauie** [comment]
I think our bug originates [here](https://github.com/elastic/logstash/blob/main/logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb#L78-L83).

If the input (receiving) plugin is sent `stop` (e.g., as part of a reload), it:
 - (1) unlistens from the address (preventing future batches from being routed to it), and then 
 - (2) begins reporting that the plugin is not running, which
 - (3) enables the pipeline to be shut down and its queue closed.

In an upstream pipeline's worker thread, a batch of events is safely routed by the `PipelineBus` to each appropriate `AddressState`, but the actual queueing of a batch of events only checks the [AddressState's input to ensure it is effectively-writable before writing the _first_ event in the batch](https://github.com/elastic/logstash/blob/main/logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb#L59) before queueing one event at a time. 

When a batch of events in the upstream pipeline has _already_ been routed to a downstream input, and that input's pipeline is shut down before the batch in the upstream has completed, the output fails to write to the closed queue as reported here.

When the downstream pipeline's queue is exerting back-pressure there is a high likelihood that the upstream pipeline's outputs are blocked long enough for the downstream pipeline to close out of under it.

****

I believe we may need something like a latch on the input plugin to prevent it from reporting that it is not running until pending writes have completed. I have not fully though through possible side-effects.

**Comment by yaauie** [comment]
I spiked briefly on [using a `ReadWriteLock` to guard access to the `AddressState`'s input](https://gist.github.com/yaauie/5bf4db9f7f7bd17d6b0b84741940a9a1), but realized that has the unfortunate side-effect of making `PipelineBus#unlistenNonblock` _block_ while in synchronized access to the effectively-globally-shared map of address states which may in turn cause a deadlock and/or impact unrelated pipelines.
