### ISSUE TITLE
[DeadLetterQueueWriter] Unable to finalize segment - java.nio.file.NoSuchFileException

### ISSUE THREAD

**Issue by edmocosta** [elastic/logstash#15227]
**Logstash information**:

Please include the following information:

1. Logstash version: 8.9
2. Logstash installation: built from source
3. How is Logstash being run: command line 

JVM version
```
openjdk 17.0.8 2023-07-18
OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7)
OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode)
```

**Description of the problem including expected versus actual behavior**:
There are some concurrency issues between the  `DeadLetterQueueReader` and  `DeadLetterQueueWriter` that generates `java.nio.file.NoSuchFileException` exceptions. 
The Reader is deleting the "oldest segment" file while it still being processed by the Writer, which throws the `NoSuchFileException`. There are more details on this error on the logs section.

**Steps to reproduce**:
 1.  Enabled the dead letter queue for the pipelines and increase the number of workers
 2. Produce several messages in a way that the Elasticsearch output plugins fails and send them to the DLQ
 
Example:

```yaml
 - pipeline.id: input
   pipeline.workers: 32
   config.string: |
    input { generator { message=> 'Generated!\n' } }
    output {  pipeline { send_to => ["forward_to_test"] }  }

 - pipeline.id: forward_unprocessed_to_test
   pipeline.workers: 16
   config.string: |
     input { pipeline { address => "forward_to_test" } }
     output {
        elasticsearch {
          hosts => ["localhost:9200"]
          index => "%{[Test][customer]}-%{[Test][index]}-%{[@metadata][date]}"
          codec => "plain"
          dlq_on_failed_indexname_interpolation => true
        }
     }

 - pipeline.id: forward_dlq_to_test
   config.string: |
      input {
        dead_letter_queue {
          path => "/elastic/logstash/dead_letter_queue"
          pipeline_id => "forward_unprocessed_to_test"
          commit_offsets => true
          clean_consumed => true
        }
      }
      
      output {
       elasticsearch {
          hosts => ["localhost:9200"]
          index => "%{[Test][customer]}-%{[Test][index]}-%{[@metadata][date]}"
          codec => "plain"
          dlq_on_failed_indexname_interpolation => true
       }
      }
```

**Provide logs**:

The logs messages were slightly changed to provide more information about the running thread, etc.

The issue is consistent with the following situation:

1 - `DeadLetterQueueWriter`: creates a new segment `5724.log.tmp`
2 - `DeadLetterQueueWriter#scheduler`: Successfully seal segment with index `5724`
3 - `DeadLetterQueueReader`: Deletes the set oldest segment (`5718.log`) that is concurrently being processed by the `DeadLetterQueueWriter`.
4 - `java.nio.file.NoSuchFileException` happens on the `DeadLetterQueueWriter` due to the missing `5718.log` 
5 - `DeadLetterQueueWriter#scheduler`: Try again to seal the segment  `5724.log` that was already sealed (moved), which raise a
`java.nio.file.NoSuchFileException` again.

```java
[2023-08-01T14:58:05,535][DEBUG][org.logstash.common.io.DeadLetterQueueWriter] Created new head segment /Users/edmo.vamerlatti/github.com/elastic/logstash/dead_letter_queue/forward_unprocessed_to_test/5724.log.tmp
...
[2023-08-01T14:58:06,133][DEBUG][org.logstash.common.io.DeadLetterQueueWriter] Trying to sealed segment with index 5724 because the segment has expired 'flush_interval' by thread dlq-flush-check-forward_unprocessed_to_test-0
[2023-08-01T14:58:06,133][DEBUG][org.logstash.common.io.DeadLetterQueueWriter] Sealed segment with index 5724 because the segment has expired 'flush_interval' by thread dlq-flush-check-forward_unprocessed_to_test-0
[2023-08-01T14:58:06,133][DEBUG][org.logstash.common.io.DeadLetterQueueWriter] Oldest segment is /Users/edmo.vamerlatti/github.com/elastic/logstash/dead_letter_queue/forward_unprocessed_to_test/5718.log
[2023-08-01T14:58:06,133][DEBUG][org.logstash.common.io.DeadLetterQueueReader][forward_dlq_to_test][08b9b64ec0bb853c68cda523b735f888518bd563eee8fdc340ba845e89701c3d] Deleted segment /Users/edmo.vamerlatti/github.com/elastic/logstash/dead_letter_queue/forward_unprocessed_to_test/5718.log
[2023-08-01T14:58:06,133][ERROR][org.logstash.common.io.DeadLetterQueueWriter] Unable to finalize segment
java.nio.file.NoSuchFileException: /Users/edmo.vamerlatti/github.com/elastic/logstash/dead_letter_queue/forward_unprocessed_to_test/5718.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148) ~[?:?]
	at java.nio.file.Files.readAttributes(Files.java:1851) ~[?:?]
	at java.nio.file.Files.size(Files.java:2468) ~[?:?]
	at org.logstash.common.io.DeadLetterQueueWriter.readTimestampOfLastEventInSegment(DeadLetterQueueWriter.java:457) ~[logstash-core.jar:?]
	at org.logstash.common.io.DeadLetterQueueWriter.updateOldestSegmentReference(DeadLetterQueueWriter.java:443) ~[logstash-core.jar:?]
	at org.logstash.common.io.DeadLetterQueueWriter.finalizeSegment(DeadLetterQueueWriter.java:542) ~[logstash-core.jar:?]
	at org.logstash.common.io.DeadLetterQueueWriter.scheduledFlushCheck(DeadLetterQueueWriter.java:507) ~[logstash-core.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2023-08-01T14:58:58,314][DEBUG][org.logstash.common.io.DeadLetterQueueWriter] Trying to sealed segment with index 5724 because the segment has expired 'flush_interval' by thread dlq-flush-check-forward_unprocessed_to_test-0
[2023-08-01T15:00:21,948][ERROR][org.logstash.common.io.DeadLetterQueueWriter] Unable to finalize segment
java.nio.file.NoSuchFileException: /Users/edmo.vamerlatti/github.com/elastic/logstash/dead_letter_queue/forward_unprocessed_to_test/5724.log.tmp -> /Users/edmo.vamerlatti/github.com/elastic/logstash/dead_letter_queue/forward_unprocessed_to_test/5724.log
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:92) ~[?:?]
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106) ~[?:?]
	at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:416) ~[?:?]
	at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:266) ~[?:?]
	at java.nio.file.Files.move(Files.java:1432) ~[?:?]
	at org.logstash.common.io.DeadLetterQueueWriter.sealSegment(DeadLetterQueueWriter.java:566) ~[logstash-core.jar:?]
	at org.logstash.common.io.DeadLetterQueueWriter.finalizeSegment(DeadLetterQueueWriter.java:540) ~[logstash-core.jar:?]
	at org.logstash.common.io.DeadLetterQueueWriter.scheduledFlushCheck(DeadLetterQueueWriter.java:507) ~[logstash-core.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

---
Related https://github.com/elastic/logstash/issues/15078

**Comment by landon-lengyel** [comment]
Just wanted to add a comment for anyone else that encounters this issue still (version `8.17.1-1`), I _think_ it can also be caused by incorrectly clearing out the Dead Letter Queue. If you clear the queue by performing a simple `rm *` in the queue directory, it will wipe out the `*.tmp` file that Logstash appears to be looking for and you have to restart the service (often with a SIGKILL since it seems to get stuck). 

Don't clear out the queue that way. If the Logstash devs see this, perhaps a check for if the file has been removed, and simply re-create it could make Logstash more resilient.
