### ISSUE TITLE
[Test] agent tests throw NPE when getting pipeline reporter snapshot

### ISSUE THREAD

**Issue by kaisecheng** [elastic/logstash#15300]
The test against metrics reporter fails to shutdown old pipeline when the native thread is done and returns null.
https://github.com/elastic/logstash/blob/v7.17.12/logstash-core/src/main/java/org/logstash/execution/PipelineReporterExt.java#L164

**Build scan**:
https://logstash-ci.elastic.co/job/elastic+logstash+pull-request/7307

**Repro line**:

**Reproduces locally?**:
yes

**Applicable branches**:
7.17.12

**Failure history**:

**Failure excerpt**:

```
03:10:38     Failures:
03:10:38 
03:10:38       1) LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config sets the success reload timestamp
03:10:38          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
03:10:38          
03:10:38          LogStash::Error:
03:10:38            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::StopAndDelete<main>`
03:10:38          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:573
03:10:38          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
03:10:38          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
03:10:38          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
03:10:38 
03:10:38       2) LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config increases the successful reload count
03:10:38          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
03:10:38          
03:10:38          LogStash::Error:
03:10:38            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::StopAndDelete<main>`
03:10:38          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:573
03:10:39          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
03:10:39          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
03:10:39          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
03:10:39 
03:10:39       3) LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not reset the global event count
03:10:39          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
03:10:39          
03:10:39          LogStash::Error:
03:10:39            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::StopAndDelete<main>`
03:10:39          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:573
03:10:39          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
03:10:39          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
03:10:39          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
03:10:39 
03:10:39       4) LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the last reload error
03:10:39          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
03:10:39          
03:10:39          LogStash::Error:
03:10:39            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::StopAndDelete<main>`
03:10:39          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:573
03:10:39          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
03:10:39          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
03:10:39          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
03:10:39 
03:10:39       5) LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the failure reload timestamp
03:10:39          Failure/Error: Unable to find org/logstash/execution/ConvergeResultExt.java to read failed line
03:10:39          
03:10:39          LogStash::Error:
03:10:39            Don't know how to handle `Java::JavaLang::NullPointerException` for `PipelineAction::StopAndDelete<main>`
03:10:39          Shared Example Group: "all Agent tests" called from ./logstash-core/spec/logstash/agent_spec.rb:573
03:10:39          # org/logstash/execution/ConvergeResultExt.java:135:in `create'
03:10:39          # org/logstash/execution/ConvergeResultExt.java:60:in `add'
03:10:39          # ./logstash-core/lib/logstash/agent.rb:405:in `block in converge_state'
03:10:39 
03:10:39     Finished in 16 minutes 24 seconds (files took 12.13 seconds to load)
03:10:39     2512 examples, 5 failures, 21 pending
03:10:39 
03:10:39     Failed examples:
03:10:39 
03:10:39     rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:5]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config sets the success reload timestamp
03:10:39     rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:3]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config increases the successful reload count
03:10:39     rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:2]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not reset the global event count
03:10:39     rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:6]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the last reload error
03:10:39     rspec './logstash-core/spec/logstash/agent_spec.rb[1:1:1:11:1:4]' # LogStash::Agent using memory queue behaves like all Agent tests metrics after config reloading when reloading a good config does not set the failure reload timestamp
```

**Comment by kaisecheng** [comment]
duplicate of https://github.com/elastic/logstash/issues/14961
