### ISSUE TITLE
[Meta]: QA acceptance (packaging) framework improvements

### ISSUE THREAD

**Issue by dliappis** [elastic/logstash#15784]
Having done the [initial refactoring](https://github.com/elastic/logstash/pull/15696) which moved us away from Vagrant, there are a number of areas that it needs further improvements:

- [x] Fix service startup: https://github.com/elastic/logstash/pull/15900, https://github.com/elastic/logstash/pull/15907
~- [ ] Ensure that all network based operations (e.g. `logstash-plugin install` etc.) use retries.~ **tracked in**: https://github.com/elastic/ingest-dev/issues/2965
~- [ ] Improve error messages; while logstash installation failures do provide helpful [messages](https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/73#018cf454-7c48-4656-b0a2-9c268923ffa5/1035-1127), other tests e.g. that logstash service is running, or pluging related rely on a lot of [boolean style functions]((https://github.com/elastic/logstash/blob/5b98f7d63dd7dd0ec853736dc4391bc0ba8f0820/qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb#L42-L53)) which [when failing](https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/73#018cf454-7c48-4656-b0a2-9c268923ffa5/1035-1127), there are no clues as to why (lacking stdout/stderr from command).[^1]~ **tracked in:** https://github.com/elastic/ingest-dev/issues/2966
~- [ ] Re-review [test scenarios](https://github.com/elastic/logstash/tree/main/qa/acceptance/spec/lib) (especially [plugin related](https://github.com/elastic/logstash/tree/main/qa/acceptance/spec/shared_examples/cli/logstash-plugin)) to see if they are still relevant and modernize as needed.~ **tracked in:** https://github.com/elastic/ingest-dev/issues/2964
- [x] Fix service start checks: https://github.com/elastic/ingest-dev/issues/2950

<details><summary>[^1]: Example failures</summary>

```
CLI operation
  behaves like logstash install
    on [Oracle Linux Server 7.9]
      with a direct internet connection
        when the plugin exist
          from a local `.GEM` file
            successfully install the plugin
          when fetching a gem from rubygems
            successfully install the plugin (FAILED - 1)

  ...

  behaves like logstash remove
    logstash-plugin remove on [Oracle Linux Server 7.9]
      when the plugin isn't installed
        fails to remove it
      when the plugin is installed
        successfully removes it (FAILED - 2)

  ...

  1) CLI operation behaves like logstash install on [Oracle Linux Server 7.9] with a direct internet connection when the plugin exist when fetching a gem from rubygems successfully install the plugin
    Failure/Error: expect(logstash).to be_running
      expected #<ServiceTester::Artifact:0x6c6b00f1 @hostfacts=#<HostFacts:0x48126a17 @os_release={"NAME"=>"Oracle Linux Server", "VERSION"=>"7.9", "ID"=>"ol", "ID_LIKE"=>"fedora", "VARIANT"=>"Server", "VARIANT_ID"=>"server", "VERSION_ID"=>"7.9", "PRETTY_NAME"=>"Oracle Linux Server 7.9", "ANSI_COLOR"=>"0;31", "CPE_NAME"=>"cpe:/o:oracle:linux:7:9:server", "HOME_URL"=>"https://linux.oracle.com/", "BUG_REPORT_URL"=>"https://github.com/oracle/oracle-linux", "ORACLE_BUGZILLA_PRODUCT"=>"Oracle Linux 7", "ORACLE_BUGZILLA_PRODUCT_VERSION"=>"7.9", "ORACLE_SUPPORT_PRODUCT"=>"Oracle Linux", "ORACLE_SUPPORT_PRODUCT_VERSION"=>"7.9"}>, @client=#<ServiceTester::RedhatCommands:0x6f695077>, @skip_jdk_infix=false, @options={}> to be running
    Shared Example Group: "logstash install" called from ./acceptance/spec/lib/cli_operation_spec.rb:35
    # ./acceptance/spec/shared_examples/cli/logstash-plugin/install.rb:61:in `block in <main>'
    # ./acceptance/spec/spec_helper.rb:29:in `with_running_logstash_service'
    # ./acceptance/spec/shared_examples/cli/logstash-plugin/install.rb:60:in `block in <main>'
    # ./Rakefile:30:in `block in <main>'

...

2) CLI operation behaves like logstash remove logstash-plugin remove on [Oracle Linux Server 7.9] when the plugin is installed successfully removes it
    Failure/Error: expect(logstash).to be_running
      expected #<ServiceTester::Artifact:0x6c6b00f1 @hostfacts=#<HostFacts:0x48126a17 @os_release={"NAME"=>"Oracle Linux Server", "VERSION"=>"7.9", "ID"=>"ol", "ID_LIKE"=>"fedora", "VARIANT"=>"Server", "VARIANT_ID"=>"server", "VERSION_ID"=>"7.9", "PRETTY_NAME"=>"Oracle Linux Server 7.9", "ANSI_COLOR"=>"0;31", "CPE_NAME"=>"cpe:/o:oracle:linux:7:9:server", "HOME_URL"=>"https://linux.oracle.com/", "BUG_REPORT_URL"=>"https://github.com/oracle/oracle-linux", "ORACLE_BUGZILLA_PRODUCT"=>"Oracle Linux 7", "ORACLE_BUGZILLA_PRODUCT_VERSION"=>"7.9", "ORACLE_SUPPORT_PRODUCT"=>"Oracle Linux", "ORACLE_SUPPORT_PRODUCT_VERSION"=>"7.9"}>, @client=#<ServiceTester::RedhatCommands:0x6f695077>, @skip_jdk_infix=false, @options={}> to be running
    Shared Example Group: "logstash remove" called from ./acceptance/spec/lib/cli_operation_spec.rb:38
    # ./acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb:48:in `block in <main>'
    # ./acceptance/spec/spec_helper.rb:29:in `with_running_logstash_service'
    # ./acceptance/spec/shared_examples/cli/logstash-plugin/remove.rb:47:in `block in <main>'
    # ./Rakefile:30:in `block in <main>'
```
</details>

**Comment by dliappis** [comment]
It appears that rpm based distros are particularly flaky about checking whether the service is running, e.g. https://buildkite.com/elastic/logstash-exhaustive-tests-pipeline/builds/179#018d64c4-eb75-4e1d-9539-f46954a173de

(background in https://elastic.slack.com/archives/C04J9GKTZRQ/p1707136137158159)
