### ISSUE TITLE
Provide option to suppress redis input errors for "cold" redis servers

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#1600]
Use case:

2 redis inputs defined in LS config.  One of the 2 redis inputs is only used in the failover scenario (will be intentionally stopped most of the time).  Currently, LS will process the redis input with the live redis server and throw repeated errors on the 2nd LS input (something like the following):
```
A plugin had an unrecoverable error. Will restart this plugin. 
Plugin: <LogStash::Inputs::Redis host=>"xxxxx", type=>"redis-input", data_type=>"list", key=>"logstash", tags=>["tenant-instance-2"], name=>"default"> 
Error: No route to host - SocketChannel.connect {:level=>:error} 
Failed to get event from Redis {:name=>"default", :exception=>#<Errno::EHOSTUNREACH: No route to host - SocketChannel.connect>, :backtrace=>["org/jruby/ext/socket/RubyTCPSocket.java:123:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/connection/ruby.rb:13:in `initialize'", "org/jruby/RubyIO.java:852:in `new'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/connection/ruby.rb:74:in `connect'", "org/jruby/ext/timeout/Timeout.java:126:in `timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/connection/ruby.rb:73:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/connection/ruby.rb:211:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:285:in `establish_connection'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:79:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:257:in `with_reconnect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:78:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:240:in `with_socket_timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis/client.rb:178:in `call_with_timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:1038:in `_bpop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'", "file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'", "file:/opt/logstash/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/monitor.rb:210:in `mon_synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:37:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:1035:in `_bpop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/redis-3.0.7/lib/redis.rb:1064:in `blpop'", "/opt/logstash/lib/logstash/inputs/redis.rb:148:in `list_listener'", "/opt/logstash/lib/logstash/inputs/redis.rb:229:in `listener_loop'", "/opt/logstash/lib/logstash/inputs/redis.rb:245:in `run'", "/opt/logstash/lib/logstash/pipeline.rb:163:in `inputworker'", "/opt/logstash/lib/logstash/pipeline.rb:157:in `start_input'"], :level=>:warn} 
A plugin had an unrecoverable error. Will restart this plugin. 
Plugin: <LogStash::Inputs::Redis host=>"169.254.220.154", type=>"redis-input", data_type=>"list", key=>"logstash", tags=>["tenant-instance-2"], name=>"default"> 
Error: No route to host - SocketChannel.connect {:level=>:error}
```
Ii would be nice to be able to suppress these errors.  For example, perhaps add an input parameter configuration option allowing the user to specify a redis input as "cold" (and as a result, suppress the repeating connection errors).

**Comment by jordansissel** [comment]
@colinsurprenant I think this belongs in our discussion of multiple-loggers where we could allow users to silence log messages from certain plugins.

**Comment by purbon** [comment]
(noted during fix it friday) 

I think the discussion in here got diverged from having multiple multiple redis outputs, to have multiple internal loggers. Going to open a new issue on that and close this. If the issue still persist we can always reopen.

**Comment by purbon** [comment]
Moved this issue to https://github.com/elastic/logstash/issues/3300, changing the scope to the multiple loggers.
