### ISSUE TITLE
Windows 2022 flaky test

### ISSUE THREAD

**Issue by andsel** [elastic/logstash#16073]
**Build scan**:
https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/147#018ec05f-ec42-4443-a380-9d8527ac5dce

**Repro line**:

**Reproduces locally?**:
No

**Applicable branches**:
`7.17`

**Failure history**:

**Failure excerpt**:

```
    Failures:
      1) LogStash::Filters::Geoip DownloadManager assert database should raise error if file is invalid
         Failure/Error: FileUtils.cp_r(cc_database_paths, dir_path)
         Errno::EACCES:
           Permission denied - A:/data/plugins/filters/geoip/CC/GeoLite2-City.mmdb
         # ./spec/filters/geoip/test_helper.rb:121:in `copy_cc'
         # ./spec/filters/geoip/download_manager_spec.rb:163:in `block in <main>'
         # A:/vendor/bundle/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in A:/vendor/bundle/jruby/2.5.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
         # A:\lib\bootstrap\rspec.rb:31:in `<main>'
    Finished in 43.33 seconds (files took 8.74 seconds to load)
    272 examples, 1 failure, 4 pending
```

**Comment by dliappis** [comment]
Similar failures in the past:

- https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/142
- https://buildkite.com/elastic/logstash-windows-jdk-matrix-pipeline/builds/133
