### ISSUE TITLE
File input throws exception when reading files with Japanese File name 

### ISSUE THREAD

**Issue by masashinakane** [elastic/logstash#2155]
Hi,  it is logstash 1.4.2

When I configure the logstash to read a file with Japanese file name , it throws Error

```
{:timestamp=>"2014-12-02T11:47:09.281000+0900", :message=>"config LogStash::Outputs::Tcp/@mode = \"client\"", :level=>:debug, :file=>"/Program Files/SNMP-L/logstash-1.4.2/lib/logstash/config/mixin.rb", :line=>"105"}
{:timestamp=>"2014-12-02T11:47:09.703000+0900", :message=>"Registering file input", :path=>["C:\\Program Files\\Apache Software Foundation\\Apache2.2\\logs\\コピー.log"], :level=>:info, :file=>"/Program Files/SNMP-L/logstash-1.4.2/lib/logstash/inputs/file.rb", :line=>"74"}
+---------------------------------------------------------+
| An unexpected error occurred. This is probably a bug.   |
| You can find help with this problem in a few places:    |
|                                                         |
| * chat: #logstash IRC channel on freenode irc.          |
|     IRC via the web: http://goo.gl/TI4Ro                |
| * email: logstash-users@googlegroups.com                |
| * bug system: https://logstash.jira.com/                |
|                                                         |
+---------------------------------------------------------+
The error reported is: 
  incompatible character encodings: UTF-8 and Windows-31J
org/jruby/RubyString.java:3408:in `rindex'
file:/C:/Program Files/SNMP-L/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/pathname.rb:48:in `chop_basename'
file:/C:/Program Files/SNMP-L/logstash-1.4.2/vendor/jar/jruby-complete-1.7.11.jar!/META-INF/jruby.home/lib/ruby/1.9/pathname.rb:221:in `relative?'
C:/Program Files/SNMP-L/logstash-1.4.2/lib/logstash/inputs/file.rb:85:in `register'
org/jruby/RubyArray.java:1613:in `each'
C:/Program Files/SNMP-L/logstash-1.4.2/lib/logstash/inputs/file.rb:84:in `register'
C:/Program Files/SNMP-L/logstash-1.4.2/lib/logstash/pipeline.rb:135:in `start_inputs'
org/jruby/RubyArray.java:1613:in `each'
C:/Program Files/SNMP-L/logstash-1.4.2/lib/logstash/pipeline.rb:134:in `start_inputs'
C:/Program Files/SNMP-L/logstash-1.4.2/lib/logstash/pipeline.rb:72:in `run'
C:/Program Files/SNMP-L/logstash-1.4.2/lib/logstash/agent.rb:139:in `execute'
C:\Program Files\SNMP-L\logstash-1.4.2\lib\logstash\runner.rb:168:in `run'
org/jruby/RubyProc.java:271:in `call'
C:/Program Files/SNMP-L/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/stud-0.0.17/lib/stud/task.rb:12:in `initialize'
{:timestamp=>"2014-12-02T12:20:12.321000+0900", :message=>"Reading config file", :file=>"/Program Files/SNMP-L/logstash-1.4.2/lib/logstash/agent.rb", :level=>:debug, :line=>"301"}
```

Can anyone succeed to read a file with non-ASCII file name by  file input?
 (Japanese content has no issue.)

Masashi Nakane

**Comment by suyograo** [comment]
Fixed in 1.5.1. https://github.com/elastic/logstash/blob/master/CHANGELOG.md#151-june-16-2015
