### ISSUE TITLE
Couldn't start TCP server error

### ISSUE THREAD

**Issue by usmanajmal** [elastic/logstash#2176]
Trying to view syslogs in elasticsearch with the help of logstash and kibana3. Followed mostly https://www.digitalocean.com/community/tutorials/how-to-use-logstash-and-kibana-to-centralize-logs-on-centos-6 fo this purpose. But Kibana interface doesn't show anything. From /var/log/logstash/logstash.log, I can see following error:
```
{:timestamp=>"2014-12-04T14:06:02.771000-0800", :message=>"Could not start TCP server: Address in use", :host=>"0.0.0.0", :port=>5000, :level=>:error}
{:timestamp=>"2014-12-04T14:06:02.775000-0800", :message=>"+---------------------------------------------------------+\n| An unexpected error occurred. This is probably a bug.   |\n| You can find help with this problem in a few places:    |\n|                                                         |\n| * chat: #logstash IRC channel on freenode irc.          |\n|     IRC via the web: http://goo.gl/TI4Ro                |\n| * email: logstash-users@googlegroups.com                |\n| * bug system: https://logstash.jira.com/                |\n|                                                         |\n+---------------------------------------------------------+\nThe error reported is: \n  Address already in use - bind - Address already in use"}
log4j, 
```

I suppose the host: 0.0.0.0 isn't right. As I am running elasticsearch, logstash, logstash-forwarder and kibana3 all on same machine, I think I should set host to 127.0.0.1?

I tried setting host in /etc/logstash/conf.d/01-lumberjack-input.conf to following but it didn't solve the problem:
````
 input {
       lumberjack {
           host => localhost
           port => 5000
           type => "logs"
           ssl_certificate => "/etc/pki/tls/certs/logstash-forwarder.crt"
           ssl_key => "/etc/pki/tls/private/logstash-forwarder.key"
       }
   }
```

Moreover, chrome's developer console shows following when I visit: http://localhost/kibana3/index.html#/dashboard/file/guided.json
```
TypeError: Cannot read property 'terms' of undefined
    at g (http://localhost/kibana3/app/panels/terms/module.js:4:2584)
    at h (http://localhost/kibana3/app/panels/terms/module.js:4:3065)
    at http://localhost/kibana3/app/panels/terms/module.js:4:4260
    at Object.f.$emit (http://localhost/kibana3/app/app.js:9:7547)
    at http://localhost/kibana3/app/panels/terms/module.js:4:1934
    at i (http://localhost/kibana3/app/app.js:9:458)
    at http://localhost/kibana3/app/app.js:9:1014
    at Object.f.$eval (http://localhost/kibana3/app/app.js:9:6963)
    at Object.f.$digest (http://localhost/kibana3/app/app.js:9:5755)
    at Object.f.$apply (http://localhost/kibana3/app/app.js:9:7111) ```

**Comment by jordansissel** [comment]
@usmanajmal Sorry for the delays in attending to your issue! This sounds like a configuration problem, so it should be fixable! If you are still having problems, I recommend you ask this on https://discuss.elastic.co/ (our new discussion forum for user help!)
