### ISSUE TITLE
Error setting up dev environment

### ISSUE THREAD

**Issue by jordan-wright** [elastic/logstash#2204]
Trying to get development up and running with Ruby v.1.9.3:

```
root@elk:~/logstash-master# rake bootstrap --trace
rake aborted!
can't convert Hash into String
/usr/lib/ruby/vendor_ruby/rake/file_list.rb:399:in `dirname'
/usr/lib/ruby/vendor_ruby/rake/file_list.rb:399:in `each_dir_parent'
/usr/lib/ruby/vendor_ruby/rake/dsl_definition.rb:66:in `directory'
/root/logstash-master/rakelib/fetch.rake:5:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load'
/usr/lib/ruby/vendor_ruby/rake/rake_module.rb:25:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/default_loader.rb:6:in `load'
/usr/lib/ruby/vendor_ruby/rake/application.rb:569:in `load_imports'
/usr/lib/ruby/vendor_ruby/rake/application.rb:508:in `raw_load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:82:in `block in load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:81:in `load_rakefile'
/usr/lib/ruby/vendor_ruby/rake/application.rb:65:in `block in run'
/usr/lib/ruby/vendor_ruby/rake/application.rb:133:in `standard_exception_handling'
/usr/lib/ruby/vendor_ruby/rake/application.rb:63:in `run'
/usr/bin/rake:27:in `<main>'
```

I'll keep poking around, but I thought I'd get the experts involved early :smile:

**Comment by colinsurprenant** [comment]
for the record, this is because `rake` needs to be updated. I just hit this and was a little confused and realized I had a fresh rbenv install of MRI 1.9.3 with a very old rake version.
