### ISSUE TITLE
Exception in filterworker

### ISSUE THREAD

**Issue by fervid** [elastic/logstash#2404]
Hello, I faced with a problem.

```
FLOAT    (?: [-+]? \d* \. \d+ | \.? \d+)  (?: e \+ \d+)?

/opt/logstash-1.4.2/bin/logstash -e 'input {stdin {}} filter{ grok { match => [ "message", "(?x) %{FLOAT:a:float} \s+ %{FLOAT:b:float}" ] } if [a] ==6002010.0{ ruby { code => "event['s'] = event['a'] + event['b']" }} } output { stdout { codec => rubydebug }}'
Using milestone 1 filter plugin 'ruby'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
5.5  7.7
{
       "message" => "5.5 7.7",
      "@version" => "1",
    "@timestamp" => "2015-01-23T07:28:32.020Z",
          "host" => "alerts-db",
             "a" => 5.5,
             "b" => 7.7
}
6002010.0  7.7
Exception in filterworker {"exception"=>#<NameError: undefined local variable or method `s' for <LogStash::Filters::Ruby code=>"event[s] = event[a] + event[b]">:LogStash::Filters::Ruby>, "backtrace"=>["(ruby filter code):1:in `register'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash-1.4.2/lib/logstash/filters/ruby.rb:38:in `filter'", "(eval):41:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash-1.4.2/lib/logstash/pipeline.rb:262:in `filter'", "/opt/logstash-1.4.2/lib/logstash/pipeline.rb:203:in `filterworker'", "/opt/logstash-1.4.2/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}
```

**Comment by fervid** [comment]
Also:
```
/opt/logstash-1.4.2/bin/logstash -e 'input {stdin {}} filter{ grok { match => [ "message", "(?x) %{FLOAT:a:float} \s %{FLOAT:b:float}" ] } mutate { add_field => { "s" => 0 } remove_field => ["@version"] } ruby { code => "event.to_hash[:f]=0; event.to_hash[:f]=event.to_hash[:f]+10"}} output { stdout { codec => rubydebug }}'
Using milestone 1 filter plugin 'ruby'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
0 0
{
       "message" => "0 0",
    "@timestamp" => "2015-01-29T08:42:15.373Z",
          "host" => "alerts-db",
             "a" => 0.0,
             "b" => 0.0,
             "s" => "0",
              :f => 10
}
^CInterrupt received. Shutting down the pipeline. {:level=>:warn}

 
 
/opt/logstash-1.4.2/bin/logstash -e 'input {stdin {}} filter{ grok { match => [ "message", "(?x) %{FLOAT:a:float} \s %{FLOAT:b:float}" ] } mutate { add_field => { "s" => 0 } remove_field => ["@version"] } ruby { code => "event.to_hash[:f]=0; event.to_hash[:f]=event.to_hash['a']+10"}} output { stdout { codec => rubydebug }}'
Using milestone 1 filter plugin 'ruby'. This plugin should work, but would benefit from use by folks like you. Please let us know if you find bugs or have suggestions on how to improve this plugin.  For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}
0 0
Exception in filterworker {"exception"=>#<NameError: undefined local variable or method `a' for #<LogStash::Filters::Ruby:0x6e02f224>>, "backtrace"=>["(ruby filter code):1:in `register'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash-1.4.2/lib/logstash/filters/ruby.rb:38:in `filter'", "(eval):57:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash-1.4.2/lib/logstash/pipeline.rb:262:in `filter'", "/opt/logstash-1.4.2/lib/logstash/pipeline.rb:203:in `filterworker'", "/opt/logstash-1.4.2/lib/logstash/pipeline.rb:143:in `start_filters'"], :level=>:error}
```

**Comment by jordansissel** [comment]
Is this still an issue? If so, the best place to ask about it is probably on the Logstash forums at https://discuss.elastic.co/.
