### ISSUE TITLE
Logstash is crashed every day

### ISSUE THREAD

**Issue by MiteshShah** [elastic/logstash#2520]
I'd setup standalone ELK on single server.

But each day logstash is crashed with following msg

```log
log4j, [2015-02-05T10:09:52.067]  WARN: org.elasticsearch.discovery.zen: [logstash-example.com-2693-2010] master_left and no other node elected to become master, current nodes: {[logstash-example.com-2693-2010][VXc55PvmRG-hFYsUrCxmLg][example.com][inet[/10.40.165.135:9300]]{client=true, data=false},}
log4j, [2015-02-05T10:09:55.855]  WARN: org.elasticsearch.discovery.zen.ping.unicast: [logstash-example.com-2693-2010] failed to send ping to [[#zen_unicast_2#][example.com][inet[localhost/127.0.0.1:9301]]]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[localhost/127.0.0.1:9301]][discovery/zen/unicast] request_id [76109] timed out after [3751ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:356)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
log4j, [2015-02-05T10:10:00.350]  WARN: org.elasticsearch.discovery.zen.ping.unicast: [logstash-example.com-2693-2010] failed to send ping to [[#zen_unicast_2#][example.com][inet[localhost/127.0.0.1:9301]]]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[localhost/127.0.0.1:9301]][discovery/zen/unicast] request_id [76115] timed out after [3750ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:356)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
log4j, [2015-02-05T10:10:34.102]  WARN: org.elasticsearch.discovery.zen.ping.unicast: [logstash-example.com-2693-2010] failed to send ping to [[#zen_unicast_2#][example.com][inet[localhost/127.0.0.1:9301]]]
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[localhost/127.0.0.1:9301]][discovery/zen/unicast] request_id [76150] timed out after [3750ms]
        at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:356)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by markwalkom** [comment]
What version, what is your config?

**Comment by MiteshShah** [comment]
Version:

```
logstash.noarch                            1.4.2-1_2c0f5a1              installed
logstash-contrib.noarch                    1.4.2-1_efd53ef              logstash-1.4
elasticsearch.noarch                       1.3.2-1                      installed
```
Config:
```
cat /etc/logstash/conf.d/logstash.conf 
input {
  udp {
    port => 7030
    codec => json_lines
  }
  tcp {
    port => 7031
    codec => json_lines
  }
}

output {
    elasticsearch {
      host => localhost
  }
  stdout { codec => rubydebug }
}
```

Let me know anything else is required from my end

**Comment by markwalkom** [comment]
Why are you using stdout and elasticsearch? It seems like a bit of overkill.

Are you monitoring Elasticsearch as well, can you check the logs for it at the same time you see that problem in the logs for Logstash?

**Comment by MiteshShah** [comment]
@markwalkom 

When i face the problem on logstash i checked elasticserach status:

```
{
   "cluster_name": "elasticsearch",
   "status": "green",
   "timed_out": false,
   "number_of_nodes": 2,
   "number_of_data_nodes": 1,
   "active_primary_shards": 263,
   "active_shards": 263,
   "relocating_shards": 0,
   "initializing_shards": 0,
   "unassigned_shards": 0
}
````

**Comment by markwalkom** [comment]
You should look in the actual ES logs.

Basically the error is saying the LS cannot talk to ES. Try using the http protocol and see if you get the same problems?

**Comment by MiteshShah** [comment]
@markwalkom Last few days same issue we are facing and elasticsearch works fine and no error on elasticsearch logs.

Also after restart logstash i can see logstash data on kibana.
So i don't think there is some issue with elasticsearch.

> Basically the error is saying the LS cannot talk to ES.
I guess there is some dedault timeout for LS to contact ES and is LS is fails to connect ES in that timeout then its crashed (Just my guess still not sure)

Right now i've to restart logstash to make its working again and we dont touch ES from last few weeks   and ES works fine for me without any issue.

**Comment by MiteshShah** [comment]
@markwalkom I'd disable stdout and restart LS

```bash
cat /etc/logstash/conf.d/logstash.conf 
input {
  udp {
    port => 7030
    codec => json_lines
  }
  tcp {
    port => 7031
    codec => json_lines
  }
}

output {
    elasticsearch {
      host => localhost
  }
  #stdout { codec => rubydebug }
}
```

Now LS through following errors:
```
{:timestamp=>"2015-02-09T22:57:19.343000-0600", :message=>"Using milestone 2 input plugin 'udp'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones", :level=>:warn}
{:timestamp=>"2015-02-09T22:57:19.373000-0600", :message=>"Using milestone 2 input plugin 'tcp'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2-modified/plugin-milestones", :level=>:warn}
{:timestamp=>"2015-02-09T22:57:28.885000-0600", :message=>"Exception in inputworker", "exception"=>#<TypeError: can't convert nil into String>, "backtrace"=>["org/jruby/RubyArray.java:1892:in `join'", "org/jruby/RubyArray.java:1898:in `join'", "/opt/logstash/lib/logstash/util/buftok.rb:87:in `extract'", "/opt/logstash/lib/logstash/codecs/line.rb:36:in `decode'", "/opt/logstash/lib/logstash/codecs/json_lines.rb:36:in `decode'", "/opt/logstash/lib/logstash/inputs/udp.rb:100:in `inputworker'", "/opt/logstash/lib/logstash/inputs/udp.rb:75:in `udp_listener'"], :level=>:error}


==> logstash/logstash.log <==
log4j, [2015-02-09T23:11:06.062]  WARN: org.elasticsearch.discovery: [logstash-srv008.jutera.com-5761-2010] waited for 30s and no initial state was set by the discovery

==> logstash/logstash.err <==
Exception in thread ">output" org.elasticsearch.discovery.MasterNotDiscoveredException: waited for [30s]
	at org.elasticsearch.action.support.master.TransportMasterNodeOperationAction$3.onTimeout(org/elasticsearch/action/support/master/TransportMasterNodeOperationAction.java:180)
	at org.elasticsearch.cluster.service.InternalClusterService$NotifyTimeout.run(org/elasticsearch/cluster/service/InternalClusterService.java:492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(java/lang/Thread.java:745)

```

**Comment by MiteshShah** [comment]
@markwalkom 
Also see following error on ES

```
[2015-02-09 23:15:21,919][DEBUG][action.search.type       ] [Jack-in-the-Box] All shards failed for phase: [query]
[2015-02-09 23:15:21,919][DEBUG][action.search.type       ] [Jack-in-the-Box] All shards failed for phase: [query_fetch]
[2015-02-09 23:15:21,919][DEBUG][action.search.type       ] [Jack-in-the-Box] All shards failed for phase: [query_fetch]
````

**Comment by ph** [comment]
The LS error log show an error with the `UDP input`, the decoder is trying to decode an empty string.
What is the application sending events to logstash?

**Comment by MiteshShah** [comment]
@ph I'd monitor logstash.stdout for more then 1 week and nothing found (No special character)

Instead of that i'd found LS crashed every day at 5:30 IST 
First i think that was due to logrotate so i was change log rotation policy from daily to monthly but still LS crashed every day at 5:30 IST

![ls 1](https://cloud.githubusercontent.com/assets/1223371/6483880/0813a27a-c29c-11e4-89af-635caee823da.png)
![ls 2](https://cloud.githubusercontent.com/assets/1223371/6483881/08313c5e-c29c-11e4-9d6e-efc1a20308e8.png)

Also I've notice one wired thing notice

LS Config:
```
cat /etc/logstash/conf.d/logstash.conf 
input {
  udp {
    port => 7030
    codec => json_lines
  }
  tcp {
    port => 7031
    codec => json_lines
  }
}

output {
    elasticsearch {
      host => localhost
      protocol => transport

  }
  stdout { codec => rubydebug }
}
```

If i'd restart LS without commenting out  `protocol => transport`  line in LS config then in  logstash.stdout file i can see data but no data is show in Kibana LS Dashboard;

So i've to first comment out that protocol line and once i see data in kibana i've to un-comment protocol line and have to restart LS again :(

**Comment by MiteshShah** [comment]
One  more thing notice today as Kibana LS dashboard doesn't display any activity after 5:30 AM IST but in logstash.stdout file i can see data

**Comment by MiteshShah** [comment]
Last Kibana Log

```
{
  "_index": "logstash-2015.03.04",
  "_type": "logs",
  "_id": "AUvnO2v1CBNQWnZl5wxb",
  "_score": null,
  "_source": {
    "@timestamp": "2015-03-04T23:59:59.993Z",
    "@source": "example.com",
    "@fields": {
      "channel": "prod",
      "level": 300,
      "ctxt_ip": "10.10.10.10"
    },
    "@message": "Lookup failed for IP address",
    "@tags": [
      "prod"
    ],
    "@type": "example-api-v2",
    "@version": "1",
    "host": "20.20.10.10"
  },
  "sort": [
    1425513599993,
    1425513599993
  ]
}
```
If you notice timestemps 2015-03-04T23:59:59.993Z and index logstash-2015.03.04 i guess LS is fail to create new index

**Comment by MiteshShah** [comment]
I'd found the solution,

As @rashidkpc  suggested (#3070 (comment)) i'd change LS protocol from node to transport and http which cause this issue and LS is not able to create new index.

I'd change LS protocol back to node and kibana3 and kibana4 both are working at least today no crash and we get continue data

**Comment by spawnazzo** [comment]
Hi guys, 
I do have the same problem but I ship logs to elasticsearch like 
```
input {
 redis {
   host => "127.0.0.1"
   data_type => "list"
   key => "logstash_core"
 }
}
output{

   if [type] == "core"
   {
     elasticsearch {
       host => "127.0.0.1"
       cluster => "clustername"
       index => "core-%{+YYYY.MM.dd}"
       node_name => "core-logs-indexer"
     }

    # stdout { codec => rubydebug }

   }
}
```
should i change it withi something like 

```
input {
 redis {
   host => "127.0.0.1"
   protocol => "http"
   data_type => "list"
   key => "logstash_core"
 }
}
output{

   if [type] == "core"
   {
     elasticsearch {
       host => "127.0.0.1"
       protocol=> "http"
       cluster => "clustername"
       index => "core-%{+YYYY.MM.dd}"
       node_name => "core-logs-indexer"
     }
   }
}
```
or am i getting it wrong? thanks

**Comment by suyograo** [comment]
Can you please move this to https://discuss.elastic.co/c/logstash
