### ISSUE TITLE
Logstash 1.4.2 OOM when ES down

### ISSUE THREAD

**Issue by nellicus** [elastic/logstash#2593]
I have run this on 2 nodes Elasticsearch 1.4.2 cluster

Logstash 1.4.2 config as below:

```
input {

    file {
        path => "/tmp/hugefile"
        sincedb_path => "/dev/null" 
        start_position => "beginning"
    }
    file {
                path => "/tmp/hugefile2"
                sincedb_path => "/dev/null"
        start_position => "beginning"
        }
    file {
                path => "/tmp/hugefile3"
                sincedb_path => "/dev/null"
        start_position => "beginning"
        }
    file {
                path => "/tmp/hugefile4"
                sincedb_path => "/dev/null"
                start_position => "beginning"
        }
    file {
                path => "/tmp/hugefile5"
                sincedb_path => "/dev/null"
                start_position => "beginning"
        }
    file {
                path => "/tmp/hugefile6"
                sincedb_path => "/dev/null"
                start_position => "beginning"
        }
    file {
                path => "/tmp/hugefile7"
                sincedb_path => "/dev/null"
                start_position => "beginning"
        }
    file {
                path => "/tmp/hugefile8"
                sincedb_path => "/dev/null"
                start_position => "beginning"
        }
    file {
                path => "/tmp/hugefile9"
                sincedb_path => "/dev/null"
                start_position => "beginning"
        }
    file {
                path => "/tmp/hugefile10"
                sincedb_path => "/dev/null"
                start_position => "beginning"
        }

}

filter {

}

output {

    elasticsearch {
        cluster => "tony_prod"
        protocol => "transport"
        workers => 16
        host => "192.168.0.101"
        port => "9302"
        index => "test"

    }
     stdout { codec => rubydebug }
}
```

where source files are

```
 $ du -hs /tmp/hugefile*
4,7G    /tmp/hugefile
4,7G    /tmp/hugefile10
4,7G    /tmp/hugefile2
4,7G    /tmp/hugefile3
4,7G    /tmp/hugefile4
4,7G    /tmp/hugefile5
4,7G    /tmp/hugefile6
4,7G    /tmp/hugefile7
4,7G    /tmp/hugefile8
4,7G    /tmp/hugefile9
```

1) Elasticsearch stopped responding (was yellow)
2) Logstash threads running out of memory and crashing

this is all running on same beefy host (32GB ram 8 cores SSD)

in Logstash stdout

```
Exception in thread "elasticsearch[logstash-w530-12453-4130][transport_client_worker][T#6]" java.lang.OutOfMemoryError: Java heap space
Exception in thread "elasticsearch[logstash-w530-12453-4142][transport_client_worker][T#6]" java.lang.OutOfMemoryError: Java heap space
Exception in thread "elasticsearch[logstash-w530-12453-4150][transport_client_worker][T#6]" java.lang.OutOfMemoryError: Java heap space
Exception in thread "elasticsearch[logstash-w530-12453-4192][transport_client_worker][T#6]" java.lang.OutOfMemoryError: Java heap space
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CException in thread "elasticsearch[logstash-w530-12453-4256][transport_client_worker][T#16]" java.lang.OutOfMemoryError: Java heap space
Error: Your application used more memory than the safety cap of 500M.
Specify -J-Xmx####m to increase it (#### = cap size in MB).
Specify -w for full OutOfMemoryError stack trace
Exception in thread "elasticsearch[logstash-w530-12453-4164][transport_client_boss][T#1]" java.lang.OutOfMemoryError: Java heap space
Exception in thread "elasticsearch[logstash-w530-12453-4210][transport_client_boss][T#1]{New I/O boss #233}" java.lang.OutOfMemoryError: Java heap space

in logstash log with debug

st"=>"w530", "path"=>"/tmp/hugefile10"}], ["index", {:_id=>nil, :_index=>"test", :_type=>"logs"}, {"message"=>"[628396.122783] [26976]     0 26976     3819       78      12        0             0 upstart-file-br", "@version"=>"1", "@timestamp"=>"2015-02-11T15:05:00.788Z", "host"=>"w530", "path"=>"/tmp/hugefile10"}], ["index", {:_id=>nil, :_index=>"test", :_type=>"logs"}, {"message"=>"[628396.122787] [ 1430]     0  1430    68174      587     130        0             0 smbd", "@version"=>"1", "@timestamp"=>"2015-02-11T15:05:00.789Z", "host"=>"w530", "path"=>"/tmp/hugefile10"}], ["index", {:_id=>nil, :_index=>"test", :_type=>"logs"}, {"message"=>"[628396.388282] [12603]  1000 12603    91470     2489     145        0             0 chrome", "@version"=>"1", "@timestamp"=>"2015-02-11T15:05:23.761Z", "host"=>"w530", "path"=>"/tmp/hugefile"}]]}, :batch_timeout=>1, :force=>true, :final=>nil, :level=>:debug, :file=>"stud/buffer.rb", :line=>"207"}log4j, [2015-02-11T16:06:50.793] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4190] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:50.795] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4142] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:50.795] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4072] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:50.795] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4232] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:50.796] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4150] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:50.797] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4154] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:52.767] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4214] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:52.768] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4164] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:53.411] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4252] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:53.412] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4020] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:06:53.412] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4148] connected to node [[#transport#-1][w530][inet[/192.168.0.101:9302]]]

log4j, [2015-02-11T16:07:24.213]  WARN: org.elasticsearch.netty.channel.socket.nio.AbstractNioSelector: Unexpected exception in the selector loop.
log4j, [2015-02-11T16:07:30.916]  WARN: org.elasticsearch.netty.channel.socket.nio.AbstractNioSelector: Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: Java heap space
log4j, [2015-02-11T16:07:32.746]  INFO: org.elasticsearch.client.transport: [logstash-w530-12453-4020] failed to get node info for [#transport#-1][w530][inet[/192.168.0.101:9302]], disconnecting...
org.elasticsearch.transport.RemoteTransportException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse]
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse]
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:148)
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:125)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
log4j, [2015-02-11T16:07:33.680]  WARN: org.elasticsearch.transport.netty: [logstash-w530-12453-4154] Message not fully read (response) for [24] handler future(org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler$1@2371fdd8), error [false], resetting
log4j, [2015-02-11T16:07:34.174] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4020] disconnected from [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:07:32.746]  WARN: org.elasticsearch.transport.netty: [logstash-w530-12453-4020] Message not fully read (response) for [22] handler future(org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler$1@542e137), error [false], resetting
log4j, [2015-02-11T16:07:35.131]  INFO: org.elasticsearch.client.transport: [logstash-w530-12453-4154] failed to get node info for [#transport#-1][w530][inet[/192.168.0.101:9302]], disconnecting...
org.elasticsearch.transport.RemoteTransportException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse]
Caused by: org.elasticsearch.transport.TransportSerializationException: Failed to deserialize response of type [org.elasticsearch.action.admin.cluster.node.info.NodesInfoResponse]
    at org.elasticsearch.transport.netty.MessageChannelHandler.handleResponse(MessageChannelHandler.java:148)
    at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:125)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.OutOfMemoryError: Java heap space
log4j, [2015-02-11T16:07:35.132] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4154] disconnected from [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:07:35.134]  WARN: org.elasticsearch.netty.channel.socket.nio.AbstractNioSelector: Unexpected exception in the selector loop.
java.lang.OutOfMemoryError: Java heap space
log4j, [2015-02-11T16:07:35.136]  WARN: org.elasticsearch.transport.netty: [logstash-w530-12453-4150] exception caught on transport layer [[id: 0xf821dd6c, /192.168.0.101:56764 => /192.168.0.101:9302]], closing connection
java.lang.OutOfMemoryError: Java heap space
log4j, [2015-02-11T16:07:35.137] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4150] disconnected from [[#transport#-1][w530][inet[/192.168.0.101:9302]]], channel closed event
log4j, [2015-02-11T16:07:35.138]  WARN: org.elasticsearch.transport.netty: [logstash-w530-12453-4192] exception caught on transport layer [[id: 0x47c4bf9d, /192.168.0.101:56741 => /192.168.0.101:9302]], closing connection
java.lang.OutOfMemoryError: Java heap space
log4j, [2015-02-11T16:07:35.138] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4192] disconnected from [[#transport#-1][w530][inet[/192.168.0.101:9302]]], channel closed event

log4j, [2015-02-11T16:07:35.621]  INFO: org.elasticsearch.client.transport: [logstash-w530-12453-4256] failed to get node info for [#transport#-1][w530][inet[/192.168.0.101:9302]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/192.168.0.101:9302]][cluster/nodes/info] request_id [23] timed out after [34854ms]
    at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:356)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
log4j, [2015-02-11T16:07:35.622] DEBUG: org.elasticsearch.transport.netty: [logstash-w530-12453-4256] disconnected from [[#transport#-1][w530][inet[/192.168.0.101:9302]]]
log4j, [2015-02-11T16:07:35.622]  INFO: org.elasticsearch.client.transport: [logstash-w530-12453-4150] failed to get node info for [#transport#-1][w530][inet[/192.168.0.101:9302]], disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][inet[/192.168.0.101:9302]][cluster/nodes/info] request_id [24] timed out after [34450ms]
    at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:356)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
log4j, [2015-02-11T16:07:35.623]  WARN: org.elasticsearch.transport.netty: [logstash-w530-12453-4150] exception caught on transport layer [[id: 0xf821dd6c, /192.168.0.101:56764 :> /192.168.0.101:9302]], closing connection
java.io.StreamCorruptedException: invalid internal transport message format
    at org.elasticsearch.transport.netty.SizeHeaderFrameDecoder.decode(SizeHeaderFrameDecoder.java:46)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
    at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
    at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318)
    at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

as far as I understand this shouldn't happen?

**Comment by abdalians** [comment]
nellicus did you get anywhere with this?

**Comment by suyograo** [comment]
Closing this, please reopen if this is still and issue with later releases
