### ISSUE TITLE
Test not having a deterministic behaviour

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#2706]
There are some test, like in the input file or input gelf that fail randomly because the test conditions are not deterministic.

Example from input-gelf:

```
:elasticsearch=>true, :elasticsearch_secure=>true, :broken=>true, :export_cypher=>true, :integration=>true, :windows=>true}
F

Failures:

  1) inputs/gelf reads chunked gelf messages  inputs
     Failure/Error: block.call(pipeline, queue)
     Insist::Failure:
       Expected 0 > 0
     # ./spec/inputs/gelf_spec.rb:46:in `(root)'
     # ./spec/inputs/gelf_spec.rb:34:in `(root)'

Finished in 1.29 seconds
1 example, 1 failure
```

**Comment by suyograo** [comment]
Fixed by https://github.com/logstash-plugins/logstash-input-gelf/pull/9
