### ISSUE TITLE
Jenkins: Regression tests fail periodically while pushing packages to S3

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#2774]
```
Publish artifacts to S3 Bucket bucket=build-eu.elasticsearch.org/logstash/1.5/nightly/JDK7, file=logstash_1.5.0.rc1.1-1_all.deb region=EU_WEST_1, upload from slave=false managed=false
ERROR: Failed to upload files
java.io.IOException: put Destination [bucketName=build-eu.elasticsearch.org, objectName=logstash/1.5/nightly/JDK7/logstash_1.5.0.rc1.1-1_all.deb]: com.amazonaws.AmazonClientException: Encountered an exception and couldn't reset the stream to retry
at hudson.plugins.s3.S3Profile.upload(S3Profile.java:140)
at hudson.plugins.s3.S3BucketPublisher.perform(S3BucketPublisher.java:174)
at hudson.tasks.BuildStepMonitor$2.perform(BuildStepMonitor.java:32)
at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:734)
at hudson.model.Build$BuildExecution.post2(Build.java:183)
at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:683)
at hudson.model.Run.execute(Run.java:1784)
```

See http://build-eu-00.elasticsearch.org/view/LS%201.5/job/logstash_regression_15/jdk=JDK7,label=metal-pool/206/

**Comment by suyograo** [comment]
this is probably a network failure, we should add a retry mechanism
