### ISSUE TITLE
IOError: invalid null character in command

### ISSUE THREAD

**Issue by filenox** [elastic/logstash#2857]
I'm trying to push syslog into Zabbix, this works fine when I want to push the hostname but I'm getting an IOError when the "send_field" field equals [message]. Manual input via zabbix_sender works fine.

************************************ 
                 CONF-FILE
************************************
input {
          tcp {
                 port => 514
                 type => syslog
                }

          udp {
                port => 514
                type => syslog
                }
}

filter {
grep {
     add_field => ["zabbix_host", "FE-001","zabbix_item", "logstash","send_field", [message]]
  }
}

output {
  stdout { codec => rubydebug }
  zabbix {
    host => "localhost"
    port => "10051"
    zabbix_sender => "/usr/bin/zabbix_sender"
    }
}

************************************ 
                 OUTPUT
************************************

output received {:event=>{"message"=>"<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "@version"=>"1", "@timestamp"=>"2015-03-19T09:04:41.845Z", "type"=>"syslog", "host"=>"192.168.253.101", "zabbix_host"=>"FE-001", "zabbix_item"=>"logstash", "send_field"=>"message"}, :level=>:debug, :file=>"(eval)", :line=>"40"}
{
        "message" => "<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000",
       "@version" => "1",
     "@timestamp" => "2015-03-19T09:04:41.845Z",
           "type" => "syslog",
           "host" => "192.168.253.101",
    "zabbix_host" => "FE-001",
    "zabbix_item" => "logstash",
     "send_field" => "message"
}
Running zabbix command {:command=>"/usr/bin/zabbix_sender -z localhost -p 10051 -s FE-001 -k logstash -o <134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000 -v", :level=>:debug, :file=>"logstash/outputs/zabbix.rb", :line=>"116"}
Skipping zabbix output; error calling zabbix_sender {:command=>["/usr/bin/zabbix_sender", "-z", "localhost", "-p", 10051, "-s", "FE-001", "-k", "logstash", "-o", "<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "-v"], :missed_event=>#<LogStash::Event:0x5e9c3ce7 @accessors=#<LogStash::Util::Accessors:0x63629237 @store={"message"=>"<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "@version"=>"1", "@timestamp"=>"2015-03-19T09:04:41.845Z", "type"=>"syslog", "host"=>"192.168.253.101", "zabbix_host"=>"FE-001", "zabbix_item"=>"logstash", "send_field"=>"message"}, @lut={"type"=>[{"message"=>"<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "@version"=>"1", "@timestamp"=>"2015-03-19T09:04:41.845Z", "type"=>"syslog", "host"=>"192.168.253.101", "zabbix_host"=>"FE-001", "zabbix_item"=>"logstash", "send_field"=>"message"}, "type"], "host"=>[{"message"=>"<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "@version"=>"1", "@timestamp"=>"2015-03-19T09:04:41.845Z", "type"=>"syslog", "host"=>"192.168.253.101", "zabbix_host"=>"FE-001", "zabbix_item"=>"logstash", "send_field"=>"message"}, "host"], "zabbix_host"=>[{"message"=>"<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "@version"=>"1", "@timestamp"=>"2015-03-19T09:04:41.845Z", "type"=>"syslog", "host"=>"192.168.253.101", "zabbix_host"=>"FE-001", "zabbix_item"=>"logstash", "send_field"=>"message"}, "zabbix_host"], "zabbix_item"=>[{"message"=>"<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "@version"=>"1", "@timestamp"=>"2015-03-19T09:04:41.845Z", "type"=>"syslog", "host"=>"192.168.253.101", "zabbix_host"=>"FE-001", "zabbix_item"=>"logstash", "send_field"=>"message"}, "zabbix_item"], "send_field"=>[{"message"=>"<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "@version"=>"1", "@timestamp"=>"2015-03-19T09:04:41.845Z", "type"=>"syslog", "host"=>"192.168.253.101", "zabbix_host"=>"FE-001", "zabbix_item"=>"logstash", "send_field"=>"message"}, "send_field"], "message"=>[{"message"=>"<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "@version"=>"1", "@timestamp"=>"2015-03-19T09:04:41.845Z", "type"=>"syslog", "host"=>"192.168.253.101", "zabbix_host"=>"FE-001", "zabbix_item"=>"logstash", "send_field"=>"message"}, "message"]}>, @data={"message"=>"<134>Mar 19 10:04:42 FE-001 SESSION(71) Data: [SES] Session 6, user \"readonly\"\n\u0000", "@version"=>"1", "@timestamp"=>"2015-03-19T09:04:41.845Z", "type"=>"syslog", "host"=>"192.168.253.101", "zabbix_host"=>"FE-001", "zabbix_item"=>"logstash", "send_field"=>"message"}, @cancelled=false>, :exception=>#<IOError: invalid null character in command>, :backtrace=>["org/jruby/RubyIO.java:4338:in `popen'", "/root/logstash-1.4.2/lib/logstash/outputs/zabbix.rb:119:in `receive'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:977:in `each_with_index'", "/root/logstash-1.4.2/lib/logstash/outputs/zabbix.rb:107:in `receive'", "/root/logstash-1.4.2/lib/logstash/outputs/base.rb:86:in `handle'", "(eval):42:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/root/logstash-1.4.2/lib/logstash/pipeline.rb:266:in `output'", "/root/logstash-1.4.2/lib/logstash/pipeline.rb:225:in `outputworker'", "/root/logstash-1.4.2/lib/logstash/pipeline.rb:152:in `start_outputs'"], :level=>:warn, :file=>"logstash/outputs/zabbix.rb", :line=>"134"}
Error during closing zabbix_sender subprocess {:exception=>#<NoMethodError: undefined method `closed?' for nil:NilClass>, :backtrace=>["/root/logstash-1.4.2/lib/logstash/outputs/zabbix.rb:139:in `receive'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:977:in `each_with_index'", "/root/logstash-1.4.2/lib/logstash/outputs/zabbix.rb:107:in `receive'", "/root/logstash-1.4.2/lib/logstash/outputs/base.rb:86:in `handle'", "(eval):42:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/root/logstash-1.4.2/lib/logstash/pipeline.rb:266:in `output'", "/root/logstash-1.4.2/lib/logstash/pipeline.rb:225:in `outputworker'", "/root/logstash-1.4.2/lib/logstash/pipeline.rb:152:in `start_outputs'"], :level=>:warn, :file=>"logstash/outputs/zabbix.rb", :line=>"141"}
^CInterrupt received. Shutting down the pipeline. {:level=>:warn, :file=>"logstash/agent.rb", :line=>"119"}

**Comment by filenox** [comment]
>mutate {strip => ["message"]} 
solved the issue.
