### ISSUE TITLE
how enable the XPath 2.0 support in XML filter?

### ISSUE THREAD

**Issue by azhiltsov** [elastic/logstash#2874]
I am trying to parse XML like this 
(http://stackoverflow.com/questions/21996965/concatenate-multiple-node-values-in-xpath)
```xml
<element1>
    <element2>
        <element3>    
            <element4>Hello</element4>
            <element5>World</element5>
        </element3>
        <element3>    
            <element4>Hello2</element4>
            <element5>World2</element5>
        </element3>
        <element3>    
            <element4>Hello3</element4>
            <element5>World3</element5>
        </element3>
    </element2>
</element1>
```
with the XML filter and the next XPath code:
```
 xml {
  source => "message"
  target => "event"
  store_xml => false
  xpath => [ "string-join(//element3/(concat(element4/text(), '.', element5/text())), "&#10;")", "events" ]
 }
```
Unfortunately it fails, even if I use simple XPath 2.0 code 
```
string-join(('a', 'b'), 's')
```
```
Exception in filterworker {"exception"=>#<Nokogiri::XML::XPath::SyntaxError: string-join(('a', 'b'), 's')>, "backtrace"=>["nokogiri/XmlXpathContext.java:169:in `evaluate'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/searchable.rb:165:in `xpath'", "org/jruby/RubyArray.java:2412:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/searchable.rb:156:in `xpath'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-xml-0.1.4/lib/logstash/filters/xml.rb:106:in `filter'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-xml-0.1.4/lib/logstash/filters/xml.rb:105:in `filter'", "(eval):467:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):463:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):460:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):398:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:275:in `filter'", "/opt/logstash/lib/logstash/pipeline.rb:209:in `filterworker'", "/opt/logstash/lib/logstash/pipeline.rb:153:in `start_filters'"], :level=>:error}
```
It looks like it do not support XPath 2.0.
Is there any chance to enable it?

**Comment by jordansissel** [comment]
I don't know. I don't use this string-join function. The library we use is nokogiri, so maybe ask them? https://github.com/sparklemotion/nokogiri/issues
