### ISSUE TITLE
LS 1.5 multiline exception

### ISSUE THREAD

**Issue by cmahlig** [elastic/logstash#2892]
Hello !

I don't know if this is a bug, but i find no solution for this problem:

I tried to use the multiline function 

filter{
    multiline {
      pattern     => "%{TIMESTAMP_ISO8601}"
      what        => "previous"
      add_tag   => ["exception"]
      negate      => "true"
    }
 ....
}

and get the following exception

Exception in filterworker {"exception"=>#<ArgumentError: wrong number of arguments (1 for 3)>, "backtrace"=>["/opt/logstash/lib/logstash/event.rb:286:in `to_hash_with_metadata'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.5/lib/logstash/filters/multiline.rb:271:in `merge'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:865:in `inject'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.5/lib/logstash/filters/multiline.rb:270:in `merge'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.5/lib/logstash/filters/multiline.rb:232:in `previous_filter!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-0.1.5/lib/logstash/filters/multiline.rb:175:in `filter'", "(eval):47:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):43:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:275:in `filter'", "/opt/logstash/lib/logstash/pipeline.rb:209:in `filterworker'", "/opt/logstash/lib/logstash/pipeline.rb:153:in `start_filters'"], :level=>:error}

Regards
Christian

Using current Version ...

**Comment by cmahlig** [comment]
It was the older 1.8 Java version. I try the 1.7.0.75 and now it works m)
