### ISSUE TITLE
Issue with aws-sdk-resources inside Logstash and parsing s3

### ISSUE THREAD

**Issue by DanielRedOak** [elastic/logstash#2944]
Trying this ruby filter with some basic listing of a s3 bucket with a large amount of files causes a weird parsing error somewhere along the line that I can't seem to track down and causes the code to crash.  The same code works outside of logstash using the same aws-sdk-resources gem, so I'm having issues finding the issue.

Ex. Config
```ruby
input {
  stdin {}
}
filter {
  ruby {
    code => "require 'aws-sdk-resources'; s3 = Aws::S3::Resource.new(:region => 'us-east-1'); bucket = 'some-bucket'; prefix = 'AWSLogs/someaccount/CloudTrail/'; s3bucket = s3.bucket(bucket); s3bucket.objects(:prefix => prefix).each do |log|; puts log.key; end"
  }
}
output {
  stdout {}
}
```
Error (tried to clean it up for readability):
```
Exception in filterworker {"exception"=>#<RuntimeError: unhandled timestamp format `2015-0'>, "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/parser/frame.rb:277:in `parse'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/parser/frame.rb:275:in `parse'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/parser/frame.rb:267:in `set_text'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/parser/stack.rb:32:in `text'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/parser/engines/nokogiri.rb:29:in `characters'", "nokogiri/XmlSaxParserContext.java:252:in `parse_with'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/sax/parser.rb:112:in `parse_memory'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/nokogiri-1.6.6.2-java/lib/nokogiri/xml/sax/parser.rb:84:in `parse'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/parser/engines/nokogiri.rb:13:in `parse'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/parser.rb:28:in `parse'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/rest_handler.rb:15:in `parse_body'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/rest_body_handler.rb:91:in `parse'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/rest_body_handler.rb:40:in `extract_data'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/rest_body_handler.rb:10:in `call'", 
"org/jruby/RubyProc.java:271:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/response.rb:44:in `on'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/http/response.rb:137:in `on_success'", 
"org/jruby/RubyProc.java:271:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/http/response.rb:164:in `listener'", 
"org/jruby/RubyProc.java:271:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/http/response.rb:128:in `on_done'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/http/response.rb:135:in `on_success'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/response.rb:42:in `on'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/response.rb:52:in `on_success'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/rest_body_handler.rb:9:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/plugins/s3_url_encoded_keys.rb:39:in `manage_keys'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/plugins/s3_url_encoded_keys.rb:31:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/plugins/restful_bindings.rb:13:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/plugins/endpoint.rb:35:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/plugins/param_validation.rb:22:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/plugins/s3_sse_cpk.rb:18:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/plugins/response_target.rb:18:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/request.rb:70:in `send_request'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/seahorse/client/base.rb:216:in `list_objects'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.0.34/lib/aws-sdk-resources/request.rb:24:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.0.34/lib/aws-sdk-resources/operations.rb:127:in `all_batches'", 
"org/jruby/RubyEnumerator.java:274:in `each'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-resources-2.0.34/lib/aws-sdk-resources/collection.rb:18:in `each'", "(ruby filter code):1:in `register'", 
"org/jruby/RubyProc.java:271:in `call'", 
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-0.1.4/lib/logstash/filters/ruby.rb:37:in `filter'", "(eval):102:in `initialize'",
"org/jruby/RubyArray.java:1613:in `each'", 
"org/jruby/RubyEnumerable.java:805:in `flat_map'", "(eval):98:in `initialize'", 
"org/jruby/RubyProc.java:271:in `call'", 
"/opt/logstash/lib/logstash/pipeline.rb:275:in `filter'", 
"/opt/logstash/lib/logstash/pipeline.rb:209:in `filterworker'", 
"/opt/logstash/lib/logstash/pipeline.rb:153:in `start_filters'"], :level=>:error, :file=>"logstash/pipeline.rb", :line=>"222", :method=>"filterworker"}
```

Some debugging I've added to (/opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/parser/stack.rb) to show what it's receiving.

```ruby
def text(value)
  puts value.inspect
  @frame.set_text(value)
end
```

Output:
```
...
"AWSLogs/someaccount/CloudTrail/eu-west-1/2015/04/04/someaccount_CloudTrail_eu-west-1_20150404T1450Z_YPnaBuc2bGxhPjHQ.json.gz"
"2015-04-04T14:52:35.000Z"
"\""
"26a091c72b039fc7b28b90414ce01c21"
"\""
"484"
"STANDARD"
"AWSLogs/someaccount/CloudTrail/eu-west-1/2015/04/04/someaccount_CloudTrail_eu-west-1_20150404T1505Z_b1NDxxGvlx5qnaHM.json.gz"
"2015-0"
...(Exception here)
```

Added some debugging in /opt/logstash/vendor/bundle/jruby/1.9/gems/aws-sdk-core-2.0.34/lib/aws-sdk-core/xml/parser.rb to validate the XML.  Everything looks correct there so its somewhere down the line.

```ruby
def parse(xml, target = nil)
  xml = '<xml/>' if xml.nil? or xml.empty?
  puts "XML: " + xml + "ENDXML"
  stack = Stack.new(@shape, target)
  @engine.new(stack).parse(xml.to_s)
  stack.result
end
```

Not sure whats going on at this point, it only seems to happen when listing a large bucket (which worked up until Friday) which seems to make the parsing fail when run within Logstash.  Ideas?

**Comment by DanielRedOak** [comment]
This has something to do with changes in the aws-sdk with the latest release I believe, not sure yet what the issue is but reverting to 2.0.33 seems to allow things to work

**Comment by DanielRedOak** [comment]
https://github.com/aws/aws-sdk-ruby/pull/745

**Comment by DanielRedOak** [comment]
Moving conversation to aws-sdk-ruby as I can reproduce externally now.
