### ISSUE TITLE
Having references to a git repo (to install plugins) in the Gemfile is not working

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#2972]
As in the process of having a test suite that test all plugins vs the current master version, and not with the last release in rubygems, I encountered with the need to use the :git notation in the Gemfile.

Coming from a clean ENV, bootstrapping the env to then modify the Gemfile to get one like 

```
source "https://rubygems.org"
gemspec :name => "logstash-core"
gem "logstash-filter-cidr", :git => "https://github.com/logstash-plugins/logstash-filter-cidr.git"
gem "logstash-filter-elasticsearch", :git => "https://github.com/logstash-plugins/logstash-filter-elasticsearch.git"
gem "logstash-filter-translate", :git => "https://github.com/logstash-plugins/logstash-filter-translate.git"
gem "logstash-filter-punct", :git => "https://github.com/logstash-plugins/logstash-filter-punct.git"
gem "logstash-input-kafka", :git => "https://github.com/logstash-plugins/logstash-input-kafka.git"
```
(Link https://gist.github.com/purbon/614b02184ab4702731c2)

and then running ```DEBUG=1 bin/plugin install --no-verify``` to install the new plugins (to check the output you can review https://gist.github.com/purbon/55bd782f682506250945 ), having no clear information about problems.

if then you aim to run ```rake test:core``` the output I'm getting is:

```
rake aborted!
Could not find rake-10.4.2 in any of the sources
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/spec_set.rb:92:in `materialize'
org/jruby/RubyArray.java:2444:in `map!'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `materialize'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup'
/Users/purbon/work/logstash/lib/logstash/environment.rb:117:in `bundler_setup!'
/Users/purbon/work/logstash/rakelib/test.rake:13:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1087:in `load'
Tasks: TOP => test:core => test:setup
(See full trace by running task with --trace)
```

More ENV info, git clones are download and reported under ```vendor/bundle/jruby/1.9/bundler/gems``` 

The error command change if you include a gem 'plugin-name' before the ones that used :git .

**Comment by ph** [comment]
Do you have multiples *.lock in your logstash directory?
Before trying the installation can you paste the result of `bin/plugin list --verbose`

**Comment by purbon** [comment]
@ph There is only one .lock file

I just did this set of commands:

``` 
   rm -rf vendor/bundle 
   rake bootstrap
   rake test:install-core
   rake test:core
   bin/plugin list --verbose
```

and the output was:

```
╰─$ bin/plugin list --verbose
logstash-codec-json (0.1.6)
logstash-codec-json_lines (0.1.6)
logstash-codec-line (0.1.5)
logstash-codec-plain (0.1.5)
logstash-filter-clone (0.1.4)
logstash-filter-grok (0.1.8)
logstash-filter-mutate (0.1.5)
logstash-input-generator (0.1.4)
logstash-input-stdin (0.1.3)
logstash-input-tcp (0.1.4)
logstash-output-stdout (0.1.4)
logstash-patterns-core (0.1.6)
```

then I added the :git plugins, run ``` plugin install ``` and got no error error, the output of ``` plugin list ``` is :

```
╰─$ bin/plugin list --verbose             
logstash-codec-json (0.1.6)
logstash-codec-json_lines (0.1.6)
logstash-codec-line (0.1.5)
logstash-codec-plain (0.1.5)
logstash-filter-cidr (0.1.5)
logstash-filter-clone (0.1.4)
logstash-filter-elasticsearch (0.1.4)
logstash-filter-grok (0.1.8)
logstash-filter-mutate (0.1.5)
logstash-filter-punct (0.1.4)
logstash-filter-translate (0.1.8)
logstash-input-generator (0.1.4)
logstash-input-kafka (0.1.12)
logstash-input-stdin (0.1.3)
logstash-input-tcp (0.1.4)
logstash-output-stdout (0.1.4)
logstash-patterns-core (0.1.6)
```
showing plugins like input kafka, installed throw git and actually found in vendor/bundle.

WHAT, now I run ``` rake test:core ``` and there are no issues.

**Comment by ph** [comment]
hmm, did you update from master between your two runs?

**Comment by purbon** [comment]
yap, rebase against your changes,  .... checking again the two flows.

**Comment by purbon** [comment]
But if it works now perfect :-)

**Comment by ph** [comment]
Well, I think I know why we were skipping the options part for the gem declaration.
My change to support :path is now keeping them..

**Comment by purbon** [comment]
Hi,
  with this workflow:

``` rm -rf vendor/bundle 
    rake bootstrap
    *** add some git plugins ***
   rake test:core
```
it fails with the given error

```
╰─$ rake test:core                        
rake aborted!
Could not find rake-10.4.2 in any of the sources
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/spec_set.rb:92:in `materialize'
org/jruby/RubyArray.java:2444:in `map!'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/spec_set.rb:85:in `materialize'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/definition.rb:132:in `specs'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/definition.rb:177:in `specs_for'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/definition.rb:166:in `requested_specs'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/environment.rb:18:in `requested_specs'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler/runtime.rb:13:in `setup'
/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.2/lib/bundler.rb:122:in `setup'
/Users/purbon/work/logstash/lib/logstash/environment.rb:114:in `bundler_setup!'
/Users/purbon/work/logstash/rakelib/test.rake:13:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1087:in `load'
Tasks: TOP => test:core => test:setup
(See full trace by running task with --trace)
```
the plugin list is after the install

```
╭─purbon@Peres-MacBook-Pro-2  ~/work/logstash  ‹feature/test_plugins_with_master*› 
╰─$ bin/plugin list --verbose                                                                                                                                     1 ↵
logstash-codec-json (0.1.6)
logstash-codec-plain (0.1.5)
logstash-filter-cidr (0.1.5)
logstash-filter-elasticsearch (0.1.4)
logstash-filter-punct (0.1.4)
logstash-filter-translate (0.1.8)
logstash-input-kafka (0.1.12)
```

so plugins are there, but running test seems to not find rake in this case. On the other side, if there are some plugins installed the "usual" way, this is not happening.

**Comment by purbon** [comment]
I check again, and I was having an small issue on my side with the commands (missing to add development dependencies throw ```bin/plugin install --no-verify --development``` ) so if the workflow is:

```
   rake boostrap
   add test:core plugins with reference to git repos
   bin/plugin install --no-verify
   bin/plugin install --no-verify --development
   rake test:core
```
everything works as expected getting a clean output

```
╭─purbon@Peres-MacBook-Pro-2  ~/work/logstash  ‹feature/test_plugins_with_master*› 
╰─$ rake test:core
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
........................................................................................................................................................................................................................................................................................

Finished in 5.03 seconds
280 examples, 0 failures

Randomized with seed 59902
```

so I think we can close this issue.
