### ISSUE TITLE
EOFError when using tcp output plugin

### ISSUE THREAD

**Issue by Akshaykapoor** [elastic/logstash#2999]
I have a custom plugin which is inheriting the tcp output plugin. The error that i receive is, 

```
tcp output exception {:host=>"localhost", :port=>3030, :exception=>#<EOFError: End of file reached>, :backtrace=>["org/jruby/RubyIO.java:3003:in `sysread'", "/opt/logstash/lib/logstash/outputs/tcp.rb:105:in `register'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/codecs/json.rb:45:in `encode'", "/opt/logstash/lib/logstash/outputs/tcp_custom.rb:42:in `receive'", "/opt/logstash/lib/logstash/outputs/base.rb:86:in `handle'", "(eval):924:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/lib/logstash/pipeline.rb:266:in `output'", "/opt/logstash/lib/logstash/pipeline.rb:225:in `outputworker'", "/opt/logstash/lib/logstash/pipeline.rb:152:in `start_outputs'"], :level=>:warn}
```

This happens for every alternate event when received by sensu. I tried running with tcp output plugin but the results are still the same EOFError.

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-output-tcp/issues/9. Let's continue the discussion there! :)
