### ISSUE TITLE
NPE with lumberjack and logstash-1.4.2

### ISSUE THREAD

**Issue by wjimenez5271** [elastic/logstash#3092]
Sharing in case its helpful:

```
Exception in thread "Ruby-0-Thread-123: /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:58" java.lang.NullPointerException
	at org.jruby.RubyIO.flush(RubyIO.java:2199)
	at org.jruby.ext.openssl.SSLSocket.do_syswrite(SSLSocket.java:657)
	at org.jruby.ext.openssl.SSLSocket.syswrite(SSLSocket.java:667)
	at rubyjit.Lumberjack::Connection$$data_2d9d45de3150120a8315c8d3418e2cae61be3793991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:243)
	at rubyjit.Lumberjack::Connection$$data_2d9d45de3150120a8315c8d3418e2cae61be3793991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb)
	at rubyjit.Lumberjack::Connection$$data_2d9d45de3150120a8315c8d3418e2cae61be3793991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:101)
	at rubyjit.Lumberjack::Connection$$run_1ab64372e67eb080a540f66cd1b058cb4524bc82991505714.block_0$RUBY$__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:223)
	at rubyjit$Lumberjack::Connection$$run_1ab64372e67eb080a540f66cd1b058cb4524bc82991505714$block_0$RUBY$__file__.call(rubyjit$Lumberjack::Connection$$run_1ab64372e67eb080a540f66cd1b058cb4524bc82991505714$block_0$RUBY$__file__)
	at org.jruby.runtime.CompiledBlock19.yieldSpecificInternal(CompiledBlock19.java:117)
	at org.jruby.runtime.CompiledBlock19.yieldSpecific(CompiledBlock19.java:107)
	at org.jruby.runtime.Block.yieldSpecific(Block.java:138)
	at org.jruby.runtime.invokedynamic.InvocationLinker.yieldSpecificFallback(InvocationLinker.java:436)
	at rubyjit.Lumberjack::Parser$$data_field_value_8b5044466ffc67b039150435734c1b91ce098897991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:182)
	at rubyjit.Lumberjack::Parser$$data_field_value_8b5044466ffc67b039150435734c1b91ce098897991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)
	at org.jruby.RubyClass.finvoke(RubyClass.java:527)
	at org.jruby.RubyBasicObject.send19(RubyBasicObject.java:1504)
	at org.jruby.RubyKernel.send19(RubyKernel.java:2242)
	at rubyjit.Lumberjack::Parser$$feed_c1a593bee4f9cc5c59aff472fd516ed3f7091307991505714.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:93)
	at rubyjit.Lumberjack::Parser$$feed_c1a593bee4f9cc5c59aff472fd516ed3f7091307991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:92)
	at rubyjit.Lumberjack::Parser$$compressed_payload_5519163418dc1b26e6f84f1d8d5e9e8396cd7536991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:198)
	at rubyjit.Lumberjack::Parser$$compressed_payload_5519163418dc1b26e6f84f1d8d5e9e8396cd7536991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)
	at org.jruby.RubyClass.finvoke(RubyClass.java:527)
	at org.jruby.RubyBasicObject.send19(RubyBasicObject.java:1504)
	at org.jruby.RubyKernel.send19(RubyKernel.java:2242)
	at rubyjit.Lumberjack::Parser$$feed_c1a593bee4f9cc5c59aff472fd516ed3f7091307991505714.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:93)
	at rubyjit.Lumberjack::Parser$$feed_c1a593bee4f9cc5c59aff472fd516ed3f7091307991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:92)
	at rubyjit.Lumberjack::Connection$$run_1ab64372e67eb080a540f66cd1b058cb4524bc82991505714.chained_2_rescue_2$RUBY$SYNTHETIC__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:220)
	at rubyjit.Lumberjack::Connection$$run_1ab64372e67eb080a540f66cd1b058cb4524bc82991505714.chained_1_rescue_1$RUBY$SYNTHETIC__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb:214)
	at rubyjit.Lumberjack::Connection$$run_1ab64372e67eb080a540f66cd1b058cb4524bc82991505714.chained_0_ensure_1$RUBY$__ensure__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb)
	at rubyjit.Lumberjack::Connection$$run_1ab64372e67eb080a540f66cd1b058cb4524bc82991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb)
	at rubyjit.Lumberjack::Connection$$run_1ab64372e67eb080a540f66cd1b058cb4524bc82991505714.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.20/lib/lumberjack/server.rb)
	at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:149)
	at org.jruby.ast.CallNoArgBlockPassNode.interpret(CallNoArgBlockPassNode.java:53)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
	at org.jruby.runtime.Block.call(Block.java:101)
	at org.jruby.RubyProc.call(RubyProc.java:290)
	at org.jruby.RubyProc.call(RubyProc.java:228)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by suyograo** [comment]
@wjimenez5271 any chance you can try with LS 1.5.0RC3 and LSF 0.4.0?

**Comment by wjimenez5271** [comment]
@suyograo Yes, I intend to upgrade to that, but I'm not certain I'll be able to reproduce the issue. This happened after running for a while, and only thing that changed was the log volume increased.

**Comment by wjimenez5271** [comment]
@suyograo When I try to run 1.5.0RC3 I get the following error on startup:
```
$ sudo /opt/logstash/bin/logstash -f /etc/logstash.d/lumberjack.conf
Exception in filterworker {"exception"=>#<NameError: undefined local variable or method `event' for #<LogStash::Pipeline:0x51a97faa>>, "backtrace"=>["(eval):111:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:309:in `flush_filters'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:308:in `flush_filters'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:317:in `flush_filters_to_output!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:223:in `filterworker'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:223:in `filterworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:156:in `start_filters'"], :level=>:error}
Logstash startup completed
cx^CSIGINT received. Shutting down the pipeline. {:level=>:warn}
Exception in lumberjack input {:exception=>#<LogStash::ShutdownSignal: LogStash::ShutdownSignal>, :level=>:error}
```

**Comment by suyograo** [comment]
@wjimenez5271 can you share your config?

**Comment by wjimenez5271** [comment]
@suyograo actually never-mind I wasn't using the right JVM

**Comment by suyograo** [comment]
@wjimenez5271 you had me worried there :smile:

**Comment by wjimenez5271** [comment]
@suyograo actually it still has the same error even after using oracle jdk 1.8. Here is my config: https://gist.github.com/wjimenez5271/d145cf8906752b5a5cbe

**Comment by suyograo** [comment]
@wjimenez5271 thanks, I've created a new issue. Could you please add sample log lines for this? Also need output of `java -version`

https://github.com/elastic/logstash/issues/3100

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-lumberjack/issues/18. Let's continue the discussion there! :)
