### ISSUE TITLE
Logstash Twitter Plugin Error

### ISSUE THREAD

**Issue by bhangun** [elastic/logstash#3097]
When i tried using twitter plugin with  "full_tweet => true" there is error occure in Elasticsearch

----------------Logstash Configuration----------------------
input{
	twitter{
             .........
             ........
            full_tweet => true
	}
}

---------------ERROR------------------------
[2015-04-24 00:52:03,873][WARN ][cluster.routing.allocation.decider] [Bennet du Paris] high disk watermark [10%] exceeded on [ly-y3A3eTHeGscyPAR7LHQ][Bennet du Paris] free: 9.9gb[1.4%], shards will be relocated away from this node
[2015-04-24 00:52:22,048][DEBUG][action.bulk              ] [Bennet du Paris] [tweets][0] failed to execute bulk item (index) index {[tweets][logs][AUznaLggwnebVGPnYcW4], source[{"created_at":"Thu Apr 23 17:52:21 +0000 2015","id":591298578884251650,"id_str":"591298578884251650","text":"Konferensi Pers saat Penyerahan Sertifikasi Syariah http://t.co/jg9QwfJsRn, Order PIN:51AB74C7 - WA: 087885546800 #Depok","source":"<a href=\"http://twittbot.net/\" rel=\"nofollow\">twittbot.net</a>","truncated":false,"in_reply_to_status_id":null,"in_reply_to_status_id_str":null,"in_reply_to_user_id":null,"in_reply_to_user_id_str":null,"in_reply_to_screen_name":null,"user":{"id":946639728,"id_str":"946639728","name":"COD di DEPOK","screen_name":"CODDEPOK","location":"Depok","url":null,"description":"JUAL MASKER SPIRULINA COD di Depok PIN:51AB74C7 - WA: 087885546800 | Herbal, HALAL, BPOM & SYARIAH","protected":false,"verified":false,"followers_count":346,"friends_count":530,"listed_count":0,"favourites_count":0,"statuses_count":2232,"created_at":"Tue Nov 13 22:39:14 +0000 2012","utc_offset":25200,"time_zone":"Jakarta","geo_enabled":false,"lang":"id","contributors_enabled":false,"is_translator":false,"profile_background_color":"C0DEED","profile_background_image_url":"http://abs.twimg.com/images/themes/theme1/bg.png","profile_background_image_url_https":"https://abs.twimg.com/images/themes/theme1/bg.png","profile_background_tile":false,"profile_link_color":"0084B4","profile_sidebar_border_color":"C0DEED","profile_sidebar_fill_color":"DDEEF6","profile_text_color":"333333","profile_use_background_image":true,"profile_image_url":"http://pbs.twimg.com/profile_images/569405743766319104/NT6cEzDg_normal.jpeg","profile_image_url_https":"https://pbs.twimg.com/profile_images/569405743766319104/NT6cEzDg_normal.jpeg","profile_banner_url":"https://pbs.twimg.com/profile_banners/946639728/1424591904","default_profile":true,"default_profile_image":false,"following":null,"follow_request_sent":null,"notifications":null},"geo":null,"coordinates":null,"place":null,"contributors":null,"retweet_count":0,"favorite_count":0,"entities":{"hashtags":[{"text":"Depok","indices":[114,120]}],"trends":[],"urls":[],"user_mentions":[],"symbols":[],"media":[{"id":473159350513827840,"id_str":"473159350513827840","indices":[52,74],"media_url":"http://pbs.twimg.com/media/BpD_7CGIAAA89WP.jpg","media_url_https":"https://pbs.twimg.com/media/BpD_7CGIAAA89WP.jpg","url":"http://t.co/jg9QwfJsRn","display_url":"pic.twitter.com/jg9QwfJsRn","expanded_url":"http://twitter.com/Tiens_Malang/status/473159358998515712/photo/1","type":"photo","sizes":{"small":{"w":340,"h":254,"resize":"fit"},"thumb":{"w":150,"h":150,"resize":"crop"},"large":{"w":511,"h":383,"resize":"fit"},"medium":{"w":511,"h":383,"resize":"fit"}},"source_status_id":473159358998515712,"source_status_id_str":"473159358998515712"}]},"extended_entities":{"media":[{"id":473159350513827840,"id_str":"473159350513827840","indices":[52,74],"media_url":"http://pbs.twimg.com/media/BpD_7CGIAAA89WP.jpg","media_url_https":"https://pbs.twimg.com/media/BpD_7CGIAAA89WP.jpg","url":"http://t.co/jg9QwfJsRn","display_url":"pic.twitter.com/jg9QwfJsRn","expanded_url":"http://twitter.com/Tiens_Malang/status/473159358998515712/photo/1","type":"photo","sizes":{"small":{"w":340,"h":254,"resize":"fit"},"thumb":{"w":150,"h":150,"resize":"crop"},"large":{"w":511,"h":383,"resize":"fit"},"medium":{"w":511,"h":383,"resize":"fit"}},"source_status_id":473159358998515712,"source_status_id_str":"473159358998515712"}]},"favorited":false,"retweeted":false,"possibly_sensitive":false,"filter_level":"low","lang":"in","timestamp_ms":"1429811541659","@timestamp":"2015-04-23T17:52:21.000Z","@version":"1"}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [user]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:409)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeObject(ObjectMapper.java:554)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:487)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:544)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:493)
	at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:453)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:432)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:149)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:515)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:422)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.ElasticsearchIllegalArgumentException: unknown property [id]
	at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateFieldForString(StringFieldMapper.java:331)
	at org.elasticsearch.index.mapper.core.StringFieldMapper.parseCreateField(StringFieldMapper.java:277)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:399)
	... 12 more
[2015-04-24 00:52:33,873][WARN ][cluster.routing.allocation.decider] [Bennet du Paris] high disk watermark [10%] exceeded on [ly-y3A3eTHeGscyPAR7LHQ][Bennet du Paris] free: 9.9gb[1.4%], shards will be relocated away from this node

**Comment by jordansissel** [comment]
For Logstash 1.5.0, we've moved all plugins to individual repositories, so I have moved this issue to https://github.com/logstash-plugins/logstash-input-twitter/issues/13. Let's continue the discussion there! :)
