### ISSUE TITLE
local installation of plugins through path or .gem depends on git

### ISSUE THREAD

**Issue by fbaligand** [elastic/logstash#3117]
Because in `.gemspec` file, the preconized way to specify files list is based on git (```s.files = `git ls-files`.split($\)```), when I install a plugin on logstash, and worse when I run logstash (with a local plugin installed) ; logstash needs `git` in `PATH`.

The problem is that git is not installed on every machine where logstash is present.
For example, if I want to install a plugin on a logstash production environment, git is probably not installed.

So, to avoid git dependency, it could be nice to prefer something like this in `.gemspec` file :
`s.files = Dir['lib/**/*','spec/**/*','*.gemspec','*.md','CONTRIBUTORS','Gemfile','LICENSE']`

**Comment by jsvd** [comment]
The recent RC3 release no longer contains a .gemspec file:

```
% ls logstash-1.5.0-rc3
CHANGELOG               Gemfile                 LICENSE                 lib/                    spec/
CONTRIBUTORS            Gemfile.jruby-1.9.lock  bin/                    locales/                vendor/
```

so this should no longer be a concern.

**Comment by fbaligand** [comment]
When I talk about ".gemspec" file, I don't mean "logstash-core", but logstash plugins, and especially external plugins that are not provided by logstash tarball.
For example, my plugin : https://github.com/fbaligand/logstash-filter-aggregate/

When I install it into logstash (using `$LS_HOME/bin/plugin install`), it is not installed in the same way than provided plugins.
It is installed into a separate folder named $LS_HOME/vendor/local_gems.
And in logstash `Gemfile`, the reference to my gem is also different from provided plugins :
`gem "logstash-filter-aggregate", "0.1.2", :path => "vendor/local_gems/9fad3d89/logstash-filter-aggregate-0.1.2"`

**Comment by fbaligand** [comment]
@suyograo Which details do you need ?

**Comment by purbon** [comment]
@fbaligand I did a very simple test with an ubuntu vm where git was not installed and can not reproduce your issue. I basically installed a local gem, build in another machine throw ```bin/plugin install ```

As far as I know the only part that is git dependant is the gem build.

It would be super useful to get a detailed descriptions of what are you doing to get into this error, including the operating system you're using. Makes sense to you?

**Comment by fbaligand** [comment]
My test was on windows 7 64 bits. 
My JVM is jdk1.7.0_55

Here is my gem : https://dl.dropboxusercontent.com/u/11312286/logstash-filter-aggregate-0.1.3.gem

Here is the error when installing my plugin (using `bin\plugin.bat install`) into logstash 1.5.0-rc3 :
```
Validating D:/Developpement/workspaces/workspaceEclipse4/logstash-filter-aggregate/logstash-filter-aggregate-0.1.3.gem
Installing logstash-filter-aggregate
Error Bundler::GemspecError, retrying 1/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 2/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 3/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 4/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 5/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 6/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 7/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 8/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 9/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Error Bundler::GemspecError, retrying 10/10
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Too many retries, aborting, caused by Bundler::GemspecError
There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'
Bundler::GemspecError: There was a Errno::ENOENT while loading logstash-filter-aggregate.gemspec:
No such file or directory - git from
  D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/local_gems/33503f73/logstash-filter-aggregate-0.1.3/logstash-filter-aggregate.gemspec:13:in `eval_gemspec'

           eval_gemspec at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler.rb:414
  load_gemspec_uncached at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler.rb:370
                  chdir at org/jruby/RubyDir.java:339
                  chdir at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/shared_helpers.rb:53
        mon_synchronize at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/jruby/lib/ruby/1.9/monitor.rb:211
                  chdir at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/shared_helpers.rb:52
  load_gemspec_uncached at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler.rb:365
           load_gemspec at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler.rb:355
        load_spec_files at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/source/path.rb:135
                   each at org/jruby/RubyArray.java:1613
        load_spec_files at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/source/path.rb:134
            local_specs at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/source/path.rb:92
                  specs at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/source/path.rb:100
  converge_locked_specs at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/definition.rb:518
                   each at org/jruby/RubyArray.java:1613
  converge_locked_specs at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/definition.rb:507
                resolve at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/definition.rb:190
                  specs at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/definition.rb:132
      resolve_remotely! at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/definition.rb:121
                    run at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/installer.rb:79
                install at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/installer.rb:18
                    run at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/cli/install.rb:80
                install at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/cli.rb:157
                    run at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/command.rb:27
         invoke_command at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:126
               dispatch at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor.rb:359
                  start at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/vendor/thor/lib/thor/base.rb:440
                  start at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/bundler-1.9.4/lib/bundler/cli.rb:10
        invoke_bundler! at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/lib/logstash/bundler.rb:109
                   loop at org/jruby/RubyKernel.java:1507
        invoke_bundler! at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/lib/logstash/bundler.rb:106
                   call at org/jruby/RubyProc.java:271
         capture_stdout at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/lib/logstash/bundler.rb:61
        invoke_bundler! at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/lib/logstash/bundler.rb:105
     install_gems_list! at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/lib/logstash/pluginmanager/install.rb:98
                execute at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/lib/logstash/pluginmanager/install.rb:34
                    run at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/command.rb:67
                execute at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/subcommand/execution.rb:11
                    run at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/command.rb:67
                    run at D:/Developpement/java-libs/logstash/logstash-1.5.0-rc3/vendor/bundle/jruby/1.9/gems/clamp-0.6.4/lib/clamp/command.rb:132
                 (root) at D:\Developpement\java-libs\logstash\logstash-1.5.0-rc3\lib\logstash\pluginmanager.rb:12
```

**Comment by jsvd** [comment]
I was able to replicate this on windows. investigating

**Comment by jsvd** [comment]
the problem might have to do with how different platforms deal with executing commands that don't exist.

On MacOSX:

```
% irb
> `command_that_doesnt_exist`
=> ""
>
```

On windows:

```
irb(main):002:0> `command_that_doesnt_exist`
Errno::ENOENT: No such file or directory - command_that_doesnt_exist
        from file:/C:/logstash-1.5.0-rc3/vendor/jruby/lib/jruby.jar!/jruby/kerne
l/jruby/process_manager.rb:24:in ``'
        from file:/C:/logstash-1.5.0-rc3/vendor/jruby/lib/jruby.jar!/jruby/kerne
l/jruby/process_manager.rb:49:in ``'
        from (irb):2:in `evaluate'
```

**Comment by jsvd** [comment]
This occurs only in local .gem or :path plugin installations that will read/execute the .gemspec.
Installing plugins from rubygems will not require git.
changing the name of this issue to reflect the issue

**Comment by fbaligand** [comment]
Ok, which title do you wish ?

Fabien

**Comment by jsvd** [comment]
It has been noted that "bin/plugin update" on a clean release doesn't work because logstash-core is a local gem.
But why don't we have an extra check during [Update#execute](https://github.com/elastic/logstash/blob/master/lib/logstash/pluginmanager/update.rb#L17-L22) that filters the `gemfile.locally_installed_gems` to remove non plugin specs?

During  [update_gems!](https://github.com/elastic/logstash/blob/master/lib/logstash/pluginmanager/update.rb#L38-L45) we bother to select gemspecs that belong to plugins using `.select { |plugin| gemfile.find(plugin) }` so why not make that check earlier and proceed with "bin/plugin update" as long as there are no local "plugin" gems (vs no local gems)?

**Comment by fbaligand** [comment]
I'm not an expert, but that suggestion sounds good to me.

**Comment by jsvd** [comment]
Unfortunately that solves only the issue of installing a gem through :path, but not in your scenario of `bin/plugin install <file>.gem`

JRuby has an open issue about this different behaviour https://github.com/jruby/jruby/issues/1396#issuecomment-99796425

Regardless, the proper fix is to update all plugins, replacing the call to git with a Dir.glob, as @fbaligand suggested.

**Comment by purbon** [comment]
Even if not just to fix this issue, I like the idea of not using anymore git to get the files ... for example in logstash-core there is no more the usage of git https://github.com/elastic/logstash/blob/master/logstash-core.gemspec#L14

**Comment by purbon** [comment]
So +1 on the Dir way :+1:

**Comment by jsvd** [comment]
My candidate for replacing `git ls-files` is:

```ruby
s.files = Dir[
  'lib/**/*',
  'spec/**/*',
  'vendor/**/*',
  '*.gemspec',
  '*.md',
  'CONTRIBUTORS',
  'Gemfile',
  'LICENSE',
  'NOTICE.TXT'
]
```

Any other suggestions?

**Comment by ph** [comment]
vendor.json ?

**Comment by jsvd** [comment]
@ph any reason for that? we're shipping with the jars so no point in including the Rakefile and vendor.json

**Comment by ph** [comment]
Yeah you are right! its a `file-dependencies` flashback.

**Comment by ph** [comment]
+1 on that list.

**Comment by fbaligand** [comment]
As there is already '*.md' pattern, it is not useful to explicitly add README.md and CHANGELOG.md.

**Comment by jordansissel** [comment]
@jsvd also ignore 'build/' directory

**Comment by colinsurprenant** [comment]
+1

**Comment by jsvd** [comment]
@fbaligand derp, you're right :+1:

**Comment by jsvd** [comment]
@jordansissel this is a list of stuff to put in, so not having build there already ignores it?

**Comment by jsvd** [comment]
all plugin repos have been updated to remove the call to git

**Comment by jsvd** [comment]
I don't think there's a reason to do a mass plugin release because of this, anyone arguments otherwise?

**Comment by fbaligand** [comment]
Up to me, no real valuable argument to release ALL plugins.

**Comment by purbon** [comment]
No need to release plugins, this affects the gem build process only as far
as i know.

/purbon

**Comment by ph** [comment]
@jsvd We have to do a mass release soon to make sure the `logstash-core` dependency are correctly defined to support the shutdown refactor. this can go in at the same time.

**Comment by webmstr** [comment]
Unfortunately, this change was only made for the 2.0 lines.  Anyone running 1.5 (which is still available for download) is seemingly hosed.
