### ISSUE TITLE
Installing plugins in linux (from source code is broken)

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3224]
As discovered from http://build-eu-00.elastic.co/view/LS%201.5/job/Logstash%20Regression%201.5%20(Release)/3/jdk=JDK7,label=metal-pool/console

```
Using sawyer 0.6.0
Using octokit 3.8.0
Using rubyzip 1.1.7
Using bundler 1.9.7
Bundle complete! 114 Gemfile dependencies, 194 gems now installed.
Gems in the group development were not installed.
Bundled gems are installed into ./vendor/bundle.
[plugin:install-core] Installing core plugins
/home/jenkins/workspace/Logstash Regression 1.5 (Release)/jdk/JDK7/label/metal-pool/bin/plugin: 4: .: Can't open /home/jenkins/workspace/bin/logstash.lib.sh
rake aborted!

/home/jenkins/workspace/Logstash Regression 1.5 (Release)/jdk/JDK7/label/metal-pool/rakelib/plugin.rake:7:in `install_plugins'
/home/jenkins/workspace/Logstash Regression 1.5 (Release)/jdk/JDK7/label/metal-pool/rakelib/plugin.rake:34:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1087:in `load'
Tasks: TOP => test:install-core => plugin:install-core
(See full trace by running task with --trace)
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
rake aborted!
Could not find rake-10.4.2 in any of the sources
/home/jenkins/workspace/Logstash Regression 1.5 (Release)/jdk/JDK7/label/metal-pool/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/spec_set.rb:92:in `materialize'
org/jruby/RubyArray.java:2444:in `map!'
/home/jenkins/workspace/Logstash Regression 1.5 (Release)/jdk/JDK7/label/metal-pool/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/spec_set.rb:85:in `materialize'
/home/jenkins/workspace/Logstash Regression 1.5 (Release)/jdk/JDK7/label/metal-pool/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/definition.rb:132:in `specs'
/home/jenkins/workspace/Logstash Regression 1.5 (Release)/jdk/JDK7/label/metal-pool/vendor/bundle/jruby/1.9/gems/bundler-1.9.7/lib/bundler/definition.rb:177:in `specs_for'
/home/jenkins/workspace/Logstash Regression 1.5 (Release)/jdk/JDK7/label/metal-pool/vendor/bundle/jruby/1.9/gems/bundler-1.9.7
```

it actually complains about not properly finding the logstash.lib.sh file in https://github.com/elastic/logstash/blob/master/bin/plugin#L1-L11

This does not happen with mac. Before assessing the severity we should also check packaging is healthy.

**Comment by purbon** [comment]
As of the test done today:

1.- If running on a mac, everything :green_heart: .
2.- Running on an ubuntu machine, from a clean clone, :green_heart: .

but if executed within a jenkins job, 

```
 ci/ci_setup.sh
 ci/ci_test.sh
```

fails if using LOGSTASH_CORE, however if pointing to the same dir everything goes well.

**Comment by purbon** [comment]
After some debugging, the problem is that if the name of the git clone have spaces using rake test:install-core or other variants is broken as of with this error:

```
plugin:install-core] Installing core plugins
/Users/purbon/work/log stash/bin/plugin: line 4: /Users/purbon/work/bin/logstash.lib.sh: No such file or directory
rake aborted!

/Users/purbon/work/log stash/rakelib/plugin.rake:7:in `install_plugins'
/Users/purbon/work/log stash/rakelib/plugin.rake:34:in `(root)'
org/jruby/RubyProc.java:271:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1087:in `load'
Tasks: TOP => test:install-core => plugin:install-core
(See full trace by running task with --trace)
```

**Comment by ph** [comment]
This is still an issue
