### ISSUE TITLE
Exception in filterworker / NoMethodError: undefined method `to_hash (geoip)

### ISSUE THREAD

**Issue by jannae** [elastic/logstash#3235]
I'm at a bit of a loss, so any help is appreciated. I'm getting a few errors that seem to have brought my ELK instance to it's knees. It stops dead on these, each time I attempt to restart or update the config in any way. Not sure what to make of it, as all my research has led me to previously corrected issues. 

It seems related to this:
 
<https://logstash.jira.com/browse/LOGSTASH-1394>

Though this is indicated as having been corrected. :(

Also, if you need to review my configs they are here: https://github.com/jannae/logstash-configs

This may or may not be related to my recent upgrade to 1.5.0 rc4, it's tough to tell, except that this is a brand new problem for me, so, seems plausible.

```
{:timestamp=>"2015-05-12T22:11:44.302000-0400",
    :message=>"Exception in filterworker",
        "exception"=>#<NoMethodError: undefined method `to_hash' for "*AS18144 Energia Communications,Inc.":String>,
        "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-0.1.9/lib/logstash/filters/geoip.rb:119:in `filter'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/filters/base.rb:162:in `multi_filter'",
        "org/jruby/RubyArray.java:1613:in `each'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/filters/base.rb:159:in `multi_filter'",
        "(eval):10100:in `cond_func_383'",
        "org/jruby/RubyArray.java:1613:in `each'",
        "(eval):10094:in `cond_func_383'",
        "(eval):3085:in `filter_func'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/pipeline.rb:219:in `filterworker'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/pipeline.rb:156:in `start_filters'"],
    :level=>:error}
{:timestamp=>"2015-05-12T22:11:44.349000-0400",
    :message=>"Exception in filterworker",
        "exception"=>#<NoMethodError: undefined method `to_hash' for "*AS18144 Energia Communications,Inc.":String>,
        "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-0.1.9/lib/logstash/filters/geoip.rb:119:in `filter'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/filters/base.rb:162:in `multi_filter'",
        "org/jruby/RubyArray.java:1613:in `each'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/filters/base.rb:159:in `multi_filter'",
        "(eval):10100:in `cond_func_383'",
        "org/jruby/RubyArray.java:1613:in `each'",
        "(eval):10094:in `cond_func_383'",
        "(eval):3085:in `filter_func'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/pipeline.rb:219:in `filterworker'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/pipeline.rb:156:in `start_filters'"],
    :level=>:error}
{:timestamp=>"2015-05-12T22:11:44.427000-0400",
    :message=>"Exception in filterworker",
        "exception"=>#<NoMethodError: undefined method `to_hash' for "*AS18144 Energia Communications,Inc.":String>,
        "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-0.1.9/lib/logstash/filters/geoip.rb:119:in `filter'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/filters/base.rb:162:in `multi_filter'",
        "org/jruby/RubyArray.java:1613:in `each'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/filters/base.rb:159:in `multi_filter'",
        "(eval):10100:in `cond_func_383'",
        "org/jruby/RubyArray.java:1613:in `each'",
        "(eval):10094:in `cond_func_383'",
        "(eval):3085:in `filter_func'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/pipeline.rb:219:in `filterworker'",
        "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc4-java/lib/logstash/pipeline.rb:156:in `start_filters'"],
    :level=>:error}
```

**Comment by jordansissel** [comment]
I've moved this here: https://github.com/logstash-plugins/logstash-filter-geoip/issues/21
