### ISSUE TITLE
A foul message in a batch makes logstash elasticsearch output drop entire batch

### ISSUE THREAD

**Issue by horkhe** [elastic/logstash#3283]
If logstash fails to push a batch of log messages through an output (elasticsearch in particular) then after a number of retries it drops entire batch even if it is just one log message that made the batch fail. It might make sense to split a failed batch into smaller batches and try deliver them. If a smaller batch is successfully delivered then our job is done. If not then it can further split it into smaller batches. The process continues until a batch is reduced to just one message that if fails can be dropped. Or something along these lines.

**Comment by colinsurprenant** [comment]
@horkhe thanks for the report. we have in fact reworked the retry mechanism in the elasticsearch output plugin. Agree than a poison message should not invalidate a complete bulk request. @talevy maybe you can take a look at this?

**Comment by talevy** [comment]
@horkhe are you seeing that successful messages from that batch are being re-indexed and showing up as duplicates in Elasticsearch? We retry events which return `429` and `503` errors from Elasticsearch. Any other errors like `400` mapping errors are dropped.

for example: this following pipeline will result in the following output and indexed items in Elasticsearch:


```
# logstash.conf

input {
  generator {
    lines => [
      '{"geoip": "notlatlon"}', # invalid geoip mapping according to default logstash index template
      "{}"
    ]
    count => 1
    codec => json
  }
}

output {
  elasticsearch {
    protocol => http
  }
}
```

```
# response from a clean es cluster with no previously indexed documents

$ curl localhost:9200/_count
{"count":1,"_shards":{"total":5,"successful":5,"failed":0}}
```

is your experience not conforming to this expected behavior?

**Comment by horkhe** [comment]
Looking at the logstash logs it seemed like entire batch was discarded. We saw:
```
{:timestamp=>"2015-05-19T12:11:54.169000+0000", :message=>"Failed to flush outgoing items", :outgoing_count=>2000, :exception=>#<Manticore::Timeout: Read timed out>, :backtrace=>["/opt/logstash/server/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:61:in `call'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:225:in `call_once'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:128:in `code'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:50:in `perform_request'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:33:in `perform_request'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch/protocol.rb:100:in `bulk'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:437:in `submit'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:436:in `submit'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:462:in `flush'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:460:in `flush'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `each'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:193:in `buffer_flush'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:159:in `buffer_receive'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:426:in `receive'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):247:in `output_func'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash/server/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0.rc3-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}
{:timestamp=>"2015-05-19T12:11:57.083000+0000", :message=>"retrying failed action with response code: 429", :level=>:warn}
```
followed by numerous
```
{:timestamp=>"2015-05-19T12:11:57.083000+0000", :message=>"retrying failed action with response code: 429", :level=>:warn}
```
that had been appearing for about 20 minutes and then a whole bunch of
```
{:timestamp=>"2015-05-19T12:12:16.278000+0000", :message=>"too many attempts at sending event. dropping: 2015-05-19T12:10:57.722Z %{host} <event content redacted>
```
reported at once. The number of these events seems to correspond to the number of events in a batch.

But I have just checked ES and was able to find all events reported as dropped in this log. And now I am confused how could they get there if they were reported as dropped.

**Comment by talevy** [comment]
I believe the log messages in logstash make it a bit difficult to understand which actions are failed. retryable actions are sent to another queue which are then sent to Elasticsearch using the same mechanism as newly introduced events. so it is sometimes difficult to see which actions are retrying for the first time or not. You should not be seeing successful actions being retried. In terms of the "too many attempts" problem, I will file an issue to slow down the retry frequency. as this can only exacerbate the issue.

**Comment by horkhe** [comment]
Ok, then I guess this issue can be closed.

**Comment by suyograo** [comment]
@horkhe thanks. We'll add a test to cover this scenario. https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/158
