### ISSUE TITLE
1.5.0 crashes with "slice bounds out of range" panic

### ISSUE THREAD

**Issue by arabold** [elastic/logstash#3309]
I'm investigating an issue I'm seeing on my local machine when running logstash 1.5.0 inside of a Docker container (based off the official "logstash:1.5" image). 

I read log data from S3 (ELB and Cloudfront data) and have a couple of generic filters defined for parsing. It works well for a while but then suddenly Logstash crashes with the following log output:

```
panic: runtime error: slice bounds out of range

goroutine 12 [running]:
bufio.(*Reader).fill(0xc08200e780)
        /usr/local/go/src/bufio/bufio.go:86 +0x2e2
bufio.(*Reader).WriteTo(0xc08200e780, 0x382410, 0xc08200abe0, 0x9b72, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:449 +0x285
io.Copy(0x382410, 0xc08200abe0, 0x3849e0, 0xc08200e780, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/io.go:354 +0xb9
github.com/docker/docker/api/client.func┬╖022(0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/hijack.go:210 +0x1e0
github.com/docker/docker/pkg/promise.func┬╖001()
        /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
created by github.com/docker/docker/pkg/promise.Go
        /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102

goroutine 1 [chan receive, 2 minutes]:
github.com/docker/docker/api/client.(*DockerCli).CmdRun(0xc0820ff400, 0xc082050020, 0x7, 0x7, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/commands.go:2469 +0xfcd
reflect.callMethod(0xc0820b52c0, 0xc082049be8)
        /usr/local/go/src/reflect/value.go:605 +0x180
reflect.methodValueCall(0xc082050020, 0x7, 0x7, 0x1, 0xc0820b52c0, 0xc0820ff401, 0xc0820d8bd0, 0x5, 0xc08200ab01, 0x375d40, ...)
        /usr/local/go/src/reflect/asm_amd64.s:29 +0x3d
github.com/docker/docker/api/client.(*DockerCli).Cmd(0xc0820ff400, 0xc082050010, 0x8, 0x8, 0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/cli.go:81 +0x385
main.main()
        /go/src/github.com/docker/docker/docker/docker.go:138 +0xb90

goroutine 5 [syscall, 4 minutes]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:21 +0x26
created by os/signal.init┬╖1
        /usr/local/go/src/os/signal/signal_unix.go:27 +0x3c

goroutine 11 [chan receive, 2 minutes]:
github.com/docker/docker/api/client.(*DockerCli).hijack(0xc0820ff400, 0x898b90, 0x4, 0xc082060800, 0x76, 0x1, 0x3823e0, 0xc08200ab90, 0x382410, 0xc08200abe0, ...)
        /go/src/github.com/docker/docker/api/client/hijack.go:237 +0xd38
github.com/docker/docker/api/client.func┬╖013(0x0, 0x0)
        /go/src/github.com/docker/docker/api/client/commands.go:2437 +0x1c9
github.com/docker/docker/pkg/promise.func┬╖001()
        /go/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x36
created by github.com/docker/docker/pkg/promise.Go
        /go/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x102

goroutine 9 [IO wait]:
net.(*pollDesc).Wait(0xc0820ec170, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:84 +0x4e
net.(*ioSrv).ExecIO(0xc082046380, 0xc0820ec060, 0x89b3f0, 0x7, 0x97d8c0, 0x91, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:188 +0x305
net.(*netFD).Read(0xc0820ec000, 0xc0820cc000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/fd_windows.go:470 +0x180
net.(*conn).Read(0xc082046020, 0xc0820cc000, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:121 +0xe3
crypto/tls.(*block).readFromUntil(0xc0820e49c0, 0x384028, 0xc082046020, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:454 +0xed
crypto/tls.(*Conn).readRecord(0xc08209a580, 0x17, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:539 +0x2e1
crypto/tls.(*Conn).Read(0xc08209a580, 0xc082013000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:904 +0x16d
net/http.noteEOFReader.Read(0x3847a0, 0xc08209a580, 0xc08206bd38, 0xc082013000, 0x1000, 0x1000, 0xc08208d500, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1270 +0x75
net/http.(*noteEOFReader).Read(0xc0820fc2a0, 0xc082013000, 0x1000, 0x1000, 0xc082014000, 0x0, 0x0)
        <autogenerated>:125 +0xdb
bufio.(*Reader).fill(0xc0820ea480)
        /usr/local/go/src/bufio/bufio.go:97 +0x1d5
bufio.(*Reader).Peek(0xc0820ea480, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xf7
net/http.(*persistConn).readLoop(0xc08206bce0)
        /usr/local/go/src/net/http/transport.go:842 +0xab
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:660 +0xca6

goroutine 10 [select]:
net/http.(*persistConn).writeLoop(0xc08206bce0)
        /usr/local/go/src/net/http/transport.go:945 +0x424
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:661 +0xcc3

goroutine 14 [sleep]:
github.com/docker/docker/api/client.func┬╖025()
        /go/src/github.com/docker/docker/api/client/utils.go:286 +0x69
created by github.com/docker/docker/api/client.(*DockerCli).monitorTtySize
        /go/src/github.com/docker/docker/api/client/utils.go:295 +0x163
```

So far I have no explanation. The crash happens randomly and I'm not perfectly sure yet whether it relates to a erroneous filter, a specific log that fails to parse properly, or if it's a more generic error of Logstash.

*UPDATE*: It seems this issue is reproducible consistently. If I create a new docker container and run it over the same data set again, it will also crash again - however, it _seems_ it crashes at a different point in time / when processing a different data set.

**Comment by arabold** [comment]
Here's the (shortened) config I was using when the crash happened. It's important to note that I did NOT send any events via TCP or syslog. The only thing that was running were the two S3 input plugins.

```
input {
  tcp {
    type => "tcp"
    port => 5000
  }

  syslog {
    type => "syslog"
    port => 5544
    tags => []
  }

  s3 {
    type => "elb"
    # FIXME Credential file doesn't work (https://github.com/logstash-plugins/logstash-input-s3/issues/28)
    #aws_credentials_file => "/etc/logstash/conf.d/aws_credentials.yml"
    credentials => [ "...", "..." ]
    bucket => "biu-logs"
    prefix => "elb/.../"
    region => "us-east-1"
    tags => [ "elb", "aws", "prod" ]
  }

  s3 {
    type => "cloudfront"
    #aws_credentials_file => "/etc/logstash/conf.d/aws_credentials.yml"
    credentials => [ "...", "..." ]
    bucket => "biu-logs"
    prefix => "cf/.../"
    region => "us-east-1"
    tags => [ "cloudfront", "aws", "prod" ]
  }

}

# Add your filters here
filter {

  if [type] == "elb" {
    grok {
      match => [ "message", "%{TIMESTAMP_ISO8601:timestamp} %{NOTSPACE:loadbalancer} %{IP:clientip}:%{NUMBER:clientport:int} %{IP:host}:%{NUMBER:hostport:int} %{NUMBER:request_processing_time:float} %{NUMBER:backend_processing_time:float} %{NUMBER:response_processing_time:float} %{NUMBER:elb_status_code:int} %{NUMBER:backend_status_code:int} %{NUMBER:received_bytes:int} %{NUMBER:sent_bytes:int} %{QS:request}" ]
    }
    date {
      match => [ "timestamp", "ISO8601" ]
    }
  }

  if [type] == "cloudfront" {
    csv {
      separator => "	"
      columns => [ "date", "time", "x-edge-location", "sc-bytes", "clientip", "verb", "cs-host", "request", "response", "referrer", "agent", "cs-uri-query", "cookie", "x-edge-result-type", "x-edge-request-id", "host", "protocol", "cs-bytes", "time-taken" ]
      add_field => [ "listener_timestamp", "%{date} %{time}" ]
    }
    date {
      match => [ "listener_timestamp", "yy-MM-dd HH:mm:ss" ]
      remove_field => [ "listener_timestamp" ]
    }

    urldecode {
      field => "agent"
    }

    if ! [host] {
      mutate {
        update => { "host" => "%{cs-host}" }
      }
    }
  }

  if [type] == "syslog" {

    // ... no messages were sent via syslog, so this part should be irrelevant
    
  }


  # Some generic post-processing filters that apply to all types
  #--------------------------------------------------------------

  # Process GeoIP information
  if [clientip] {
    geoip {
      source => "clientip"
      add_tag => [ "geoip" ]
    }
  }

  if [agent] {
    useragent {
      source => "agent"
    }
  }
}

output {

   stdout {
     codec => rubydebug
   }
}
```

**Comment by arabold** [comment]
My current hypothesis is that this error is caused due to my setup with Docker 1.6 running on Windows (inside Boot2docker). After I have disabled the `stdout` output plugin and don't use the Logstash `-vv` flag, I cannot reproduce this issue anymore. Anyone else having similar problems?

**Comment by arabold** [comment]
Uhmm... now, thinking about it... I should have realized that the crash happens in Go and thus is very likely related to Docker and not Logstash at all! I think you can close this here and I'll report that problem over at Docker instead.

Sorry for the spam.

**Comment by colinsurprenant** [comment]
@arabold thanks for the report, as you figured out, this error/crash is within docker. I will go ahead and close this issue.
