### ISSUE TITLE
Failing test on the 1.5 branch on jenkins 

### ISSUE THREAD

**Issue by ph** [elastic/logstash#3384]
http://build-eu-00.elastic.co/job/logstash_regression_1.5_release/jdk=JDK8,label=metal-pool/lastBuild/console

Failures:

  1) LogStashConfigParser#compile with multiline conditionals should compile successfully
     Failure/Error: expect { eval(result.compile) }.not_to(raise_error)
       expected no Exception, got #<SyntaxError: (eval):23: syntax error, unexpected kOR
                    or [anotherthing]
                     ^> with backtrace:
         # ./spec/core/config_spec.rb:65:in `(root)'
         # ./spec/core/config_spec.rb:65:in `(root)'
         # ./rakelib/test.rake:17:in `(root)'
     # ./spec/core/config_spec.rb:65:in `(root)'
     # ./rakelib/test.rake:17:in `(root)'

**Comment by ph** [comment]
A bit weird, the master branch and the other 1.5 regression branch includes the failing test and run on jenkins

see http://build-eu-00.elastic.co/job/logstash_regression_15/
and http://build-eu-00.elastic.co/job/logstash_regression_master/

**Comment by ph** [comment]
Okay got it, if you use the ./ci_setup.sh and ./ci_test.sh It fails on the 1.5 branch

**Comment by ph** [comment]
Same scenario doesn't fail on master branch.

**Comment by ph** [comment]
The problem is this branch actually use the released `logstash-core` gem and will fail since we did not release it and the fix is include in that release. So I wont touch this but I have found another issue when looking at the specs will make a PR for it.
