### ISSUE TITLE
Different results between stdin and lumberjack input

### ISSUE THREAD

**Issue by Limskya** [elastic/logstash#3392]
Hi everyone,

I'm trying to parse a full java stack like this :

[2015-06-08 15:54:28.045 +0200CEST] ERROR 172.16.10.24 ES1 appserver0 [NI-NOFR-Site] [-] com.intershop.adapter.search_solr.internal.SolrIndex [] [Storefront] [o9jb8LqBSPYp-e_07NLC-qotyeLR_G1H-wgMNuJRjLMdrm1H-wg=] [1QqzEFV1npMZChCs-0-00] "1QqzEFV1npMZChCs-0-00" Error during Solr server communication. org.apache.solr.client.solrj.SolrServerException: java.net.ConnectException: Connection refused
	at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:480)
	at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:246)
	at org.apache.solr.client.solrj.request.QueryRequest.process(QueryRequest.java:89)
	at org.apache.solr.client.solrj.SolrServer.query(SolrServer.java:276)
	at com.intershop.adapter.search_solr.internal.SolrIndex.query(SolrIndex.java:134)
	at com.intershop.component.search.pipelet.QuerySearchIndex.execute(QuerySearchIndex.java:80)
	at com.intershop.beehive.core.internal.pipeline.PipeletNode.executeNode(PipeletNode.java:353)
	at com.intershop.beehive.core.internal.pipeline.Pipeline.executeNode(Pipeline.java:1062)
	at com.intershop.beehive.core.internal.pipeline.Pipeline.executePipeline(Pipeline.java:888)
	at com.intershop.beehive.core.internal.pipeline.PipelineProcessorImpl.executePipeline(PipelineProcessorImpl.java:634)
	at com.intershop.beehive.core.internal.pipeline.PipelineProcessorImpl.executePipeline(PipelineProcessorImpl.java:477)
	at com.intershop.beehive.pipeline.internal.PipelineEngineImpl.executePipeline(PipelineEngineImpl.java:97)
	at com.intershop.beehive.core.internal.pipeline.PipelineProcessorImpl.executePipeline(PipelineProcessorImpl.java:416)
	at com.intershop.beehive.core.internal.pipeline.PipelineProcessorImpl.executePipeline(PipelineProcessorImpl.java:256)
	at com.intershop.beehive.core.internal.request.RequestHandlerServlet.processRequest(RequestHandlerServlet.java:469)
	at com.intershop.beehive.core.internal.request.RequestHandlerServlet.processRequest(RequestHandlerServlet.java:299)
	at com.intershop.beehive.core.internal.request.RequestHandlerServlet.service(RequestHandlerServlet.java:194)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:168)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.intershop.beehive.core.internal.locking.ProcessContextCleanupFilter.doFilter(ProcessContextCleanupFilter.java:35)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.intershop.beehive.core.internal.app.AppContextCleanupFilter.doFilter(AppContextCleanupFilter.java:40)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.intershop.beehive.core.internal.request.ORMCleanupFilter.doFilter(ORMCleanupFilter.java:43)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.intershop.beehive.core.internal.request.MDCClearingFilter.doFilter(MDCClearingFilter.java:32)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.intershop.beehive.core.internal.request.SecureTokenFilter.doFilter(SecureTokenFilter.java:105)
	at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:280)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at org.apache.solr.client.solrj.impl.CommonsHttpSolrServer.request(CommonsHttpSolrServer.java:424)
	... 53 common frames omitted

System Information
------------------
RequestID: 1QqzEFV1npMZChCs-0-00
StartDate: Mon Jun 08 15:54:27 CEST 2015
SessionType: STOREFRONT
SessionID: o9jb8LqBSPYp-e_07NLC-qotyeLR_G1H-wgMNuJRjLMdrm1H-wg=
UserID: lK6sEAoYteAAAAFNI1UUY9Nz
ServerName: norautofr-re7-metier-live.elosi.com
ServerPort: 80

Request Information
-------------------
URI: /servlet/Beehive/WFS/NI-NOFR-Site/fr_FR/-/EUR/IncludeParametricSearchIndexJSon-Start
Method: GET
PathInfo: /WFS/NI-NOFR-Site/fr_FR/-/EUR/IncludeParametricSearchIndexJSon-Start
QueryString: FilterTarget=&UseCache=true&mode=0&SearchParameter=%26%40QueryTerm%3D*%26PNEUSTYPE%3DVoiture%26Categorie%3D1%26%40GroupSize.MARQUE%3D0%26LARGEUR_PNEUMATIQUE%3D205%26SERIE_PNEUMATIQUE%3D55%26DIAMETRE_PNEUMATIQUE%3D16%26%40GroupSize.RUNFLAT%3D0%26INDICE_DE_CHARGE%3D91%26INDICE_DE_VITESSE%3DV
Remote Address: 192.168.90.26

Request Parameters
------------------
UseCache=true
FilterTarget=
mode=0
SearchParameter=&@QueryTerm=*&PNEUSTYPE=Voiture&Categorie=1&@GroupSize.MARQUE=0&LARGEUR_PNEUMATIQUE=205&SERIE_PNEUMATIQUE=55&DIAMETRE_PNEUMATIQUE=16&@GroupSize.RUNFLAT=0&INDICE_DE_CHARGE=91&INDICE_DE_VITESSE=V

Sometimes my events dont have Java stack or Request Parameters

So this is my filter config :

input { stdin{
	 type=>"javastack"
	 codec =>multiline{
		pattern =>"^\["
		negate =>true
		what =>"previous"
}}}

filter{
if [type] == "javastack"{
 
mutate{
	gsub => [ "message","\s"," "]
	gsub => [ "message","\t"," "]
}

#Filter avec JST et avec RP 
	grok{
	match =>{"message" => "\[%{DATA:Timestamp}\] %{LOGLEVEL:Severity} %{DATA:Role} \[%{DATA:Request-site}\] \[%{DATA:Resquest-app}\] %{DATA:logger} \[%{DATA:marker}\] \[%{DATA:Request-type}\] \[%{DATA:Session-ID}\] \[%{DATA:UUID}\] %{DATA:Log-message}   at %{GREEDYDATA:JavaStack}    System Information  ------------------  %{GREEDYDATA:System-Information}    Request Information  -------------------  %{GREEDYDATA:Request-Information}    Request Parameters  ------------------  %{GREEDYDATA:Request-Parameters}"}	
 }
 if "_grokparsefailure" in [tags]{
	mutate{
		remove_tag =>"_grokparsefailure"
		add_tag => "_grok1fail"
  }
}
if "_grok1fail" not in [tags]{
	mutate{ add_tag => "JST-RP"}
 }

#Filter avec JST et sans RP
if "_grok1fail" in [tags]{
	grok{
	match =>{"message" => "\[%{DATA:Timestamp}\] %{LOGLEVEL:Severity} %{DATA:Role} \[%{DATA:Request-site}\] \[%{DATA:Resquest-app}\] %{DATA:logger} \[%{DATA:marker}\] \[%{DATA:Request-type}\] \[%{DATA:Session-ID}\] \[%{DATA:UUID}\] %{DATA:Log-message}   at %{GREEDYDATA:JavaStack}    System Information  ------------------  %{GREEDYDATA:System-Information}    Request Information  -------------------  %{GREEDYDATA:Request-Information}    Request Parameters  ------------------"}	
 }
 if "_grokparsefailure" in [tags]{
	mutate{
		remove_tag =>"_grokparsefailure"
		add_tag => "_grok2fail"
  }
}
if "_grok2fail" not in [tags]{
	mutate{ add_tag => "JST-0"}
 }
}
#Filter sans JST avec RP
if "_grok2fail" in [tags]{
        grok {
         match => {"message" => "\[%{DATA:Timestamp}\] %{LOGLEVEL:Severity} %{DATA:Role} \[%{DATA:Request-site}\] \[%{DATA:Resquest-app}\] %{DATA:logger} \[%{DATA:marker}\] \[%{DATA:Request-type}\] \[%{DATA:Session-ID}\] \[%{DATA:UUID}\] %{DATA:Log-message}%{SPACE}    System Information  ------------------  %{GREEDYDATA:System-Information}    Request Information  -------------------  %{GREEDYDATA:Request-Information}"}
  }
if "_grokparsefailure" in [tags]{
	mutate{
		remove_tag =>"_grokparsefailure"
		add_tag =>"_grok3fail" 
   }
  
if "_grok3fail" not in [tags]{
        mutate{ add_tag => "0-RP"}
 }
}
}
#Filter sans JST et sans RP
if "_grok3fail" in [tags]{
	grok{
	match => {"message" => "\[%{DATA:Timestamp}\] %{LOGLEVEL:Severity} %{DATA:Role} \[%{DATA:Request-site}\] \[%{DATA:Resquest-app}\] %{DATA:logger} \[%{DATA:marker}\] \[%{DATA:Request-type}\] \[%{DATA:Session-ID}\] \[%{DATA:UUID}\] %{GREEDYDATA:Log-message}"}

}
	mutate{
		add_tag =>"0-0"
}
}
mutate{
	remove_field =>["message"]
}

}
}
output{stdout{codec=>rubydebug}}

My problem is : When i try to use this config with my ELK ( well configured) my results in Kibana are differents, my first three filters are ignored and  i don't have my fields Javastack and Request Parameters when they are in the event !

Is it me or there is something else ? 
Thx

**Comment by suyograo** [comment]
Hi can you please post this question/discuss here: https://discuss.elastic.co/c/logstash. Github is mainly used for issues/enhancements.
