### ISSUE TITLE
logstash crashing the whole time

### ISSUE THREAD

**Issue by sybnex** [elastic/logstash#3400]
Hi, 

running on RHEL 7.1, Logstash 1.5.0-1, Elastsearch 1.5.2, Redis 2.8

The indexer connecting to redis, reading stuff and shipping it to elastisearch ist crashing. 
I'll tried severeal configurations playing with workers on elastic, with threads on redis and -w option on logstash.
Logstash ist crashing in any of these configs loading the redis queue. 
actually workaround: restarting logstash every 5 min.

```
logstash.err:
Exception in thread ">elasticsearch.1" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)

logstash.conf:
input {
  redis {
    host => "something"
    data_type => "list"
    key => "logstash"
    threads => 32
    batch_count => 100
  }
}
(a lot of filters (grok and kv)
output {
  elasticsearch { host       => localhost
                  protocol   => "http"
                  index      => "idx_%{type}-%{+YYYY.MM.dd}"
                  flush_size => 100
                  workers    => 2
                }
}
```

At the moment I can not understand how does it works for anybody.
I've just started with a big project and around 1200 hosts to collect logfiles from and it is just crashing.

**Comment by jsvd** [comment]
@sybnex what is the minimum, average and maximum size of the requests sent to elasticsearch?

If you output to a file does it still crash?

**Comment by sybnex** [comment]
I was just monitoring the redis stat and I saw max. at 22000 (requests/sec.) min. at 1000 and avg maybe at 4000. The incoming request is about 80 - 200.

Now, since the queue is nearly emtpy it seems to be stable again. So I think this is an workload issue on the elasticsearch plugin. 

Before, I just had a pure ELK installation and logstash crashed all the time. So I decided to try it with redis.

I will monitor it for a while and put some feedback on it.

**Comment by sybnex** [comment]
This night I had several crashed with different reasons:

```
Exception in thread ">elasticsearch.1" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread ">elasticsearch.1" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread ">elasticsearch.1" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Ruby-0-Thread-95: /opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:92" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Ruby-0-Thread-96: /opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:92" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread ">elasticsearch.0" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "|worker" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "|worker" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

My workaround is just to force restart (normal wouldn't work).

I don't know what to do to stable this solution.

**Comment by sybnex** [comment]
Found the following running logstah in debug mode:

```
filters/LogStash::Filters::Grok: adding value to field {:field=>"received_at", :value=>["%{@timestamp}"], :level=>:debug, :file=>"logstash/filters/base.rb", :line=>"193", :method=>"filter_matched"}
filters/LogStash::Filters::Grok: adding value to field {:field=>"received_from", :value=>["%{host}"], :level=>:debug, :file=>"logstash/filters/base.rb", :line=>"193", :method=>"filter_matched"}
Shifting current elasticsearch client {:level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"468", :method=>"flush"}
Switched current elasticsearch client to #0 at localhost {:level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"518", :method=>"shift_client"}
Exception in thread "|worker" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

But I don't know, since it is a thread, if the exception is coming from there.

**Comment by sybnex** [comment]
After implementing the following filter:

```
  if [type] == "jboss" {
    if [message] =~ /:Envelope/ {
      drop { }
    }
  }
```

Logstash is not crashing anymore.

It seems there is an issue on very large log lines (> 100.000 lines).
Sometimes logstash was crashing on the grok filter during parsing of such large things or during the shipping to elasticsearch.

grok:
```
...
  else if [type] == "jboss" {
#    multiline {
#      pattern => "20%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:?%{MINUTE}(?::?%{SECOND})"
#      negate  => true
#      what    => "previous"
#    }
    grok {
      match => [ "message", "20%{YEAR}-%{MONTHNUM}-%{MONTHDAY} %{HOUR}:?%{MINUTE}(?::?%{SECOND}) %{LOGLEVEL:severity} \[%{DATA:package}\] \(%{DATA:address}\) %{GREEDYDATA:jboss_message}" ]
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "timestamp", "yyyy-MM-dd HH:mm:ss,SSS" ]
    }
  }
...
```

Sadly I can't ship the logfiles. 
But it could be tested with very large input (in my example a huge soap entry).

**Comment by LiangAllen** [comment]
hi ,@sybnex 
How to solve this error ，logstash restart and occurred error ：
Exception in thread "Ruby-0-Thread-10: /usr/local/src/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.20/lib/stud/buffer.rb:92" java.lang.UnsupportedOperationException
	at java.lang.Thread.stop(Thread.java:869)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Thread.java:745)


 Exception in thread ">output" java.lang.UnsupportedOperationException
	at java.lang.Thread.stop(Thread.java:869)
	at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sybnex** [comment]
To be honest,  I gave up on the ELK stack. Just using elasticsearch and kibana. 

IHMO logstash and the forwarder are horrible in handling large systems. 

I'm using now python with the plugin to import stuff and forward to elasticsearch. It seems to be much more stable. 

Greets

**Comment by suyograo** [comment]
@sybnex apologies for having a bad experience with Logstash. Since you were pumping in large documents to ES, did you try increasing the heap size? The default bulk size in ES output is 5K, which may be too much for the default heap size of 500 MB. In our next release, we are doing 2 things to address this: Reducing the default bulk size to 500, and increasing the heap size to 1 GB OOTB.

Thanks for the feedback.

**Comment by suyograo** [comment]
@LiangAllen it would be helpful to create a new issue for the particular error you are facing. Also, please attach your config and a sample log line to help us debug. Thanks!
