### ISSUE TITLE
Logstash 1:1.5.0-1 cannot reconnect to rabbitmq after rabbitmq server has been restarted

### ISSUE THREAD

**Issue by parabolic** [elastic/logstash#3403]
**System**
```
Ubuntu 14.04.1 LTS
```
**Logstash_version**
```
1:1.5.0-1
```
**Conf**
```
UDP input
No filters
Rabbitmq ssl output
```
**Kernel**
```
3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
After restarting the rabbitmq server logstash is not able to reconect to rabbitmq and it needs to be restarted. I get the following error in the logs. And I see a lot of connects from that ip in the rabbitmq server.
** Logstash log **
```
{:timestamp=>"2015-06-09T13:02:20.348000+0000", :message=>"RabbitMQ connection error: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0). Will attempt to reconnect in 10 seconds...", :exception=>#<MarchHare::ChannelAlreadyClosed: #method<connection.close>(reply-code=320, reply-text=CONNECTION_FORCED - broker forced connection closure with reason 'shutdown', class-id=0, method-id=0)>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:965:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:963:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:595:in `basic_publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exchange.rb:77:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:40:in `publish_serialized'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-0.1.7/lib/logstash/codecs/json.rb:44:in `encode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:31:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:88:in `handle'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:79:in `worker_setup'"], :level=>:error}
```
**Rabbitmq server log**
```
=INFO REPORT==== 9-Jun-2015::14:51:49 ===
accepting AMQP connection
```
again and again

Logstash at this point cannot be restarted with /etc/init.d/logstash restart and it needs to be killed with -9. After that everything works fine.

**Comment by untergeek** [comment]
Thanks for the detailed report.  Can you please open this in the RabbitMQ output's repository instead?

https://github.com/logstash-plugins/logstash-output-rabbitmq

That's the appropriate place for this issue.

Thanks!

**Comment by parabolic** [comment]
Thanks! I will do so right away
