### ISSUE TITLE
Logstash 1.5.0 plugin crash with rest-client dependency

### ISSUE THREAD

**Issue by lucashenning** [elastic/logstash#3411]
Hi,
I have an issue regarding logstash plugins which have a dependency to [ruby rest-client](https://rubygems.org/gems/rest-client). Receiving an event causes the following exception:

```
Exception in filterworker {"exception"=>#<SystemCallError: Unknown error - Unknown Error (0) - /home/xxx/.netrc>, "backtrace"=>[
    "org/jruby/RubyFile.java:865:in `stat'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/netrc-0.10.3/lib/netrc.rb:43:in `check_permissions'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/netrc-0.10.3/lib/netrc.rb:52:in `read'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/request.rb:284:in `parse_url_with_auth'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/request.rb:175:in `execute'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/resource.rb:54:in `get'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-rest-0.1.0/lib/logstash/filters/rest.rb:50:in `filter'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:162:in `multi_filter'", 
    "org/jruby/RubyArray.java:1613:in `each'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:159:in `multi_filter'", 
    "(eval):41:in `filter_func'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:219:in `filterworker'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:156:in `start_filters'"
], :level=>:error}
```

When a .netrc file with 0600 permissions is created in /home/xxx/ Logstash throws this exception:

```
Exception in filterworker {"exception"=>#<Netrc::Error: Permission bits for '/home/xxx/.netrc' should be 0600, but are 644>, "backtrace"=>[
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/netrc-0.10.3/lib/netrc.rb:45:in `check_permissions'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/netrc-0.10.3/lib/netrc.rb:52:in `read'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/request.rb:284:in `parse_url_with_auth'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/request.rb:175:in `execute'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/request.rb:41:in `execute'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/rest-client-1.8.0/lib/restclient/resource.rb:54:in `get'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-rest-0.1.0/lib/logstash/filters/rest.rb:50:in `filter'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:162:in `multi_filter'", 
    "org/jruby/RubyArray.java:1613:in `each'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/filters/base.rb:159:in `multi_filter'", 
    "(eval):41:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:219:in `filterworker'", 
    "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:156:in `start_filters'"
], :level=>:error}
```

For further information please see:
https://github.com/cyli/logstash-output-slack/issues/1
https://discuss.elastic.co/t/logstash-1-5-rest-plugin-exception-with-rest-client-and-netrc/1917

Could this be a logstash bug?

**Comment by lucashenning** [comment]
Supplement:
Today I tried Logstash 1.5.1 but the issue is still there. Any ideas?

**Comment by ph** [comment]
This seems to be a problem with netrc as commented there https://github.com/cyli/logstash-output-slack/issues/1#issuecomment-121201946
