### ISSUE TITLE
gelf listener died

### ISSUE THREAD

**Issue by avcherkasov** [elastic/logstash#3447]
hi there,
i have es 1.5.2+logstash 1.5.0
and there an input gelf on 12201 port by udp in my config.
I have a lot of docs receiving by this input, but it's a lot of exceptions also(
:message=>"gelf listener died", :exception=>#<LogStash::Json::ParserError: No content to map due to end-of-input
 at [Source: [B@7221f4fe; line: 1, column: 1]>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/json.rb:37:in `jruby_load'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/json.rb:35:in `jruby_load'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-0.1.5/lib/logstash/inputs/gelf.rb:109:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-0.1.5/lib/logstash/inputs/gelf.rb:62:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:177:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:171:in `start_input'"], :level=>:warn}
 at [Source: [B@7afd729d; line: 1, column: 1]>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/json.rb:37:in `jruby_load'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/json.rb:35:in `jruby_load'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-0.1.5/lib/logstash/inputs/gelf.rb:109:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-0.1.5/lib/logstash/inputs/gelf.rb:62:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:177:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:171:in `start_input'"], :level=>:warn}

Please, give me some advice!

**Comment by ro0kie4** [comment]
Have you fixed it somehow?
