### ISSUE TITLE
Prerelease plugins cannot be used

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#3449]
```
% bin/plugin list --verbose logstash-output-http
logstash-output-http (0.1.5.pre)

% bin/logstash --debug -e 'output { http { } }'
Plugin not defined in namespace, checking for plugin file {:type=>"output", :name=>"http", :path=>"logstash/outputs/http", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"133", :method=>"lookup"}
The error reported is:
  undefined method `version' for nil:NilClass
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/util/plugin_version.rb:26:in `find_version!'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/util/plugin_version.rb:36:in `find_plugin_version!'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/config/mixin.rb:219:in `print_version_notice'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/config/mixin.rb:206:in `validate'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/config/mixin.rb:102:in `config_init'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:52:in `initialize'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:292:in `plugin'
(eval):7:in `initialize'
org/jruby/RubyKernel.java:1107:in `eval'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:30:in `initialize'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/agent.rb:109:in `execute'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/runner.rb:87:in `run'
org/jruby/RubyProc.java:271:in `call'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/runner.rb:92:in `run'
org/jruby/RubyProc.java:271:in `call'
/Users/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/task.rb:12:in `initialize'
```

The plugin was found, sorta, but failed to load.

If I try to uninstall it, uninstalling claims it's not installed:

```
% bin/plugin uninstall logstash-output-http
ERROR: Uninstall Aborted, message: This plugin has not been previously installed, aborting
```

---

If I version the plugin as non-prerelease, things seem to work:

```
# (on a fresh install)
% bin/plugin install ~/projects/logstash-output-http/logstash-output-http-0.1.5.gem
Validating /Users/jls/projects/logstash-output-http/logstash-output-http-0.1.5.gem
Installing logstash-output-http
Installation successful

# And now logstash works on the plugin
% bin/logstash --debug -e 'output { http { .... } }'
...

# And uninstalling works, too
% bin/plugin uninstall logstash-output-http
Uninstalling logstash-output-http

```

**Comment by purbon** [comment]
Fixed in #3476
