### ISSUE TITLE
Lumberjack connections stay in CLOSE_WAIT state

### ISSUE THREAD

**Issue by lvasiliev** [elastic/logstash#3459]
I have a some problem with logstash-1.5.1. After some times Lumberjack doesn't accept new connections. I collected data for debug:

OS: 
FreeBSD 9.3-RELEASE-p10
```
openjdk version "1.7.0_80"
OpenJDK Runtime Environment (build 1.7.0_80-b15)
OpenJDK 64-Bit Server VM (build 24.80-b11, mixed mode)
```
In this case Lumberjack doesn't accept new connections:
```
% netstat -Lan
Current listen queue sizes (qlen/incqlen/maxqlen)
Proto Listen         Local Address         
tcp4  76/0/50        XX.XX.XX.XX.5043    

% netstat -an | grep CLOSE_WAIT | wc -l
      76
```
FreeBSD kernel message:
```
kernel: sonewconn: pcb 0xfffffe0a81ae1000: Listen queue overflow: 76 already in queue awaiting acceptance (350 occurrences)
```
```
% telnet XXX 5043
Trying XX.XX.XX.XX...
Connected to XXX.
Escape character is '^]'.
Connection closed by foreign host.
```

Running process:
```
root 9863 23.6  1.2 2080452 612264 ??  I     8:00AM 55:17.59 /usr/local/openjdk7/bin/java -Xmx1G -Xss2048k -Djffi.boot.library.path=/usr/local/logstash-1.5.1/vendor/jruby/lib/jni -Xbootclasspath/a:/usr/local/logstash-1.5.1/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/usr/local/logstash-1.5.1/vendor/jruby -Djruby.lib=/usr/local/logstash-1.5.1/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main --1.9 /usr/local/logstash/lib/bootstrap/environment.rb logstash/runner.rb agent -f /usr/local/etc/logstash/logstash-broker.conf --log /var/log/logstash/logstash_broker.log -w 6
```

Part of jstack command:
```
"<lumberjack" daemon prio=5 tid=0x000000085c893800 nid=0x85cb61400 runnable [0x00007ffffdfe6000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:200)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x00000008106a20c0> (a sun.nio.ch.Util$2)
        - locked <0x00000008106a20b0> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000008106a1f30> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
        at org.jruby.ext.openssl.SSLSocket$2.run(SSLSocket.java:348)
        at org.jruby.RubyThread.executeBlockingTask(RubyThread.java:1065)
        at org.jruby.ext.openssl.SSLSocket.waitSelect(SSLSocket.java:325)
        at org.jruby.ext.openssl.SSLSocket.doHandshake(SSLSocket.java:440)
        at org.jruby.ext.openssl.SSLSocket.acceptCommon(SSLSocket.java:276)
        at org.jruby.ext.openssl.SSLSocket.accept(SSLSocket.java:238)
        at org.jruby.ext.openssl.SSLSocket$INVOKER$i$0$0$accept.call(SSLSocket$INVOKER$i$0$0$accept.gen)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
        at rubyjit.OpenSSL::SSL::SSLServer$$accept_aa44fff8dcff80ddb31aa5ae2378886b2b329fe42051849391.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/usr/local/logstash-1.5.1/vendor/jruby/l
ib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:142)
        at rubyjit.OpenSSL::SSL::SSLServer$$accept_aa44fff8dcff80ddb31aa5ae2378886b2b329fe42051849391.__file__(/usr/local/logstash-1.5.1/vendor/jruby/lib/ruby/shared/jopenssl19/openssl
/ssl-internal.rb:139)
        at rubyjit.OpenSSL::SSL::SSLServer$$accept_aa44fff8dcff80ddb31aa5ae2378886b2b329fe42051849391.__file__(/usr/local/logstash-1.5.1/vendor/jruby/lib/ruby/shared/jopenssl19/openssl
/ssl-internal.rb)
        at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:141)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
        at rubyjit.Lumberjack::Server$$accept_fde2c563046cccd2079a76be417618d822b6b5282051849391.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/g
ems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:58)
        at rubyjit.Lumberjack::Server$$accept_fde2c563046cccd2079a76be417618d822b6b5282051849391.__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:57)
        at rubyjit.Lumberjack::Server$$accept_fde2c563046cccd2079a76be417618d822b6b5282051849391.__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb)
        at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:141)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
        at rubyjit.LogStash::Inputs::Lumberjack$$accept_d7eab2108c99695217432fe7b335272a4988fecd2051849391.__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.9/lib/logstash/inputs/lumberjack.rb:80)
        at rubyjit.LogStash::Inputs::Lumberjack$$accept_d7eab2108c99695217432fe7b335272a4988fecd2051849391.__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.9/lib/logstash/inputs/lumberjack.rb)
        at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
        at org.jruby.ast.FCallNoArgBlockNode.interpret(FCallNoArgBlockNode.java:32)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
        at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
        at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
        at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
        at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
        at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
        at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
        at org.jruby.runtime.Block.call(Block.java:101)
        at org.jruby.RubyProc.call(RubyProc.java:290)
        at org.jruby.RubyProc.call(RubyProc.java:228)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None
```

In normal state:
```
Current listen queue sizes (qlen/incqlen/maxqlen)
Proto Listen         Local Address         
tcp4  0/0/50         XX.XX.XX.XX.5043    
```

```
"<lumberjack" daemon prio=5 tid=0x000000083bc94800 nid=0x83bcf5800 runnable [0x00007ffffdfe6000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
        at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:200)
        at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:103)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:87)
        - locked <0x0000000810e87810> (a sun.nio.ch.Util$2)
        - locked <0x0000000810e87800> (a java.util.Collections$UnmodifiableSet)
        - locked <0x0000000810e875c0> (a sun.nio.ch.KQueueSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:98)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:102)
        at org.jruby.RubyThread.select(RubyThread.java:1278)
        - locked <0x000000080d72add8> (a java.lang.Object)
        at org.jruby.RubyThread.select(RubyThread.java:1256)
        at org.jruby.RubyThread.select(RubyThread.java:1248)
        at org.jruby.ext.socket.RubyTCPServer.accept(RubyTCPServer.java:148)
        at org.jruby.ext.socket.RubyTCPServer$INVOKER$i$0$0$accept.call(RubyTCPServer$INVOKER$i$0$0$accept.gen)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
        at rubyjit.OpenSSL::SSL::SSLServer$$accept_aa44fff8dcff80ddb31aa5ae2378886b2b329fe41063096049.__file__(/usr/local/logstash-1.5.1/vendor/jruby/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb:138)
        at rubyjit.OpenSSL::SSL::SSLServer$$accept_aa44fff8dcff80ddb31aa5ae2378886b2b329fe41063096049.__file__(/usr/local/logstash-1.5.1/vendor/jruby/lib/ruby/shared/jopenssl19/openssl/ssl-internal.rb)
        at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:141)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
        at rubyjit.Lumberjack::Server$$accept_fde2c563046cccd2079a76be417618d822b6b5281063096049.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:58)
        at rubyjit.Lumberjack::Server$$accept_fde2c563046cccd2079a76be417618d822b6b5281063096049.__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb:57)
        at rubyjit.Lumberjack::Server$$accept_fde2c563046cccd2079a76be417618d822b6b5281063096049.__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.22/lib/lumberjack/server.rb)
        at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:141)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
        at rubyjit.LogStash::Inputs::Lumberjack$$accept_d7eab2108c99695217432fe7b335272a4988fecd1063096049.__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.9/lib/logstash/inputs/lumberjack.rb:80)
        at rubyjit.LogStash::Inputs::Lumberjack$$accept_d7eab2108c99695217432fe7b335272a4988fecd1063096049.__file__(/usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.9/lib/logstash/inputs/lumberjack.rb)
        at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:161)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
        at org.jruby.ast.FCallNoArgBlockNode.interpret(FCallNoArgBlockNode.java:32)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
        at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
        at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
        at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
        at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
        at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
        at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
        at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
        at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
        at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
        at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
        at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
        at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
        at org.jruby.runtime.Block.call(Block.java:101)
        at org.jruby.RubyProc.call(RubyProc.java:290)
        at org.jruby.RubyProc.call(RubyProc.java:228)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
        at java.lang.Thread.run(Thread.java:745)

   Locked ownable synchronizers:
        - None
```

**Comment by suyograo** [comment]
@ph is this fixed with https://github.com/logstash-plugins/logstash-input-lumberjack/pull/12 ?

**Comment by ph** [comment]
Yes connection  will now timeout and won't stay in close wait.

**Comment by lvasiliev** [comment]
I see same error in logstash-1.5.2 too.
