### ISSUE TITLE
Logstash 1.5.1 RabbitMQ output exception

### ISSUE THREAD

**Issue by sombut** [elastic/logstash#3513]
Hi,

We got an issue after upgraded the logstash from 1.4.2 to 1.5.1 where the rabbitmq output connection was error, it kept retrying but never success. Below an exception we got, could you shed some light on this please?

{:timestamp=>"2015-06-27T13:00:10.157000+0000", :message=>"RabbitMQ connection error: IOError. Will attempt to reconnect in 10 seconds...", :exception=>#<IOError: IOError>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:965:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:963:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:595:in `basic_publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exchange.rb:77:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:40:in `publish_serialized'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-0.1.7/lib/logstash/codecs/json.rb:44:in `encode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:31:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/outputs/base.rb:88:in `handle'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/outputs/base.rb:79:in `worker_setup'"], :level=>:error}
…
{:timestamp=>"2015-06-29T06:55:47.300000+0000", :message=>"RabbitMQ connection error: MarchHare::ChannelAlreadyClosed. Will attempt to reconnect in 10 seconds...", :exception=>#<MarchHare::ChannelAlreadyClosed: MarchHare::ChannelAlreadyClosed>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exceptions.rb:121:in `convert_and_reraise'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:965:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:963:in `converting_rjc_exceptions_to_ruby'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/channel.rb:595:in `basic_publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/march_hare-2.5.1-java/lib/march_hare/exchange.rb:77:in `publish'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:40:in `publish_serialized'", "org/jruby/RubyProc.java:271:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-0.1.7/lib/logstash/codecs/json.rb:44:in `encode'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-rabbitmq-0.1.5-java/lib/logstash/outputs/rabbitmq/march_hare.rb:31:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/outputs/base.rb:88:in `handle'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.1-java/lib/logstash/outputs/base.rb:79:in `worker_setup'"], :level=>:error}

**Comment by sombut** [comment]
I found this thread reporting the same issue with me. Thanks you.

https://github.com/logstash-plugins/logstash-output-rabbitmq/issues/10
