### ISSUE TITLE
[1.5.2] Logstash default plugins test failures

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3527]
Finished in 58.7 seconds (files took 4.72 seconds to load)
609 examples, 37 failures

http://build-eu-00.elastic.co/view/LS%201.5/job/Logstash_15_Default_Plugins/173/

Looks related to #3526

**Comment by purbon** [comment]
Also another issue, this time coming from Collectd:

```
) LogStash::Codecs::Collectd Replace nan_value and nan_tag with non-default values should replace a NaN with the specified value and tag 'NaN_encountered'
     Failure/Error: next LogStash::Codecs::Collectd.new({"nan_value" => 1,
     RuntimeError:
       You must specify 'typesdb => ...' in your collectd input (I looked for '/home/jenkins/workspace/Logstash_15_Default_Plugins/vendor/bundle/jruby/1.9/gems/logstash-codec-collectd-1
```

**Comment by purbon** [comment]
@ph @jordansissel there are a couple of lumberjack issues raised here:

```  26) LogStash::Inputs::Lumberjack#processing of events #codecs clone the codec per connection
     Failure/Error: let(:port) { LogStashTest.random_port }
     NameError:
       uninitialized constant LogStashTest
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.1/spec/inputs/lumberjack_spec.rb:13:in `port'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.1/spec/inputs/lumberjack_spec.rb:37:in `config'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.1/spec/inputs/lumberjack_spec.rb:17:in `lumberjack'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.1/spec/inputs/lumberjack_spec.rb:31:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  27) LogStash::Inputs::Lumberjack#register raise no exception
     Failure/Error: let(:certificate) { LogStashTest.certificate }
     NameError:
       uninitialized constant LogStashTest
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.1/spec/inputs/lumberjack_spec.rb:12:in `certificate'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.1/spec/inputs/lumberjack_spec.rb:15:in `config'
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-1.0.1/spec/inputs/lumberjack_spec.rb:21:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

can you guys take a look at it please?

**Comment by purbon** [comment]
The collectd issue is addressed -> https://github.com/logstash-plugins/logstash-codec-collectd/pull/12 @ph review welcome. We would need, as with the geoip filter to release a new gem that actually have the vendored files on it.

**Comment by purbon** [comment]
The long standing failing, and abandonded test suites, for the logstash-filter-checksum has been fixed also fixed at: https://github.com/logstash-plugins/logstash-filter-checksum/pull/4 

@ph reviews welcome.

It would be nice, also for plugins that might be deprecated than when we merge a change, test get updated acordingly :+1:

**Comment by purbon** [comment]
The only pending issue to be fix is ```lumberjack``` waiting for @ph or @jordansissel to jump in. For the rest, all has been addressed and are waiting for reviews.

**Comment by ph** [comment]
The lumberjack issue is a path issue.. The files are correctly requried in the `spec_helper`, but this file is not loaded when running all the test from the logstash distribution.

**Comment by purbon** [comment]
@ph you might need to use require_releative to load this file, so it's actually not an issue with doing the "hacky" all plugins test.

**Comment by ph** [comment]
I am using `require_relative`, but its down inside the `spec_helper`, so I suspect this file is not loaded when you run *test all the plugins* task. 

See https://github.com/logstash-plugins/logstash-input-lumberjack/blob/master/spec/spec_helper.rb#L3

**Comment by purbon** [comment]
Is probably an issue that you should use the require relative in the input test to fetch the spec_helper?

**Comment by ph** [comment]
Not sure I want to do that, it could possibly override the project defaults?

**Comment by purbon** [comment]
not that I'm aware of.

- purbon

**Comment by ph** [comment]
@purbon can you review this https://github.com/logstash-plugins/logstash-input-lumberjack/pull/35 ?

**Comment by purbon** [comment]
done, reported some feedback there.

**Comment by purbon** [comment]
This as of now closed so all test are green. /cc @suyograo
