### ISSUE TITLE
Could not find gem 'logstash-core (= 1.5.1) 

### ISSUE THREAD

**Issue by innovia** [elastic/logstash#3567]
im getting this error (did get the same for 1.5.2)

````log
INFO: [logstash-Logstash-Glide-i-a864007b-4527-13154] bound_address {inet[/0:0:0:0:0:0:0:0:9301]}, publish_address {inet[/10.10.11.91:9301]}
/etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/resolver.rb:328:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'logstash-core (= 1.5.1) ruby' in any of the gem sources listed in your Gemfile or installed on this machine. (Bundler::GemNotFound)
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/resolver.rb:307:in `each'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/resolver.rb:307:in `verify_gemfile_dependencies_are_found!'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/resolver.rb:199:in `start'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/resolver.rb:182:in `resolve'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/definition.rb:192:in `resolve'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/definition.rb:132:in `specs'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/definition.rb:177:in `specs_for'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/definition.rb:166:in `requested_specs'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/environment.rb:18:in `requested_specs'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/runtime.rb:13:in `setup'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler.rb:122:in `setup'
	from /etc/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.9/lib/bundler/setup.rb:18:in `<top (required)>'
	from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Jul 07, 2015 5:24:07 PM org.elasticsearch.discovery.DiscoveryService doStart
````

**Comment by innovia** [comment]
Closing this
Sorry

this was created because im using my own Ruby script for the exec output, which collides with the Jruby of logstash

reverted to using bash script
