### ISSUE TITLE
Log4J input is not working with SocketAppender (Logstash 1.5.2)

### ISSUE THREAD

**Issue by vnyvh** [elastic/logstash#3610]
I am using Logstash 1.5.2 with Elasticsearch. I am trying to read the events from Log4J SocketAppender. Following is my configuration -
Logstash conf -
log4j {
			type => "log4j"
			host => "localhost"
			port => 4560
			add_field => [ "index", "mma-app-log" ]
			add_field => [ "parsing", "success" ]
		 }

Here is my Log4J config -
<socket name="logstashSocket" host="localhost" port="4560">
	<JSONLayout/>
</socket>

Whenever I start Logstash I get following warnings -
io/console not supported; tty will not be manipulated
'[DEPRECATED] use `require 'concurrent'` instead of `require 'concurrent_ruby'`
log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.PoolingHttpClientConnectionManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Logstash startup completed

And when I start my app server, the SocketAppender throws following error -
ERROR Failed to asynchronously log message: org.apache.logging.log4j.core.async.AsyncLoggerConfigHelper$Log4jEventWrapper@7dbfbfd org.apache.logging.log4j.core.appender.AppenderLoggingException: Error writing to TCP:localhost:4560
	at org.apache.logging.log4j.core.net.TcpSocketManager.write(TcpSocketManager.java:134)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.write(OutputStreamManager.java:136)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:110)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:99)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:430)
	at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:121)
	at org.apache.logging.log4j.core.async.AsyncLoggerConfigHelper$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigHelper.java:222)
	at org.apache.logging.log4j.core.async.AsyncLoggerConfigHelper$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigHelper.java:207)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Software caused connection abort: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
	at org.apache.logging.log4j.core.net.TcpSocketManager.write(TcpSocketManager.java:125)
	... 11 more

But if I replace Log4j input with tcp, everything works fine and I do not get any warnings for Logstash.

I am using JDK1.8, Logstash1.5.2, elasticsearch-1.6.0 (all ELK components are downloaded from https://www.elastic.co.

**Comment by purbon** [comment]
As this is a plugin related issue, do you ming reopening this issue https://github.com/logstash-plugins/logstash-input-log4j ? thanks a lot, feel free to just close this one when done.

**Comment by vnyvh** [comment]
Opened the new issue in plugins https://github.com/logstash-plugins/logstash-input-log4j/issues/13
