### ISSUE TITLE
http output gives StoreContext#error_depth error

### ISSUE THREAD

**Issue by wastedepository** [elastic/logstash#3670]
I have Logstash sending simple JSON messages to a test Bottle server I set up, and they work fine. However, when I try to set http output up with a more sophisticated URL as an endpoint, I get this error message 4 times in a row for every log entry that I send to Logstash:

WARNING: unimplemented method called: StoreContext#error_depth

The service gets the JSON message correctly, but it would be nice to remove this error message. I'm using Logstash 1.5.0.

My http filter:

http {
    headers => ["Authorization", "(the appropriate authorization)",
                "Content-Type", "application/json"]
    http_method => "post"
    url => "(the appropriate URL)"
}

**Comment by ph** [comment]
@wastedepository This error look related to this one https://github.com/elastic/logstash/issues/1612
And since you are running an older version of logstash 1.5.0, I would try with the latest logstash release (1.5.3), this release contains a newer version of `jruby-openssl` that should hide that message.

**Comment by wastedepository** [comment]
Upgrading to 1.5.3 removes the error, but now I get this single error instead:

*WARNING: unimplemented method called: Store#add_path*

Also, it says I have an untrusted certificate because:

*"What you think it's for: api.somewebsite (port 443)
What it's actually for: *.somewebsite"*

Pressing "P" to store a permanent exception causes an error:

*stty: standard input: Inappropriate ioctl for device*

... and an unhandled exception error which mentions this exception (the ... is used to simplify the path):

*:exception=>#<OpenSSL::SSL::SSLError: writer side was already closed.>, :stacktrace=>["org/jruby/ext/openssl/SSLSocket.java:195:in `connect_nonblock'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/connection.rb:413:in `do_secure'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/connection.rb:393:in `secure'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/agent.rb:449:in `connect'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/agent.rb:283:in `execute'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-output-http-1.0.0/lib/logstash/outputs/http.rb:126:in `receive'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):168:in `output_func'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:244:in `outputworker'", ".../logstash-1.5.3/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.3-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn*

(I should mention that I'm on Fedora at this point, and these warning messages seem to show up regarless of which terminal program I try.)

This series of warnings does go away temporarily when I use P for permanent, but it shows up again next time I restart Logstash.
