### ISSUE TITLE
logstash crashes with java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by serialdoom** [elastic/logstash#3711]
after running for a couple of days (just under 10 mil events) my logstash crashed with this in `logstash.err`

```
Aug 09, 2015 12:01:20 PM org.elasticsearch.monitor.jvm.JvmMonitorService$JvmMonitor monitorLongGc
WARNING: [logstash-m002-24984-11620] [gc][young][159430][32811] duration [1s], collections [1]/[3.1s], total [1s]/[4.7m], memory [478.6mb]->[400.3mb]/[483.3mb], all_pools {[young] [133.1mb]->[66.7mb]/[133.1mb]}{[survivor] [15.7mb]->[0b]/[16.6mb]}{[old] [329.7mb]->[333.6mb]/[333.6mb]}
Exception in thread "<udp" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread ">output" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "Ruby-0-Thread-13: /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:144" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

im running version `logstash 1.5.2` and my configuration file is this

```
input {
    udp {
        port => 25826
            buffer_size => 1452
            codec => collectd { }
    }
    tcp {
        port => 25926
            type => "syslog"
            codec => "json"
    }
}
output {
    elasticsearch {
        host => "192.168.250.20"
    }
    stdout { }
}
```

I think thats the second time i've observed that, but i got no evidence to support that.

**Comment by suyograo** [comment]
@serialdoom what's the output of `java -version` and can you provide a sample event you are sending through LS?

**Comment by ph** [comment]
We had another report of this error in the main repo https://github.com/elastic/logstash/issues/3811
I am leaving the other open until we get more details.

**Comment by ayashjorden** [comment]
Hi,
I'm experiencing a similar behaviour with the following configuration:
```javascript
input {
    lumberjack {
        port            => 5230
        ssl_certificate => '/etc/pki/logstash-forwarder.crt'
        ssl_key         => '/etc/pki/logstash-forwarder.key'
    }
}
filter {
    if [type] ==  "email_sending"{
        csv {
            columns => [LIST_OF_COLUMNS]
            remove_field => ["message"]
        }
        if [tracking_params] {
            ruby {
                init => "require 'zlib'"
                code => "event['message_id_int'] = Zlib::crc32(event['tracking_params'])"
            }
            kv {
                source => "tracking_params"
                field_split => "&"
            }
        }
        if [event_date] {
            date {
                match => ["event_date", "YYYY-MM-dd HH:mm:ss"]
            }
            ruby {
                init => "require 'time'"
                code => "event['event_date_ms'] = (Time.parse(event['event_date']).to_f * 1000).to_i"
                remove_field => ['event_date']
            }
        }
        mutate {
            add_field => { "http_message" => 'BUILD_JSON_PAYLOAD_FROM_FIELDS' }
        }
    }
}
output {
    if [@metadata][type] in [ "email_tracking", "email_sending" ]{
        http {
            url => "API_URL"
            content_type => "application/x-www-form-urlencoded"
            http_method  => "post"
            message => "%{http_message}"
            ssl_certificate_validation => false
            format => "message"
            workers => 5
        }
    }
}
```

And getting exceptions:
```
Exception in thread "<udp" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread ">http.4" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread ">http.0" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
```

Java version:
```
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

Any Idea?

**Comment by serialdoom** [comment]
here is my `java -version` output

```
java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```

The events im sending are default `collectd` items

**Comment by Enteee** [comment]
similar behaviour here:
```
Exception in thread ">output" java.lang.UnsupportedOperationException
        at java.lang.Thread.stop(Thread.java:869)
        at org.jruby.RubyThread.exceptionRaised(RubyThread.java:1221)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:112)
        at java.lang.Thread.run(Thread.java:745)
```
with:
* logstash-1.5.4
* java

 ```
$ java -version
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
```
* logstash config:
```
input {
    pipe {
        codec => "json"
        command => "tshark -i enp0s9 -q -lT pdml $(/vagrant/sys/pcap_mac_filter.sh) | \
        /vagrant/flowworker.py -i enp0s9"
    }
    #stdin {}
}

filter{
    ruby {
        code => "event['env.hostname'] = data = File.read('/etc/hostname').strip()"
    }
    geoip {
        source => "ip.src"
        target => "ip.src.geoip" 
    }
    geoip {
        source => "ip.dst"
        target => "ip.dst.geoip" 
    }
}

output {
    elasticsearch {
        cluster => "EtherFlows"
        protocol => "transport"
        template => "/vagrant/etc/template.js"
    }
}
```

**Comment by RichJackson** [comment]
I think it might be a memory related issue. I saw this issue using the JDBC input plugin and a large table. It seems to have gone away after reducing the jdbc_page_size input parameter from 5000 to 500.

**Comment by fedelemantuano** [comment]
I have the same issue. In my case, when I try to index a huge document, a thread of logstash dead but the process no. As mentioned by @RichJackson is a memory issue.

I use redis like buffer and [this nagios plugin](https://github.com/fedelemantuano/nagios-plugin-redis) to monitoring the queues.

**Comment by rsltrifork** [comment]
+1

**Comment by suyograo** [comment]
Please reopen a new issue if this is still happening.
