### ISSUE TITLE
logstash-1.5.0 can't connect to elasticsearch through http even though curl can

### ISSUE THREAD

**Issue by drewr** [elastic/logstash#3713]
For some reason logstash has stopped talking to ES:

```
2015-08-10 19:36:56.705497500 {:timestamp=>"2015-08-10T19:36:56.705000+0000", :message=>"Create client to elasticsearch server on es00.proxyr.web.use1:", :level=>:info}
2015-08-10 19:37:02.995354500 LoadError: load error: manticore -- java.lang.NoSuchFieldError: INSTANCE
2015-08-10 19:37:02.995356500         require at org/jruby/RubyKernel.java:1071
2015-08-10 19:37:02.995357500         require at /usr/local/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
2015-08-10 19:37:02.995358500          (root) at /usr/local/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manti
core.rb:1
2015-08-10 19:37:02.995571500         require at org/jruby/RubyKernel.java:1071
2015-08-10 19:37:02.995572500         require at /usr/local/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
2015-08-10 19:37:02.995574500          (root) at /usr/local/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch/pr
otocol.rb:1
2015-08-10 19:37:02.995716500      initialize at /usr/local/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch/pr
otocol.rb:58
2015-08-10 19:37:02.995718500             map at org/jruby/RubyArray.java:2412
2015-08-10 19:37:02.995719500        register at /usr/local/logstash/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb
:341
2015-08-10 19:37:02.995848500            each at org/jruby/RubyArray.java:1613
[...]
```

Even though curl can from the same machine:

```
% curl -s es00.proxyr.web.use1:9200
{
  "status" : 200,
  "name" : "es00",
  "cluster_name" : "web.proxyr",
  "version" : {
    "number" : "1.6.0",
    "build_hash" : "cdd3ac4dde4f69524ec0a14de3828cb95bbb86d0",
    "build_timestamp" : "2015-06-09T13:36:34Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}
```

The output part of the config looks like:

```
  elasticsearch {
    protocol   => "http"
    index_type => "log"
    index      => "download-%{+YYYY.MM}"
    host       => "es00.proxyr.web.use1"
    port       => "9200"
  }
```

Anything I'm overlooking? It's like this across five of six of our proxies.

**Comment by jordansissel** [comment]
What build of Logstash 1.5.0 is this? Can you try Logstash 1.5.3? Are you using the deb/rpm or tarball?

**Comment by drewr** [comment]
We bake it with the plugins we need, publish it to S3, and that gets extracted by config management. I can try a newer version.

More curious why this magically started happening.

**Comment by jordansissel** [comment]
Yeah not sure. We would've caught this in jenkins/testing if this were affecting others. So weird. Can you show me how you bake it?

**Comment by drewr** [comment]
I'm mistaken. These machines just install stock logstash and do a bin/plugin install of a custom plugin.

**Comment by jordansissel** [comment]
If I try this with stock Logstash 1.5.0 -

```
% bin/logstash -e 'output {  elasticsearch {
    protocol   => "http"
    index_type => "log"
    index      => "download-%{+YYYY.MM}"
    host       => "es00.proxyr.web.use1"
    port       => "9200"
  }
}' 
asdf
You are using a deprecated config setting "index_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future.  If you have any 
questions about this, please visit the #logstash channel on freenode irc. {:name=>"index_type", :plugin=><LogStash::Outputs::ElasticSearch --->, :level=>:warn}
Failed to install template: es00.proxyr.web.use1: unknown error {:level=>:error}
Logstash startup completed
Got error to send bulk of actions to elasticsearch server at es00.proxyr.web.use1 : es00.proxyr.web.use1 {:level=>:error}
Failed to flush outgoing items {:outgoing_count=>1, :exception=>#<Manticore::ResolutionFailure: es00.proxyr.web.use1>, :backtrace=>["/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:35:in `initialize'", "org/jruby/RubyProc.java:271:in `call'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:61:in `call'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:225:in `call_once'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/manticore-0.4.1-java/lib/manticore/response.rb:128:in `code'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:50:in `perform_request'", "org/jruby/RubyProc.java:271:in `call'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/transport/http/manticore.rb:33:in `perform_request'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.7/lib/elasticsearch/transport/client.rb:115:in `perform_request'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.7/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch/protocol.rb:100:in `bulk'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash/outputs/elasticsearch.rb:437:in `submit'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-0.2.4-java/lib/logstash
/outputs/elasticsearch.rb:462:in `flush'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1341:in `eac
h'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:216:in `buffer_flush'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/stud-0.0.19/li
b/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1507:in `loop'", "/home/jls/build/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/stud-0.0.19/lib/stud/buffer.rb:110:in `buffer
_initialize'"], :level=>:warn}

```

The errors I get are indications that it cannot find Elasticsearch (which makes sense since I don't have your internal DNS stuff on my laptop).

Things work for me on 1.5.0 :\

**Comment by drewr** [comment]
So that would confirm that it's something with logstash (more specifically manticore) and not HTTP (which seems to work fine).

I just don't get why bits that didn't change would stop working. Even with the current AWS problems.

**Comment by jordansissel** [comment]
@drewr what I Meant was the errors I showed above were because the 'host' I used from your example doesn't exist on my laptop.  I will show you the same run with a valid elasticsearch host (again, environmental, for my laptop) - one sec.

**Comment by jordansissel** [comment]
Same as above but using localhost for me:

```
% bin/logstash -e 'output {  elasticsearch {
    protocol   => "http"
    index_type => "log"
    index      => "download-%{+YYYY.MM}"
    host       => "localhost"           
    port       => "9200"
  }
}'
You are using a deprecated config setting "index_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future.  If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"index_type", :plugin=><LogStash::Outputs::ElasticSearch --->, :level=>:warn}
HelloLogstash startup completed

World
Logstash shutdown completed
⓿ crinkle(~/build/logstash-1.5.0) 
% curl localhost:9200/download-*/_count
{"count":2,"_shards":{"total":5,"successful":5,"failed":0}}
```

1.5.0 working fine for me with your config.

**Comment by jordansissel** [comment]
> So that would confirm that it's something with logstash (more specifically manticore) and not HTTP (which seems to work fine).

@drewr yeah, sorta, in a way. Logstash 1.5.0 works fine for me. The specific error you get indicates that the manticore library is failing to be loaded.

How are you running Logstash? Can you show me the command line? Also, what's the output of `/usr/local/logstash/logstash-1.5.0/bin/logstash version` ?

**Comment by drewr** [comment]
So I tried logstash-1.5.3 without our plugin and it works.

I can accept that our plugin could mess with manticore (it was a bear to get it to work in the first place) but the bits on these machines didn't change.

**Comment by drewr** [comment]
I was able to check through and find that the bits actually did change, unsurprisingly. Somehow a bogus plugin build was generated, published, and deployed (a more concerning issue). Anyway, Logstash couldn't talk to ES because manticore wasn't loading. manticore wasn't loading because a conflicting httpclient snuck in the filter's jar (similar to cheald/manticore#2).

**Comment by jordansissel** [comment]
@drewr ouch, that's a pretty sneaky bug. Good research!

**Comment by purbon** [comment]
@jordansissel @drewr @andrewvc can we setup somehow of test to actually validate this in our CI?

**Comment by andrewvc** [comment]
@purbon That is a pretty tricky test to setup and provide positive feedback for. [Classloader issues are hard](https://github.com/cheald/manticore/issues/2). 

I don't really have any ideas for creating good tests around this other than having a mega pipeline test where we load every official plugin and run a pipeline with all of them setup just to see if something blows up when they all try to play together.
