### ISSUE TITLE
Jenkins: Build failing in statsd plugin

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#3838]
Failures:

```

  1) LogStash::Outputs::Statsd#send count metrics should receive data send to the server
     Failure/Error: expect(@server.received).to include("logstash.spec.foo.bar:0.1|c")
       expected [] to include "logstash.spec.foo.bar:0.1|c"
     # ./vendor/bundle/jruby/1.9/gems/logstash-output-statsd-1.1.0/spec/outputs/statsd_spec.rb:41:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

**Comment by untergeek** [comment]
Hmmm.  This sounds like a case of Jenkins is WRONG, somehow:

```
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}

LogStash::Outputs::Statsd
  #send
    count metrics
      should receive data send to the server
  registration and teardown
    should register without errors

Finished in 0.089 seconds (files took 2.54 seconds to load)
2 examples, 0 failures

Randomized with seed 59690
```

It works flawlessly on my local box with JRuby 1.7.19.

**Comment by untergeek** [comment]
![screenshot 2015-09-02 16 33 43](https://cloud.githubusercontent.com/assets/1020383/9646417/9f9f355e-5190-11e5-99f4-759576266f1f.png)

This is from http://build-eu-00.elasticsearch.org/view/LS%20Plugins/view/LS%20Outputs/job/logstash-plugin-output-statsd-unit/

Where is this failure coming from?

**Comment by suyograo** [comment]
weird, now its passing on master... some jobs had failed http://build-eu-00.elastic.co/view/LS%20Master/job/Logstash_Master_Default_Plugins/435/console
