### ISSUE TITLE
xml filter: "target" setting required

### ISSUE THREAD

**Issue by jacobweber** [elastic/logstash#3843]
https://www.elastic.co/guide/en/logstash/master/plugins-filters-xml.html#plugins-filters-xml-target

The "target" setting should be listed as required, and probably validated. If I omit it, I get an error:
```
Trouble parsing xml with XmlSimple {:source=>"message", :value=>"<foo>bar</foo>", :exception=>#<NoMethodError: undefined method `start_with?' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/event.rb:140:in `[]='", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-xml-1.0.0/lib/logstash/filters/xml.rb:129:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:163:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:160:in `multi_filter'", "(eval):382:in `cond_func_7'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):371:in `cond_func_7'", "(eval):234:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:157:in `start_filters'"], :level=>:warn}
```

My filter is:
```
xml {
	source => message
}
```

and my XML is:
```
<foo>bar</foo>
```

Using LogStash 1.5.4.

**Comment by magnusbaeck** [comment]
I suggest we close this issue as it duplicates https://github.com/logstash-plugins/logstash-filter-xml/pull/8 (document that the option is required) and https://github.com/logstash-plugins/logstash-filter-xml/issues/9 (fix the filter so it doesn't crash when the option isn't set).

**Comment by suyograo** [comment]
Dup of https://github.com/logstash-plugins/logstash-filter-xml/issues/9
