### ISSUE TITLE
logstash 1.5.4 hipchat output plugin is not working because of SSL handshake failures

### ISSUE THREAD

**Issue by xtimmu** [elastic/logstash#3850]
Log file fills up with error messages like this:

```
{:timestamp=>"2015-09-03T10:42:59.211000+0300", :message=>"Unhandled exception", :request=><FTW::Request(@13710) @headers=FTW::HTTP::Headers <{"host"=>"api.hipchat.com", "connection"=>"keep-alive", "content-type"=>"application/x-www-form-urlencoded", "content-length"=>2365}> @method="POST" @body="room_id=ekoolErrors&from=Live&color=red&notify=0&message=%3Ccode%3EServer%3A+e1runner+Log%3A+%2Fopt%2Frunner%2Flogs%2FidnetworkErrorLog.log+Message%3A+ERROR+%7C+2015-09-03+04%3A16%3A21.005+%7C+IdnetworkDataSynchronizer.java+%7C+79+%7C+ex%0Aee.ekool.idnetwork.base.IdnetServiceException%0A%09at+ee.ekool.idnetwork.IdnetService.getEvents%28IdnetService.java%3A51%29+%7E%5Bidnet-service-1.0.14083.jar%3A%3F%5D%0A%09at+ee.ekool.util.IdnetworkDataSynchronizer.updateEvents%28IdnetworkDataSynchronizer.java%3A54%29+%5Bclasses%2F%3A%3F%5D%0A%09at+sun.reflect.GeneratedMethodAccessor784.invoke%28Unknown+Source%29+%7E%5B%3F%3A%3F%5D%0A%09at+sun.reflect.DelegatingMethodAccessorImpl.invoke%28DelegatingMethodAccessorImpl.java%3A43%29+%7E%5B%3F%3A1.8.0_40%5D%0A%09at+java.lang.reflect.Method.invoke%28Method.java%3A497%29+%7E%5B%3F%3A1.8.0_40%5D%0A%09at+org.springframework.util.MethodInvoker.invoke%28MethodInvoker.java%3A273%29+%5Borg.springframework.core-3.0.5.RELEASE.jar%3A3.0.5.RELEASE%5D%0A%09at+org.springframework.scheduling.support.MethodInvokingRunnable.run%28MethodInvokingRunnable.java%3A65%29+%5Borg.springframework.context-3.0.5.RELEASE.jar%3A3.0.5.RELEASE%5D%0A%09at+org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run%28DelegatingErrorHandlingRunnable.java%3A51%29+%5Borg.springframework.context-3.0.5.RELEASE.jar%3A3.0.5.RELEASE%5D%0A%09at+org.springframework.scheduling.concurrent.ReschedulingRunnable.run%28ReschedulingRunnable.java%3A81%29+%5Borg.springframework.context-3.0.5.RELEASE.jar%3A3.0.5.RELEASE%5D%0A%09at+java.util.concurrent.Executors%24RunnableAdapter.call%28Executors.java%3A511%29+%5B%3F%3A1.8.0_40%5D%0A%09at+java.util.concurrent.FutureTask.run%28FutureTask.java%3A266%29+%5B%3F%3A1.8.0_40%5D%0A%09at+java.util.concurrent.ScheduledThreadPoolExecutor%24ScheduledFutureTask.access%24201%28ScheduledThreadPoolExecutor.java%3A180%29+%5B%3F%3A1.8.0_40%5D%0A%09at+java.util.concurrent.ScheduledThreadPoolExecutor%24ScheduledFutureTask.run%28ScheduledThreadPoolExecutor.java%3A293%29+%5B%3F%3A1.8.0_40%5D%0A%09at+java.util.concurrent.ThreadPoolExecutor.runWorker%28ThreadPoolExecutor.java%3A1142%29+%5B%3F%3A1.8.0_40%5D%0A%09at+java.util.concurrent.ThreadPoolExecutor%24Worker.run%28ThreadPoolExecutor.java%3A617%29+%5B%3F%3A1.8.0_40%5D%0A%09at+java.lang.Thread.run%28Thread.java%3A745%29+%5B%3F%3A1.8.0_40%5D%3C%2Fcode%3E" @logger=#<Cabin::Channel:0x71f2be75 @metrics=#<Cabin::Metrics:0x65b56327 @metrics_lock=#<Mutex:0x7118c306>, @metrics={}, @channel=#<Cabin::Channel:0x71f2be75 ...>>, @subscriber_lock=#<Mutex:0x511ba365>, @level=:info, @subscribers={}, @data={}> @request_uri="/v1/rooms/message?auth_token=575b884b90cbd1e7768b3bf6e0981c" @version=1.1 @port=443 @protocol="https" >, :response=>nil, :exception=>#<OpenSSL::SSL::SSLError: Received fatal alert: handshake_failure>, :stacktrace=>["org/jruby/ext/openssl/SSLSocket.java:195:in `connect_nonblock'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/connection.rb:413:in `do_secure'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/connection.rb:393:in `secure'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/agent.rb:449:in `connect'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/ftw-0.0.44/lib/ftw/agent.rb:283:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-hipchat-1.0.0/lib/logstash/outputs/hipchat.rb:60:in `receive'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):234:in `output_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}
```

This is on debian 7 (wheezy).

java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b26)
Java HotSpot(TM) 64-Bit Server VM (build 25.40-b25, mixed mode

I assume it's similar to all the other SSL errors going, like https://github.com/elastic/logstash/issues/3657 etc..

**Comment by purbon** [comment]
HI, @xtimmu thanks a lot for your feedback, could you reopen this issue in the hipchat output repo (), nowadays each one has their own lifecycle in his own house so we're trying to keep bugs close to their project :+1: 

Thanks a lot,

PD: feel free to open the bug there yourself and close this one when done!

**Comment by xtimmu** [comment]
Hi! Will do.. Could you point me in the right direction, where the repo is located?

**Comment by purbon** [comment]
Oh, I forgot the link apologies! https://github.com/logstash-plugins/logstash-output-hipchat here you've!

**Comment by purbon** [comment]
Closing this issue as the one in the plugin got open.
