### ISSUE TITLE
Default plugins integration test breaks in 2.0 branch

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#3946]
From: http://build-eu-00.elastic.co/view/LS%202.0/job/Logstash_Default_Plugins_20/228/console

```
...127.0.0.1 - - [21/Sep/2015:07:31:02 CEST] "HEAD /good HTTP/1.1" 200 0
- -> /good
.....................................................................................................................................................................................................................................................................................................................................................................

Failures:

  1) LogStash::Filters::GeoIP returned object identities should dup the objects
     Failure/Error: let(:geo_data) { plugin.get_geo_data_for_ip("8.8.8.8") }
     NoMethodError:
       undefined method `city' for nil:NilClass
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-1.1.1/lib/logstash/filters/geoip.rb:187:in `get_geo_data_for_ip'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-1.1.1/spec/filters/geoip_spec.rb:228:in `geo_data'
     # ./vendor/bundle/jruby/1.9/gems/logstash-filter-geoip-1.1.1/spec/filters/geoip_spec.rb:237:in `(root)'
     # ./rakelib/test.rake:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
```

**Comment by purbon** [comment]
After merging in nearly all the new plugins, the 2.0 test now breaks in some cases and hangs in others.

In my local laptop, running

```
purbon-elastic% bin/rspec 
[2015-09-24 12:37:41.768]  WARN -- Concurrent: [DEPRECATED] Java 7 is deprecated, please use Java 8.
Java 7 support is only best effort, it may not work. It will be removed in next release (1.0).
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
..........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^C
Exiting... Interrupt again to exit immediately.
``` 
hangs

while running:

```
purbon-elastic% rake test:core
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.........................F................................................................................................................................................................................................................................................................................................................................................................FF................................................................................................................................................................................................................................................................................................................................................F.................................................................F.......................................................................................................................

Failures:

  1) LogStash::Filters::Base should provide class public API
     Failure/Error: expect(subject).to respond_to(method)
       expected <LogStash::Filters::Base periodic_flush=>false> to respond to :close
     # ./spec/filters/base_spec.rb:28:in `(root)'
     # ./spec/filters/base_spec.rb:27:in `(root)'
     # ./rakelib/test.rake:24:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  2) LogStash::Pipeline close output close should call close of output without output-workers
     Failure/Error: expect(pipeline.outputs.first.worker_plugins.first.num_closes ).to eq(1)
       
       expected: 1
            got: 0
       
       (compared using ==)
     # ./spec/core/pipeline_spec.rb:103:in `(root)'
     # ./rakelib/test.rake:24:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  3) LogStash::Pipeline close output close should call output close correctly with output workers
     Failure/Error: expect(plugin.num_closes ).to eq(1)
       
       expected: 1
            got: 0
       
       (compared using ==)
     # ./spec/core/pipeline_spec.rb:113:in `(root)'
     # ./spec/core/pipeline_spec.rb:112:in `(root)'
     # ./rakelib/test.rake:24:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  4) LogStash::Event using normal hash input behaves like all event tests #sprintf should not strip last character
     Failure/Error: expect(subject.sprintf("%{type}%{message}|")).to eq("sprintfhello world|")
       
       expected: "sprintfhello world|"
            got: "sprintfhello world"
       
       (compared using ==)
     Shared Example Group: "all event tests" called from ./spec/core/event_spec.rb:487
     # ./spec/core/event_spec.rb:108:in `(root)'
     # ./rakelib/test.rake:24:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

  5) LogStash::Event using hash input from deserialized json behaves like all event tests #sprintf should not strip last character
     Failure/Error: expect(subject.sprintf("%{type}%{message}|")).to eq("sprintfhello world|")
       
       expected: "sprintfhello world|"
            got: "sprintfhello world"
       
       (compared using ==)
     Shared Example Group: "all event tests" called from ./spec/core/event_spec.rb:495
     # ./spec/core/event_spec.rb:108:in `(root)'
     # ./rakelib/test.rake:24:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'

Finished in 6.19 seconds (files took 3.13 seconds to load)
902 examples, 5 failures

Failed examples:

rspec ./spec/filters/base_spec.rb:26 # LogStash::Filters::Base should provide class public API
rspec ./spec/core/pipeline_spec.rb:97 # LogStash::Pipeline close output close should call close of output without output-workers
rspec ./spec/core/pipeline_spec.rb:106 # LogStash::Pipeline close output close should call output close correctly with output workers
rspec ./spec/core/event_spec.rb:107 # LogStash::Event using normal hash input behaves like all event tests #sprintf should not strip last character
rspec ./spec/core/event_spec.rb:107 # LogStash::Event using hash input from deserialized json behaves like all event tests #sprintf should not strip last character

Randomized with seed 12381
``` 
breaks

**Comment by purbon** [comment]
removing

```
describe "conditionals in output" do
  extend ConditionalFanciness

  describe "simple" do
    config <<-CONFIG
      input {
        generator {
          message => '{"foo":{"bar"},"baz": "quux"}'
          count => 1
        }
      }
      output {
        if [foo] == "bar" {
          stdout { }
        }
      }
    CONFIG

    agent do
      #LOGSTASH-2288, should not fail raising an exception
    end
  end
end
``` 
from ```spec/core/conditional_spec.rb``` makes ```bin/rspec``` run all test as expected. but ``` rake test:core``` is still failing,

**Comment by purbon** [comment]
Fixed with https://github.com/elastic/logstash/pull/3962
