### ISSUE TITLE
worker thread pegs a core in Encoder.encodeLoop and processing halts

### ISSUE THREAD

**Issue by jstangroome** [elastic/logstash#3989]
logstash 1.5.4 (from official apt package) on Ubuntu Trusty 14.04.1 with Oracle JRE 1.8.0_60-b27.

Using a lumberjack input 1.0.5

`|worker` thread pegs a single core. I took three stack dumps a few seconds apart and found these two different stacks for the worker thread:

```
"|worker" #33 daemon prio=5 os_prio=0 tid=0x000000000107a800 nid=0x788d runnable [0x00007f7c2bbfa000]
   java.lang.Thread.State: RUNNABLE
  at java.nio.charset.CoderResult$Cache.access$200(CoderResult.java:194)
  at java.nio.charset.CoderResult.malformedForLength(CoderResult.java:236)
  at sun.nio.cs.Surrogate$Parser.parse(Surrogate.java:242)
  at sun.nio.cs.US_ASCII$Encoder.encodeArrayLoop(US_ASCII.java:192)
  at sun.nio.cs.US_ASCII$Encoder.encodeLoop(US_ASCII.java:231)
 ... truncated ... same as next stack from here
```

and

```
"|worker" #33 daemon prio=5 os_prio=0 tid=0x000000000107a800 nid=0x788d runnable [0x00007f7c2bbfa000]
   java.lang.Thread.State: RUNNABLE
  at sun.nio.cs.US_ASCII$Encoder.encodeLoop(US_ASCII.java:231)
  at java.nio.charset.CharsetEncoder.encode(CharsetEncoder.java:579)
  at org.jruby.util.encoding.CharsetTranscoder$TranscoderEngine.encode(CharsetTranscoder.java:660)
  at org.jruby.util.encoding.CharsetTranscoder$TranscoderEngine.transcode(CharsetTranscoder.java:510)
  at org.jruby.util.encoding.CharsetTranscoder.primitiveConvert(CharsetTranscoder.java:333)
  at org.jruby.util.encoding.CharsetTranscoder.transcode(CharsetTranscoder.java:294)
  at org.jruby.util.encoding.CharsetTranscoder.transcode(CharsetTranscoder.java:236)
  at org.jruby.util.io.EncodingUtils.transcodeLoop(EncodingUtils.java:874)
  at org.jruby.util.io.EncodingUtils.strTranscode0(EncodingUtils.java:802)
  at org.jruby.util.io.EncodingUtils.strTranscode(EncodingUtils.java:737)
  at org.jruby.util.io.EncodingUtils.strEncode(EncodingUtils.java:708)
  at org.jruby.RubyString.encode(RubyString.java:7636)
  at org.jruby.RubyString$INVOKER$i$encode.call(RubyString$INVOKER$i$encode.gen)
  at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:236)
  at org.jruby.ast.CallThreeArgNode.interpret(CallThreeArgNode.java:61)
  at org.jruby.ast.AttrAssignTwoArgNode.interpret(AttrAssignTwoArgNode.java:36)
  at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
  at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
  at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
  at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
  at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
  at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
  at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
  at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
  at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
  at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
  at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
  at org.jruby.runtime.Block.call(Block.java:101)
  at org.jruby.RubyProc.call(RubyProc.java:290)
  at org.jruby.RubyProc.call19(RubyProc.java:271)
  at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
  at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
  at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
  at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
  at rubyjit.LogStash::Filters::Ruby$$filter_34fb026be97a49ada447ec516c307c145131e3f11028566121.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-1.0.0/lib/logstash/filters/ruby.rb:38)
  at rubyjit.LogStash::Filters::Ruby$$filter_34fb026be97a49ada447ec516c307c145131e3f11028566121.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-1.0.0/lib/logstash/filters/ruby.rb:37)
  at rubyjit.LogStash::Filters::Ruby$$filter_34fb026be97a49ada447ec516c307c145131e3f11028566121.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-ruby-1.0.0/lib/logstash/filters/ruby.rb)
  at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:201)
  at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:336)
  at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:179)
  at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)
  at rubyjit.LogStash::Filters::Base$$multi_filter_709707e674cf07ceb9bf9dc86e16f69c57fedcfd1028566121.block_0$RUBY$__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:163)
  at rubyjit$LogStash::Filters::Base$$multi_filter_709707e674cf07ceb9bf9dc86e16f69c57fedcfd1028566121$block_0$RUBY$__file__.call(rubyjit$LogStash::Filters::Base$$multi_filter_709707e674cf07ceb9bf9dc86e16f69c57fedcfd1028566121$block_0$RUBY$__file__)
  at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
  at org.jruby.runtime.Block.yield(Block.java:142)
  at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
  at org.jruby.RubyArray.each(RubyArray.java:1613)
  at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
  at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
  at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
  at rubyjit.LogStash::Filters::Base$$multi_filter_709707e674cf07ceb9bf9dc86e16f69c57fedcfd1028566121.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb:160)
  at rubyjit.LogStash::Filters::Base$$multi_filter_709707e674cf07ceb9bf9dc86e16f69c57fedcfd1028566121.__file__(/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.4-java/lib/logstash/filters/base.rb)
  at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
  at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
  at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
  at rubyjit.LogStash::Pipeline$$cond_func_3755_e8899e4409f7e1b5ccfbcbff032b4ace15d524861028566121.block_0$RUBY$__file__((eval):65387)
  at rubyjit$LogStash::Pipeline$$cond_func_3755_e8899e4409f7e1b5ccfbcbff032b4ace15d524861028566121$block_0$RUBY$__file__.call(rubyjit$LogStash::Pipeline$$cond_func_3755_e8899e4409f7e1b5ccfbcbff032b4ace15d524861028566121$block_0$RUBY$__file__)
  at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
  at org.jruby.runtime.Block.yield(Block.java:142)
  at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
  at org.jruby.RubyArray.each(RubyArray.java:1613)
  at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
  at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
  at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
  at rubyjit.LogStash::Pipeline$$cond_func_3755_e8899e4409f7e1b5ccfbcbff032b4ace15d524861028566121.__file__((eval):65384)
  at rubyjit.LogStash::Pipeline$$cond_func_3755_e8899e4409f7e1b5ccfbcbff032b4ace15d524861028566121.__file__((eval))
  at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
  at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
  at rubyjit.LogStash::Pipeline$$cond_func_3754_0292750717c297520892c1ee33145c0e97436e2d1028566121.block_0$RUBY$__file__((eval):65402)
  at rubyjit$LogStash::Pipeline$$cond_func_3754_0292750717c297520892c1ee33145c0e97436e2d1028566121$block_0$RUBY$__file__.call(rubyjit$LogStash::Pipeline$$cond_func_3754_0292750717c297520892c1ee33145c0e97436e2d1028566121$block_0$RUBY$__file__)
  at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
  at org.jruby.runtime.Block.yield(Block.java:142)
  at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
  at org.jruby.RubyArray.each(RubyArray.java:1613)
  at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
  at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
  at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
  at rubyjit.LogStash::Pipeline$$cond_func_3754_0292750717c297520892c1ee33145c0e97436e2d1028566121.__file__((eval):65399)
  at rubyjit.LogStash::Pipeline$$cond_func_3754_0292750717c297520892c1ee33145c0e97436e2d1028566121.__file__((eval))
  at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
  at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
  at rubyjit.LogStash::Pipeline$$filter_func_6f653d35875fd7a1ca5c1984ba5ff6c56cfc87d41028566121.__file__((eval):5960)
  at rubyjit.LogStash::Pipeline$$filter_func_6f653d35875fd7a1ca5c1984ba5ff6c56cfc87d41028566121.__file__((eval))
  at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
  at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
  at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
  at org.jruby.ast.CallNoArgBlockNode.interpret(CallNoArgBlockNode.java:60)
  at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
  at org.jruby.ast.WhenOneArgNode.whenSlowTest(WhenOneArgNode.java:36)
  at org.jruby.ast.WhenOneArgNode.when(WhenOneArgNode.java:46)
  at org.jruby.ast.CaseNode.interpret(CaseNode.java:133)
  at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
  at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
  at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
  at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
  at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
  at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
  at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
  at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
  at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
  at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
  at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:139)
  at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:187)
  at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)
  at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)
  at org.jruby.ast.VCallNode.interpret(VCallNode.java:88)
  at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
  at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
  at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
  at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
  at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
  at org.jruby.runtime.Block.call(Block.java:101)
  at org.jruby.RubyProc.call(RubyProc.java:290)
  at org.jruby.RubyProc.call(RubyProc.java:228)
  at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
  at java.lang.Thread.run(Thread.java:745)
```

**Comment by jstangroome** [comment]
Has similarities with https://github.com/jruby/jruby/issues/2856 and https://github.com/jruby/jruby/issues/1713

**Comment by guyboertje** [comment]
@jstangroome - am I correct to presume your source data is us-ascii?

**Comment by jstangroome** [comment]
@guyboertje We have this snippet in a Ruby filter:

```
gz = Zlib::GzipReader.new(StringIO.new(Base64.decode64(event['extracted_message'])))
event['message'] = gz.read
event['message'] = event['message'].encode('US-ASCII', 'utf-8', :invalid => :replace, :undef => :replace, :replace => '')
```

I believe this means we are attempting to convert from utf-8 to US-ASCII.

We've have recently changed from Open JRE 1.7 to Oracle JRE 1.8.

**Comment by guyboertje** [comment]
@jstangroome - I find this odd, because I know LS goes to quite lengths to ensure the events generated are using utf8 by encoding in the input as early as possible.  I don't get why one would want some strings in the event object values to be utf8 and some in us-ascii, but I have only been on the LS team for 3 months.

I'm not sure whether you tried this but I think it is more efficient to store the message value once e.g.
```ruby
gz = Zlib::GzipReader.new(StringIO.new(Base64.decode64(event['extracted_message'])))
unzipped = gz.read
event['message'] = unzipped.encode('US-ASCII', 'utf-8', :invalid => :replace, :undef => :replace, :replace => '')
```
Also, you can test the encoding of the unzipped string like so:
```ruby
event['message_encoding'] = unzipped.encoding.to_s
```
Are you able to modify your config?

**Comment by ph** [comment]
@jstangroome Any specific reasons why you want `us-ascii` ? Most of the output of logstash expect utf-8 strings, what is the original encoding of the content?

**Comment by jordansissel** [comment]
Just a note that JSON is only valid in UTF-8, so it must be put back in UTF-8 for most any output in Logstash to ship it properly.

**Comment by jstangroome** [comment]
I'll follow up with the original developer of the logstash configuration in question for whether the use of `.encode()` is appropriate but my primary concern is that the worker gets stuck and the input queue grows and there is no new output.

Surely we should see an exception, an event dropped, or the pipeline restarted - basically anything but a hang with high CPU.

**Comment by guyboertje** [comment]
@jstangroome - thank you for raising this issue and finding relevant Jruby issues.

Re: raising an exception etc, it is very difficult to detect this from outside the worker thread as the endless loop lies deep inside a Java class in the worker thread.

We are working on a separated monitoring 'supervisor' solution, but version 1 of this will not include automated pipeline problem detection and correction.

The bug is most likely a JRuby one, although we might be feeding JRuby some edge case data that manifests this behaviour. you should know that it is unlikely that we will get some time to work on this soon.

For this reason we are asking you to find a work around.

We may find it is fixed with newer versions of JRuby.  Its hard to add a 'passing test' that validates incorrect operation (if it was do-able then the test would fail for correct operation and we would detect the upstream fix).

**Comment by jstangroome** [comment]
@guyboertje Thank you for explaining.

My experience with logstash has been that it comes packaged with a particular version of JRuby. How would you suggest I try running logstash with a newer JRuby? Is this even supported, or is it a case of a newer version of logstash choosing to adopt newer a JRuby?

**Comment by guyboertje** [comment]
@jstangroome - we embed JRuby. So, yes, to get a newer version of JRuby, a LS upgrade is needed.
We usually use the latest 1.7.XX whenever we do a point release of LS.

LS 1.5.4 uses JRuby 1.7.22 (current release)

**Comment by guyboertje** [comment]
@jstangroome - I will leave this issue open pending feedback from your original dev.  If you don't plan on feeding back, please tell me and I can take appropriate action.

**Comment by jstangroome** [comment]
@guyboertje I've removed the offending call to `encode()` in our logstash configuration and the problem has gone.

Separately though, LS 1.5.4 is *not* using JRuby 1.7.22, it is instead using 1.7.20 and is apparent in the installed `/opt/logstash/vendor/jruby/lib/jruby.jar:META-INF/MANIFEST.MF` file and in the Rake scripts:
https://github.com/elastic/logstash/blob/v1.5.4/rakelib/vendor.rake#L3
```
"jruby" => { "version" => "1.7.20", "sha1" => "3c11f01d38b9297cef2c281342f8bb799772e481" },
```

**Comment by guyboertje** [comment]
@jstangroome - I'm glad that you resolved the problem.

Re: JRuby 1.7.20 / 22; thank you for correcting this. I was looking at the master branch.  We will be releasing v 1.5.5 after 2.0 has settled down.

Are you able to use 2.0 at all?

**Comment by guyboertje** [comment]
@jstangroome - is this closeable?

**Comment by jstangroome** [comment]
Yes.
