### ISSUE TITLE
Getting errors with the tcp input

### ISSUE THREAD

**Issue by glennslaven** [elastic/logstash#3995]
We're using the TCP input to receive messages from syslog-ng instances, we're getting a lot of these errors:

```
{:timestamp=>"2015-10-07T04:06:09.696000+0000", :message=>"An error occurred. Closing connection", :client=>"10.0.1.137:61189", :exception=>#<Timeout::Error: execution expired>, :backtrace=>["org/jruby/RubyIO.java:2996:in `sysread'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:164:in `read'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:115:in `handle_socket'", "org/jruby/ext/timeout/Timeout.java:126:in `timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:114:in `handle_socket'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:147:in `client_thread'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-1.0.0/lib/logstash/inputs/tcp.rb:145:in `client_thread'"], :level=>:error}
```

Input conf looks like this

```
  tcp {
    port => 6515
    codec => line
    data_timeout => 120
    type => "syslogng"
  }
```

Has anyone run across this before?

We're running logstash 1:1.5.4-1 on ubuntu

**Comment by jordansissel** [comment]
You have set data_timeout such they after 120 seconds of idle connection,
that connection will be terminated. If you don't want this behavior, you
can use the default (no timeout) and remove the data_timeout setting in
your config.
