### ISSUE TITLE
hardcoded port for https? 

### ISSUE THREAD

**Issue by nellicus** [elastic/logstash#3998]
using 2.0 beta

```
if [type] == "syslog" {
                        elasticsearch {
                                hosts => ["w530:9200","w530:9201","w530:9202"]
                                index => "logstash-syslog-%{+YYYY.MM.dd}"
                                user => "logstash"
                                password => "secret"
				ssl => true
				keystore => "/opt/elk/PRODSEC/FS/secure/node1.jks"
				keystore_password => "secret"
				truststore => "/opt/elk/PRODSEC/FS/secure/ca-truststore.jks"
				truststore_password => "secret"
                        }
                }
```

```
The error reported is: 
  the scheme https does not accept registry part: w530:9200:9200 (or bad hostname?)
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/jruby/lib/ruby/1.9/uri/generic.rb:214:in `initialize'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/jruby/lib/ruby/1.9/uri/http.rb:84:in `initialize'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/jruby/lib/ruby/1.9/uri/common.rb:214:in `parse'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/jruby/lib/ruby/1.9/uri/common.rb:747:in `parse'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/client.rb:149:in `__extract_hosts'
org/jruby/RubyArray.java:2414:in `map'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/client.rb:145:in `__extract_hosts'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport/client.rb:109:in `initialize'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.13/lib/elasticsearch/transport.rb:26:in `new'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.beta6-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.beta6-java/lib/logstash/outputs/elasticsearch/http_client.rb:17:in `initialize'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.0.0.beta6-java/lib/logstash/outputs/elasticsearch.rb:256:in `register'
org/jruby/RubyArray.java:1613:in `each'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/pipeline.rb:164:in `start_outputs'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/pipeline.rb:83:in `run'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/agent.rb:155:in `execute'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/runner.rb:90:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0.beta1-java/lib/logstash/runner.rb:95:in `run'
org/jruby/RubyProc.java:271:in `call'
/opt/elk/PRODSEC/logstash/logstash-2.0.0-beta1/vendor/bundle/jruby/1.9/gems/stud-0.0.21/lib/stud/task.rb:12:in `initialize'
```

**Comment by nellicus** [comment]
moved to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/262
