### ISSUE TITLE
Logstash 2.0.0 crashed by "NoMethodError: undefined method `[]' for nil:NilClass"

### ISSUE THREAD

**Issue by abcfy2** [elastic/logstash#4178]
Here is the stacktrace:

```
NoMethodError: undefined method `[]' for nil:NilClass
         filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-throttle-2.0.2/lib/logstash/filters/throttle.rb:196
   multi_filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/filters/base.rb:152
           each at org/jruby/RubyArray.java:1613
   multi_filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/filters/base.rb:149
   cond_func_38 at (eval):884
           each at org/jruby/RubyArray.java:1613
   cond_func_38 at (eval):881
    filter_func at (eval):333
   filterworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:219
  start_filters at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:154
root@rtdstest:/var/log/logstash# vim /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb
```

Here is logstash.log:

```
{:timestamp=>"2015-11-10T15:44:15.557000+0800", :message=>"Exception in filterworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.", "exception"=>#<RuntimeError: can't add a new key into hash during iteration>, "backtrace"=>["org/jruby/RubyHash.java:992:in `[]='", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-throttle-2.0.2/lib/logstash/filters/throttle.rb:186:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/filters/base.rb:152:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/filters/base.rb:149:in `multi_filter'", "(eval):884:in `cond_func_38'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):881:in `cond_func_38'", "(eval):333:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:154:in `start_filters'"], :level=>:error}
{:timestamp=>"2015-11-11T16:58:54.577000+0800", :message=>"Exception in filterworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.", "exception"=>#<NoMethodError: undefined method `[]' for nil:NilClass>, "backtrace"=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-throttle-2.0.2/lib/logstash/filters/throttle.rb:196:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/filters/base.rb:152:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/filters/base.rb:149:in `multi_filter'", "(eval):884:in `cond_func_38'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):881:in `cond_func_38'", "(eval):333:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:219:in `filterworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:154:in `start_filters'"], :level=>:error}
```

OS: Ubuntu Server 14.04.3
JVM: 1.8.0_66
Logstash: 2.0.0

But I have no more information about this issue. I will set log leve to debug and try again.

**Comment by onlinegangster** [comment]
It seems in the newer logstash versions the syntax for testing has changed, it should look like this now:
insist { subject["my_field"] } == "some_value"

**Comment by kares** [comment]
logstash-filter-throttle-2.x was using a Hash to store events ... might have been the cause here.
since than (4.x) the updated plugin one uses a proper concurrent map-like collection.
