### ISSUE TITLE
Couldn't find any input plugin named 'file' (or filter 'translate') - no such file to load

### ISSUE THREAD

**Issue by ThomasdOtreppe** [elastic/logstash#4276]
System info:
 - Ubuntu 14.04.3 64 bit
 - Logstash 2.1.0 (from Elastic deb repository)

After upgrading from 1.5.5 (deb, via apt) to 2.1.0, Logstash didn't start correctly. It told me "Couldn't find any input plugin named 'file'. I thought it was just due to a failure from apt since 'file' input is built-in, so I forced a reinstall with apt and it worked fine.

Now, after restarting Logstash (to debug another issue), it happened again with the filter 'translate'. I know it's there because I have a post dpkg script to install that plugin when Logstash is updated (and I could see the output of plugin installation on the screen which was successful).

Is there anymore information needed to debug the issue?

**Comment by purbon** [comment]
@ThomasdOtreppe thanks for your report, I was trying to reproduce your issue in a VM with the same config and I was not able to reproduce. What I basically did is:

* Install the 1.5.5 via the apt repo.
* Run logstash (basic stdin/stdout)
* Update to 2.1 also via the apt repo, via changing the source and doing an ```apt-get update```, ```apt-get upgrade```.
* Run logstash (basic stdin/stdout)

I was not able to see any error, what might be a good strategy to reproduce this in your opinion?

what do you think?

**Comment by ThomasdOtreppe** [comment]
I have no idea how to reproduce it. It seems to be random.

**Comment by purbon** [comment]
hate non deterministic errors :-(

**Comment by ThomasdOtreppe** [comment]
If you'd like, I might be able to give you access to the system having the issue if I see it again.

**Comment by ph** [comment]
@ThomasdOtreppe Have you encountered the issue again with the latest versions?

**Comment by ThomasdOtreppe** [comment]
No.

**Comment by matajaz** [comment]
I suddenly experience the same problem.
I have been running with this configuration for days without this problem.
This morning I did a sudo apt-get install --resinstall logstash
I could successfully start the service after this but after another stop I could not restart.

sudo service logstash restart
Configuration error. Not restarting. Re-run with configtest parameter for details

sudo service logstash configtest
An unexpected error occurred! {:error=>#<LogStash::PluginLoadingError: Couldn't find any filter plugin named 'file'. Are you sure this is correct? Trying to load the file filter plugin resulted in this error: no such file to load -- logstash/filters/file>, :class=>"LogStash::PluginLoadingError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/plugin.rb:85:in `lookup'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:403:in `plugin'", "(eval):54:in `initialize'", "org/jruby/RubyKernel.java:1079:in `eval'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:60:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/agent.rb:171:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/runner.rb:90:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/runner.rb:95:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:warn}

**Comment by baspet** [comment]
i 've just downloaded 5.0.0-alpha3 and translate plugin is missing

**Comment by ThomasdOtreppe** [comment]
@baspet When you update you have to reinstall all the plugins you had installed before. Updating erase all plugins.
