### ISSUE TITLE
logstash-2.1.0 cpu 100%

### ISSUE THREAD

**Issue by wintersunny** [elastic/logstash#4379]
一、background
1. logstash read json types of data from kafka
2. logstash process id: 77859 

二、cpu state
top -p 77859 -H
PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
77919 work      20   0 4794m 503m  13m R 100.2  0.4  15966:02 <kafka

三、thread log（jstack 77859 ）
"<kafka" daemon prio=10 tid=0x00007fc3842f2800 nid=0x1305f runnable [0x00007fc3c8c88000]
   java.lang.Thread.State: RUNNABLE
    at org.jruby.internal.runtime.methods.JittedMethod.pre(JittedMethod.java:294)
    at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:139)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
    at org.jruby.ast.FCallNoArgNode.interpret(FCallNoArgNode.java:31)
    at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
    at org.jruby.ast.WhileNode.interpret(WhileNode.java:127)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
    at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
    at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
    at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
    at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
    at org.jruby.ast.EnsureNode.interpret(EnsureNode.java:96)
    at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
    at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
    at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
    at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
    at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
    at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
    at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
    at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
    at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
    at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
    at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
    at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
    at org.jruby.runtime.Block.call(Block.java:101)
    at org.jruby.RubyProc.call(RubyProc.java:290)
    at org.jruby.RubyProc.call(RubyProc.java:228)
    at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
    at java.lang.Thread.run(Thread.java:745)

**Comment by wintersunny** [comment]
logstash conf:

input {
    kafka {
        zk_connect => "XX.XX.XX.XX:2181"
        group_id => "logstash-stat"
        topic_id => "XXXX"
        reset_beginning => false # boolean (optional)， default: false
        consumer_threads => 4  # number (optional)， default: 1
        decorate_events => true # boolean (optional)， default: false
    }
}
output {
  elasticsearch { hosts => ["XX.XX.XX.XX:9200"] }
}

**Comment by jsvd** [comment]
version 2.0.3 of the logstash-input-kafka has been released to address this: https://github.com/logstash-plugins/logstash-input-kafka/pull/54 please update with `bin/plugin update logstash-input-kafka`

**Comment by suyograo** [comment]
Closing in favor of https://github.com/logstash-plugins/logstash-input-kafka/issues/52
