### ISSUE TITLE
Fingerprint filter randomly failing

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4419]
This was initially reported by @cdahlqvist 

An import made from stdin is randomly failling with a `NameError` when using the fingerprint flter.

**Logstash version:** 2.1.1
**OS**: Amazon Linux
**JVM:**
```
java version "1.7.0_91"
OpenJDK Runtime Environment (amzn-2.6.2.2.63.amzn1-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
```
**Errors**
```
[ec2-user@XXXX duplicate-prevention]$ ./cat_logs logs 100000 | /home/ec2-user/logstash-2.1.1/bin/logstash -w 7 -f ./hashid2.conf
Settings: User set filter workers: 7, Default filter workers: 4
Exception in filterworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>#<NameError: uninitialized constant LogStash::Filters::Fingerprint::OpenSSL>, "backtrace"=>["org/jruby/RubyModule.java:2745:in `const_missing'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:136:in `encryption_algorithm'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:106:in `anonymize_openssl'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:91:in `filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:86:in `filter'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:151:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:148:in `multi_filter'", "(eval):155:in `filter_func'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:244:in `filterworker'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:178:in `start_filters'"], :level=>:error}
Exception in filterworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>#<NameError: uninitialized constant LogStash::Filters::Fingerprint::OpenSSL>, "backtrace"=>["org/jruby/RubyModule.java:2745:in `const_missing'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:136:in `encryption_algorithm'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:106:in `anonymize_openssl'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:91:in `filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:86:in `filter'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:151:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:148:in `multi_filter'", "(eval):155:in `filter_func'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb
:244:in `filterworker'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:178:in `start_filters'"], :level=>:error}
Exception in filterworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>#<NameError: uninitialized constant LogStash::Filters::Fingerprint::OpenSSL>, "backtrace"=>["org/jruby/RubyModule.java:2745:in `const_missing'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:136:in `encryption_algorithm'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:106:in `anonymize_openssl'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:91:in `filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:86:in `filter'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:151:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:148:in `multi_filter'", "(eval):155:in `filter_func'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:244:in `filterworker'", "/home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:178:in `start_filters'"], :level=>:error}
NameError: uninitialized constant LogStash::Filters::Fingerprint::OpenSSL
         const_missing at org/jruby/RubyModule.java:2745
  encryption_algorithm at /home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:136
     anonymize_openssl at /home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:106
                filter at /home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:91
                  each at org/jruby/RubyArray.java:1613
                filter at /home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:86
          multi_filter at /home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:151
                  each at org/jruby/RubyArray.java:1613
          multi_filter at /home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:148
           filter_func at (eval):155
          filterworker at /home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:244
         start_filters at /home/ec2-user/logstash-2.1.1/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:178
```
**Config**
```
https://gist.github.com/d8013ac1710ffb57fae7
```

This is really odd, because each filter has to go through a `#register` call which will lazy load the OpenSSL library, the call to those methods is done in the single thread, then the worker thread are started. Following the stacktrace the error was made in a `filter` call, so the openssl library should be loaded and the namespace available at that time? From the stacktrace you can see that the method `anonymize_openssl` was called, for that method to exist at least once instance of the filter should have ran the `#register` call?

I was not able to reproduce it with a simple config like this. https://gist.github.com/ph/e2ff019dc74265daab69

**Comment by ph** [comment]
@cdahlqvist can you add the jdk version or any other info that could be useful?

**Comment by ph** [comment]
From a discussion with @colinsurprenant on hipchat, this could be a concurrency/initializations issues, he was suggesting doing some test with different values of `-w X` and `-w 1` to see if we can find a pattern.

**Comment by ph** [comment]
update with jvm version

**Comment by colinsurprenant** [comment]
I was just able to reproduce the exception using simplified config and command https://gist.github.com/colinsurprenant/687bff77b5f876893c94

```
Exception in filterworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>#<NameError: uninitialized constant LogStash::Filters::Fingerprint::OpenSSL>, "backtrace"=>["org/jruby/RubyModule.java:2745:in `const_missing'", "/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:128:in `encryption_algorithm'", "/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:106:in `anonymize_openssl'", "/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:91:in `filter'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-fingerprint-2.0.2/lib/logstash/filters/fingerprint.rb:86:in `filter'", "/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:151:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/filters/base.rb:148:in `multi_filter'", "(eval):41:in `filter_func'", "/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:244:in `filterworker'", "/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.1-java/lib/logstash/pipeline.rb:178:in `start_filters'"], :level=>:error}
```

investigating...

**Comment by colinsurprenant** [comment]
proposed fix in https://github.com/logstash-plugins/logstash-filter-fingerprint/pull/10 
I am currently stress testing with that fix and so far so good but will need to complete a few passes before definitive victory :P
