### ISSUE TITLE
input-beats: ArgumentError: Could not find shared examples "an interruptible input plugin"

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#4454]
in master, `rake test:plugins` on a fresh `Gemfile.jruby-1.9.lock` (meaning `rm Gemfile.jruby-1.9.lock; rm -rf vendor/bundle; rake bootstrap`) gives this error :

```
rake test:plugins
Using Accessor#strict_set for specs
rake aborted!
ArgumentError: Could not find shared examples "an interruptible input plugin"
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:370:in `find_and_eval_shared'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:310:in `it_behaves_like'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `subclass'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:255:in `example_group'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:309:in `it_behaves_like'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.0/spec/inputs/beats_spec.rb:121:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `subclass'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:255:in `context'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.0/spec/inputs/beats_spec.rb:120:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:385:in `subclass'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/example_group.rb:255:in `describe'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/dsl.rb:43:in `describe'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/dsl.rb:82:in `describe'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-2.1.0/spec/inputs/beats_spec.rb:11:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1:in `(root)'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1361:in `load_spec_files'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:102:in `setup'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:88:in `run'
/Users/colin/dev/src/elasticsearch/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.4.1/lib/rspec/core/runner.rb:73:in `run'
/Users/colin/dev/src/elasticsearch/logstash/rakelib/test.rake:72:in `(root)'
Tasks: TOP => test:plugins
(See full trace by running task with --trace)
```

**Comment by ph** [comment]
Weird its complaining from a shared example which should be already present, the `beat_spec` doesnt a require_relative on `spec_helper` which require the devutils.

**Comment by colinsurprenant** [comment]
just realized it's not only input beats, removed it from Gemfile and now it gives same error on input-couchdb_changes

**Comment by ph** [comment]
Do you have devutils installed? Could we have a path collision that make the shared examples from the devutils not available?

**Comment by colinsurprenant** [comment]
false alarm. it was a local environment issue. :confused:
