### ISSUE TITLE
Logstash freeze with STALLING_THREADS

### ISSUE THREAD

**Issue by calve** [elastic/logstash#4484]
Hello

I have a logstash 2.1 instance, running on an EC2 Ubuntu 14.04. It periodically freeze, and then does not parse new incoming logs (while it still listen for incoming TCP connections). The only solution I found so far is to kill and restart the process.

When killed, Logstash exit with the following message

```
^CSIGINT received. Shutting down the pipeline. {:level=>:warn}
Received shutdown signal, but pipeline is still waiting for in-flight events
to be processed. Sending another ^C will force quit Logstash, but this may cause
data loss. {:level=>:warn}
 {:level=>:warn, "INFLIGHT_EVENT_COUNT"=>{"input_to_filter"=>20, "total"=>20}, "STALLING_THREADS"=>{["LogStash::Filters::Grok", {"match"=>["message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}(?:\\[%{INT:pid}\\]): \\[uid:%{INT:uid} sid:%{INT:sid} tty:%{NOTSPACE:tty}? cwd:%{PATH:cwd} filename:%{PATH:filename}\\]: %{GREEDYDATA:command}", "message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}: %{NOTSPACE:user} : TTY=%{NOTSPACE:tty} ; PWD=%{PATH:cwd} ; USER=%{NOTSPACE:elevated_user} ; COMMAND=%{GREEDYDATA:command}", "message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}: %{GREEDYDATA:remaining_message}", "message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}\\[%{INT:pid}\\]: %{GREEDYDATA:remaining_message}"]}]=>[{"thread_id"=>19, "name"=>"|filterworker.0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/jls-grok-0.11.2/lib/grok-pure.rb:177:in `match'"}]}}
The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information. {:level=>:error}
 {:level=>:warn, "INFLIGHT_EVENT_COUNT"=>{"input_to_filter"=>20, "total"=>20}, "STALLING_THREADS"=>{["LogStash::Filters::Grok", {"match"=>["message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}(?:\\[%{INT:pid}\\]): \\[uid:%{INT:uid} sid:%{INT:sid} tty:%{NOTSPACE:tty}? cwd:%{PATH:cwd} filename:%{PATH:filename}\\]: %{GREEDYDATA:command}", "message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}: %{NOTSPACE:user} : TTY=%{NOTSPACE:tty} ; PWD=%{PATH:cwd} ; USER=%{NOTSPACE:elevated_user} ; COMMAND=%{GREEDYDATA:command}", "message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}: %{GREEDYDATA:remaining_message}", "message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}\\[%{INT:pid}\\]: %{GREEDYDATA:remaining_message}"]}]=>[{"thread_id"=>19, "name"=>"|filterworker.0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/jls-grok-0.11.2/lib/grok-pure.rb:177:in `match'"}]}}
 {:level=>:warn, "INFLIGHT_EVENT_COUNT"=>{"input_to_filter"=>20, "total"=>20}, "STALLING_THREADS"=>{["LogStash::Filters::Grok", {"match"=>["message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}(?:\\[%{INT:pid}\\]): \\[uid:%{INT:uid} sid:%{INT:sid} tty:%{NOTSPACE:tty}? cwd:%{PATH:cwd} filename:%{PATH:filename}\\]: %{GREEDYDATA:command}", "message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}: %{NOTSPACE:user} : TTY=%{NOTSPACE:tty} ; PWD=%{PATH:cwd} ; USER=%{NOTSPACE:elevated_user} ; COMMAND=%{GREEDYDATA:command}", "message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}: %{GREEDYDATA:remaining_message}", "message", "%{MONTH} %{MONTHDAY} %{TIME} %{NOTSPACE:hostname} %{NOTSPACE:process}\\[%{INT:pid}\\]: %{GREEDYDATA:remaining_message}"]}]=>[{"thread_id"=>19, "name"=>"|filterworker.0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/jls-grok-0.11.2/lib/grok-pure.rb:177:in `match'"}]}}
```

What can I do to investigate further ?

**Comment by jsvd** [comment]
can you provide the configuration, maybe sample data?

**Comment by calve** [comment]
Sure. Here it is ;

```
input {
    tcp {
        port => 9000
        codec => json
        type => "remote" # We do not use `syslog` so that logstash do not attempt to parse input
    }
    file {
        type => "ossec"
        path => "/var/ossec/logs/alerts/alerts.log"
        sincedb_path => "/opt/logstash/sincedbfile"
        codec => multiline {
            pattern => "^\*\*"
            negate => true
            what => "previous"
        }
    }
}

# Copy %{MESSAGE} to %{message}
filter {
    if [type] == "remote" {
        mutate {
            add_field =>  {"message" => "%{MESSAGE}"}
        }
    }
}

filter {
    if [type] == "remote" and "uwsgi" in [FILE_NAME] {
        multiline {
        # Everything that does not start with a timestamp, ``[pid``, or an ip
        # is a multiline logs which belongs to the previous line
        pattern => "^(\d{4}-\d{2}-\d{2})|(\[pid:)|((%{IP} )?- - \[%{HTTPDATE}\])|(\[%{DAY} %{MONTH})|(%{SYSLOGTIMESTAMP})"
        negate => true
        what => "previous"
        }
    }
}

filter {
  if [type] == "ossec" {
       # Parse the header of the alert
       grok {
         # Matches  2014 Mar 08 00:57:49 (some.server.com) 10.1.2.3->ossec
         # (?m) fixes issues with multi-lines see https://logstash.jira.com/browse/LOGSTASH-509
         match => ["message", "(?m)\*\* Alert %{DATA:timestamp_seconds}:%{SPACE}%{WORD}?%{SPACE}\- %{DATA:ossec_group}\n%{YEAR} %{SYSLOGTIMESTAMP:syslog_timestamp} \(%{DATA:reporting_host}\) %{IP:reporting_ip}\-\>%{DATA:reporting_source}\nRule: %{NONNEGINT:rule_number} \(level %{NONNEGINT:severity}\) \-\> '%{DATA:signature}'\n%{GREEDYDATA:remaining_message}"]

         # Matches  2014 Mar 08 00:00:00 ossec-server01->/var/log/auth.log
         match => ["message", "(?m)\*\* Alert %{DATA:timestamp_seconds}:%{SPACE}%{WORD}?%{SPACE}\- %{DATA:ossec_group}\n%{YEAR} %{SYSLOGTIMESTAMP:syslog_timestamp} %{DATA:reporting_host}\-\>%{DATA:reporting_source}\nRule: %{NONNEGINT:rule_number} \(level %{NONNEGINT:severity}\) \-\> '%{DATA:signature}'\n%{GREEDYDATA:remaining_message}"]
         tag_on_failure => ['_ossec_head_fail']
       }

       # Attempt to parse additional data from the alert
       grok {
         match => ["remaining_message", "(?m)(Src IP: %{IP:src_ip}%{SPACE})?(Src Port: %{NONNEGINT:src_port}%{SPACE})?(Dst IP: %{IP:dst_ip}%{SPACE})?(Dst Port: %{NONNEGINT:dst_port}%{SPACE})?(User: %{USER:acct}%{SPACE})?%{GREEDYDATA:real_message}"]
         tag_on_failure => ['_ossec_data_fail']
       }

       mutate {
         convert      => [ "severity", "integer"]
         replace      => [ "@message", "%{real_message}" ]
         replace      => [ "@fields.hostname", "%{reporting_host}"]
         add_field    => [ "@fields.product", "ossec"]
         add_field    => [ "raw_message", "%{message}"]
         add_field    => [ "ossec_server", "%{host}"]
         remove_field => [ "syslog_program", "syslog_timestamp", "reporting_host", "message", "timestamp_seconds", "real_message", "remaining_message", "path", "host", "tags"]
       }
     }
  else {
    grok {
      # Test it at http://grokconstructor.appspot.com/do/match
      # Should matches the logs at ``../samples/access.log``
      match => [
        "message", "(%{IP:src_ip} )?- - \[%{HTTPDATE:DATE}\] \"(?:(%{WORD:method} %{NOTSPACE:request_url} HTTP/%{NUMBER:http_version})|(%{NOTSPACE:request_url}))\" %{NUMBER:http_status} %{NUMBER:request_size}( %{QUOTEDSTRING:referer} %{QUOTEDSTRING:user_agent})?",
        # Match some uwsgi.log entries
        # [pid: 486|app: 0|req: 8870/34275] 10.0.0.48 () {38 vars in 542 bytes} [Mon May  4 10:34:17 2015] GET /test => generated 195 bytes in 2 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
        "message", "(?m)\[pid: %{NUMBER:pid}\|app: %{NUMBER:app}\|req: %{NUMBER:req}/%{NUMBER}\] %{IP:src_ip} \(\) \{%{NUMBER} vars in %{NUMBER} bytes\} \[%{GREEDYDATA:DATE}\] %{WORD:method} %{URIPATHPARAM:request_url} \=\> generated %{NUMBER:request_size} bytes in %{NUMBER} msecs \(HTTP/%{NUMBER:http_version} %{NUMBER:http_status}\) %{NUMBER} headers in %{NUMBER}",
        # Match some uwsgi.log entries
        # 2015-12-18 10:37:25,260 [INFO] requests.packages.urllib3.connectionpool: Starting new HTTP connection (1): 10.0.32.195
        "message", "(?m)%{TIMESTAMP_ISO8601:DATE} \[%{LOGLEVEL:level}\] %{NOTSPACE:process}: %{GREEDYDATA:remaining_message}",
        # Match snoopylogger auth.log entries
        # Dec 21 09:55:00 ip-10-75-21-213 snoopy[16746]: [uid:0 sid:28267 tty: cwd:/ filename:/bin/netstat]: netstat -tan
        "message", "%{SYSLOGTIMESTAMP:DATE} %{NOTSPACE:hostname} %{NOTSPACE:process}(?:\[%{INT:pid}\]): \[uid:%{INT:uid} sid:%{INT:sid} tty:%{NOTSPACE:tty}? cwd:%{PATH:cwd} filename:%{PATH:filename}\]: %{GREEDYDATA:command}",          # Match some uwsgi.log entries
        # Fri Dec 18 10:37:14 2015 - SIGINT/SIGQUIT received...killing workers...
        "message", "%{GREEDYDATA:DATE} - %{GREEDYDATA:remaining_message}",
        # Match sudo auth.log entries
        # Dec 21 11:41:29 ip-10-89-6-32 sudo: username : TTY=pts/6 ; PWD=/home/username ; USER=root ; COMMAND=/usr/bin/tail /var/log/auth.log
        "message", "%{SYSLOGTIMESTAMP:DATE} %{NOTSPACE:hostname} %{NOTSPACE:process}: %{NOTSPACE:user} : TTY=%{NOTSPACE:tty} ; PWD=%{PATH:cwd} ; USER=%{NOTSPACE:elevated_user} ; COMMAND=%{GREEDYDATA:command}",
        # Dec 21 11:41:29 ip-10-89-6-32 sudo: pam_unix(sudo:session): session opened for user root by username(uid=0)
        "message", "%{SYSLOGTIMESTAMP:DATE} %{NOTSPACE:hostname} %{NOTSPACE:process}: %{GREEDYDATA:remaining_message}",
        # Match misc auth.log entries
        # Dec 21 11:20:01 ip-10-75-21-213 CRON[21081]: pam_unix(cron:session): session opened for user smmsp by (uid=0)
        "message", "%{SYSLOGTIMESTAMP:DATE} %{NOTSPACE:hostname} %{NOTSPACE:process}\[%{INT:pid}\]: %{GREEDYDATA:remaining_message}"
      ]
      add_field => { "tags" => "parsed" }
    }
    mutate {
      convert      => [ "http_status", "integer"]
      convert      => [ "http_version", "integer"]
      convert      => [ "request_size", "integer"]
    }

    if "api" in [ROLES] {
         ruby {
           code => "event['type'] = 'api'"
         }
       }
    else if "web" in [ROLES] {
           ruby {
             code => "event['type'] = 'web'"
           }
         }
    else if "card" in [ROLES] {
           ruby {
             code => "event['type'] = 'card'"
           }
         }
    else if "couch" in [ROLES] {
           ruby {
             code => "event['type'] = 'couch'"
           }
         }
      if [origin] and [ENVIRONMENT] and [type] {
           mutate {
             add_field => { "saved_path" => "%{ENVIRONMENT}/%{type}/%{origin}" }
           }
         }
    }
}

filter {
    date {
      match => ["DATE",
                "MMM dd HH:mm:ss", # auth.log messages don't have years :s
                "ISO8601",
                "dd/MMM/YYYY:HH:mm:ss Z",
                "yyyy-MM-dd HH:mm:ss,SSS", # empirically, this one (uwsgi.log) needs to be last :s
                "E MMM d HH:mm:ss YYYY",
                "E MMM  d HH:mm:ss YYYY" # some dates have two fuckings spaces before the monthday
               ]
      remove_field => ["DATE"]
      remove_tag => ["parsed_dateparsefailure"]
      locale => "en"
    }
}

filter {
  geoip {
    source => "src_ip"
  }
}

output {
    if [type] == "ossec" {
        elasticsearch {
            hosts => ["127.0.0.1:9201"]
            index => "logstash-ossec-%{+YYYY.MM.dd}"
            document_type => "ossec"
            template_name => "template-ossec"
            template => "/home/ubuntu/log_config/logstash/template-ossec.json"
            template_overwrite => true
        }
    }
    else {
        elasticsearch {
            hosts => ["127.0.0.1:9201"]
            index => "%{ENVIRONMENT}-%{+YYYY.MM.dd}"
        }
        if [saved_path] {
            file {
                # According to plugin documentation, ``path`` should not starts with a dynamic string
                path => "/home/ubuntu/logs/%{saved_path}-%{+YYYY-MM-dd}.json"
                codec => json
            }
        }
    }
    stdout{
    }
    s3 {
            access_key_id => "myaccesskey"
            bucket => "myownbucket"
            region => "eu-west-1"
            secret_access_key => "ahahalolnope"
            time_file => 5
            codec => json
    }
}

```

Input data are regular applications logs (``auth.log``, ``syslog``, ``access.log``, ``error.log`` and the likes), which are successfully parsed by logstash.

**Comment by jsvd** [comment]
can you investigate and find out if any abnormally large events appeared on the logs?
I can see multiple optimizations that can be done in the config, but in itself it should no cause long delays in grok processing.

I would suspect some very big lines ( > 256k for example) could be appearing in the logs

**Comment by calve** [comment]
So I launched a second logstash instance on a fresh ec2, and we came across the following entry ;

```
Jan 15 17:27:26 ip-10-0-32-79 snoopy[32245]: [uid:106 sid:10847 tty: cwd:/var/lib/jenkins/jobs/athome_pci_card/workspace/venv/build/pycrypto filename:/usr/bin/print]: print -r -- \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
```

Yep, there are actually 3000+ `\`. Does it makes sense to you ?

**Comment by jsvd** [comment]
@calve is that the contents of one of the files the logstash instance is reading? it seems very strange but should cause the stalling

**Comment by calve** [comment]
Actually, this is read from a tcp input sent from a syslogng client.

After more testing in a development environment, it looks like logstshash 
correctly parse said entry, so I might be on the wrong path.

To add context, this line is written by snoopylogger which intercepts excve() 
calls during some CI compilation task. We started noticing that logstash 
systematically stall after running the said task.

I'll keep you updated as I track that behaviour.

**Comment by purbon** [comment]
closing this for now, please keep us update it if you have more details.
