### ISSUE TITLE
Truncated Messages In Logstash Debian Package 1:2.1.1-1

### ISSUE THREAD

**Issue by cgough** [elastic/logstash#4500]
I just upgraded logstash to version 1:2.1.1-1 using the elastic debian repository and I am seeing grokparsefailures in logstash.stdout that did not occur with version 1.2.1.0-1.  Reverting back to 1.2.1.0-1 fixed the issue.   Essentially it appears that logstash is truncating some of the messages from my nginx access log.  This is resulting in grokparsefailures in logstash.stdout.  I have tested my grok patterns against the lines that are being truncated and they match perfectly.  Again, reverting back to version 1.2.1.0-1 fixed the issue.   

Here's my stack, note these are virtual machines running on vmware:
```
ubuntu-14.04.3 LTS
nginx-1.6.2/passenger-5.0.11
elasticsearch-2.1.1
logstash-1.2.1.1-1
logstash-fowarder-0.4.0
```
Here's an example of a line from our nginx access log that is being truncated:
```
2016-01-15T07:39:54+00:00 1452843594.522 - - api.blahblah.com 107 [-] [-] [-] [-] [-] 200 15 0.017 0.014914 GET /v9/status - [HTTP-Monitor/1.1]
```
Here are our logstash filters.  They work with the earlier version and are verified to match the line above using https://grokdebug.herokuapp.com.
```
      match => [
        "message", "%{TIMESTAMP_ISO8601:time_iso8601} %{NUMBER:msec:float} %{IPORHOST:x_forwarded_for} %{DATA:x_forwarded_proto} %{HOSTNAME:hostname} %{NUMBER:request_length:float} \[%{GREEDYDATA:authentication_token}\] \[%{GREEDYDATA:x_token}\] \[%{GREEDYDATA:x_brokerage}\] \[%{GREEDYDATA:x_cred_label}\] \[%{GREEDYDATA:x_cred_type}\] %{NUMBER:status:int} %{NUMBER:body_bytes_sent:float} %{NUMBER:request_time:float} %{NUMBER:x_runtime:float} %{WORD:request_method} %{URIPATH:uri} %{DATA:query_string} \[%{GREEDYDATA:user_agent}\]",
        "message", "%{TIMESTAMP_ISO8601:time_iso8601} %{NUMBER:msec:float} %{DATA:x_forwarded_for} %{DATA:x_forwarded_proto} %{HOSTNAME:hostname} %{NUMBER:request_length:float} \[%{GREEDYDATA:authentication_token}\] \[%{GREEDYDATA:x_token}\] \[%{GREEDYDATA:x_brokerage}\] \[%{GREEDYDATA:x_cred_label}\] \[%{GREEDYDATA:x_cred_type}\] %{NUMBER:status:int} %{NUMBER:body_bytes_sent:float} %{NUMBER:request_time:float} %{DATA:x_runtime:float} %{WORD:request_method} %{URIPATH:uri} %{DATA:query_string} \[%{GREEDYDATA:user_agent}\]"
```
Here is logstash.stdout showing the truncated message:
```
{
       "message" => " [-] [-] 200 15 0.017 0.014914 GET /v9/status - [HTTP-Monitor/1.1]",
      "@version" => "1",
    "@timestamp" => "2016-01-15T18:27:54.261Z",
          "type" => "api-access",
          "file" => "/home/deploy/exchange/shared/log/api_access.log",
          "host" => "app023",
        "offset" => "3596738",
          "pool" => "be.carbon-api.prod",
          "tags" => [
        [0] "_grokparsefailure"
    ],
      "endpoint" => "%{uri}"
}
```
Again, rolling back to the prior version fixed this.

Thanks.

**Comment by cgough** [comment]
Some more context, we do some `mutates` in our filter:
```
    mutate {
      ## copy uri into new field called endpoint
      add_field => [ "endpoint", "%{uri}" ]
    }\ mutate {
      ## convert empty dashes in fields to string 'NULL'
      ## kibana 4.2 currently has issues searching for empty dashes
      ## empty dashes are special characters in lucene syntax
      gsub => [ "authentication_token", "^-$", "NULL"]
      gsub => [ "x_token", "^-$", "NULL" ]
      gsub => [ "x_forwarded_for", "^-$", "NULL" ]
      gsub => [ "x_forwarded_proto", "^-$", "NULL" ]
      gsub => [ "x_brokerage", "^-$", "NULL" ]
      gsub => [ "x_cred_label", "^-$", "NULL" ]
      gsub => [ "x_cred_type", "^-$", "NULL" ]
      gsub => [ "x_runtime", "^-$", "NULL" ]
      gsub => [ "query_string", "^-$", "NULL"]
      gsub => [ "user_agent", "^-$", "NULL"]
      gsub => [ "endpoint", "/v9/categories/(?!deleted$)([a-zA-Z\-]|[0-9])*[a-zA-Z\-]+([a-zA-Z\-]|[0-9])*$", "/v9/categories/name" ]
      gsub => [ "endpoint", "/v9/performers/(?!(search|deleted)$)([a-zA-Z\-]|[0-9])*[a-zA-Z\-]+([a-zA-Z\-]|[0-9])*$", "/v9/performers/name" ]
      gsub => [ "endpoint", "/v9/venues/(?!(search|deleted)$)([a-zA-Z\-]|[0-9])*[a-zA-Z\-]+([a-zA-Z\-]|[0-9])*$", "/v9/venues/name" ]
      gsub => [ "endpoint", "/[0-9\-]+", "/id" ]  
  }
```

**Comment by cgough** [comment]
Wondering if this is related to the stack trace I see in elasticsearch.log, which seems to be complaining about a malformed time_iso8601 timestamp.  Quite possible this elasticsearch error is due to a bug in logstash, or vice-versa.
```
[2016-01-15 15:14:09,584][DEBUG][action.bulk              ] [Warren III Worthington] [logstash-api-access-2016-01-15][0] failed to execute bulk item (index) index {[logstash-api-access-2016-01-15][api-access][AVJF2dQLaXSqaz5Osiqt], source[{"message":"16-01-15T14:04:15+00:00 1452866655.631 - - api.ticketevolution.com 107 [-] [-] [-] [-] [-] 200 15 0.015 0.013500 GET /v9/status - [HTTP-Monitor/1.1]","@version":"1","@timestamp":"2016-01-15T15:14:09.137Z","type":"api-access","file":"/home/deploy/exchange/shared/log/api_access.log","host":"app028","offset":"4995990","pool":"be.pos-api.int","time_iso8601":"16-01-15T14:04:15+00:00","msec":1.452866655631E9,"x_forwarded_for":"NULL","x_forwarded_proto":"NULL","hostname":"api.ticketevolution.com","request_length":107.0,"authentication_token":"NULL","x_token":"NULL","x_brokerage":"NULL","x_cred_label":"NULL","x_cred_type":"NULL","status":200,"body_bytes_sent":15.0,"request_time":0.015,"x_runtime":0.0135,"request_method":"GET","uri":"/v9/status","query_string":"NULL","user_agent":"HTTP-Monitor/1.1","endpoint":"/v9/status"}]}
MapperParsingException[failed to parse [time_iso8601]]; nested: IllegalArgumentException[Invalid format: "16-01-15T14:04:15+00:00" is malformed at "-01-15T14:04:15+00:00"];
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:339)
        at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrField(DocumentParser.java:314)
        at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:441)
        at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:267)
        at org.elasticsearch.index.mapper.DocumentParser.innerParseDocument(DocumentParser.java:127)
        at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:79)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:304)
        at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:516)
        at org.elasticsearch.index.shard.IndexShard.prepareCreate(IndexShard.java:507)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.prepareIndexOperationOnPrimary(TransportReplicationAction.java:1052)
        at org.elasticsearch.action.support.replication.TransportReplicationAction.executeIndexRequestOnPrimary(TransportReplicationAction.java:1060)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:338)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:131)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.performOnPrimary(TransportReplicationAction.java:579)
        at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase$1.doRun(TransportReplicationAction.java:452)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Invalid format: "16-01-15T14:04:15+00:00" is malformed at "-01-15T14:04:15+00:00"
        at org.joda.time.format.DateTimeParserBucket.doParseMillis(DateTimeParserBucket.java:187)
        at org.joda.time.format.DateTimeFormatter.parseMillis(DateTimeFormatter.java:780)
        at org.elasticsearch.index.mapper.core.DateFieldMapper$DateFieldType.parseStringValue(DateFieldMapper.java:360)
        at org.elasticsearch.index.mapper.core.DateFieldMapper.innerParseCreateField(DateFieldMapper.java:526)
        at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:213)
        at org.elasticsearch.index.mapper.FieldMapper.parse(FieldMapper.java:331)
        ... 18 more
```

**Comment by jsvd** [comment]
I haven't been able to reproduce this, I tried with the sample line and grok+mutate patterns, using logstash 2.1.1:

```
input { generator { count => 2 message => "2016-01-15T07:39:54+00:00 1452843594.522 - - api.blahblah.com 107 [-] [-] [-] [-] [-] 200 15 0.017 0.014914 GET /v9/status - [HTTP-Monitor/1.1]" } }
filter {
  grok {
   match => [
           "message", "%{TIMESTAMP_ISO8601:time_iso8601} %{NUMBER:msec:float} %{IPORHOST:x_forwarded_for} %{DATA:x_forwarded_proto} %{HOSTNAME:hostname} %{NUMBER:request_length:float} \[%{GREEDYDATA:authentication_token}\] \[%{GREEDYDATA:x_token}\] \[%{GREEDYDATA:x_brokerage}\] \[%{GREEDYDATA:x_cred_label}\] \[%{GREEDYDATA:x_cred_type}\] %{NUMBER:status:int} %{NUMBER:body_bytes_sent:float} %{NUMBER:request_time:float} %{NUMBER:x_runtime:float} %{WORD:request_method} %{URIPATH:uri} %{DATA:query_string} \[%{GREEDYDATA:user_agent}\]",
                   "message", "%{TIMESTAMP_ISO8601:time_iso8601} %{NUMBER:msec:float} %{DATA:x_forwarded_for} %{DATA:x_forwarded_proto} %{HOSTNAME:hostname} %{NUMBER:request_length:float} \[%{GREEDYDATA:authentication_token}\] \[%{GREEDYDATA:x_token}\] \[%{GREEDYDATA:x_brokerage}\] \[%{GREEDYDATA:x_cred_label}\] \[%{GREEDYDATA:x_cred_type}\] %{NUMBER:status:int} %{NUMBER:body_bytes_sent:float} %{NUMBER:request_time:float} %{DATA:x_runtime:float} %{WORD:request_method} %{URIPATH:uri} %{DATA:query_string} \[%{GREEDYDATA:user_agent}\]"
    ]
  }
  mutate {
    ## copy uri into new field called endpoint
    add_field => [ "endpoint", "%{uri}" ]
  } mutate {
    ## convert empty dashes in fields to string 'NULL'
    ## kibana 4.2 currently has issues searching for empty dashes
    ## empty dashes are special characters in lucene syntax
    gsub => [ "authentication_token", "^-$", "NULL"]
    gsub => [ "x_token", "^-$", "NULL" ]
    gsub => [ "x_forwarded_for", "^-$", "NULL" ]
    gsub => [ "x_forwarded_proto", "^-$", "NULL" ]
    gsub => [ "x_brokerage", "^-$", "NULL" ]
    gsub => [ "x_cred_label", "^-$", "NULL" ]
    gsub => [ "x_cred_type", "^-$", "NULL" ]
    gsub => [ "x_runtime", "^-$", "NULL" ]
    gsub => [ "query_string", "^-$", "NULL"]
    gsub => [ "user_agent", "^-$", "NULL"]
    gsub => [ "endpoint", "/v9/categories/(?!deleted$)([a-zA-Z\-]|[0-9])*[a-zA-Z\-]+([a-zA-Z\-]|[0-9])*$", "/v9/categories/name" ]
    gsub => [ "endpoint", "/v9/performers/(?!(search|deleted)$)([a-zA-Z\-]|[0-9])*[a-zA-Z\-]+([a-zA-Z\-]|[0-9])*$", "/v9/performers/name" ]
    gsub => [ "endpoint", "/v9/venues/(?!(search|deleted)$)([a-zA-Z\-]|[0-9])*[a-zA-Z\-]+([a-zA-Z\-]|[0-9])*$", "/v9/venues/name" ]
    gsub => [ "endpoint", "/[0-9\-]+", "/id" ]
  }
}
output { stdout { codec => rubydebug } }
```

output:

```
/tmp/logstash-2.1.1 % bin/logstash -f grok
Settings: Default filter workers: 2
Logstash startup completed
{
                 "message" => "2016-01-15T07:39:54+00:00 1452843594.522 - - api.blahblah.com 107 [-] [-] [-] [-] [-] 200 15 0.017 0.014914 GET /v9/status - [HTTP-Monitor/1.1]",
                "@version" => "1",
              "@timestamp" => "2016-02-01T13:51:40.700Z",
                    "host" => "Joaos-MBP.lan",
                "sequence" => 1,
            "time_iso8601" => "2016-01-15T07:39:54+00:00",
                    "msec" => 1452843594.522,
         "x_forwarded_for" => "NULL",
       "x_forwarded_proto" => "NULL",
                "hostname" => "api.blahblah.com",
          "request_length" => 107.0,
    "authentication_token" => "NULL",
                 "x_token" => "NULL",
             "x_brokerage" => "NULL",
            "x_cred_label" => "NULL",
             "x_cred_type" => "NULL",
                  "status" => 200,
         "body_bytes_sent" => 15.0,
            "request_time" => 0.017,
               "x_runtime" => 0.014914,
          "request_method" => "GET",
                     "uri" => "/v9/status",
            "query_string" => "NULL",
              "user_agent" => "HTTP-Monitor/1.1",
                "endpoint" => "/v9/status"
}
{
                 "message" => "2016-01-15T07:39:54+00:00 1452843594.522 - - api.blahblah.com 107 [-] [-] [-] [-] [-] 200 15 0.017 0.014914 GET /v9/status - [HTTP-Monitor/1.1]",
                "@version" => "1",
              "@timestamp" => "2016-02-01T13:51:40.699Z",
                    "host" => "Joaos-MBP.lan",
                "sequence" => 0,
            "time_iso8601" => "2016-01-15T07:39:54+00:00",
                    "msec" => 1452843594.522,
         "x_forwarded_for" => "NULL",
       "x_forwarded_proto" => "NULL",
                "hostname" => "api.blahblah.com",
          "request_length" => 107.0,
    "authentication_token" => "NULL",
                 "x_token" => "NULL",
             "x_brokerage" => "NULL",
            "x_cred_label" => "NULL",
             "x_cred_type" => "NULL",
                  "status" => 200,
         "body_bytes_sent" => 15.0,
            "request_time" => 0.017,
               "x_runtime" => 0.014914,
          "request_method" => "GET",
                     "uri" => "/v9/status",
            "query_string" => "NULL",
              "user_agent" => "HTTP-Monitor/1.1",
                "endpoint" => "/v9/status"
}
Logstash shutdown completed
```

**Comment by cgough** [comment]
I suspect that this may be network related as the issue has mitigated.  Our provider has been migrating datacenters and I suspect this issue was network related.  During this period, we were seeing logstash forwarder errors:
```
2016/01/13 19:09:09.843031 Failed to tls handshake with 10.0.0.19 read tcp 10.0.0.19:5043: i/o timeout
2016/01/13 19:09:10.844603 Connecting to [10.0.0.19]:5043 (admin003.xxx.xxx.xxx)
2016/01/13 19:09:25.845376 Failed to tls handshake with 10.0.0.19 read tcp 10.0.0.19:5043: i/o timeout
2016/01/13 19:09:26.846597 Connecting to [10.0.0.19]:5043 (admin003.xxx.xxx.xxx)
2016/01/13 19:09:28.151772 Connected to 10.0.0.19
```
These errors have also mysteriously disappeared.

**Comment by ph** [comment]
I will close this feel free to open another issue if you see it again.
