### ISSUE TITLE
Test failling feature/metrics

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4514]
Not sure why we are using a different channel for the web api?
Changes introduced in master break the tests.

```
 1) LogStash::Runner pipeline settings when pipeline workers is defined by the user should pass the value to the pipeline
     Failure/Error: Unable to find matching line from backtrace
       <Cabin::Channel (class)> received :get with unexpected arguments
         expected: (LogStash)
              got: (LogStash::Api)
        Please stub a default value first if message might be received with other args as well.
     # ./logstash-core/api/lib/app.rb:18:in `BaseApp'
     # ./logstash-core/api/lib/app.rb:9:in `Api'
     # ./logstash-core/api/lib/app.rb:8:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     # ./logstash-core/api/lib/app/root.rb:1:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     # ./logstash-core/api/lib/app/root.rb:2:in `(root)'
     # ./logstash-core/lib/logstash/../../api/init.ru:1:in `(root)'
     # ./logstash-core/lib/logstash/../../api/init.ru:6:in `new_from_string'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
     # ./logstash-core/lib/logstash/../../api/init.ru:0:in `new_from_string'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
     # ./vendor/bundle/jruby/1.9/gems/puma-2.15.3-java/lib/puma/configuration.rb:144:in `load_rackup'
     # ./vendor/bundle/jruby/1.9/gems/puma-2.15.3-java/lib/puma/configuration.rb:97:in `app'
     # ./vendor/bundle/jruby/1.9/gems/puma-2.15.3-java/lib/puma/runner.rb:113:in `load_and_bind'
     # ./vendor/bundle/jruby/1.9/gems/puma-2.15.3-java/lib/puma/single.rb:79:in `run'

  2) LogStash::Runner pipeline settings when pipeline workers is not defined by the user should not pass the value to the pipeline
     Failure/Error: Unable to find matching line from backtrace
       <Cabin::Channel (class)> received :get with unexpected arguments
         expected: (LogStash)
              got: (LogStash::Api)
        Please stub a default value first if message might be received with other args as well.
     # ./logstash-core/api/lib/app.rb:18:in `BaseApp'
     # ./logstash-core/api/lib/app.rb:9:in `Api'
     # ./logstash-core/api/lib/app.rb:8:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     # ./logstash-core/api/lib/app/root.rb:1:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     # ./logstash-core/api/lib/app/root.rb:2:in `(root)'
     # ./logstash-core/lib/logstash/../../api/init.ru:1:in `(root)'
     # ./logstash-core/lib/logstash/../../api/init.ru:6:in `new_from_string'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
     # ./logstash-core/lib/logstash/../../api/init.ru:0:in `new_from_string'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
     # ./vendor/bundle/jruby/1.9/gems/puma-2.15.3-java/lib/puma/configuration.rb:144:in `load_rackup'
     # ./vendor/bundle/jruby/1.9/gems/puma-2.15.3-java/lib/puma/configuration.rb:97:in `app'
     # ./vendor/bundle/jruby/1.9/gems/puma-2.15.3-java/lib/puma/runner.rb:113:in `load_and_bind'
     # ./vendor/bundle/jruby/1.9/gems/puma-2.15.3-java/lib/puma/single.rb:79:in `run'

Finished in 14.52 seconds (files took 2.59 seconds to load)
1139 examples, 2 failures```

**Comment by purbon** [comment]
what? this is strange, lets talk about it and see where it gets the problem. how can I reproduce?

**Comment by ph** [comment]
You can reproduce it in the `feature/metrics` branch directly there added test on the Runner from master.
And this change breaks the setup of the logger for the API. 

Not sure what is the correct fix in the case.

**Comment by purbon** [comment]
Oh!

  I see, will take a look.

- purbon

**Comment by ph** [comment]
Where you able to reproduce it?

**Comment by purbon** [comment]
@ph I can reproduce, I think this has a simply easy fix for now .... I will provide a fix very soon.

**Comment by purbon** [comment]
Will need to work a bit more on this test, as removing this bug also show another bug with the thread used to start the webserver.

```
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
.................................* Listening on tcp://0.0.0.0:9292 {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"43", :method=>"log"}
* Listening on tcp://0.0.0.0:9292 {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"43", :method=>"log"}
Use Ctrl-C to stop {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"43", :method=>"log"}
Use Ctrl-C to stop {:level=>:debug, :file=>"logstash/webserver.rb", :line=>"43", :method=>"log"}



^C
Exiting... Interrupt again to exit immediately.
SIGINT received. Shutting down the pipeline. {:level=>:warn, :file=>"logstash/agent.rb", :line=>"181", :method=>"trap_sigint"}
SIGINT received. Shutting down the pipeline. {:level=>:warn, :file=>"logstash/agent.rb", :line=>"181", :method=>"trap_sigint"}
F
```

**Comment by purbon** [comment]
this is not failing anymore as usage of cabin has been removed in the api. Closing this and opening a new bug for the runner.rb file.
