### ISSUE TITLE
Logstash Master default plugins job failure 

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#4611]
File input break the master default plugins test:

see for an error description at http://build-eu-00.elastic.co/view/LS%20Master/job/Logstash_Master_Default_Plugins/1029/console

```
Failures:

  1) LogStash::Inputs::File testing with new, register, run and stop when close_older config is specified having timed_out, the identity is evicted
     Failure/Error: expect(codec).to receive_call_and_args(:accept, [true])
       Expecting method accept to receive: [true] but got: false
     # ./vendor/bundle/jruby/1.9/gems/logstash-input-file-2.2.0/spec/inputs/file_spec.rb:232:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:72:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'

Deprecation Warnings:
```

@guyboertje i know you're working on this, something fixed? what do you think?

**Comment by guyboertje** [comment]
@purbon - expect a PR to review immanently :smile:

**Comment by purbon** [comment]
@guyboertje my pleasure

**Comment by guyboertje** [comment]
Fixed with https://github.com/logstash-plugins/logstash-input-file/pull/99
