### ISSUE TITLE
Logstash 2.1.0: NoMethodError: undefined method `[]' for nil:NilClass / logstash-codec-json_lines / logstash-input-tcp

### ISSUE THREAD

**Issue by CryptonZylog** [elastic/logstash#4618]
Firstly,

OS: Windows Server 2012 R2
JVM: java version "1.8.0_71"
Logstash 2.1.0 (all plugins zip)

Using a simple tcp json_lines input:
```perl
#
# Logstash input rules
#

input {  
  # Generic JSON input for external agents
  tcp {
    port => 5115
	codec => "json_lines"
  }  
}
```

Then for each data document received, this continuously is being logged. No data reaches elasticsearch (so **total data loss**)

```
{:timestamp=>"2016-02-02T11:22:27.858000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56660", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:27.905000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56661", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:27.967000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56662", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:28.030000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56663", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:28.108000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56664", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:28.186000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56697", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:28.233000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56736", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:28.295000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56737", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:28.358000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56738", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:28.405000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56739", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
{:timestamp=>"2016-02-02T11:22:28.467000-0800", :message=>"An error occurred. Closing connection", :client=>"10.12.196.128:56740", :exception=>#<NoMethodError: undefined method `[]' for nil:NilClass>, :backtrace=>["D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.0-java/lib/logstash/event.rb:73:in `initialize'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:52:in `guard'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:38:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:36:in `decode'", "org/jruby/RubyArray.java:1613:in `each'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-line-2.0.2/lib/logstash/codecs/line.rb:35:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json_lines-2.0.2/lib/logstash/codecs/json_lines.rb:37:in `decode'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:149:in `handle_socket'", "D:/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-tcp-2.0.4/lib/logstash/inputs/tcp.rb:140:in `server_connection_thread'"], :level=>:error}
...
```

JSON documents can be sent via another logstash instance, or a different application sending up same document format.

What gives?

**Comment by jsvd** [comment]
can you provide an example payload?

**Comment by CryptonZylog** [comment]
Here's an example payload. It is passed from another application as single-line JSON, terminated by a ''\n'' for the json_lines codec.

```javascript
{
	"rsm_source_device" : "TEST-PC",
	"rsm_source_application" : "Some Application",
	"rsm_source_category" : "Parameters",
	"rsm_source_tag" : null,
	"rsm_source_date" : "2016-02-03T16:44:15.621Z",
	"rsm_source_level" : "Info",
	"rsm_payload_type" : "TextualPayload",
	"type" : "Parameters",
	"tags" : ["TEST"],
	"@version" : "1",
	"@timestamp" : "2016-02-03T16:44:16.177Z",
	"host" : "10.11.12.13",
	"port" : 56321,
	"parameters" : {
		"r_IntTemp" : "32",
		"r_FrontTemp" : "99",
		"r_BackTemp" : "99",
		"r_HumTemp" : "26",
		"r_V24" : "0",
		"r_VHeat" : "0",
		"r_VFan" : "0",
		"r_V33" : "3785",
		"r_V5" : "5194",
		"r_LDRLight" : "0",
		"r_HumRel" : "22",
		"r_FrontBright" : "0",
		"r_BackBright" : "0",
		"r_ExtFanAlarm" : "1",
		"r_IntFanAlarm" : "1",
		"r_PanelFanAlarm" : "1",
		"r_HeaterCurrent" : "0",
		"r_BacklightLevel" : "0",
		"r_FanExtStatus" : "0",
		"r_FanIntStatus" : "0",
		"r_FanPanStatus" : "1",
		"r_HeaterStatus" : "0",
		"r_FanExtSpeed" : "0",
		"r_FanIntSpeed" : "0",
		"r_FanPanelSpeed" : "75",
		"r_MonitorModel" : "0",
		"rs_AlarmStatusReg" : "641597593",
		"rs_FailureStatusReg" : "60",
		"rw_TempHyst" : "21",
		"rw_BacklightDefault" : "90",
		"rw_HeaterHyst" : "28",
		"rw_HumidityHyst" : "78",
		"rw_BacklightMin" : "30",
		"rw_BacklightMax" : "110",
		"rw_LDRMin" : "99",
		"rw_LDRMax" : "825",
		"rw_CondHyst" : "82",
		"rw_AutoBrightEnable" : "3",
		"rw_IRId" : "92",
		"rd_ControllerOnTime" : "66762907",
		"rd_PanelOnTime" : "578",
		"rd_BacklightOnTime" : "578",
		"rd_ExtFanOnTime" : "491764",
		"rd_IntFanOnTime" : "491764",
		"rd_PanelFanOnTime" : "66762128",
		"rd_DiagSerialNum" : "xyz",
		"rd_MonitorSerialNum" : "xyz"
	}
}
```

**Comment by colinsurprenant** [comment]
I am able to reproduce on 2.1.0 using 
```
bin/logstash -e 'input{stdin{codec=>json_lines}} output{stdout{codec=>rubydebug}}' --debug
```
and hitting <enter>

I added some debugging traces and 2 events are generated, the first *empty* from the <enter> and a second one `nil`. 

I also tried on master and I cannot reproduce with json_lines 2.0.2 and latest.

**Comment by colinsurprenant** [comment]
same with 2.1.2 and 2.2.0  but fine in master. investigating.

**Comment by colinsurprenant** [comment]
the problem seems to be with `LogStash::Json.load("")` which generates an exception in the codec **but** I cannot reproduce the same behaviour if I add a spec for this case and run rspec. very weird.

**Comment by jsvd** [comment]
I believe this is working in master because the logstash-core-event and logstash-core-event-java behave differently when initialized with nil:

#### with logstash-core-event-java

```
/tmp/logstash % cat Gemfile | grep core
gem "logstash-core", "3.0.0.dev", :path => "./logstash-core"
gem "logstash-core-event-java", "3.0.0.dev", :path => "./logstash-core-event-java"
/tmp/logstash % bin/logstash irb
1.9 :001 > LogStash::Event.new(nil)
 => 2016-02-10T01:11:14.307Z %{host} %{message} 
```

#### with logstash-core-event

```
/tmp/logstash % cat Gemfile | grep core
gem "logstash-core", "3.0.0.dev", :path => "./logstash-core"
gem "logstash-core-event", "3.0.0.dev", :path => "./logstash-core-event"
/tmp/logstash % bin/logstash irb
1.9 :001 > LogStash::Event.new(nil)
NoMethodError: undefined method `[]' for nil:NilClass
	from /tmp/logstash/logstash-core-event/lib/logstash/event.rb:73:in `initialize'
	from (irb):1:in `evaluate'
	from org/jruby/RubyKernel.java:1079:in `eval'
	from org/jruby/RubyKernel.java:1479:in `loop'
	from org/jruby/RubyKernel.java:1242:in `catch'
	from org/jruby/RubyKernel.java:1242:in `catch'
	from /tmp/logstash/logstash-core/lib/logstash/runner.rb:321:in `start_shell'
	from /tmp/logstash/logstash-core/lib/logstash/runner.rb:140:in `execute'
	from /tmp/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /tmp/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /tmp/logstash/lib/bootstrap/environment.rb:70:in `(root)'
```

**Comment by colinsurprenant** [comment]
True that. 

Here's what completely sidetracked me while trying to debug this: 

```
bin/logstash irb
irb(main):001:0> require "logstash/json"
=> true
irb(main):002:0> LogStash::Json.load('')
=> nil
irb(main):003:0> LogStash::Json.load('').to_s
Java::JavaLang::NullPointerException:
	from org.jruby.runtime.callsite.CachingCallSite.pollAndGetClass(CachingCallSite.java:433)
	from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:131)
	from org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
	from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	from org.jruby.ast.RootNode.interpret(RootNode.java:129)
	from org.jruby.evaluator.ASTInterpreter.INTERPRET_EVAL(ASTInterpreter.java:95)
	from org.jruby.evaluator.ASTInterpreter.evalWithBinding(ASTInterpreter.java:184)
	from org.jruby.RubyKernel.evalCommon(RubyKernel.java:1116)
	from org.jruby.RubyKernel.eval19(RubyKernel.java:1079)
	from org.jruby.RubyKernel$INVOKER$s$0$3$eval19.call(RubyKernel$INVOKER$s$0$3$eval19.gen)
	from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:180)
	from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:70)
	from org.jruby.ast.FCallManyArgsNode.interpret(FCallManyArgsNode.java:60)
	from org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	from org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	from org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)
```

So this completely misdirected by debugging sessions. Bug that's an interesting one ^^.

@joao obviously passing nil should not crash the `Event` class and we can push a fix for next minor release. We can also push a fix in json_lines to make sure we don't pass nil object and just ignore empty lines so that @CryptonZylog will be able to just upgrade the codec and that will solve his problem.

**Comment by colinsurprenant** [comment]
@CryptonZylog logstash-codec-json_lines v2.1.1 has just been pushed and should solve your problem. Let me know how that works for you.
