### ISSUE TITLE
Test  for `JVM stats LogStash::Api::HotThreadsCommand` failling randomly

### ISSUE THREAD

**Issue by ph** [elastic/logstash#4682]
```
  1) JVM stats LogStash::Api::HotThreadsCommand#schema return hot threads information
     Failure/Error: expect(subject).to receive(:uptime).and_return(10).at_least(:once)
       (#<LogStash::Api::HotThreadsCommand:0xdd81806>).uptime(any args)
           expected: at least 1 time with any arguments
           received: 0 times with any arguments
     # ./logstash-core/spec/api/lib/commands/jvm_spec.rb:15:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:240:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:179:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:78:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'

Finished in 19.81 seconds (files took 2.44 seconds to load)
1727 examples, 1 failure
```
Randomized with seed 64424

**Comment by ph** [comment]
updated with seed

**Comment by purbon** [comment]
@ph confirm the issue, easy fix ... the expectation is not really necessary there as the command is not really printing the uptime anymore (is more a leftover from the past)
