### ISSUE TITLE
`LoadError: no such file to load -- archive/tar/minitar` during `rake bootstrap`

### ISSUE THREAD

**Issue by jeffcharles** [elastic/logstash#4702]
Hi, I'm trying to get a local clone of Logstash up and running and can't seem to get past the `rake bootstrap` step. I cloned the repo and then ran `rake bootstrap` like the REAME specified. Specifically I see:

```
$ rake bootstrap
Installing minitar >= 0 because the build process needs it.
[bootstrap] Fetching and installing gem: minitar (>= 0)
rake aborted!
LoadError: no such file to load -- archive/tar/minitar
/Users/jeffreycharles/projects/logstash/rakelib/vendor.rake:17:in `untar'
/Users/jeffreycharles/projects/logstash/rakelib/vendor.rake:86:in `(root)'
Tasks: TOP => bootstrap => vendor:all => vendor:jruby
(See full trace by running task with --trace)
```

Ruby version: 

```
$ ruby --version
jruby 1.7.16 (1.9.3p392) 2014-09-25 575b395 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_66-b17 +jit [darwin-x86_64]
```

Rake version:

```
$ rake --version
rake, version 10.5.0
```

Full trace output:

```
$ rake bootstrap --trace  
** Invoke bootstrap (first_time)
** Invoke vendor:all (first_time)
** Invoke vendor:jruby (first_time)
** Execute vendor:jruby
** Invoke vendor/_/jruby-bin-1.7.24.tar.gz (first_time)
** Invoke vendor/_ (first_time, not_needed)
** Invoke vendor (first_time, not_needed)
** Execute vendor/_/jruby-bin-1.7.24.tar.gz
** Invoke vendor/jruby (first_time, not_needed)
** Invoke vendor (not_needed)
** Invoke dependency:archive-tar-minitar (first_time)
** Execute dependency:archive-tar-minitar
** Invoke gem:require (first_time)
** Execute gem:require
Installing minitar >= 0 because the build process needs it.
** Invoke gem:install (first_time)
** Invoke build/bootstrap (first_time, not_needed)
** Invoke build (first_time, not_needed)
** Execute gem:install
[bootstrap] Fetching and installing gem: minitar (>= 0)
rake aborted!
LoadError: no such file to load -- archive/tar/minitar
org/jruby/RubyKernel.java:1065:in `require'
/Users/jeffreycharles/.rubies/jruby-1.7.16/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:55:in `require'
/Users/jeffreycharles/.rubies/jruby-1.7.16/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:53:in `require'
/Users/jeffreycharles/projects/logstash/rakelib/vendor.rake:17:in `untar'
/Users/jeffreycharles/projects/logstash/rakelib/vendor.rake:86:in `(root)'
org/jruby/RubyProc.java:271:in `call'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:240:in `execute'
org/jruby/RubyArray.java:1613:in `each'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:235:in `execute'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:179:in `invoke_with_call_chain'
/Users/jeffreycharles/.rubies/jruby-1.7.16/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:201:in `invoke_prerequisites'
org/jruby/RubyArray.java:1613:in `each'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:178:in `invoke_with_call_chain'
/Users/jeffreycharles/.rubies/jruby-1.7.16/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:201:in `invoke_prerequisites'
org/jruby/RubyArray.java:1613:in `each'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:199:in `invoke_prerequisites'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:178:in `invoke_with_call_chain'
/Users/jeffreycharles/.rubies/jruby-1.7.16/lib/ruby/1.9/monitor.rb:211:in `mon_synchronize'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/task.rb:165:in `invoke'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/application.rb:150:in `invoke_task'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
org/jruby/RubyArray.java:1613:in `each'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/application.rb:106:in `top_level'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/application.rb:115:in `run_with_threads'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/application.rb:100:in `top_level'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/application.rb:78:in `run'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/Users/jeffreycharles/.gem/jruby/1.9.3/gems/rake-10.5.0/bin/rake:33:in `(root)'
org/jruby/RubyKernel.java:1081:in `load'
/Users/jeffreycharles/.rubies/jruby-1.7.16/bin/rake:23:in `(root)'
Tasks: TOP => bootstrap => vendor:all => vendor:jruby
```

Is there a step I missed while trying to set this up?

**Comment by purbon** [comment]
it should be possible to just clone and execute rake bootstrap to set up everything like you just made, I'm thinking you might not get minitar installed properly before installing jruby, can you do this commands:

* git clone [logstash repo]
* rake dependency:archive-tar-minitar

this should give you minitar installed, would help to see if something is happening with this command and your environment. 

thanks.

**Comment by jeffcharles** [comment]
```
$ rake dependency:archive-tar-minitar
Installing minitar >= 0 because the build process needs it.
[bootstrap] Fetching and installing gem: minitar (>= 0)
rake aborted!
LoadError: no such file to load -- archive/tar/minitar
/Users/jeffreycharles/projects/logstash/rakelib/vendor.rake:17:in `untar'
/Users/jeffreycharles/projects/logstash/rakelib/vendor.rake:86:in `(root)'
/Users/jeffreycharles/projects/logstash/rakelib/z_rubycheck.rake:28:in `(root)'
Tasks: TOP => vendor:jruby
(See full trace by running task with --trace)
```

**Comment by purbon** [comment]
This is strange, I'm wondering if your ruby env have:

* do you have bundler installed?
* wich version of rubygems do you have? (```run: gem -v```)

**Comment by jeffcharles** [comment]
```
$ bundler --version
Bundler version 1.11.2
```

```
$ gem -v
2.1.9
```

**Comment by purbon** [comment]
can you update your rubygems version to a more recent one? and try again?

**Comment by jeffcharles** [comment]
Updating to 2.5.2 solved the problem. Thanks!

**Comment by purbon** [comment]
happy it helped! will you be willing to probably add a note (through a Pull Request) to our readme ? this will help others a lot. what do you think?

**Comment by jeffcharles** [comment]
I can do that

**Comment by purbon** [comment]
Awesome, much appreciate it!

/purbon
