### ISSUE TITLE
Invalid update request to Elasticsearch when document field is named "data"

### ISSUE THREAD

**Issue by bitmelt** [elastic/logstash#4796]
When using logstash to update existing document, I want to add a field named `data`, but that results in an invalid bulk request to Elasticsearch.  Is field name `data` reserved?  The error from Elasticsearch is

    IllegalArgumentException[Malformed action/metadata line [3], expected START_OBJECT or END_OBJECT but found [null]]

logstash outputs (formatted for readability):

    Attempted to send a bulk request to Elasticsearch configured at '["http://localhost:9200/"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided?
    {
        :client_config=>{
            :hosts=>["http://localhost:9200/"],
            :ssl=>nil,
            :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil, :ssl=>{}},
            :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore,
            :logger=>nil,
            :tracer=>nil,
            :reload_connections=>false,
            :retry_on_failure=>false,
            :reload_on_failure=>false,
            :randomize_hosts=>false
        },
        :error_message=>"[500] {\"error\":\"IllegalArgumentException[Malformed action/metadata line [3], expected START_OBJECT or END_OBJECT but found [null]]\",\"status\":500}",
        :error_class=>"Elasticsearch::Transport::Transport::Errors::InternalServerError",
        :backtrace=>[
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:146:in `__raise_transport_error'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/base.rb:256:in `perform_request'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/transport/http/manticore.rb:54:in `perform_request'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.15/lib/elasticsearch/transport/client.rb:125:in `perform_request'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.15/lib/elasticsearch/api/actions/bulk.rb:87:in `bulk'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:53:in `non_threadsafe_bulk'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'",
            "org/jruby/ext/thread/Mutex.java:149:in `synchronize'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:38:in `bulk'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:162:in `safe_bulk'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:101:in `submit'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:86:in `retrying_submit'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:29:in `multi_receive'",
            "org/jruby/RubyArray.java:1653:in `each_slice'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.1-java/lib/logstash/outputs/elasticsearch/common.rb:28:in `multi_receive'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/output_delegator.rb:119:in `worker_multi_receive'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/output_delegator.rb:65:in `multi_receive'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:290:in `output_batch'",
            "org/jruby/RubyHash.java:1342:in `each'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:290:in `output_batch'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:221:in `worker_loop'",
            "/Users/gg/Applications/logstash-2.2.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.2-java/lib/logstash/pipeline.rb:190:in `start_workers'"
        ],

The update request looks like this:

    bin/logstash -e 'input { stdin {codec => "json_lines"} } output { elasticsearch {hosts => ["localhost:9200"] action => "update" index => "logtest" document_type => "entry" document_id => "%{id}"} }' <<EOF
    {"id":"3", "data":{"NAME_MOD":"Kevin", "MSG":"Good Morning", "REF":"abc123", "REF2":"jhg65"}}
    EOF

Although the error happens even if `data` is a plain string rather than an object, like `"data":"foo"` .

I ran the request through an HTTP proxy to see what is being sent to Elasticsearch, and here's the bulk request:

    {"update":{"_id":"3","_index":"logtest","_type":"entry","_routing":null}}
    {"doc":{"id":"3","@version":"1","@timestamp":"2016-03-11T14:56:55.462Z","host":"ggpmbp.local"}}
    {"NAME_MOD":"Kevin","MSG":"Good Morning","REF":"abc123","REF2":"jhg65"}

which is obviously invalid.  It looks like logstash took the `data` object and put it on its own line instead of keeping it embedded in the document.  If I change the name of the `data` field to `foo`, then everything works fine, resulting in the following bulk request:

    {"update":{"_id":"3","_index":"logtest","_type":"entry","_routing":null}}
    {"doc":{"id":"3","foo":{"NAME_MOD":"Kevin","MSG":"Good Morning","REF":"abc123","REF2":"jhg65"},"@version":"1","@timestamp":"2016-03-11T14:53:50.106Z","host":"ggpmbp.local"}}

If I change the field name to `DATA` it also works fine.  The issue seems to be only with a field named `data`.

**Comment by purbon** [comment]
Thanks for your feedback, is interesting error, might best guess here is this might be due to the usage of json_lines, can you verify this does not happen if you use the json codec?

I see your example, but can you share a full config + a set of dummy lines to try to reproduce better? 

Thanks a lot,

**Comment by purbon** [comment]
If the bug is confirmed it would be nice to move it to the elasticsearch output, if end up being a bug from there, repo is https://github.com/logstash-plugins/logstash-output-elasticsearch for details.

**Comment by bitmelt** [comment]
Using the `json` codec results in an identical error.  Here's the code using the `json` codec:

    bin/logstash -e 'input { stdin {codec => "json"} } output { elasticsearch {hosts => ["localhost:9200"] action => "update" index => "logtest" document_type => "entry" document_id => "%{id}"} }' <<EOF
    {"id":"3", "data":{"NAME_MOD":"Kevin", "MSG":"Good Morning", "REF":"abc123", "REF2":"jhg65"}}
    EOF

I don't have a full config, I just downloaded logstash and trying this on the command line.  My configuration is Elasticsearch 1.7.3, index named `logtest` does not exist.  Then I run the following to insert some data:

    bin/logstash -e 'input { stdin {codec => "json_lines"} } output { elasticsearch {hosts => ["localhost:9200"] index => "logtest" document_type => "entry" document_id => "%{id}"} }' <<EOF
    {"id":"1", "name":"Bob", "text":"Hello"}
    {"id":"2", "name":"John", "text":"Hi"}
    {"id":"3", "name":"Kevin", "text":"Good morning"}
    EOF

(BTW, using the a field named `data` when inserting rather than updating works fine.)  After I run the above insert, here are the documents in Elasticsearch:

    $ curl 'http://localhost:9200/logtest/_search?pretty'
    {
      "took" : 1,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      },
      "hits" : {
        "total" : 3,
        "max_score" : 1.0,
        "hits" : [ {
          "_index" : "logtest",
          "_type" : "entry",
          "_id" : "1",
          "_score" : 1.0,
          "_source":{"id":"1","name":"Bob","text":"Hello","@version":"1","@timestamp":"2016-03-11T17:20:42.061Z","host":"ggpmbp.local"}
        }, {
          "_index" : "logtest",
          "_type" : "entry",
          "_id" : "2",
          "_score" : 1.0,
          "_source":{"id":"2","name":"John","text":"Hi","@version":"1","@timestamp":"2016-03-11T17:20:42.129Z","host":"ggpmbp.local"}
        }, {
          "_index" : "logtest",
          "_type" : "entry",
          "_id" : "3",
          "_score" : 1.0,
          "_source":{"id":"3","name":"Kevin","text":"Good morning","@version":"1","@timestamp":"2016-03-11T17:20:42.129Z","host":"ggpmbp.local"}
        } ]
      }
    }

And here's the mapping

    $ curl 'http://localhost:9200/logtest/_mapping?pretty'
    {
      "logtest" : {
        "mappings" : {
          "entry" : {
            "properties" : {
              "@timestamp" : {
                "type" : "date",
                "format" : "dateOptionalTime"
              },
              "@version" : {
                "type" : "string"
              },
              "host" : {
                "type" : "string"
              },
              "id" : {
                "type" : "string"
              },
              "name" : {
                "type" : "string"
              },
              "text" : {
                "type" : "string"
              }
            }
          }
        }
      }
    }

After that I run

    bin/logstash -e 'input { stdin {codec => "json"} } output { elasticsearch {hosts => ["localhost:9200"] action => "update" index => "logtest" document_type => "entry" document_id => "%{id}"} }' <<EOF
    {"id":"3", "data":{"NAME_MOD":"Kevin", "MSG":"Good Morning", "REF":"abc123", "REF2":"jhg65"}}
    EOF

And get the error (with `json` or `json_lines` codec).  Both codecs work fine if I change `data` to `foo`, updating Elasticsearch to

    $ curl 'http://localhost:9200/logtest/_search?pretty'
    {
      "took" : 1,
      "timed_out" : false,
      "_shards" : {
        "total" : 5,
        "successful" : 5,
        "failed" : 0
      },
      "hits" : {
        "total" : 3,
        "max_score" : 1.0,
        "hits" : [ {
          "_index" : "logtest",
          "_type" : "entry",
          "_id" : "1",
          "_score" : 1.0,
          "_source":{"id":"1","name":"Bob","text":"Hello","@version":"1","@timestamp":"2016-03-11T17:20:42.061Z","host":"ggpmbp.local"}
        }, {
          "_index" : "logtest",
          "_type" : "entry",
          "_id" : "2",
          "_score" : 1.0,
          "_source":{"id":"2","name":"John","text":"Hi","@version":"1","@timestamp":"2016-03-11T17:20:42.129Z","host":"ggpmbp.local"}
        }, {
          "_index" : "logtest",
          "_type" : "entry",
          "_id" : "3",
          "_score" : 1.0,
          "_source":{"id":"3","name":"Kevin","text":"Good morning","@version":"1","@timestamp":"2016-03-11T17:29:42.006Z","host":"ggpmbp.local","foo":{"NAME_MOD":"Kevin","MSG":"Good Morning","REF":"abc123","REF2":"jhg65"}}
        } ]
      }
    }

**Comment by yanjunh** [comment]
I can reproduce this issue. Running logstash 2.1.3 with elasticsearch http ouput. "data" field is at the second level of the document. Had to mutate it to a different name. This seems to be a severe bug.

**Comment by suyograo** [comment]
This has been fixed in https://github.com/elastic/elasticsearch-ruby/issues/283 /cc @karmi . 

We'll be releasing a new version of ES output which patches the underlying elasticsearch-ruby lib
