### ISSUE TITLE
Logstash crashing with exception IOError: Too many open files

### ISSUE THREAD

**Issue by rbjorklin** [elastic/logstash#4815]
We are running Logstash 2.1.3 on Ubuntu 14.04.4 and we are seeing crashes about once a week.

This is from /var/log/logstash/logstash.err.1
```
IOError: Too many open files
         select at org/jruby/RubyIO.java:3682
        request at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:659
  each_resource at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:512
         resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1035
           each at org/jruby/RubyArray.java:1613
         resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1034
           each at org/jruby/RubyArray.java:1613
         resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1033
           each at org/jruby/RubyArray.java:1613
         resolv at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:1031
  each_resource at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:503
  each_resource at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:502
      each_name at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:453
      each_name at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:151
           each at org/jruby/RubyArray.java:1613
      each_name at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:150
        getname at /opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:132
        reverse at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.0.2/lib/logstash/filters/dns.rb:174
           each at org/jruby/RubyArray.java:1613
        reverse at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.0.2/lib/logstash/filters/dns.rb:155
         filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.0.2/lib/logstash/filters/dns.rb:85
        timeout at org/jruby/ext/timeout/Timeout.java:115
         filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.0.2/lib/logstash/filters/dns.rb:84
   multi_filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.3-java/lib/logstash/filters/base.rb:151
           each at org/jruby/RubyArray.java:1613
   multi_filter at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.3-java/lib/logstash/filters/base.rb:148
   cond_func_91 at (eval):3073
           each at org/jruby/RubyArray.java:1613
   cond_func_91 at (eval):3069
    filter_func at (eval):954
   filterworker at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.3-java/lib/logstash/pipeline.rb:244
  start_filters at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.1.3-java/lib/logstash/pipeline.rb:178
```

This is the limits for the running logstash process.
```
$ cat /proc/57469/limits
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             15786                15786                processes
Max open files            16384                16384                files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       15786                15786                signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

**Comment by suyograo** [comment]
Can you post your config?

**Comment by rbjorklin** [comment]
What follows is the output of `cat /etc/logstash/conf.d/*` with a few things redacted.

```
input {
  syslog {
    tags => [ "syslog" ]
  }
}

output {
  if "syslog" in [tags] {
    elasticsearch {
      hosts => [REDACTED]
      index => "logstash-syslog-%{+YYYY.MM.dd}"
    }
  }
}
input {
  syslog {
    port => 1030
    tags => [ "tomcat" ]
  }
}

filter {
  if "tomcat" in [tags] {
    grok {
      match => { "message" => [ "%{WORD:tag} +%{COMMONAPACHELOG}", "%{WORD:tag} +%{TOMCAT_DATESTAMP:timestamp2} +%{LOGLEVEL:severity_label} +%{GREEDYDATA:message}", "%{WORD:tag} +%{LOGLEVEL:severity_label}: %{GREEDYDATA:message}", "%{WORD:tag} +%{CATALINA_DATESTAMP} +%{GREEDYDATA:message}", "%{WORD:tag} +%{GREEDYDATA:message}" ] }
      overwrite => [ "message", "timestamp2", "severity_label" ]
      add_tag => [ "%{tag}" ]
    }
 }
  if [severity_label] =~ "([Aa]lert|ALERT)" {
    mutate {
      replace => { "severity" => 1 
                   "severity_label" => "ALERT"
      }
    }
  } else if [severity_label] =~ "([Cc]rit?(?:ical)?|CRIT?(?:ICAL)?)" {
    mutate {
      replace => { "severity" => 2
                   "severity_label" => "CRITICAL"
      }
    }
  } else if [severity_label] =~ "(^[Ee]rr?(?:or)?|ERR?(?:OR)?)" {
    mutate {
      replace => { "severity" => 3
                   "severity_label" => "ERROR"
      }
    }
  } else if [severity_label] =~ "(^[Ww]arn?(?:ing)?|WARN?(?:ING)?)" {
    mutate {
      replace => { "severity" => 4
                   "severity_label" => "WARNING"
      }
    }
  } else if [severity_label] =~ "([Nn]otice|NOTICE)" {
    mutate {
      replace => { "severity" => 5 
                   "severity_label" => "NOTICE"
      }
    }
  } else if [severity_label] =~ "([Ii]nfo|INFO|[Ii]nformational)" {
    mutate {
      replace => { "severity" => 6
                   "severity_label" => "INFO"
      }
    }
  } else if [severity_label] =~ "(^[Dd]ebug|DEBUG)" {
    mutate {
      replace => { "severity" => 7
                   "severity_label" => "DEBUG"
      }
    }
  } else {
    mutate {
      replace => { "severity" => 6 }
      replace => { "severity_label" => "INFO" }
    }
  }
  if "syslog" in [tags] {
    mutate {
      replace => { "host" => "%{logsource}" }
    }
  } else if "tomcat" in [tags] {
    mutate {
      replace => { "host" => "%{logsource}" }
    }
  }
}

output {
  if "tomcat" in [tags] {
    elasticsearch {
      hosts => [REDACTED]
      index => "logstash-tomcat-%{+YYYY.MM.dd}"
    }
  }
}
input {
  gelf {
    tags => [ "gelf" ]
  }
}

filter {
  if [severity] == 1 and "gelf" in [tags]  {
    mutate {
      add_field => { "severity_label" => "ALERT" }
      add_field => { "logsource" => "%{host}" }
    }
  } else if [severity] == 2 and "gelf" in [tags] {
    mutate {
      add_field => { "severity_label" => "CRITICAL" }
      add_field => { "logsource" => "%{host}" }
    }
  } else if [severity] == 3 and "gelf" in [tags] {
    mutate {
      add_field => { "severity_label" => "ERROR" }
      add_field => { "logsource" => "%{host}" }
    }
  } else if [severity] == 4 and "gelf" in [tags] {
    mutate {
      add_field => { "severity_label" => "WARNING" }
      add_field => { "logsource" => "%{host}" }
    }
  } else if [severity] == 5 and "gelf" in [tags] {
    mutate {
      add_field => { "severity_label" => "NOTICE" }
      add_field => { "logsource" => "%{host}" }
    }
  } else if [severity] == 6 and "gelf" in [tags] {
    mutate {
      add_field => { "severity_label" => "INFO" }
      add_field => { "logsource" => "%{host}" }
    }
  } else if [severity] == 7 and "gelf" in [tags] {
    mutate {
      add_field => { "severity_label" => "DEBUG" }
      add_field => { "logsource" => "%{host}" }
    }
  } else if "gelf" in [tags] {
    mutate {
      add_field => { "logsource" => "%{host}" }
    }
  }
}

output {
  if "gelf" in [tags] {
    elasticsearch {
      hosts => [REDACTED]
      index => "logstash-gelf-%{+YYYY.MM.dd}"
    }
  }
}
input {
  gelf {
    tags => [ "docker" ]
    port => 12205
  }
}

filter {
  if "docker" in [tags] {
    mutate {
      lowercase => [ "environment", "artifact", "application", "tag" ]
      add_tag => [ "%{tag}" ]
      add_field => { "logsource" => "%{source_host}" }
    }
    dns {
      action => "replace"
      reverse => [ "logsource" ]
    }
    grok {
      match => { "logsource" => "%{WORD:logsource}" }
      overwrite => [ "logsource" ]
    }
  }
}
filter {
  geoip {
    source => "%{clientip}"
    database => "/opt/logstash/GeoLiteCity.dat"
  }
}
filter {
  if "docker" in [tags] {
    if [severity] == "1" or [level] == "1" {
      mutate {
        add_field => { "blargh" => "%{facility}" }
        replace => { "severity" => "1" "severity_label" => "ALERT" }
        remove_field => [ "level" ]
      }
    } else if [severity] == "2" or [level] == "2" {
      mutate {
        add_field => { "blargh" => "%{facility}" }
        replace => { "severity" => "2" "severity_label" => "CRITICAL" }
        remove_field => [ "level" ]
      }
    } else if [severity] == "3" or [level] == "3" {
      mutate {
        add_field => { "blargh" => "%{facility}" }
        replace => { "severity" => "3" "severity_label" => "ERROR" }
        remove_field => [ "level" ]
      }
    } else if [severity] == "4" or [level] == "4" {
      mutate {
        add_field => { "blargh" => "%{facility}" }
        replace => { "severity" => "4" "severity_label" => "WARNING" }
        remove_field => [ "level" ]
      }
    } else if [severity] == "5" or [level] == "5" {
      mutate {
        add_field => { "blargh" => "%{facility}" }
        replace => { "severity" => "5" "severity_label" => "NOTICE" }
        remove_field => [ "level" ]
      }
    } else if [severity] == "6" or [level] == "6" {
      mutate {
        add_field => { "blargh" => "%{facility}" }
        replace => { "severity" => "6" "severity_label" => "INFO" }
        remove_field => [ "level" ]
      }
    } else if [severity] == "7" or [level] == "7" {
      mutate {
        add_field => { "blargh" => "%{facility}" }
        replace => { "severity" => "7" "severity_label" => "DEBUG" }
        remove_field => [ "level" ]
      }
    }
  }
}
output {
  if [environment] == "REDACTED" {
    gelf {
      host => "REDACTED"
      level => "%{severity_label}"
    }
  } else if [environment] == "REDACTED" {
    gelf {
      host => "REDACTED"
      level => "%{severity_label}"
    }
  } else {
    gelf {
      host => "REDACTED"
      level => "%{severity_label}"
    }
  }
}
output {
  if [REDACTED] {
    udp {
      codec => "json_lines"
      host => "REDACTED"
      port => 6501
    }
  }
}
output {
  if "docker" in [tags] {
    # Uncomment and start from cmd line with: sudo -u logstash /opt/logstash/bin/logstash agent -f /etc/logstash/conf.d
    stdout { codec => rubydebug { metadata => true } }
  }
}
output {
  if "docker-tomcat-log" in [tags] {
    file {
      path => "/logs/%{environment}/tomcat/%{application}/%{artifact}-%{logsource}-%{+YYYY.MM.dd}.log"
      codec => "line"
    }
  } else if "docker-app-log" in [tags] {
    file {
      path => "/logs/%{environment}/app/%{application}/%{artifact}-%{logsource}-%{+YYYY.MM.dd}.log"
      codec => "line"
    }
  }
}
output {
  if "docker-app-log" in [tags] {
    elasticsearch {
      hosts => [REDACTED]
      index => "logstash-docker-app-log-%{+YYYY.MM.dd}"
    }
  } else if "docker-tomcat-log" in [tags] {
    elasticsearch {
      hosts => [REDACTED]
      index => "logstash-docker-tomcat-log-%{+YYYY.MM.dd}"
    }
  }
}
```

**Comment by inqueue** [comment]
In Logstash 2.3.x, I am seeing a bunch of these errors leading to an eventual `Too many open files` error:

```
{:timestamp=>"2016-04-28T06:44:57.118000-0500", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n Plugin: <LogStash::Inputs::Tcp type=>\"DClogs\", port=>54322, codec=><LogStash::Codecs::Line charset=>\"UTF-8\", delimiter=>\"\\n\">, host=>\"0.0.0.0\", data_timeout=>-1, mode=>\"server\", ssl_enable=>false, ssl_verify=>true, ssl_key_passphrase=><password>>\n Error: closed stream", :level=>:error}

{:timestamp=>"2016-04-28T06:44:57.703000-0500", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n Plugin: <LogStash::Inputs::Lumberjack port=>5014, ssl_certificate=>\"/etc/pki/tls/certs/logstash-forwarder.crt\", ssl_key=>\"/etc/pki/tls/private/logstash-forwarder.key\", codec=><LogStash::Codecs::Plain charset=>\"UTF-8\">, host=>\"0.0.0.0\", congestion_threshold=>5>\n Error: problem when accepting", :level=>:error}

{:timestamp=>"2016-04-28T06:44:58.000000-0500", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n Plugin: <LogStash::Inputs::Beats port=>54323, codec=><LogStash::Codecs::Plain charset=>\"UTF-8\">, host=>\"0.0.0.0\", ssl=>false, ssl_verify_mode=>\"none\", congestion_threshold=>5, target_field_for_codec=>\"message\">\n Error: problem when accepting", :level=>:error}
```

Then,

```
{:timestamp=>"2016-04-28T06:44:59.520000-0500", :message=>"UDP listener died", :exception=>#<IOError: Too many open files>, :backtrace=>["org/jruby/RubyIO.java:3682:in `select'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:77:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-2.0.5/lib/logstash/inputs/udp.rb:50:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:336:in `start_input'"], :level=>:warn}
```

Still need to confirm, but it seems like the first error could be resulting file descriptors remaining open. The user is restarting Logstash periodically to avoid the condition, but I will ask them for netstat output to confirm the theory.

**Comment by zyphlar** [comment]
Also getting similar errors on 2.1.3, just using a regular tcp input with no filters:

input:
```
        tcp {
          port => 20000
          type => syslog
        }
```

output:
```
        sqs {
            queue => "my_sqs_queue"
            region => "my_aws_region"
            batch => false
        }
```

```
Jul 23 04:51:27 localhost logstash.log:  {:timestamp=>"2016-07-23T11:51:27.642000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Tcp port=>20000, type=>\"syslog\", codec=><LogStash::Codecs::Line charset=>\"UTF-8\", delimiter=>\"\\n\">, host=>\"0.0.0.0\", data_timeout=>-1, mode=>\"server\", ssl_enable=>false, ssl_verify=>true, ssl_key_passphrase=><password>>\n  Error: problem when accepting", :level=>:error}
Jul 23 04:51:28 localhost logstash.log:  {:timestamp=>"2016-07-23T11:51:28.782000+0000", :message=>"A plugin had an unrecoverable error. Will restart this plugin.\n  Plugin: <LogStash::Inputs::Tcp port=>20000, type=>\"syslog\", codec=><LogStash::Codecs::Line charset=>\"UTF-8\", delimiter=>\"\\n\">, host=>\"0.0.0.0\", data_timeout=>-1, mode=>\"server\", ssl_enable=>false, ssl_verify=>true, ssl_key_passphrase=><password>>\n  Error: closed stream", :level=>:error}
```

Then I get one of those "closed stream" errors every second for eternity until I kill and restart logstash. This is behind an AWS load balancer and on an AWS m4.large instance. It coincides with a build up to 100% cpu and about 300 load balancer requests / 2,000 syslog messages per minute, about 600 unique clients, and about 5000 open connections as shown by `netstat`. About 3000 of those connections are in state CLOSE_WAIT, 600 in ESTABLISHED, and 300 in LAST_ACK.
