### ISSUE TITLE
Creating all-plugins tar is not working

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#4936]
Trying to create all-plugins packaged tar using

```
rake artifact:tar-all-plugins
```

but it errors out with:

```
Installation successful
[artifact:install-logstash-core] using logstash-core from Rubygems
[artifact:install-logstash-core] using logstash-core-event-java from Rubygems
[artifact:tar] Building tar.gz of all plugins
[artifact:tar] building build/logstash-all-plugins-2.3.0.tar.gz
rake aborted!
Archive::Tar::Minitar::Writer::BoundedStream::FileOverflow
/private/tmp/logstash/vendor/bundle/jruby/1.9/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:285:in `write'
/private/tmp/logstash/rakelib/artifacts.rake:141:in `build_tar'
org/jruby/RubyIO.java:1182:in `open'
/private/tmp/logstash/rakelib/artifacts.rake:138:in `build_tar'
/private/tmp/logstash/vendor/bundle/jruby/1.9/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:344:in `add_file_simple'
/private/tmp/logstash/rakelib/artifacts.rake:137:in `build_tar'
org/jruby/RubyArray.java:1613:in `each'
/private/tmp/logstash/rakelib/artifacts.rake:126:in `build_tar'
/private/tmp/logstash/rakelib/artifacts.rake:115:in `(root)'
org/jruby/RubyProc.java:281:in `call'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyKernel.java:1059:in `load'
Tasks: TOP => artifact:tar-all-plugins
(See full trace by running task with --trace)
````

Ref:
http://build-eu-00.elasticsearch.org/job/logstash_create_all_plugins_tar_artifact_23/jdk=JDK7,label=metal-pool/3/console

**Comment by suyograo** [comment]
@purbon can you take a look at this please?

**Comment by purbon** [comment]
on it

**Comment by suyograo** [comment]
Fixed
