### ISSUE TITLE
Logstash does not start if the password has a dollar char

### ISSUE THREAD

**Issue by skokhanovskiy** [elastic/logstash#4953]
Logstash 2.3 does not start if the password has a dollar '$' sign

```
output {
	if "elasticsearch" in [tags] {
		elasticsearch {
			hosts => [ "elasticsearch:9080" ]
			user => "logstash"
			password => "f*t4$Xqf"
...
```

Error message

```
Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Cannot evaluate `$Xqf`. Environment variable `Xqf` is not set and there is no default value given.>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/config/mixin.rb:164:in `replace_env_placeholders'", "org/jruby/RubyString.java:3064:in `gsub'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/config/mixin.rb:154:in `replace_env_placeholders'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/config/mixin.rb:116:in `config_init'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/config/mixin.rb:105:in `config_init'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/outputs/base.rb:63:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/output_delegator.rb:74:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:185:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:185:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:140:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/agent.rb:448:in `start_pipeline'"], :level=>:error}
```

**Comment by sjsadowski** [comment]
Use single quotes so that the password is a string literal, not interpreted.

**Comment by andrewvc** [comment]
This seems to be a bug related to https://github.com/elastic/logstash/issues/3944 Using single quotes does not help here.

**Comment by andrewvc** [comment]
As a workaround you can use an environment variable to (say FOO) and reference it in your file as $FOO. We need to find a real fix for this however.

**Comment by andrewvc** [comment]
Our current plan is to roll back this feature and mark it as an experimental feature that you must opt in to with a special command line flag. We're targeting this for a 2.3.1 hotfix.

**Comment by ph** [comment]
@sjsadowski The current logstash configuration parser doesn't make the difference between single quote and double quotes so this wouldn't work in this case.

**Comment by andrewvc** [comment]
I'm closing this issue since we'll be tracking progress here https://github.com/elastic/logstash/issues/4958

If you have further comments to make, please make them there.
