### ISSUE TITLE
The all plugins jobs return success when it actually failed

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5052]
http://build-eu-1.elasticsearch.org/job/logstash_create_all_plugins_tar_artifact_23/jdk=JDK7,label=metal-pool/lastBuild/console

The build returned a **SUCCESS** but in fact encountered many errors in either installing the gems OR building the actual `tar`

### ERRORS:
```
[artifact:tar] building build/logstash-all-plugins-2.3.0.tar.gz
rake aborted!
Archive::Tar::Minitar::Writer::BoundedStream::FileOverflow
/home/jenkins/workspace/logstash_create_all_plugins_tar_artifact_23/jdk/JDK7/label/metal-pool/vendor/bundle/jruby/1.9/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:285:in `write'
/home/jenkins/workspace/logstash_create_all_plugins_tar_artifact_23/jdk/JDK7/label/metal-pool/rakelib/artifacts.rake:141:in `build_tar'
org/jruby/RubyIO.java:1182:in `open'
/home/jenkins/workspace/logstash_create_all_plugins_tar_artifact_23/jdk/JDK7/label/metal-pool/rakelib/artifacts.rake:138:in `build_tar'
/home/jenkins/workspace/logstash_create_all_plugins_tar_artifact_23/jdk/JDK7/label/metal-pool/vendor/bundle/jruby/1.9/gems/minitar-0.5.4/lib/archive/tar/minitar.rb:344:in `add_file_simple'
/home/jenkins/workspace/logstash_create_all_plugins_tar_artifact_23/jdk/JDK7/label/metal-pool/rakelib/artifacts.rake:137:in `build_tar'
org/jruby/RubyArray.java:1613:in `each'
/home/jenkins/workspace/logstash_create_all_plugins_tar_artifact_23/jdk/JDK7/label/metal-pool/rakelib/artifacts.rake:126:in `build_tar'
/home/jenkins/workspace/logstash_create_all_plugins_tar_artifact_23/jdk/JDK7/label/metal-pool/rakelib/artifacts.rake:115:in `(root)'
org/jruby/RubyProc.java:281:in `call'
org/jruby/RubyArray.java:1613:in `each'
```

```
Error Bundler::InstallError, retrying 3/10
An error occurred while installing net-ssh (3.1.1), and Bundler cannot continue.
Make sure that `gem install net-ssh -v '3.1.1'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
Error Bundler::InstallError, retrying 4/10
An error occurred while installing net-ssh (3.1.1), and Bundler cannot continue.
Make sure that `gem install net-ssh -v '3.1.1'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
```

```
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "jar-dependencies":
  In snapshot (Gemfile.lock):
    jar-dependencies (= 0.3.2)

  In Gemfile:
    logstash-output-elasticsearch (>= 0) java depends on
      manticore (< 1.0.0, >= 0.5.4) java depends on
        jar-dependencies (>= 0) java

    logstash-input-kafka (>= 0) java depends on
      jruby-kafka (= 1.5.0) java depends on
        jar-dependencies (~> 0) java

    logstash-output-elasticsearch (>= 0) java depends on
      manticore (< 1.0.0, >= 0.5.4) java depends on
        jar-dependencies (>= 0) java

    logstash-output-gemfire (>= 0) java depends on
      jar-dependencies (~> 0.0.6) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
Bundler could not find compatible versions for gem "logstash-core":
  In snapshot (Gemfile.lock):
    logstash-core (= 2.3.0)

  In Gemfile:
    logstash-core-plugin-api (= 1.3.0) java depends on
      logstash-core (<= 2.3.0, >= 2.0.0) java

    logstash-codec-cloudtrail (>= 0) java depends on
      logstash-codec-spool (>= 0) java depends on
        logstash-core (< 3.0.0, >= 2.0.0.beta2) java

    logstash-output-gemfire (>= 0) java depends on
      logstash-core (~> 2.0.0.snapshot) java

```

**Comment by suyograo** [comment]
We are removing the all-plugin Jenkins job
