### ISSUE TITLE
useragent filter broken in 2.3?

### ISSUE THREAD

**Issue by wfrank** [elastic/logstash#5078]
with logstash 2.2, I can digest the input:

      "user_agent" => "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36",

and producing the output:

     "user_agent" => {
           "name" => "Chrome",
             "os" => "Windows 7",
        "os_name" => "Windows 7",
         "device" => "Other",
          "major" => "49",
          "minor" => "0",
          "patch" => "2623"
    },

while with logstash 2.3, I got these instead.

```
Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>#<NoMethodError: undefined method `multi_filter' for nil:NilClass>, "backtrace"=>["(eval):789:in `cond_func_28'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):786:in `cond_func_28'", "(eval):390:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:271:in `filter_batch'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:852:in `inject'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:269:in `filter_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:227:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:205:in `start_workers'"], :level=>:error}
NoMethodError: undefined method `multi_filter' for nil:NilClass
   cond_func_28 at (eval):789
           each at org/jruby/RubyArray.java:1613
   cond_func_28 at (eval):786
    filter_func at (eval):390
   filter_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:271
           each at org/jruby/RubyArray.java:1613
         inject at org/jruby/RubyEnumerable.java:852
   filter_batch at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:269
    worker_loop at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:227
  start_workers at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:205

```

**Comment by purbon** [comment]
We just released `2.3.1`, you can find it at https://www.elastic.co/downloads/logstash that include a fix for this issue. Sorry for your pain here.

**Comment by wfrank** [comment]
@purbon Thanks. 

While I am using the official Docker logstash image, I don't see an update there. is it maintained by Elastic? any idea how soon should I expected to see an update?

**Comment by purbon** [comment]
@wfrank there is no official Docker logstash image as in terms of maintained for elastic right now, so no idea sorry.
