### ISSUE TITLE
incorrect chmod not reported by daemon

### ISSUE THREAD

**Issue by spixx** [elastic/logstash#5155]
- Version: logstash-2.3.0-1.noarch
- Operating System: Centos 7
- Sample Data: see `log`
- Steps to Reproduce: be a bit dull

1. Create filter files
2. Create pattern and change filters to point to catalog with patterns
3. Start daemon
4. Get <log> error that does not really tell you anything
5. Start in debug (works?!?)
6. Use 30 minutes to find out what the issue is
7. `facepalm`
8. chmod 644 /etc/logstash/pattern.d/*
9. Sucess!

Suggestion (since I do this more for others whom might have the same issue) please add some kind of check on the pattern folder (and config folder) so that files with paranoid chmods are noticed and complained about.

ls
```
/etc/logstash/conf.d
-rw-r--r--. 1 root root 3.2K Apr 21 10:37 00-inputs.conf
-rw-r--r--. 1 root root  830 Apr 21 12:23 01-transforms.conf
-rw-r--r--. 1 root root  176 Apr 21 10:32 99-outputs.conf

/etc/logstash/pattern.d
-rw-------. 1 root root  645 Apr 21 12:23 11-tomcat.pattern
```

log

```
{:timestamp=>"2016-04-21T12:17:46.842000+0200", :message=>"Pipeline aborted due to error", :exception=>#<NoMethodError: undefined method `close' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-grok-0.11.2/lib/grok-pure.rb:83:in `add_patterns_from_file'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-2.0.5/lib/logstash/filters/multiline.rb:147:in `register'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-2.0.5/lib/logstash/filters/multiline.rb:145:in `register'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-multiline-2.0.5/lib/logstash/filters/multiline.rb:143:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:186:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:186:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:140:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/agent.rb:448:in `start_pipeline'"], :level=>:error}
{:timestamp=>"2016-04-21T12:17:49.852000+0200", :message=>"stopping pipeline", :id=>"main"}
```

**Comment by spixx** [comment]
Closing since this is solved.

**Comment by spixx** [comment]
Reopen until dev says yay or nay ;)

**Comment by regardfs** [comment]
Hi , spixx , i met the same problem, i have already changed the mode ,but it did not work...
`{:timestamp=>"2017-02-11T03:50:12.614000+0000", :message=>"An unexpected error occurred!", :error=>#<ArgumentError: invalid byte sequence in UTF-8>, :class=>"ArgumentError", :backtrace=>["org/jruby/RubyRegexp.java:1657:in `=~'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-grok-0.11.2/lib/grok-pure.rb:72:in `add_patterns_from_file'", "org/jruby/RubyIO.java:3542:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jls-grok-0.11.2/lib/grok-pure.rb:70:in `add_patterns_from_file'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-grok-2.0.5/lib/logstash/filters/grok.rb:372:in `add_patterns_from_files'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-grok-2.0.5/lib/logstash/filters/grok.rb:368:in `add_patterns_from_files'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-grok-2.0.5/lib/logstash/filters/grok.rb:263:in `register'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-grok-2.0.5/lib/logstash/filters/grok.rb:259:in `register'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-grok-2.0.5/lib/logstash/filters/grok.rb:255:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:174:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:174:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/pipeline.rb:126:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/agent.rb:210:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/runner.rb:90:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.2.4-java/lib/logstash/runner.rb:95:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:warn}`
