### ISSUE TITLE
[5.0] jruby-openssl dependency bug 

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5177]
see: https://logstash-ci.elastic.co/job/elastic+logstash+5.0+multijob-intake/30/console

```
This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.8/userguide/gradle_daemon.html
[plugin:install-core] Installing core plugins
Installing logstash-filter-clone, logstash-filter-mutate, logstash-filter-multiline, logstash-input-generator, logstash-input-stdin, logstash-input-tcp, logstash-output-stdout
Installation successful
[plugin:install-development-dependencies] Installing development dependencies of all installed plugins
Installing logstash-devutils, logstash-input-generator, logstash-codec-json, logstash-output-null, logstash-filter-mutate, flores, rspec, stud, pry, rspec-wait, childprocess, ftw, logstash-output-elasticsearch, rspec-sequencing, gmetric, gelf, timecop, jdbc-derby, docker-api, logstash-codec-plain, simplecov, coveralls, longshoreman, rumbster, logstash-filter-kv, logstash-filter-ruby, sinatra, webrick, poseidon, logstash-output-lumberjack, webmock, logstash-codec-line
Installation successful
rake aborted!
Gem::LoadError: You have already activated jruby-openssl 0.9.16, but your Gemfile requires jruby-openssl 0.9.13. Prepending `bundle exec` to your command may solve this.
/var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:34:in `setup'
/var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:19:in `setup'
/var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122:in `setup'
/var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/lib/bootstrap/bundler.rb:64:in `setup!'
/var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-intake/rakelib/test.rake:15:in `(root)'
Tasks: TOP => test:core => test:setup
(See full trace by running task with --trace)
<<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
```

**Comment by purbon** [comment]
This test are failing because of a unreleased logstash-core snapshot, when this happen this test will be green again, hope.
