### ISSUE TITLE
Redis input plugin with pattern_channel settings breaks --auto-reload

### ISSUE THREAD

**Issue by Qile** [elastic/logstash#5222]
When using redis input plugin and using channels (pub/sub) logstash is unable to reload configuration settings.
- Version: logstash 2.3.1 and redis 3.0.7
- Operating System: CentOS 7
- Config File:
  `input {
  redis {
    host => "localhost"
    data_type => "pattern_channel"
    key => "*"
    batch_count => 100
  }
  }`

After config file is changed, logstash ouputs:
`logstash    | stopping pipeline {:id=>"main"}`

But nothing happens afterwards, but it still working as usual.

Update:

After some long time logstash detects slowdown in shutdown process due to plugin:

```
logstash-indexer    | stopping pipeline {:id=>"main"}
logstash-indexer    | {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>16, "name"=>"[main]<redis", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/connection/ruby.rb:52:in `select'"}], ["LogStash::Filters::Mutate", {"remove_field"=>["count", "fields", "input_type"], "add_tag"=>"fields_cleared"}]=>[{"thread_id"=>23, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:309:in `synchronize'"}, {"thread_id"=>24, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:309:in `synchronize'"}, {"thread_id"=>25, "name"=>"[main]>worker2", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:218:in `synchronize'"}, {"thread_id"=>26, "name"=>"[main]>worker3", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:309:in `synchronize'"}]}} {:level=>:warn}
logstash-indexer    | {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>16, "name"=>"[main]<redis", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/redis-3.2.2/lib/redis/connection/ruby.rb:52:in `select'"}], ["LogStash::Filters::Mutate", {"remove_field"=>["count", "fields", "input_type"], "add_tag"=>"fields_cleared"}]=>[{"thread_id"=>23, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:309:in `synchronize'"}, {"thread_id"=>24, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:309:in `synchronize'"}, {"thread_id"=>25, "name"=>"[main]>worker2", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:218:in `synchronize'"}, {"thread_id"=>26, "name"=>"[main]>worker3", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.1-java/lib/logstash/pipeline.rb:309:in `synchronize'"}]}} {:level=>:warn}
logstash-indexer    | The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information. {:level=>:error}
```

**Comment by jsvd** [comment]
I confirm this, only when using the `pattern_channel` type. When using both list and channel types, the plugin is able to properly shutdown and pipeline is able to restart.

**Comment by jsvd** [comment]
I opened https://github.com/redis/redis-rb/issues/674 on the redis client side to find more about this behaviour
