### ISSUE TITLE
Crash in java.lang.NegativeArraySizeException

### ISSUE THREAD

**Issue by marek-obuchowicz** [elastic/logstash#5339]
I have observer that our logstash receiver (recieves message from network, does basic filtering, saves them in redis list) very often crashes with outOfMemory error (even with 16gb of heap). During while having `--debug` options i had to wait long to reproduce the issue... It finally happened, with another output as outOfMemoryError.

Exception:

```
16:34:19 - Exception in thread "[main]>worker0" java.lang.NegativeArraySizeException
at org.jruby.util.ByteList.grow(ByteList.java:1095)
at org.jruby.util.ByteList.append(ByteList.java:542)
at org.jruby.util.Sprintf.rubySprintfToBuffer(Sprintf.java:278)
at org.jruby.util.Sprintf.rubySprintfToBuffer(Sprintf.java:241)
at org.jruby.util.Sprintf.rubySprintf(Sprintf.java:237)
at org.jruby.util.Sprintf.sprintf(Sprintf.java:229)
at org.jruby.RubyString.inspect19(RubyString.java:2523)
at org.jruby.RubyString$INVOKER$i$0$0$inspect19.call(RubyString$INVOKER$i$0$0$inspect19.gen)
at org.jruby.RubyClass.finvoke(RubyClass.java:624)
at org.jruby.runtime.Helpers.invoke(Helpers.java:502)
at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:356)
at org.jruby.RubyObject.inspect(RubyObject.java:533)
at org.jruby.RubyHash$5.visit(RubyHash.java:816)
at org.jruby.RubyHash.visitLimited(RubyHash.java:648)
at org.jruby.RubyHash.visitAll(RubyHash.java:634)
at org.jruby.RubyHash.inspectHash19(RubyHash.java:811)
at org.jruby.RubyHash.inspect19(RubyHash.java:848)
at org.jruby.RubyHash$INVOKER$i$0$0$inspect19.call(RubyHash$INVOKER$i$0$0$inspect19.gen)
at org.jruby.RubyClass.finvoke(RubyClass.java:624)
at org.jruby.runtime.Helpers.invoke(Helpers.java:502)
at org.jruby.RubyBasicObject.callMethod(RubyBasicObject.java:356)
at org.jruby.RubyObject.inspect(RubyObject.java:533)
at org.jruby.RubyHash$5.visit(RubyHash.java:816)
at org.jruby.RubyHash.visitLimited(RubyHash.java:648)
at org.jruby.RubyHash.visitAll(RubyHash.java:634)
at org.jruby.RubyHash.inspectHash19(RubyHash.java:811)
at org.jruby.RubyHash.inspect19(RubyHash.java:848)
at org.jruby.RubyHash$INVOKER$i$0$0$inspect19.call(RubyHash$INVOKER$i$0$0$inspect19.gen)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:134)
at rubyjit.Cabin::Outputs::IO$$\=\^\^_a759d2d46347217e5f0d618914b90c91265cea161442407170.block_0$RUBY$__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/outputs/io.rb:52)
at rubyjit$Cabin::Outputs::IO$$\=\^\^_a759d2d46347217e5f0d618914b90c91265cea161442407170$block_0$RUBY$__file__.call(rubyjit$Cabin::Outputs::IO$$\=\^\^_a759d2d46347217e5f0d618914b90c91265cea161442407170$block_0$RUBY$__file__)
at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
at org.jruby.runtime.Block.yield(Block.java:142)
at org.jruby.ext.thread.Mutex.synchronize(Mutex.java:149)
at org.jruby.ext.thread.Mutex$INVOKER$i$0$0$synchronize.call(Mutex$INVOKER$i$0$0$synchronize.gen)
at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
at rubyjit.Cabin::Outputs::IO$$\=\^\^_a759d2d46347217e5f0d618914b90c91265cea161442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/outputs/io.rb:50)
at rubyjit.Cabin::Outputs::IO$$\=\^\^_a759d2d46347217e5f0d618914b90c91265cea161442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/outputs/io.rb)
at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
at org.jruby.runtime.callsite.ShiftLeftCallSite.call(ShiftLeftCallSite.java:24)
at rubyjit.Cabin::Subscriber$$\=\^\^_10bd20586d047ca25f2f05ebf603ebf4af74e6dd1442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/subscriber.rb:10)
at rubyjit.Cabin::Subscriber$$\=\^\^_10bd20586d047ca25f2f05ebf603ebf4af74e6dd1442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/subscriber.rb)
at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
at org.jruby.runtime.callsite.ShiftLeftCallSite.call(ShiftLeftCallSite.java:24)
at rubyjit.Cabin::Channel$$publish_2fedc2a9a4a36f3ad01bf44594d627e37af6b87f1442407170.block_2$RUBY$__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/channel.rb:196)
at rubyjit$Cabin::Channel$$publish_2fedc2a9a4a36f3ad01bf44594d627e37af6b87f1442407170$block_2$RUBY$__file__.call(rubyjit$Cabin::Channel$$publish_2fedc2a9a4a36f3ad01bf44594d627e37af6b87f1442407170$block_2$RUBY$__file__)
at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
at org.jruby.runtime.Block.yield(Block.java:142)
at org.jruby.RubyHash$13.visit(RubyHash.java:1355)
at org.jruby.RubyHash.visitLimited(RubyHash.java:648)
at org.jruby.RubyHash.visitAll(RubyHash.java:634)
at org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1306)
at org.jruby.RubyHash.each_pairCommon(RubyHash.java:1351)
at org.jruby.RubyHash.each19(RubyHash.java:1342)
at org.jruby.RubyHash$INVOKER$i$0$0$each19.call(RubyHash$INVOKER$i$0$0$each19.gen)
at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
at rubyjit.Cabin::Channel$$publish_2fedc2a9a4a36f3ad01bf44594d627e37af6b87f1442407170.block_1$RUBY$__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/channel.rb:193)
at rubyjit$Cabin::Channel$$publish_2fedc2a9a4a36f3ad01bf44594d627e37af6b87f1442407170$block_1$RUBY$__file__.call(rubyjit$Cabin::Channel$$publish_2fedc2a9a4a36f3ad01bf44594d627e37af6b87f1442407170$block_1$RUBY$__file__)
at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:135)
at org.jruby.runtime.Block.yield(Block.java:142)
at org.jruby.ext.thread.Mutex.synchronize(Mutex.java:149)
at org.jruby.ext.thread.Mutex$INVOKER$i$0$0$synchronize.call(Mutex$INVOKER$i$0$0$synchronize.gen)
at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:143)
at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:154)
at rubyjit.Cabin::Channel$$publish_2fedc2a9a4a36f3ad01bf44594d627e37af6b87f1442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/channel.rb:192)
at rubyjit.Cabin::Channel$$publish_2fedc2a9a4a36f3ad01bf44594d627e37af6b87f1442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/channel.rb)
at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
at rubyjit.Cabin::Mixins::Logger$$_log_7fdc38c37c12878271fb87e534608dca474b95f51442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/mixins/logger.rb:113)
at rubyjit.Cabin::Mixins::Logger$$_log_7fdc38c37c12878271fb87e534608dca474b95f51442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/mixins/logger.rb)
at org.jruby.ast.executable.AbstractScript.__file__(AbstractScript.java:46)
at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:221)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
at rubyjit.Cabin::Mixins::Logger$$log_with_level_318771d99629138c44ee765dd7cdf03012b82f861442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/mixins/logger.rb:90)
at rubyjit.Cabin::Mixins::Logger$$log_with_level_318771d99629138c44ee765dd7cdf03012b82f861442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/mixins/logger.rb)
at org.jruby.ast.executable.AbstractScript.__file__(AbstractScript.java:50)
at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:261)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:236)
at org.jruby.ast.FCallThreeArgNode.interpret(FCallThreeArgNode.java:40)
at org.jruby.ast.IfNode.interpret(IfNode.java:116)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
at org.jruby.runtime.Block.call(Block.java:101)
at org.jruby.RubyProc.call(RubyProc.java:300)
at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:214)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
at org.jruby.ast.AndNode.interpret(AndNode.java:97)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
at org.jruby.runtime.Block.call(Block.java:101)
at org.jruby.RubyProc.call(RubyProc.java:300)
at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:64)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:210)
at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:206)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
at rubyjit.LogStash::Pipeline$$filter_batch_0b21c86b210b64a38e10430dce5d7faf239ce9691442407170.block_0$RUBY$__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:267)
at rubyjit$LogStash::Pipeline$$filter_batch_0b21c86b210b64a38e10430dce5d7faf239ce9691442407170$block_0$RUBY$__file__.call(rubyjit$LogStash::Pipeline$$filter_batch_0b21c86b210b64a38e10430dce5d7faf239ce9691442407170$block_0$RUBY$__file__)
at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:159)
at org.jruby.runtime.CompiledBlock19.yield(CompiledBlock19.java:145)
at org.jruby.runtime.Block.yieldArray(Block.java:158)
at org.jruby.RubyEnumerable$25.call(RubyEnumerable.java:835)
at org.jruby.runtime.CallBlock.yield(CallBlock.java:90)
at org.jruby.runtime.Block.yield(Block.java:142)
at org.jruby.RubyArray.eachCommon(RubyArray.java:1606)
at org.jruby.RubyArray.each(RubyArray.java:1613)
at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
at org.jruby.RubyClass.finvoke(RubyClass.java:528)
at org.jruby.runtime.Helpers.invoke(Helpers.java:486)
at org.jruby.RubyEnumerable.callEach(RubyEnumerable.java:98)
at org.jruby.RubyEnumerable.injectCommon(RubyEnumerable.java:831)
at org.jruby.RubyEnumerable.inject(RubyEnumerable.java:852)
at org.jruby.RubyEnumerable$INVOKER$s$inject.call(RubyEnumerable$INVOKER$s$inject.gen)
at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:177)
at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:188)
at rubyjit.LogStash::Pipeline$$filter_batch_0b21c86b210b64a38e10430dce5d7faf239ce9691442407170.chained_0_rescue_1$RUBY$SYNTHETIC__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:265)
at rubyjit.LogStash::Pipeline$$filter_batch_0b21c86b210b64a38e10430dce5d7faf239ce9691442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb)
at rubyjit.LogStash::Pipeline$$filter_batch_0b21c86b210b64a38e10430dce5d7faf239ce9691442407170.__file__(/opt/logstash-2.3.2/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb)
at org.jruby.internal.runtime.methods.JittedMethod.call(JittedMethod.java:181)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:168)
at org.jruby.ast.FCallOneArgNode.interpret(FCallOneArgNode.java:36)
at org.jruby.ast.LocalAsgnNode.interpret(LocalAsgnNode.java:123)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.ast.WhileNode.interpret(WhileNode.java:131)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
at org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
at org.jruby.runtime.Block.call(Block.java:101)
at org.jruby.RubyProc.call(RubyProc.java:300)
at org.jruby.RubyProc.call(RubyProc.java:230)
at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:99)
at java.lang.Thread.run(Thread.java:745)
```

Logstash debug logs:

```
{:timestamp=>"2016-05-20T16:33:35.000Z", :message=>"Date parsing done", :value=>"May 20 16:33:35", :level=>:debug, :file=>"logstash/filters/date.rb", :line=>"348", :method=>"filter"}
{:timestamp=>"2016-05-20T16:33:52.000Z", :message=>"Date parsing done", :value=>"May 20 16:33:52", :level=>:debug, :file=>"logstash/filters/date.rb", :line=>"348", :method=>"filter"}
{:timestamp=>"2016-05-20T16:34:10.000Z", :message=>"Date parsing done", :value=>"May 20 16:34:10", :level=>:debug, :file=>"logstash/filters/date.rb", :line=>"348", :method=>"filter"}
{:timestamp=>"2016-05-20T16:34:20.214000+0000", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn, :file=>"logstash/inputs/beats.rb", :line=>"170", :method=>"run"}
{:timestamp=>"2016-05-20T16:34:20.714000+0000", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn, :file=>"logstash/inputs/beats.rb", :line=>"170", :method=>"run"}
{:timestamp=>"2016-05-20T16:34:21.215000+0000", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn, :file=>"logstash/inputs/beats.rb", :line=>"170", :method=>"run"}
{:timestamp=>"2016-05-20T16:34:21.715000+0000", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn, :file=>"logstash/inputs/beats.rb", :line=>"170", :method=>"run"}
```

logstash configs:

```
input {
  beats {
    port => 5043
    ssl => true
    ssl_certificate => "/etc/logstash/ssl/lumberjack.crt"
    ssl_key => "/etc/logstash/ssl/lumberjack.key"
  }
  syslog {
    port => 5514
    type => "syslog"
  }
}


# Add default values if field does not exist
filter {
  if ![environment] {
    mutate {
      add_field => { "environment" => "-" }
    }
  }
  if ![type] {
    mutate {
      add_field => { "type" => "unknown" }
    }
  }
  if ![subtype] {
    mutate {
      add_field => { "subtype" => "unknown" }
    }
  }
}

# sp text messages - use filename as subtype
filter {
  if [type] == "sp" and [subtype] != "lumberjack" and [subtype] != "elasticsearch" {
    grok {
      match => { "file" => "%{GREEDYDATA}/%{GREEDYDATA:filename}\.log" }
    }
    mutate {
      replace => { "subtype" => "%{filename}" }
    }
  }
}

# Handle multi-line messages (to preserve line ordering)
filter {
  if [type] == "sp" {
    if [subtype] == "exception" or [subtype] == "timeout" or [subtype] == "builder_missing" {
      multiline {
        pattern => "-------"
        negate => true
        what => previous
        stream_identity => "%{host}.%{file}.%{type}.%{subtype}.%{environment}"
      }
    }

    # Jenkins multi-line messages
    if [subtype] == "jenkins" {
      multiline {
        pattern => "^%{MONTH} %{MONTHDAY}, %{YEAR} %{TIME} (AM|PM)"
        negate => true
        what => previous
        stream_identity => "%{host}.%{file}.%{type}.%{subtype}.%{environment}"
      }
    }
  }
}

# Handle message objects from rsyslog
filter {
  if [type] == "syslog" {
    # Strip newline at the end of message
    ruby { code => "event['message'].chomp!" }
    mutate {
      replace => {
        "host" => "%{logsource}"
        "subtype" => "%{facility_label}"
      }
      gsub => [ "subtype", "/", "_" ]
    }
  }
}
output {

  redis {
    host => "127.0.0.1"
    workers => 1
    key => "elk:incoming"
    data_type => "list"
    congestion_threshold => 2000000
    congestion_interval => 10
  }
}
```

Versions:

```
logstash: 2.3.2
OpenJDK build 1.8.0_72-internal-b15
OS: Debian 8, kernel 3.16.7-ckt11-1+deb8u5
```

**Comment by suyograo** [comment]
@marek-obuchowicz thanks for the info. Can you also get us a jmap heap dump when this is happening? 

`jmap -heap:format=b <process-id>`

**Comment by jordansissel** [comment]
The reported error `Exception in thread "[main]>worker0" java.lang.NegativeArraySizeException` is, from my experience, more likely to be a symptom of an OOM than the cause of an OOM.

I don't know anything about what logs are going through your config. It's possible to OOM Logstash, I think, with the multiline filter if you have it misconfigured such that it buffers endlessly waiting for the end of an event that is never seen.

Without more data, I don't think this is a bug. Will need more data to diagnose things. A heap dump just before the OOM would be helpful. Watching Java's GC behavior would help also (maybe run with gc logging also?)

**Comment by marek-obuchowicz** [comment]
The last output of GC log is following:
``
23.391: Total time for which application threads were stopped: 1.9477592 seconds, Stopping threads took: 0.0001034 seconds
39.162: Total time for which application threads were stopped: 15.7698981 seconds, Stopping threads took: 0.0001005 seconds
39.163: [GC (CMS Initial Mark) [1 CMS-initial-mark: 4864223K(5609920K)] 4864789K(6223360K), 0.0010622 secs] [Times: user=0.01 sys=0.00, real=0.00 secs]
39.164: Total time for which application threads were stopped: 0.0024968 seconds, Stopping threads took: 0.0008006 seconds
39.164: [CMS-concurrent-mark-start]
39.176: Total time for which application threads were stopped: 0.0006993 seconds, Stopping threads took: 0.0001574 seconds
39.178: Total time for which application threads were stopped: 0.0007281 seconds, Stopping threads took: 0.0002637 seconds
39.179: Total time for which application threads were stopped: 0.0005378 seconds, Stopping threads took: 0.0001262 seconds
39.191: Total time for which application threads were stopped: 0.0007014 seconds, Stopping threads took: 0.0001590 seconds
39.192: Total time for which application threads were stopped: 0.0006085 seconds, Stopping threads took: 0.0002040 seconds
39.195: Total time for which application threads were stopped: 0.0005021 seconds, Stopping threads took: 0.0000681 seconds
39.195: Total time for which application threads were stopped: 0.0004846 seconds, Stopping threads took: 0.0001101 seconds
39.238: [CMS-concurrent-mark: 0.069/0.074 secs] [Times: user=0.45 sys=0.01, real=0.08 secs]
39.239: [CMS-concurrent-preclean-start]
39.259: Total time for which application threads were stopped: 0.0036219 seconds, Stopping threads took: 0.0028774 seconds
39.264: [CMS-concurrent-preclean: 0.018/0.026 secs] [Times: user=0.17 sys=0.00, real=0.02 secs]
39.264: [CMS-concurrent-abortable-preclean-start]
39.367: Total time for which application threads were stopped: 0.0007203 seconds, Stopping threads took: 0.0001301 seconds
39.367: Total time for which application threads were stopped: 0.0005771 seconds, Stopping threads took: 0.0001984 seconds
39.369: Total time for which application threads were stopped: 0.0005280 seconds, Stopping threads took: 0.0001542 seconds
39.370: Total time for which application threads were stopped: 0.0005566 seconds, Stopping threads took: 0.0001934 seconds
39.374: [Full GC (System.gc()) 39.374: [CMS39.379: [CMS-concurrent-abortable-preclean: 0.022/0.115 secs] [Times: user=0.26 sys=0.00, real=0.12 secs]
 (concurrent mode interrupted): 4864223K->2980460K(5609920K), 0.6334846 secs] 4929440K->2980460K(6223360K), [Metaspace: 45218K->45218K(1089536K)], 0.6343804 secs] [Times: user=0.64 sys=0.00, real=0.64 secs]
40.009: Total time for which application threads were stopped: 0.6349772 seconds, Stopping threads took: 0.0000977 seconds
Heap
 par new generation   total 613440K, used 9093K [0x0000000640000000, 0x0000000669990000, 0x0000000669990000)
  eden space 545344K,   1% used [0x0000000640000000, 0x00000006408e15c0, 0x0000000661490000)
  from space 68096K,   0% used [0x0000000665710000, 0x0000000665710000, 0x0000000669990000)
  to   space 68096K,   0% used [0x0000000661490000, 0x0000000661490000, 0x0000000665710000)
 concurrent mark-sweep generation total 5609920K, used 2980460K [0x0000000669990000, 0x00000007c0000000, 0x00000007c0000000)
 Metaspace       used 45292K, capacity 47988K, committed 48248K, reserved 1089536K
  class space    used 7305K, capacity 8042K, committed 8144K, reserved 1048576K
```

I have also `heapdump.hprof` file - its size is ca 5GB. I prefer not to publish the file - it can contain fragment of logs with business critical data, like customer names. I can either start jhat and give you access to web interface or upload it to any location of your suggestion, which is not public. Please contact me on e-mail associated with my github account, i'd be happy to provide as much information as I can

**Comment by suyograo** [comment]
@marek-obuchowicz any reason why you are not using multiline processing capabilities in beats?

**Comment by marek-obuchowicz** [comment]
We do not use beats, we use logstash-forwarder

**Comment by marek-obuchowicz** [comment]
I have just commented out all filters using multiline filter, the same issue is happening.

**Comment by suyograo** [comment]
I can't see your email from GH profile. Can you send an email to suyog at elastic.co and I'll send you details of S3 location

**Comment by marek-obuchowicz** [comment]
I have managed to keep logstash running during last night, but I had to significantly reduce number of logstash-forwarders pushing data to it. With smaller load it seems to handle the data without issues. I would bet something with either concurrency of beats input (with SSL), or issues with redis output (it should be really fast, we're writing to redis instance on localhost, so no slowdowns expected here)

**Comment by marek-obuchowicz** [comment]
Heapdump is uploaded to the s3 bucket pointed by support, let me know if anything else could come as help here

**Comment by suyograo** [comment]
@marek-obuchowicz thanks. got the heap dump. Will analyze shortly.
