### ISSUE TITLE
Failling test on master concerning metric,

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5400]
```

--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.7.1 - omit version 2.7.1-1
Using Accessor#strict_set for specs
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}
....................................................Updating dummy
Plugin foo version 9.0.0.0 does not exist
....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Validating dummy
ERROR: Configuration reloading also requires passing a configuration path with '-f yourlogstash.conf'
..............................F...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

Failures:

  1) LogStash::Pipeline when collecting metrics in the pipeline global metric populates the differents
     Failure/Error: expect(collected_metric[:stats][:events][:in].value).to eq(number_of_events)
       
       expected: 1000
            got: 1049
       
       (compared using ==)
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/logstash-core/spec/logstash/pipeline_spec.rb:618:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/rakelib/test.rake:42:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:248:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:78:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'

Finished in 36.37 seconds (files took 3.48 seconds to load)
1330 examples, 1 failure

Failed examples:

rspec /var/lib/jenkins/workspace/elastic+logstash+master+multijob-os-compatibility/os/centos/logstash-core/spec/logstash/pipeline_spec.rb:617 # LogStash::Pipeline when collecting metrics in the pipeline global metric populates the differents

Randomized with seed 8085

**Comment by ph** [comment]
At the moment of the expectation only one pipeline is running in the background. So It may be corrupted before?

**Comment by jsvd** [comment]
not sure..I'm also seeing https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-os-compatibility/os=ubuntu/lastBuild/console, but can't replicate locally

**Comment by ph** [comment]
There is a lot of failure related to the metric in the link log output. OK and the `IO closed` for the log.

I am able to replicate the one in the description 50% of the time with the seed.

**Comment by ph** [comment]
I think I will just go ahead and do https://github.com/elastic/logstash/issues/5366

**Comment by ph** [comment]
OK, just add the latest to this issue, in some trace you have multiple pipeline runing and in other you don't.. The easiest thing and the more safe thing is go ahead with #5366, So this will make this situation impossible and the reset will be controlled by the agent.

```
[5] pry(#<RSpec::ExampleGroups::LogStashPipeline::WhenCollectingMetricsInThePipeline::GlobalMetric>)> PIPELINE_LIST.keys[0].config_str
=> "input { generator {count => 0} } output { }"
```
