### ISSUE TITLE
branch 5.0 core tests failing

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#5434]
https://travis-ci.org/elastic/logstash/builds/134732394

```
rake test:install-core  102.80s user 5.56s system 59% cpu 3:03.54 total
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.7.1 - omit version 2.7.0
--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.7.1 - omit version 2.7.1-1
Using Accessor#strict_set for specs
rake aborted!
NameError: uninitialized constant LogStash::Api::RackApp::ApiErrorHandler
/Users/joaoduarte/projects/logstash/logstash-core/spec/api/lib/rack_app_spec.rb:26:in `(root)'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:325:in `subclass'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/example_group.rb:219:in `describe'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/dsl.rb:41:in `describe'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/dsl.rb:79:in `describe'
/Users/joaoduarte/projects/logstash/logstash-core/spec/api/lib/rack_app_spec.rb:4:in `(root)'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1:in `(root)'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
/Users/joaoduarte/projects/logstash/vendor/bundle/jruby/1.9/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
/Users/joaoduarte/projects/logstash/rakelib/test.rake:42:in `(root)'
Tasks: TOP => test:core
```

@andrewvc I believe ef18693 is missing in 5.0?

**Comment by jsvd** [comment]
this is also likely due to 5.0 branch using a fixed version of core gems, but launching the specs from the local git repo.

**Comment by purbon** [comment]
most probably is because of using core from unreleased snapshot, so looking forward to finally get https://github.com/elastic/logstash/issues/5416 (see Plugins test section) so we test with core code 👍, all this been unecessary pain we're seen here.

**Comment by suyograo** [comment]
Released a new snapshot.
