### ISSUE TITLE
JavaEvent#set should allow to pass a JavaMapProxy as a value

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5465]
When working on the netty rewrite of the beats input I came across this issue when implementing the codecs and doing merges of values from a hash.

When you pass a `JavaMapProxy` to the set method it currently doesn't work because the Javafier doesn't know how to handle that kind of value. As noted by @guyboertje it should also handle the case of `ArrayMapProxy`.

```
java.lang.IllegalArgumentException: Missing Ruby class handling for full class name=org.jruby.java.proxies.MapJavaProxy, simple name=MapJavaProxy
	at com.logstash.Javafier.deep(Javafier.java:111)
	at com.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_set_field(JrubyEventExtLibrary.java:159)
	at com.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$2$0$ruby_set_field.gen)
	at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:66)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
	at org.jruby.ast.FCallTwoArgNode.interpret(FCallTwoArgNode.java:38)
```
cc @guyboertje @colinsurprenant

**Comment by guyboertje** [comment]
and ConcreteJavaProxy for List objects.
