### ISSUE TITLE
Error in the api tests in Jenkins (Build broken)

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5478]
Bug seen in https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-intake/196/console 

```
  2) LogStash::Api::Modules::NodeStats GET / should set 'process.mem.total_virtual_in_bytes' to be a 'Numeric'
     Failure/Error: path_value = path.reduce(payload) {|acc,v| acc[v]}
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/logstash-core/spec/api/lib/api/support/resource_dsl_methods.rb:31:in `test_api'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/logstash-core/spec/api/lib/api/support/resource_dsl_methods.rb:31:in `test_api'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/rakelib/test.rake:42:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:248:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:243:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/task.rb:173:in `invoke'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:150:in `invoke_task'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:106:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:115:in `run_with_threads'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:100:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:78:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:176:in `standard_exception_handling'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-11.1.2/lib/rake/application.rb:75:in `run'

Finished in 42.62 seconds (files took 2.67 seconds to load)
1179 examples, 2 failures
```

**Comment by jakelandis** [comment]
Closing as this hasn't been seen for quite while, and major changes to the testing infra have been implemented since this was logged.
