### ISSUE TITLE
ubuntu-1604 issues in acceptance testing with installation and update

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5504]
seen at https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/label=metal,suite=debian/22/console

 ```
Failures:

  1) artifacts operation behaves like installable is running on ubuntu-1604
     Failure/Error: expect(logstash).to be_running
       expected #<ServiceTester::Artifact:0x5149f008 @host="127.0.0.1:2202", @client=#<ServiceTester::Ubuntu1604Commands:0x7072bc39>, @options={"host"=>"ubuntu-1604", "type"=>"debian"}> to be running
     Shared Example Group: "installable" called from /var/lib/jenkins/workspace/elastic+logstash+master+multijob-acceptance/label/metal/suite/debian/qa/acceptance/spec/lib/artifact_operation_spec.rb:12
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-acceptance/label/metal/suite/debian/qa/acceptance/spec/shared_examples/installed.rb:17:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-acceptance/label/metal/suite/debian/qa/Rakefile:58:in `(root)'

  2) artifacts operation behaves like updated can be updated an run on ubuntu-1604
     Failure/Error: expect(logstash).to be_running
       expected #<ServiceTester::Artifact:0x5149f008 @host="127.0.0.1:2202", @client=#<ServiceTester::Ubuntu1604Commands:0x7072bc39>, @options={"host"=>"ubuntu-1604", "type"=>"debian"}> to be running
     Shared Example Group: "updated" called from /var/lib/jenkins/workspace/elastic+logstash+master+multijob-acceptance/label/metal/suite/debian/qa/acceptance/spec/lib/artifact_operation_spec.rb:13
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-acceptance/label/metal/suite/debian/qa/acceptance/spec/shared_examples/updated.rb:23:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-acceptance/label/metal/suite/debian/qa/Rakefile:58:in `(root)'

Finished in 52 minutes 21 seconds (files took 1.04 seconds to load)
72 examples, 2 failures, 4 pending
```

**Comment by purbon** [comment]
<img width="991" alt="screen shot 2016-06-15 at 16 38 03" src="https://cloud.githubusercontent.com/assets/68540/16084208/38c26d32-3318-11e6-8bfd-7c2d07396425.png">

@untergeek this is basically the error I'm seeing, where basically systemctl is getting stuck for this distro and logstash, it only terminates when I do it manually, otherwise it hangs. Do you have an idea why this might happen? thanks a lot.

@suyograo ubuntu-1604, together with other distros like fedora does not really belong to our immediate stacks of testing, what I'm proposing is we do acceptance testing for our distros in the matrix, but include another level with stuff like this one, just for sure feature, you know. What do you think?

**Comment by purbon** [comment]
for me it really looks like it's trying to start logstash to know is it running.

**Comment by untergeek** [comment]
I do not know, @purbon.  What plugins are running when `systemctl status logstash.service` is called?  It always came right back for me, but that was with just a tcp input, and stdout output running.

**Comment by purbon** [comment]
no plugins, fresh install.

**Comment by untergeek** [comment]
Something is up, then.  I will try to run it manually with a built package on my system, but won't be able to get to it until tomorrow.

**Comment by purbon** [comment]
sure, no problem. What I'm thinking is to actually do acceptance testing strictly with the set of OS's in support matrix and keep this _just for the feature_ stuff in other layer, but then I'm afraid It might led to have less attention. What do you think @suyograo ?

**Comment by purbon** [comment]
@untergeek any improvements on this so we can bring ubuntu-16 back to the testing stack?

**Comment by untergeek** [comment]
I haven't been able to touch it yet.  I'll try to get to it today.

**Comment by purbon** [comment]
no hurry, this was just me doing housekeeping of tickets :-p let me know
when you get a clever idea on this issue :-)
