### ISSUE TITLE
Failed spec in master on the hot_threads api module

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#5556]
I can't replicate this consistently:

```
Failures:

  1) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm the default metadata should include the http address
     Failure/Error: expect(payload["http_address"]).to eql("#{Socket.gethostname}:#{::LogStash::WebServer::DEFAULT_PORT}")

       expected: "Joaos-MBP.lan:9600"
            got: "Joaos-MBP:9600"

       (compared using eql?)
     # ./logstash-core/spec/api/lib/api/support/resource_dsl_methods.rb:38:in `test_api'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.8/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/exe/rake:27:in `(root)'

Finished in 1 minute 46.63 seconds (files took 3.22 seconds to load)
1461 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/api/lib/api/support/resource_dsl_methods.rb:37 # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm the default metadata should include the http address

Randomized with seed 29570
```

**Comment by suyograo** [comment]
Not reproducing anymore on tests
