### ISSUE TITLE
Listener died (Gelf) - logstash 2.3.2 

### ISSUE THREAD

**Issue by Arnros** [elastic/logstash#5697]
Hi,

I have a logstash collector with input in gelf and output Redis.

Sometimes the listener died : 
```
{:timestamp=>"2016-07-26T22:00:56.628000+0200", :message=>"gelf listener died", :exception=>#<NoMethodError: undefined method `[]=' for nil:NilClass>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-2.0.7/lib/logstash/inputs/gelf.rb:130:in `new_event'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-2.0.7/lib/logstash/inputs/gelf.rb:113:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-gelf-2.0.7/lib/logstash/inputs/gelf.rb:77:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:342:in `inputworker'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.2-java/lib/logstash/pipeline.rb:336:in `start_input'"], :level=>:warn
```

I want to try to upgrade logstash-input-gelf plugin to try if it fix the previous error but I have another error : 

```
/opt/logstash/bin/plugin update logstash-input-gelf
The use of bin/plugin is deprecated and will be removed in a feature release. Please use bin/logstash-plugin.
You are updating logstash-input-gelf to a new version 3.0.2, which may not be compatible with 2.0.7. are you sure you want to proceed (Y/N)?

Y
No plugin updated
```

Centos 6.7
Logstash 2.3.2
logstash-input-gelf 2.0.7
Redis 3.0.7

My configuration :

````
input {
 gelf {
  type => "gelf"
  port => "12201"
 }
}

output {
 redis {
  host => "127.0.0.1"
  data_type => "list"
  key => "logstash"
 }
}
````

**Comment by suyograo** [comment]
@Arnros `/opt/logstash/bin/plugin update logstash-input-gelf` should update the plugin if you said yes.

**Comment by Arnros** [comment]
I have tried with "yes" but same result :

```` 
/opt/logstash/bin/logstash-plugin update logstash-input-gelf
You are updating logstash-input-gelf to a new version 3.0.2, which may not be compatible with 2.0.7. are you sure you want to proceed (Y/N)?
yes
No plugin updated
````

**Comment by AGirin** [comment]
https://github.com/elastic/logstash/issues/5727
