### ISSUE TITLE
`rake test:integration` is failing

### ISSUE THREAD

**Issue by talevy** [elastic/logstash#5744]
Looks like the tests under `spec/integration` were moved. this move is causing `rake test:integration` to fail.

error:

```
21) bin/logstash-plugin uninstall when the plugin isn't installed fails to uninstall it
     Failure/Error: result = command("bin/logstash-plugin uninstall logstash-filter-cidr")
     IOError:
       Cannot run program "bin/logstash-plugin" (in directory "/Users/tal/Code/es/talevy-logstash/spec"): error=2, No such fi
le or directory
     # ./spec/integration/support/integration_test_helpers.rb:40:in `command'
     # ./spec/integration/support/integration_test_helpers.rb:39:in `command'
     # ./vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:245:in `with_clean_env'
     # ./vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:232:in `with_original_env'
     # ./vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:238:in `with_clean_env'
     # ./spec/integration/support/integration_test_helpers.rb:38:in `command'
     # ./spec/integration/plugin_manager/plugin_uninstall_spec.rb:7:in `(root)'
     # ./rakelib/test.rake:115:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/exe/rake:27:in `(root)'
```

sidenote: looks like the path can be resolved by updating the relative path here to join with `../..`: https://github.com/elastic/logstash/blob/bf12902496033cde6a34e9ff6d1f3bf0861a30cc/spec/integration/spec_helper.rb#L29

Doing this does not make the tests pass though... but it does look like logstash is executing though.

**Comment by suyograo** [comment]
Do we need these tests at all?

**Comment by purbon** [comment]
@suyograo @ph If we're happy with having this test only at the acceptance layer yes, however not sure if we're all happy with having to bootstrap a VM to run the tests, basically because it takes time. This test might be interesting to keep if we like to run them locally.

**Comment by ph** [comment]
@purbon @suyograo I would be more than happy to only have them with the acceptance layer for 3 reasons.

1. I've ported them from the rsync behavior to the VM.
2. The VM are actually closer to the real world since we use real package which isn't the case with theses tests.
3. The VM tests are actually run on jenkins.

So if everyone agree with this removing them I would make a PR to clean it.

**Comment by suyograo** [comment]
@ph lets clean up. No point having the same test in 2 places.
