### ISSUE TITLE
6 core test failures on Windows

### ISSUE THREAD

**Issue by LeeDr** [elastic/logstash#5749]
- Version: master logstash 5.0.0-alpha5
- Operating System: Windows 10 64 bit
- Config File (if you have sensitive info, please remove it): see master
- Sample Data: n/a
- Steps to Reproduce:
1. git clone this repo
2. follow steps in README
3. run `rake test:core`

Output:

```
c:\git\logstash>jruby -v
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_73-b02 +jit [Windows 10-amd64]

c:\git\logstash>gem list

*** LOCAL GEMS ***

jar-dependencies (0.2.6)
jruby-openssl (0.9.16 java)
jruby-win32ole (0.8.5)
json (1.8.0 java)
rake (10.1.0)
rdoc (4.1.2)


c:\git\logstash>rake test:core
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :unix=>true}
..........................................................................................................................................................................................
Plugin foo version 9.0.0.0 does not exist
............................................................................................................................
ERROR: Configuration reloading also requires passing a configuration path with '-f yourlogstash.conf'
.....The signal HUP is in use by the JVM and will not work correctly on this platform
........The signal HUP is in use by the JVM and will not work correctly on this platform
..................................................................................FF............................................................Updating dummy
................................................................................................................................................................................................................................................................................................................................................................................................................
................................................................................................................................................................................................................................................................................................................................................................................................................
................................................................................................................................................................................................................................................................................................................................................................FF..............................................
..............................FF................................................................................................................................................................................................................................................................................................................................................................................
....Validating dummy
..............................................................................................................................................................................................................................................

Failures:

  1) LogStash::Api::Modules::Node#hot threads when asking for human output should return a text/plain content type
     Failure/Error: do_request { get "/hot_threads?human" }
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/api/commands/hot_threads_reporter.rb:24:in `to_s'
     # ./logstash-core/lib/logstash/api/commands/hot_threads_reporter.rb:18:in `to_s'
     # ./logstash-core/lib/logstash/api/app_helpers.rb:21:in `respond_with'
     # ./logstash-core/lib/logstash/api/modules/node.rb:22:in `HEAD /hot_threads'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `compile!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `route!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `route!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `process_route'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `route!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `dispatch!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # ./vendor/bundle/jruby/1.9/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # ./vendor/bundle/jruby/1.9/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # ./logstash-core/spec/api/lib/api/node_spec.rb:44:in `(root)'
     # ./logstash-core/spec/api/spec_helper.rb:77:in `do_request'
     # ./logstash-core/spec/api/lib/api/node_spec.rb:44:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/exe/rake:27:in `(root)'

  2) LogStash::Api::Modules::Node#hot threads when asking for human output should return a plain text payload
     Failure/Error: do_request { get "/hot_threads?human" }
     NoMethodError:
       undefined method `each' for nil:NilClass
     # ./logstash-core/lib/logstash/api/commands/hot_threads_reporter.rb:24:in `to_s'
     # ./logstash-core/lib/logstash/api/commands/hot_threads_reporter.rb:18:in `to_s'
     # ./logstash-core/lib/logstash/api/app_helpers.rb:21:in `respond_with'
     # ./logstash-core/lib/logstash/api/modules/node.rb:22:in `HEAD /hot_threads'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `compile!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `route!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `route!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `process_route'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `route!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `dispatch!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
     # ./vendor/bundle/jruby/1.9/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
     # ./vendor/bundle/jruby/1.9/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # ./vendor/bundle/jruby/1.9/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # ./vendor/bundle/jruby/1.9/gems/rack-test-0.6.3/lib/rack/test.rb:58:in `get'
     # ./logstash-core/spec/api/lib/api/node_spec.rb:44:in `(root)'
     # ./logstash-core/spec/api/spec_helper.rb:77:in `do_request'
     # ./logstash-core/spec/api/lib/api/node_spec.rb:44:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/exe/rake:27:in `(root)'

  3) LogStash::Event using hash input from deserialized json behaves like all event tests #sprintf #encoding should return unknown patterns as UTF-8
     Failure/Error: expect(subject.sprintf("%{unkown_pattern}").encoding).to eq(Encoding::UTF_8)

       expected: #<Encoding:UTF-8>
            got: #<Encoding:Windows-1252>

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -#<Encoding:UTF-8>
       +#<Encoding:Windows-1252>
     Shared Example Group: "all event tests" called from ./logstash-core-event/spec/logstash/event_spec.rb:582
     # ./logstash-core-event/spec/logstash/event_spec.rb:194:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/exe/rake:27:in `(root)'

  4) LogStash::Event using hash input from deserialized json behaves like all event tests #sprintf #encoding should return known patterns as UTF-8
     Failure/Error: expect(subject.sprintf("%{message}").encoding).to eq(Encoding::UTF_8)

       expected: #<Encoding:UTF-8>
            got: #<Encoding:Windows-1252>

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -#<Encoding:UTF-8>
       +#<Encoding:Windows-1252>
     Shared Example Group: "all event tests" called from ./logstash-core-event/spec/logstash/event_spec.rb:582
     # ./logstash-core-event/spec/logstash/event_spec.rb:190:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/exe/rake:27:in `(root)'

  5) LogStash::Event using normal hash input behaves like all event tests #sprintf #encoding should return unknown patterns as UTF-8
     Failure/Error: expect(subject.sprintf("%{unkown_pattern}").encoding).to eq(Encoding::UTF_8)

       expected: #<Encoding:UTF-8>
            got: #<Encoding:Windows-1252>

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -#<Encoding:UTF-8>
       +#<Encoding:Windows-1252>
     Shared Example Group: "all event tests" called from ./logstash-core-event/spec/logstash/event_spec.rb:574
     # ./logstash-core-event/spec/logstash/event_spec.rb:194:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/exe/rake:27:in `(root)'

  6) LogStash::Event using normal hash input behaves like all event tests #sprintf #encoding should return known patterns as UTF-8
     Failure/Error: expect(subject.sprintf("%{message}").encoding).to eq(Encoding::UTF_8)

       expected: #<Encoding:UTF-8>
            got: #<Encoding:Windows-1252>

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -#<Encoding:UTF-8>
       +#<Encoding:Windows-1252>
     Shared Example Group: "all event tests" called from ./logstash-core-event/spec/logstash/event_spec.rb:574
     # ./logstash-core-event/spec/logstash/event_spec.rb:190:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.2.2/exe/rake:27:in `(root)'

Finished in 1 minute 50.97 seconds (files took 8.81 seconds to load)
2309 examples, 6 failures

Failed examples:

rspec ./logstash-core/spec/api/lib/api/node_spec.rb:49 # LogStash::Api::Modules::Node#hot threads when asking for human output should return a text/plain content type
rspec ./logstash-core/spec/api/lib/api/node_spec.rb:53 # LogStash::Api::Modules::Node#hot threads when asking for human output should return a plain text payload
rspec ./logstash-core-event/spec/logstash/event_spec.rb:193 # LogStash::Event using hash input from deserialized json behaves like all event tests #sprintf #encoding should return unknown patterns as UTF-8
rspec ./logstash-core-event/spec/logstash/event_spec.rb:189 # LogStash::Event using hash input from deserialized json behaves like all event tests #sprintf #encoding should return known patterns as UTF-8
rspec ./logstash-core-event/spec/logstash/event_spec.rb:193 # LogStash::Event using normal hash input behaves like all event tests #sprintf #encoding should return unknown patterns as UTF-8
rspec ./logstash-core-event/spec/logstash/event_spec.rb:189 # LogStash::Event using normal hash input behaves like all event tests #sprintf #encoding should return known patterns as UTF-8

Randomized with seed 63106


c:\git\logstash>
```

**Comment by jordansissel** [comment]
We dropped this, sorry.

This is for 5.0.0-alpha (long since released). Closing, but we can reopen if it's still a problem.
