### ISSUE TITLE
Logstash config file not reading environment variable

### ISSUE THREAD

**Issue by dkirrane** [elastic/logstash#5821]
I upgraded from Docker image `2.3.0-1` to `2.3.4-1` and logstash config file can no longer read env variable

- Operating System: `logstash:2.3.4-1` Docker image running on Ubuntu 14:04

Config file has following
```
output {
    elasticsearch {
        hosts   => ["${HOST_IP}:9200"]
    }
}
```

When I exec into the container I can see the the env variable is set
```
# docker exec -it logstash bash
# echo ${HOST_IP}
1.2.3.4
```

The docker log:
```
# docker logs --follow logstash
{:timestamp=>"2016-08-24T14:23:25.048000+0000", :message=>"Pipeline aborted due to error", :exception=>#<LogStash::ConfigurationError: Host '${HOST_IP}:9200' was specified, but is not valid! Use either a full URL or a hostname:port string!>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:170:in `host_to_url'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "org/jruby/RubyArray.java:2414:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:44:in `build'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch.rb:134:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:14:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473:in `start_pipeline'"], :level=>:error}
```

**Comment by andrewvc** [comment]
@dkirrane have you confirmed this bug by just downloading a zip and using this locally?

This is most likely a bug with the docker image which we do not ourselves support. If you can confirm that is the case we'd be glad to take a look.

**Comment by ph** [comment]
@dkirrane IIRC 2.3.0 was doing environment variable interpolation by default, because of bugs and edge cases we have reverted that choice and you now have to start logstash with `--allow-env` to use environments variables in your configuration.

**Comment by ph** [comment]
@dkirrane The docker image you are using is probably not starting logstash with `--allow-env`

**Comment by dkirrane** [comment]
Yes that works. thanks
