### ISSUE TITLE
InterruptedRegexpError

### ISSUE THREAD

**Issue by Danko90** [elastic/logstash#5851]
Hello guys,

I'm experiencing a problem with Logstash 2.3.3 about InterruptedRegexpError on Ubuntu Server 14.04.
This is the error:

`{:timestamp=>"2016-08-25T14:27:11.667000+0200", :message=>"Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.", "exception"=>#<InterruptedRegexpError: Regexp Interrupted>, "backtrace"=>["org/jruby/RubyRegexp.java:1657:in `=~'", "/opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:114:in `each_address'", "/opt/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:97:in `getaddress'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.1.3/lib/logstash/filters/dns.rb:249:in `getaddress'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.1.3/lib/logstash/filters/dns.rb:238:in `retriable_getaddress'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.1.3/lib/logstash/filters/dns.rb:216:in `retriable_request'", "org/jruby/ext/timeout/Timeout.java:115:in `timeout'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.1.3/lib/logstash/filters/dns.rb:215:in `retriable_request'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.1.3/lib/logstash/filters/dns.rb:237:in `retriable_getaddress'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.1.3/lib/logstash/filters/dns.rb:120:in `resolve'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.1.3/lib/logstash/filters/dns.rb:103:in `resolve'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.1.3/lib/logstash/filters/dns.rb:91:in `filter'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/filters/base.rb:151:in `multi_filter'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/filters/base.rb:148:in `multi_filter'", "(eval):1845:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1842:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):1862:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1857:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):1884:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1874:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):1924:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1913:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):845:in `filter_func'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:267:in `filter_batch'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:852:in `inject'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:265:in `filter_batch'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:223:in `worker_loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.3-java/lib/logstash/pipeline.rb:201:in `start_workers'"], :level=>:error}`

This is the snippet of the configuration file about the DNS resolution:
`
 mutate {
                                        add_field => [ "host_ip", "%{host}" ]
                                }

 if [host_ip] !~ /^[\d]*\.[\d]*\.[\d]*\.[\d]*$/ {

                                        dns {
                                                resolve => ["host_ip"]
                                                action => "replace"
                                                timeout => 1
                                                nameserver => ["127.0.0.1"]
                                        }

                                        if [host_ip] == [] or [host_ip] !~ /^[\d]*\.[\d]*\.[\d]*\.[\d]*$/ {
                                                mutate {
                                                        remove_field => ["host_ip"]
                                                }
                                        }
                                }
`
On the server there is bind9 that performs the dns query (that's why the nameserver is localhost).
Has anyone ever had this problem?

Thanks in advance.

Danilo

**Comment by andrewvc** [comment]
This is most likely caused by a regexp that is running very slowly. This is most likely related to https://github.com/logstash-plugins/logstash-filter-grok/pull/88 

There seems to be an issue where the interrupted exception is bubbling up directly.

**Comment by andrewvc** [comment]
I take this back actually, its not grok its something to do with https://github.com/logstash-plugins/logstash-filter-dns/blob/e9f56be6cc0f1164c407d16762951df853ea596f/lib/logstash/filters/dns.rb#L249 I'll take a look

**Comment by andrewvc** [comment]
@Danko90 do you know what the value is of the `host_ip` field when this exception is thrown?

This is a cross-thread raise so it will be tricky to track down.

**Comment by jordansissel** [comment]
The exception comes from the dns filter. Possible that some kind of timeout is expiring during execution? The timer uses wallclock, not cpu cycles, so maybe Logstash was starved for resources and couldn't finish the dns lookup in time?

Hard to tell without more data. Is this reproducible?

**Comment by andrewvc** [comment]
@jordansissel I went looking for a timeout but couldn't find one in dns.rb . Do you know of one that I missed? These cross thread exceptions leave to trace by definition!

**Comment by jordansissel** [comment]
@andrewvc Stack trace has this:

```
`retriable_request'",
"org/jruby/ext/timeout/Timeout.java:115:in
`timeout'",
"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-dns-2.1.3/lib/logstash/filters/dns.rb:215:in
`retriable_request'",
```

retriable_request uses Timeout::timeout - https://github.com/logstash-plugins/logstash-filter-dns/blob/v2.1.3/lib/logstash/filters/dns.rb#L215-L217

**Comment by Danko90** [comment]
@jordansissel I don't know exactly the host_ip value but it's an hostname coming from Bro. I checked all logs values of Bro given by searching for that timestamp as well, but there weren't malformed values or something like that.
@jordansissel probably you're right about the Logstash resources. I have bind9 as DNS local cache but I didn't set any timeout on logstash.. I don't know if there's an internal timeout on it.
Unfortunately this kind of error is not reproducible very easy.. I got it twice for the first time after several months and the config is always the same.
Is there some way to handle that exception in order to avoid another crash of logstash?

Thanks for the responses.
Danilo

**Comment by Danko90** [comment]
Hello,

any news? Could anyone help me to handle this issue?

Thanks,
Regards

**Comment by andrewvc** [comment]
@Danko90 sorry this slipped through the cracks. I believe all the interrupted regex errors have been fixed in 5.x for a while. Have you experienced this problem recently?

**Comment by Daniel314** [comment]
I'm still seeing occasional problems that are very similar.  Here's a sample output I get from Logstash, version 5.4.3 (reformatted slightly for readability):

{"exception"=>"Regexp Interrupted"
,"backtrace"=>["org/jruby/RubyRegexp.java:1657:in `=~'"
,"org/jruby/RubyString.java:1729:in `=~'"
,"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-kv-4.0.0/lib/logstash/filters/kv.rb:335:in `has_value_splitter?'"
,"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-kv-4.0.0/lib/logstash/filters/kv.rb:351:in `parse'"
,"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-filter-kv-4.0.0/lib/logstash/filters/kv.rb:310:in `filter'"
,"/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:145:in `do_filter'"
,"/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:164:in `multi_filter'"
,"org/jruby/RubyArray.java:1613:in `each'"
,"/usr/share/logstash/logstash-core/lib/logstash/filters/base.rb:161:in `multi_filter'"
,"/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:43:in `multi_filter'"
,"(eval):27302:in `initialize'"
,"org/jruby/RubyArray.java:1613:in `each'"
,"(eval):27298:in `initialize'"
,"org/jruby/RubyProc.java:281:in `call'"
,"(eval):3643:in `filter_func'"
,"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:370:in `filter_batch'"
,"org/jruby/RubyProc.java:281:in `call'"
,"/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:224:in `each'"
,"org/jruby/RubyHash.java:1342:in `each'"
,"/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:223:in `each'"
,"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:369:in `filter_batch'"
,"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:350:in `worker_loop'"
,"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:317:in `start_workers'"]
}

I see this error about once a week.  It doesn't always happen in the kv module.

Thanks,

**Comment by Daniel314** [comment]
If no one minds me piggybacking on this issue, I'm seeing this error in LogStash 5.4.3 as well... I see some form of this error (there are 2-3 ways LH 5.4.3 crashes, all regarding "interrupted regex") 1-3 times a week.

**Comment by jordansissel** [comment]
@Daniel314 Can you open a new issue with full details (your config, full log, etc)?

**Comment by Daniel314** [comment]
Jordan,

At this point I've moved on to a new version of Logstash (from 5.4.3 to 5.6.2) and modified my config slightly, and since then I have experienced very few errors.  I no longer have the old crash logs.

I'm pretty sure the reason I was experiencing errors in LogStash 5.4.3 was specifically related to the Kafka input plugin and its default batch size.
In particular, the kafka input plugin defaults to a very large size for its batches, and in Logstash 5.6.2 I saw messages in the log about batches taking excessively long to process (with a message about a stalled/starved Kafka batch thread) and a hint to reduce the batch size.  Once I specified a modest kafka batch size (max_poll_records => 128), I've only experienced a couple of crashes since then, and they were for different reasons.

If you would still like me to open an issue about this, all I can provide is my LogStash config and a couple of notes about my environment...

	- Daniel
