### ISSUE TITLE
logstash 2.3.4 java.lang.InternalError

### ISSUE THREAD

**Issue by yccphp** [elastic/logstash#5860]
elasticsearch version : 2.3.5
logstash version : 2.3.4
system version : CentOS 7
java -version
```
java version "1.7.0_111"
OpenJDK Runtime Environment (rhel-2.6.7.2.el7_2-x86_64 u111-b01)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)
```

`conf file`

```

input {
    redis {
        type => "php-error"
        host => "127.0.0.1"
        port => "6379"
        db => "6"
        data_type => "list"
        key => "php-error"
    }
    redis {
        type => "nginx-log"
        host => "127.0.0.1"
        port => "6379"
        db => "6"
        data_type => "list"
        key => "nginx-log"
    }
}
output {
    if [type] == "php-error" {
        elasticsearch {
            hosts => ["localhost:9200"]
            index => "php-error-%{+YYYY.MM.dd}"
        }
    }
    if [type] == "nginx-log" {

        if [fields.status] != "200" {
            elasticsearch {
                hosts => ["localhost:9200"]
                index => "nginx-log-%{+YYYY.MM.dd}"
            }
        }
    }
}

```

`run command `
```
usr/local/logstash/bin/logstash -f /usr/local/logstash/conf/central.conf
```

`error `

```

[root@iZ25n30nd86Z conf]# /usr/local/logstash/bin/logstash -f /usr/local/logstash/conf/central.conf
Settings: Default pipeline workers: 1
sun/security/ec/SunEC.java:-2:in `initialize': java.lang.InternalError
        from sun/security/ec/SunEC.java:49:in `access$000'
        from sun/security/ec/SunEC.java:61:in `run'
        from sun/security/ec/SunEC.java:58:in `run'
        from java/security/AccessController.java:-2:in `doPrivileged'
        from sun/security/ec/SunEC.java:58:in `<clinit>'
        from java/lang/reflect/Constructor.java:526:in `newInstance'
        from java/lang/Class.java:383:in `newInstance'
        from sun/security/jca/ProviderConfig.java:221:in `run'
        from sun/security/jca/ProviderConfig.java:206:in `run'
        from java/security/AccessController.java:-2:in `doPrivileged'
        from sun/security/jca/ProviderConfig.java:206:in `doLoadProvider'
        from sun/security/jca/ProviderConfig.java:187:in `getProvider'
        from sun/security/jca/ProviderList.java:233:in `getProvider'
        from sun/security/jca/ProviderList.java:331:in `getService'
        from sun/security/jca/GetInstance.java:157:in `getInstance'
        from javax/net/ssl/TrustManagerFactory.java:138:in `getInstance'
        from org/apache/http/conn/ssl/SSLContextBuilder.java:104:in `loadTrustMaterial'
        from java/lang/reflect/Method.java:606:in `invoke'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:622:in `setup_trust_store'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:602:in `ssl_socket_factory_from_options'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:394:in `pool_builder'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:402:in `pool'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/manticore-0.6.0-java/lib/manticore/client.rb:208:in `initialize'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/manticore.rb:58:in `build_client'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/manticore.rb:49:in `initialize'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:118:in `initialize'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport.rb:26:in `new'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:129:in `build_client'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:44:in `build'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch.rb:134:in `build_client'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:14:in `register'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/output_delegator.rb:75:in `register'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'
        from org/jruby/RubyArray.java:1613:in `each'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:181:in `start_workers'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/pipeline.rb:136:in `run'
        from /usr/local/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.4-java/lib/logstash/agent.rb:473:in `start_pipeline'
        from java/lang/Thread.java:745:in `run'
```

There is a solution [https://github.com/elastic/logstash/issues/5798](https://github.com/elastic/logstash/issues/5798)

`but error`

```
fetched an invalid config {:config=>"input {\n    redis {\n        type => \"php-error\"\n        host => \"127.0.0.1\"\n        port => \"6379\"\n        db => \"6\"\n        data_type => \"list\"\n        key => \"php-error\"\n    }\n    redis {\n        type => \"nginx-log\"\n        host => \"127.0.0.1\"\n        port => \"6379\"\n        db => \"6\"\n        data_type => \"list\"\n        key => \"nginx-log\"\n    }\n}\noutput {\n    if [type] == \"php-error\" {\n        elasticsearch_java {\n            hosts => [\"localhost:9200\"]\n            index => \"php-error-%{+YYYY.MM.dd}\"\n        }\n    }\n    if [type] == \"nginx-log\" {\n        elasticsearch_java {\n            hosts => [\"localhost:9200\"]\n            index => \"nginx-log-%{+YYYY.MM.dd}\"\n        }\n    }\n}\n\n", :reason=>"Couldn't find any output plugin named 'elasticsearch_java'. Are you sure this is correct? Trying to load the elasticsearch_java output plugin resulted in this error: no such file to load -- logstash/outputs/elasticsearch_java", :level=>:error}
```

please help me

**Comment by MarkOStewart** [comment]
From your error message "Couldn't find any output plugin named 'elasticsearch_java'"
have you installed the elasticsearch_java plugin into logstash?

**Comment by yccphp** [comment]
yum install java-1.8.0-openjdk -y

It works fine
