### ISSUE TITLE
Create a logstash output beats

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5867]
Since LSF is now end of life it makes sense to logstash to have a `logstash-output-beats`, this plugin could leverage the java rewrite and use the encoder in the test.  The current ruby implementation doesn't work when you have an intermediate ca in the chain, it will refuse to complete the handshake.

What need to be done:

- Share the jars between the output and the inputs.
- Add persistent connection
- Handle reconnect
- Back pressure (ack 0)

**Comment by fjiang212** [comment]
This plugin will be very useful for our cases. We have many logstash shipping instances collecting data from different the business unit and then send to kafka. The architecture is very similar to the once describe in this document(https://www.elastic.co/guide/en/logstash/5.0/deploying-and-scaling.html).  Now we have to drop message queue because infrastructure issue. Then we need to find another output to build the bridge between the logstash shipping instances and logstash indexing instance. This new plugin will be perfect fit for our case.  And I guess it will send the data to logstash indexing instance beat input and support the following features like the filebeat have:

- security

- compression

- load balance 

Could you implement it in the logstash v5.3 since I found it has been rescheduled couple times already. 

And logstash v5 have a persistent queues now. Hope this plugin + persistent quest can kind of replace the message queue to simply the whole Elastic stack architecture. 
https://www.elastic.co/guide/en/logstash/current/persistent-queues.html 


Thanks,
Feng

**Comment by ph** [comment]
@fjiang212 We don't currently have a timeline for it, buts its certainly one of our priorities.

**Comment by cgough** [comment]
First off, thanks to everyone for an excellent product (the ELK stack), and for all the work you do in making it better.

I have a pressing need to this. We are currently using `lumberjack` to ship logs from our in house `logstash` to `logstash` instances running in Amazon. 

`lumberjack` is absolutely unreliable for `logstash` to `logstash` communication. Lots of back pressure related errors.

I find it extremely odd that `logstash` has no way of doing this easily and reliably. I would use the `kinesis-output-plugin` but this is not supported in`logstash-5.2.x`. 
`fluentd` can easily do this out of the box, for instance.

Can anyone tell me how I can reliably ship filtered events from one `logstash` instance to another without using `kafka`, `redis` or `rabbitmq`? 
```
[2017-02-20T18:39:07,085][ERROR][logstash.outputs.lumberjack] Client write error, trying connect {:e=>#<RuntimeError: Whoa we shouldn't get this frame: >, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/client.rb:146:in `ack'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/client.rb:134:in `write_sync'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/client.rb:42:in `write'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-lumberjack-3.1.2/lib/logstash/outputs/lumberjack.rb:65:in `flush'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:193:in `buffer_flush'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1479:in `loop'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:110:in `buffer_initialize'"]}
[2017-02-20T18:39:16,631][ERROR][logstash.outputs.lumberjack] Client write error
```
```
[2017-02-20T18:29:51,825][WARN ][logstash.inputs.lumberjack] Lumberjack input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover. {:exception=>LogStash::CircuitBreaker::HalfOpenBreaker}
```

**Comment by ph** [comment]
@cgough is the SQS input/output an option for you until we add a beats outputs?

**Comment by cgough** [comment]
We are going to replace one of our in house logstash instances with filebeat, then move filters to the AWS instances. This should help.

I will look into SQS, that didn't even occur to me. Thanks for the quick feedback.

**Comment by jordansissel** [comment]
> [2017-02-20T18:39:07,085][ERROR][logstash.outputs.lumberjack] Client write error, trying connect {:e=>#<RuntimeError: Whoa we shouldn't get this frame: >, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/client.rb:146:in `ack'",

The above is a strange error. THe log message code:

https://github.com/elastic/ruby-lumberjack/blob/master/lib/lumberjack/client.rb#L146

```ruby
raise "Whoa we shouldn't get this frame: #{type}" if type != "A"
```

Your log message doesn't show anything for the 'type' (value read from the socket). It might be a nil value, which indicates the socket was read, but closed, so it returned nil.

If so, this indeed is probably an indication that Logstash (the receiver, beats input) is overloaded or stalled and is rejecting connections. Your Logstash with beats input should log when it is rejecting connections, but I might be remembering incorrectly.

THe output-lumberjack plugin should still work because the protocol hasn't changed in a way that rejects it, if I'm remembering right.

Anyway, we have plans to make a beats output, and will do it when we can. Hopefully for Logstash 5.5.0 time frame.

**Comment by alexef** [comment]
We are also interested in this.

**Comment by cgough** [comment]
I am presently using SQS to solve the transport issue. We run logstash instances in our hosted environment that filter the messages and insert them into SQS. Then, on the amazon side, we have simple logstash consumers which pull the filtered events from the SQS queues and insert them into elasticsearch (also running on EC2). Very pleased with the results. It is resilient for the most part. One or two minor hiccups, but overall much more reliable than using lumberjack as an intermediate transport.

**Comment by jordansissel** [comment]
> overall much more reliable than using lumberjack 

The purpose of the lumberjack (now beats) protocol is to provide reliable transport. If you are finding anything unreliable about this transport, it is a bug, not a feature, and if you have the energy, I invite you to file an issue about what you experience with these bugs.

**Comment by cgough** [comment]
Sorry if I am confusing the older lumberjack protocol with the beats protocol. I was under the assumption they were different. We have had very good luck with filebeat vs the old logstash forwarder.  @ph inquired if I was experiencing success using SQS, I was responding to this user.

Thanks for all your excellent work.

**Comment by kuyote** [comment]
I would like to add my interest in the logstash-beats-output.

**Comment by lsoumille** [comment]
Any progress on this ?

**Comment by widhalmt** [comment]
Is this still on your list?

**Comment by AnthonyJClink** [comment]
We leverage beats and logstash in an IOT project where our instance sits between low connected devices and an enrichment process we have in our data center. I feel that our product would gain quite a bit if we could push this IOT data via beats.

I would love to help with this issue if the LS team can help guide me to a possible implementation. I believe I could give it a stab.

**Comment by allamiro** [comment]
Any progress on this issue ?

**Comment by tanganellilore** [comment]
Team, any news on this?

Lumberjack output have a loto of "bugs" in CA, not allow the usage of CA, not allow to use private key for mtls and use ip address for socket instead fqdn.

I can submit some PR to add all of these features o lumberjack output and in the ruby_lumberjack, but seems that all of them are not supported and maintabed by anyone.

Let me know if I can supoort
