### ISSUE TITLE
Concurrency Error in the Webserver patches for the Logger STDERR.

### ISSUE THREAD

**Issue by ph** [elastic/logstash#5912]
https://logstash-ci.elastic.co/job/elastic+logstash+5.0+multijob-os-compatibility/143/os=amazon/console

````
ERROR: Configuration reloading also requires passing a configuration path with '-f yourlogstash.conf'
INFO: Logstash has a new settings file which defines start up time settings. This file is typically located in $LS_HOME/config or /etc/logstash. If you installed Logstash through a package and are starting it manually please specify the location to this settings file by passing in "--path.settings=/path/.." in the command line options
ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/tmp/a/a/a/a, exception=Errno::ENOENT, message=>No such file or directory - /tmp/a/a/a/a/logstash.yml
.................Validating dummy
............

Failures:

  1) LogStash::WebServer when an exception occur in the server thread should not log to STDERR
     Failure/Error: Unable to find matching line from backtrace
     ConcurrencyError:
       Detected invalid array contents due to unsynchronized modifications with concurrent users
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-os-compatibility/os/amazon/rakelib/test.rake:42:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:248:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:243:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.0+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-11.2.2/lib/rake/task.rb:187:in `invoke_with_call_chain'

**Comment by ph** [comment]
dang, its related to the hack we have made to make sure we can silence puma correctly.

**Comment by ph** [comment]
I am confused by this stacktrace and where the error was throw, the trace is from the rspec wait lib, which we don't use in the in this specific. I'm using `const_defined` to override the `STDERR`  and this operation might not be threadsafe.
