### ISSUE TITLE
Buggy --version flag usage

### ISSUE THREAD

**Issue by purbon** [elastic/logstash#5924]
Checking the version with the following command will finish with an error code,

```bash
skywalker% ./bin/logstash  --path.settings=config --version
logstash 6.0.0-alpha1
[2016-09-15T15:31:17,741][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `is_info_enabled' for #<LogStash::Logging::Logger:0x7671a060>>, :backtrace=>["/Users/purbon/work/logstash/logstash-core/lib/logstash/runner.rb:287:in `show_version'", "/Users/purbon/work/logstash/logstash-core/lib/logstash/runner.rb:217:in `execute'", "/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/Users/purbon/work/logstash/logstash-core/lib/logstash/runner.rb:174:in `run'", "/Users/purbon/work/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/Users/purbon/work/logstash/lib/bootstrap/environment.rb:68:in `(root)'"]}
skywalker% echo $?
1
```

if this is executed from package (deb/rpm), as we are not logging to stdout by default anymore the message will not be cached.

the expected output should be something like:

```bash
skywalker% ./bin/logstash  --path.settings=config --version                                      
logstash 6.0.0-alpha1
jruby 1.7.25 (1.9.3p551) 2016-04-13 867cb81 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_91-b14 +jit [darwin-x86_64]
java 1.8.0_91 (Oracle Corporation)
jvm Java HotSpot(TM) 64-Bit Server VM / 25.91-b14
skywalker% echo $?
0
```

This is one reason why acceptance jobs are failing at [logstash-ci](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/label=metal,suite=debian/123/console)

**Comment by suyograo** [comment]
Fixed in https://github.com/elastic/logstash/pull/5927
