### ISSUE TITLE
bin/plugin install --development failing

### ISSUE THREAD

**Issue by gstamp** [elastic/logstash#5994]
We have an automated build for testing out logstash config. Recently this has started failing despite there being no changes introduced. I managed to reproduce it locally easily enough. I thought maybe it was specific to our somewhat old version of logstash but I tested with 2.4.0 as well and the same error occurs.

- Version: (Tested with versions 1.5.3, 1.5.5 and 2.4.0)
- Operating System: OS/X
- Steps to Reproduce:

1. wget https://download.elastic.co/logstash/logstash/logstash-2.4.0.tar.gz
2. Change into directory logstash directory.
3.`DEBUG=1 bin/plugin install --development`

```

... output chopped ...

Gem::InstallError: docker-api requires Ruby version >= 2.0.0.
/private/tmp/logstash-2.4.0/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:560:in `ensure_required_ruby_version_met'
/private/tmp/logstash-2.4.0/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:782:in `pre_install_checks'
/private/tmp/logstash-2.4.0/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:231:in `install'
/tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/source/rubygems.rb:114:in `install'
/tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/rubygems_integration.rb:131:in `preserve_paths'
/tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/source/rubygems.rb:113:in `install'
/tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:107:in `install_gem_from_spec'
/tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:287:in `install_in_parallel'
org/jruby/RubyProc.java:281:in `call'
/tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/worker.rb:55:in `apply_func'
/tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/worker.rb:50:in `process_queue'
org/jruby/RubyKernel.java:1479:in `loop'
/tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/worker.rb:47:in `process_queue'
/tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/worker.rb:22:in `initialize'
Installing rumbster 1.1.0
3:  rumbster (1.1.0) from /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/specifications/rumbster-1.1.0.gemspec
Installing crack 0.4.3
4:  crack (0.4.3) from /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/specifications/crack-0.4.3.gemspec
Installing rspec 3.1.0
2:  rspec (3.1.0) from /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/specifications/rspec-3.1.0.gemspec
Installing term-ansicolor 1.3.2
0:  term-ansicolor (1.3.2) from /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/specifications/term-ansicolor-1.3.2.gemspec
Installing sinatra 1.4.7
1:  sinatra (1.4.7) from /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/specifications/sinatra-1.4.7.gemspec
Bundler::InstallError: An error occurred while installing docker-api (1.32.0), and Bundler cannot continue.
Make sure that `gem install docker-api -v '1.32.0'` succeeds before bundling.
  install_gem_from_spec at /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:145
    install_in_parallel at /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:287
                   call at org/jruby/RubyProc.java:281
             apply_func at /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/worker.rb:55
          process_queue at /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/worker.rb:50
                   loop at org/jruby/RubyKernel.java:1479
          process_queue at /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/worker.rb:47
             initialize at /tmp/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/worker.rb:22
```

All versions tested were failing with the same error.

**Comment by gstamp** [comment]
Error now seems to have disappeared so whatever environmental issue was causing this now seems to be fixed.
