### ISSUE TITLE
ÆØÅ in warning log message forces logstash in loop flushing duplicates

### ISSUE THREAD

**Issue by nikolaia** [elastic/logstash#6002]
- Version: 2.3.0
- Operating System: Windows
- Config File:

```
input {
    file {
        path => "C:/logs/*.json"
        start_position => "beginning"
        codec => json
    }
}
output {
    elasticsearch {
        hosts => ["localhost:9200"]
        index => "prod-%{+YYYY.MM.dd}"
    }
}
```
- Sample Data:

``` json
{"@timestamp":"2016-10-06T06:09:38.424Z","level":"Information","messageTemplate":"EventA {UserId} {@Event}","message":"Unable to find user with fødselsnummer 12345678910 { Name: \"EventA\", Id: 3100, Scope: \"AppEvent\" }","fields":{"UserId":12345678910,"Event":{"Name":"EventA","Id":3100,"Scope":"AppEvent"},"MachineName":"WEB2","ThreadId":72,"environment":"PROD"},"@version":"1"}
{"@timestamp":"2016-10-06T07:52:05.493Z","level":"Information","messageTemplate":"EventB {UserId} {@Event}","message":"Starting delete of account with fødselsnummer \"Project.Primitives.Fødselsnummer\" { Name: \"EventB\", Id: 4203, Scope: \"AppEvent\" }","fields":{"UserId":"Project.Primitives.Fødselsnummer","Event":{"Name":"EventB","Id":4203,"Scope":"AppEvent"},"MachineName":"WEB4","ThreadId":31,"environment":"PROD"},"@version":"1"}
```
- Steps to Reproduce:
  Just run with the sample data on Windows. The index will be created with UserID as a number, and message two will trigger a warning to be logged to logstashes own log. However it seems like logstash (or cabin, the logging framework) doesn't take to kindly to the Norwegian letters æøå. This is from logstash stdout:

``` ruby
incompatible encodings: Windows-1252 and UTF-8 {:class=>"Encoding::CompatibilityError", :backtrace=>["org/jruby/RubyHash.java:848:in `inspect'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/outputs/io.rb:83:in `tty_write'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/outputs/io.rb:55:in `<<'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/outputs/io.rb:50:in `<<'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/subscriber.rb:10:in `<<'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/channel.rb:196:in `publish'", "org/jruby/RubyHash.java:1342:in `each'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/channel.rb:193:in `publish'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/channel.rb:192:in `publish'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/mixins/logger.rb:113:in `_log'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/mixins/logger.rb:90:in `log_with_level'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/mixins/logger.rb:75:in `warn'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/common.rb:119:in `submit'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:974:in `each_with_index'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/common.rb:107:in `submit'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/common.rb:86:in `retrying_submit'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/common.rb:29:in `multi_receive'", "org/jruby/RubyArray.java:1653:in `each_slice'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/common.rb:28:in `multi_receive'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/output_delegator.rb:130:in `worker_multi_receive'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/output_delegator.rb:114:in `multi_receive'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:305:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:305:in `output_batch'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:236:in `worker_loop'", "C:/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.3.0-java/lib/logstash/pipeline.rb:205:in `start_workers'"], :level=>:warn, :file=>"/ProgramData/scoop/apps/logstash230/2.3.0/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.5.5-java/lib/logstash/outputs/elasticsearch/common.rb", :line=>"88", :method=>"retrying_submit"}
```

This forces logstash in a loop attempting to flush to elasticsearch, which ends up with it retrying for every, making duplicates of messages that are stuck in the same flush as the message that triggers the error. This gives us millions of duplicate documents in Elasticsearch to delete after we notice the error.

**Comment by suyograo** [comment]
@colinsurprenant @jordansissel any ideas?

**Comment by jordansissel** [comment]
This problem is with the elasticsearch output, not logstash.

I don't' know how it happens, because the file input should be forcing the text in the events to be UTF-8. This sounds like a JSON serialization problem, though it's hard to tell from the log message.

If this is easily reproducible, it should be easy to fix.

**Comment by nikolaia** [comment]
If I replace all occurrences of `ø` with `o` in the second log message of the sample data it will log the intended warning message, that it seems to be unable to log when it contains any of the characters æ ø å (triggering the retry loop):
```
Failed action.  {:status=>400, :action=>["index", {:_id=>nil, :_index=>"prod-2016.10.06", :_type=>"logs", :_routing=>nil}, 2016-10-06T07:52:05.493Z DESKTOP-HGU7PPG Starting delete of account with fodselsnummer "Project.Primitives.Fodselsnummer" { Name: "EventB", Id: 4203, Scope: "AppEvent" }], :response=>{"create"=>{"_index"=>"prod-2016.10.06", "_type"=>"logs", "_id"=>"AVedvxSumC928yd4Ylrn", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [fields.UserId]", "caused_by"=>{"type"=>"number_format_exception", "reason"=>"For input string: \"Project.Primitives.Fodselsnummer\""}}}}, :level=>:warn}
```
