### ISSUE TITLE
Logstash::Json::GeneratorError issue

### ISSUE THREAD

**Issue by marek-obuchowicz** [elastic/logstash#6015]
- Version: 2.4.0
- Operating System: Debian 8.0

After enabling `--log-as-json` option, some log messages cause Logstash to fail on writing json messages with error:
```
{"timestamp":"2016-10-10T13:45:44.245000+0000","message":"Pipeline aborted due to error","exception":"LogStash::Json::GeneratorError","backtrace":["/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logs
tash/json.rb:53:in `jruby_dump'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/logging/json.rb:15:in `<<'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/subscribe
r.rb:10:in `<<'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/channel.rb:196:in `publish'","org/jruby/RubyHash.java:1342:in `each'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin
/channel.rb:193:in `publish'","org/jruby/ext/thread/Mutex.java:149:in `synchronize'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/channel.rb:192:in `publish'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9
/gems/cabin-0.8.1/lib/cabin/mixins/logger.rb:113:in `_log'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/cabin-0.8.1/lib/cabin/mixins/logger.rb:90:in `log_with_level'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/cabin-0
.8.1/lib/cabin/mixins/logger.rb:75:in `warn'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/config/mixin.rb:81:in `config_init'","org/jruby/RubyHash.java:1342:in `each'","/opt/logstash-2.4
.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/config/mixin.rb:72:in `config_init'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/outputs/base.rb:79:in `initialize'"
,"/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/output_delegator.rb:74:in `register'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181
:in `start_workers'","org/jruby/RubyArray.java:1613:in `each'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181:in `start_workers'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.
9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'","/opt/logstash-2.4.0/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491:in `start_pipeline'"],"level":"error"}
```

After removing `--log-as-json` option, all seems fine. First log entries were:
```
{:timestamp=>"2016-10-10T13:45:53.023000+0000", :message=>"Pipeline main started"}
{:timestamp=>"2016-10-10T13:46:07.479000+0000", :message=>"Error parsing json", :source=>"message_source", :raw=>"Traceback (most recent call last):", :exception=>#<LogStash::Json::ParserError: Unrecognized token 'Traceback': was
expecting ('true', 'false' or 'null')
 at [Source: [B@3fb84a09; line: 1, column: 11]>, :level=>:warn}
{:timestamp=>"2016-10-10T13:46:07.490000+0000", :message=>"Error parsing json", :source=>"message_source", :raw=>"  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1475, in full_dispatch_request", :exception=>#<
LogStash::Json::ParserError: Unrecognized token 'File': was expecting ('true', 'false' or 'null')
 at [Source: [B@5cbf9893; line: 1, column: 8]>, :level=>:warn}
```

**Comment by guyboertje** [comment]
@marek-obuchowicz - the JSON codec is putting an instance of `LogStash::Json::ParserError` into the log statement. These instances are not JSON serialisable.

We will get around to fixing these errors after the 5.0 release. We have to track down all cases in (most) plugins and core where unserialisable objects are being used in log statements.

The one you have experienced is from the JSON codec or maybe another input that uses JSON under the hood.

More info. https://github.com/elastic/logstash/issues/4857

**Comment by marek-obuchowicz** [comment]
Thanks for the info. I suggest that until it's handled correctly, the option `--log-as-json` in 2.4.x should be marked as "experimental" (or similiar) in the documentation as switching logging format from to json can cause working logstash instances to die if unserializable object happends to appear in the log
