### ISSUE TITLE
[TEST FAILURE] LogStash::Pipeline when collecting metrics in the pipeline pipelines populates the pipelines core metrics

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6025]
https://travis-ci.org/elastic/logstash/builds/166809012

```
  1) LogStash::Pipeline when collecting metrics in the pipeline pipelines populates the pipelines core metrics
     Failure/Error: raise "Waited too long" if times > 4
     RuntimeError:
       Waited too long
     # ./logstash-core/spec/logstash/pipeline_spec.rb:602:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:42:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/exe/rake:27:in `(root)'

Finished in 3 minutes 3.8 seconds (files took 6.36 seconds to load)
1509 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/logstash/pipeline_spec.rb:624 # LogStash::Pipeline when collecting metrics in the pipeline pipelines populates the pipelines core metrics

Randomized with seed 58050
```

**Comment by jsvd** [comment]
also https://travis-ci.org/elastic/logstash/builds/167292340

**Comment by ph** [comment]
```ruby
      thread.new { subject.run }
      # make sure we have received all the generated events

      times = 0
      while dummyoutput.events.size < number_of_events
        times += 1
        sleep 0.25
        raise "waited too long" if times > 4
      end
```
I suspect that the `Thread.new { subject.run }` is not even started, on a very busy travis box this can happen. 

We should:

-  check if the thread is correct started.
- Add the number of events in the raise exception
- Add a predicate in the dummy filter to know if he was received something ;)

**Comment by suyograo** [comment]
Not reproducing anymore on tests
