### ISSUE TITLE
Redis output issues

### ISSUE THREAD

**Issue by martinbaillie** [elastic/logstash#6048]
Hi folks,

I swapped in rc1 versions of ElasticSearch, Kibana, Logstash today in my Docker-based ELK stack. I hit the following issue with the Redis output plugin. Downgrading exclusively Logstash to previous alpha based builds (keeping E and K as rc1) works. Has something gone wrong with this output? It's late and I haven't done much research but couldn't see any obvious breaking changes in the documentation. The following example is a simple single line webserver access log entry.
 
- Version: 5.0.0-rc1
- Operating System: Linux (official upstream Docker image)
- Config: -w "2" -b "1000"
      outputs: 
        redis {
          host => "redis.host"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }

- Steps to Reproduce:

```
[2016-10-13T18:21:38,098][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"0.0.0.0:5000"}
[2016-10-13T18:21:38,098][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:5001"}
[2016-10-13T18:21:38,700][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>1000, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>2000}
[2016-10-13T18:21:38,701][INFO ][logstash.pipeline        ] Pipeline main started
[2016-10-13T18:21:38,855][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2016-10-13T18:21:39,338][WARN ][logstash.outputs.redis   ] Failed to send event to Redis {:event=>2016-10-13T07:21:38.613Z environment-logging_logstash-collector_1 - - [13/Oct/2016:13:15:10 +1100] 0.002 GET /some/kind/of/file.css 200 153 - 123.123.123.123 "http://hostname/something" -, :identity=>"default", :exception=>#<NameError: no method 'debug' for arguments (org.jruby.RubyHash,org.jruby.RubyHash) on Java::OrgApacheLoggingLog4jCore::Logger
  available overloads:
    (java.lang.String,org.apache.logging.log4j.util.Supplier[])
    (org.apache.logging.log4j.Marker,java.lang.String,java.lang.Object[])
    (org.apache.logging.log4j.Marker,java.lang.String,org.apache.logging.log4j.util.Supplier[])
    (java.lang.String,java.lang.Object[])>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/logging/logger.rb:41:in `debug'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-3.0.2/lib/logstash/outputs/redis.rb:216:in `connect'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-3.0.2/lib/logstash/outputs/redis.rb:241:in `send_to_redis'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-json-3.0.2/lib/logstash/codecs/json.rb:42:in `encode'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-redis-3.0.2/lib/logstash/outputs/redis.rb:150:in `receive'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:92:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/legacy.rb:19:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:42:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:302:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:252:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:225:in `start_workers'"]}
```

**Comment by ph** [comment]
@talevy could you take a look?

**Comment by untergeek** [comment]
I'm not sure which version you're migrating from, but your worker and batch sizes are not optimized for the newest versions of Logstash. See https://www.elastic.co/blog/just_enough_redis_for_logstash for much more information, plus stats and graphs to back up the assertion. 

Long story short: you probably should do tuning of batch options in the output block, rather than `-w` and `-b` options.

**Comment by jordansissel** [comment]
This is a bug in the Redis output caused by an incorrect logging call that is now raising an exception because of our switch to log4j2, I believe.

**Comment by jordansissel** [comment]
(let's move this issue to http://github.com/logstash-plugins/logstash-output-redis)
