### ISSUE TITLE
Experimental feature --allow-env should not require quotes

### ISSUE THREAD

**Issue by SchulteMarkus** [elastic/logstash#6081]
Hi there,

I want to use Logstash's experimental feature [--allow-env](https://www.elastic.co/guide/en/logstash/current/environment-variables.html).
Nice feature!

Though, right now it requires quotes around the env-vars. 

    output {
      elasticsearch { hosts => "${ELASTICSEARCH_OUTPUT_HOSTS}" }

This example is valid and will be parsed. Though, of course not every input is possible. My input would be 

    # printenv
    ELASTICSEARCH_OUTPUT_HOSTS=['192.168.43.9:9200']

which does not work with the above example, as the env var is already quoted.

Using 

    output {
      elasticsearch { hosts => ${ELASTICSEARCH_OUTPUT_HOSTS} }

gives (excerpt)

    fetched an invalid config {:config=>"output {\n  elasticsearch { hosts => ${ELASTICSEARCH_OUTPUT_HOSTS} }\n}\n\n", :reason=>"Expected one of #, \", ', -, [, { at line 2, column 26 (byte 94)

Similar behavior for number-input:

     "port" : ${SOME_PORT} # this wont be parsed by logstash

**Comment by untergeek** [comment]
The problem here is that a dollar-sign has meaning in the configuration.  Remove the quotes, and it's going to be interpreted.  Similarly, square braces have meaning.  With quotes, it's just a string, but that cannot be interpreted properly.

I'm not sure there's a way to fix either of these scenarios without changing how Logstash parses its configuration.  One solution would require parsing the file with a secondary script before Logstash parses the configuration.  Another might require some huge hoops and coding contortions.

As we're drawing nearer to having a full Logstash configuration API, I'm not sure this will get the attention you want.  At some point, you'd be able to launch Logstash without a configuration, and import one over the API, whether all at once, or by degrees.  You'd theoretically be able to use env vars in such a case, so the solution may just be to make configuration API based.

We'll look at this, but I'm not sure it's going to be weighted heavily in our prioritizing of issues.

**Comment by SchulteMarkus** [comment]
I understand your technical estimation.
From a "user"'s point of view, --allow-env (I am not forgetting its experimental) is only useable for string-values right now.

Anyhow, you are right pointing to the future Logstash API - which would change dealing with die Logstash configuration and moving my wishes regarding environment variables to another location.

**Comment by SchulteMarkus** [comment]
I have been doing some more testing here...

[--allow-env example](https://www.elastic.co/guide/en/logstash/current/environment-variables.html)

    input {
      tcp {
        port => "${TCP_PORT}"
      }
    }

${TCP_PORT} is quoted here. I assume the example is working, so a String is somehow parsed to a number.

Concrete, I want output -> elasticsearch -> hosts to be from environment variables

    # printenv
    ELASTICSEARCH_OUTPUT_HOSTS=["1.2.3.4:9200"]

I cannot quote this JSON-array on this point. Doing so

    output {
      elasticsearch { hosts => "${ELASTICSEARCH_OUTPUT_HOSTS}" }
    }

gives

    Pipeline aborted due to error {:exception=>"LogStash::ConfigurationError", :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:170:in `host_to_url'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "org/jruby/RubyArray.java:2414:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:109:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client.rb:20:in `initialize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:44:in `build'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch.rb:134:in `build_client'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.7.1-java/lib/logstash/outputs/elasticsearch/common.rb:14:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/output_delegator.rb:75:in `register'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:181:in `start_workers'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/pipeline.rb:136:in `run'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.0-java/lib/logstash/agent.rb:491:in `start_pipeline'"], :level=>:error}

Not using quotes

    output {
      elasticsearch { hosts => ${ELASTICSEARCH_OUTPUT_HOSTS} }
    }

gives 

    fetched an invalid config {:config=>"input {\n  jmx {\n    path => \"${LOGSTASH_CONFIGURATION_DIR}/jmxconf\"\n    polling_frequency => \"${JMX_INPUT_POLLING_FREQUENCY}\"\n    type => \"jmx\"\n    nb_thread => \"${JMX_NB_THREAD}\"\n  }\n}\noutput {\n  elasticsearch { hosts => ${ELASTICSEARCH_OUTPUT_HOSTS} }\n}\n\n", :reason=>"Expected one of #, \", ', -, [, { at line 10, column 28 (byte 223) after output {\n  elasticsearch { hosts => ", :level=>:error}

**Comment by untergeek** [comment]
Yes, numerical values are tested and cast appropriately when `validate` is set to `number` or `int` or things like that in the plugin code, so `${TCP_PORT}` in quotes is acceptable.

Rather than make
```
elasticsearch { hosts => ${ELASTICSEARCH_OUTPUT_HOSTS} }
```
from 
```
ELASTICSEARCH_OUTPUT_HOSTS=["1.2.3.4:9200"]
```

What would happen if:
```
ELASTICSEARCH_OUTPUT_HOSTS="1.2.3.4:9200"
```
and then you changed your config to:
```
elasticsearch { hosts => ["${ELASTICSEARCH_OUTPUT_HOSTS}"] }
```

And I say this, not knowing whether it will work or not.  My hope is that it removes the square braces from being inside the string, and therefore not interpreted.

**Comment by SchulteMarkus** [comment]
I tried that - it works! But limits me to one elasticsearch host.

**Comment by untergeek** [comment]
If you enable sniffing, that may be enough.  If it can connect to one host, it should get the rest of the cluster state from the one it did connect to, and then round-robin the traffic to all available clients that are not master nodes.  See https://www.elastic.co/guide/en/logstash/current/plugins-outputs-elasticsearch.html#plugins-outputs-elasticsearch-sniffing

> This setting asks Elasticsearch for the list of all cluster nodes and adds them to the hosts list. Note: This will return ALL nodes with HTTP enabled (including master nodes!). If you use this with master nodes, you probably want to disable HTTP on them by setting `http.enabled` to false in their elasticsearch.yml. You can either use the `sniffing` option or manually enter multiple Elasticsearch hosts using the `hosts` parameter.

**Comment by SchulteMarkus** [comment]
You are a fox!
I will keep it in mind. Right now, I got a workaround for this issue by doing some sed-stuff. By time I will remove that workaround and use your idea.

**Comment by untergeek** [comment]
Using sed to put in extra quotes and such may be a viable workaround too.  Glad it's working for you.

**Comment by jordansissel** [comment]
Is this resolved?

**Comment by passing** [comment]
It would be nice to have a solution for providing multiple values in general
Another use case would be "host" for redis-output:
https://www.elastic.co/guide/en/logstash/current/plugins-outputs-redis.html

So it would be nice to have the possibility to explicitly pass an array to logstash for a variable that gets then properly processed on object level instead of configuration-file / string replacement level.
