### ISSUE TITLE
build logstash for a new platform--mips64el

### ISSUE THREAD

**Issue by vans88** [elastic/logstash#6111]
Hi, I am a new comer and wanna build logstash for my platform---mips64el. I got source code from github. and run the command "rake bootstrap". The results list as follows:
**The build result**
[root@dscn2 logstash]# logstash --version
logstash 6.0.0-alpha1
[root@dscn2 logstash]# logstash --help
Usage:
    bin/logstash [OPTIONS]

Options:
    -n, --node.name NAME          Specify the name of this logstash instance, if no value is given
                                  it will default to the current hostname.
                                   (default: "172.17.42.1")
    -f, --path.config CONFIG_PATH Load the logstash config from a specific file
                                  or directory.  If a directory is given, all
                                  files in that directory will be concatenated
                                  in lexicographical order and then parsed as a
                                  single config file. You can also specify
                                  wildcards (globs) and any matched files will
                                  be loaded in the order described above.
    -e, --config.string CONFIG_STRING Use the given string as the configuration
                                  data. Same syntax as the config file. If no
                                  input is specified, then the following is
                                  used as the default input:
                                  "input { stdin { type => stdin } }"
                                  and if no output is specified, then the
                                  following is used as the default output:
                                  "output { stdout { codec => rubydebug } }"
                                  If you wish to use both defaults, please use
                                  the empty string for the '-e' flag.
                                   (default: nil)
    -w, --pipeline.workers COUNT  Sets the number of pipeline workers to run.
                                   (default: 15)
    -b, --pipeline.batch.size SIZE Size of batches the pipeline is to work in.
                                   (default: 125)
    -u, --pipeline.batch.delay DELAY_IN_MS When creating pipeline batches, how long to wait while polling
                                  for the next event.
                                   (default: 5)
    --pipeline.unsafe_shutdown    Force logstash to exit during shutdown even
                                  if there are still inflight events in memory.
                                  By default, logstash will refuse to quit until all
                                  received events have been pushed to the outputs.
                                   (default: false)
    --path.data PATH              This should point to a writable directory. Logstash
                                  will use this directory whenever it needs to store
                                  data. Plugins will also have access to this path.
                                   (default: "/usr/local/logstash/data")
    -p, --path.plugins PATH       A path of where to find plugins. This flag
                                  can be given multiple times to include
                                  multiple paths. Plugins are expected to be
                                  in a specific directory hierarchy:
                                  'PATH/logstash/TYPE/NAME.rb' where TYPE is
                                  'inputs' 'filters', 'outputs' or 'codecs'
                                  and NAME is the name of the plugin.
                                   (default: [])
    -l, --path.logs PATH          Write logstash internal logs to the given
                                  file. Without this flag, logstash will emit
                                  logs to standard output.
                                   (default: "/usr/local/logstash/logs")
    --log.level LEVEL             Set the log level for logstash. Possible values are:
                                    - fatal
                                    - error
                                    - warn
                                    - info
                                    - debug
                                    - trace
                                   (default: "info")
    --config.debug                Print the compiled config ruby code out as a debug log (you must also have --debug enabled).
                                  WARNING: This will include any 'password' options passed to plugin configs as plaintext, and may result
                                  in plaintext passwords appearing in your logs!
                                   (default: false)
    -i, --interactive SHELL       Drop to shell instead of running as normal.
                                  Valid shells are "irb" and "pry"
    -V, --version                 Emit the version of logstash and its friends,
                                  then exit.
    -t, --config.test_and_exit    Check configuration for valid syntax and then exit.
                                   (default: false)
    -r, --config.reload.automatic Monitor configuration changes and reload
                                  whenever it is changed.
                                  NOTE: use SIGHUP to manually reload the config
                                   (default: false)
    --config.reload.interval RELOAD_INTERVAL How frequently to poll the configuration location
                                  for changes, in seconds.
                                   (default: 3)
    --http.host HTTP_HOST         Web API binding host (default: "127.0.0.1")
    --http.port HTTP_PORT         Web API http port (default: 9600..9700)
    --log.format FORMAT           Specify if Logstash should write its own logs in JSON form (one
                                  event per line) or in plain text (using Ruby's Object#inspect)
                                   (default: "plain")
    --path.settings SETTINGS_DIR  Directory containing logstash.yml file. This can also be
                                  set through the LS_SETTINGS_DIR environment variable.
                                   (default: "/usr/local/logstash/config")
    --verbose                     Set the log level to info.
                                  DEPRECATED: use --log.level=verbose instead.
    --debug                       Set the log level to debug.
                                  DEPRECATED: use --log.level=debug instead.
    --quiet                       Set the log level to info.
                                  DEPRECATED: use --log.level=quiet instead.
    -h, --help                    print help

**But when I run the following command for test the new logstash. The error is listed at the later part;**
[root@dscn2 logstash]# logstash -e 'input { stdin { } } output { stdout {} }'
Sending Logstash logs to /usr/local/logstash/logs which is now configured via log4j2.properties.
LoadError: Unsupported platform: unknown-linux
          require at org/jruby/RubyKernel.java:1040
          require at /usr/local/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /usr/local/logstash/vendor/jruby/lib/ruby/shared/ffi/ffi.rb:69
          require at org/jruby/RubyKernel.java:1040
          require at /usr/local/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /usr/local/logstash/vendor/jruby/lib/ruby/shared/ffi.rb:1
          require at org/jruby/RubyKernel.java:1040
          require at /usr/local/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
           (root) at /usr/local/logstash/vendor/jruby/lib/ruby/shared/ffi.rb:1
           (root) at /usr/local/logstash/logstash-core/lib/logstash/util/prctl.rb:1
          require at org/jruby/RubyKernel.java:1040
          require at /usr/local/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65
             LibC at /usr/local/logstash/logstash-core/lib/logstash/util/prctl.rb:3
           (root) at /usr/local/logstash/logstash-core/lib/logstash/util/prctl.rb:2
           (root) at /usr/local/logstash/logstash-core/lib/logstash/util.rb:1
  set_thread_name at /usr/local/logstash/logstash-core/lib/logstash/util.rb:20
          execute at /usr/local/logstash/logstash-core/lib/logstash/runner.rb:204
           (root) at /usr/local/logstash/lib/bootstrap/environment.rb:68

**Comment by untergeek** [comment]
The libffi library is going to be your big hurdle to compiling for any other platform (ARM64, MIPS, SPARC, etc).  Without the ffi library, you'll get the errors you already reported.  

See if you can get ffi compiled, and/or look at other people's journey trying to compile/use Logstash on less supported platforms.

**Comment by vans88** [comment]
Via the google.com. I realize the reason is my platform mips64el is not supported by jruby jffi. I run the commands as follows:

**For Debug**
[root@dscn2 logstash]# rpm -qa jffi*
jffi-1.2.7-5.fc21.loongson.mips64el
jffi-native-1.2.7-5.fc21.loongson.mips64el
[root@dscn2 logstash]# rpm -ql jffi-native
/usr/lib/java/jffi-native.jar
/usr/lib/java/jffi/jffi-native.jar
/usr/lib64/jffi
/usr/lib64/jffi/mips64-Linux
/usr/lib64/jffi/mips64-Linux/libjffi-1.2.so
/usr/lib64/jffi/mips64-Linux/libjffi.so
/usr/share/doc/jffi-native
/usr/share/doc/jffi-native/COPYING.GPL
/usr/share/doc/jffi-native/COPYING.LESSER
/usr/share/doc/jffi-native/LICENSE
/usr/share/maven-metadata/jffi-native.xml

**In the vendor/jruby/lib/jni dir I get the list of the following dirs:**

[root@dscn2 jni]# ls
arm-Linux  i386-Linux  i386-Windows  ppc64le-Linux  ppc-AIX        x86_64-FreeBSD  x86_64-SunOS
Darwin     i386-SunOS  **_mips64-Linux_**  ppc64-Linux    sparcv9-SunOS  x86_64-Linux    x86_64-
Windows

So I copy the /usr/lib64/jffi/mips64-Linux/libjffi-1.2.so to the  mips64_Linux (created manually). but the error is still exists

**Comment by vans88** [comment]
OK, many thanks for your reply. I will build ffi libray instantly.

**Comment by vans88** [comment]
Hi untergeek, I am confused that the software  libffi have installed by manually. 

[root@dscn2 logstash]# rpm -qa libffi*
libffi-3.1-7.fc21.loongson.1.mipsel
libffi-3.1-7.fc21.loongson.1.mips64el
libffi-devel-3.1-7.fc21.loongson.1.mips64el
[root@dscn2 logstash]# rpm -ql libffi
/usr/lib64/libffi.so.6
/usr/lib64/libffi.so.6.0.2
/usr/share/doc/libffi
/usr/share/doc/libffi/README
/usr/share/licenses/libffi
/usr/share/licenses/libffi/LICENSE
/usr/lib/libffi.so.6
/usr/lib/libffi.so.6.0.2
/usr/share/doc/libffi
/usr/share/doc/libffi/README
/usr/share/licenses/libffi
/usr/share/licenses/libffi/LICENSE

But the error is still exists.

**Comment by untergeek** [comment]
I'm not 100% sure, but either JRuby or Java, or both need to be compiled aware of that library.

**Comment by untergeek** [comment]
You could try compiling your own JRuby locally

**Comment by vans88** [comment]
Ok, I will get the source code and build JRuby locally.

**Comment by untergeek** [comment]
Yes, but JRuby most likely must be built against that libffi in order to work.  You will probably have to build your own JRuby.  I don't have any super insights for you, but there are probably other platform related reasons for the ffi failures.  See https://logstash.jira.com/browse/LOGSTASH-665 (be sure to follow the entire thread) for how someone worked around these issues on a SPARC machine.  Not sure if your issue will be related, but it may.

**Comment by vans88** [comment]
I have installed jruby successfully  on my mips64el platform, but when  running  the command "logstash --help", I got the following error:

**The extra error:**
/usr/local/share/gems/gems/bundler-1.13.6/lib/bundler.rb:429:in `rescue in eval_gemspec':  (Bundler::GemspecError)
[!] There was an error while loading `logstash-core-plugin-api.gemspec`: The logstash-core-api need to be build on jruby. Bundler cannot continue.

 #  from /usr/local/logstash/logstash-core-plugin-api/logstash-core-plugin-api.gemspec:27
 #  -------------------------------------------
 #    else
 >      raise "The logstash-core-api need to be build on jruby"
 #    end
 #  -------------------------------------------
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler.rb:421:in `eval_gemspec'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler.rb:374:in `block in load_gemspec_uncached'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:54:in `chdir'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:54:in `block in chdir'
        from /usr/share/ruby/monitor.rb:211:in `mon_synchronize'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/shared_helpers.rb:53:in `chdir'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler.rb:369:in `load_gemspec_uncached'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler.rb:359:in `load_gemspec'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/source/path.rb:146:in `block in load_spec_files'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/source/path.rb:145:in `each'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/source/path.rb:145:in `load_spec_files'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/source/path.rb:95:in `local_specs'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/source/path.rb:103:in `specs'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:665:in `block in converge_locked_specs'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:654:in `each'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:654:in `converge_locked_specs'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:243:in `resolve'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:174:in `specs'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:233:in `specs_for'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/definition.rb:222:in `requested_specs'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/runtime.rb:118:in `block in definition_method'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler/runtime.rb:19:in `setup'
        from /usr/local/share/gems/gems/bundler-1.13.6/lib/bundler.rb:99:in `setup'
        from /usr/local/logstash/lib/bootstrap/bundler.rb:64:in `setup!'
        from /usr/local/logstash/lib/bootstrap/environment.rb:64:in `<main>'

**Comment by sgrover01** [comment]
Hi All,

Can anyone please help? My work with logstash is going round in circles. My **goal is to install the logstash-filter-mutate plugin**. When I run the following command:

`bin/logstash-plugin install --local --no-verify`

I get the error:
```
Installing...
Plugin not found, aborting
ERROR: Installation Aborted, message: Could not find gem 'ci_reporter_rspec (= 1.0.0) java' in any of the gem sources listed in your Gemfile or installed on this machine.
```

I have installed the ci_reporter_rspec gem. But when I run the bundle command, I see the same JRUBY error, which is listed above. The server I am working on has no access to the internet. I'd greatly appreciate your advice. See JRUBY error below:

```
[!] There was an error while loading `logstash-core-plugin-api.gemspec`: The logstash-core-api need to be build on jruby. Bundler cannot continue.

 #  from /opt/grovers_poc/logstash-5.5.2-build1/logstash-core-plugin-api/logstash-core-plugin-api.gemspec:27
 #  -------------------------------------------
 #    else
 >      raise "The logstash-core-api need to be build on jruby"
 #    end
 #  -------------------------------------------
```
