### ISSUE TITLE
pipeline spec failure in #6152 PR against 5.x

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#6154]
This is a random/intermittent failure that showed up when trying to reproduce another problem in #6152

```
Failures:
  1) LogStash::Pipeline defaulting the pipeline workers based on thread safety when there are threadsafe filters only starts multiple filter threads
     Failure/Error: expect(pipeline.worker_threads.size).to eq(worker_thread_count)
       
       expected: 5
            got: 8
       
       (compared using ==)
     # ./logstash-core/spec/logstash/pipeline_spec.rb:251:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:49:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/exe/rake:27:in `(root)'
Finished in 3 minutes 8 seconds (files took 6.39 seconds to load)
1944 examples, 1 failure, 1 pending
Failed examples:
rspec ./logstash-core/spec/logstash/pipeline_spec.rb:248 # LogStash::Pipeline defaulting the pipeline workers based on thread safety when there are threadsafe filters only starts multiple filter threads
Randomized with seed 61027
```

**Comment by andrewvc** [comment]
@colinsurprenant at a glance it looks like that test is asking the pipeline to have exactly 5 worker threads but for some reason 8 are created. My best guess: the user setting is being ignored or the test isn't passing in the argument correctly anymore.

**Comment by suyograo** [comment]
Not reproducing anymore on tests
