### ISSUE TITLE
Agent spec failure in #6152 PR against 5.x 

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#6155]
This is a random/intermittent failure that showed up when trying to reproduce another problem in #6152

```
Failures:
  1) LogStash::Agent#execute when auto_reload is true if state is clean should periodically reload_state
     Failure/Error: expect(subject).to receive(:reload_state!).at_least(2).times
       (#<LogStash::Agent:0x820039a>).reload_state!(any args)
           expected: at least 2 times with any arguments
           received: 1 time with any arguments
     # ./logstash-core/spec/logstash/agent_spec.rb:190:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:49:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/exe/rake:27:in `(root)'
Finished in 3 minutes 4.5 seconds (files took 5.83 seconds to load)
2101 examples, 1 failure, 1 pending
Failed examples:
rspec ./logstash-core/spec/logstash/agent_spec.rb:186 # LogStash::Agent#execute when auto_reload is true if state is clean should periodically reload_state
Randomized with seed 44997
```

**Comment by ph** [comment]
@jsvd Did we encounter a similar issue a few month ago? I remember that you have run theses in a loop to find the cause?
