### ISSUE TITLE
Bug in the beats integration suite

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6185]
With the addition of more config checks it raises and issue with the beat integration test in the master branch.

```
Starting Filebeat with /home/travis/build/elastic/logstash/qa/integration/services/installed/filebeat/filebeat -c /tmp/studtmp-ab9ce0234c4719e65337260f784a895e8d1ad9ba2b21df9aa60032235040
Sending Logstash's logs to /home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logs which is now configured via log4j2.properties
[2016-11-03T17:53:18,473][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<LogStash::ConfigurationError: Using `verify_mode` set to PEER or FORCE_PEER, requires the configuration of `certificate_authorities`>, :backtrace=>["/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.8-java/lib/logstash/inputs/beats.rb:157:in `register'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:348:in `start_inputs'", "org/jruby/RubyArray.java:1613:in `each'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:347:in `start_inputs'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:223:in `start_workers'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:179:in `run'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/agent.rb:251:in `start_pipeline'"]}
[2016-11-03T17:53:18,543][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2016-11-03T17:53:21,498][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
```

travis link: https://travis-ci.org/elastic/logstash/builds/173025096

Thanks @talevy for reporting it.

**Comment by talevy** [comment]
@ph wasn't able to reproduce locally. but showed up again in another build here:

https://travis-ci.org/elastic/logstash/builds/173099252

**Comment by talevy** [comment]
I see it now. looks like I couldn't reproduce because of a lock file...


looks like the latest beats update breaks existing configs that do not explicitly provide a certificate authority

config:

```
  tls_mutual_auth: |-
    input {
      beats {
        ssl => true
        port => 5044
        ssl_certificate => '<%=options[:ssl_certificate]%>'
        ssl_key => '<%=options[:ssl_key]%>'
        ssl_verify_mode => "peer"
      }
    }
    output {}
```


and is matching this check: https://github.com/logstash-plugins/logstash-input-beats/blob/b94eba41f580a750bab31a7111177db76ae1a6aa/lib/logstash/inputs/beats.rb#L156-L158

where `ssl_certificate_authorities` is empty.

**Comment by talevy** [comment]
This is not failing in 5.0 since we didn't bump the plugin version just yet

**Comment by ph** [comment]
good finding!
