### ISSUE TITLE
Logstash 5.x resurrection not working with Elasticsearch + X-Pack

### ISSUE THREAD

**Issue by sbarrier** [elastic/logstash#6292]
On an ELK cluster using x-pack (Logstash / Elasticsearch / X-pack version 5.0.1), restart the master node (ie: maintenance/rolling restart...), ES cluster will be yellow then green after the shards recoveries, Logstash will never been able to recover till you perform a restart.

Is there some missing authentication leading to a permission issue ? like in #6254 ?

```
[2016-11-22T19:19:38,181][WARN ][logstash.outputs.elasticsearch] Error while performing resurrection {:error_message=>"Got response code '403' contact Elasticsearch at URL 'http://~hidden~:~hidden~@1.2.3.4:
9200/'", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/
outputs/elasticsearch/http_client/manticore_adapter.rb:48:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/htt
p_client/pool.rb:233:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:201:in `resur
rect_dead!'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:196:in `
resurrect_dead!'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:189:in `start_resurrectionist'", "/usr/share/
logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:117:in `until_stopped'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/l
ogstash-output-elasticsearch-5.2.1-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:188:in `start_resurrectionist'"]}
[2016-11-22T19:19:40,993][WARN ][logstash.outputs.elasticsearch] UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
[2016-11-22T19:19:40,993][ERROR][logstash.outputs.elasticsearch] Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreac
hable or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>64}

```

**Comment by suyograo** [comment]
Make sure your Logstash user has the `monitor` privilege. See https://www.elastic.co/guide/en/x-pack/current/logstash.html#ls-http-auth-basic

**Comment by sbarrier** [comment]
it missing _monitor_ role, see #6254 the documentation is incomplete.

**Comment by jsvd** [comment]
we will be adding that detail to the x-pack documentation
