### ISSUE TITLE
logstash.inputs.udp - UDP listener died

### ISSUE THREAD

**Issue by r0bj** [elastic/logstash#6312]
logstash: 5.0.1
docker: 1.12.1-0~trusty
docker image: https://hub.docker.com/_/logstash/
docker image version: 5.0.1-1
OS: Ubuntu 14.04

Logstash config:
```
input {
  udp {
    port => 1514
    type => 'syslog'
  }
}

output {
  stdout {}
}
```

Steps to reproduce:
1. start docker container with logstash
2. run traffic into logstash port 1514
3. it's working for some time generating messages on stdout
4. after some time (~1 minute depending on traffic volume) logstash exitting with log:
```14:48:02.481 [SIGTERM handler] WARN  logstash.runner - SIGTERM received. Shutting down the agent.
14:48:02.486 [LogStash::Runner] WARN  logstash.agent - stopping pipeline {:id=>"main"}
14:48:02.989 [[main]<udp] WARN  logstash.inputs.udp - UDP listener died {:exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3705:in `select'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.0.3/lib/logstash/inputs/udp.rb:77:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.0.3/lib/logstash/inputs/udp.rb:50:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:331:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:325:in `start_input'"]}
```

**Comment by r0bj** [comment]
Unrelated
