### ISSUE TITLE
logstash-input-syslog-3.2.0 error

### ISSUE THREAD

**Issue by Dave89** [elastic/logstash#6330]
Good morning everyone,

I'm having trouble with logstash-input-syslog plugin when i try to retrieve logs from a syslog server.
I have a socket error:

 `[2016-11-30T09:51:32,898][INFO ][logstash.inputs.syslog   ] Starting syslog tcp listener {:address=>"172.25.7.251:514"}
[2016-11-30T09:51:32,901][INFO ][logstash.inputs.syslog   ] Starting syslog udp listener {:address=>"172.25.7.251:514"}
[2016-11-30T09:51:32,900][WARN ][logstash.inputs.syslog   ] syslog listener died {:protocol=>:tcp, :address=>"172.25.7.251:514", :exception=>#<SocketError: initialize: name or service not known>, :backtrace=>["org/jruby/ext/socket/RubyTCPServer.java:126:in `initialize'", "org/jruby/RubyIO.java:871:in `new'", "/usr/share/logstash/vendor/local_gems/1df3aae8/logstash-input-syslog-3.2.0/lib/logstash/inputs/syslog.rb:159:in `tcp_listener'", "/usr/share/logstash/vendor/local_gems/1df3aae8/logstash-input-syslog-3.2.0/lib/logstash/inputs/syslog.rb:122:in `server'", "/usr/share/logstash/vendor/local_gems/1df3aae8/logstash-input-syslog-3.2.0/lib/logstash/inputs/syslog.rb:106:in `run'"]}
`
I'm running:

RHEL 7.1
Elasticsearch, Logstash and Kibana running on the same machine (Version 5.0.1) (user: root)
Syslog server running on a seperate machine (Rsyslog)

Config:

`input
 {
    syslog
            {
        host => "172.25.7.251" #Sylog IP Adress
            }
  }

filter { }

output {

    elasticsearch {
      hosts => [ "172.25.7.151:9200" ]
    }

}
`

Thanks in advance for your help!!!

**Comment by jsvd** [comment]
moved this issue to https://github.com/logstash-plugins/logstash-input-syslog/issues/36
