### ISSUE TITLE
Test failure in `When auto_reload is false when calling reload_pipeline`

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6341]
```
Failures:
  1) LogStash::Agent#execute when auto_reload is false when calling reload_pipeline! with a config that does not contain reload incompatible plugins does upgrade the new config
     Failure/Error: expect(subject).to receive(:upgrade_pipeline).once.and_call_original
       (#<LogStash::Agent:0x215ac1b2>).upgrade_pipeline(any args)
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./logstash-core/spec/logstash/agent_spec.rb:139:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:49:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:248:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-11.3.0/exe/rake:27:in `(root)'
Finished in 2 minutes 52.5 seconds (files took 5.15 seconds to load)
1761 examples, 1 failure
Failed examples:
rspec ./logstash-core/spec/logstash/agent_spec.rb:136 # LogStash::Agent#execute when auto_reload is false when calling reload_pipeline! with a config that does not contain reload incompatible plugins does upgrade the new config
Randomized with seed 20300
```

**Comment by andrewvc** [comment]
Suspected fixed in master, may only be happening in 5x. Closing to see if it recurs.
