### ISSUE TITLE
Test failling: LogStash::Pipeline defaulting the pipeline workers based on thread safety when there are threadsafe filters only starts multiple filter threads

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6355]
```
  1) LogStash::Pipeline defaulting the pipeline workers based on thread safety when there are threadsafe filters only starts multiple filter threads
     Failure/Error: expect(pipeline.worker_threads.size).to eq(worker_thread_count)
       
       expected: 5
            got: 8
       
       (compared using ==)
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/logstash-core/spec/logstash/pipeline_spec.rb:251:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/rakelib/test.rake:49:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:248:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:243:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:180:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/task.rb:173:in `invoke'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:152:in `invoke_task'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:108:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:117:in `run_with_threads'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:102:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:80:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/lib/rake/application.rb:77:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/ubuntu/vendor/bundle/jruby/1.9/gems/rake-11.3.0/exe/rake:27:in `(root)'

Finished in 2 minutes 46.9 seconds (files took 7.13 seconds to load)
2413 examples, 1 failure
```

see https://logstash-ci.elastic.co/job/elastic+logstash+5.x+multijob-os-compatibility/134/os=ubuntu/console

**Comment by jsvd** [comment]
this seems to be a dup of https://github.com/elastic/logstash/issues/6245

**Comment by jordansissel** [comment]
Dup of https://github.com/elastic/logstash/issues/6245 indeed
