### ISSUE TITLE
My logstash is not sending input logs to my AWS Elasticsearch

### ISSUE THREAD

**Issue by rajasekaran07** [elastic/logstash#6452]
Hello,

I have configured logstash server to collect AWS ECS container logs using gelf driver. I didnt get ant error while starting my container also I have checked my logstash logs as well i didnt see any error. Kindly suggest someone why my logs are not going to Elasticsearch.

cat /var/log/logstash/logstash-plain.log
[2016-12-21T05:01:09,971][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"0.0.0.0:12201"}
[2016-12-21T05:01:10,041][INFO ][logstash.inputs.udp      ] UDP listener started {:address=>"0.0.0.0:12201", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2016-12-21T05:01:10,503][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>["http://search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com"]}}
[2016-12-21T05:01:10,504][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:url=>#<URI::HTTP:0x6e57daf2 URL:http://search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com>, :healthcheck_path=>"/"}
[2016-12-21T05:01:10,669][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>#<URI::HTTP:0x6e57daf2 URL:http://search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com>}
[2016-12-21T05:01:10,683][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2016-12-21T05:01:10,755][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"_all"=>{"enabled"=>true, "omit_norms"=>true}, "dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"string", "index"=>"analyzed", "omit_norms"=>true, "fielddata"=>{"format"=>"disabled"}}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"string", "index"=>"analyzed", "omit_norms"=>true, "fielddata"=>{"format"=>"disabled"}, "fields"=>{"raw"=>{"type"=>"string", "index"=>"not_analyzed", "doc_values"=>true, "ignore_above"=>256}}}}}, {"float_fields"=>{"match"=>"*", "match_mapping_type"=>"float", "mapping"=>{"type"=>"float", "doc_values"=>true}}}, {"double_fields"=>{"match"=>"*", "match_mapping_type"=>"double", "mapping"=>{"type"=>"double", "doc_values"=>true}}}, {"byte_fields"=>{"match"=>"*", "match_mapping_type"=>"byte", "mapping"=>{"type"=>"byte", "doc_values"=>true}}}, {"short_fields"=>{"match"=>"*", "match_mapping_type"=>"short", "mapping"=>{"type"=>"short", "doc_values"=>true}}}, {"integer_fields"=>{"match"=>"*", "match_mapping_type"=>"integer", "mapping"=>{"type"=>"integer", "doc_values"=>true}}}, {"long_fields"=>{"match"=>"*", "match_mapping_type"=>"long", "mapping"=>{"type"=>"long", "doc_values"=>true}}}, {"date_fields"=>{"match"=>"*", "match_mapping_type"=>"date", "mapping"=>{"type"=>"date", "doc_values"=>true}}}, {"geo_point_fields"=>{"match"=>"*", "match_mapping_type"=>"geo_point", "mapping"=>{"type"=>"geo_point", "doc_values"=>true}}}], "properties"=>{"@timestamp"=>{"type"=>"date", "doc_values"=>true}, "@version"=>{"type"=>"string", "index"=>"not_analyzed", "doc_values"=>true}, "geoip"=>{"type"=>"object", "dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip", "doc_values"=>true}, "location"=>{"type"=>"geo_point", "doc_values"=>true}, "latitude"=>{"type"=>"float", "doc_values"=>true}, "longitude"=>{"type"=>"float", "doc_values"=>true}}}}}}}}
[2016-12-21T05:01:10,770][INFO ][logstash.outputs.elasticsearch] Installing elasticsearch template to _template/logstash
[2016-12-21T05:01:10,993][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com:80"]}
[2016-12-21T05:01:10,996][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>125}
[2016-12-21T05:01:10,998][INFO ][logstash.pipeline        ] Pipeline main started
[2016-12-21T05:01:11,072][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

![image](https://cloud.githubusercontent.com/assets/19193992/21379061/166e774c-c771-11e6-9389-6f4ec750aa88.png)

Kibana page:

![image](https://cloud.githubusercontent.com/assets/19193992/21379074/28c6b576-c771-11e6-9b14-0ed0fc416e41.png)

Regards,
Raja

**Comment by rajasekaran07** [comment]
My configuration file:

cat /etc/logstash/conf.d/logstash-syslog.conf
input {
  udp {
    port => 12201
    type => syslog
  }
}

output {
  elasticsearch { hosts => 'search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com:80' }
}

ECS Task definition:

**{
  "requiresAttributes": [
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.logging-driver.gelf",
      "targetId": null,
      "targetType": null
    },**
    {
      "value": null,
      "name": "com.amazonaws.ecs.capability.docker-remote-api.1.19",
      "targetId": null,
      "targetType": null
    }
  ],
  "taskDefinitionArn": "arn:aws:ecs:us-east-1:855158544446:task-definition/mytestecs:16",
  "networkMode": "bridge",
  "status": "ACTIVE",
  "revision": 16,
  "taskRoleArn": null,
  "containerDefinitions": [
    {
      "volumesFrom": [],
      "memory": 100,
      "extraHosts": null,
      "dnsServers": null,
      "disableNetworking": null,
      "dnsSearchDomains": null,
      "portMappings": [
        {
          "hostPort": 5000,
          "containerPort": 5000,
          "protocol": "tcp"
        }
      ],
      "hostname": null,
      "essential": true,
      "entryPoint": null,
      "mountPoints": [],
      "name": "pythonapp",
      "ulimits": null,
      "dockerSecurityOptions": null,
      "environment": [],
      "links": null,
      "workingDirectory": null,
      "readonlyRootFilesystem": null,
      "image": "training/webapp",
      "command": [],
      "user": null,
      "dockerLabels": null,
      **"logConfiguration": {
        "logDriver": "gelf",
        "options": {
          "gelf-address": "udp://IPADDRESS:12201"
        }
      },**
      "cpu": 25,
      "privileged": null,
      "memoryReservation": null
    }
  ],
  "placementConstraints": [],
  "volumes": [],
  "family": "mytestecs"
}


Regards,
Raja

**Comment by rajasekaran07** [comment]
My Logstash logs...

root@ip-172-31-23-78:/home/ubuntu# cat /var/log/logstash/logstash-plain.log
[2016-12-21T05:01:09,971][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"0.0.0.0:12201"}
[2016-12-21T05:01:10,041][INFO ][logstash.inputs.udp      ] UDP listener started {:address=>"0.0.0.0:12201", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2016-12-21T05:01:10,503][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>["http://search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com"]}}
[2016-12-21T05:01:10,504][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:url=>#<URI::HTTP:0x6e57daf2 URL:http://search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com>, :healthcheck_path=>"/"}
[2016-12-21T05:01:10,669][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>#<URI::HTTP:0x6e57daf2 URL:http://search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com>}
[2016-12-21T05:01:10,683][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2016-12-21T05:01:10,755][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"_all"=>{"enabled"=>true, "omit_norms"=>true}, "dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"string", "index"=>"analyzed", "omit_norms"=>true, "fielddata"=>{"format"=>"disabled"}}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"string", "index"=>"analyzed", "omit_norms"=>true, "fielddata"=>{"format"=>"disabled"}, "fields"=>{"raw"=>{"type"=>"string", "index"=>"not_analyzed", "doc_values"=>true, "ignore_above"=>256}}}}}, {"float_fields"=>{"match"=>"*", "match_mapping_type"=>"float", "mapping"=>{"type"=>"float", "doc_values"=>true}}}, {"double_fields"=>{"match"=>"*", "match_mapping_type"=>"double", "mapping"=>{"type"=>"double", "doc_values"=>true}}}, {"byte_fields"=>{"match"=>"*", "match_mapping_type"=>"byte", "mapping"=>{"type"=>"byte", "doc_values"=>true}}}, {"short_fields"=>{"match"=>"*", "match_mapping_type"=>"short", "mapping"=>{"type"=>"short", "doc_values"=>true}}}, {"integer_fields"=>{"match"=>"*", "match_mapping_type"=>"integer", "mapping"=>{"type"=>"integer", "doc_values"=>true}}}, {"long_fields"=>{"match"=>"*", "match_mapping_type"=>"long", "mapping"=>{"type"=>"long", "doc_values"=>true}}}, {"date_fields"=>{"match"=>"*", "match_mapping_type"=>"date", "mapping"=>{"type"=>"date", "doc_values"=>true}}}, {"geo_point_fields"=>{"match"=>"*", "match_mapping_type"=>"geo_point", "mapping"=>{"type"=>"geo_point", "doc_values"=>true}}}], "properties"=>{"@timestamp"=>{"type"=>"date", "doc_values"=>true}, "@version"=>{"type"=>"string", "index"=>"not_analyzed", "doc_values"=>true}, "geoip"=>{"type"=>"object", "dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip", "doc_values"=>true}, "location"=>{"type"=>"geo_point", "doc_values"=>true}, "latitude"=>{"type"=>"float", "doc_values"=>true}, "longitude"=>{"type"=>"float", "doc_values"=>true}}}}}}}}
[2016-12-21T05:01:10,770][INFO ][logstash.outputs.elasticsearch] Installing elasticsearch template to _template/logstash
[2016-12-21T05:01:10,993][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com:80"]}
[2016-12-21T05:01:10,996][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>125}
[2016-12-21T05:01:10,998][INFO ][logstash.pipeline        ] Pipeline main started
[2016-12-21T05:01:11,072][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2016-12-21T07:18:06,417][WARN ][logstash.runner          ] SIGTERM received. Shutting down the agent.
[2016-12-21T07:18:06,462][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
[2016-12-21T07:18:06,709][WARN ][logstash.inputs.udp      ] UDP listener died {:exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3705:in `select'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:93:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:56:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:359:in `start_input'"]}
[2016-12-21T08:58:15,327][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"0.0.0.0:12201"}
[2016-12-21T08:58:15,450][INFO ][logstash.inputs.udp      ] UDP listener started {:address=>"0.0.0.0:12201", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2016-12-21T08:58:15,803][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>["http://search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com"]}}
[2016-12-21T08:58:15,805][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:url=>#<URI::HTTP:0x57850ca5 URL:http://search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com>, :healthcheck_path=>"/"}
[2016-12-21T08:58:15,959][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>#<URI::HTTP:0x57850ca5 URL:http://search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com>}
[2016-12-21T08:58:15,968][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2016-12-21T08:58:16,137][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"_all"=>{"enabled"=>true, "omit_norms"=>true}, "dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"string", "index"=>"analyzed", "omit_norms"=>true, "fielddata"=>{"format"=>"disabled"}}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"string", "index"=>"analyzed", "omit_norms"=>true, "fielddata"=>{"format"=>"disabled"}, "fields"=>{"raw"=>{"type"=>"string", "index"=>"not_analyzed", "doc_values"=>true, "ignore_above"=>256}}}}}, {"float_fields"=>{"match"=>"*", "match_mapping_type"=>"float", "mapping"=>{"type"=>"float", "doc_values"=>true}}}, {"double_fields"=>{"match"=>"*", "match_mapping_type"=>"double", "mapping"=>{"type"=>"double", "doc_values"=>true}}}, {"byte_fields"=>{"match"=>"*", "match_mapping_type"=>"byte", "mapping"=>{"type"=>"byte", "doc_values"=>true}}}, {"short_fields"=>{"match"=>"*", "match_mapping_type"=>"short", "mapping"=>{"type"=>"short", "doc_values"=>true}}}, {"integer_fields"=>{"match"=>"*", "match_mapping_type"=>"integer", "mapping"=>{"type"=>"integer", "doc_values"=>true}}}, {"long_fields"=>{"match"=>"*", "match_mapping_type"=>"long", "mapping"=>{"type"=>"long", "doc_values"=>true}}}, {"date_fields"=>{"match"=>"*", "match_mapping_type"=>"date", "mapping"=>{"type"=>"date", "doc_values"=>true}}}, {"geo_point_fields"=>{"match"=>"*", "match_mapping_type"=>"geo_point", "mapping"=>{"type"=>"geo_point", "doc_values"=>true}}}], "properties"=>{"@timestamp"=>{"type"=>"date", "doc_values"=>true}, "@version"=>{"type"=>"string", "index"=>"not_analyzed", "doc_values"=>true}, "geoip"=>{"type"=>"object", "dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip", "doc_values"=>true}, "location"=>{"type"=>"geo_point", "doc_values"=>true}, "latitude"=>{"type"=>"float", "doc_values"=>true}, "longitude"=>{"type"=>"float", "doc_values"=>true}}}}}}}}
[2016-12-21T08:58:16,152][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["search-mytestesdomain-r2nnqdws2zljuqnh3ek2d5n67u.us-east-1.es.amazonaws.com:80"]}
[2016-12-21T08:58:16,161][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>125}
[2016-12-21T08:58:16,172][INFO ][logstash.pipeline        ] Pipeline main started
[2016-12-21T08:58:16,274][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

Regards,
Raja

**Comment by andrewvc** [comment]
Since this is not a bug, but a usage question please ask this under our forum: https://discuss.elastic.co/c/logstash
