### ISSUE TITLE
[WARN ][logstash.inputs.udp      ] UDP listener died {:exception=>#<IOError: closed stream>

### ISSUE THREAD

**Issue by rajasekaran07** [elastic/logstash#6454]
Hi Team,

I am sending ECS logs to logstash using gelf log driver. I have configured using UDP port 12201.

gelf-address	udp://IPADDRESS:12201 

My logstash configuration file.

input {
  udp {
    port => 12201
    type => syslog
  }
}

output {
  elasticsearch {
  hosts => 'search-**************-cgzsrxl4ottkonjeucl2gzg2wu.us-east-1.es.amazonaws.com:80'
  }
}

My logstash var logs:

[2016-12-21T12:21:28,847][WARN ][logstash.inputs.udp      ] UDP listener died {:exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3705:in `select'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:93:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:56:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:359:in `start_input'"]}

kindly someone suggest how to fix this issue.

Regards,
Raja

**Comment by jsvd** [comment]
moved to https://github.com/logstash-plugins/logstash-input-udp/issues/29
