### ISSUE TITLE
Bad file descriptor - Bad file descriptor (Errno::EBADF) from monitoring agent

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#6463]
5.1.1

Are these benign?  It's coming from the agent that is used by monitoring.  It's showing up at the DEBUG level.  Is this something the end user have to worry about?  There's not a way for me to disable the monitoring agent to isolate this further.

```
[2016-12-27T00:02:14,483][DEBUG][logstash.agent           ] Starting puma
[2016-12-27T00:02:14,486][DEBUG][logstash.agent           ] Trying to start WebServer {:port=>9600}
[2016-12-27T00:02:14,488][DEBUG][logstash.api.service     ] [api-service] start
[2016-12-27T00:02:14,521][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2016-12-27T00:02:14,552][DEBUG][logstash.agent           ] Error in reactor loop escaped: Bad file descriptor - Bad file descriptor (Errno::EBADF)
[2016-12-27T00:02:14,553][DEBUG][logstash.agent           ] ["org/jruby/RubyIO.java:3705:in `select'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/reactor.rb:29:in `run_internal'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/reactor.rb:138:in `run_in_thread'"]
[2016-12-27T00:02:14,553][DEBUG][logstash.agent           ] Error in reactor loop escaped: Bad file descriptor - Bad file descriptor (Errno::EBADF)
[2016-12-27T00:02:14,554][DEBUG][logstash.agent           ] ["org/jruby/RubyIO.java:3705:in `select'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/reactor.rb:29:in `run_internal'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/puma-2.16.0-java/lib/puma/reactor.rb:138:in `run_in_thread'"]
```

**Comment by ph** [comment]
@ppf2  This seem to originate from puma, the webserver that power both the web api and the http input.

I have a few questions:
- Does it happen all the time?
- Are you using the http input too?
- Are you using the default configuration in the logstash.yml?

**Comment by andrewvc** [comment]
I think this may have been fixed here: https://github.com/puma/puma-dev/issues/12 . 

I think we need to upgrade to Puma 3 to see this fix :(

**Comment by NewstHet** [comment]
I ran into this problem but the solution was kind easy/weird to fix, maybe have/had the same issue.
logstash as a linux service didn't show all of the configuration chain errors at debugger level. only under windows running at CMD it showed syntax errors like event.set (...).   it didn't like the space between the set and (. and some other minor syntax bugs. after those were fixed that error was gone and logstash worked as it should.

**Comment by elvarb** [comment]
Ran into this problem yesterday after upgrading a logstash instance from version 2 to version 5. After a very long debugging session the only thing that stopped this from coming up was disabling the statsd output.

```
        #               statsd {
        #                       host => "influxdb"
        #                       port => "8125"
        #                       # namespace => ""
        #                       sender => ""
        #                       increment => [
        #                               "%{statsd}"
        #                       ]
        #               }
```

This is ok for now since that output was just for experiments.
