### ISSUE TITLE
Acceptance test failure on 5.2

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#6560]
https://logstash-ci.elastic.co/job/elastic+logstash+5.2+multijob-acceptance/label=metal,suite=redhat/1/console

```
1) CLI operation behaves like logstash update logstash-plugin update on centos-6 update all the plugins has executed succesfully
     Failure/Error: expect(logstash).to have_installed?(plugin_name, previous_version)
       expected #<ServiceTester::Artifact:0x49cb1baf @host="127.0.0.1:2222", @client=#<ServiceTester::Centos6Commands:0x3664f108>, @options={"host"=>"centos-6", "type"=>"redhat"}> to have installed? "logstash-filter-qatest" and "0.1.0"
     Shared Example Group: "logstash update" called from /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/acceptance/spec/lib/cli_operation_spec.rb:21
     # /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb:22:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/Rakefile:66:in `(root)'

  2) CLI operation behaves like logstash update logstash-plugin update on centos-7 update all the plugins has executed succesfully
     Failure/Error: expect(logstash).to have_installed?(plugin_name, previous_version)
       expected #<ServiceTester::Artifact:0x16b3c905 @host="127.0.0.1:2200", @client=#<ServiceTester::RedhatCommands:0x49fdbe2b>, @options={"host"=>"centos-7", "type"=>"redhat"}> to have installed? "logstash-filter-qatest" and "0.1.0"
     Shared Example Group: "logstash update" called from /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/acceptance/spec/lib/cli_operation_spec.rb:21
     # /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb:22:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/Rakefile:66:in `(root)'

  3) CLI operation behaves like logstash update logstash-plugin update on oel-6 update all the plugins has executed succesfully
     Failure/Error: expect(logstash).to have_installed?(plugin_name, previous_version)
       expected #<ServiceTester::Artifact:0x5b7ee56c @host="127.0.0.1:2201", @client=#<ServiceTester::Oel6Commands:0x311a0b3e>, @options={"host"=>"oel-6", "type"=>"redhat"}> to have installed? "logstash-filter-qatest" and "0.1.0"
     Shared Example Group: "logstash update" called from /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/acceptance/spec/lib/cli_operation_spec.rb:21
     # /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb:22:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/Rakefile:66:in `(root)'

  4) CLI operation behaves like logstash update logstash-plugin update on oel-7 update all the plugins has executed succesfully
     Failure/Error: expect(logstash).to have_installed?(plugin_name, previous_version)
       expected #<ServiceTester::Artifact:0x64d93096 @host="127.0.0.1:2202", @client=#<ServiceTester::RedhatCommands:0x76ed7573>, @options={"host"=>"oel-7", "type"=>"redhat"}> to have installed? "logstash-filter-qatest" and "0.1.0"
     Shared Example Group: "logstash update" called from /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/acceptance/spec/lib/cli_operation_spec.rb:21
     # /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/acceptance/spec/shared_examples/cli/logstash-plugin/update.rb:22:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.2+multijob-acceptance/label/metal/suite/redhat/qa/Rakefile:66:in `(root)'
```

**Comment by suyograo** [comment]
@ph any ideas?

**Comment by ph** [comment]
I will have to check it more deeply.

**Comment by ph** [comment]
@suyograo restarted the job and this time it succeeded.

I wonder if it's not a network hiccups, we certainly need to add better reporting to the console.
We need the raw output of the command on the remote vm, to debug this issues, the expectation is not enough.
