### ISSUE TITLE
Installed from RPM/systemd Logstash 5 not working

### ISSUE THREAD

**Issue by mrjameshamilton** [elastic/logstash#6562]
Hi, I want to run multiple Logstash instances on the same machine. I installed from RPM according to https://discuss.elastic.co/t/solved-multiple-instances-for-logstash/65539/2

I copied the /etc/logstash folder to /etc/logstash-statistics

When I try `sudo systemctl start logstash-statistics.service` the process starts but nothing works; not even any output in the log folder.

I try running like this `sudo /usr/share/logstash/bin/logstash --path.settings="/etc/logstash-statistics"` and get the following error:

`ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/etc/logstash-statistics, exception=Psych::SyntaxError, message=>(<unknown>): expected <block end>, but found BlockMappingStart while parsing a block mapping at line 72 column 2
`

**Comment by mrjameshamilton** [comment]
Actually, it doesn't even seem to work from the default location. I'm using the JDBC input & ES output and nothing is happening.

**Comment by mrjameshamilton** [comment]
`Jan 23 09:23:41 cs-ccr-scada003 logstash[11043]: ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/etc/logstash, exception=Psych::SyntaxError, message=>(<unknown>): expected <block end>, but found Scalar while parsing a block mapping at line 155 column 2
Jan 23 09:23:42 cs-ccr-scada003 systemd[1]: logstash.service: main process exited, code=exited, status=1/FAILURE
Jan 23 09:23:42 cs-ccr-scada003 systemd[1]: Unit logstash.service entered failed state.
Jan 23 09:23:42 cs-ccr-scada003 systemd[1]: logstash.service failed.
Jan 23 09:23:42 cs-ccr-scada003 systemd[1]: logstash.service holdoff time over, scheduling restart.
`

**Comment by mrjameshamilton** [comment]
I went back to version 2.4 for now

**Comment by suyograo** [comment]
@untergeek can you look at this please?

**Comment by untergeek** [comment]
@mrjameshamilton 

Can you please describe the full process you used?  I'm currently running two instances of Logstash–from a single, package install–in my home setup with systemd and it works great for me.  I'd like to try to replicate your process to see what happened.

**Comment by sadsfae** [comment]
I may have a similiar issue - using the latest ```logstash-5.2.1-1.noarch``` RPM I have a similiar issue, no matter what I try it seems to only start once.  It also doesn't like any of the standard, basic configuration files from the docs examples.

Here's the config I was using:

```
input {
  tcp {
    port => 5000
    type => syslog
  }
  udp {
    port => 5000
    type => syslog
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}

output {
  elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => rubydebug }
}
```

I've also tried just manually running things with the -f option using various incantations and very simplistic filters like:

```
input { stdin { } }
output {
  elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => rubydebug }
}
```

And with something like:

```
echo "Feb 16 10:19:43 host-01 crond[640] (CRON) INFO (Shutting down)" | sudo -u logstash /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/logstash.conf
```

The farthest I've gotten is when it runs once and complains about blocking plugins:

```
[2017-02-16T10:29:04,878][DEBUG][logstash.pipeline        ] Closed inputs
[2017-02-16T10:29:05,830][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>26, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:213:in `run'"}, {"thread_id"=>29, "name"=>"[main]>worker0", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:108:in `synchronize'"}, {"thread_id"=>30, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:127:in `synchronize'"}, {"thread_id"=>31, "name"=>"[main]>worker2", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:127:in `synchronize'"}, {"thread_id"=>32, "name"=>"[main]>worker3", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:127:in `synchronize'"}]}}
[2017-02-16T10:29:05,832][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2017-02-16T10:29:06,887][DEBUG][logstash.inputs.beats    ] closing {:plugin=>"LogStash::Inputs::Beats"}
[2017-02-16T10:29:06,888][DEBUG][logstash.pipeline        ] Input plugins stopped! Will shutdown filter/output workers.
[2017-02-16T10:29:06,915][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline
[2017-02-16T10:29:06,916][DEBUG][logstash.pipeline        ] Pushing shutdown {:thread=>"#<Thread:0x4be9fcbd run>"}
[2017-02-16T10:29:06,916][DEBUG][logstash.pipeline        ] Pushing shutdown {:thread=>"#<Thread:0x35976b0a sleep>"}
[2017-02-16T10:29:06,916][DEBUG][logstash.pipeline        ] Pushing shutdown {:thread=>"#<Thread:0x7c503969 sleep>"}
[2017-02-16T10:29:06,917][DEBUG][logstash.pipeline        ] Pushing shutdown {:thread=>"#<Thread:0x76b6ec8b sleep>"}
[2017-02-16T10:29:06,917][DEBUG][logstash.pipeline        ] Shutdown waiting for worker thread #<Thread:0x4be9fcbd>
[2017-02-16T10:29:06,942][DEBUG][logstash.pipeline        ] Shutdown waiting for worker thread #<Thread:0x35976b0a>
[2017-02-16T10:29:06,942][DEBUG][logstash.pipeline        ] Shutdown waiting for worker thread #<Thread:0x7c503969>
[2017-02-16T10:29:06,942][DEBUG][logstash.pipeline        ] Shutdown waiting for worker thread #<Thread:0x76b6ec8b>
[2017-02-16T10:29:06,942][DEBUG][logstash.filters.grok    ] closing {:plugin=>"LogStash::Filters::Grok"}
[2017-02-16T10:29:07,148][DEBUG][logstash.filters.date    ] closing {:plugin=>"LogStash::Filters::Date"}
[2017-02-16T10:29:07,148][DEBUG][logstash.outputs.stdout  ] closing {:plugin=>"LogStash::Outputs::Stdout"}
[2017-02-16T10:29:07,148][DEBUG][logstash.outputs.elasticsearch] closing {:plugin=>"LogStash::Outputs::ElasticSearch"}
[2017-02-16T10:29:07,148][DEBUG][logstash.outputs.elasticsearch] Stopping sniffer
[2017-02-16T10:29:07,148][DEBUG][logstash.outputs.elasticsearch] Stopping resurrectionist
[2017-02-16T10:29:07,628][DEBUG][logstash.outputs.elasticsearch] Waiting for in use manticore connections
[2017-02-16T10:29:07,629][DEBUG][logstash.outputs.elasticsearch] Closing adapter #<LogStash::Outputs::ElasticSearch::HttpClient::ManticoreAdapter:0x64f08e08>
```

The full configuration file I am trying to use which works in 2.x versions is:

```
# standard remote syslog input
input {
  tcp {
    port => 5000
    type => syslog
  }
  udp {
    port => 5000
    type => syslog
  }
}

# local stdin syslog input
# mostly used for generating first index mapping via local logs
input {
  stdin {
      type => "syslog"
    }
}

# syslog filter
filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}

output {
  stdout { codec => rubydebug }
}

# configure beats for remote logs
input {
  beats {
    port => "5044"
    ssl => true
    ssl_certificate => ["/usr/share/logstash/filebeat-forwarder.crt"]
    ssl_key => ["/usr/share/logstash/filebeat-forwarder.key"]
    ssl_verify_mode => none
  }
}

output {
  elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => rubydebug }
}
```

I'm not sure what I am doing wrong, but bog-standard RPM deployed ```5.2.1``` doesn't want to accept any configuration I throw at it.  It generally will start the first time and never survive a restart though the process is running according to systemd.

strace on the running logstash pid will give me either two results:

```
futex(0x7f06d0121054, FUTEX_WAIT_BITSET_PRIVATE, 1, {2205, 175857885}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f06d0121028, FUTEX_WAKE_PRIVATE, 1) = 0
futex(0x7f06d0121054, FUTEX_WAIT_BITSET_PRIVATE, 1, {2205, 226322362}, ffffffff) = -1 ETIMEDOUT (Connection timed out)
futex(0x7f06d0121028, FUTEX_WAKE_PRIVATE, 1) = 0
```

OR 

```
futex(0x7f8939b1a9d0, FUTEX_WAIT, 3812, NULL
```

Lastly, here is my current testing system service file information:

```
[root@host-01 ~]# systemctl status logstash -l
● logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-02-16 11:27:33 GMT; 7min ago
 Main PID: 3791 (java)
   CGroup: /system.slice/logstash.service
           └─3791 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Djava.awt.headless=true -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Xmx1g -Xms256m -Xss2048k -Djffi.boot.library.path=/usr/share/logstash/vendor/jruby/lib/jni -Xbootclasspath/a:/usr/share/logstash/vendor/jruby/lib/jruby.jar -classpath : -Djruby.home=/usr/share/logstash/vendor/jruby -Djruby.lib=/usr/share/logstash/vendor/jruby/lib -Djruby.script=jruby -Djruby.shell=/bin/sh org.jruby.Main /usr/share/logstash/lib/bootstrap/environment.rb logstash/runner.rb --path.settings=/etc/logstash --log.level=debug --config.debug --path.config=/etc/logstash/conf.d

Feb 16 11:27:33 host-01 systemd[1]: Started logstash.
Feb 16 11:27:33 host-01 systemd[1]: Starting logstash...
```

I've been trying to upgrade my [existing Ansible playbooks](https://github.com/sadsfae/ansible-elk/issues/16) with the 5.2x+ ELK series and I'm only having trouble with the logstash part of it.

**Comment by mrjameshamilton** [comment]
I've since moved on from this installation and have installed version 5 with Docker successfully since.

**Comment by jtyr** [comment]
@untergeek I'm having the same problem on CentOS 7. When installed from RPM, systemd starts the service but after a while (approx 2 mins) I receive these messages:

```
WARNING: Could not find logstash.yml which is typically located in $LS_HOME/config or /etc/logstash. You can specify the path using --path.settings. Continuing using the defaults
ERROR: option '--path.settings': Setting "path.settings" must be a String. Received:  (NilClass)
```

The problem seems to be in the `/etc/systemd/system/logstash.service` file:

```
ExecStart=/usr/share/logstash/bin/logstash "--path.settings"
```

The parameter `--path.settings` has no value. This can be fixed by changing that line to this:

```
ExecStart=/usr/share/logstash/bin/logstash --path.settings /etc/logstash
```

**Comment by mrjameshamilton** [comment]
I'm having a similar problem again. I installed on a machine from RPM and nothing is happening and there's no output in the log.

``` logstash.service - logstash
   Loaded: loaded (/etc/systemd/system/logstash.service; disabled; vendor preset: disabled)
   Active: active (running) since jeu. 2017-03-16 15:27:36 CET; 4s ago
 Main PID: 22182 (java)
   CGroup: /system.slice/logstash.service
           └─22182 /usr/bin/java -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -Djava.awt.headless=true -Dfile.en...

mars 16 15:27:36 scadastatslogstashshipper systemd[1]: Started logstash.
mars 16 15:27:36 scadastatslogstashshipper systemd[1]: Starting logstash...
```

**Comment by mrjameshamilton** [comment]
If I run it like this: ```DEBUG=1 /usr/share/logstash/bin/logstash```

I get the output: 

```DEBUG: exec /usr/share/logstash/vendor/jruby/bin/jruby /usr/share/logstash/lib/bootstrap/environment.rb logstash/runner.rb```

Should there be further output?

**Comment by untergeek** [comment]
@mrjameshamilton Is there a possibility you are hitting the [slow-startup-because-there's-insufficient-entropy bug](https://github.com/elastic/logstash/issues/6117)?  I ask, because with no further output, it could be this.

**Comment by untergeek** [comment]
See also https://github.com/elastic/logstash/issues/5507

**Comment by mrjameshamilton** [comment]
OK, yes, maybe it's related to that. after a while it seems to start.

**Comment by untergeek** [comment]
Going to re-close, then, since it seems unrelated to the original issue.
