### ISSUE TITLE
LogStash::Agent metrics after config reloading when reloading a config that raises exception on pipeline.run does not increase the successful reload count

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6565]
```
Failures:

  1) LogStash::Agent metrics after config reloading when reloading a config that raises exception on pipeline.run does not increase the successful reload count
     Failure/Error: expect { subject.send(:"reload_pipeline!", "main") }.to_not change {
       expected result not to have changed, but did change from 0 to 1
     # ./logstash-core/spec/logstash/agent_spec.rb:575:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:49:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'
```

**Comment by jsvd** [comment]
tracking this in #7138

**Comment by colinsurprenant** [comment]
reopening - build failed on 5.1 https://logstash-ci.elastic.co/job/elastic+logstash+5.1+multijob-intake/75/console
```
Failures:

  1) LogStash::Agent metrics after config reloading when reloading a config that raises exception on pipeline.run does not increase the successful reload count
     Failure/Error: expect { subject.send(:"reload_pipeline!", "main") }.to_not change {
       expected result not to have changed, but did change from 0 to 1
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/logstash-core/spec/logstash/agent_spec.rb:572:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/rakelib/test.rake:49:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'

Finished in 2 minutes 36.1 seconds (files took 4.66 seconds to load)
2208 examples, 1 failure

Failed examples:

rspec /var/lib/jenkins/workspace/elastic+logstash+5.1+multijob-intake/logstash-core/spec/logstash/agent_spec.rb:571 # LogStash::Agent metrics after config reloading when reloading a config that raises exception on pipeline.run does not increase the successful reload count

Randomized with seed 58329

```
