### ISSUE TITLE
persisted queue fails on windows

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6646]
The persistent queue seems to fail on Windows. I am able to reproduce with Logstash 5.2.0 and with the test suite. 

## bin/logstash failure

1) Run logstash with `queue.type: persisted`
2) Stop logstash after some events are processed
3) Start Logstash again, which fails:

```
14:48:56.143 [LogStash::Runner] ERROR logstash.agent - fetched an invalid config {:config=>"input { stdin { } }output { stdout { codec => rubydebug }
 }", :reason=>"C:\\Users\\jls.FRIENDSHIP\\Downloads\\logstash-5.2.0\\logstash-5.2.0\\data\\queue\\page.0: The process cannot access the file because
it is being used by another process.\r\n", :backtrace=>["org/logstash/ackedqueue/ext/JrubyAckedQueueExtLibrary.java:136:in `open'", "C:/Users/jls.FRI
ENDSHIP/Downloads/logstash-5.2.0/logstash-5.2.0/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:40:in `with_queue'", "C:/Users/jls.FRIENDSHIP/
Downloads/logstash-5.2.0/logstash-5.2.0/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:29:in `create_file_based'", "C:/Users/jls.FRIENDSHIP/D
ownloads/logstash-5.2.0/logstash-5.2.0/logstash-core/lib/logstash/pipeline.rb:141:in `build_queue_from_settings'", "C:/Users/jls.FRIENDSHIP/Downloads
/logstash-5.2.0/logstash-5.2.0/logstash-core/lib/logstash/pipeline.rb:102:in `initialize'", "C:/Users/jls.FRIENDSHIP/Downloads/logstash-5.2.0/logstas
h-5.2.0/logstash-core/lib/logstash/agent.rb:246:in `create_pipeline'", "C:/Users/jls.FRIENDSHIP/Downloads/logstash-5.2.0/logstash-5.2.0/logstash-core
/lib/logstash/agent.rb:95:in `register_pipeline'", "C:/Users/jls.FRIENDSHIP/Downloads/logstash-5.2.0/logstash-5.2.0/logstash-core/lib/logstash/runner
.rb:264:in `execute'", "C:/Users/jls.FRIENDSHIP/Downloads/logstash-5.2.0/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb
:67:in `run'", "C:/Users/jls.FRIENDSHIP/Downloads/logstash-5.2.0/logstash-5.2.0/logstash-core/lib/logstash/runner.rb:183:in `run'", "C:/Users/jls.FRI
ENDSHIP/Downloads/logstash-5.2.0/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "C:\\Users\\jls.FRIENDSH
IP\\Downloads\\logstash-5.2.0\\logstash-5.2.0\\lib\\bootstrap\\environment.rb:71:in `(root)'"]}
```

## Test suite failure:

```
...\logstash-core\> ../gradlew build --info
org.logstash.ackedqueue.QueueTest > testAckedCount FAILED
    java.nio.file.FileSystemException: C:\Users\JLS~1.FRI\AppData\Local\Temp\junit3335886594418972867\data\page.0: The process cannot access the file
 because it is being used by another process.
        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at org.logstash.common.io.MmapPageIO.purge(MmapPageIO.java:99)
        at org.logstash.ackedqueue.TailPage.purge(TailPage.java:38)
        at org.logstash.ackedqueue.Queue.ack(Queue.java:536)
        at org.logstash.ackedqueue.QueueTest.testAckedCount(QueueTest.java:559)

org.logstash.common.io.FileCheckpointIOTest > write FAILED
    java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/jls.FRIENDSHIP/projects/logstash/logstash-core/build/resources/test/or
g/logstash/common/io/checkpoint.head
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
        at java.nio.file.Paths.get(Paths.java:84)
        at org.logstash.common.io.FileCheckpointIOTest.write(FileCheckpointIOTest.java:49)
Gradle Test Executor 1 finished executing tests.

71 tests completed, 2 failed
```

**Comment by jordansissel** [comment]
Current hypothesis is that we have an open file handle to a is that we are calling `delete` on a file that is still open by Logstash, and this operation (delete while file is open) is rejected on Windows.

**Comment by colinsurprenant** [comment]
I was able to reproduce under Windows 2012 R2 on master. 

The weird thing is that under `rake test:install-core` all tests are passing. Also the `QueueTest > testAckedCount` failure is intermittent.

**Comment by colinsurprenant** [comment]
I right, that is because the build scripts are running `gradlew jar ...` which does not run the tests.

**Comment by colinsurprenant** [comment]
Pushed PR #6740 which should solve. I will be doing more tests.

**Comment by colinsurprenant** [comment]
After so testings: all tests using plain configs and generator input ana sleep filter, stop start are now working correctly with the fix. Without the fix they were crashing systematically.

**Comment by colinsurprenant** [comment]
fix merged in master, 5.x and 5.3
