### ISSUE TITLE
Logstash crashes when auto reloading configuration and syslog input plugin has incoming connection

### ISSUE THREAD

**Issue by oridag** [elastic/logstash#6663]
When using the syslog input plugin and using the config auto reload, LS crashes with the following error:

[2017-02-08T09:49:49,873][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<Errno::EBADF: Bad file descriptor - Bad file descriptor>, :backtrace=>["org/jruby/RubyIO.java:3565:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-3.2.0/lib/logstash/inputs/syslog.rb:182:in `tcp_receiver'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-3.2.0/lib/logstash/inputs/syslog.rb:167:in `tcp_listener'"]}

- Version: 5.1.2
- Operating System: Ubuntu 16.04
- Steps to Reproduce:
  * Configure syslog input plugin and auto reload
  * Wait for incoming connection from rsyslog
  * Change a configuration file

**Comment by oridag** [comment]
I have investigated some more, this time without autoreload but by sending SIGTERM. I see two different behaviors:

**After only one event processed:** 
I'm getting the same behavior as with autoreload i.e:
[2017-02-08T13:23:09,636][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<Errno::EBADF: Bad file descriptor - Bad file descriptor>, :backtrace=>["org/jruby/RubyIO.java:3565:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-3.2.0/lib/logstash/inputs/syslog.rb:182:in `tcp_receiver'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-3.2.0/lib/logstash/inputs/syslog.rb:167:in `tcp_listener'"]}

And the process exits.

**After 2 events or more processed:**
[2017-02-08T13:24:32,203][WARN ][logstash.inputs.udp      ] UDP listener died {:exception=>#<IOError: closed stream>, :backtrace=>["org/jruby/RubyIO.java:3705:in `select'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:93:in `udp_listener'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:56:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:359:in `start_input'"]}
[2017-02-08T13:24:32,783][WARN ][logstash.shutdownwatcher ] {}
[2017-02-08T13:24:32,784][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.

And the process stays up forever.

I have verified, via API, that in both cases all events have been fully processed

**Comment by oridag** [comment]
I can still reproduce that on 6.0.0-beta1. It basically makes the config reload feature useless since Logstash will crash on SIGHUP if there is an open syslog connection.
Are there any plans to fix it?
