### ISSUE TITLE
ClassCastException and missing output

### ISSUE THREAD

**Issue by tokred** [elastic/logstash#6695]
I have a quite simple pipeline with heartbeats, where a ClassCastException occurs and no output is generated:
```
==> /var/log/logstash/logstash-plain.log <==
[2017-02-13T16:37:01,708][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>250}
[2017-02-13T16:37:01,712][INFO ][logstash.pipeline        ] Pipeline main started
[2017-02-13T16:37:01,724][DEBUG][logstash.agent           ] Starting puma
[2017-02-13T16:37:01,725][DEBUG][logstash.agent           ] Trying to start WebServer {:port=>9600}
[2017-02-13T16:37:01,728][DEBUG][logstash.api.service     ] [api-service] start
[2017-02-13T16:37:01,735][DEBUG][logstash.pipeline        ] filter received {"event"=>{"log_type"=>"log-heartbeat", "@timestamp"=>2017-02-13T15:37:01.201Z, "host"=>"log-shipper01.XXX", "@version"=>"1", "message"=>"log-shipper01.XXX is up", "tags"=>["_heartbeat", "_skipfilters"]}}
[2017-02-13T16:37:01,738][DEBUG][logstash.filters.mutate  ] filters/LogStash::Filters::Mutate: removing tag {:tag=>"_skipfilters"}
[2017-02-13T16:37:01,755][DEBUG][logstash.util.decorators ] filters/LogStash::Filters::Mutate: adding value to field {"field"=>"source_dns", "value"=>["log-shipper01.XXX"]}
[2017-02-13T16:37:01,759][DEBUG][logstash.filters.mutate  ] filters/LogStash::Filters::Mutate: removing field {:field=>"@version"}
[2017-02-13T16:37:01,773][DEBUG][logstash.filters.mutate  ] filters/LogStash::Filters::Mutate: removing field {:field=>"port"}
[2017-02-13T16:37:01,775][DEBUG][logstash.pipeline        ] output received {"event"=>{"source_dns"=>"log-shipper01.XXX", "log_type"=>"log-heartbeat", "host"=>"11.11.11.11", "message"=>"log-shipper01.XXX is up", "log_collector_timestamp"=>2017-02-13T15:37:01.201Z, "tags"=>["_heartbeat"]}}

==> /var/log/messages <==
Feb 13 16:37:01 log-shipper01 logstash: Exception in thread "[main]>worker0" java.lang.ClassCastException: org.logstash.bivalues.StringBiValue cannot be cast to java.lang.String
Feb 13 16:37:01 log-shipper01 logstash: at org.logstash.Event.toString(Event.java:312)
Feb 13 16:37:01 log-shipper01 logstash: at org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_to_s(JrubyEventExtLibrary.java:209)
Feb 13 16:37:01 log-shipper01 logstash: at org.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$0$0$ruby_to_s.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$0$0$ruby_to_s.gen)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:306)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:136)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.ast.CallNoArgNode.interpret(CallNoArgNode.java:60)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.ast.IfNode.interpret(IfNode.java:118)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
Feb 13 16:37:01 log-shipper01 logstash: at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
[...]
```

Configuration used:
```
input {
	heartbeat {
		interval => 30
			message => "log-shipper01.XXX is up"
			add_field => {
				"log_type" => "log-heartbeat"
			}
			tags => [ "_heartbeat", "_skipfilters" ]
	}
}

filter {
	if "_heartbeat" in [tags] {
		mutate {
			replace => { "host" => "11.11.11.11" }
			add_field => { "source_dns" => "log-shipper01.XXX" }
		}
	}

	mutate {
		rename => { "@timestamp" => "log_collector_timestamp" }
		remove_field => [ "@version", "port" ]
	}
}

output {
	kafka {
		bootstrap_servers => "172.2.1.101:9092,172.2.1.187:9092,172.2.1.202:9092"
		topic_id => "%{log_type}"
	}
}
```

The Kafka topics stays empty. Any idea how to narrow this down?

- Version: 5.2.0
- Operating System: Red Hat 7

**Comment by kares** [comment]
LS 5.X was the last to use `StringBiValue` ... was removed in 6.X
since 5.X is EOL this won't fix (unless it was actually resolved in 5.4), sorry for the inconvenience.
