### ISSUE TITLE
LogStash::Runner pipeline settings when :pipeline_workers is not defined by the user should not pass the value to the pipeline

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#6737]
failure from master (hash 9cc165a428a356c974d7ae56f4789cd77a6b3f74), running `rake test:core`:

```
Failures:

  1) LogStash::Runner pipeline settings when :pipeline_workers is not defined by the user should not pass the value to the pipeline
     Failure/Error: expect(settings.set?("pipeline.workers")).to be(false)
       
       expected false
            got true
     # ./logstash-core/spec/logstash/runner_spec.rb:261:in `(root)'
     # ./logstash-core/lib/logstash/runner.rb:357:in `create_agent'
     # ./logstash-core/lib/logstash/runner.rb:272:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
     # ./logstash-core/lib/logstash/runner.rb:185:in `run'
     # ./vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
     # ./logstash-core/spec/logstash/runner_spec.rb:264:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:49:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'

Finished in 3 minutes 42.6 seconds (files took 5.97 seconds to load)
1711 examples, 1 failure

Failed examples:

rspec ./logstash-core/spec/logstash/runner_spec.rb:259 # LogStash::Runner pipeline settings when :pipeline_workers is not defined by the user should not pass the value to the pipeline

Randomized with seed 18296
```

The failure is not triggered consistently.

**Comment by jsvd** [comment]
another occurence of this https://logstash-ci.elastic.co/job/elastic+logstash+master+dockerubuntu-periodic/2018/console

**Comment by andrewvc** [comment]
This is reaaaly hard to repro. I've scoured the code, and tried pegging my CPU with `stress` while running the tests, no luck so far.

The best theory I have is that some other test is altering the settings object and not cleaning it well.

If we can figure out a way to mostly not use the `LogStash::SETTINGS` reference, but instead only inject settings in tests that would be ideal. I'll explore that tomorrow. Unfortunately, it will be impossible to confirm if that works.

**Comment by colinsurprenant** [comment]
ocurred in https://logstash-ci.elastic.co/job/elastic+logstash+5.4+multijob-os-compatibility/os=centos/45/console
```
Failures:

  1) LogStash::Runner pipeline settings when :pipeline_workers is not defined by the user should not pass the value to the pipeline
     Failure/Error: expect(settings.set?("pipeline.workers")).to be(false)
       
       expected false
            got true
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/logstash-core/spec/logstash/runner_spec.rb:261:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/logstash-core/lib/logstash/runner.rb:360:in `create_agent'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/logstash-core/lib/logstash/runner.rb:272:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/logstash-core/lib/logstash/runner.rb:185:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/logstash-core/spec/logstash/runner_spec.rb:264:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/rakelib/test.rake:40:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:216:in `invoke_prerequisites'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:193:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'

Finished in 6 minutes 14 seconds (files took 4.37 seconds to load)
2345 examples, 1 failure, 1 pending

Failed examples:

rspec /var/lib/jenkins/workspace/elastic+logstash+5.4+multijob-os-compatibility/os/centos/logstash-core/spec/logstash/runner_spec.rb:259 # LogStash::Runner pipeline settings when :pipeline_workers is not defined by the user should not pass the value to the pipeline

Randomized with seed 12645

```
