### ISSUE TITLE
Logstash template install fails passing through Elasticsearch's reasons

### ISSUE THREAD

**Issue by loekvangool** [elastic/logstash#6749]
When I use an illegal template from Logstash using `manage_template`, Logstash shows an unhelpful message instead of passing through the error from Elasticsearch that allows me to go ahead and fix it.

- Version: 5.2
- Operating System: OSX 
- Config File (if you have sensitive info, please remove it):
```
    manage_template => true
    template_overwrite => true
    template_name => "flights"
    template => "./flights_mapping.json"
```

The Logstash error is non-specific: `Got response code '400' contacting Elasticsearch`

Full message:
```
[2017-02-23T09:11:01,281][INFO ][logstash.outputs.elasticsearch] Installing elasticsearch template to _template/flights
[2017-02-23T09:11:01,465][ERROR][logstash.outputs.elasticsearch] Failed to install template. {:message=>"Got response code '400' contacting Elasticsearch at URL 'https://***.eu-west-1.aws.found.io:9243/_template/flights'", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::BadResponseCodeError", :backtrace=>["/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:76:in `perform_request'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:273:in `perform_request_to_url'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:261:in `perform_request'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:351:in `with_connection'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:260:in `perform_request'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:268:in `put'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client.rb:303:in `template_put'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client.rb:79:in `template_install'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/template_manager.rb:29:in `install'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/template_manager.rb:9:in `install_template'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/common.rb:54:in `install_template'", "/usr/local/Cellar/logstash/5.2.1/libexec/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/common.rb:21:in `register'", "/usr/local/Cellar/logstash/5.2.1/libexec/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:8:in `register'", "/usr/local/Cellar/logstash/5.2.1/libexec/logstash-core/lib/logstash/output_delegator.rb:37:in `register'", "/usr/local/Cellar/logstash/5.2.1/libexec/logstash-core/lib/logstash/pipeline.rb:234:in `start_workers'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/local/Cellar/logstash/5.2.1/libexec/logstash-core/lib/logstash/pipeline.rb:234:in `start_workers'", "/usr/local/Cellar/logstash/5.2.1/libexec/logstash-core/lib/logstash/pipeline.rb:188:in `run'", "/usr/local/Cellar/logstash/5.2.1/libexec/logstash-core/lib/logstash/agent.rb:302:in `start_pipeline'"]}
```

When trying this directly in Elasticsearch with `PUT _template`, it gives errors that are telling me what to fix:

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "Mapping definition for [Arrival] has unsupported parameters:  [WeatherDelay : {type=integer}] [WheelsOn : {type=keyword}]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [flights]: Mapping definition for [Arrival] has unsupported parameters:  [WeatherDelay : {type=integer}] [WheelsOn : {type=keyword}]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "Mapping definition for [Arrival] has unsupported parameters:  [WeatherDelay : {type=integer}] [WheelsOn : {type=keyword}]"
    }
  },
  "status": 400
}
```

**Comment by untergeek** [comment]
Please move this issue to https://github.com/logstash-plugins/logstash-output-elasticsearch as that is where the template stuff is handled.

**Comment by loekvangool** [comment]
https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/333#issuecomment-282274531
