### ISSUE TITLE
Loogstash 5.1.0 EBADF error on systemd stop command

### ISSUE THREAD

**Issue by randude** [elastic/logstash#6821]
Logstash was issued a stop command by systemd which caused logstash to fail.
Here are the logs:
2017-03-18 20:27:44 +0000 systemd[1]: INFO - -  Stopping logstash...
2017-03-18 20:27:49 +0000 systemd[1]: NOTICE - -  logstash.service: Main process exited, code=exited, status=1/FAILURE
2017-03-18 20:27:49 +0000 systemd[1]: INFO - -  Stopped logstash.
2017-03-18 20:27:49 +0000 systemd[1]: NOTICE - -  logstash.service: Unit entered failed state.
2017-03-18 20:27:49 +0000 systemd[1]: WARNING - -  logstash.service: Failed with result 'exit-code'.
2017-03-18 20:27:49 +0000 systemd[1]: INFO - -  Stopped logstash.
2017-03-18 20:27:49 +0000 systemd[1]: INFO - -  Started logstash.

and from the logstash log:
[2017-03-18T20:27:44,112][WARN ][logstash.runner          ] SIGTERM received. Shutting down the agent.
[2017-03-18T20:27:44,116][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
[2017-03-18T20:27:48,650][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<Errno::EBADF: Bad file descriptor - Bad file descriptor>, :backtrace=>["org/jruby/RubyIO.java:3565:in `each'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-3.2.0/lib/logstash/inputs/syslog.rb:182:in `tcp_receiver'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-3.2.0/lib/logstash/inputs/syslog.rb:167:in `tcp_listener'"]}
[2017-03-18T20:29:12,610][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"localhost:5044"}
[2017-03-18T20:29:12,857][INFO ][org.logstash.beats.Server] Starting server on port: 5044
[2017-03-18T20:29:13,141][INFO ][logstash.inputs.syslog   ] Starting syslog udp listener {:address=>"localhost:2514"}
[2017-03-18T20:29:13,144][INFO ][logstash.inputs.syslog   ] Starting syslog tcp listener {:address=>"localhost:2514"}
[2017-03-18T20:29:13,156][INFO ][logstash.inputs.udp      ] Starting UDP listener {:address=>"localhost:4994"}
[2017-03-18T20:29:13,169][INFO ][logstash.inputs.tcp      ] Automatically switching from json to json_lines codec {:plugin=>"tcp"}
[2017-03-18T20:29:13,171][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"localhost:4995"}
[2017-03-18T20:29:13,177][INFO ][logstash.inputs.pipe     ] Registering pipe input {:command=>"/opt/vaultive/admin/logstashplugins/logstash2logstash.py --server --port 5134 --ssl --compression"}
[2017-03-18T20:29:13,189][INFO ][logstash.inputs.udp      ] UDP listener started {:address=>"localhost:4994", :receive_buffer_bytes=>"106496", :queue_size=>"2000"}
[2017-03-18T20:29:15,102][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>250}
[2017-03-18T20:29:15,123][INFO ][logstash.pipeline        ] Pipeline main started
 

- Version: 5.1.0
- Operating System: ubuntu 16.04
- Config File - listens on input tcp port
- Sample Data: json lines
- Steps to Reproduce: occurs from time to time randomly

**Comment by randude** [comment]
anyone?
