### ISSUE TITLE
Logstash 2.4.1 fails to find configuration files after running for a while

### ISSUE THREAD

**Issue by quulah** [elastic/logstash#6822]
- Version: 2.4.1
- Operating System: Ubuntu 16.04

I have a Logstash instance, with multiple configuration files in /etc/logstash/conf.d. It starts properly and runs OK, but then after a few days it starts failing with the message:

```
{:timestamp=>"2017-03-20T13:19:09.898000+0000", :message=>"An unexpected error occurred!", :error=>#<RuntimeError: No config files found: /etc/logstash/conf.d/*
Can you make sure this path is a logstash config file?>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/config/loader.rb:58:in `local_config'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/config/loader.rb:37:in `load_config'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/config/loader.rb:17:in `format_config'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:501:in `fetch_config'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:461:in `reload_pipeline!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:389:in `reload_state!'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:387:in `reload_state!'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:386:in `reload_state!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:222:in `execute'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:20:in `interval'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:222:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/runner.rb:94:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/runner.rb:99:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:error}
{:timestamp=>"2017-03-20T13:19:12.898000+0000", :message=>"An unexpected error occurred!", :error=>#<RuntimeError: No config files found: /etc/logstash/conf.d/*
Can you make sure this path is a logstash config file?>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/config/loader.rb:58:in `local_config'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/config/loader.rb:37:in `load_config'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/config/loader.rb:17:in `format_config'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:501:in `fetch_config'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:461:in `reload_pipeline!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:389:in `reload_state!'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:387:in `reload_state!'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:386:in `reload_state!'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:222:in `execute'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:20:in `interval'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/agent.rb:222:in `execute'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/runner.rb:94:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.4.1-java/lib/logstash/runner.rb:99:in `run'", "org/jruby/RubyProc.java:281:in `call'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"], :level=>:error}
```

This happens every 3 seconds, so it's most likely the auto reload function. My service file states the command like this:

```
/opt/logstash/bin/logstash agent -f /etc/logstash/conf.d -l /var/log/logstash/logstash.log --auto-reload --pipeline-workers 4
```

When I restart the process, everything is OK again.

The permissions seem to be fine, and --configtest is happy too.

```
$ /opt/logstash/bin/logstash agent -f /etc/logstash/conf.d --configtest --debug
Reading config file {:config_file=>"/etc/logstash/conf.d/10-input-logs.conf", :level=>:debug, :file=>"logstash/config/loader.rb", :line=>"69", :method=>"local_config"}
Reading config file {:config_file=>"/etc/logstash/conf.d/10-input-redis.conf", :level=>:debug, :file=>"logstash/config/loader.rb", :line=>"69", :method=>"local_config"}
...
config LogStash::Filters::Mutate/@add_field = {} {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
config LogStash::Filters::Mutate/@remove_field = [] {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
config LogStash::Filters::Mutate/@periodic_flush = false {:level=>:debug, :file=>"logstash/config/mixin.rb", :line=>"154", :method=>"config_init"}
Plugin not defined in namespace, checking for plugin file {:type=>"output", :name=>"elasticsearch", :path=>"logstash/outputs/elasticsearch", :level=>:debug, :file=>"logstash/plugin.rb", :line=>"86", :method=>"lookup"}
Configuration OK
```

```
$ ls -lah | head -5
total 56K
drwxr-xr-x 2 logstash logstash 4.0K Mar  9 07:16 .
drwxrwxr-x 4 root     root     4.0K Mar  9 07:16 ..
-rw-r--r-- 1 logstash logstash  314 Mar  9 07:16 10-input-logs.conf
-rw-r--r-- 1 logstash logstash  428 Mar  9 07:16 10-input-redis.conf
```

**Comment by quulah** [comment]
A rough estimate of this happening is 5 days, but I'll try to pinpoint it. How does auto reloading work, could the limits of the system stop Logstash from reading the configuration files again?

MAX_OPEN_FILES type of thing perhaps... Though hitting that type of limit when polling for changed files in a directory seems a bit weird.

**Comment by quulah** [comment]
Testing the code from [loader.rb](https://github.com/elastic/logstash/blob/v2.4.1/logstash-core/lib/logstash/config/loader.rb#L53) by hand works too, so this has something to do with the long running process.

```
irb(main):004:0> path = '/etc/logstash/conf.d'
=> "/etc/logstash/conf.d"
irb(main):005:0> path = ::File.expand_path(path)
=> "/etc/logstash/conf.d"
irb(main):006:0> path = ::File.join(path, "*") if ::File.directory?(path)
=> "/etc/logstash/conf.d/*"
irb(main):007:0> Dir.glob(path).length
=> 12
```

**Comment by quulah** [comment]
I raised the limit of open files for Logstash. Which helped a bit, but after a while the same error occurred.

I finally figured out what is causing it though. The backend was broken, so Logstash was gathering a lot of TCP connections in a CLOSED_WAIT state, which in turn ate all the file handles and caused checking for the configuration changes fail.

So a bit of a red herring, but there's probably little to be done in the loader.rb file to give a better error message. I'm a bit unsure if not closing the TCP connections would be considered a bug or not, but I'll close this now that I know what to fix.

**Comment by danielmotaleite** [comment]
I'm also having this issue, with logstash 5.3.2 and the connections open are coming from the client filebeats. stop and restart logstash for now is the workaround, but i do suspect that something is wrong in logstash closing connections

```
tcp      150      0 192.168.1.3:17000     192.168.3.6:40524     CLOSE_WAIT 
tcp      150      0 192.168.1.3:17000     192.168.1.156:36598   CLOSE_WAIT 
tcp      150      0 192.168.1.3:17000     192.168.3.6:53684     CLOSE_WAIT 
tcp      150      0 192.168.1.3:17000     192.168.2.6:49364     CLOSE_WAIT 

```

**Comment by danielmotaleite** [comment]
probably related with https://github.com/elastic/logstash/issues/4225 (see last comment)
