### ISSUE TITLE
Test failure: Something failed in the acceptance test (?)

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6870]
Build failure: https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-acceptance/label=metal,suite=debian/235/console

```
...
Using rspec-expectations 3.1.2
Using rspec-mocks 3.1.3
Using pry 0.10.4 (java)
Using runner-tool 0.2.0 from https://github.com/purbon/runner-tool.git (at master@5ec0803)
Using rspec 3.1.0
Bundle complete! 4 Gemfile dependencies, 17 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Acceptance: Running the tests
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
The signal EXIT is in use by the JVM and will not work correctly on this platform
bootstrapping all non experimental VM's defined in acceptance/Vagrantfile for debian: ["debian-8", "ubuntu-1204", "ubuntu-1404"]
rake aborted!
LogStash::CommandExecutor::CommandError: CMD: vagrant up debian-8 ubuntu-1204 ubuntu-1404 STDERR: The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
/var/lib/jenkins/workspace/elastic+logstash+master+multijob-acceptance/label/metal/suite/debian/qa/vagrant/command.rb:49:in `run!'
/var/lib/jenkins/workspace/elastic+logstash+master+multijob-acceptance/label/metal/suite/debian/qa/vagrant/helpers.rb:21:in `bootstrap'
/var/lib/jenkins/workspace/elastic+logstash+master+multijob-acceptance/label/metal/suite/debian/qa/Rakefile:40:in `(root)'
/var/lib/jenkins/.rbenv/versions/jruby-1.7.26/bin/bundle:23:in `(root)'
Tasks: TOP => qa:vm:setup
(See full trace by running task with --trace)
runbld>>> <<<<<<<<<<<< SCRIPT EXECUTION END <<<<<<<<<<<<
runbld>>> DURATION: 105455ms
```

**Comment by ph** [comment]
fixed in #7187
