### ISSUE TITLE
Logstash Offline Plugin Installation doesn't work on windows 

### ISSUE THREAD

**Issue by ESamir** [elastic/logstash#6882]
Logstash Offline Plugin Installation doesn't work on windows 

- Version: 5.2.2
- Operating System: Windows
- Steps to Reproduce:

```D:\ES\logstash-5.2.0\bin>logstash-plugin install logstash-output-syslog
Validating logstash-output-syslog
Installing logstash-output-syslog
Installation successful
```

```
D:\ES\logstash-5.2.0\bin>logstash-plugin prepare-offline-pack logstash-output-sy
slog
Offline package created at: D:/ES/logstash-5.2.0/logstash-offline-plugins-5.2.0.
zip
```
You can install it with this command 

```
D:\ES\logstash-5.2.0\bin>logstash-plugin install file:///D:/ES/logstash-5.2.0/lo
gstash-offline-plugins-5.2.0.zip
Installing file: /D:/ES/logstash-5.2.0/logstash-offline-plugins-5.2.0.zip
ERROR: Something went wrong when installing file:///D:/ES/logstash-5.2.0/logstas
h-offline-plugins-5.2.0.zip, message: package is corrupt, exception while verify
ing: footer is not found (Zlib::GzipFile::NoFooter) in C:\Users\ASTEFAN\AppData\
Local\Temp/studtmp-d9a8f2593cc60b2ac379f15544b99ec73e9a7859a934e9b10ebdabd428f4/
logstash/logstash-output-syslog-3.0.1.gem
```

Installing with DEBUG=1

```
D:\ES\logstash-5.2.0\bin>set DEBUG=1
D:\ES\logstash-5.2.0\bin>logstash-plugin install file:///D:/ES/logstash-5.2.0/lo
gstash-offline-plugins-5.2.0.zip
Local file: /D:/ES/logstash-5.2.0/logstash-offline-plugins-5.2.0.zip
Installing with strategy: LogStash::PluginManager::PackInstaller::Local
Installing file: /D:/ES/logstash-5.2.0/logstash-offline-plugins-5.2.0.zip
Pack uncompressed to C:\Users\ASTEFAN\AppData\Local\Temp/studtmp-bce7ded94e0c729
9e8868d3cd9544f375644ae335538d7920b1d34a7e47f
Creating the index structure format from C:\Users\ASTEFAN\AppData\Local\Temp/stu
dtmp-bce7ded94e0c7299e8868d3cd9544f375644ae335538d7920b1d34a7e47f to C:\Users\AS
TEFAN\AppData\Local\Temp/studtmp-32f3c7cafdb1d932926fd9fa1f36279001c7843785100db
901ba8b679c8a
Generating indexes in C:\Users\ASTEFAN\AppData\Local\Temp/studtmp-32f3c7cafdb1d9
32926fd9fa1f36279001c7843785100db901ba8b679c8a
ERROR:  Unable to process C:\Users\ASTEFAN\AppData\Local\Temp/studtmp-32f3c7cafd
b1d932926fd9fa1f36279001c7843785100db901ba8b679c8a/gems/logstash-codec-plain-3.0
.2.gem
package is corrupt, exception while verifying: footer is not found (Zlib::GzipFi
le::NoFooter) in C:\Users\ASTEFAN\AppData\Local\Temp/studtmp-32f3c7cafdb1d932926
fd9fa1f36279001c7843785100db901ba8b679c8a/gems/logstash-codec-plain-3.0.2.gem (G
em::Package::FormatError)
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:57
1:in `verify_entry'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:57
9:in `verify_files'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package/tar_r
eader.rb:64:in `each'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:57
8:in `verify_files'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:50
8:in `verify'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package/tar_r
eader.rb:28:in `new'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:50
5:in `verify'
        org/jruby/RubyIO.java:1201:in `open'
        org/jruby/RubyKernel.java:325:in `open'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package/file_
source.rb:29:in `with_read_io'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:50
4:in `verify'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:48
5:in `spec'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/indexer.rb:22
1:in `map_gems_to_specs'
        org/jruby/RubyArray.java:2414:in `map'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/indexer.rb:21
4:in `map_gems_to_specs'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/indexer.rb:11
7:in `build_indicies'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/indexer.rb:31
0:in `generate_index'
        D:/ES/logstash-5.2.0/lib/pluginmanager/custom_gem_indexer.rb:53:in `upda
te_in_memory_index!'
        D:/ES/logstash-5.2.0/lib/pluginmanager/custom_gem_indexer.rb:58:in `inde
x'
        D:/ES/logstash-5.2.0/lib/pluginmanager/pack_installer/local.rb:32:in `ex
ecute'
        D:/ES/logstash-5.2.0/lib/pluginmanager/install.rb:32:in `execute'
        D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/
command.rb:67:in `run'
        D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/
subcommand/execution.rb:11:in `execute'
        D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/
command.rb:67:in `run'
        D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/
command.rb:132:in `run'
        D:\ES\logstash-5.2.0\lib\pluginmanager\main.rb:46:in `(root)'
ERROR:  Unable to process C:\Users\ASTEFAN\AppData\Local\Temp/studtmp-32f3c7cafd
b1d932926fd9fa1f36279001c7843785100db901ba8b679c8a/gems/logstash-output-syslog-3
.0.1.gem
package is corrupt, exception while verifying: footer is not found (Zlib::GzipFi
le::NoFooter) in C:\Users\ASTEFAN\AppData\Local\Temp/studtmp-32f3c7cafdb1d932926
fd9fa1f36279001c7843785100db901ba8b679c8a/gems/logstash-output-syslog-3.0.1.gem
(Gem::Package::FormatError)
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:57
1:in `verify_entry'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:57
9:in `verify_files'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package/tar_r
eader.rb:64:in `each'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:57
8:in `verify_files'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:50
8:in `verify'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package/tar_r
eader.rb:28:in `new'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:50
5:in `verify'
        org/jruby/RubyIO.java:1201:in `open'
        org/jruby/RubyKernel.java:325:in `open'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package/file_
source.rb:29:in `with_read_io'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:50
4:in `verify'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/package.rb:48
5:in `spec'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/indexer.rb:22
1:in `map_gems_to_specs'
        org/jruby/RubyArray.java:2414:in `map'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/indexer.rb:21
4:in `map_gems_to_specs'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/indexer.rb:11
7:in `build_indicies'
        D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/shared/rubygems/indexer.rb:31
0:in `generate_index'
        D:/ES/logstash-5.2.0/lib/pluginmanager/custom_gem_indexer.rb:53:in `upda
te_in_memory_index!'
        D:/ES/logstash-5.2.0/lib/pluginmanager/custom_gem_indexer.rb:58:in `inde
x'
        D:/ES/logstash-5.2.0/lib/pluginmanager/pack_installer/local.rb:32:in `ex
ecute'
        D:/ES/logstash-5.2.0/lib/pluginmanager/install.rb:32:in `execute'
        D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/
command.rb:67:in `run'
        D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/
subcommand/execution.rb:11:in `execute'
        D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/
command.rb:67:in `run'
        D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/
command.rb:132:in `run'
        D:\ES\logstash-5.2.0\lib\pluginmanager\main.rb:46:in `(root)'
Generating Marshal quick index gemspecs for 0 gems
Complete
Generated Marshal quick index gemspecs: 0.003s
Generating specs index
Generated specs index: 0.004s
Generating latest specs index
Generated latest specs index: 0.003s
Generating prerelease specs index
Generated prerelease specs index: 0.004s
Compressing indicies
Compressed indicies: 0.021s
Installing, logstash-output-syslog, version: 3.0.1 file: C:\Users\ASTEFAN\AppDat
a\Local\Temp/studtmp-bce7ded94e0c7299e8868d3cd9544f375644ae335538d7920b1d34a7e47
f/logstash/logstash-output-syslog-3.0.1.gem
Gem::Package::FormatError: package is corrupt, exception while verifying: footer
 is not found (Zlib::GzipFile::NoFooter) in C:\Users\ASTEFAN\AppData\Local\Temp/
studtmp-bce7ded94e0c7299e8868d3cd9544f375644ae335538d7920b1d34a7e47f/logstash/lo
gstash-output-syslog-3.0.1.gem
                verify_entry at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package.rb:571
                verify_files at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package.rb:579
                        each at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package/tar_reader.rb:64
                verify_files at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package.rb:578
                      verify at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package.rb:508
                         new at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package/tar_reader.rb:28
                      verify at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package.rb:505
                        open at org/jruby/RubyIO.java:1201
                        open at org/jruby/RubyKernel.java:325
                with_read_io at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package/file_source.rb:29
                      verify at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package.rb:504
                        spec at D:/ES/logstash-5.2.0/vendor/jruby/lib/ruby/share
d/rubygems/package.rb:485
                        spec at D:/ES/logstash-5.2.0/lib/pluginmanager/gem_insta
ller.rb:41
                     gem_dir at D:/ES/logstash-5.2.0/lib/pluginmanager/gem_insta
ller.rb:57
  create_destination_folders at D:/ES/logstash-5.2.0/lib/pluginmanager/gem_insta
ller.rb:87
                     install at D:/ES/logstash-5.2.0/lib/pluginmanager/gem_insta
ller.rb:28
                     install at D:/ES/logstash-5.2.0/lib/pluginmanager/gem_insta
ller.rb:36
                     execute at D:/ES/logstash-5.2.0/lib/pluginmanager/pack_inst
aller/local.rb:42
                        each at org/jruby/RubyArray.java:1613
                     execute at D:/ES/logstash-5.2.0/lib/pluginmanager/pack_inst
aller/local.rb:40
                     execute at D:/ES/logstash-5.2.0/lib/pluginmanager/install.r
b:32
                         run at D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gem
s/clamp-0.6.5/lib/clamp/command.rb:67
                     execute at D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gem
s/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                         run at D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gem
s/clamp-0.6.5/lib/clamp/command.rb:67
                         run at D:/ES/logstash-5.2.0/vendor/bundle/jruby/1.9/gem
s/clamp-0.6.5/lib/clamp/command.rb:132
                      (root) at D:\ES\logstash-5.2.0\lib\pluginmanager\main.rb:4
6
D:\ES\logstash-5.2.0\bin>
```

@ph

**Comment by ph** [comment]
@ESamir Thanks for reporting it, This was fixed in https://github.com/elastic/logstash/pull/6840 and that should be included in 5.3.1.
