### ISSUE TITLE
Strange behavior JSON logging is enabled and rabbitmq output shuts down.

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#6906]
logstash.yml:

```
log.format: json
```

logstash config:

<details>

```
input {
generator {
    count => 1000
    lines => ["teszt message1","teszt mesage2","teszt messae3","teszt messae4 teszt","teszt message5"]
    threads => 1
    }
}
output {
  stdout { codec => rubydebug }
  rabbitmq {
    host => "localhost"
    exchange => "asm"
    exchange_type => "fanout"
    persistent => true
    workers => 1
    durable => true
    password => "guest"
  }
}
```
</details>

WIth this configuration, only JSON logs should be emitted. However, when Logstash starts its shutdown sequence, a non-JSON log message is emitted.

<details>

```
2017-04-11 06:22:02,297 AMQP Connection 127.0.0.1:5672 ERROR java.net.SocketException: Socket is closed java.net.SocketException: Socket is closed
	at java.net.Socket.getSoTimeout(Socket.java:1157)
	at com.rabbitmq.client.impl.SocketFrameHandler.getTimeout(SocketFrameHandler.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:633)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:672)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:678)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:157)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2444)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:355)
	at com.fasterxml.jackson.core.JsonGenerator.writeObjectField(JsonGenerator.java:1442)
	at org.logstash.log.CustomLogEventSerializer.serialize(CustomLogEventSerializer.java:28)
	at org.logstash.log.CustomLogEventSerializer.serialize(CustomLogEventSerializer.java:11)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130)
	at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1428)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:1129)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:983)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:83)
	at org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(JsonLayout.java:937)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:63)
	at org.apache.logging.log4j.core.layout.JsonLayout.toSerializable(JsonLayout.java:801)
	at org.apache.logging.log4j.core.layout.AbstractJacksonLayout.toSerializable(AbstractJacksonLayout.java:33)
	at org.apache.logging.log4j.core.layout.AbstractStringLayout.toByteArray(AbstractStringLayout.java:253)
	at org.apache.logging.log4j.core.layout.AbstractLayout.encode(AbstractLayout.java:159)
	at org.apache.logging.log4j.core.layout.AbstractLayout.encode(AbstractLayout.java:36)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:120)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:113)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:104)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:155)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:128)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:119)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:390)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:375)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:359)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:349)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2005)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1876)
	at org.apache.logging.log4j.spi.AbstractLogger.warn(AbstractLogger.java:2639)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:421)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:288)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:27)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:50)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:225)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:219)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_BLOCK(ASTInterpreter.java:112)
	at org.jruby.runtime.Interpreted19Block.evalBlockBody(Interpreted19Block.java:206)
	at org.jruby.runtime.Interpreted19Block.yield(Interpreted19Block.java:194)
	at org.jruby.runtime.Interpreted19Block.call(Interpreted19Block.java:125)
	at org.jruby.runtime.Block.call(Block.java:101)
	at org.jruby.RubyProc.call(RubyProc.java:300)
	at org.jruby.RubyProc.call19(RubyProc.java:281)
	at org.jruby.RubyProc$INVOKER$i$0$0$call19.call(RubyProc$INVOKER$i$0$0$call19.gen)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:218)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:214)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:202)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:112)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:169)
	at MarchHare$$ShutdownListener_576622282.shutdownCompleted(MarchHare$$ShutdownListener_576622282.gen:13)
	at com.rabbitmq.client.impl.ShutdownNotifierComponent.notifyListeners(ShutdownNotifierComponent.java:77)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:593)
	at java.lang.Thread.run(Thread.java:745)
```
</details>

What I see from this stack trace is:

* Within the AMQP client, the Shutdown notifications are being sent
* which calls into Ruby
* which logs a warning
* which tries to serialize some objects to JSON
* and in serializing, asks for a Socket's timeout value, which, itself, throws an exception?

**Comment by jordansissel** [comment]
Here's what I think summarizes the behavior, but I haven't made an isolated reproduction case yet:

1) RabbitMQ is shutting down because Logstash is terminating
2) Logstash logs that RabbitMQ is shutting down connections
3) When logging this, Logstash also logs some context (any exceptions), and when Jackson serializes this, it invokes a method on a `com.rabbitmq.client.impl.SocketFrameHandler` instance, `getTimeout`. This throws a SocketException because the socket is already closed.

It seems like the old battle has resurfaced -- the reason I moved away from JSON logs in the first place, haha, was to avoid [exceptions during serialization](https://github.com/jordansissel/ruby-cabin/commit/6407d9a2fcc8077b6be06e1b63549dbe5f679103).

This issue, I hope, won't be too hard to solve. I believe we need to just update what we do in the Rabbitmq `on_shutdown` handler over in the logstash-output-rabbitmq plugin.

reference:  https://github.com/elastic/logstash/issues/1569

**Comment by jordansissel** [comment]
Ahh ok, I think I am right. I can reproduce with `bin/logstash -i pry`

```
[17] pry(#<LogStash::Runner>)> socket = java.net.Socket.new("localhost", 22)
=> #<Java::JavaNet::Socket:0x79c500ef>
[19] pry(#<LogStash::Runner>)> sf = com.rabbitmq.client.impl.SocketFrameHandler.new(socket)
=> #<Java::ComRabbitmqClientImpl::SocketFrameHandler:0x760e0b3c>

# Socket is still open, try logging, and it should work:
[20] pry(#<LogStash::Runner>)> logger.info("Hello", a: sf)
{"level":"INFO","loggerName":"logstash.runner","timeMillis":1491919637309,"thread":"LogStash::Runner","logEvent":{"message":"Hello","a":{"timeout":0,"address":"localhost","port":22,"localAddress":"127.0.0.1","localPort":58692}}}
=> nil

# Close the socket
[21] pry(#<LogStash::Runner>)> socket.close
=> nil

# Now try logging again. This should fail due to serialization:
[22] pry(#<LogStash::Runner>)> logger.info("Hello", a: sf)
2017-04-11 07:07:21,929 LogStash::Runner ERROR java.net.SocketException: Socket is closed java.net.SocketException: Socket is closed
	at java.net.Socket.getSoTimeout(Socket.java:1157)
	at com.rabbitmq.client.impl.SocketFrameHandler.getTimeout(SocketFrameHandler.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
....


# Let's try to just serialize with JSON and see it also fail
[24] pry(#<LogStash::Runner>)> LogStash::Json.dump(sf)
LogStash::Json::GeneratorError: Socket is closed
```

**Comment by jordansissel** [comment]
Reproducing this:

```
% bin/logstash --log.format=json -e 'output { rabbitmq { host => localhost exchange => foobar exchange_type => fanout } }'
<type some stuff to feed stdin>
^C
{"level":"WARN","loggerName":"logstash.agent","timeMillis":1493928185069,"thread":"LogStash::Runner","logEvent":{"message":"stopping pipeline","id":"main"}}
2017-05-04 13:03:05,191 AMQP Connection 127.0.0.1:5672 ERROR java.net.SocketException: Socket is closed java.net.SocketException: Socket is closed
```

**Comment by jordansissel** [comment]
Filed https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/40 with a patch.

**Comment by jordansissel** [comment]
Closing this in favor of tracking this in https://github.com/logstash-plugins/logstash-mixin-rabbitmq_connection/pull/40
