### ISSUE TITLE
Clarify stalling_thread_info in log messages

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash#6908]
As part of the shutdown watcher, we write a field named `stalling_thread_info` out to the log files:

```
stalling_thread_info"=>{"other"=>[{"thread_id"=>38, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:213:in `run'"}, {"thread_id"=>39, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:213:in `run'"}, {"thread_id"=>40, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.12-java/lib/logstash/inputs/beats.rb:213:in `run'"}], ["LogStash::Filters::Mutate", 
```
Perhaps we can revisit and look into renaming `stalling_thread_info` to something that indicates outstanding threads for just seeing threads listed here doesn't necessarily mean that something is getting stuck/stalled or is hanging.  The shutdown process can actually be working and eventually shut down the JVM gracefully.   "Stalling" can be misinterpreted as something that has gone wrong.

**Comment by mxplusb** [comment]
I'm currently troubleshooting a production outage and this log message led me here. Good to know it's not indicative of a problem, necessarily...
