### ISSUE TITLE
Faillure in master since merge of the refactor

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6935]
```
Pending:
  LogStash::Agent#execute when auto_reload is true when calling reload_state! with a config that contains reload incompatible plugins does not upgrade the new config
    # Temporarily skipped with xcontext
    # ./logstash-core/spec/logstash/agent_spec.rb:257
  LogStash::Agent#upgrade_pipeline when the upgrade fails and current state is empty should not start a pipeline
    # Temporarily skipped with xcontext
    # ./logstash-core/spec/logstash/agent_spec.rb:374

Failures:

  1) LogStash::Config::Source::Local::ConfigPathLoader when it exist relative path returns alphabetically sorted parts
     Failure/Error: expect(parts.collect { |part| ::File.basename(part.source_id) }).to eq(files.keys.sort)
       
       expected: ["config1.conf"]
            got: []
       
       (compared using ==)
     # ./logstash-core/spec/logstash/config/source/local_spec.rb:72:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'

  2) LogStash::Config::Source::Local::ConfigPathLoader when it exist relative path returns a `config_parts` per file
     Failure/Error: expect(subject.read(reader_config).size).to eq(files.size)
       
       expected: 1
            got: 0
       
       (compared using ==)
     # ./logstash-core/spec/logstash/config/source/local_spec.rb:67:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'

Finished in 1 minute 45.08 seconds (files took 6.53 seconds to load)
1962 examples, 2 failures, 2 pending

Failed examples:

rspec ./logstash-core/spec/logstash/config/source/local_spec.rb:70 # LogStash::Config::Source::Local::ConfigPathLoader when it exist relative path returns alphabetically sorted parts
rspec ./logstash-core/spec/logstash/config/source/local_spec.rb:66 # LogStash::Config::Source::Local::ConfigPathLoader when it exist relative path returns a `config_parts` per file

Randomized with seed 25855

**Comment by ph** [comment]
```
 1) LogStash::Agent metrics after config reloading when reloading a good config does not set the last reload error
     Failure/Error: expect(value).to be(nil)
       
       expected nil
            got #<Hash:1400292> => {:message=>"<LogStash::Plugin (class)> received :lookup with unexpected arguments\n  expected: (\"output\", \"dummyoutput2\")\n       got: (\"output\", \"stdout\")\n Please stub a default value first if message might be received with other args as well. \n", :backtrace=>["/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/error_generator.rb:213:in `__raise'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/error_generator.rb:54:in `raise_missing_default_stub_error'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/proxy.rb:198:in `raise_missing_default_stub_error'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/proxy.rb:178:in `message_received'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/proxy.rb:313:in `message_received'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/method_double.rb:73:in `proxy_method_invoked'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/method_double.rb:60:in `define_proxy_method'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:101:in `plugin'", "(eval):8:in `initialize'", "org/jruby/RubyKernel.java:1079:in `eval'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:69:in `initialize'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/pipeline_action/reload.rb:30:in `execute'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:301:in `converge_state'", "org/jruby/RubyArray.java:1613:in `each'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:286:in `converge_state'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:150:in `converge_state_and_update'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:148:in `converge_state_and_update'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:101:in `execute'", "org/jruby/RubyProc.java:281:in `call'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:18:in `interval'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/home/travis/build/elastic/logstash/logstash-core/spec/logstash/agent_spec.rb:459:in `(root)'"]}
     # ./logstash-core/spec/logstash/agent_spec.rb:525:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'
Finished in 2 minutes 33.8 seconds (files took 6.51 seconds to load)
2770 examples, 1 failure, 2 pending
```

**Comment by colinsurprenant** [comment]
also getting
```
Failures:
  1) LogStash::Agent metrics after config reloading when reloading a good config sets the success reload timestamp
     Failure/Error: expect(value).to be_a(LogStash::Timestamp)
       expected nil to be a kind of LogStash::Timestamp
     # ./logstash-core/spec/logstash/agent_spec.rb:519:in `(root)'
Finished in 6 minutes 36 seconds (files took 6.48 seconds to load)
2403 examples, 1 failure, 2 pending
Failed examples:
rspec ./logstash-core/spec/logstash/agent_spec.rb:516 # LogStash::Agent metrics after config reloading when reloading a good config sets the success reload timestamp
Randomized with seed 53000
```

**Comment by colinsurprenant** [comment]
and
```
  1) LogStash::Agent Agent execute options when `config.reload.automatic` is set to `TRUE` and succesfully load the config converges periodically the pipelines from the configs source
     Failure/Error: expect(source_loader.fetch_count).to be > 1
       expected: > 1
            got:   1
     # ./logstash-core/spec/logstash/agent/converge_spec.rb:115:in `(root)'
Finished in 13 minutes 52 seconds (files took 14.53 seconds to load)
2638 examples, 1 failure, 2 pending
Failed examples:
rspec ./logstash-core/spec/logstash/agent/converge_spec.rb:110 # LogStash::Agent Agent execute options when `config.reload.automatic` is set to `TRUE` and succesfully load the config converges periodically the pipelines from the configs source
Randomized with seed 37950
```

**Comment by ph** [comment]
Thanks @colin, will fix them, will check if I can make the agent_spec more robust I was able to make a PR to remove it glad I let it cook a bit.

**Comment by colinsurprenant** [comment]
related  #6931

**Comment by colinsurprenant** [comment]
related #6929

**Comment by ph** [comment]
I was able to reproduce the `relative path` issues, I believe the code is fine, the test is a bit weird. I will clean that up.

**Comment by ph** [comment]
>  1) LogStash::Agent metrics after config reloading when reloading a good config does not set the last reload error
     Failure/Error: expect(value).to be(nil)
>   1) LogStash::Agent metrics after config reloading when reloading a good config sets the success reload timestamp
     Failure/Error: expect(value).to be_a(LogStash::Timestamp)
       expected nil to be a kind of LogStash::Timestamp
     # ./logstash-core/spec/logstash/agent_spec.rb:519:in `(root)'

We had theses error before the agent refactor, I suspect other things is going on in the collector

**Comment by ph** [comment]
```
  1) LogStash::Agent metrics after config reloading when reloading a good config does not set the last reload error
     Failure/Error: expect(value).to be(nil)
       
       expected nil
            got #<Hash:4501738> => {:message=>"<LogStash::Plugin (class)> received :lookup with unexpected arguments\n  expected: (\"output\", \"dummyoutput2\")\n       got: (\"output\", \"stdout\")\n Please stub a default value first if message might be received with other args as well. \n", :backtrace=>["/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/error_generator.rb:213:in `__raise'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/error_generator.rb:54:in `raise_missing_default_stub_error'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/proxy.rb:198:in `raise_missing_default_stub_error'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/proxy.rb:178:in `message_received'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/proxy.rb:313:in `message_received'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/method_double.rb:73:in `proxy_method_invoked'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/rspec-mocks-3.1.3/lib/rspec/mocks/method_double.rb:60:in `define_proxy_method'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:101:in `plugin'", "(eval):8:in `initialize'", "org/jruby/RubyKernel.java:1079:in `eval'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/pipeline.rb:69:in `initialize'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/pipeline_action/reload.rb:30:in `execute'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:301:in `converge_state'", "org/jruby/RubyArray.java:1613:in `each'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:286:in `converge_state'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:150:in `converge_state_and_update'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:148:in `converge_state_and_update'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:101:in `execute'", "org/jruby/RubyProc.java:281:in `call'", "/home/travis/build/elastic/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:18:in `interval'", "/home/travis/build/elastic/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/home/travis/build/elastic/logstash/logstash-core/spec/logstash/agent_spec.rb:459:in `(root)'"]}
     # ./logstash-core/spec/logstash/agent_spec.rb:525:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:44:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'
Finished in 2 minutes 33.2 seconds (files took 5.75 seconds to load)
2008 examples, 1 failure, 2 pending
Failed examples:
rspec ./logstash-core/spec/logstash/agent_spec.rb:522 # LogStash::Agent metrics after config reloading when reloading a good config does not set the last reload error
Randomized with seed 4116

**Comment by ph** [comment]
I wasn't able to reproduce the error from the last comment, but I have a hypothesis I think it's because we try to mock something in a multi threaded context.
