### ISSUE TITLE
Api reloads count doesn't seems to be correctly set on the first try.

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6958]
This is a message we have from our integration suite, but it doesn't generate any test failure, but logstash shouldn't crash and this values should always be present.

```
2017-04-24T19:25:33,200][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-04-24T19:25:33,282][ERROR][logstash.agent           ] Internal API server error {:status=>500, :request_method=>"GET", :path_info=>"/_node/stats/pipeline", :query_string=>"", :http_version=>"HTTP/1.1", :http_accept=>nil, :error=>"Unexpected Internal Error", :class=>"LogStash::Instrument::MetricStore::MetricNotFound", :message=>"For path: pipelines. Map keys: [:reloads]", :backtrace=>["/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/instrument/metric_store.rb:225:in `get_recursively'", "org/jruby/RubyArray.java:1613:in `each'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/instrument/metric_store.rb:235:in `get_recursively'", "org/jruby/RubyArray.java:1613:in `each'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/instrument/metric_store.rb:224:in `get_recursively'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/instrument/metric_store.rb:95:in `get'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/instrument/metric_store.rb:94:in `get'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/instrument/metric_store.rb:108:in `get_shallow'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/api/service.rb:26:in `get_shallow'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/api/commands/stats.rb:49:in `pipeline'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/api/modules/node_stats.rb:48:in `pipeline_payload'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/api/modules/node_stats.rb:12:in `HEAD /?:filter?'", "org/jruby/RubyMethod.java:116:in `call'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/1.9/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `compile!'", "org/jruby/RubyProc.java:281:in `call'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/1.9/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `route!'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/1.9/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/1.9/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `route!'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/1.9/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `process_route'", "org/jruby/RubyKernel.java:1242:in `catch'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/1.9/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/1.9/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `route!'", "org/jruby/RubyArray.java:1613:in `each'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/1.9/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-a

**Comment by ph** [comment]
This error is a bit weird, I am not if its because the API system is not completely started at that point, #6955 might help in that case.

**Comment by andrewvc** [comment]
This looks like an actual bug, we should make sure metrics are ready before querying them via API.

**Comment by jsvd** [comment]
Just an update that this can still happen in 6.2.4. To replicate with some success, in a tab run:
` while true; do curl -f http://localhost:9600/_node -m 1; sleep 0.1; done`

and in another start logstash:  `bin/logstash -e ""`

curl will go from "connection refused", to "internal server error" to responding correctly:

```
curl: (7) Failed to connect to localhost port 9600: Connection refused
curl: (7) Failed to connect to localhost port 9600: Connection refused
curl: (7) Failed to connect to localhost port 9600: Connection refused
curl: (7) Failed to connect to localhost port 9600: Connection refused
curl: (22) The requested URL returned error: 500 Internal Server Error
curl: (22) The requested URL returned error: 500 Internal Server Error
curl: (22) The requested URL returned error: 500 Internal Server Error
curl: (22) The requested URL returned error: 500 Internal Server Error
curl: (22) The requested URL returned error: 500 Internal Server Error
curl: (22) The requested URL returned error: 500 Internal Server Error
curl: (22) The requested URL returned error: 500 Internal Server Error
curl: (22) The requested URL returned error: 500 Internal Server Error
{"host":"Joaos-MBP-5.lan","version":"6.2.4","http_address":"127.0.0.1:9600","id":"f0e3ece3-fd84-4b73-9d9a-2739e62f14ba","name":"Joaos-MBP-5.lan","pipelines":{"main":{}},"os":{"name":"Mac OS X","arch":"x86_64","version":"10.12.6","available_processors":4},"jvm":{"pid":45602,"version":"1.8.0_111","vm_version":"1.8.0_111","vm_vendor":"Oracle Corporation","vm_name":"Java HotSpot(TM) 64-Bit Server VM","start_time_in_millis":1525423223741,"mem":{"heap_init_in_bytes":1073741824,"heap_max_in_bytes":1038876672,"non_heap_init_in_bytes":2555904,"non_heap_max_in_bytes":0},"gc_collectors":["ParNew","ConcurrentMarkSweep"]}}{"host":"Joaos-MBP-5.lan","version":"6.2.4","http_address":"127.0.0.1:9600","id":"f0e3ece3-fd84-4b73-9d9a-2739e62f14ba","name":"Joaos-MBP-5.lan","pipelines":{"main":{}},"os":{"name":"Mac OS X","arch":"x86_64","version":"10.12.6","available_processors":4},"jvm":{"pid":45602,"version":"1.8.0_111","vm_version":"1.8.0_111","vm_vendor":"Oracle Corporation","vm_name":"Java HotSpot(TM) 64-Bit Server VM","start_time_in_millis":1525423223741,"mem":{"heap_init_in_bytes":1073741824,"heap_max_in_bytes":1038876672,"non_heap_init_in_bytes":2555904,"non_heap_max_in_bytes":0},"gc_collectors":["ParNew","ConcurrentMarkSweep"]}}
```
