### ISSUE TITLE
Test failure for: LogStash::Agent Environment Variables In Configs environment variable templating are evaluated at plugins creation

### ISSUE THREAD

**Issue by ph** [elastic/logstash#6978]
```
 1) LogStash::Agent Environment Variables In Configs environment variable templating are evaluated at plugins creation
     Failure/Error: expect(subject.converge_state_and_update).to be_a_successful_converge
       Expected all actions to be successful:
           pipeline_id: main, message: Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main
     # ./logstash-core/spec/logstash/agent_spec.rb:333:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:47:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:216:in `invoke_prerequisites'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:193:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'
Finished in 6 minutes 59 seconds (files took 6.24 seconds to load)
2355 examples, 1 failure, 2 pending
Failed examples:
rspec ./logstash-core/spec/logstash/agent_spec.rb:332 # LogStash::Agent Environment Variables In Configs environment variable templating are evaluated at plugins creation
Randomized with seed 59633

**Comment by ph** [comment]
I haven't been able to reproduce that easily, I have added code to keep track return value of the action.

**Comment by original-brownbear** [comment]
@ph have you seen this recently? I ran 

```bash
for i in `seq 1000`; do bin/rspec ./logstash-core/spec/logstash/agent_spec.rb; done
```

for almost an hour now with no luck and have not seen this one ever. Also just looking at the logic of this, this code failing effectively means that the pipeline just erred out for the settings given which don't look non-standard in any way (in so far that I dont see what's special about them and wouldn't also happen in similar tests).
Could it be that this was some local act of god like running out of fds or did you see this more than one?

**Comment by ph** [comment]
I've only seen it once, but the `agent_spec` was recently refactored by @jsvd to remove the sleeps so it might have fixed it? I am ok with closing and reopening if needed?

**Comment by original-brownbear** [comment]
@ph yea there were a few changes to the sleeps (though those seem to not directly interact), but also to related actual `agent.rb` code in between.

Closing then, thanks! :)
