### ISSUE TITLE
5.4.0 undefined method 'dlq_writer' 

### ISSUE THREAD

**Issue by LeeDr** [elastic/logstash#6986]
- Version:  5.4.0-797cd833 (.deb file installed and started as a service)
- Operating System: Ubuntu 14.04 
- Config File (if you have sensitive info, please remove it): 
```
root@packer-virtualbox-iso-1492351135:~# cat /etc/logstash/conf.d/logstash.conf
input {
  file {
    path => "/var/log/syslog"
    start_position => "beginning"
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => { "message" => "%{SYSLOGTIMESTAMP:syslog_timestamp} %{SYSLOGHOST:syslog_hostname} %{DATA:syslog_program}(?:\[%{POSINT:syslog_pid}\])?: %{GREEDYDATA:syslog_message}" }
      add_field => [ "received_at", "%{@timestamp}" ]
      add_field => [ "received_from", "%{host}" ]
    }
    date {
      match => [ "syslog_timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "logstash_internal"
    password => "changeme"
    ssl => true
    cacert => "/etc/logstash/sslconfig/ca.crt"
  }
}
```

```
root@packer-virtualbox-iso-1492351135:~# grep -v "^#" /etc/logstash/logstash.yml
path.data: /var/lib/logstash
path.config: /etc/logstash/conf.d
path.logs: /var/log/logstash
xpack.monitoring.elasticsearch.url: https://localhost:9200
xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: changeit
xpack.monitoring.elasticsearch.ssl.ca: "/etc/logstash/sslconfig/ca.crt"
```

- Sample Data: just a Ubuntu /var/log/syslog
- Steps to Reproduce: start logstash on Ubuntu with above config

```
[2017-04-27T14:20:07,196][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<NoMethodError: undefined method `dlq_writer' for #<LogStash::ExecutionContext:0x46f3da2f>>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.0-java/lib/logstash/outputs/elasticsearch/common.rb:20:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:41:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:268:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:279:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:279:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:288:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:214:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:398:in `start_pipeline'"]}
[2017-04-27T14:20:07,210][ERROR][logstash.pipeline        ] Error registering plugin {:plugin=>"#<LogStash::OutputDelegator:0x2991302e @namespaced_metric=#<LogStash::Instrument::NamespacedMetric:0x6c93bb78 @metric=#<LogStash::Instrument::Metric:0x5c9ae1f @collector=#<LogStash::Instrument::Collector:0x68a5b1a5 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x106ee113 @store=#<Concurrent::Map:0x2d6cbda6 @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x364cab2f>, @fast_lookup=#<Concurrent::Map:0x73a11cda @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"64927baa3b36b351ccad93b9c13eb70fa7f9c69f-4\"]>, @metric=#<LogStash::Instrument::NamespacedMetric:0x7d057894 @metric=#<LogStash::Instrument::Metric:0x5c9ae1f @collector=#<LogStash::Instrument::Collector:0x68a5b1a5 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x106ee113 @store=#<Concurrent::Map:0x2d6cbda6 @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x364cab2f>, @fast_lookup=#<Concurrent::Map:0x73a11cda @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs]>, @logger=#<LogStash::Logging::Logger:0x741354e9 @logger=#<Java::OrgApacheLoggingLog4jCore::Logger:0x724716c>>, @strategy=#<LogStash::OutputDelegatorStrategies::Shared:0x44cdbae9 @output=<LogStash::Outputs::ElasticSearch hosts=>[https://localhost:9200], user=>\"logstash_internal\", password=><password>, ssl=>true, cacert=>\"/etc/logstash/sslconfig/ca.crt\", id=>\"64927baa3b36b351ccad93b9c13eb70fa7f9c69f-4\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_cc4ac8c8-2d14-4aab-8886-cae8c6b27eaa\", enable_metric=>true, charset=>\"UTF-8\">, workers=>1, index=>\"logstash-%{+YYYY.MM.dd}\", manage_template=>true, template_name=>\"logstash\", template_overwrite=>false, idle_flush_time=>1, doc_as_upsert=>false, script_type=>\"inline\", script_lang=>\"painless\", script_var_name=>\"event\", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, action=>\"index\", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>>, @id=\"64927baa3b36b351ccad93b9c13eb70fa7f9c69f-4\", @metric_events=#<LogStash::Instrument::NamespacedMetric:0x3096ce6f @metric=#<LogStash::Instrument::Metric:0x5c9ae1f @collector=#<LogStash::Instrument::Collector:0x68a5b1a5 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x106ee113 @store=#<Concurrent::Map:0x2d6cbda6 @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x364cab2f>, @fast_lookup=#<Concurrent::Map:0x73a11cda @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"64927baa3b36b351ccad93b9c13eb70fa7f9c69f-4\", :events]>, @output_class=LogStash::Outputs::ElasticSearch>", :error=>"undefined method `dlq_writer' for #<LogStash::ExecutionContext:0x8f2bc3a @pipeline_id=\"main\">"}
```

**Comment by LeeDr** [comment]
root@packer-virtualbox-iso-1492351135:/usr/share/logstash# bin/logstash-plugin list --verbose logstash-output-elasticsearch
logstash-output-elasticsearch (7.3.0)

**Comment by jsvd** [comment]
the 5.4 branch's Gemfile isn't locking the es output plugin to < 7 like the 5.3 branch does, which means 5.4 is shipping with 7.x of the es output:

on 5.3 https://github.com/elastic/logstash/blob/5.3/Gemfile#L101
on 5.4 https://github.com/elastic/logstash/blob/5.4/Gemfile#L99

**Comment by jsvd** [comment]
actually this is unrelated to #6987.

the logstash-output-elasticsearch 7.3.0 introduced the possibility of using DLQ if the logstash-core supports it. unfortunately [the detection code for the bwc layer](https://github.com/logstash-plugins/logstash-output-elasticsearch/blob/491a3e0b4e9aa789e7412e01887f5196a4bd04ec/lib/logstash/outputs/elasticsearch/common.rb#L19-L20) is incorrect, since 5.4 has execution context but doesn't have a `dlq_writer` method.

**Comment by jsvd** [comment]
published es output 7.3.1 where the bwc layer for dlq is fixed: https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/594

**Comment by ph** [comment]
@jsvd Should we yank 7.3.0?

**Comment by jsvd** [comment]
it's just a release with a but and now there's a patch release, so I'm ok with not yanking

**Comment by suyograo** [comment]
Fixed in logstash-plugins/logstash-output-elasticsearch#594
