### ISSUE TITLE
Logstash 5.3.2 crashes on startup with NameError: uninitialized constant LogStash::Logger

### ISSUE THREAD

**Issue by harelmoshe** [elastic/logstash#7020]
While attempting to run LogStash 5.3.2 with Kafka plugin v5.0.2, the following error occurs:

[2017-05-04T13:32:30,482][ERROR][logstash.agent] Pipeline aborted due to error {:exception=>#<NameError: uninitialized constant LogStash::Logger>, :backtrace=>["org/jruby/RubyModule.java:2719:in `const_missing'", "/logstash-5.3.2/vendor/local_gems/858d3776/logstash-input-kafka-5.0.2/lib/logstash/inputs/kafka.rb:168:in `register'", "/logstash-5.3.2/logstash-core/lib/logstash/pipeline.rb:257:in `register_plugin'", "/logstash-5.3.2/logstash-core/lib/logstash/pipeline.rb:268:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "/logstash-5.3.2/logstash-core/lib/logstash/pipeline.rb:268:in `register_plugins'", "/logstash-5.3.2/logstash-core/lib/logstash/pipeline.rb:412:in `start_inputs'", "/logstash-5.3.2/logstash-core/lib/logstash/pipeline.rb:312:in `start_workers'", "/logstash-5.3.2/logstash-core/lib/logstash/pipeline.rb:207:in `run'", "/logstash-5.3.2/logstash-core/lib/logstash/agent.rb:389:in `start_pipeline'"]}

Of course, the **logstash-core** folder is present in the logstash folder itself, and contains the **lib/logstash/logging/logger.rb** file which holds the allegedly missing class.

Commenting out line 168 in that file makes LogStash start-up successfully:

`LogStash::Logger.setup_log4j(@logger)`

**Comment by svrc-pivotal** [comment]
you'll want to bump the plugin to at least 5.0.6 or higher which fixed this

**Comment by harelmoshe** [comment]
Thanks, @svrc-pivotal ! problem solved.
