### ISSUE TITLE
DNS lookups failing when `ndots` is specified in /etc/resolv.conf

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7030]
Parent bug: https://bugs.ruby-lang.org/issues/10412

This was fixed and backported into ruby 2.0.0, but as we are targeting 1.9.3, we'll need to patch this ourselves.

Found by @tylerjl.

Reproducing:

```
>> Resolv::DNS.new(nameserver: "8.8.8.8", search: "foo", ndots: 2).getaddress("google.com")
Resolv::ResolvError: DNS result has no information for google.com
```

Looking up a rooted (with `.` at the end) name works, though, indicating this is an ndots/search problem:

```
>> Resolv::DNS.new(nameserver: "8.8.8.8", search: "foo", ndots: 2).getaddress("google.com.")
=> #<Resolv::IPv4 216.58.195.78>
```

**Comment by Jeiwan** [comment]
This bug causes a big problem with https://github.com/logstash-plugins/logstash-input-twitter on a Kubernetes cluster. Here's a log from Logstash:
```
03:16:47.279 [[main]<twitter] WARN  logstash.inputs.twitter - Twitter client error {
:message=>"no address for stream.twitter.com", 
:exception=>"Resolv::ResolvError", 
:backtrace=>[
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:98:in `getaddress'", 
"/usr/share/logstash/vendor/jruby/lib/ruby/1.9/resolv.rb:48:in `getaddress'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.5/lib/logstash/inputs/twitter/patches.rb:26:in `stream'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.5/lib/logstash/inputs/twitter/patches.rb:58:in `request'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", 
"/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.5/lib/logstash/inputs/twitter.rb:138:in `run'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:456:in `inputworker'", 
"/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:449:in `start_input'"
], :options=>nil}
```
(the address is reachable from the container)
In a Kubernetes cluster, `ndots: 5` is set by default.

**Comment by tylerjl** [comment]
@Jeiwan I also ran into this when attempting to get an LS pipeline up and running in k8s, but I do have a hacky workaround to make it work in the meantime until this is resolved.

The ruby bug Jordan addressed includes an example patch that fixes the issue, so I've derived a Dockerfile to patch the affected file in-place. It's not pretty, but I can confirm that it works and since a custom Dockerfile is usually needed anyway (to install any needed plugins), it's not a terribly big bit of overhead.

The relevant lines from my `Dockerfile`:

```
FROM docker.elastic.co/logstash/logstash:5.3.2

# We have to patch a weird bug that manifests in kubernetes...
USER root
RUN apt install -y patch
USER logstash
COPY resolv.patch /tmp/
RUN cd /opt/logstash/vendor/jruby/lib/ruby/1.9 && patch < /tmp/resolv.patch
```

And the `resolv.patch` file in the same cwd:

```
--- /usr/lib/ruby/1.8/resolv.rb 2010-12-22 22:22:57.000000000 -0500
+++ resolv.rb   2014-08-20 18:50:05.653882000 -0400
@@ -945,6 +945,10 @@
             candidates = []
           end
           candidates.concat(@search.map {|domain| Name.new(name.to_a + domain)})
+          fname = Name.create("#{name}.")
+          if !candidates.include?(fname)
+              candidates << fname
+          end
         end
         return candidates
       end
```

Subsequently building and running this image in k8s should resolve those errors.

**Comment by Jeiwan** [comment]
@tylerjl Thank you! It works. I didn't know the sources were there and tried to patch 'twitter' gem.
