### ISSUE TITLE
Fails: LogStash::Instrument::WrappedWriteClient AckedMemoryQueue pushes single event to the `WriteClient`      Failure/Error: expect(read_client.read_batch.size).to eq(1)

### ISSUE THREAD

**Issue by ph** [elastic/logstash#7032]
https://logstash-ci.elastic.co/job/elastic+logstash+5.x+multijob-os-compatibility/os=amazon/268/console
```
Failures:

  1) LogStash::Instrument::WrappedWriteClient AckedMemoryQueue pushes single event to the `WriteClient`
     Failure/Error: expect(read_client.read_batch.size).to eq(1)
       
       expected: 1
            got: 0
       
       (compared using ==)
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:28:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/rakelib/test.rake:40:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:216:in `invoke_prerequisites'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:193:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'

  2) LogStash::Instrument::WrappedWriteClient AckedMemoryQueue pushes batch to the `WriteClient`
     Failure/Error: subject { described_class.new(write_client, pipeline, metric, plugin) }
       Double "pipeline" was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/logstash-core/lib/logstash/instrument/wrapped_write_client.rb:7:in `initialize'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:19:in `subject'
     # /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/amazon/logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:25:in `(root)'

Finished in 6 minutes 36 seconds (files took 5.72 seconds to load)
2689 examples, 2 failures

Failed examples:
```

**Comment by jsvd** [comment]
another instance of this: https://logstash-ci.elastic.co/job/elastic+logstash+5.x+multijob-os-compatibility/os=fedora/275/console

Also this job showed a NPE in the Queue code:

```
Exception in thread "Ruby-0-Thread-40: /var/lib/jenkins/workspace/elastic+logstash+5.x+multijob-os-compatibility/os/fedora/logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:36" java.lang.NullPointerException
	at org.logstash.ackedqueue.Queue.write(Queue.java:317)
	at org.logstash.ackedqueue.ext.JrubyAckedQueueMemoryExtLibrary$RubyAckedMemoryQueue.ruby_write(JrubyAckedQueueMemoryExtLibrary.java:152)
	at org.logstash.ackedqueue.ext.JrubyAckedQueueMemoryExtLibrary$RubyAckedMemoryQueue$INVOKER$i$1$0$ruby_write.call(JrubyAckedQueueMemoryExtLibrary$RubyAckedMemoryQueue$INVOKER$i$1$0$ruby_write.gen)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at org.jruby.ast.CallOneArgNode.interpret(CallOneArgNode.java:57)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
```

**Comment by ph** [comment]
I've rewrote the test, I am not sure anymore that the NPE is justified there.

**Comment by ph** [comment]
Will close this since #7103 is merged, lets see if the NPE is still showing somewhere.
