### ISSUE TITLE
logstash exception NoMethodError: undefined method `\u003e'

### ISSUE THREAD

**Issue by ronakg** [elastic/logstash#7049]
Hi,

I'm hitting following exception from time to time.

```
18:49:50.473 [[main]\u003eworker6] ERROR logstash.pipeline - Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.          {"exception"=\u003e#\u003cNoMethodError: undefined method `\u003e' for {}:Hash\u003e, "backtrace"=\u003e["(eval):1244:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1242:in          `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):566:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:378:in `filter_batch'", "org/jruby/RubyProc.java:281:in  `call'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:201:in `each'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/util/  wrapped_synchronous_queue.rb:200:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:377:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in         `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:331:in `start_workers'"]}
18:49:50.658 [LogStash::Runner] FATAL logstash.runner - An unexpected error occurred! {:error=\u003e#\u003cNoMethodError: undefined method `\u003e' for {}:Hash\u003e, :backtrace=\u003e["(eval):1244:in    `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1242:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):566:in `filter_func'", "/usr/share/logstash/logstash-core/lib/    logstash/pipeline.rb:378:in `filter_batch'", "org/jruby/RubyProc.java:281:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:201:in `each'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:200:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:377:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:331:in `start_workers'"]}
```

I've looked in my configuration to make sure I'm not checking for a field that doesn't exist.

- Version: 5.2.2
- Operating System: Ubuntu 16.04
- Config File (if you have sensitive info, please remove it):

```
input {
    file {
        # kubelet created symlinks to docker container logs
        path => [ "/var/log/containers/*.log" ]
        tags => ["kubernetes"]
        start_position => "beginning"
        sincedb_path => "/etc/logstash/sincedb/kubernetes_logs"
    }
}

filter {
    # Convert the log to json
    json {
        source => "message"
        target => "message"
        remove_field => [ "[message][stream]" ]
    }

    # Grab the timestamp from the actual message, rather than at the point of
    # which events arrive
    if [message][time] {
        date {
            match => ["[message][time]", "ISO8601"]
            remove_field => [ "[message][time]" ]
        }
    }

    # Check if message["log"] looks like json and try to encode it and flatten
    # log fields out into a message field
    if [message][log] =~ /^\{.*\}$/ {
        json {
            source => "[message][log]"
            remove_field => "[message]"
        }

        if ! [lvl] {
            grok {
                match => { "[msgid]" => "%{POSINT:[lvl]}" }
            }
        }
    } else {

        # Check if we can drop the event early
        if 8 > 6 {
            drop {}
        }

    }

    # There are logs from thirdparty services which have json format like us, but have
    # different fields. Consider those at trace level as well
    if ! [lvl] {
        mutate {
            add_field => { "[msgid]" => "%DEFAULT-8-TRACE" }
            add_field => { "[params]" => "{}" }
            add_field => { "[tenant]" => "-1 NONE" }
            add_field => { "[lvl]" => 8 }
        }
    }

    mutate {
        replace => { "host" => "maglev-master-1" }
        convert => { "[lvl]" => "integer" }
    }

    # Check if we can drop the event early
    if [lvl] > 6 {
        drop {}
    }

    if [lvl] == 0 {
        mutate {
            add_field => { "severity" => "emergency" }
        }
    } else if [lvl] == 1 {
        mutate {
            add_field => { "severity" => "alert" }
        }
    } else if [lvl] == 2 {
        mutate {
            add_field => { "severity" => "critical" }
        }
    } else if [lvl] == 3 {
        mutate {
            add_field => { "severity" => "error" }
        }
    } else if [lvl] == 4 {
        mutate {
            add_field => { "severity" => "warning" }
        }
    } else if [lvl] == 5 {
        mutate {
            add_field => { "severity" => "notice" }
        }
    } else if [lvl] == 6 {
        mutate {
            add_field => { "severity" => "informational" }
        }

    } else if [lvl] >= 7 {
        mutate {
            add_field => { "severity" => "debug" }
        }
    }

    # Add kubernetes metadata and hostname
    kubernetes {}

    # Rename kubernetes.container_name to service
    mutate {
        rename => { "[kubernetes][container_name]" => "service" }
    }
}

output {


    # Exporting to local elasticsearch for monitoring
    if [lvl] <= 6 {

        # elasticsearch configuration
        elasticsearch {
            hosts => ["elasticsearch.cluster.local"]
            index => "logstash-%{+YYYY.MM.dd}"
        }

    }

}
```

**Comment by jsvd** [comment]
this is a strange one, have you tried updating to 5.4.0?
Also can you provide some logging at the --log.level=debug  level around that exception?

**Comment by ronakg** [comment]
I've upgraded to 5.4.0. Not sure if that'll fix the issue as it happens only intermittently. I'm closing this for now. Will reopen if needed.

Thanks.
