### ISSUE TITLE
[integration test failure] Test Kafka Input can ingest 37 apache log lines from Kafka broker

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7081]
seen in https://travis-ci.org/elastic/logstash/jobs/231200764#L2253-L2274

```
  1) Test Kafka Input can ingest 37 apache log lines from Kafka broker
     Failure/Error: expect(@fixture.output_exists?).to be true
     
       expected true
            got false
     # ./specs/kafka_input_spec.rb:24:in `(root)'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/stud-0.0.22/lib/stud/try.rb:79:in `try'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/stud-0.0.22/lib/stud/try.rb:95:in `try'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/stud-0.0.22/lib/stud/try.rb:91:in `try'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/stud-0.0.22/lib/stud/try.rb:123:in `try'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/logstash-devutils-1.3.1-java/lib/logstash/devutils/rspec/logstash_helpers.rb:18:in `try'
     # ./specs/kafka_input_spec.rb:23:in `(root)'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
Finished in 15 minutes 4 seconds (files took 5.76 seconds to load)
32 examples, 1 failure
Failed examples:
rspec ./specs/kafka_input_spec.rb:19 # Test Kafka Input can ingest 37 apache log lines from Kafka broker
```

**Comment by original-brownbear** [comment]
@suyograo closing here, this should be good now

**Comment by jsvd** [comment]
@original-brownbear could this still be an instance of the same problem ? https://travis-ci.org/elastic/logstash/jobs/232651438#L1924-L1939

**Comment by original-brownbear** [comment]
@jsvd I don't think so, that's not a Kafka related failure at all right? Seems almost like coming from a slight change to the data in the geoip dataset?

**Comment by jsvd** [comment]
indeed, I'll open an separate issue
