### ISSUE TITLE
[test failure] Test Logstash instance should keep the same id between restarts

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7086]
from: https://travis-ci.org/elastic/logstash/jobs/231513226#L2429

```
  1) Test Logstash instance should keep the same id between restarts
     Failure/Error: JSON.parse(open("http://localhost:9600/").read)["id"]
     
     Errno::ECONNREFUSED:
       Connection refused - Connection refused
     # ./specs/01_logstash_bin_smoke_spec.rb:164:in `get_id'
     # ./specs/01_logstash_bin_smoke_spec.rb:175:in `(root)'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
Finished in 25 minutes 38 seconds (files took 14.15 seconds to load)
34 examples, 1 failure
Failed examples:
rspec ./specs/01_logstash_bin_smoke_spec.rb:167 # Test Logstash instance should keep the same id between restarts
```

**Comment by jsvd** [comment]
taking on this one. should be just a matter of wrapping get_id in a try, as logstash process may be up but the webserver not yet.
