### ISSUE TITLE
bin/logstash-plugin update failed due to httparty 0.15.x

### ISSUE THREAD

**Issue by fixlair** [elastic/logstash#7164]
- Version: tested on Logstash 2.4.1
- Operating System: Debian Jessie
- Config File (if you have sensitive info, please remove it): N/A
- Steps to Reproduce:

1. `Run bin/logstash-plugin update`
2. output : 
```
Error Bundler::InstallError, retrying 1/10
An error occurred while installing httparty (0.15.5), and Bundler cannot continue.
Make sure that `gem install httparty -v '0.15.5'` succeeds before bundling.
WARNING: SSLSocket#session= is not supported
```

In Debug Mode : 
1. `DEBUG=1 bin/logstash-plugin update`
2. 
```
(...)
Using geoip 1.6.3
0:  geoip (1.6.3) from /opt/logstash/vendor/bundle/jruby/1.9/specifications/geoip-1.6.3.gemspec
Using gmetric 0.1.3
0:  gmetric (0.1.3) from /opt/logstash/vendor/bundle/jruby/1.9/specifications/gmetric-0.1.3.gemspec
Using multi_xml 0.6.0
0:  multi_xml (0.6.0) from /opt/logstash/vendor/bundle/jruby/1.9/specifications/multi_xml-0.6.0.gemspec

Gem::InstallError: httparty requires Ruby version >= 2.0.0.
/opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:560:in `ensure_required_ruby_version_met'
/opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:782:in `pre_install_checks'
/opt/logstash/vendor/jruby/lib/ruby/shared/rubygems/installer.rb:231:in `install'
(...)
/opt/logstash/lib/pluginmanager/main.rb:43:in `(root)'
Bundler::InstallError: An error occurred while installing httparty (0.15.5), and Bundler cannot continue.
Make sure that `gem install httparty -v '0.15.5'` succeeds before bundling.

```

In fact Version publied on Rubygem on May 11 2017 of httparty is 0.15.0 (now the latest is 0.15.5) and require now require Ruby 2.0 :  https://github.com/jnunemaker/httparty/blob/master/Changelog.md
But Logstash use jruby 1.9.

**Comment by fixlair** [comment]
For information my initial problem was : 
On a fresh install of Logstash 2.4.1 :  I was not able to run a 
`bin/logstash-plugin`
Output was : 
`Gem::LoadError: You have already activated json 1.8.6, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this
`

So i tried the `bin/logstash-plugin update` without success as explained in the first message.


I found a workaround on my server with the following  : 
1. update a plugin with a json dependancy for example I run : 
`bin/logstash-plugin update logstash-filter-json`
With success
2. remove logstash-output-hipchat plugin wich has dependancy to httparty !
`bin/logstash-plugin uninstall logstash-output-hipchat`
3. now run with success : 
`bin/logstash-plugin update`

And now this command work !
`bin/logstash-plugin list` :)

**Comment by techpanga** [comment]
Is there a fix for this issue. 

I also see this. I could not update or install any plugins on logstash 5.4.

**Comment by MrPrimate** [comment]
@mossholderm I'm also seeing this, it seems you have to run the update for logstash-filter-json first

```
[root@server logstash]# bin/logstash-plugin uninstall logstash-output-hipchat
Gem::LoadError: You have already activated json 1.8.6, but your Gemfile requires json 1.8.3. Prepending `bundle exec` to your command may solve this.
    setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
     each at org/jruby/RubyArray.java:1613
     each at /opt/logstash/vendor/jruby/lib/ruby/1.9/forwardable.rb:201
    setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/runtime.rb:19
    setup at /opt/logstash/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler.rb:122
   setup! at /opt/logstash/lib/bootstrap/bundler.rb:64
  execute at /opt/logstash/lib/pluginmanager/uninstall.rb:16
      run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
  execute at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
      run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67
      run at /opt/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132
   (root) at /opt/logstash/lib/pluginmanager/main.rb:43
[root@server logstash]# bin/logstash-plugin update logstash-filter-json
No plugin updated
[root@server logstash]# bin/logstash-plugin uninstall logstash-output-hipchat
Uninstalling logstash-output-hipchat
[root@server logstash]# 

```

**Comment by jsvd** [comment]
this seems to be working now:

```
/tmp/logstash-2.4.1 % bin/logstash-plugin uninstall logstash-output-hipchat
Uninstalling logstash-output-hipchat
/tmp/logstash-2.4.1 % bin/logstash-plugin list hipchat
ERROR: No plugins found

```
