### ISSUE TITLE
randomized test creates DuplicateFormatFlagsException in test

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#7184]
There seems to be a problem with some values of the random `page_count` https://github.com/elastic/logstash/blob/47517b89321cdcad5970a243554e6fd3c4d882c8/logstash-core/src/test/java/org/logstash/ackedqueue/QueueTest.java#L299 which result is a `DuplicateFormatFlagsException`.
Did not analyze but its probably when the random `page_count` is set to its limit?

```
org.logstash.ackedqueue.QueueTest > randomAcking FAILED
    java.util.DuplicateFormatFlagsException: Flags = '0'
        at java.util.Formatter$Flags.parse(Formatter.java:4443)
        at java.util.Formatter$FormatSpecifier.flags(Formatter.java:2640)
        at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2709)
        at java.util.Formatter.parse(Formatter.java:2560)
        at java.util.Formatter.format(Formatter.java:2501)
        at java.util.Formatter.format(Formatter.java:2455)
        at java.lang.String.format(String.java:2940)
        at org.logstash.ackedqueue.QueueTest.randomAcking(QueueTest.java:305)
```

**Comment by colinsurprenant** [comment]
again in https://logstash-ci.elastic.co/job/elastic+logstash+5.x+multijob-os-compatibility/os=fedora/305/console

**Comment by original-brownbear** [comment]
let me try :)

**Comment by original-brownbear** [comment]
easily reproducible by running in a local loop with current `master`

**Comment by original-brownbear** [comment]
fixed by https://github.com/elastic/logstash/pull/7262
