### ISSUE TITLE
Logstash data folder appears to have incorrect permissiosn

### ISSUE THREAD

**Issue by todd-bowles-console** [elastic/logstash#7190]
I've been struggling with this issue ever since I tried to upgrade to 5.4.0 this morning. Logstash 5.2.0 does not exhibit the same problem.

I've created a data directory for logstash using the following script:

```
sudo mkdir -p /data/logstash || exit 1
sudo chown -R logstash:logstash /data/logstash || exit 1
sudo chmod g+s /data/logstash || exit 1
sudo chmod -R g+rwx /data/logstash || exit 1
```

I've configured logstash.yml to contain /data/logstash as the data directory.

When logstash starts up, it creates a /data/logstash/queue directory, which is fine.

It can't write to it though.

```
[2017-05-24T04:42:02,021][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Path "/data/logstash/queue" must be a writable directory. It is not writable.>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:433:in `validate'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:216:in `validate_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:132:in `validate_all'", "org/jruby/RubyHash.java:1342:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:131:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:217:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:185:in `run'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}
```

This seems to cause it to go into an infinite startup loop, it slams the CPU and generally just keeps doing that until I tell it to stop.

The permissions of /data/logstash are:

```
$ stat /data/logstash
  File: ‘/data/logstash’
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: ca01h/51713d    Inode: 270682      Links: 3
Access: (2775/drwxrwsr-x)  Uid: (  498/logstash)   Gid: (  497/logstash)
Access: 2017-05-24 04:38:08.560851615 +0000
Modify: 2017-05-24 04:38:25.456851615 +0000
Change: 2017-05-24 04:38:25.456851615 +0000
 Birth: -
```

And the permissions of /data/logstash/queue are:

```
$ stat /data/logstash/queue
  File: ‘/data/logstash/queue’
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: ca01h/51713d    Inode: 270685      Links: 2
Access: (2755/drwxr-sr-x)  Uid: (    0/    root)   Gid: (  497/logstash)
Access: 2017-05-24 04:38:25.456851615 +0000
Modify: 2017-05-24 04:38:25.456851615 +0000
Change: 2017-05-24 04:38:25.456851615 +0000
 Birth: -
```

I honestly have no idea whats going on. I don't even know how it managed to create a directory it couldn't access.

I can create the queue directory myself, but I don't feel like that's a particular robust solution, when the configuration only asked for a root directory (which I created and gave to it).

**Comment by Docker-Donegal** [comment]
did you manage to sort the problem?

**Comment by todd-bowles-console** [comment]
I did not manage to get to the root of the issue. Instead all I did was create the queue directory myself and ensure it had the correct permissions before running Logstash.

I haven't upgraded Logstash since then either, so maybe its better in a newer version?

My knowledge of Linux environments is limited to be honest, so perhaps I was just doing something stupid with the folders? It still feels weird that the user id of the subfolder (the one Logstash created) was root, when the parent was clearly logstash.

**Comment by ilovemysillybanana** [comment]
I'm on logstash 6.3.0 and can confirm that this issue is still occurring. It is a total PITA to find too if you're new to logstash and elk in general.
