### ISSUE TITLE
[test failure: 5.x] LogStash::Pipeline when collecting metrics in the pipeline pipelines populates the output metrics

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#7197]
https://logstash-ci.elastic.co/job/elastic+logstash+5.x+dockerubuntu-periodic/2210/console

```
Failures:

  1) LogStash::Pipeline when collecting metrics in the pipeline pipelines populates the output metrics
     Failure/Error: expect(collected_metric[:stats][:pipelines][:main][:plugins][:outputs][plugin_name][:events][:out].value).to eq(number_of_events)
       
       expected: 420
            got: 331
       
       (compared using ==)
     # ./logstash-core/spec/logstash/pipeline_spec.rb:829:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./lib/bootstrap/rspec.rb:13:in `(root)'

Finished in 14 minutes 34 seconds (files took 9.92 seconds to load)
2668 examples, 1 failure, 1 pending

Failed examples:

rspec ./logstash-core/spec/logstash/pipeline_spec.rb:825 # LogStash::Pipeline when collecting metrics in the pipeline pipelines populates the output metrics

Randomized with seed 60527
```

**Comment by jakelandis** [comment]
Closing since we no longer have the docker periodic tests, many changes w/r/t to test retries and metrics since this was logged.
