### ISSUE TITLE
[test failure: 5.4] WrappedAckedQueue with multiple writers with simulate_work OFF > larger event size < behaves like a well behaved queue writes, reads, closes and reopens

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#7231]
https://logstash-ci.elastic.co/job/elastic+logstash+5.4+dockerubuntu-periodic/518/console

```
Failures:

  1) LogStash::Util::WrappedAckedQueue with multiple writers with simulate_work OFF > larger event size < behaves like a well behaved queue writes, reads, closes and reopens
     Failure/Error: expect(output_strings).to eq([])
       
       expected: []
            got: ["File count after close mismatch expected: 2 got: 3", "checkpoint.431", "checkpoint.head", "page.476", "{:counts=>[20419, 19675, 19906, 0, 0, 0, 0, 0], :page_capacity_multiplier=>20, :page_capacity=>1048576, :queue_checkpoint_acks=>1024, :queue_checkpoint_writes=>1024, :queue_checkpoint_interval=>1000, :queue_capacity_multiplier=>128, :queue_capacity=>134217728, :writers=>3, :expected_count=>60000, :items=>20000, :string_size=>8192, :batch_size=>500, :batch_wait=>1000, :readers=>3, :simulate_work=>false, :writers_finished=>#<Concurrent::AtomicBoolean:0x54fde296>}"]
       
       (compared using ==)
     Shared Example Group: "a well behaved queue" called from ./logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb:277
     # ./logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb:121:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
     # ./rakelib/test.rake:40:in `(root)'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:194:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:216:in `invoke_prerequisites'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:214:in `invoke_prerequisites'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:193:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:108:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:80:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/lib/rake/application.rb:77:in `run'
     # ./vendor/bundle/jruby/1.9/gems/rake-12.0.0/exe/rake:27:in `(root)'

Finished in 15 minutes 38 seconds (files took 18.19 seconds to load)
2511 examples, 1 failure, 1 pending

Failed examples:

rspec ./logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb:71 # LogStash::Util::WrappedAckedQueue with multiple writers with simulate_work OFF > larger event size < behaves like a well behaved queue writes, reads, closes and reopens

Randomized with seed 32947

```

**Comment by colinsurprenant** [comment]
Again in 5.4 https://logstash-ci.elastic.co/job/elastic+logstash+5.4+dockerubuntu-periodic/562/console

**Comment by colinsurprenant** [comment]
closing ... this does not seem to happen anymore.
