### ISSUE TITLE
OAuth error using twitter API

### ISSUE THREAD

**Issue by Varunram** [elastic/logstash#7246]
Operating System: masOS Sierra 10.12.5
P.S. The tokens are right, double-checked them just to be sure.
I've attached the config and the stack trace below.
Logstash config:
```input {
  twitter {
      consumer_key => "xxx"
      consumer_secret => "xxx"
      oauth_token => "xxx"
      oauth_token_secret => "xxx"
      keywords => ["elastic]
      full_tweet => true
  }
}

output {
  stdout {}
  elasticsearch {
    hosts => "localhost"
    index => "twitter"
    document_type => "tweet"
    template => "twitter.json"
    template_name => "twitter"
  }
}
```
```
[2017-05-29T12:21:37,474][WARN ][logstash.inputs.twitter  ] Twitter client error {:message=>"", :exception=>"Twitter::Error::Unauthorized", :backtrace=>["/usr/local/Cellar/logstash/5.4.0/libexec/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb:21:in `on_headers_complete'", "org/ruby_http_parser/RubyHttpParser.java:370:in `<<'", "/usr/local/Cellar/logstash/5.4.0/libexec/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/response.rb:16:in `<<'", "/usr/local/Cellar/logstash/5.4.0/libexec/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.3/lib/logstash/inputs/twitter/patches.rb:31:in `stream'", "/usr/local/Cellar/logstash/5.4.0/libexec/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.3/lib/logstash/inputs/twitter/patches.rb:58:in `request'", "/usr/local/Cellar/logstash/5.4.0/libexec/vendor/bundle/jruby/1.9/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:37:in `filter'", "/usr/local/Cellar/logstash/5.4.0/libexec/vendor/bundle/jruby/1.9/gems/logstash-input-twitter-3.0.3/lib/logstash/inputs/twitter.rb:138:in `run'", "/usr/local/Cellar/logstash/5.4.0/libexec/logstash-core/lib/logstash/pipeline.rb:443:in `inputworker'", "/usr/local/Cellar/logstash/5.4.0/libexec/logstash-core/lib/logstash/pipeline.rb:436:in `start_input'"], :options=>nil}
```

**Comment by untergeek** [comment]
This sounds like it should be in the [logstash-input-twitter](https://github.com/logstash-plugins/logstash-input-twitter) repository rather than the core Logstash one.  Can you please move it?
