### ISSUE TITLE
Integ test failure: Beats plugin was not found

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#7299]
https://travis-ci.org/elastic/logstash/jobs/238998526

```
[2017-06-03T04:21:41,489][ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"input", :name=>"beats", :path=>"logstash/inputs/beats", :error_message=>"\n\n\tyou might need to reinstall the gem which depends on the missing jar or in case there is Jars.lock then resolve the jars with `lock_jars` command\n\nno such file to load -- io/netty/netty-all/4.1.3.Final/netty-all-4.1.3.Final (LoadError)", :error_class=>RuntimeError, :error_backtrace=>["/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jar_dependencies.rb:348:in `do_require'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jar_dependencies.rb:255:in `require_jar'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jar_dependencies.rb:0:in `require_jar_with_block'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/vendor/bundle/jruby/1.9/gems/jar-dependencies-0.3.11/lib/jar_dependencies.rb:254:in `require_jar'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/lib/bootstrap/patches/jar_dependencies.rb:6:in `require_jar'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/vendor/bundle/jruby/1.9/gems/logstash-input-beats-4.0.0-java/lib/logstash-input-beats_jars.rb:4:in `(root)'", "org/jruby/RubyKernel.java:1040:in `require'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/vendor/bundle/jruby/1.9/gems/logstash-input-beats-4.0.0-java/lib/logstash/inputs/beats.rb:1:in `(root)'", "org/jruby/RubyKernel.java:1040:in `require'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/vendor/bundle/jruby/1.9/gems/logstash-input-beats-4.0.0-java/lib/logstash/inputs/beats.rb:7:in `(root)'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/plugins/registry.rb:1:in `(root)'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/plugins/registry.rb:155:in `legacy_lookup'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/plugins/registry.rb:137:in `lookup'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/plugins/registry.rb:179:in `lookup_pipeline_plugin'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "org/jruby/RubyKernel.java:1079:in `eval'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:114:in `plugin'", "(eval):8:in `initialize'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:81:in `initialize'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/pipeline.rb:179:in `initialize'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/pipeline_action/create.rb:35:in `execute'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/agent.rb:340:in `converge_state'", "org/jruby/RubyArray.java:1613:in `each'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/agent.rb:139:in `with_pipelines'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/agent.rb:337:in `converge_state'", "/home/travis/build/elastic/logstash/build/logstash-6.0.0-alpha2-SNAPSHOT/logstash-core/lib/logstash/agent.rb:324:in `converge_state'", 
```

**Comment by suyograo** [comment]
Must be related to the new beats published on Friday: https://rubygems.org/gems/logstash-input-beats/versions/4.0.0-java

**Comment by original-brownbear** [comment]
let me see if I can fix this, this is kinda annoying :)

**Comment by suyograo** [comment]
https://rubygems.org/gems/logstash-input-beats/versions/3.1.15-java is 8.01 MB while the new ones are 28.5 KB. Something is busted with the publishing. It may not be including the jar deps.

**Comment by original-brownbear** [comment]
@suyograo nice thanks, link https://github.com/logstash-plugins/logstash-input-beats/issues/210

**Comment by jakelandis** [comment]
Do we also want to yank 3.1.16 since it will be included in the 5.5 release ?

**Comment by original-brownbear** [comment]
@suyograo ping, the above makes a lot of sense imo :)

**Comment by original-brownbear** [comment]
fixed by @suyograo :)
