### ISSUE TITLE
ES Output IT is Failing ~100% of Times!

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7304]
I see this one in basically all PRs https://travis-ci.org/elastic/logstash/jobs/239121919#L2056.

```sh
Failures:
  1) Test Elasticsearch output can ingest 37K log lines of sample apache logs
     Failure/Error: expect(result["hits"]["total"]).to eq(37)
     
       expected: 37
            got: 0
     
       (compared using ==)
     # ./specs/es_output_how_spec.rb:25:in `(root)'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `(root)'
Finished in 8 minutes 43 seconds (files took 4.61 seconds to load)
29 examples, 1 failure
Failed examples:
rspec ./specs/es_output_how_spec.rb:17 # Test Elasticsearch output can ingest 37K log lines of sample apache logs
Randomized with seed 46182

```

**Comment by original-brownbear** [comment]
This is broken because ES output in general doesn't work (at least with default settings):

```sh
➜  logstash git:(master) bin/logstash -e 'input { generator { threads => 1 }  } output { elasticsearch { } }'                                               
WARNING: Default JAVA_OPTS will be overridden by the JAVA_OPTS defined in the environment. Environment JAVA_OPTS are -Xms1g -Xmx1g
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /Users/brownbear/src/logstash/logs which is now configured via log4j2.properties
[2017-06-05T10:51:54,179][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/Users/brownbear/src/logstash/data/dead_letter_queue"}
[2017-06-05T10:51:54,203][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"887cfee7-5b32-4ec4-87ff-ab5a89deb4c3", :path=>"/Users/brownbear/src/logstash/data/uuid"}
[2017-06-05T10:51:54,260][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because 'config.string' (-e) is being used.
[2017-06-05T10:51:54,300][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-06-05T10:51:54,750][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://127.0.0.1:9200/]}}
[2017-06-05T10:51:54,751][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://127.0.0.1:9200/, :path=>"/"}
[2017-06-05T10:51:54,754][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :thread=>"#<Thread:0x61a02949 run>", :plugin=>"#<LogStash::OutputDelegator:0x6ef1b126 @namespaced_metric=#<LogStash::Instrument::NamespacedMetric:0x3c3c79a3 @metric=#<LogStash::Instrument::Metric:0x3e85817d @collector=#<LogStash::Instrument::Collector:0x34553d91 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x574ec2bc @store=#<Concurrent::Map:0x8e05897 @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x1a7cbe9f>, @fast_lookup=#<Concurrent::Map:0x758b1f4 @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"34339009ccf92cd3bd8484e09f9228c5871deff7-2\"]>, @metric=#<LogStash::Instrument::NamespacedMetric:0x2c0c0832 @metric=#<LogStash::Instrument::Metric:0x3e85817d @collector=#<LogStash::Instrument::Collector:0x34553d91 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x574ec2bc @store=#<Concurrent::Map:0x8e05897 @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x1a7cbe9f>, @fast_lookup=#<Concurrent::Map:0x758b1f4 @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs]>, @logger=#<LogStash::Logging::Logger:0x11ee1fe0 @logger=#<Java::OrgApacheLoggingLog4jCore::Logger:0x4bbb364c>>, @strategy=#<LogStash::OutputDelegatorStrategies::Shared:0x6d39ea11 @output=<LogStash::Outputs::ElasticSearch id=>\"34339009ccf92cd3bd8484e09f9228c5871deff7-2\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_dc7edf03-6358-47b6-ae1c-1d601c25a4fd\", enable_metric=>true, charset=>\"UTF-8\">, workers=>1, index=>\"logstash-%{+YYYY.MM.dd}\", manage_template=>true, template_name=>\"logstash\", template_overwrite=>false, hosts=>[//127.0.0.1], idle_flush_time=>1, doc_as_upsert=>false, script_type=>\"inline\", script_lang=>\"painless\", script_var_name=>\"event\", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, action=>\"index\", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>>, @id=\"34339009ccf92cd3bd8484e09f9228c5871deff7-2\", @metric_events=#<LogStash::Instrument::NamespacedMetric:0x6054845f @metric=#<LogStash::Instrument::Metric:0x3e85817d @collector=#<LogStash::Instrument::Collector:0x34553d91 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x574ec2bc @store=#<Concurrent::Map:0x8e05897 @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x1a7cbe9f>, @fast_lookup=#<Concurrent::Map:0x758b1f4 @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"34339009ccf92cd3bd8484e09f9228c5871deff7-2\", :events]>, @output_class=LogStash::Outputs::ElasticSearch>", :error=>"bad argument (expected URI object or URI string)"}
[2017-06-05T10:51:54,755][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :thread=>"#<Thread:0x61a02949 run>", :exception=>#<ArgumentError: bad argument (expected URI object or URI string)>, :backtrace=>["/Users/brownbear/src/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:537:in `convert_to_uri'", "/Users/brownbear/src/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:236:in `join'", "/Users/brownbear/src/logstash/vendor/jruby/lib/ruby/1.9/uri/common.rb:785:in `join'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:98:in `format_url'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:67:in `perform_request'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:269:in `perform_request_to_url'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:237:in `healthcheck!'", "org/jruby/RubyHash.java:1342:in `each'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:233:in `healthcheck!'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:319:in `update_urls'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:70:in `start'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:284:in `build_pool'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:60:in `initialize'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:101:in `create_http_client'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:97:in `build'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch.rb:230:in `build_client'", "/Users/brownbear/src/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/common.rb:28:in `register'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/output_delegator.rb:41:in `register'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/pipeline.rb:351:in `register_plugin'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/pipeline.rb:362:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/pipeline.rb:362:in `register_plugins'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/pipeline.rb:371:in `start_workers'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/pipeline.rb:296:in `run'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/pipeline.rb:256:in `start'"]}
[2017-06-05T10:51:54,763][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main, action_result: false"}
```

**Comment by original-brownbear** [comment]
Caused by https://github.com/elastic/logstash/pull/7236, reverting #280722e fixes the issue

**Comment by original-brownbear** [comment]
see https://github.com/elastic/logstash/pull/7312
