### ISSUE TITLE
Pipeline does not terminate with SIGINT and stalls with error "undefined local variable or method event"

### ISSUE THREAD

**Issue by dedemorton** [elastic/logstash#7315]
Testing on 6.0.0-alpha2 (build candidate 2).

Here's the config:
```
input {
  generator {
    message => '{"static": "value", "rand": "changeme"}'
    codec => json
    count => 10000
  }
}

filter {
  ruby {
    code => 'event.set("rand", rand) if rand <= 0.95'
  }
}

output {
  elasticsearch {
    index => "demo"
  }
}
```
When I run the pipeline, I see way more events than I expect (199,266) and the pipeline hangs. When I press Ctrl+C (multiple times) Logstash stalls, and I see the following messages:

````
^C[2017-06-05T09:40:18,875][FATAL][logstash.runner          ] SIGINT received. Terminating immediately..
^C[2017-06-05T09:40:19,237][FATAL][logstash.runner          ] SIGINT received. Terminating immediately..
[2017-06-05T09:40:21,042][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>847, "stalling_thread_info"=>{["LogStash::Filters::Ruby", {"code"=>"event.set(\"rand\", rand) if rand <= 0.95", "id"=>"206a9f8bd6a577207cce0964163b937b7bdaef8b-2"}]=>[{"thread_id"=>25, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>26, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>27, "name"=>"[main]>worker2", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>28, "name"=>"[main]>worker3", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>29, "name"=>"[main]>worker4", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>30, "name"=>"[main]>worker5", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>31, "name"=>"[main]>worker6", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>32, "name"=>"[main]>worker7", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}]}}
[2017-06-05T09:40:26,045][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>847, "stalling_thread_info"=>{["LogStash::Filters::Ruby", {"code"=>"event.set(\"rand\", rand) if rand <= 0.95", "id"=>"206a9f8bd6a577207cce0964163b937b7bdaef8b-2"}]=>[{"thread_id"=>25, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>26, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>27, "name"=>"[main]>worker2", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>28, "name"=>"[main]>worker3", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>29, "name"=>"[main]>worker4", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>30, "name"=>"[main]>worker5", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>31, "name"=>"[main]>worker6", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>32, "name"=>"[main]>worker7", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}]}}
[2017-06-05T09:40:31,042][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>847, "stalling_thread_info"=>{["LogStash::Filters::Ruby", {"code"=>"event.set(\"rand\", rand) if rand <= 0.95", "id"=>"206a9f8bd6a577207cce0964163b937b7bdaef8b-2"}]=>[{"thread_id"=>25, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>26, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>27, "name"=>"[main]>worker2", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>28, "name"=>"[main]>worker3", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>29, "name"=>"[main]>worker4", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>30, "name"=>"[main]>worker5", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>31, "name"=>"[main]>worker6", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>32, "name"=>"[main]>worker7", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}]}}
[2017-06-05T09:40:36,042][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>847, "stalling_thread_info"=>{["LogStash::Filters::Ruby", {"code"=>"event.set(\"rand\", rand) if rand <= 0.95", "id"=>"206a9f8bd6a577207cce0964163b937b7bdaef8b-2"}]=>[{"thread_id"=>25, "name"=>"[main]>worker0", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>26, "name"=>"[main]>worker1", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>27, "name"=>"[main]>worker2", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>28, "name"=>"[main]>worker3", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>29, "name"=>"[main]>worker4", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>30, "name"=>"[main]>worker5", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>31, "name"=>"[main]>worker6", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}, {"thread_id"=>32, "name"=>"[main]>worker7", "current_call"=>"[...]/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/interval.rb:84:in `sleep'"}]}}
[2017-06-05T09:40:40,523][ERROR][logstash.outputs.elasticsearch] Encountered an unexpected error submitting a bulk request! Will retry. {:error_message=>"undefined local variable or method `event' for #<LogStash::Outputs::ElasticSearch:0x2ff00b8b>", :class=>"NameError", :backtrace=>["/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/common.rb:153:in `submit'", "org/jruby/RubyArray.java:1613:in `each'", "org/jruby/RubyEnumerable.java:974:in `each_with_index'", "/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/common.rb:131:in `submit'", "/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/common.rb:91:in `retrying_submit'", "/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.2-java/lib/logstash/outputs/elasticsearch/common.rb:42:in `multi_receive'", "/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'", "/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/logstash-core/lib/logstash/pipeline.rb:493:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/logstash-core/lib/logstash/pipeline.rb:491:in `output_batch'", "/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/logstash-core/lib/logstash/pipeline.rb:433:in `worker_loop'", "/Users/dedemorton/BuildTesting/6.0.0-alpha2_40867bdc/logstash-6.0.0-alpha2/logstash-core/lib/logstash/pipeline.rb:398:in `start_workers'"]}
````

**Comment by jsvd** [comment]
this has been fixed in the es output version 7.3.5 https://github.com/logstash-plugins/logstash-output-elasticsearch/commit/c56322b23f81fb0711fc86e86d0944e6e752fbd9

This means DLQ does not work in Logstash 6.0.0-alpha2 without updating the es output plugin.
