### ISSUE TITLE
CEF module: Unclear how to proceed with `Connection Refused` error

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7347]
```
% bin/logstash --modules cef

[2017-06-04T01:39:43,337][INFO ][logstash.modules.importer] Attempting PUT {:url_path=>"_template/cef", :file_path=>"/home/jls/projects/logstash/modules/cef/configuration/elasticsearch/cef.json"}
[2017-06-04T01:39:43,446][ERROR][logstash.elasticsearchclient] [Manticore::SocketException] Connection refused (Connection refused) {:host=>"localhost", :port=>9200, :protocol=>"http"}
[2017-06-04T01:39:43,456][ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>LogStash::ConfigLoadingError, :message=>"Failed to parse the module configuration: [Connection refused (Connection refused)]", :backtrace=>["/home/jls/projects/logstash/logstash-core/lib/logstash/config/modules_common.rb:39:in `pipeline_configs'", "org/jruby/RubyArray.java:1613:in `each'", "/home/jls/projects/logstash/logstash-core/lib/logstash/config/modules_common.rb:25:in `pipeline_configs'", "/home/jls/projects/logstash/logstash-core/lib/logstash/config/source/modules.rb:14:in `pipeline_configs'", "/home/jls/projects/logstash/logstash-core/lib/logstash/config/source_loader.rb:59:in `fetch'", "org/jruby/RubyArray.java:2409:in `collect'", "/home/jls/projects/logstash/logstash-core/lib/logstash/config/source_loader.rb:58:in `fetch'", "/home/jls/projects/logstash/logstash-core/lib/logstash/agent.rb:146:in `converge_state_and_update'", "/home/jls/projects/logstash/logstash-core/lib/logstash/agent.rb:88:in `execute'", "/home/jls/projects/logstash/logstash-core/lib/logstash/runner.rb:333:in `execute'", "org/jruby/RubyProc.java:281:in `call'", "/home/jls/projects/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"]}
[2017-06-04T01:39:43,458][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>RuntimeError, :message=>"Could not fetch the configuration, message: Failed to parse the module configuration: [Connection refused (Connection refused)]", :backtrace=>["/home/jls/projects/logstash/logstash-core/lib/logstash/agent.rb:153:in `converge_state_and_update'", "/home/jls/projects/logstash/logstash-core/lib/logstash/agent.rb:88:in `execute'", "/home/jls/projects/logstash/logstash-core/lib/logstash/runner.rb:333:in `execute'", "org/jruby/RubyProc.java:281:in `call'", "/home/jls/projects/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/task.rb:24:in `initialize'"]}
```

The errors here do not seem particularly actionable. The best hint I can see is this: `(Connection refused) {:host=>"localhost", :port=>9200, :protocol=>"http"}` which is a clue for me that Elasticsearch is expected to be at localhost by default.

**Comment by guyboertje** [comment]
Fixed by #7367
