### ISSUE TITLE
Test failure: two Plugin Manager test failures

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7389]
https://logstash-ci.elastic.co/job/elastic+logstash+feature-9000+dockerubuntu-periodic/98/console

```
Failures:

  1) LogStash::PluginManager::GemInstaller post_install_message when present when we want the message display the message
     Failure/Error: expect(LogStash::PluginManager.ui).to receive(:info).with(message)

       (#<LogStash::PluginManager::Shell:0x673ce30a>).info("Hello from the friendly pack")
           expected: 1 time with arguments: ("Hello from the friendly pack")
           received: 0 times
     # ./spec/unit/plugin_manager/gem_installer_spec.rb:39:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /tmp/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'

  2) LogStash::PluginManager::PackInstaller::Local when the local file exist when the pack is valid install the gems
     Failure/Error: expect(mock_indexer).to receive(:generate_index)

       (Double "Gem::Indexer").generate_index(*(any args))
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/unit/plugin_manager/pack_installer/local_spec.rb:61:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /tmp/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'

Finished in 5 minutes 30 seconds (files took 7.79 seconds to load)
2584 examples, 2 failures, 3 pending
```

**Comment by jakelandis** [comment]
Closing since we no longer have the docker periodic tests, and have not witnessed this recently.
