### ISSUE TITLE
Test failure: LogStash::Timestamp subtraction

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7391]
https://logstash-ci.elastic.co/job/elastic+logstash+feature-9000+dockerubuntu-periodic/68/console

```
  1) LogStash::Timestamp subtraction should work with numeric value
     Failure/Error: expect(t - 10).to eq(current)

       expected: 2017-06-05 19:36:17.118999999 +0000
            got: 2017-06-05 19:36:17.118000000 +0000

       (compared using ==)

       Diff:
       @@ -1,2 +1,2 @@
       -2017-06-05 19:36:17 +0000
       +2017-06-05 19:36:17 UTC
     # ./logstash-core/spec/logstash/legacy_ruby_timestamp_spec.rb:82:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /tmp/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'
```

**Comment by jakelandis** [comment]
closing this since we no longer have docker periodic tests, and believe that this may have been fixed by https://github.com/elastic/logstash/pull/7474
