### ISSUE TITLE
bin/logstash -e "" fails on master (IncompleteSourceWithMetadataException)

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7437]
tested commit 0332ee5087831aa1267ccd70a2a414ec6a5d633c

```
% bin/logstash -e ''
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to /home/jls/projects/logstash/logs which is now configured via log4j2.properties
[2017-06-13T05:11:42,058][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/home/jls/projects/logstash/data/dead_letter_queu
e"}
[2017-06-13T05:11:42,311][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"c4498f7e-690f-40ae-a519-ce5e031a3e81", :path=>"/home/jls/proje
cts/logstash/data/uuid"}
[2017-06-13T05:11:42,563][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because 'config.string' (-e) is being used.
[2017-06-13T05:11:42,608][ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>Java::OrgLogstashCommon::IncompleteSourceWithMetadataException, :message=>
"Missing attributes in SourceWithMetadata: ([]) [string]config_string:0:0:```\n\n```", :backtrace=>["org.logstash.common.SourceWithMetadata.<init>(org/logstash/common/SourceWithMetad
ata.java:66)", "java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:423)", "org.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/Jav
aConstructor.java:246)", "org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:1022)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.g
en)", "RUBY.read(/home/jls/projects/logstash/logstash-core/lib/logstash/config/source/local.rb:22)", "RUBY.pipeline_configs(/home/jls/projects/logstash/logstash-core/lib/logstash/con
fig/source/local.rb:154)", "RUBY.block in fetch(/home/jls/projects/logstash/logstash-core/lib/logstash/config/source_loader.rb:59)", "org.jruby.RubyArray.collect(org/jruby/RubyArray.
java:2472)", "org.jruby.RubyArray.collect(org/jruby/RubyArray.java:2481)", "org.jruby.RubyArray$INVOKER$i$0$0$collect19.call(org/jruby/RubyArray$INVOKER$i$0$0$collect19.gen)", "RUBY.
fetch(/home/jls/projects/logstash/logstash-core/lib/logstash/config/source_loader.rb:58)", "RUBY.converge_state_and_update(/home/jls/projects/logstash/logstash-core/lib/logstash/agen
t.rb:146)", "RUBY.execute(/home/jls/projects/logstash/logstash-core/lib/logstash/agent.rb:88)", "RUBY.block in execute(/home/jls/projects/logstash/logstash-core/lib/logstash/runner.r
b:333)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)", "org.jruby.RubyProc.call19(org/jruby/RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/Rub
yProc$INVOKER$i$0$0$call19.gen)", "RUBY.block in initialize(/home/jls/projects/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24)", "org.jruby.RubyProc.call(org
/jruby/RubyProc.java:289)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:246)", "java.lang.Thread.run(java/lang/Thread.java:745)"]}
[2017-06-13T05:11:42,618][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>RuntimeError, :message=>"Could not fetch the configuratio
n, message: Missing attributes in SourceWithMetadata: ([]) [string]config_string:0:0:```\n\n```", :backtrace=>["/home/jls/projects/logstash/logstash-core/lib/logstash/agent.rb:153:in
 `converge_state_and_update'", "/home/jls/projects/logstash/logstash-core/lib/logstash/agent.rb:88:in `execute'", "/home/jls/projects/logstash/logstash-core/lib/logstash/runner.rb:33
3:in `block in execute'", "/home/jls/projects/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}

```

**Comment by jordansissel** [comment]
Seems like [this line of code](https://github.com/elastic/logstash/blob/master/logstash-core/src/main/java/org/logstash/common/SourceWithMetadata.java#L58) is ignoring empty strings when considering something to hash (the attributes?) and when I provide an empty config string (valid in 5.x and 2.x) with `-e` it crashes because all attributes are empty or null values.

**Comment by andrewvc** [comment]
@jordansissel I recently added that. Hmmm, this is tricky. I mean, its kind of doing what I expected it to do?

The goal was to make it impossible to have 'empty' `SourceWithmetadata` objects. The reason here is that before you could either set a LIR vertex's `.source_with_metadata` property to null OR fill it in with a `SourceWithMetadata` object with blank or null properties. That made reasoning about metadata hard, because you would need to check so many things to determine whether you did or did not have metadata.

I think the fix here is to intercept an empty config and do nothing earlier.

WDYT? I'm glad to submit a patch when I have time.

**Comment by andrewvc** [comment]
The hacky fix would probably be to just check a `#empty` comment into the string perhaps.

**Comment by andrewvc** [comment]
To be clear, I do not advocate the hacky fix.

**Comment by jordansissel** [comment]
Yeah there's no rush on this fix. I doubt many folks use -e "" anyway. I
will dig a bit since I want to learn more about the newer code.

**Comment by jsvd** [comment]
haha I use `-e ""` it all the time, since I rely on the auto complete to provide me with a simple pipeline with stdin/stdout.
Also, I use `-e ""` when I want to manually check something about logstash startup, monitoring api, etc.

We've always supported this since we have the autocomplete for stdout/stdin. I guess we could talk about removing auto completion altogether (which I'm not a fan, but open to discuss it)?

**Comment by kares** [comment]
seems like this discussion is no longer relevat -> `-e ""` is :back: and :grinning:
