### ISSUE TITLE
Test failure: LogStash::Util::WrappedAckedQueue with multiple writers ...

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#7441]
Tested using JRuby 9.1.8.0

```
% bin/rspec logstash-core/spec

  1) LogStash::Util::WrappedAckedQueue with multiple writers with simulate_work OFF > larger event size < behaves like a well behaved queue writes, reads, closes and reopens
     Failure/Error: expect(output_strings).to eq([])

       expected: []
            got: ["File count after close mismatch expected: 2 got: 4", "page.476", "checkpoint.425", "checkpoint.424"...home/jls/projects/logstash/logstash-core/spec/logstash/acked_
queue_concurrent_stress_spec.rb:118>>"]

       (compared using ==)
     Shared Example Group: "a well behaved queue" called from ./logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb:277
     # ./logstash-core/spec/logstash/acked_queue_concurrent_stress_spec.rb:121:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /home/jls/projects/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.
rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'
```

**Comment by original-brownbear** [comment]
Can't reproduce this on OSX, this could be very system dependent :( What Kernel are you running this on? Also, you are running a VM for this (Vagrant nfs sync maybe?)?
