### ISSUE TITLE
`queue.drain` Setting is Broken

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7476]
Running with `queue.drain = true` leads to:

```sh
[2017-06-16T16:26:59,779][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `is_fully_acked?' for #<LogStash::Util::WrappedAckedQueue:0x33a7f62e>>, :backtrace=>["/Users/brownbear/src/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:132:in `empty?'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/pipeline.rb:785:in `draining_queue?'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/pipeline.rb:455:in `worker_loop'", "/Users/brownbear/src/logstash/logstash-core/lib/logstash/pipeline.rb:411:in `block in start_workers'"]}
```

for me. 

This is trivial to fix by simply adding another `.queue` in that method.

```sh
      def empty?
        @mutex.lock
        begin
          @queue.queue.is_fully_acked?
        ensure
          @mutex.unlock
        end
      end
```

Unfortunately fixing the syntax here doesn't seem to suffice. Even on drained queues the `.empty?` method never returns true leading to a never-ending loop of:

```sh

[2017-06-16T16:47:43,397][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:47:48,395][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:47:53,390][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:47:58,397][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:48:03,391][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:48:08,399][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:48:13,394][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:48:18,391][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:48:23,396][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:195:in `lock'"}]}}
[2017-06-16T16:48:28,389][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:48:33,393][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:48:38,395][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent", "id"=>"1db6e3e8163d4cf302e5b5ee12f6fc3dcfe783ba-5"}]=>[{"thread_id"=>33, "name"=>"[main]>worker1", "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:210:in `lock'"}]}}
[2017-06-16T16:48:43,393][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{["LogStash::Filters::UserAgent", {"source"=>"agent", "target"=>"useragent"
```

**Comment by colinsurprenant** [comment]
- #7524 will address the missing reference
- created #7568 and #7570 as followup.

**Comment by colinsurprenant** [comment]
#7575 fixes this, closing.
