### ISSUE TITLE
Strings containing quotes - LS 6.0.0alpha3

### ISSUE THREAD

**Issue by recrudesce** [elastic/logstash#7550]
Hey, so I'm running LS 6.0.0alpha3, which apparently supports the config.support_escapes option.

I've set that option, however I am still unable to import ANY data that contains double or single quotes.

My data is as follows:

```
email@email.com	07139718b2240dc483d80929c22bcddb	database		11111"	Unsalted MD5		username
```

I've also tried using `"11111\""`, `'11111\"'`, `'11111"'` etc, yet I always get an error

```
08:53:26.088 [[main]>worker0] WARN  logstash.filters.csv - Error parsing csv {:field=>"message", :source=>"email@email.com\t07139718b2240dc483d80929c22bcddb\tdatabase\t\t11111\\\"\tUnsalted MD5\t\tusername\r", :exception=>#<CSV::MalformedCSVError: Illegal quoting in line 1.>}
```

What am I doing wrong ?

**Comment by recrudesce** [comment]
The above was with a CSV filter.  If I use a grok filter it ingests, but stores it under a `_grokparsefailure` (presumably because it can't parse the " or \" value.

```
  grok {
      match => { "message" => "%{WORD:email_address}	%{WORD:hash}	%{WORD:database}	%{WORD:other_data}	%{WORD:plaintext_password}	%{WORD:hash_type}	%{WORD:ip_address}	%{WORD:username}"}
  }
```

**Comment by scherma** [comment]
The definition for %{WORD} is \b\w+\b, therefore it will not work for the password you have defined. You can make it work by using (?<plaintext_password>[^\t]+) I think - this should be ok provided it's not possible to have a tab character in a password. You can see the definitions for built in patterns here: https://github.com/elastic/logstash/blob/v1.4.2/patterns/grok-patterns

**Comment by recrudesce** [comment]
That didn't work either :(  Still a grokparsefailure.  It doesn't work in http://grokconstructor.appspot.com/ either, it matches perfectly up until the 11111" text.

**Comment by scherma** [comment]
%{WORD} will also not match an email because of the "@" and "." , or "Unsalted md5" because of the space. Depending on the possibilities for these fields, it may be easier to define their matches by the characters they cannot contain, rather than by the ones that they can.

**Comment by scherma** [comment]
Part of the problem is that some of the matches are being broken by the presence of a space character on the end of the string, for example you have "database " and "Unsalted MD5 ". Without the spaces, I find that the following grok pattern works:

(?<email_address>[^\s]+)\t%{WORD:hash}\t(?<database>[^\t]+)\t(?<plaintext_password>[^\t]+)\t(?<hash_type>[^\t]+)\t%{WORD:username}

If you need it to match the spaces as well then I would have to play with it a bit more.

**Comment by recrudesce** [comment]
It was not happy with that !
```
[2017-06-28T10:01:47,656][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :thread=>"#<Thread:0xd427428@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:258 run>", :exception=>#<RegexpError: undefined group option: /(?<email_address>[^\s]+)\t(?<WORD:hash>\b\w+\b)\t(?[^\t]+)\t(?<plaintext_password>[^\t]+)\t(?<hash_type>[^\t]+)\t(?<WORD:username>\b\w+\b)/m>, :backtrace=>["org/jruby/RubyRegexp.java:928:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/jls-grok-0.11.4/lib/grok-pure.rb:127:in `compile'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-3.4.1/lib/logstash/filters/grok.rb:286:in `block in register'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-3.4.1/lib/logstash/filters/grok.rb:280:in `block in register'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-grok-3.4.1/lib/logstash/filters/grok.rb:275:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:356:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:367:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:367:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:377:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:261:in `block in start'"]}
```

Thanks for helping me out, I really appreciate it :)

**Comment by scherma** [comment]
You might get more information on where it's breaking by testing the config file: /opt/logstash/bin/logstash --configtest -f /etc/logstash/conf.d/

**Comment by recrudesce** [comment]
Found it, didn't define for the database regexp part.  Still results in a grokparsefailure though :(

**Comment by scherma** [comment]
My general method for debugging grokparsefailures: Remove all but the first match group from your pattern; test. If that works, add the next group, test again. Repeat until you find the group that breaks parsing. Then figure out what's wrong with that group :)

**Comment by recrudesce** [comment]
OK, fixed it.  Now gotta make it carry on if a specific entry is empty (like if we don't have a plain text password).

Thanks scherma, you've been an immense help :)

**Comment by scherma** [comment]
put a ? after the group to make it optional. e.g. \t(?<plaintext_password>[^\t]+)?\t would match if there was no content between the two tabs.

**Comment by recrudesce** [comment]
Perfect, exactly what I needed.

Any way I can "rep" you here so that people know you're a actual Regexp god ?

**Comment by scherma** [comment]
Appreciated, but I'm no regex god. Show me someone who can beat https://regex.alf.nu and I'll show you a real regex god :)

**Comment by jordansissel** [comment]
Glad y'all got this sorted out so quickly! :)

I am wondering about how we (Logstash) are documenting the new string escapes feature. THe intent is that it enables string escapes in the pipeline configuration file (where inputs/filters/outputs are defined), and doesn't control anything else.

This is good feedback for me that our documentation confused you about the new functionality. I'll do some thinking about how we can improve the docs.

**Comment by recrudesce** [comment]
That's explain why it didn't work for me then :P  I was under the impression it'd allow me to ingest CSV files with escaped characters in the content !
