### ISSUE TITLE
Test Failure:  LogStash::Inputs::Base#fix_streaming_codecs should carry the charset setting along when switching

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#7574]
The following test failed on master at https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-intake/790/console:

```
Failures:

  1) LogStash::Inputs::Base#fix_streaming_codecs should carry the charset setting along when switching
     Failure/Error: # encoding: utf-8

     Errno::ENOENT:
       No such file or directory - /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/2.3.0/gems/logstash-input-tcp-4.2.0-java/lib/../version
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/2.3.0/gems/logstash-input-tcp-4.2.0-java/lib/logstash-input-tcp_jars.rb:4:in `<main>'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/2.3.0/gems/logstash-input-tcp-4.2.0-java/lib/logstash/inputs/tcp.rb:1:in `<main>'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/2.3.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/2.3.0/gems/logstash-input-tcp-4.2.0-java/lib/logstash/inputs/tcp.rb:7:in `block in (root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/logstash-core/spec/logstash/inputs/base_spec.rb:1:in `block in (root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/logstash-core/spec/logstash/inputs/base_spec.rb:110:in `(root)'
     # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-intake/lib/bootstrap/rspec.rb:13:in `<main>'

Finished in 5 minutes 27 seconds (files took 6.51 seconds to load)
2295 examples, 1 failure, 6 pending
```

A new version of the logstash-input-tcp plugin was pushed around that time, and this error was not reproduced locally, so it may be temporary

**Comment by robbavey** [comment]
This looks like an issue with 

https://github.com/logstash-plugins/logstash-input-tcp/blob/master/lib/logstash-input-tcp_jars.rb#L4

being unable to resolve the version file in the latest version of https://github.com/logstash-plugins/logstash-input-tcp

**Comment by jakelandis** [comment]
I think this error may be because the [gemspec](https://github.com/logstash-plugins/logstash-input-tcp/blob/master/logstash-input-tcp.gemspec#L14) specifies ```VERSION```, but the file is actually called ```version```

The ```version``` file clearly exists in the [github repo](https://github.com/logstash-plugins/logstash-input-tcp/blob/master/version), but when downloaded from the rubygems, it is missing.

**Comment by jakelandis** [comment]
Assigning to @original-brownbear  as this will likely require a yank + re-release of the gem.

**Comment by jakelandis** [comment]
This has been fixed, and master is green again.
