### ISSUE TITLE
Ingest Conversion Tool Tests Fail on Windows

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7642]
The ingest converter tools tests are failing on Windows as can be seen here https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-windows-compatibility/18/consoleFull.

```sh
org.logstash.ingest.LowercaseTest > convertsAppendProcessorCorrectly[1] FAILED

    java.lang.reflect.InvocationTargetException

        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

        at java.lang.reflect.Method.invoke(Method.java:498)

        at org.logstash.ingest.IngestTest.assertCorrectConversion(IngestTest.java:30)

        at org.logstash.ingest.LowercaseTest.convertsAppendProcessorCorrectly(LowercaseTest.java:17)



        Caused by:

        joptsimple.OptionArgumentConversionException: Cannot parse argument 'file://C:\Users\jenkins\AppData\Local\Temp\junit6902148868081172536\junit743297878821291798\converted' of option output

            at joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:92)

            at joptsimple.ArgumentAcceptingOptionSpec.convert(ArgumentAcceptingOptionSpec.java:277)

            at joptsimple.OptionSet.valuesOf(OptionSet.java:223)

            at joptsimple.OptionSet.valueOf(OptionSet.java:172)

            at org.logstash.ingest.JsUtil.convert(JsUtil.java:83)

            at org.logstash.ingest.Lowercase.main(Lowercase.java:15)

            ... 6 more



            Caused by:

            joptsimple.internal.ReflectionException: java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\Users\jenkins\AppData\Local\Temp\junit6902148868081172536\junit743297878821291798\converted

                at joptsimple.internal.Reflection.reflectionException(Reflection.java:136)

                at joptsimple.internal.Reflection.instantiate(Reflection.java:102)

                at joptsimple.internal.ConstructorInvokingValueConverter.convert(ConstructorInvokingValueConverter.java:46)

                at joptsimple.internal.Reflection.convertWith(Reflection.java:124)

                at joptsimple.AbstractOptionSpec.convertWith(AbstractOptionSpec.java:90)

                ... 11 more



                Caused by:

                java.net.URISyntaxException: Illegal character in authority at index 7: file://C:\Users\jenkins\AppData\Local\Temp\junit6902148868081172536\junit743297878821291798\converted

                    at java.net.URI$Parser.fail(URI.java:2848)

                    at java.net.URI$Parser.parseAuthority(URI.java:3186)

                    at java.net.URI$Parser.parseHierarchical(URI.java:3097)

                    at java.net.URI$Parser.parse(URI.java:3053)

                    at java.net.URI.<init>(URI.java:588)

                    at sun.reflect.GeneratedConstructorAccessor13.newInstance(Unknown Source)

                    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

                    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

                    at joptsimple.internal.Reflection.instantiate(Reflection.java:100)

                    ... 14 more


```

Looking into it.

**Comment by jakelandis** [comment]
I believe this is a duplicate of https://github.com/elastic/logstash/issues/7634

@jsvd was going to take a look.  

In the mean time a PR was merged to master to skip these windows tests (https://github.com/elastic/logstash/pull/7637).  You should be able to rebase and pass your tests.

**Comment by original-brownbear** [comment]
@jakelandis no worries @jsvd pointed me here, fix incoming, ETA 10 min :)

**Comment by original-brownbear** [comment]
closing here, ingest conversion tool tests pass.
