### ISSUE TITLE
v5.5.0 fails with elasticsearch output

### ISSUE THREAD

**Issue by posener** [elastic/logstash#7656]
- Version: 5.5.0 running from a official container
- Operating System: linux
- Config File (if you have sensitive info, please remove it):
Just a simple udp input, elasticsearch output:
```
input {
  udp {
    port => 2233
    type => inline_attributes
  }
}

output {
  elasticsearch {
    hosts => "elasticsearch:9200"
    user => "root"
    password => ""
  }
}
```
- Sample Data:
Nothing fancy here...
- Steps to Reproduce:
Fails on startup:
```
#<NoMethodError: undefined method `tr' for nil:NilClass>

/usr/share/logstash/vendor/jruby/lib/ruby/1.9/cgi/util.rb:16:in `unescape'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client/manticore_adapter.rb:58:in `perform_request'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:269:in `perform_request_to_url'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:237:in `healthcheck!'
org/jruby/RubyHash.java:1342:in `each'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:233:in `healthcheck!'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:319:in `update_urls'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:70:in `start'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client.rb:284:in `build_pool'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client.rb:60:in `initialize'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:101:in `create_http_client'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:97:in `build'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch.rb:230:in `build_client'
/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-7.3.6-java/lib/logstash/outputs/elasticsearch/common.rb:28:in `register'
/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'
/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:41:in `register'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:281:in `register_plugin'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:292:in `register_plugins'
org/jruby/RubyArray.java:1613:in `each'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:292:in `register_plugins'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:301:in `start_workers'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:226:in `run'
/usr/share/logstash/logstash-core/lib/logstash/agent.rb:398:in `start_pipeline'"
```

**Comment by original-brownbear** [comment]
Tracked here https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/614
