### ISSUE TITLE
5.x Test failure

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7683]
https://logstash-ci.elastic.co/job/elastic+logstash+5.x+dockerubuntu-periodic/

Appears to be related to : https://github.com/elastic/logstash/commit/c542e74324bd475b8efb07ef1f4153f59b215855

```

org.logstash.ingest.PipelineTest > convertsComplexCaseCorrectly[11] FAILED
    java.lang.AssertionError: 
    Expected: is "filter {\n   grok {\n      match => {\n         \"message\" => [\n            \"%{SYSLOGTIMESTAMP:[system][syslog][timestamp]} %{SYSLOGHOST:[system][syslog][hostname]} %{DATA:[system][syslog][program]}(?:\[%{POSINT:[system][syslog][pid]}\])?: %{GREEDYMULTILINE:[system][syslog][message]}\",\n            \"%{SYSLOGTIMESTAMP:[system][syslog][timestamp]} %{GREEDYMULTILINE:[system][syslog][message]}\"\n         ]\n      }\n      pattern_definitions => {\n         \"GREEDYMULTILINE\" => \"(.|\n)*\"\n         \"AUDIT_TYPE\" => \"^type=%{NOTSPACE:[auditd][log][record_type]}\"\n      }\n   }\n}\noutput {\n   elasticsearch {\n      hosts => \"localhost\"\n   }\n}\n"
         but: was "filter {\n   grok {\n      match => {\n         \"message\" => [\n            \"%{SYSLOGTIMESTAMP:[system][syslog][timestamp]} %{SYSLOGHOST:[system][syslog][hostname]} %{DATA:[system][syslog][program]}(?:\[%{POSINT:[system][syslog][pid]}\])?: %{GREEDYMULTILINE:[system][syslog][message]}\",\n            \"%{SYSLOGTIMESTAMP:[system][syslog][timestamp]} %{GREEDYMULTILINE:[system][syslog][message]}\"\n         ]\n      }\n      pattern_definitions => {\n         \"GREEDYMULTILINE\" => \"(.|\n)*\"\n         \"AUDIT_TYPE\" => \"^type=%{NOTSPACE:[auditd][log][record_type]}\"\n      }\n   }\n}\n"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.logstash.ingest.IngestTest.assertCorrectConversion(IngestTest.java:51)
        at org.logstash.ingest.PipelineTest.convertsComplexCaseCorrectly(PipelineTest.java:33)

org.logstash.ingest.GrokTest > convertsGrokFieldCorrectly[2] FAILED
    java.lang.AssertionError: 
    Expected: is "filter {\n   grok {\n      match => {\n         \"message\" => [\n            \"%{SYSLOGTIMESTAMP:[system][syslog][timestamp]} %{SYSLOGHOST:[system][syslog][hostname]} %{DATA:[system][syslog][program]}(?:\[%{POSINT:[system][syslog][pid]}\])?: %{GREEDYMULTILINE:[system][syslog][message]}\",\n            \"%{SYSLOGTIMESTAMP:[system][syslog][timestamp]} %{GREEDYMULTILINE:[system][syslog][message]}\"\n         ]\n      }\n      pattern_definitions => {\n         \"GREEDYMULTILINE\" => \"(.|\n)*\"\n         \"AUDIT_TYPE\" => \"^type=%{NOTSPACE:[auditd][log][record_type]}\"\n      }\n   }\n}\noutput {\n   elasticsearch {\n      hosts => \"localhost\"\n   }\n}\n"
         but: was "filter {\n   grok {\n      match => {\n         \"message\" => [\n            \"%{SYSLOGTIMESTAMP:[system][syslog][timestamp]} %{SYSLOGHOST:[system][syslog][hostname]} %{DATA:[system][syslog][program]}(?:\[%{POSINT:[system][syslog][pid]}\])?: %{GREEDYMULTILINE:[system][syslog][message]}\",\n            \"%{SYSLOGTIMESTAMP:[system][syslog][timestamp]} %{GREEDYMULTILINE:[system][syslog][message]}\"\n         ]\n      }\n      pattern_definitions => {\n         \"GREEDYMULTILINE\" => \"(.|\n)*\"\n         \"AUDIT_TYPE\" => \"^type=%{NOTSPACE:[auditd][log][record_type]}\"\n      }\n   }\n}\n"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at org.logstash.ingest.IngestTest.assertCorrectConversion(IngestTest.java:51)
        at org.logstash.ingest.GrokTest.convertsGrokFieldCorrectly(GrokTest.java:17)
Gradle Test Executor 1 finished executing tests.

56 tests completed, 2 failed
Finished generating test XML results (0.015 secs) into: /tmp/logstash/tools/ingest-converter/build/test-results/test
Generating HTML test report...
Finished generating test html results (0.03 secs) into: /tmp/logstash/tools/ingest-converter/build/reports/tests/test
:ingest-converter:test FAILED

:ingest-converter:test (Thread[Daemon worker Thread 2,5,main]) completed. Took 5.858 secs.
9 actionable tasks: 9 executed
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ingest-converter:test'.
> There were failing tests. See the report at: file:///tmp/logstash/tools/ingest-converter/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED in 7s
```

**Comment by original-brownbear** [comment]
Fixed via #7684
