### ISSUE TITLE
Reloading a pipeline can hang indefinitely if reloaded configuration has a syntax error.

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#7718]
When running with the ```-r``` flag, and a pipeline is reloaded with a syntax error, the instance of Logstash may never recover. 

To reproduce start Logstash with a valid configuration and the ```-r``` option, then break the config by removing a required bracket. The pipeline will attempt to reload and fail (expected). Fix the configuration, the pipeline will not reload the valid configuration (not expected).

Reloading errors of the grammar seems works fine, just syntax error seem to have issues recovering properly.

**Comment by ajoliveira** [comment]
@jakelandis Found a variation of this, using the ES output with localhost:9200, changing this to localhost:9500 will trigger the reload and error messages will be logged that connection fails since port 9500 is not available.  If you correct the port back to 9200, the configuration is reloaded but it will continue to try to connect to port 9500 and keep logging same error.

Additionally, this subsequent failure appears to bring down monitoring all together if you are using x-pack monitoring.

**Comment by inqueue** [comment]
I have received another report of this issue and it reproduces in 6.5.4 and 6.6.0. A thread dump taken after committing a "bad" configuration reveals a reload thread that never goes away:
```
"Converge PipelineAction::Reload<test_main>" #61 daemon prio=5 os_prio=31 tid=0x00007f9c29b7d000 nid=0x720b in Object.wait() [0x0000700006cee000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Thread.join(Thread.java:1260)
        - locked <0x000000078b325b20> (a java.lang.Thread)
        at org.jruby.internal.runtime.NativeThread.join(NativeThread.java:76)
        at org.jruby.RubyThread.join(RubyThread.java:1053)
        at org.jruby.RubyThread$INVOKER$i$0$1$join.call(RubyThread$INVOKER$i$0$1$join.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:717)
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:192)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:737)
        at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:77)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
        at org.jruby.RubySymbol$SymbolProcBody.yieldInner(RubySymbol.java:1041)
        at org.jruby.RubySymbol$SymbolProcBody.doYield(RubySymbol.java:1057)
        at org.jruby.runtime.BlockBody.yield(BlockBody.java:116)
        at org.jruby.runtime.Block.yield(Block.java:165)
        at org.jruby.RubyArray.collect(RubyArray.java:2472)
        at org.jruby.RubyArray.map19(RubyArray.java:2486)
        at java.lang.invoke.LambdaForm$DMH/1083292099.invokeVirtual_L3_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH/909914828.reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$reinvoker/49127538.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/1067588937.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$reinvoker/49127538.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/1067588937.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/581770158.linkToCallSite(LambdaForm$MH)
        at Users.jbryan.stack.$6_dot_5.logstash_minus_6_dot_5_dot_4.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$wait_for_workers$0(/Users/jbryan/stack/6.5/logstash-6.5.4/logstash-core/lib/logstash/java_pipeline.rb:321)
        at Users.jbryan.stack.$6_dot_5.logstash_minus_6_dot_5_dot_4.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$wait_for_workers$0$__VARARGS__(/Users/jbryan/stack/6.5/logstash-6.5.4/logstash-core/lib/logstash/java_pipeline.rb)
        at java.lang.invoke.LambdaForm$DMH/1797712197.invokeStatic_L7_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/2951941.invokeExact_MT(LambdaForm$MH)
        at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
        at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
        at java.lang.invoke.LambdaForm$DMH/486715174.invokeVirtual_L6_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH/2027549979.reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$reinvoker/947437179.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/132065521.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$reinvoker/947437179.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/132065521.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$reinvoker/947437179.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/132065521.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/602748972.linkToCallSite(LambdaForm$MH)
        at Users.jbryan.stack.$6_dot_5.logstash_minus_6_dot_5_dot_4.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$shutdown$0(/Users/jbryan/stack/6.5/logstash-6.5.4/logstash-core/lib/logstash/java_pipeline.rb:314)
        at Users.jbryan.stack.$6_dot_5.logstash_minus_6_dot_5_dot_4.logstash_minus_core.lib.logstash.java_pipeline.RUBY$method$shutdown$0$__VARARGS__(/Users/jbryan/stack/6.5/logstash-6.5.4/logstash-core/lib/logstash/java_pipeline.rb)
        at java.lang.invoke.LambdaForm$DMH/1797712197.invokeStatic_L7_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/2951941.invokeExact_MT(LambdaForm$MH)
        at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
        at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
        at java.lang.invoke.LambdaForm$DMH/486715174.invokeVirtual_L6_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH/1487814699.reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$reinvoker/49127538.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/1067588937.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$reinvoker/49127538.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/1067588937.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$reinvoker/49127538.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/1067588937.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/581770158.linkToCallSite(LambdaForm$MH)
        at Users.jbryan.stack.$6_dot_5.logstash_minus_6_dot_5_dot_4.logstash_minus_core.lib.logstash.pipeline_action.stop.RUBY$block$execute$1(/Users/jbryan/stack/6.5/logstash-6.5.4/logstash-core/lib/logstash/pipeline_action/stop.rb:14)
        at java.lang.invoke.LambdaForm$DMH/831236296.invokeStatic_L8_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/1083777179.invokeExact_MT(LambdaForm$MH)
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:289)
        at org.jruby.RubyProc.call(RubyProc.java:246)
        at org.jruby.javasupport.Java$ProcToInterface.callProc(Java.java:1112)
        at org.jruby.javasupport.Java$ProcToInterface.access$300(Java.java:1089)
        at org.jruby.javasupport.Java$ProcToInterface$ConcreteMethod.call(Java.java:1150)
        at org.jruby.gen.InterfaceImpl487450876.apply(org/jruby/gen/InterfaceImpl487450876.gen:13)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
        - locked <0x000000078aef7c30> (a java.util.concurrent.ConcurrentHashMap$Node)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:468)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:326)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:115)
        at java.lang.invoke.LambdaForm$DMH/698562080.invokeVirtual_L7_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH/1781668126.reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$reinvoker/655180711.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/19400322.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$reinvoker/655180711.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/19400322.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/871461513.linkToCallSite(LambdaForm$MH)
        at Users.jbryan.stack.$6_dot_5.logstash_minus_6_dot_5_dot_4.logstash_minus_core.lib.logstash.pipeline_action.stop.RUBY$method$execute$0(/Users/jbryan/stack/6.5/logstash-6.5.4/logstash-core/lib/logstash/pipeline_action/stop.rb:13)
        at java.lang.invoke.LambdaForm$DMH/831236296.invokeStatic_L8_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH/670959005.reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$reinvoker/655180711.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/19400322.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$reinvoker/655180711.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/19400322.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/871461513.linkToCallSite(LambdaForm$MH)
        at Users.jbryan.stack.$6_dot_5.logstash_minus_6_dot_5_dot_4.logstash_minus_core.lib.logstash.pipeline_action.reload.RUBY$block$execute$2(/Users/jbryan/stack/6.5/logstash-6.5.4/logstash-core/lib/logstash/pipeline_action/reload.rb:53)
        at java.lang.invoke.LambdaForm$DMH/831236296.invokeStatic_L8_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/1083777179.invokeExact_MT(LambdaForm$MH)
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:289)
        at org.jruby.RubyProc.call(RubyProc.java:246)
        at org.jruby.javasupport.Java$ProcToInterface.callProc(Java.java:1112)
        at org.jruby.javasupport.Java$ProcToInterface.access$300(Java.java:1089)
        at org.jruby.javasupport.Java$ProcToInterface$ConcreteMethod.call(Java.java:1150)
        at org.jruby.gen.InterfaceImpl487450876.apply(org/jruby/gen/InterfaceImpl487450876.gen:13)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
        - locked <0x000000078aef7c30> (a java.util.concurrent.ConcurrentHashMap$Node)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:468)
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:326)
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:115)
        at java.lang.invoke.LambdaForm$DMH/698562080.invokeVirtual_L7_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH/1781668126.reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$reinvoker/655180711.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/19400322.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$reinvoker/655180711.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/19400322.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/871461513.linkToCallSite(LambdaForm$MH)
        at Users.jbryan.stack.$6_dot_5.logstash_minus_6_dot_5_dot_4.logstash_minus_core.lib.logstash.pipeline_action.reload.RUBY$method$execute$0(/Users/jbryan/stack/6.5/logstash-6.5.4/logstash-core/lib/logstash/pipeline_action/reload.rb:52)
        at java.lang.invoke.LambdaForm$DMH/831236296.invokeStatic_L8_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$BMH/670959005.reinvoke(LambdaForm$BMH)
        at java.lang.invoke.LambdaForm$reinvoker/655180711.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/19400322.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$reinvoker/655180711.dontInline(LambdaForm$reinvoker)
        at java.lang.invoke.LambdaForm$MH/19400322.guard(LambdaForm$MH)
        at java.lang.invoke.LambdaForm$MH/871461513.linkToCallSite(LambdaForm$MH)
        at Users.jbryan.stack.$6_dot_5.logstash_minus_6_dot_5_dot_4.logstash_minus_core.lib.logstash.agent.RUBY$block$converge_state$2(/Users/jbryan/stack/6.5/logstash-6.5.4/logstash-core/lib/logstash/agent.rb:317)
        at java.lang.invoke.LambdaForm$DMH/831236296.invokeStatic_L8_L(LambdaForm$DMH)
        at java.lang.invoke.LambdaForm$MH/1083777179.invokeExact_MT(LambdaForm$MH)
        at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71)
        at org.jruby.runtime.Block.call(Block.java:124)
        at org.jruby.RubyProc.call(RubyProc.java:289)
        at org.jruby.RubyProc.call(RubyProc.java:246)
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
        at java.lang.Thread.run(Thread.java:748)
```

The thread never goes away once it is spawned with a bad configuration. 

@jsvd

**Comment by jsvd** [comment]
@inqueue can you provide the configuration you used to trigger this?

**Comment by inqueue** [comment]
The pipeline is managed by centralized pipeline management in Kibana.

Good pipeline:
```
input {
  generator {
    lines => [
      "generator line 1",
      "generator line 2"
    ]
    count => 10
  }
}
filter {
}
output {
  elasticsearch {
    ssl_certificate_verification => false
    hosts => ["https://localhost:9200"]
    user => elastic
    password => ᕕ( ◔3◔)ᕗ
    index => test_main
  }
}
```

Bad pipeline (`hosts` is invalid):
```
input {
  generator {
    lines => [
      "generator line 1",
      "generator line 2"
    ]
    count => 10
  }
}
filter {
}
output {
  elasticsearch {
    ssl_certificate_verification => false
    hosts => ["https://notlocalhost:9200"]
    user => elastic
    password => ( ◕ ʖ̯ ◕ )
    index => test_main
  }
}
```

**logstash.yml**:
```
# X-Pack Management
xpack.management.enabled: true
xpack.management.pipeline.id: ["test_main"]
xpack.management.elasticsearch.username: elastic
xpack.management.elasticsearch.password: ᕕ( ◔3◔)ᕗ
xpack.management.elasticsearch.url: ["https://localhost:9200"]
xpack.management.elasticsearch.ssl.verification_mode: none
```

Log while in "bad" state:
```
[2019-01-31T13:16:17,519][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://elastic:xxxxxx@notlocalhost:9200/]}}
[2019-01-31T13:16:17,554][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://elastic:xxxxxx@notlocalhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://elastic:xxxxxx@notlocalhost:9200/][Manticore::ResolutionFailure] notlocalhost: nodename nor servname provided, or not known"}
[2019-01-31T13:16:17,557][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://notlocalhost:9200"]}
[2019-01-31T13:16:17,561][INFO ][logstash.javapipeline    ] Starting pipeline {:pipeline_id=>"test_main", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>125, :thread=>"#<Thread:0x53831391 run>"}
[2019-01-31T13:16:17,565][INFO ][logstash.javapipeline    ] Pipeline started {"pipeline.id"=>"test_main"}
[2019-01-31T13:16:22,578][WARN ][logstash.outputs.elasticsearch] Attempted to resurrect connection to dead ES instance, but got an error. {:url=>"https://elastic:xxxxxx@notlocalhost:9200/", :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [https://elastic:xxxxxx@notlocalhost:9200/][Manticore::ResolutionFailure] notlocalhost"}
```
