### ISSUE TITLE
LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7737]
error can be seen here https://travis-ci.org/elastic/logstash/jobs/255240896#L7091-L7107

```
  1) LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once
     Failure/Error: expect(subject).to have_running_pipeline?(pipeline_config)
     
     ArgumentError:
       Failure message is nil. Does your matcher define the appropriate failure_message[_when_negated] method to return a string?
     # ./logstash-core/spec/logstash/agent/converge_spec.rb:110:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /home/travis/build/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'
Finished in 7 minutes 10 seconds (files took 15.89 seconds to load)
2447 examples, 1 failure, 3 pending
Failed examples:
rspec ./logstash-core/spec/logstash/agent/converge_spec.rb:106 # LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once
Randomized with seed 44261
```

**Comment by jakelandis** [comment]
Looks like another intermittent failure due the timing, will add in a retry step.
