### ISSUE TITLE
LogStash::Pipeline event cancellation should not propagate cancelled events from filter to output

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7738]
from master, https://travis-ci.org/elastic/logstash/jobs/255315563#L7352-L7370

```
  1) LogStash::Pipeline event cancellation should not propagate cancelled events from filter to output
     Failure/Error: end.to be_truthy
     
       expected: truthy value
            got: false
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `block in handle_matcher'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `block in handle_matcher'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `block in to'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `block in with_wait'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
     # ./logstash-core/spec/logstash/pipeline_spec.rb:184:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /home/travis/build/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'
Finished in 7 minutes 32 seconds (files took 17.05 seconds to load)
2389 examples, 1 failure, 3 pending
```

**Comment by jakelandis** [comment]
This looks the same root cause as https://github.com/elastic/logstash/issues/7724 (not waiting long enough) and the same fix should apply. 

Taking ownership.
