### ISSUE TITLE
Test failure 5.x amazon

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7766]
Failure in 5.x https://logstash-ci.elastic.co/job/elastic+logstash+5.x+multijob-unix-compatibility/os=amazon/lastBuild/consoleFull

```
Caused by: com.headius.invokebinder.InvalidTransformException: java.lang.IllegalAccessException: no such method: rubyjit.LogStash::Filters::Multiline$$filter_b78cba0c9f1bd982b66c40881ba24cdf9951bf64142257191.__file__(LogStash::Filters::Multiline$$filter_b78cba0c9f1bd982b66c40881ba24cdf9951bf64142257191,ThreadContext,IRubyObject,IRubyObject,Block)IRubyObject/invokeStatic
	at com.headius.invokebinder.Binder.invokeStaticQuiet(Binder.java:1079)
	at org.jruby.runtime.invokedynamic.InvocationLinker.createRubyHandle(InvocationLinker.java:1678)
	... 75 more
Caused by: java.lang.IllegalAccessException: no such method: rubyjit.LogStash::Filters::Multiline$$filter_b78cba0c9f1bd982b66c40881ba24cdf9951bf64142257191.__file__(LogStash::Filters::Multiline$$filter_b78cba0c9f1bd982b66c40881ba24cdf9951bf64142257191,ThreadContext,IRubyObject,IRubyObject,Block)IRubyObject/invokeStatic
	at java.lang.invoke.MemberName.makeAccessException(MemberName.java:867)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
	at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780)
	at com.headius.invokebinder.Binder.invokeStatic(Binder.java:1055)
	at com.headius.invokebinder.Binder.invokeStaticQuiet(Binder.java:1077)
	... 76 more
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "rubyjit.LogStash::Filters::Multiline$$filter_b78cba0c9f1bd982b66c40881ba24cdf9951bf64142257191.__file__(Lrubyjit/LogStash::Filters::Multiline$$filter_b78cba0c9f1bd982b66c40881ba24cdf9951bf64142257191;Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/Block;)Lorg/jruby/runtime/builtin/IRubyObject;" the class loader (instance of org/jruby/util/ClassCache$OneShotClassLoader) of the current class, rubyjit/LogStash::Filters::Base$$do_filter_8e8403dcfdf01a35ffca12ed35ec4e7945548907142257191, and the class loader (instance of org/jruby/util/ClassCache$OneShotClassLoader) for the method's defining class, rubyjit/LogStash::Filters::Multiline$$filter_b78cba0c9f1bd982b66c40881ba24cdf9951bf64142257191, have different Class objects for the type rubyjit/LogStash::Filters::Multiline$$filter_b78cba0c9f1bd982b66c40881ba24cdf9951bf64142257191 used in the signature
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	... 80 more
```

**Comment by robbavey** [comment]
Related? #7698

**Comment by jsvd** [comment]
Maybe related to https://github.com/jruby/jruby/issues/1518 and/or https://github.com/jruby/jruby/issues/1658

**Comment by original-brownbear** [comment]
@jsvd @robbavey yea looks like this is a bug in JRuby.

I never saw this issue and it's a huge speedup to have `invokedynamic` on in most cases, maybe we should "fix" this by documenting the problem and having users turn it off if they run into this?
(I kinda like this approach because from reading the JRuby issues it seems this is related to the JVM used and will probably only affect a fraction of users)
WDYT?

**Comment by jsvd** [comment]
With this issue I'm a little skeptic in making InDy the default, maybe we could expose it through the normal packaging property files like jvm.options, then make it default on in 7.0.0?

**Comment by robbavey** [comment]
@original-brownbear - I'd tend to agree with @jsvd in that I'm not sure it should be the default, at least for 5.x - which will go straight into production usage - and has potential to cause support issues. For 6.x and 7.0, I'd have less of a problem with turning it on by default - particularly given this comment https://github.com/jruby/jruby/issues/1658#issuecomment-71588142 around InDy support being rewritten for jRuby 9k.

**Comment by original-brownbear** [comment]
@jsvd @robbavey on second thought, you guys are right :( let's revert this for `5.x`.

**Comment by original-brownbear** [comment]
@jsvd @robbavey I guess this would mean creating branch+release `5.7` though? (gnarf)

**Comment by robbavey** [comment]
@original-brownbear I don't think 5.6.0 has been tagged yet, so you might be able to make the changes in the 5.6 branch...

cc @suyograo, @jsvd

**Comment by jsvd** [comment]
I'm +1 on disabling InDy by default in 5.6 asap.

**Comment by original-brownbear** [comment]
putting in a PR sec

**Comment by original-brownbear** [comment]
done => #7805

**Comment by suyograo** [comment]
+1 to leave it on for 6.x, but not 5.x. I just approved #7805 for 5.6.

**Comment by original-brownbear** [comment]
merged :)
