### ISSUE TITLE
Hot Threads API is Broken in Master

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7797]
All tests related to it fail:

```sh
Finished in 5 minutes 12 seconds (files took 11.98 seconds to load)
2687 examples, 102 failures, 3 pending

Failed examples:

rspec './logstash-core/spec/logstash/legacy_ruby_event_spec.rb[1:2:1:5:1]' # LogStash::Event using hash input from deserialized json behaves like all event tests #overwrite should swap data with new content
rspec './logstash-core/spec/logstash/legacy_ruby_event_spec.rb[1:2:1:11:3:1]' # LogStash::Event using hash input from deserialized json behaves like all event tests metadata with no metadata should have no metadata
rspec './logstash-core/spec/logstash/legacy_ruby_event_spec.rb[1:2:1:1:1]' # LogStash::Event using hash input from deserialized json behaves like all event tests []= should raise an exception if you attempt to set @timestamp to a value type other than a Time object
rspec './logstash-core/spec/logstash/legacy_ruby_event_spec.rb[1:1:1:1:1]' # LogStash::Event using normal hash input behaves like all event tests []= should raise an exception if you attempt to set @timestamp to a value type other than a Time object
rspec './logstash-core/spec/logstash/legacy_ruby_event_spec.rb[1:1:1:11:3:1]' # LogStash::Event using normal hash input behaves like all event tests metadata with no metadata should have no metadata
rspec './logstash-core/spec/logstash/legacy_ruby_event_spec.rb[1:1:1:5:1]' # LogStash::Event using normal hash input behaves like all event tests #overwrite should swap data with new content
rspec ./logstash-core/spec/logstash/api/modules/node_spec.rb:17 # LogStash::Api::Modules::Node#hot threads respond OK
rspec ./logstash-core/spec/logstash/api/modules/node_spec.rb:21 # LogStash::Api::Modules::Node#hot threads should return a JSON object
rspec ./logstash-core/spec/logstash/api/modules/node_spec.rb:31 # LogStash::Api::Modules::Node#hot threads #threads count should return a json payload content type
rspec ./logstash-core/spec/logstash/api/modules/node_spec.rb:35 # LogStash::Api::Modules::Node#hot threads #threads count should return information for <= # requested threads
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:4:1]' # LogStash::Api::Modules::Node#hot threads when asking for human output should return a text/plain content type
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:4:2]' # LogStash::Api::Modules::Node#hot threads when asking for human output should return a plain text payload
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:4:3]' # LogStash::Api::Modules::Node#hot threads when asking for human output should return a text/plain content type
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:4:4]' # LogStash::Api::Modules::Node#hot threads when asking for human output should return a plain text payload
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:4:5]' # LogStash::Api::Modules::Node#hot threads when asking for human output should return a text/plain content type
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:4:6]' # LogStash::Api::Modules::Node#hot threads when asking for human output should return a plain text payload
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:4:7]' # LogStash::Api::Modules::Node#hot threads when asking for human output should return a text/plain content type
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:4:8]' # LogStash::Api::Modules::Node#hot threads when asking for human output should return a plain text payload
rspec ./logstash-core/spec/logstash/api/modules/node_spec.rb:84 # LogStash::Api::Modules::Node#hot threads When asking for human output and threads count should return information for <= # requested threads
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:6:1]' # LogStash::Api::Modules::Node#hot threads when not asking for human output should return a json payload content type
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:6:2]' # LogStash::Api::Modules::Node#hot threads when not asking for human output should return a json payload
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:6:3]' # LogStash::Api::Modules::Node#hot threads when not asking for human output should return a json payload content type
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:6:4]' # LogStash::Api::Modules::Node#hot threads when not asking for human output should return a json payload
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:6:5]' # LogStash::Api::Modules::Node#hot threads when not asking for human output should return a json payload content type
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:6:6]' # LogStash::Api::Modules::Node#hot threads when not asking for human output should return a json payload
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should respond OK
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.workers' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.batch_size' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.batch_delay' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:6]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.config_reload_automatic' at '/' to be a 'Boolean'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:7]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.config_reload_interval' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:8]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'pipelines.main.dead_letter_queue_enabled' at '/' to be a 'Boolean'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:9]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'os.name' at '/' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:10]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'os.arch' at '/' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:11]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'os.version' at '/' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:12]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'os.available_processors' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:13]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.pid' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:14]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.version' at '/' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:15]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.vm_name' at '/' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:16]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.vm_version' at '/' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:17]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.vm_vendor' at '/' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:18]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.start_time_in_millis' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:19]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.mem.heap_init_in_bytes' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:20]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.mem.heap_max_in_bytes' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:21]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.mem.non_heap_init_in_bytes' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:22]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.mem.non_heap_max_in_bytes' at '/' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:23]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / should set 'jvm.gc_collectors' at '/' to be a 'Array'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:2:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / the default metadata should include the host
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:2:2]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / the default metadata should include the version
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:2:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / the default metadata should include the http address
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:2:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / the default metadata should include the node name
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:1:2:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / the default metadata should include the node id
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should respond OK
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.workers' at '/pipelines' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.batch_size' at '/pipelines' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.batch_delay' at '/pipelines' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:6]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.config_reload_automatic' at '/pipelines' to be a 'Boolean'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:7]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.config_reload_interval' at '/pipelines' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:8]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines should set 'pipelines.main.dead_letter_queue_enabled' at '/pipelines' to be a 'Boolean'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:2:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines the default metadata should include the host
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:2:2]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines the default metadata should include the version
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:2:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines the default metadata should include the http address
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:2:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines the default metadata should include the node name
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:2:2:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /pipelines the default metadata should include the node id
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os should respond OK
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os should set 'os.name' at '/os' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os should set 'os.arch' at '/os' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os should set 'os.version' at '/os' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:6]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os should set 'os.available_processors' at '/os' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:2:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os the default metadata should include the host
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:2:2]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os the default metadata should include the version
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:2:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os the default metadata should include the http address
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:2:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os the default metadata should include the node name
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:3:2:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /os the default metadata should include the node id
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should respond OK
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.pid' at '/jvm' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.version' at '/jvm' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.vm_name' at '/jvm' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:6]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.vm_version' at '/jvm' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:7]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.vm_vendor' at '/jvm' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:8]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.start_time_in_millis' at '/jvm' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:9]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.mem.heap_init_in_bytes' at '/jvm' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:10]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.mem.heap_max_in_bytes' at '/jvm' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:11]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.mem.non_heap_init_in_bytes' at '/jvm' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:12]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.mem.non_heap_max_in_bytes' at '/jvm' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:13]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm should set 'jvm.gc_collectors' at '/jvm' to be a 'Array'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:2:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm the default metadata should include the host
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:2:2]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm the default metadata should include the version
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:2:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm the default metadata should include the http address
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:2:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm the default metadata should include the node name
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:4:2:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /jvm the default metadata should include the node id
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:5:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /hot_threads should respond OK
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:5:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /hot_threads should set 'hot_threads.time' at '/hot_threads' to be a 'String'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:5:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /hot_threads should set 'hot_threads.busiest_threads' at '/hot_threads' to be a 'Numeric'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:5:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /hot_threads should set 'hot_threads.threads' at '/hot_threads' to be a 'Array'
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:5:2:1]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /hot_threads the default metadata should include the host
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:5:2:2]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /hot_threads the default metadata should include the version
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:5:2:3]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /hot_threads the default metadata should include the http address
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:5:2:4]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /hot_threads the default metadata should include the node name
rspec './logstash-core/spec/logstash/api/modules/node_spec.rb[1:2:7:5:2:5]' # LogStash::Api::Modules::Node#hot threads Generic JSON testing GET /hot_threads the default metadata should include the node id
rspec ./logstash-core/spec/logstash/api/commands/stats_spec.rb:27 # LogStash::Api::Commands::Stats#hot_threads should return hot threads information as a string
rspec ./logstash-core/spec/logstash/api/commands/stats_spec.rb:31 # LogStash::Api::Commands::Stats#hot_threads should return hot threads info as a hash

Randomized with seed 7040

```

Also visiting the hot threads API url gives me this:

```
{"status":500,"request_method":"GET","path_info":"/_node/hot_threads","query_string":"","http_version":"HTTP/1.1","http_accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","error":"Unexpected Internal Error","class":"TypeError","message":"no implicit conversion of String into Integer","backtrace":["org/jruby/RubyArray.java:1458:in `[]'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/util/thread_dump.rb:23:in `block in each'","org/jruby/RubyHash.java:1343:in `each'","org/jruby/java/proxies/MapJavaProxy.java:576:in `each'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/util/thread_dump.rb:22:in `each'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/commands/hot_threads_reporter.rb:39:in `to_hash'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/app_helpers.rb:24:in `respond_with'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node.rb:20:in `block in GET /hot_threads'","org/jruby/RubyMethod.java:111:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'","org/jruby/RubyKernel.java:1120:in `catch'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'","org/jruby/RubyArray.java:1734:in `each'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'","org/jruby/RubyKernel.java:1120:in `catch'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'","org/jruby/RubyKernel.java:1120:in `catch'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/nulllogger.rb:9:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/head.rb:13:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:66:in `block in call'","org/jruby/RubyArray.java:1734:in `each'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:50:in `call'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:57:in `call'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:31:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:153:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:557:in `handle_request'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:404:in `process_client'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:270:in `block in run'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:106:in `block in spawn_thread'"]}
```

**Comment by jordansissel** [comment]
https://github.com/elastic/logstash/pull/7617 maybe?

**Comment by original-brownbear** [comment]
@jordansissel likely, it's the only related change since it was green

**Comment by original-brownbear** [comment]
false alarm here it seems, but our build is screwed up somehow. Had to `git clean -x -f -d -e *.iml -e .idea -e .bundle` to make it work again.
