### ISSUE TITLE
Dead Letter Queue Tests fail on Windows

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#7807]
Running the DeadLetterQueue tests on Windows yields the following failures:

```org.logstash.common.io.DeadLetterQueueReaderTest > testWriteStopSmallWriteSeekByTimestamp FAILED

    java.io.IOException: Access is denied

        at java.io.WinNTFileSystem.createFileExclusively(Native Method)

        at java.io.File.createNewFile(File.java:1012)

        at org.logstash.common.io.DeadLetterQueueWriter.<init>(DeadLetterQueueWriter.java:63)

        at org.logstash.common.io.DeadLetterQueueReaderTest.writeEntries(DeadLetterQueueReaderTest.java:170)

        at org.logstash.common.io.DeadLetterQueueReaderTest.testWriteStopSmallWriteSeekByTimestamp(DeadLetterQueueReaderTest.java:137)



org.logstash.common.io.DeadLetterQueueReaderTest > testWriteStopBigWriteSeekByTimestamp FAILED

    java.io.IOException: Access is denied

        at java.io.WinNTFileSystem.createFileExclusively(Native Method)

        at java.io.File.createNewFile(File.java:1012)

        at org.logstash.common.io.DeadLetterQueueWriter.<init>(DeadLetterQueueWriter.java:63)

        at org.logstash.common.io.DeadLetterQueueReaderTest.writeEntries(DeadLetterQueueReaderTest.java:170)

        at org.logstash.common.io.DeadLetterQueueReaderTest.testWriteStopBigWriteSeekByTimestamp(DeadLetterQueueReaderTest.java:153)
```

**Comment by robbavey** [comment]
fixed by #7822
