### ISSUE TITLE
DLQ: Plugin can crash when events end on block boundaries

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#7860]
When the RecordIOReader tries to read the next event from a segment where the last byte of the event lines up with the block boundary, the plugin can fail with an ArrayIndexOutOfBoundsException, which will cause the DLQ input plugin to fail, and potentially not be able to recover to read the next event.

This may be related to the failures seen in #7820 

Test Case: 

```
    @Test
    public void testBlockBoundary() throws Exception {
        Event event = new Event(Collections.emptyMap());
        char[] field = new char[32610];
        Arrays.fill(field, 'x');
        event.setField("message", new String(field));
        long startTime = System.currentTimeMillis();
        try(DeadLetterQueueWriter writeManager = new DeadLetterQueueWriter(dir, 10 * 1024 * 1024, 1_000_000_000)) {
            for (int i = 0; i < 2; i++) {
                DLQEntry entry = new DLQEntry(event, "", "", "", new Timestamp(startTime++));
                assertThat(entry.serialize().length + RecordIOWriter.RECORD_HEADER_SIZE, is(RecordIOWriter.BLOCK_SIZE));
                writeManager.writeEntry(entry);
            }
        }
        try (DeadLetterQueueReader readManager = new DeadLetterQueueReader(dir)) {
            for (int i = 0; i < 2;i++) {
                readManager.pollEntry(100);
            }
        }
    }
```

Fails with:

```
java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: 32768

	at org.logstash.common.io.RecordIOReader.seekToStartOfEventInBlock(RecordIOReader.java:176)
	at org.logstash.common.io.RecordIOReader.consumeToStartOfEvent(RecordIOReader.java:227)
	at org.logstash.common.io.RecordIOReader.readEvent(RecordIOReader.java:261)
	at org.logstash.common.io.DeadLetterQueueReader.pollEntryBytes(DeadLetterQueueReader.java:120)
	at org.logstash.common.io.DeadLetterQueueReader.pollEntry(DeadLetterQueueReader.java:96)
	at org.logstash.common.io.DeadLetterQueueReaderTest.testBlockBoundary(DeadLetterQueueReaderTest.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 32768
	at org.logstash.common.io.RecordIOReader.seekToStartOfEventInBlock(RecordIOReader.java:165)
	... 30 more
```

**Comment by robbavey** [comment]
Should be fixed by #7871
