### ISSUE TITLE
multiple pipeline reloading broken in beta1

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7865]
Reloading when using the MultiLocal source class can throw an exception since the loop that creates pipelines uses the local `@settings` var to store each pipeline settings during the iteration step, but never resets it to the generic instance-level settings, causing this:

```
/tmp/logstash-6.0.0-beta1 % bin/logstash -r
[2017-08-01T14:18:21,900][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-08-01T14:18:23,135][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"another_test", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>500, :thread=>"#<Thread:0x1e2878e8@/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/pipeline.rb:271 run>"}
[2017-08-01T14:18:23,356][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"another_test"}
[2017-08-01T14:18:23,766][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"test", "pipeline.workers"=>1, "pipeline.batch.size"=>1, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>1, :thread=>"#<Thread:0x300ef01f@/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/pipeline.rb:271 run>"}
[2017-08-01T14:18:23,770][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"test"}
[2017-08-01T14:18:23,786][INFO ][logstash.agent           ] Pipelines running {:count=>2, :pipelines=>["another_test", "test"]}
..[2017-08-01T14:18:26,794][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>ArgumentError, :message=>"Setting \"modules.cli\" hasn't been registered", :backtrace=>["/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/settings.rb:32:in `get_setting'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source/base.rb:60:in `modules_cli_setting'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source/base.rb:64:in `modules_cli'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source/base.rb:68:in `modules_cli?'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source/multi_local.rb:34:in `match?'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:49:in `block in fetch'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:90:in `block in sources'", "org/jruby/RubyHash.java:1405:in `each_key'", "/private/tmp/logstash-6.0.0-beta1/vendor/jruby/lib/ruby/stdlib/set.rb:306:in `each'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:89:in `block in sources'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:87:in `sources'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:48:in `fetch'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/agent.rb:148:in `converge_state_and_update'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/agent.rb:105:in `block in execute'", "/tmp/logstash-6.0.0-beta1/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/interval.rb:18:in `interval'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/agent.rb:94:in `execute'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/tmp/logstash-6.0.0-beta1/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
...[2017-08-01T14:18:29,792][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>ArgumentError, :message=>"Setting \"modules.cli\" hasn't been registered", :backtrace=>["/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/settings.rb:32:in `get_setting'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source/base.rb:60:in `modules_cli_setting'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source/base.rb:64:in `modules_cli'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source/base.rb:68:in `modules_cli?'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source/multi_local.rb:34:in `match?'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:49:in `block in fetch'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:90:in `block in sources'", "org/jruby/RubyHash.java:1405:in `each_key'", "/private/tmp/logstash-6.0.0-beta1/vendor/jruby/lib/ruby/stdlib/set.rb:306:in `each'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:89:in `block in sources'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:87:in `sources'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/config/source_loader.rb:48:in `fetch'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/agent.rb:148:in `converge_state_and_update'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/agent.rb:105:in `block in execute'", "/tmp/logstash-6.0.0-beta1/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/interval.rb:18:in `interval'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/agent.rb:94:in `execute'", "/tmp/logstash-6.0.0-beta1/logstash-core/lib/logstash/runner.rb:346:in `block in execute'", "/tmp/logstash-6.0.0-beta1/vendor/bundle/jruby/2.3.0/gems/stud-0.0.22/lib/stud/task.rb:24:in `block in initialize'"]}
```

**Comment by kares** [comment]
was resolved at https://github.com/elastic/logstash/pull/7866
