### ISSUE TITLE
Random Fail: LogStash::Event using normal hash input behaves like all event tests timestamp initialization should tag for invalid value

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#7933]
https://travis-ci.org/elastic/logstash/jobs/262001100#L7169

```rb
  1) LogStash::Event using normal hash input behaves like all event tests timestamp initialization should tag for invalid value
     Failure/Error: expect(event.timestamp.to_i).to be_within(1).of Time.now.to_i
       expected 1502141350 to be within 1 of 1502141352
     Shared Example Group: "all event tests" called from ./logstash-core/spec/logstash/legacy_ruby_event_spec.rb:576
     # ./logstash-core/spec/logstash/legacy_ruby_event_spec.rb:407:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /home/travis/build/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'
```

I guess we could increase the accepted margin of error here a little to fix this :)

**Comment by original-brownbear** [comment]
this was already fixed in f64762fd05926fb07e30d8d4028a5ae21fa6124e
