### ISSUE TITLE
logstash sometimes doesn't upload the mapping template

### ISSUE THREAD

**Issue by xificurC** [elastic/logstash#7936]
while searching for a working connection logstash can fail to upload a template mapping and later decide to start sending data without ensuring the template is uploaded.

```
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:29.929 [[main]-pipeline-manager] INFO  logstash.outputs.elasticsearch - Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://sura-world-elasticsearch:9200/]}}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:29.929 [[main]-pipeline-manager] INFO  logstash.outputs.elasticsearch - Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://sura-world-elasticsearch:9200/, :path=>"/
"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:29.933 [[main]-pipeline-manager] WARN  logstash.outputs.elasticsearch - Attempted to resurrect connection to dead ES instance, but got an error. {:url=>#<URI::HTTP:0x505838c5 URL:http://sura-world-elasticsearc
h:9200/>, :error_type=>LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError, :error=>"Elasticsearch Unreachable: [http://sura-world-elasticsearch:9200/][Manticore::SocketException] Connection refused (Connection refused)"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:29.934 [[main]-pipeline-manager] INFO  logstash.outputs.elasticsearch - Using mapping template from {:path=>"/etc/logstash/index-template.json"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:29.943 [[main]-pipeline-manager] WARN  logstash.outputs.elasticsearch - Marking url as dead. Last error: [LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError] Elasticsearch Unreachable: [h
ttp://sura-world-elasticsearch:9200/][Manticore::SocketException] Connection refused (Connection refused) {:url=>http://sura-world-elasticsearch:9200/, :error_message=>"Elasticsearch Unreachable: [http://sura-world-elasticsearch:9200/][Manticore::SocketException] Connectio
n refused (Connection refused)", :error_class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:29.945 [[main]-pipeline-manager] ERROR logstash.outputs.elasticsearch - Failed to install template. {:message=>"Elasticsearch Unreachable: [http://sura-world-elasticsearch:9200/][Manticore::SocketException] Co
nnection refused (Connection refused)", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::HostUnreachableError", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_clien
t/pool.rb:287:in `perform_request_to_url'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:273:in `perform_request'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logsta
sh-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:363:in `with_connection'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:272:in `pe
rform_request'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:280:in `get'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/
logstash/outputs/elasticsearch/http_client.rb:83:in `get_version'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/template_manager.rb:16:in `get_es_version'", "/usr/share/logstash/vendor/bundle
/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/template_manager.rb:20:in `get_es_major_version'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/temp
late_manager.rb:7:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/common.rb:54:in `install_template'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-el
asticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/common.rb:21:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:9:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:41:in `registe
r'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:268:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:279:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pi
peline.rb:279:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:288:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:214:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:398:in `start_pipe
line'"]}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:29.949 [[main]-pipeline-manager] INFO  logstash.outputs.elasticsearch - New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>[#<URI::Generic:0x36dd45dd URL://sura-world-elasticsearch:9
200>]}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:30.257 [[main]-pipeline-manager] INFO  logstash.pipeline - Starting pipeline {"id"=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>1000}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:30.677 [[main]-pipeline-manager] INFO  logstash.inputs.beats - Beats inputs: Starting input listener {:address=>"0.0.0.0:5043"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:30.711 [[main]-pipeline-manager] INFO  logstash.inputs.tcp - Automatically switching from json to json_lines codec {:plugin=>"tcp"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:30.721 [[main]-pipeline-manager] INFO  logstash.inputs.tcp - Starting tcp input listener {:address=>"0.0.0.0:5044"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:30.730 [[main]-pipeline-manager] INFO  logstash.inputs.tcp - Automatically switching from json to json_lines codec {:plugin=>"tcp"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:30.737 [[main]-pipeline-manager] INFO  logstash.inputs.tcp - Starting tcp input listener {:address=>"0.0.0.0:6969"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:30.748 [[main]-pipeline-manager] INFO  logstash.pipeline - Pipeline main started
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:30.827 [Api Webserver] INFO  logstash.agent - Successfully started Logstash API endpoint {:port=>9600}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:32.464 [[main]>worker6] WARN  logstash.outputs.elasticsearch - UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:32.465 [[main]>worker0] WARN  logstash.outputs.elasticsearch - UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:32.465 [[main]>worker0] ERROR logstash.outputs.elasticsearch - Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreach
able or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>2}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:32.465 [[main]>worker6] ERROR logstash.outputs.elasticsearch - Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreach
able or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>2}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:32.463 [[main]>worker7] WARN  logstash.outputs.elasticsearch - UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:32.466 [[main]>worker7] ERROR logstash.outputs.elasticsearch - Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreach
able or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>2}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:32.468 [[main]>worker1] WARN  logstash.outputs.elasticsearch - UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:32.470 [[main]>worker1] ERROR logstash.outputs.elasticsearch - Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreach
able or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>2}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:33.194 [[main]>worker4] WARN  logstash.outputs.elasticsearch - UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:33.195 [[main]>worker4] ERROR logstash.outputs.elasticsearch - Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreach
able or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>2}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.466 [[main]>worker0] WARN  logstash.outputs.elasticsearch - UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.467 [[main]>worker6] WARN  logstash.outputs.elasticsearch - UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.468 [[main]>worker6] ERROR logstash.outputs.elasticsearch - Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreach
able or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>4}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.468 [[main]>worker7] WARN  logstash.outputs.elasticsearch - UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.467 [[main]>worker0] ERROR logstash.outputs.elasticsearch - Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreach
able or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>4}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.468 [[main]>worker7] ERROR logstash.outputs.elasticsearch - Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreach
able or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>4}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.473 [[main]>worker1] WARN  logstash.outputs.elasticsearch - UNEXPECTED POOL ERROR {:e=>#<LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError: No Available connections>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.473 [[main]>worker1] ERROR logstash.outputs.elasticsearch - Attempted to send a bulk request to elasticsearch, but no there are no living connections in the connection pool. Perhaps Elasticsearch is unreach
able or down? {:error_message=>"No Available connections", :class=>"LogStash::Outputs::ElasticSearch::HttpClient::Pool::NoConnectionAvailableError", :will_retry_in_seconds=>4}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.911 [Ruby-0-Thread-18: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:234] INFO  logstash.outputs.elasticsea
rch - Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://sura-world-elasticsearch:9200/, :path=>"/"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.937 [Ruby-0-Thread-19: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:234] INFO  logstash.outputs.elasticsearch - Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://sura-world-elasticsearch:9200/, :path=>"/"}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.969 [Ruby-0-Thread-18: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:234] WARN  logstash.outputs.elasticsearch - Restored connection to ES instance {:url=>#<URI::HTTP:0x27531b27 URL:http://sura-world-elasticsearch:9200/>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:24:34.972 [Ruby-0-Thread-19: /usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.3.0-java/lib/logstash/outputs/elasticsearch/http_client/pool.rb:234] WARN  logstash.outputs.elasticsearch - Restored connection to ES instance {:url=>#<URI::HTTP:0x1fbed827 URL:http://sura-world-elasticsearch:9200/>}
suradev_sura-world_logstash.1.kfxgd5cz5a33@nagyubupc    | 08:26:54.657 [[main]>worker4] WARN  logstash.outputs.elasticsearch - Failed action. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-2017.08.08", :_type=>"log", :_routing=>nil}, 2017-08-08T08:26:54.482Z sura-pr-tomcat-beat-1 08-Aug-2017 08:26:45.412 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dmail.port=25,Command line argument: -Dmail.port=25], :response=>{"index"=>{"_index"=>"logstash-2017.08.08", "_type"=>"log", "_id"=>"AV3A9C7hH0VcyV2h7OtK", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [timestamp]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Invalid format: \"08-Aug-2017 08:26:45.412\" is malformed at \"-Aug-2017 08:26:45.412\""}}}}}
```

- Version: docker hub image with version 5.5.1
- Config File (if you have sensitive info, please remove it):
the output contains:
```
    elasticsearch {
      hosts => ["sura-world-elasticsearch:9200"]
      template => "/etc/logstash/index-template.json"
      template_name => "template1"
      index => "logstash-%{+YYYY.MM.dd}"
    }
```

**Comment by jsvd** [comment]
moved to https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/635
