### ISSUE TITLE
Elasticsearch credentials with special character not accepted in modules

### ISSUE THREAD

**Issue by suyograo** [elastic/logstash#7952]
I have an ES and Kibana instance whose password has `$` char in it. Some thing like `$foobar`. When I use this with modules, I get a configuration error.

bin/logstash --modules netflow -M "netflow.var.elasticsearch.password=$foobar" -M "netflow.var.kibana.password=$foobar" -M "netflow.var.kibana.username=elastic"

```sh
An unexpected error occurred! {:error=>#<LogStash::ConfigLoadingError: Failed to parse module variable arcsight.var.elasticsearch.password=.  Must be in -M "MODULE_NAME.KEY.SUBKEY=VALUE" format>, :backtrace=>["/home/ubuntu/logstash-5.6.0/logstash-core/lib/logstash/modules/cli_parser.rb:41:in `get_kv'", "/home/ubuntu/logstash-5.6.0/logstash-core/lib/logstash/modules/cli_parser.rb:61:in `parse_vars'", "org/jruby/RubyArray.java:1613:in `each'", "/home/ubuntu/logstash-5.6.0/logstash-core/lib/logstash/modules/cli_parser.rb:58:in `parse_vars'", "/home/ubuntu/logstash-5.6.0/logstash-core/lib/logstash/modules/cli_parser.rb:70:in `parse_it'", "org/jruby/RubyArray.java:1613:in `each'", "/home/ubuntu/logstash-5.6.0/logstash-core/lib/logstash/modules/cli_parser.rb:69:in `parse_it'", "/home/ubuntu/logstash-5.6.0/logstash-core/lib/logstash/modules/cli_parser.rb:14:in `initialize'", "/home/ubuntu/logstash-5.6.0/logstash-core/lib/logstash/runner.rb:250:in `execute'", "/home/ubuntu/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/home/ubuntu/logstash-5.6.0/logstash-core/lib/logstash/runner.rb:199:in `run'", "/home/ubuntu/logstash-5.6.0/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/home/ubuntu/logstash-5.6.0/lib/bootstrap/environment.rb:71:in `(root)'"]}
```

**Comment by untergeek** [comment]
Since this is a command-line action, `"$foobar"` will be evaluated as a shell variable, but `'$foobar'` will be literal.  This is not unexpected.
