### ISSUE TITLE
LogStash::Event using normal hash input behaves like all event tests timestamp initialization should assign current time when no timestamp

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#7958]
I got this locally on master:

```
Failures:

  1) LogStash::Event using normal hash input behaves like all event tests timestamp initialization should assign current time when no timestamp
     Failure/Error: expect(LogStash::Event.new({}).timestamp.to_i).to be_within(1).of (Time.now.to_i)
       expected 1502286490 to be within 1 of 1502286492
     Shared Example Group: "all event tests" called from ./logstash-core/spec/logstash/legacy_ruby_event_spec.rb:576
     # ./logstash-core/spec/logstash/legacy_ruby_event_spec.rb:402:in `block in (root)'
     # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /private/tmp/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # ./lib/bootstrap/rspec.rb:13:in `<main>'

Finished in 9 minutes 8 seconds (files took 27.58 seconds to load)
2299 examples, 1 failure, 3 pending

Failed examples:

rspec './logstash-core/spec/logstash/legacy_ruby_event_spec.rb[1:1:1:9:2]' # LogStash::Event using normal hash input behaves like all event tests timestamp initialization should assign current time when no timestamp

Randomized with seed 36097
```

**Comment by jsvd** [comment]
@guyboertje it seems the 1 second flexibility in this test isn't guaranteed to be enough ?

**Comment by jsvd** [comment]
another example in jenkins https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-linux-intake/430/console:

```
  1) LogStash::Timestamp constructors should work
     Failure/Error: expect(t.time.to_i).to be_within(1).of Time.now.to_i
       expected 1502290365 to be within 1 of 1502290367
     # /var/lib/jenkins/workspace/elastic+logstash+pull-request+multijob-linux-intake/logstash-core/spec/logstash/timestamp_spec.rb:16:in `block in (root)'
     # /var/lib/jenkins/workspace/elastic+logstash+pull-request+multijob-linux-intake/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+pull-request+multijob-linux-intake/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
     # /var/lib/jenkins/workspace/elastic+logstash+pull-request+multijob-linux-intake/lib/bootstrap/rspec.rb:13:in `<main>'
```

**Comment by original-brownbear** [comment]
I think this is a duplicate of https://github.com/elastic/logstash/issues/7933 (at least in terms of the fix it will require :))

**Comment by jsvd** [comment]
ugh, I did search for an open issue, seems my search foo is poor. closing as duplicate of https://github.com/elastic/logstash/issues/7933
