### ISSUE TITLE
the problem of logstash path 

### ISSUE THREAD

**Issue by Howard-Chang** [elastic/logstash#8018]
Hi everyone,
   I am new in logstash.I refer to the website https://www.elastic.co/guide/en/logstash/current/config-examples.html#config-examples and try to do its "processing Apache log" example 
this is the directory of logstash :
![image](https://user-images.githubusercontent.com/19474557/29418432-da06281e-839e-11e7-92bf-9727b37fbec2.png)
and this is the logstash-apache.conf:
![image](https://user-images.githubusercontent.com/19474557/29418476-f9298150-839e-11e7-9857-162e29517d93.png)

the cmd output:
C:\Users\User\Downloads\logstash-5.5.1\bin>logstash -f logstash-apache.conf
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Sending Logstash's logs to C:/Users/User/Downloads/logstash-5.5.1/logs which is now configured via log4j2.properties
[2017-08-17T22:47:25,120][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2017-08-17T22:47:25,120][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[2017-08-17T22:47:25,277][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>#<Java::JavaNet::URI:0x3c4c5c1d>}
[2017-08-17T22:47:25,277][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2017-08-17T22:47:25,339][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>50001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"_all"=>{"enabled"=>true, "norms"=>false}, "dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date", "include_in_all"=>false}, "@version"=>{"type"=>"keyword", "include_in_all"=>false}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
[2017-08-17T22:47:25,339][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>[#<Java::JavaNet::URI:0x4052ee7>]}
[2017-08-17T22:47:25,464][INFO ][logstash.pipeline        ] Starting pipeline {"id"=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>500}
[2017-08-17T22:47:25,886][ERROR][logstash.pipeline        ] Error registering plugin {:plugin=>"<LogStash::Inputs::File path=>[\"access_log\"], start_position=>\"beginning\", id=>\"7c023815a1eff81f47b80a88993928b5f7efe0fa-1\", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>\"plain_38649b50-a063-406e-a126-f5c219eb4030\", enable_metric=>true, charset=>\"UTF-8\">, stat_interval=>1, discover_interval=>15, sincedb_write_interval=>15, delimiter=>\"\\n\", close_older=>3600>", :error=>"File paths must be absolute, relative path specified: access_log"}
[2017-08-17T22:47:26,295][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<ArgumentError: File paths must be absolute, relative path specified: access_log>, :backtrace=>["C:/Users/User/Downloads/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/logstash-input-file-4.0.2/lib/logstash/inputs/file.rb:187:in `register'", "org/jruby/RubyArray.java:1613:in `each'", "C:/Users/User/Downloads/logstash-5.5.1/vendor/bundle/jruby/1.9/gems/logstash-input-file-4.0.2/lib/logstash/inputs/file.rb:185:in `register'", "C:/Users/User/Downloads/logstash-5.5.1/logstash-core/lib/logstash/pipeline.rb:281:in `register_plugin'", "C:/Users/User/Downloads/logstash-5.5.1/logstash-core/lib/logstash/pipeline.rb:292:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "C:/Users/User/Downloads/logstash-5.5.1/logstash-core/lib/logstash/pipeline.rb:292:in `register_plugins'", "C:/Users/User/Downloads/logstash-5.5.1/logstash-core/lib/logstash/pipeline.rb:442:in `start_inputs'", "C:/Users/User/Downloads/logstash-5.5.1/logstash-core/lib/logstash/pipeline.rb:336:in `start_workers'", "C:/Users/User/Downloads/logstash-5.5.1/logstash-core/lib/logstash/pipeline.rb:226:in `run'", "C:/Users/User/Downloads/logstash-5.5.1/logstash-core/lib/logstash/agent.rb:398:in `start_pipeline'"]}
[2017-08-17T22:47:26,389][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-08-17T22:47:29,341][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
It seems didn't work .
I thought the problem maybe the wrong path, but I don't know how to correct it.

**Comment by jakelandis** [comment]
Have you tried using backslashes instead of forward slashes ?

This config worked for me on Windows without issue:
```
input {
 file {
   path => "C:\Users\jake\apache_logs.txt"
   start_position => "beginning"
 }
}
filter { }
output { 
   stdout { 
       codec => rubydebug { metadata => true }
      }
} 
```

**Comment by Howard-Chang** [comment]
I tried the same steps on another windows pc.
I found it could work, but on my pc it can't work .

**Comment by Howard-Chang** [comment]
I found it sometimes could work sometimes couldn't work..

**Comment by Howard-Chang** [comment]
it's usually blocked here
[2017-08-17T22:47:26,389][INFO ][logstash.agent ] Successfully started Logstash API endpoint {:port=>9600}

**Comment by jakelandis** [comment]
I am going to close out this issue since this seems local to your setup, not an issue with Logstash itself. 

Feel free to post to https://discuss.elastic.co/c/logstash , maybe someone there has experienced the same. (Alot more people watch the forum's then Github issues).
