### ISSUE TITLE
[test failure: PR integration test] Test Kafka Input can ingest 37 apache log lines from Kafka broker

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8033]
the PR Travis integration test has failed with an unrelated Kafka input error.
See https://travis-ci.org/elastic/logstash/jobs/266095127

```
Failures:
  1) Test Kafka Input can ingest 37 apache log lines from Kafka broker
     Failure/Error: expect(count).to eq(num_events)
     
       expected: 37
            got: 1
     
       (compared using ==)
     # ./specs/kafka_input_spec.rb:29:in `block in /home/travis/build/elastic/logstash/qa/integration/specs/kafka_input_spec.rb'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/logstash-devutils-1.3.3-java/lib/logstash/devutils/rspec/logstash_helpers.rb:18:in `try'
     # ./specs/kafka_input_spec.rb:27:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
  2) Test Logstash Slowlog should write logs to a new dir
     Failure/Error: expect(IO.read(slowlog_file).split("\n").size).to eq(2)
     
       expected: 2
            got: 1
     
       (compared using ==)
     # ./specs/slowlog_spec.rb:44:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
Finished in 26 minutes 42 seconds (files took 8.65 seconds to load)
32 examples, 2 failures
Failed examples:
rspec ./specs/kafka_input_spec.rb:19 # Test Kafka Input can ingest 37 apache log lines from Kafka broker
rspec ./specs/slowlog_spec.rb:33 # Test Logstash Slowlog should write logs to a new dir
Randomized with seed 28404
```

**Comment by jakelandis** [comment]
Closing this. Our testing strategy w/r/t to kafka and elastic search has changed since this was logged. See https://github.com/elastic/logstash/pull/8211 for additional information.
