### ISSUE TITLE
RATS Tests sometimes start two logstashes causing test failures

### ISSUE THREAD

**Issue by andrewvc** [elastic/logstash#8057]
Sometimes we get failures like:   
```
11) LogStash::Api::Modules::Node#hot threads Generic JSON testing GET / the default metadata should include the http address
      Failure/Error: expect(payload["http_address"]).to eql("127.0.0.1:#{::LogStash::WebServer::DEFAULT_PORTS.first}")
      
        expected: "127.0.0.1:9600"
             got: "127.0.0.1:9601"
      
        (compared using eql?)
      # ./spec/support/resource_dsl_methods.rb:48:in `block in test_api'
      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /home/travis/build/elastic/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
      # ./lib/bootstrap/rspec.rb:13:in `<main>'
```
which indicate that a previous logstash isn't being properly cleaned up before this run.

**Comment by jakelandis** [comment]
Moving to a Docker based approach for the RATS Tests should resolve this issue, and after a week of close monitoring I have not seen this issue re-appear. 

Closing issue.
