### ISSUE TITLE
LogStash::WebServer when an exception occur in the server thread should not log to STDERR

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8148]
`LogStash::WebServer when an exception occur in the server thread should not log to STDERR`

just failed here https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-unix-compatibility/os=amazon/116/console with error:

```sh
20:01:13   1) LogStash::WebServer when an exception occur in the server thread should not log to STDERR
20:01:13      Failure/Error: status = RSpec::Core::Runner.run(ARGV.empty? ? ["spec"] : ARGV).to_i
20:01:13 
20:01:13      ConcurrencyError:
20:01:13        Detected invalid array contents due to unsynchronized modifications with concurrent users
20:01:13      # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/amazon/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/amazon/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
20:01:13      # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/amazon/lib/bootstrap/rspec.rb:13:in `<main>'
```

**Comment by original-brownbear** [comment]
Fixed by #8150
