### ISSUE TITLE
 LogStash::Agent metrics after config reloading when reloading a bad config sets the failure reload timestamp

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8149]
Seems we're leaking in these specs, error for ` LogStash::Agent metrics after config reloading when reloading a bad config sets the failure reload timestamp`:

```sh
19:43:51   1) LogStash::Agent metrics after config reloading when reloading a bad config sets the failure reload timestamp
19:43:51      Failure/Error: raise ExpiredTestDoubleError,
19:43:51        #<Double "logger"> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.
19:43:51      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/opensuse/logstash-core/lib/logstash/webserver.rb:90:in `start_webserver'
19:43:51      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/opensuse/logstash-core/lib/logstash/webserver.rb:44:in `block in run'
19:43:51      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/opensuse/logstash-core/lib/logstash/webserver.rb:39:in `run'
19:43:51      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/opensuse/logstash-core/lib/logstash/agent.rb:393:in `block in start_webserver'
```

https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/os=opensuse/62/console

**Comment by original-brownbear** [comment]
fixed by #8151
