### ISSUE TITLE
Metrics exceptions supply misleading stack trace

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#8153]
While discussing an integration test failure, the following stack trace was observed:

https://github.com/elastic/logstash/issues/8142#issuecomment-327483836

which looks like a failure attempting to increment the metrics counter by a negative value. Unfortunately, the stack trace is lost because of the static initialization of the Exception, which causes the stack trace to be constructed at the point the Counter class was initialized, rather than where the increment call was made from

To verify this, run the `incrementByNegativeValue` test in LongCounterTest.java, and observe the stack trace shows the stack trace from the first instantiation of LongCounter.java, and not where the error occurs: 

```
java.lang.IllegalArgumentException: Counters can not be incremented by negative values
	at org.logstash.instrument.metrics.counter.LongCounter.<clinit>(LongCounter.java:15)
	at org.logstash.instrument.metrics.counter.LongCounterTest._setup(LongCounterTest.java:21)
```

cc @jakelandis, @original-brownbear

**Comment by jakelandis** [comment]
From @original-brownbear comment on https://github.com/elastic/logstash/issues/8142#issuecomment-327519298 

> nah this is intentional :) This path is so hot and already crazy nested, making this a static was the only thing small enough to not break inlining :)

This is one of the hottest paths in all of the code, and IMO micro-optimizations here are warranted.  However, there may be other ways to optimize that doesn't break the traceability?

 @original-brownbear - Do you know if there is an alternatives such as a private or a static method to handle the exception case that keeps the JIT happy, but doesn't break trace-ability ?

**Comment by original-brownbear** [comment]
@jakelandis when I last profiled this I think there wasn't but obviously the code changed a lot recently, maybe we can change this stuff. I'd just leave this alone for the time being. This thing should basically never ever be thrown if it is, it's a bug every time (and tracking it down by grepping all places that call `increment` should be possible).

**Comment by robbavey** [comment]
@original-brownbear, @jakelandis  Given that these Exceptions almost never happen, what is the actual performance impact in general running, of using the static Exception over a standard Exception - if this is rare, you are not going to be paying the cost of filling in the stack trace, which is the normal expensive part with Exceptions (and why people using Exceptions for control flow typically override fillInStackTrace to avoid this?). I mean you could call fillInStackTrace manually on the throw of Exception - 

```
    @Override
    public void increment(Long by) {
        if (by < 0) {
            throw (IllegalArgumentException)NEGATIVE_COUNT_EXCEPTION.fillInStackTrace();
        }
        longAdder.add(by);
    }
```
but, I don't know what the perf. impact would be in the general (non-exceptional...) case

**Comment by original-brownbear** [comment]
@robbavey 

> but, I don't know what the perf. impact would be in the general (non-exceptional...) case

me neither, it's really hard to predict and we already have a super weird exec environment in the hot path (with the constant Ruby -> Java -> Ruby stuff and such), so we better not mess with this imo ... that said, maybe just turn this into an assertion? To me, it seems natural since we're micro optimizing here :)
