### ISSUE TITLE
Running a single integration tests can fail due to classpath/load ordering. 

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8177]
- Steps to Reproduce:

Following the directions here: https://github.com/elastic/logstash/tree/master/qa/integration , and run `rspec specs/es_output_how_spec.rb`. This will result in a `missing class name ` error. 

There is nothing wrong with that specific test, but when it is called prior to any other test, the stack can result in calling a `java_import` BEFORE the classpath has been set.  See the full backtrace below. 

The fix for this should be un-wind the odd dependency stack (devutils->old logstash) AND to ensure that classpath is properly set prior to any calls to `java_import`. 

Note - a cheap hack to get around this issue is to add `require "logstash-core"` to anyone of the files in the stack trace. This will ensure that the Java class path is set prior to the call to `java_import`  which is what blows up. 

```
     NameError:
       missing class name (`org.apache.logging.log4j.Level')
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/logging/logger.rb:6:in `<module:Logging>'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/logging/logger.rb:5:in `<module:LogStash>'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/logging/logger.rb:4:in `<main>'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/util/loggable.rb:1:in `<main>'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/util/loggable.rb:2:in `<main>'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/settings.rb:1:in `<main>'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/settings.rb:2:in `<main>'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/environment.rb:1:in `<main>'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/environment.rb:5:in `<main>'
     # uri:classloader:/jruby/kernel/kernel.rb:13:in `require_relative'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/agent.rb:1:in `<main>'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-core-5.5.1.snapshot1-java/lib/logstash/agent.rb:2:in `block in (root)'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-devutils-1.3.3-java/lib/logstash/devutils/rspec/logstash_helpers.rb:1:in `(root)'
     # /Users/jake/.rvm/gems/jruby-9.1.12.0/gems/logstash-devutils-1.3.3-java/lib/logstash/devutils/rspec/logstash_helpers.rb:1:in `(root)'
     # ./services/service_container.rb:1:in `(root)'
     # ./services/service_container.rb:3:in `block in (root)'
     # ./services/elasticsearch_service.rb:1:in `(root)'
     # ./services/elasticsearch_service.rb:1:in `block in (root)'
     # ./services/service_locator.rb:1:in `(root)'
     # ./services/service_locator.rb:23:in `available_services'
     # ./services/service_locator.rb:22:in `block in available_services'
     # ./services/service_locator.rb:12:in `block in initialize'
     # ./framework/fixture.rb:28:in `initialize'
     # ./specs/es_output_how_spec.rb:8:in `(root)'
```

**Comment by original-brownbear** [comment]
@jakelandis nice, thanks for tracking this down. Let me see if I can find a fix for this, hate this circular dependency :D

**Comment by original-brownbear** [comment]
fixed
