### ISSUE TITLE
Test Failure: LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#8204]
Jenkins test failure running compatibility tests on OpenSuse for version 6.x:

```
17:43:03 Failures:
17:43:03 
17:43:03   1) LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once
17:43:03      Failure/Error: expect(source_loader.fetch_count).to eq(1)
17:43:03 
17:43:03        expected: 1
17:43:03             got: 0
17:43:03 
17:43:03        (compared using ==)
17:43:03      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/opensuse/logstash-core/spec/logstash/agent/converge_spec.rb:108:in `block in (root)'
17:43:03      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/opensuse/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/opensuse/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
17:43:03      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/opensuse/lib/bootstrap/rspec.rb:13:in `<main>'
17:43:03 
17:43:03 Finished in 7 minutes 23 seconds (files took 19.54 seconds to load)
17:43:03 3060 examples, 1 failure, 3 pending
17:43:03 
17:43:03 Failed examples:
17:43:03 
17:43:03 rspec /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/opensuse/logstash-core/spec/logstash/agent/converge_spec.rb:105 # LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once
17:43:03 
17:43:03 Randomized with seed 56177
```

This test appears to have had some issues in the past: 
#7737 
#7392

**Comment by jakelandis** [comment]
... and again

```
11:24:11 Failures:
11:24:11 
11:24:11   1) LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once
11:24:11      Failure/Error: expect(source_loader.fetch_count).to eq(1)
11:24:11 
11:24:11        expected: 1
11:24:11             got: 0
11:24:11 
11:24:11        (compared using ==)
11:24:11      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/debian/logstash-core/spec/logstash/agent/converge_spec.rb:108:in `block in (root)'
11:24:11      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
11:24:11      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/debian/lib/bootstrap/rspec.rb:13:in `<main>'
11:24:12 
11:24:12 Finished in 7 minutes 32 seconds (files took 20.77 seconds to load)
11:24:12 2153 examples, 1 failure, 3 pending
11:24:12 
11:24:12 Failed examples:
11:24:12 
11:24:12 rspec /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/debian/logstash-core/spec/logstash/agent/converge_spec.rb:105 # LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once
11:24:12 
11:24:12 Randomized with seed 50126
```

**Comment by jakelandis** [comment]
I wasn't ever able to recreate this issue, but I believe this is a timing issue when starting the agent. The fix here is to give more time to agent to start. (It is currently .1s)

**Comment by colinsurprenant** [comment]
Reopening:
https://logstash-ci.elastic.co/job/elastic+logstash+6.0+multijob-unix-compatibility/os=amazon/125/console
```
16:36:41   1) LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once
16:36:41      Failure/Error: expect(source_loader.fetch_count).to eq(1)
16:36:41 
16:36:41        expected: 1
16:36:41             got: 0
16:36:41 
16:36:41        (compared using ==)
16:36:41      # /var/lib/jenkins/workspace/elastic+logstash+6.0+multijob-unix-compatibility/os/amazon/logstash-core/spec/logstash/agent/converge_spec.rb:120:in `block in (root)'
16:36:41      # /var/lib/jenkins/workspace/elastic+logstash+6.0+multijob-unix-compatibility/os/amazon/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+6.0+multijob-unix-compatibility/os/amazon/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
16:36:41      # /var/lib/jenkins/workspace/elastic+logstash+6.0+multijob-unix-compatibility/os/amazon/lib/bootstrap/rspec.rb:13:in `<main>'
16:36:41 
16:36:41 Finished in 6 minutes 10 seconds (files took 11.18 seconds to load)
16:36:41 2491 examples, 1 failure, 3 pending
16:36:41 
16:36:41 Failed examples:
16:36:41 
16:36:41 rspec /var/lib/jenkins/workspace/elastic+logstash+6.0+multijob-unix-compatibility/os/amazon/logstash-core/spec/logstash/agent/converge_spec.rb:119 # LogStash::Agent Agent execute options when `config.reload.automatic` is set to`FALSE` and successfully load the config converge only once
16:36:41 
16:36:41 Randomized with seed 44136
```
