### ISSUE TITLE
6.0 Integration Tests around the Installation are Broken

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8299]
See https://travis-ci.org/elastic/logstash/jobs/276850296

```sh
Failures:
  1) CLI > logstash-plugin install pack when the command is run in the `$LOGSTASH_HOME` without internet connection (linux seccomp wrapper) successfully install the pack
     Failure/Error: expect(installed.stderr_and_stdout).to match(/logstash-output-secret/)
     
       expected "Gem::LoadError: You have already activated ruby-progressbar 1.8.3, but your Gemfile requires ruby-pr...home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/main.rb:48\n" to match /logstash-output-secret/
       Diff:
       @@ -1,2 +1,14 @@
       -/logstash-output-secret/
       +Gem::LoadError: You have already activated ruby-progressbar 1.8.3, but your Gemfile requires ruby-progressbar 1.8.1. Prepending `bundle exec` to your command may solve this.
       +  block in setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
       +            each at org/jruby/RubyArray.java:1734
       +            each at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/jruby/lib/ruby/stdlib/forwardable.rb:189
       +           setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:19
       +           setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:122
       +          setup! at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/bootstrap/bundler.rb:68
       +         execute at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/list.rb:17
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
       +         execute at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
       +          <main> at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/main.rb:48
       
     Shared Example Group: "install from a pack" called from ./specs/cli/install_spec.rb:76
     # ./specs/cli/install_spec.rb:51:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
  2) CLI > logstash-plugin install pack when the command is run outside of the `$LOGSTASH_HOME` without internet connection (linux seccomp wrapper) successfully install the pack
     Failure/Error: expect(installed.stderr_and_stdout).to match(/logstash-output-secret/)
     
       expected "Gem::LoadError: You have already activated ruby-progressbar 1.8.3, but your Gemfile requires ruby-pr...home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/main.rb:48\n" to match /logstash-output-secret/
       Diff:
       @@ -1,2 +1,14 @@
       -/logstash-output-secret/
       +Gem::LoadError: You have already activated ruby-progressbar 1.8.3, but your Gemfile requires ruby-progressbar 1.8.1. Prepending `bundle exec` to your command may solve this.
       +  block in setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
       +            each at org/jruby/RubyArray.java:1734
       +            each at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/jruby/lib/ruby/stdlib/forwardable.rb:189
       +           setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:19
       +           setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:122
       +          setup! at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/bootstrap/bundler.rb:68
       +         execute at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/list.rb:17
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
       +         execute at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
       +          <main> at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/main.rb:48
       
     Shared Example Group: "install from a pack" called from ./specs/cli/install_spec.rb:80
     # ./specs/cli/install_spec.rb:51:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
  3) CLI > logstash-plugin prepare-offline-pack creating a pack for specific plugins successfully create a pack
     Failure/Error: expect(execute.exit_code).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./specs/cli/prepare_offline_pack_spec.rb:25:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
  4) CLI > logstash-plugin prepare-offline-pack create a pack with a locally installed .gem successfully create a pack
     Failure/Error: expect(execute.stderr_and_stdout).to match(/#{plugin_to_pack}/)
     
       expected "Gem::LoadError: You have already activated ruby-progressbar 1.8.3, but your Gemfile requires ruby-pr...home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/main.rb:48\n" to match /logstash-filter-qatest/
       Diff:
       @@ -1,2 +1,14 @@
       -/logstash-filter-qatest/
       +Gem::LoadError: You have already activated ruby-progressbar 1.8.3, but your Gemfile requires ruby-progressbar 1.8.1. Prepending `bundle exec` to your command may solve this.
       +  block in setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
       +            each at org/jruby/RubyArray.java:1734
       +            each at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/jruby/lib/ruby/stdlib/forwardable.rb:189
       +           setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:19
       +           setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:122
       +          setup! at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/bootstrap/bundler.rb:68
       +         execute at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/list.rb:17
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
       +         execute at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
       +          <main> at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/main.rb:48
     m  
     # ./specs/cli/prepare_offline_pack_spec.rb:68:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
  5) CLI > logstash-plugin prepare-offline-pack create a pack from a wildcard successfully create a pack
     Failure/Error: expect(execute.exit_code).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./specs/cli/prepare_offline_pack_spec.rb:44:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
  6) CLI > logstash-plugin remove without internet connection (linux seccomp wrapper) when other plugins depends on this plugin refuses to remove the plugin and display the plugin that depends on it.
     Failure/Error: expect(execute.stderr_and_stdout).to match(/Failed to remove "logstash-codec-json"/)
     
       expected "Gem::LoadError: You have already activated ruby-progressbar 1.8.3, but your Gemfile requires ruby-pr...home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/main.rb:48\n" to match /Failed to remove "logstash-codec-json"/
       Diff:
       @@ -1,2 +1,14 @@
       -/Failed to remove "logstash-codec-json"/
       +Gem::LoadError: You have already activated ruby-progressbar 1.8.3, but your Gemfile requires ruby-progressbar 1.8.1. Prepending `bundle exec` to your command may solve this.
       +  block in setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:34
       +            each at org/jruby/RubyArray.java:1734
       +            each at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/jruby/lib/ruby/stdlib/forwardable.rb:189
       +           setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:19
       +           setup at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:122
       +          setup! at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/bootstrap/bundler.rb:68
       +         execute at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/remove.rb:16
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
       +         execute at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
       +             run at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
       +          <main> at /home/travis/build/elastic/logstash/build/logstash-6.0.0-rc1-SNAPSHOT/lib/pluginmanager/main.rb:48
       
     # ./specs/cli/remove_spec.rb:47:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
  7) CLI > logstash-plugin remove without internet connection (linux seccomp wrapper) when no other plugins depends on this plugin successfully remove the plugin
     Failure/Error: expect(execute.exit_code).to eq(0)
     
       expected: 0
            got: 1
     
       (compared using ==)
     # ./specs/cli/remove_spec.rb:31:in `block in (root)'
     # /home/travis/.rvm/gems/jruby-9.1.10.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
Finished in 24 minutes 18 seconds (files took 6.72 seconds to load)
38 examples, 7 failures
Failed examples:
rspec ./specs/cli/install_spec.rb[1:1:1:1:1] # CLI > logstash-plugin install pack when the command is run in the `$LOGSTASH_HOME` without internet connection (linux seccomp wrapper) successfully install the pack
rspec ./specs/cli/install_spec.rb[1:1:2:1:1] # CLI > logstash-plugin install pack when the command is run outside of the `$LOGSTASH_HOME` without internet connection (linux seccomp wrapper) successfully install the pack
rspec ./specs/cli/prepare_offline_pack_spec.rb:22 # CLI > logstash-plugin prepare-offline-pack creating a pack for specific plugins successfully create a pack
rspec ./specs/cli/prepare_offline_pack_spec.rb:72 # CLI > logstash-plugin prepare-offline-pack create a pack with a locally installed .gem successfully create a pack
rspec ./specs/cli/prepare_offline_pack_spec.rb:41 # CLI > logstash-plugin prepare-offline-pack create a pack from a wildcard successfully create a pack
rspec ./specs/cli/remove_spec.rb:43 # CLI > logstash-plugin remove without internet connection (linux seccomp wrapper) when other plugins depends on this plugin refuses to remove the plugin and display the plugin that depends on it.
rspec ./specs/cli/remove_spec.rb:28 # CLI > logstash-plugin remove without internet connection (linux seccomp wrapper) when no other plugins depends on this plugin successfully remove the plugin
```

**Comment by original-brownbear** [comment]
fixed in #8301
