### ISSUE TITLE
Regression: 5.6.2-SNAPSHOT - Ruby loggers

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8337]
There is a regression in the pending 5.6.2 release that breaks the ability to configure the Ruby loggers via the API. 

5.6.1
----
```
curl -XGET 'localhost:9600/_node/logging?pretty'
{
  "host" : "macd",
  "version" : "5.6.1",
  "http_address" : "127.0.0.1:9600",
  "id" : "44823f48-fd29-4f2c-8c46-05e02667692d",
  "name" : "macd",
  "loggers" : {
    "logstash.agent" : "INFO",
    "logstash.api.service" : "INFO",
    "logstash.codecs.line" : "INFO",
    "logstash.codecs.rubydebug" : "INFO",
    "logstash.inputs.stdin" : "INFO",
    "logstash.instrument.periodicpoller.deadletterqueue" : "INFO",
    "logstash.instrument.periodicpoller.jvm" : "INFO",
    "logstash.instrument.periodicpoller.os" : "INFO",
    "logstash.instrument.periodicpoller.persistentqueue" : "INFO",
    "logstash.modules.scaffold" : "INFO",
    "logstash.outputs.stdout" : "INFO",
    "logstash.pipeline" : "INFO",
    "logstash.plugins.registry" : "INFO",
    "logstash.runner" : "INFO",
    "logstash.setting.writabledirectory" : "INFO",
    "org.logstash.Event" : "INFO",
    "org.logstash.common.DeadLetterQueueFactory" : "INFO",
    "org.logstash.common.io.DeadLetterQueueWriter" : "INFO",
    "slowlog.logstash.codecs.line" : "TRACE",
    "slowlog.logstash.codecs.rubydebug" : "TRACE",
    "slowlog.logstash.inputs.stdin" : "TRACE",
    "slowlog.logstash.outputs.stdout" : "TRACE"
  }
}
```

5.6.2-SNAPSHOT
------
```
curl -XGET 'localhost:9600/_node/logging?pretty'
{
  "host" : "macd",
  "version" : "5.6.2",
  "http_address" : "127.0.0.1:9600",
  "id" : "2e8c3473-0953-49a6-80c4-1c89d599a741",
  "name" : "macd",
  "loggers" : {
    "org.logstash.Event" : "INFO",
    "org.logstash.common.DeadLetterQueueFactory" : "INFO",
    "org.logstash.common.io.DeadLetterQueueWriter" : "INFO"
  }
}
```

Found via an integration test:
```
13:05:45 Failures:
13:05:45 
13:05:45   1) Test Monitoring API can configure logging
13:05:45      Failure/Error: expect(logstash_service.monitoring_api.logging_get["loggers"]["logstash.agent"]).to eq ("DEBUG")
13:05:45      
13:05:45        expected: "DEBUG"
13:05:45             got: nil
13:05:45      
13:05:45        (compared using ==)
13:05:45      # ./specs/monitoring_api_spec.rb:121:in `(root)'
13:05:45      # ./specs/monitoring_api_spec.rb:105:in `(root)'
13:05:45 
13:05:45 Finished in 11 minutes 40 seconds (files took 3.48 seconds to load)
13:05:45 21 examples, 1 failure
```

Since this test exists in other pipeline, I believe that 5.6 branch is the branch effected.

**Comment by original-brownbear** [comment]
@jakelandis https://github.com/elastic/logstash/issues/8331

**Comment by jakelandis** [comment]
fixed with https://github.com/elastic/logstash/pull/8339
