### ISSUE TITLE
Test failure: timing issue in timestamp_spec.rb

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8341]
```
16:28:26 Failures:
16:28:26 
16:28:26   1) LogStash::Timestamp constructors should work
16:28:26      Failure/Error: expect(t.time.to_i).to be_within(1).of Time.now.to_i
16:28:26        expected 1505924544 to be within 1 of 1505924546
16:28:26      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/ubuntu/logstash-core/spec/logstash/timestamp_spec.rb:16:in `block in (root)'
16:28:26      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/ubuntu/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/ubuntu/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
16:28:26      # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/ubuntu/lib/bootstrap/rspec.rb:13:in `<main>'
16:28:26 
16:28:26 Finished in 7 minutes 42 seconds (files took 18.7 seconds to load)
```

Caused by the following test in timestamp_spec.rb is dependent on these two command being executed within 1ms of each other: 

```
      t = LogStash::Timestamp.now
      expect(t.time.to_i).to be_within(1).of Time.now.to_i
```

**Comment by original-brownbear** [comment]
fixed in #8342
