### ISSUE TITLE
Broken Param Syntax in REST Request Leads to HTTP 500

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8343]
Relatively minor bug it seems, but if you visit a broken URL like `http://127.0.0.1:9600/_node/hot_threads?human=?threads=5` you get a 400 back, when it should be a `400`.

E.g.
```sh
{"status":500,"request_method":"GET","path_info":"/_node/hot_threads","query_string":"human=?threads=5","http_version":"HTTP/1.1","http_accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8","error":"Unexpected Internal Error","class":"ArgumentError","message":"invalid value for Boolean: \"?threads=5\"","backtrace":["/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/app_helpers.rb:48:in `as_boolean'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/app_helpers.rb:72:in `human?'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/modules/node.rb:19:in `block in Node'","org/jruby/RubyMethod.java:111:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block in route!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'","org/jruby/RubyKernel.java:1114:in `catch'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'","org/jruby/RubyArray.java:1734:in `each'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'","org/jruby/RubyKernel.java:1114:in `catch'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'","org/jruby/RubyKernel.java:1114:in `catch'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/nulllogger.rb:9:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/head.rb:13:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:66:in `block in call'","org/jruby/RubyArray.java:1734:in `each'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/urlmap.rb:50:in `call'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:57:in `call'","/Users/brownbear/src/logstash/logstash-core/lib/logstash/api/rack_app.rb:31:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:153:in `call'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:557:in `handle_request'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:404:in `process_client'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/server.rb:270:in `block in run'","/Users/brownbear/src/logstash/vendor/bundle/jruby/2.3.0/gems/puma-2.16.0-java/lib/puma/thread_pool.rb:106:in `block in spawn_thread'"]}
```

**Comment by jordansissel** [comment]
I agree you should get a 400 back since this is a client error.
