### ISSUE TITLE
[Windows] Metrics Java test fails on master on Windows

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8360]
```
org.logstash.benchmark.cli.LsMetricsMonitorTest > parsesFilteredCount FAILED                                  
    java.lang.AssertionError:                                                                                 
    Expected: is <21052.0>                                                                                    
         but: was <NaN>                                                                                       
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)                                       
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)                                        
        at org.logstash.benchmark.cli.LsMetricsMonitorTest.parsesFilteredCount(LsMetricsMonitorTest.java:40)  
```

**Comment by original-brownbear** [comment]
fixed in #8372
