### ISSUE TITLE
Test Failing: Virtualbox error?

### ISSUE THREAD

**Issue by ph** [elastic/logstash#8406]
```
20:51:12 Stderr: VBoxManage: error: The machine 'qa_debian-8_1506545469118_1066' is already locked by a session (or being locked or unlocked)
20:51:12 VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
20:51:12 VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 590 of file VBoxManageMisc.cpp
20:51:12 /var/lib/jenkins/workspace/elastic+logstash+6.0+multijob-acceptance/label/metal/suite/debian/qa/vagrant/command.rb:49:in `run!'
20:51:12 /var/lib/jenkins/workspace/elastic+logstash+6.0+multijob-acceptance/label/metal/suite/debian/qa/vagrant/helpers.rb:21:in `bootstrap'
20:51:12 /var/lib/jenkins/workspace/elastic+logstash+6.0+multijob-acceptance/label/metal/suite/debian/qa/Rakefile:40:in `block in (root)'
20:51:12 /var/lib/jenkins/.rbenv/versions/jruby-9.1.12.0/bin/bundle:22:in `<main>'
```

**Comment by ph** [comment]
@jakelandis Have you seen this error before, two jobs using the same resources?

**Comment by jakelandis** [comment]
I saw errors similar to this for a short period of time after we bumped from 1 to 4 executors and the Jenkins jobs were getting aborted. This PR https://github.com/elastic/logstash/pull/8380 fixed that Jenkins jobs aborted and I didn't see this re-appear until now, so likely different root cause, same symptom. 

I jumped on the host machine and checked vagrant status and they all look good, and no rouge virtual box instances hanging around. I am not sure what would cause this. 

Worst case, if this keeps happening, we may need to go back to 1 executor for the acceptance tests, but without more hardware that will slow down the builds.
