### ISSUE TITLE
Logstash crushed when server run out of disk space

### ISSUE THREAD

**Issue by pavel-sbor** [elastic/logstash#8486]
One of our servers with Logstash run out of disk space.
This led to crushing of Logstash process with NullPointerException in logs
[logstash.err.txt](https://github.com/elastic/logstash/files/1379977/logstash.err.txt)

- Version: 5.5.2
- Operating System: RHEL7
- Steps to Reproduce:
You need to load a disk with running Logstash with any kind of data until you see a fatal message in logstash-plain log file: 
`[FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<IOError: No space left on device>, :backtrace=>["org/jruby/ext/zlib/JZlibRubyGzipWriter.java:360:in `flush'", "/data/elog/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-file-4.1.0/lib/logstash/outputs/file.rb:293:in `flush'", "/data/elog/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-file-4.1.0/lib/logstash/outputs/file.rb:127:in `multi_receive_encoded'", "org/jruby/RubyHash.java:1342:in `each'", "/data/elog/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-file-4.1.0/lib/logstash/outputs/file.rb:124:in `multi_receive_encoded'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/data/elog/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-file-4.1.0/lib/logstash/outputs/file.rb:123:in `multi_receive_encoded'", "/data/elog/logstash/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'", "/data/elog/logstash/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:13:in `multi_receive'", "/data/elog/logstash/logstash-core/lib/logstash/output_delegator.rb:47:in `multi_receive'", "/data/elog/logstash/logstash-core/lib/logstash/pipeline.rb:420:in `output_batch'", "org/jruby/RubyHash.java:1342:in `each'", "/data/elog/logstash/logstash-core/lib/logstash/pipeline.rb:419:in `output_batch'", "/data/elog/logstash/logstash-core/lib/logstash/pipeline.rb:365:in `worker_loop'", "/data/elog/logstash/logstash-core/lib/logstash/pipeline.rb:330:in `start_workers'"]}`

**Comment by andrewvc** [comment]
What behavior would you have preferred @pavel-sbor ?

I think it would be better for the file output to catch the error and retry waiting for disk space to become available later.

Your thoughts?

**Comment by pavel-sbor** [comment]
@andrewvc Yes, I agree with you.
