### ISSUE TITLE
logstash Netflow codec problem for IPFIX

### ISSUE THREAD

**Issue by zzurashvili** [elastic/logstash#8503]
I had logstash 5.2 getting netflow v9 successfully but after I started exporting IPFix (netflow v10) logstash started crashing as soon as It sees template. then I upgraded logstash to logstash-5.6.3 but issues remains.
This is a log file what I'm getting
[2017-10-19T15:51:34,307][WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:34,330][WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:34,333][WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:34,668][WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:35,002][WARN ][logstash.codecs.netflow  ] Can't (yet) decode flowset id 256 from observation domain id 131328, because no template to decode it with has been received. This message will usually go away after 1 minute.
[2017-10-19T15:51:35,121][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `>' for nil:NilClass", "backtrace"=>["(eval):1043:in `initialize'", "org/jruby/RubyArray.java:1613:in `each'", "(eval):1035:in `initialize'", "org/jruby/RubyProc.java:281:in `call'", "(eval):896:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}

looking at tcpdump I see that at 15:51:35 is when logstash got template.
this is my configuration file:
input {
    udp {
        port => 9996
        codec => netflow {
            versions => [9, 10]
            target => ipfix
        }
        type => ipfix
        receive_buffer_bytes => 16777216
        queue_size=> 8000
    }
}
filter ....

I'm sending ipfix flows from gigamon.  again when I had in v9 format everything was working fine.
did anybody have the same issue and found solution?

**Comment by jordansissel** [comment]
Please open this on the https://github.com/logstash-plugins/logstash-codec-netflow/issues repo
