### ISSUE TITLE
Test failure: agent expecting :main pipeline but not found

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash#8546]
https://logstash-ci.elastic.co/job/elastic+logstash+6.0+multijob--ruby-unit-tests/72/console

```
18:29:01 Failures:
18:29:01 
18:29:01   1) LogStash::Agent Agent execute options system pipeline when we have an infinite pipeline and a system pipeline running #running_user_defined_pipelines returns the user defined pipelines
18:29:01      Failure/Error:
18:29:01        wait_for do
18:29:01          subject.with_running_user_defined_pipelines {|pipelines| pipelines.keys }
18:29:01        end.to eq([:main])
18:29:01      
18:29:01        expected: [:main]
18:29:01             got: []
18:29:01      
18:29:01        (compared using ==)
18:29:01      
18:29:01        Diff:
18:29:01        @@ -1,2 +1,2 @@
18:29:01        -[:main]
18:29:01        +[]
18:29:01        
18:29:01      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:13:in `block in handle_matcher'
18:29:01      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:10:in `block in handle_matcher'
18:29:01      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/handler.rb:9:in `handle_matcher'
18:29:01      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `block in to'
18:29:01      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `block in with_wait'
18:29:01      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:28:in `with_wait'
18:29:01      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:44:in `with_wait'
18:29:01      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait/target.rb:30:in `to'
18:29:01      # ./logstash-core/spec/logstash/agent/converge_spec.rb:84:in `block in (root)'
18:29:01      # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
18:29:01      # ./lib/bootstrap/rspec.rb:13:in `<main>'
```

**Comment by kares** [comment]
defunct
