### ISSUE TITLE
undefined method `to_hash' for []:Array

### ISSUE THREAD

**Issue by ebdavison** [elastic/logstash#8627]
Receiving the following logs after adding an http_poller which then parses the results as CSV.  I had 2 of these same http_pollers working and then duplicated one with a new URL and then I get these errors:

[2017-11-08T17:33:58,877][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {"exception"=>"undefined method `to_hash' for []:Array", "backtrace"=>["(eval):1552:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}
[2017-11-08T17:33:58,959][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `to_hash' for []:Array>, :backtrace=>["(eval):1552:in `filter_func'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:398:in `filter_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:379:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:342:in `start_workers'"]}

I have already tried reverting the config changes to where they were before the errors started showing up and no change in the errors being reported.  So, I am at a loss.

**Comment by ebdavison** [comment]
Just upgraded to 5.6.4 after finding reference to bug in 5.6.3 with debug logs enabled.
Problem fixed.
