### ISSUE TITLE
Error during Shutdown in ITs

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8668]
Seeing a few ITs failing for `master` with this one now:

```sh
:runIntegrationTests<===========--> 88% EXECUTING [11m 5s]> :runIntegrationTests[2017-11-14T17:43:44,982][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NoMethodError: undefined method `size' for nil:NilClass>, :backtrace=>["/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline_reporter.rb:90:in `block in worker_states'", "org/jruby/RubyArray.java:2486:in `map'", "org/jruby/RubyEnumerator.java:323:in `each'", "org/jruby/RubyEnumerator.java:501:in `with_index'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline_reporter.rb:88:in `worker_states'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline_reporter.rb:57:in `block in to_hash'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:80:in `inflight_batches'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline_reporter.rb:56:in `to_hash'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline_reporter.rb:51:in `snapshot'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/shutdown_watcher.rb:88:in `pipeline_report_snapshot'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/shutdown_watcher.rb:63:in `block in start'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/interval.rb:20:in `interval'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/shutdown_watcher.rb:59:in `start'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/shutdown_watcher.rb:35:in `block in start'"]}
```

**Comment by original-brownbear** [comment]
Fixed in https://github.com/elastic/logstash/pull/8669
