### ISSUE TITLE
Test Failure: Cannot allocate memory - git ls-files

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#8671]
Test Failure:

```
 Failures:
20:46:41 
20:46:41   1) CLI > logstash-plugin remove without internet connection (linux seccomp wrapper) when no other plugins depends on this plugin successfully remove the plugin
20:46:41      Failure/Error: expect(presence_check.stderr_and_stdout).to match(/ERROR: No plugins found/)
20:46:41 
20:46:41        expected "warning: ignoring JAVA_OPTS= -Xmx1g  -Xss2048k; pass JVM parameters via LS_JAVA_OPTS\nBundler::Gemsp...        <main> at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/lib/pluginmanager/main.rb:48\n" to match /ERROR: No plugins found/
20:46:41        Diff:
20:46:41        @@ -1,2 +1,37 @@
20:46:41        -/ERROR: No plugins found/
20:46:41        +warning: ignoring JAVA_OPTS= -Xmx1g  -Xss2048k; pass JVM parameters via LS_JAVA_OPTS
20:46:41        +Bundler::GemspecError: There was a Errno::ENOMEM while loading logstash-filter-qatest-newer.gemspec: 
20:46:41        +Cannot allocate memory - git ls-files from
20:46:41        +  /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/local_gems/ae226283/logstash-filter-qatest-0.1.1/logstash-filter-qatest-newer.gemspec:13:in `block in eval_gemspec'
20:46:41        +
20:46:41        +                    eval_gemspec at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:412
20:46:41        +  block in load_gemspec_uncached at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:368
20:46:41        +                           chdir at org/jruby/RubyDir.java:323
20:46:41        +                  block in chdir at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/shared_helpers.rb:53
20:46:41        +                 mon_synchronize at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/jruby/lib/ruby/stdlib/monitor.rb:214
20:46:41        +                           chdir at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/shared_helpers.rb:52
20:46:41        +           load_gemspec_uncached at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:363
20:46:41        +                    load_gemspec at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:353
20:46:41        +        block in load_spec_files at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/source/path.rb:135
20:46:41        +                            each at org/jruby/RubyArray.java:1734
20:46:41        +                 load_spec_files at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/source/path.rb:134
20:46:41        +                     local_specs at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/source/path.rb:92
20:46:41        +                           specs at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/source/path.rb:100
20:46:41        +  block in converge_locked_specs at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/definition.rb:539
20:46:41        +                            each at org/jruby/RubyArray.java:1734
20:46:41        +                            each at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/jruby/lib/ruby/stdlib/forwardable.rb:189
20:46:41        +           converge_locked_specs at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/definition.rb:526
20:46:41        +                         resolve at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/definition.rb:187
20:46:41        +                           specs at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/definition.rb:132
20:46:41        +                       specs_for at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/definition.rb:177
20:46:41        +                 requested_specs at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/definition.rb:166
20:46:41        +                 requested_specs at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/environment.rb:18
20:46:41        +                           setup at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/runtime.rb:13
20:46:41        +                           setup at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler.rb:122
20:46:41        +                          setup! at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/lib/bootstrap/bundler.rb:57
20:46:41        +                         execute at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/lib/pluginmanager/list.rb:17
20:46:41        +                             run at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
20:46:41        +                         execute at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
20:46:41        +                             run at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
20:46:41        +                             run at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
20:46:41        +                          <main> at /opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/lib/pluginmanager/main.rb:48
20:46:41      # ./specs/cli/remove_spec.rb:36:in `block in (root)'
20:46:41      # /opt/logstash/build/qa/integration/gems/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
```

Interesting part looks like:

```
Bundler::GemspecError: There was a Errno::ENOMEM while loading logstash-filter-qatest-newer.gemspec: 
20:46:41        +Cannot allocate memory - git ls-files from
```

https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-integration-2/161/console

**Comment by original-brownbear** [comment]
closing in favour of #8676 that identified the deeper reason for the issue :)
