### ISSUE TITLE
Logstash-6.0 not working when config contains nested hash

### ISSUE THREAD

**Issue by sw-jung** [elastic/logstash#8701]
I have developed and been using plugin [logstash-filter-memoize](https://github.com/sw-jung/logstash-filter-memoize).

I have [an issue](https://github.com/sw-jung/logstash-filter-memoize/issues/1) that the plugin does not work in logstash-6, There was a problem at compiling the config file.

The problem occurs when config file contains a nested hash. It was compiled normally until 5.x. Is not support nested hash?

Currently, this seems to be a problem only in my plugin, but I think nested hash is useful structure and it can be used in other plugins.

I would be appreciated if you could give any opinion on this issue

---

- Version: 6.0.0
- Operating System: centos-release-7-4.1708.el7.centos.x86_64
- Config File (if you have sensitive info, please remove it):
```ruby
input {
  file {
    path => "/var/log/logstash/test.log"
    codec => "json"
  }
}

filter {
  memoize {
    key => "%{host}"
    fields => ["host_owner", "host_location"]
    filter_name => "elasticsearch"
    filter_options => {
      query => "host:%{host}"
      index => "known_host"
      fields => { # <-- This is nested hash!
        "host_owner" => "host_owner"
        "host_location" => "host_location"
      }
    }
    ttl => 5
  }
}

output {
  stdout {
    codec => rubydebug
  }
}
```
- Sample Data:
```bash
$ echo '{"host": "test"}' >> /var/log/logstash/test.log
```
- Steps to Reproduce:
1. Install logstash-6.0.0
2. Install logstash-filter-memoize
```bash
$ bin/logstash-plugin install logstash-filter-memoize
```
3. Set config file above
4. Run! and I get following errors:
```
[2017-11-21T23:54:50,419][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"NoMethodError", :message=>"undefined method `get' for {\"host_owner\"=>\"host_owner\", \"host_location\"=>\"host_location\"}:Hash\nDid you mean?  gem", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:210:in `expr'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:202:in `expr'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:133:in `expr'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:98:in `expr_attributes'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:76:in `expr'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:69:in `expr'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:48:in `block in compile'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/compiler/lscl.rb:46:in `compile'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:46:in `compile_ast'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:50:in `compile_imperative'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:54:in `compile_graph'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:12:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/usr/share/logstash/logstash-core/lib/logstash/compiler.rb:11:in `compile_sources'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:107:in `compile_lir'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:215:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:35:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'",
"/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
```

**Comment by andrewvc** [comment]
@sw-jung this does appear to be a bug, we'll definitely look into it. Thanks for the report!

**Comment by Thor77** [comment]
I guess it's the same issue [this](https://discuss.elastic.co/t/pipeline-cannot-start-with-http-poller/108405) forum post is describing.

**Comment by jsvd** [comment]
Also reported [in the https output plugin repo](https://github.com/logstash-plugins/logstash-output-http/issues/77

**Comment by sconrod-tester** [comment]
I am getting the same error for nested hash with the grok filter plugin for logstash in 6.0
[ERROR] 2017-12-01 16:33:08.650 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] agent - Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"translation missing: en.logstash.agent.configuration.invalid_plugin_register", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-filter-date-3.1.8/lib/logstash/filters/date.rb:160:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/filter_delegator.rb:23:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:150:in `plugin'", "(eval):64:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:82:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:215:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:35:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
