### ISSUE TITLE
Don't know how to handle `Java::JavaLang::NullPointerException`

### ISSUE THREAD

**Issue by robin13** [elastic/logstash#8755]
- Version: 6.0.0
- Operating System: Ubuntu 16.04
- Config File (if you have sensitive info, please remove it): See below
- Sample Data: None
- Steps to Reproduce:

Run with this configuration:
```
input {
    stdin {}
}

filter {
    if [foo] != /bar/ {
        mutate {
            add_tag => [ "not_bar" ]
        }
    }
}

output {
    stdout {}
}
```

Results in the critical (logstash does not start) ERROR:

```
[2017-11-29T14:39:08,369][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"Java::JavaLang::NullPointerException", :message=>"", :backtrace=>["org.logstash.config.ir.expression.BinaryBooleanExpression.toRubyString(org/logstash/config/ir/expression/BinaryBooleanExpression.java:46)", "org.logstash.config.ir.expression.Expression.hashSource(org/logstash/config/ir/expression/Expression.java:46)", "org.logstash.config.ir.graph.IfVertex.calculateIndividualHashSource(org/logstash/config/ir/graph/IfVertex.java:98)", "org.logstash.config.ir.graph.Vertex.individualHashSource(org/logstash/config/ir/graph/Vertex.java:198)", "org.logstash.config.ir.graph.Vertex.hashPrefix(org/logstash/config/ir/graph/Vertex.java:170)", "org.logstash.config.ir.graph.Vertex.uniqueHash(org/logstash/config/ir/graph/Vertex.java:147)", "org.logstash.config.ir.graph.Vertex.getId(org/logstash/config/ir/graph/Vertex.java:246)", "java.util.stream.Collectors.lambda$groupingBy$45(java/util/stream/Collectors.java:907)", "java.util.stream.ReduceOps$3ReducingSink.accept(java/util/stream/ReduceOps.java:169)", "java.util.HashMap$KeySpliterator.forEachRemaining(java/util/HashMap.java:1548)", "java.util.stream.AbstractPipeline.copyInto(java/util/stream/AbstractPipeline.java:481)", "java.util.stream.AbstractPipeline.wrapAndCopyInto(java/util/stream/AbstractPipeline.java:471)", "java.util.stream.ReduceOps$ReduceTask.doLeaf(java/util/stream/ReduceOps.java:747)", "java.util.stream.ReduceOps$ReduceTask.doLeaf(java/util/stream/ReduceOps.java:721)", "java.util.stream.AbstractTask.compute(java/util/stream/AbstractTask.java:316)", "java.util.concurrent.CountedCompleter.exec(java/util/concurrent/CountedCompleter.java:731)", "java.util.concurrent.ForkJoinTask.doExec(java/util/concurrent/ForkJoinTask.java:289)", "java.util.concurrent.ForkJoinTask.doInvoke(java/util/concurrent/ForkJoinTask.java:401)", "java.util.concurrent.ForkJoinTask.invoke(java/util/concurrent/ForkJoinTask.java:734)", "java.util.stream.ReduceOps$ReduceOp.evaluateParallel(java/util/stream/ReduceOps.java:714)", "java.util.stream.AbstractPipeline.evaluate(java/util/stream/AbstractPipeline.java:233)", "java.util.stream.ReferencePipeline.collect(java/util/stream/ReferencePipeline.java:499)", "org.logstash.config.ir.graph.Graph.validate(org/logstash/config/ir/graph/Graph.java:280)", "org.logstash.config.ir.PipelineIR.<init>(org/logstash/config/ir/PipelineIR.java:52)", "java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:423)", "org.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/JavaConstructor.java:246)", "org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:1022)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)", "RUBY.compile_sources(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/compiler.rb:30)", "RUBY.compile_lir(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/pipeline.rb:107)", "RUBY.initialize(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/pipeline.rb:49)", "RUBY.initialize(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/pipeline.rb:215)", "org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:1022)", "org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)", "RUBY.execute(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/pipeline_action/create.rb:35)", "RUBY.block in converge_state(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:335)", "RUBY.with_pipelines(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:141)", "RUBY.block in converge_state(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:332)", "org.jruby.RubyArray.each(org/jruby/RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(org/jruby/RubyArray$INVOKER$i$0$0$each.gen)", "RUBY.converge_state(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:319)", "RUBY.block in converge_state_and_update(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:166)", "RUBY.with_pipelines(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:141)", "RUBY.converge_state_and_update(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:164)", "RUBY.execute(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:90)", "RUBY.block in execute(/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/runner.rb:362)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)", "org.jruby.RubyProc.call19(org/jruby/RubyProc.java:273)", "org.jruby.RubyProc$INVOKER$i$0$0$call19.call(org/jruby/RubyProc$INVOKER$i$0$0$call19.gen)", "RUBY.block in initialize(/home/rclarke/elastic/stack/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:289)", "org.jruby.RubyProc.call(org/jruby/RubyProc.java:246)", "java.lang.Thread.run(java/lang/Thread.java:748)"]}
[2017-11-29T14:39:08,376][ERROR][logstash.agent           ] An exception happened when converging configuration {:exception=>LogStash::Error, :message=>"Don't know how to handle `Java::JavaLang::NullPointerException` for `LogStash::PipelineAction::Create/pipeline_id:main`", :backtrace=>["/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/converge_result.rb:27:in `create'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/converge_result.rb:67:in `add'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:347:in `block in converge_state'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/home/rclarke/elastic/stack/logstash-6.0.0/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/home/rclarke/elastic/stack/logstash-6.0.0/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
```

The conditional above was much more complex in production, and to achieve the desired function it should have been `!~` rather than `!=` - a simple typo... but the resulting error message is very unclear and as a result it took a _long_ time to find this one character error in a config file thousands of lines long...  It would be great if this kind of error could be caught more elegantly.

**Comment by original-brownbear** [comment]
@robin13 improved that message a little in #8774, take a look if you want :)

**Comment by original-brownbear** [comment]
improved the situation via #8774

**Comment by robin13** [comment]
Nice! Thank you @original-brownbear
