### ISSUE TITLE
Update the Proxy configuration documentation

### ISSUE THREAD

**Issue by anthony-o** [elastic/logstash#8760]
- Version: 6.0.0
- Operating System: Docker version (docker.elastic.co/logstash/logstash-oss:6.0.0) running on a RHEL7 host
- Steps to Reproduce:

In an environment that needs to pass through a Proxy to get to the web, execute:
```bash
docker run -it --rm docker.elastic.co/logstash/logstash-oss:6.0.0 bash
```
Then in this bash, execute (according to the [documentation](https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#http-proxy)) the following, replacing `$PROXY_URL` with your settings (for example `http://10.10.10.10:5865`):
```bash
export http_proxy=$PROXY_URL
export https_proxy=$PROXY_URL
logstash-plugin install logstash-input-beats
```
Here is the result:
```
Validating logstash-input-beats
Installing logstash-input-beats
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core (6.0.0), and Bundler cannot continue.
Make sure that `gem install logstash-core -v '6.0.0'` succeeds before bundling.
```
That means that either https://github.com/elastic/logstash/issues/6044 is not fixed or https://www.elastic.co/guide/en/logstash/current/working-with-plugins.html#http-proxy does not indicate the right settings for Proxy configuration (the forum also references [such unfixed problems](https://discuss.elastic.co/t/5-1-1-plugin-installation-behind-proxy/70454/12))

**Comment by gaving** [comment]
Not a fix but try adding `--no-verify` to your logstash-plugin install, e.g.:-

```
RUN logstash-plugin install --no-verify logstash-output-elasticsearch
RUN logstash-plugin install --no-verify logstash-input-jdbc
RUN logstash-plugin install --no-verify logstash-filter-translate
```

Seemed to get me further at my end!

**Comment by k1ng87** [comment]
set the proxy with HTTP_PROXY instead of http_proxy...I've seen where uppercase gets picked up and lower case doesn't...just tried with 6.1.1 and it works for me....

**Comment by anthony-o** [comment]
I can confirm that even with `http_proxy`, `https_proxy`, `HTTP_PROXY` & `HTTPS_PROXY` [set](https://github.com/anthony-o/docker-elk_logstash-filter-sparql/blob/426e4280fbc4515a8db5b29e9c67bf2ffa2b1bab/docker-compose.yml#L21) and the following `Dockerfile`:
```
# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash-oss:6.1.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

RUN logstash-plugin install logstash-input-beats
```

I still have:
```
Error Bundler::InstallError, retrying 1/10
An error occurred while installing logstash-core (6.1.1), and Bundler cannot continue.
Make sure that `gem install logstash-core -v '6.1.1'` succeeds before bundling.
```
If I add `DEBUG=1` before the `logstash-plugin` command, here is the log:
```
DEBUG: exec /usr/share/logstash/vendor/jruby/bin/jruby /usr/share/logstash/lib/pluginmanager/main.rb install logstash-input-beats
Looking if package named: logstash-input-beats exists at https://artifacts.elastic.co/downloads/logstash-plugins/logstash-input-beats/logstash-input-beats-6.1.1.zip
Package not found at: https://artifacts.elastic.co/downloads/logstash-plugins/logstash-input-beats/logstash-input-beats-6.1.1.zip
Validating logstash-input-beats
Installing logstash-input-beats
Resolving dependencies............................
Using addressable 2.3.8
0:  addressable (2.3.8) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/addressable-2.3.8.gemspec
Using cabin 0.9.0
0:  cabin (0.9.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/cabin-0.9.0.gemspec
Using arr-pm 0.0.10
0:  arr-pm (0.0.10) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/arr-pm-0.0.10.gemspec
Using atomic 1.1.99
0:  atomic (1.1.99) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/atomic-1.1.99-java.gemspec
Using avl_tree 1.2.1
0:  avl_tree (1.2.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/avl_tree-1.2.1.gemspec
Using awesome_print 1.8.0
0:  awesome_print (1.8.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/awesome_print-1.8.0.gemspec
Using jmespath 1.3.1
0:  jmespath (1.3.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/jmespath-1.3.1.gemspec
Using aws-sdk-core 2.3.22
0:  aws-sdk-core (2.3.22) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/aws-sdk-core-2.3.22.gemspec
Using aws-sdk-resources 2.3.22
0:  aws-sdk-resources (2.3.22) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/aws-sdk-resources-2.3.22.gemspec
Using aws-sdk 2.3.22
0:  aws-sdk (2.3.22) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/aws-sdk-2.3.22.gemspec
Using json 1.8.6
0:  json (1.8.6) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/json-1.8.6-java.gemspec
Using nokogiri 1.8.1
0:  nokogiri (1.8.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/nokogiri-1.8.1-java.gemspec
Using aws-sdk-v1 1.67.0
0:  aws-sdk-v1 (1.67.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/aws-sdk-v1-1.67.0.gemspec
Using backports 3.10.3
0:  backports (3.10.3) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/backports-3.10.3.gemspec
Using bindata 2.4.1
0:  bindata (2.4.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/bindata-2.4.1.gemspec
Using buftok 0.2.0
0:  buftok (0.2.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/buftok-0.2.0.gemspec
Using builder 3.2.3
0:  builder (3.2.3) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/builder-3.2.3.gemspec
Using ffi 1.9.18
0:  ffi (1.9.18) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/ffi-1.9.18-java.gemspec
Using childprocess 0.8.0
0:  childprocess (0.8.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/childprocess-0.8.0.gemspec
Using numerizer 0.1.1
0:  numerizer (0.1.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/numerizer-0.1.1.gemspec
Using chronic_duration 0.10.6
0:  chronic_duration (0.10.6) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/chronic_duration-0.10.6.gemspec
Using clamp 0.6.5
0:  clamp (0.6.5) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/clamp-0.6.5.gemspec
Using coderay 1.1.2
0:  coderay (1.1.2) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/coderay-1.1.2.gemspec
Using concurrent-ruby 1.0.5
0:  concurrent-ruby (1.0.5) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/concurrent-ruby-1.0.5-java.gemspec
Using unf 0.1.4
0:  unf (0.1.4) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/unf-0.1.4-java.gemspec
Using domain_name 0.5.20170404
0:  domain_name (0.5.20170404) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/domain_name-0.5.20170404.gemspec
Using dotenv 2.2.1
0:  dotenv (2.2.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/dotenv-2.2.1.gemspec
Using edn 1.1.1
0:  edn (1.1.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/edn-1.1.1.gemspec
Using multi_json 1.12.2
0:  multi_json (1.12.2) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/multi_json-1.12.2.gemspec
Using elasticsearch-api 5.0.4
0:  elasticsearch-api (5.0.4) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/elasticsearch-api-5.0.4.gemspec
Using multipart-post 2.0.0
0:  multipart-post (2.0.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/multipart-post-2.0.0.gemspec
Using faraday 0.9.2
0:  faraday (0.9.2) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/faraday-0.9.2.gemspec
Using elasticsearch-transport 5.0.4
0:  elasticsearch-transport (5.0.4) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/elasticsearch-transport-5.0.4.gemspec
Using elasticsearch 5.0.4
0:  elasticsearch (5.0.4) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/elasticsearch-5.0.4.gemspec
Using equalizer 0.0.10
0:  equalizer (0.0.10) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/equalizer-0.0.10.gemspec
Using filesize 0.0.4
0:  filesize (0.0.4) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/filesize-0.0.4.gemspec
Using filewatch 0.9.0
0:  filewatch (0.9.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/filewatch-0.9.0.gemspec
Using fpm 1.3.3
0:  fpm (1.3.3) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/fpm-1.3.3.gemspec
Using gelfd 0.2.0
0:  gelfd (0.2.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/gelfd-0.2.0.gemspec
Using gems 0.8.3
0:  gems (0.8.3) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/gems-0.8.3.gemspec
Using hitimes 1.2.6
0:  hitimes (1.2.6) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/hitimes-1.2.6-java.gemspec
Using http-cookie 1.0.3
0:  http-cookie (1.0.3) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/http-cookie-1.0.3.gemspec
Using http-form_data 1.0.1
0:  http-form_data (1.0.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/http-form_data-1.0.1.gemspec
Using http_parser.rb 0.6.0
0:  http_parser.rb (0.6.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/http_parser.rb-0.6.0-java.gemspec
Using http 0.9.9
0:  http (0.9.9) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/http-0.9.9.gemspec
Using i18n 0.6.9
0:  i18n (0.6.9) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/i18n-0.6.9.gemspec
Using insist 1.0.0
0:  insist (1.0.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/insist-1.0.0.gemspec
Using jar-dependencies 0.3.11
0:  jar-dependencies (0.3.11) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/jar-dependencies-0.3.11.gemspec
Using jls-grok 0.11.4
0:  jls-grok (0.11.4) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/jls-grok-0.11.4.gemspec
Using jls-lumberjack 0.0.26
0:  jls-lumberjack (0.0.26) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/jls-lumberjack-0.0.26.gemspec
Using jrjackson 0.4.4
0:  jrjackson (0.4.4) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/jrjackson-0.4.4-java.gemspec
Using jruby-openssl 0.9.21
0:  jruby-openssl (0.9.21) from /usr/share/logstash/vendor/jruby/lib/ruby/gems/shared/specifications/default/jruby-openssl-0.9.21-java.gemspec
Using jruby-stdin-channel 0.2.0
0:  jruby-stdin-channel (0.2.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/jruby-stdin-channel-0.2.0-java.gemspec
Using manticore 0.6.1
0:  manticore (0.6.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/manticore-0.6.1-java.gemspec
Using minitar 0.6.1
0:  minitar (0.6.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/minitar-0.6.1.gemspec
Using method_source 0.8.2
0:  method_source (0.8.2) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/method_source-0.8.2.gemspec
Using slop 3.6.0
0:  slop (3.6.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/slop-3.6.0.gemspec
Using spoon 0.0.6
0:  spoon (0.0.6) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/spoon-0.0.6.gemspec
Using pry 0.10.4
0:  pry (0.10.4) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/pry-0.10.4-java.gemspec
Using puma 2.16.0
0:  puma (2.16.0) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/puma-2.16.0-java.gemspec
Using rack 1.6.6
0:  rack (1.6.6) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/rack-1.6.6.gemspec
Using ruby-maven-libs 3.3.9
0:  ruby-maven-libs (3.3.9) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/ruby-maven-libs-3.3.9.gemspec
Using ruby-maven 3.3.12
0:  ruby-maven (3.3.12) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/ruby-maven-3.3.12.gemspec
Using rubyzip 1.2.1
0:  rubyzip (1.2.1) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/rubyzip-1.2.1.gemspec
Using rack-protection 1.5.3
0:  rack-protection (1.5.3) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/rack-protection-1.5.3.gemspec
Using tilt 2.0.8
0:  tilt (2.0.8) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/tilt-2.0.8.gemspec
Using sinatra 1.4.8
0:  sinatra (1.4.8) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/sinatra-1.4.8.gemspec
Using stud 0.0.23
0:  stud (0.0.23) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/stud-0.0.23.gemspec
Using thread_safe 0.3.6
0:  thread_safe (0.3.6) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/thread_safe-0.3.6-java.gemspec
Using polyglot 0.3.5
0:  polyglot (0.3.5) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/polyglot-0.3.5.gemspec
Using treetop 1.4.15
0:  treetop (1.4.15) from /usr/share/logstash/vendor/bundle/jruby/2.3.0/specifications/treetop-1.4.15.gemspec
  jar dependencies for logstash-core-6.1.1-java.gemspec . . .
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.11/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.11/lib/jars/gemspec_pom.rb) has 1 error
[ERROR]     Non-parseable POM /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.11/lib/jars/gemspec_pom.rb: only whitespace content allowed before start tag and not # (position: START_DOCUMENT seen #... @1:1)  @ line 1, column 1 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/ModelParseException

Errno::ENOENT: No such file or directory - /usr/share/logstash/logstash-core/deps.lst
org/jruby/RubyIO.java:3600:in `read'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.11/lib/jars/installer.rb:73:in `load_from_maven'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.11/lib/jars/installer.rb:239:in `install_dependencies'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.11/lib/jars/installer.rb:226:in `do_install'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/jar-dependencies-0.3.11/lib/jars/installer.rb:172:in `vendor_jars'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/jars/post_install_hook.rb:28:in `block in (root)'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/source/path.rb:215:in `block in run_hooks'
org/jruby/RubyArray.java:1734:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/source/path.rb:214:in `run_hooks'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/source/path.rb:195:in `block in generate_bin'
org/jruby/RubyDir.java:323:in `chdir'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/shared_helpers.rb:53:in `block in chdir'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/monitor.rb:214:in `mon_synchronize'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/shared_helpers.rb:52:in `chdir'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/source/path.rb:189:in `generate_bin'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/source/path.rb:73:in `install'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:107:in `install_gem_from_spec'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:269:in `block in install_sequentially'
org/jruby/RubyArray.java:1734:in `each'
/usr/share/logstash/vendor/jruby/lib/ruby/stdlib/forwardable.rb:189:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:268:in `install_sequentially'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:90:in `run'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:18:in `install'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/cli/install.rb:80:in `run'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/cli.rb:155:in `install'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/cli.rb:10:in `start'
/usr/share/logstash/lib/bootstrap/bundler.rb:155:in `execute_bundler'
/usr/share/logstash/lib/bootstrap/bundler.rb:116:in `invoke!'
/usr/share/logstash/lib/pluginmanager/install.rb:141:in `install_gems_list!'
/usr/share/logstash/lib/pluginmanager/install.rb:60:in `execute'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11:in `execute'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
/usr/share/logstash/lib/pluginmanager/main.rb:48:in `<main>'
Bundler::InstallError: An error occurred while installing logstash-core (6.1.1), and Bundler cannot continue.
Make sure that `gem install logstash-core -v '6.1.1'` succeeds before bundling.
          install_gem_from_spec at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:145
  block in install_sequentially at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:269
                           each at org/jruby/RubyArray.java:1734
                           each at /usr/share/logstash/vendor/jruby/lib/ruby/stdlib/forwardable.rb:189
           install_sequentially at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:268
                            run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:90
                        install at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/installer.rb:18
                            run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/cli/install.rb:80
                        install at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/cli.rb:155
                            run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/command.rb:27
                 invoke_command at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:126
                       dispatch at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor.rb:359
                          start at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/base.rb:440
                          start at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bundler-1.9.10/lib/bundler/cli.rb:10
                execute_bundler at /usr/share/logstash/lib/bootstrap/bundler.rb:155
                        invoke! at /usr/share/logstash/lib/bootstrap/bundler.rb:116
             install_gems_list! at /usr/share/logstash/lib/pluginmanager/install.rb:141
                        execute at /usr/share/logstash/lib/pluginmanager/install.rb:60
                            run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
                        execute at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/subcommand/execution.rb:11
                            run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67
                            run at /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132
                         <main> at /usr/share/logstash/lib/pluginmanager/main.rb:48
ERROR: Service 'logstash' failed to build: The command '/bin/sh -c DEBUG=1 logstash-plugin install logstash-input-beats' returned a non-zero code: 1
```
```

**Comment by anthony-o** [comment]
I found a workaround, inspired by [another one I discovered](https://discuss.elastic.co/t/the-source-does-not-contain-any-versions-of-logstash-when-trying-to-create-a-logstash-filter-plugin/110399/4?u=anthony-o): you have to [remove empty `<username></username>` and `<password></password>` from the `~/.m2/settings.xml`](https://github.com/anthony-o/docker-elk_logstash-filter-sparql/blob/1dbb7ad0031f9001455696e21001e9c69eec2bd6/logstash/Dockerfile#L7).

So here is [my final `Dockerfile`](https://github.com/anthony-o/docker-elk_logstash-filter-sparql/blob/1dbb7ad0031f9001455696e21001e9c69eec2bd6/logstash/Dockerfile) beginning:
```
# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash-oss:6.1.1

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

RUN DEBUG=1 logstash-plugin install logstash-input-beats || (sed -i '/username><\//d' ~/.m2/settings.xml && sed -i '/password><\//d' ~/.m2/settings.xml && logstash-plugin install logstash-input-beats)
```
