### ISSUE TITLE
LIR Array <- String error prevents Logstash 6.x from starting.

### ISSUE THREAD

**Issue by jakelandis** [elastic/logstash#8827]
The following configuration will prevent Logstash 6.x from starting. 
```
filter {
  mutate {
        remove_field => ["foo"]
        remove_field => "bar"
  } 
}
```
with the following error (from 6.0.1 release):
```
[2017-12-11T15:12:15,976][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"TypeError", :message=>"no implicit conversion of String into Array", :backtrace=>["/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler/lscl.rb:117:in `block in expr_attributes'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyEnumerable.java:936:in `inject'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler/lscl.rb:98:in `expr_attributes'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler/lscl.rb:76:in `expr'", "org/jruby/RubyArray.java:2486:in `map'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler/lscl.rb:69:in `expr'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler/lscl.rb:48:in `block in compile'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler/lscl.rb:46:in `compile'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler.rb:46:in `compile_ast'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler.rb:50:in `compile_imperative'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler.rb:54:in `compile_graph'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler.rb:12:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/compiler.rb:11:in `compile_sources'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:107:in `compile_lir'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/pipeline.rb:215:in `initialize'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/pipeline_action/create.rb:35:in `execute'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/Users/jake/workspace/releases/logstash-6.0.1/logstash-core/lib/logstash/runner.rb:362:in `block in execute'", "/Users/jake/workspace/releases/logstash-6.0.1/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
```

**Comment by jakelandis** [comment]
Related: https://github.com/elastic/logstash/pull/8597
