### ISSUE TITLE
Configuration parser fails when encountering an escaped backslash

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#8843]
Regardless of the value of `config.support_escapes`, the following filter section will raise an error:

```
filter { mutate { split => { "message" => "\\" } } }
```

```
/tmp/logstash-6.1.0 % bin/logstash -e 'filter { mutate { split => { "message" => "\\" } } }'
Sending Logstash's logs to /tmp/logstash-6.1.0/logs which is now configured via log4j2.properties
[2017-12-15T13:27:32,757][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/tmp/logstash-6.1.0/modules/fb_apache/configuration"}
[2017-12-15T13:27:32,780][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/tmp/logstash-6.1.0/modules/netflow/configuration"}
[2017-12-15T13:27:33,083][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2017-12-15T13:27:33,862][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.0"}
[2017-12-15T13:27:34,613][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2017-12-15T13:27:35,071][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::ConfigurationError", :message=>"Expected one of \\\", \", any character at line 3, column 53 (byte 128) after filter { mutate { split => { \"message\" => \"\\\\\" } } }", :backtrace=>["/tmp/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:42:in `compile_imperative'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:50:in `compile_graph'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:12:in `block in compile_sources'", "org/jruby/RubyArray.java:2486:in `map'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/compiler.rb:11:in `compile_sources'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/pipeline.rb:51:in `initialize'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/pipeline.rb:171:in `initialize'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/tmp/logstash-6.1.0/logstash-core/lib/logstash/runner.rb:343:in `block in execute'", "/tmp/logstash-6.1.0/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
```

Migrated from https://github.com/logstash-plugins/logstash-filter-mutate/issues/109

**Comment by original-brownbear** [comment]
Interesting, let me see what I can do here :)

**Comment by holiiveira** [comment]
Any news on that? Is there any workaround?

**Comment by fatalglitch** [comment]
Is there any update on this issue? I'm trying to split a "domain\username" field coming off a firewall and found this after spending a decent amount of time troubleshooting.

**Comment by holiiveira** [comment]
You can use [gsub](https://www.elastic.co/guide/en/logstash/current/plugins-filters-mutate.html#plugins-filters-mutate-gsub) as an alternative:

Chang `\` to `/`:
```
mutate {
  gsub => [ "[user]", "[\\]", "/" ]
}
```

Then do the split:

```
mutate {
  split => [ "[user]", "/" ]
}
```

That solved my problem.

**Comment by BlakeWills** [comment]
Anything happening with this? The gsub workaround doesn't work for us.

**Comment by VimCommando** [comment]
### Getting a split on \ without gsub

A workaround I found was to rely on how Logstash can fall back to a default value when evaluating environment variables:
https://www.elastic.co/guide/en/logstash/current/environment-variables.html

So instead of escaping the backslash, you use an environment variable that doesn't exist with a `\` default:
```
filter {
  split {
    field => "user"
    terminator => "${TERMINATOR:\}"
  }
}
```
In this case `TERMINATOR` can be any name, as long as it is not defined in Logstash's environment variables. Since it will not have a value, the backslash `\` default gets used.

### Is split the right filter?

A note if you are trying to break apart the `domain\username` that the split filter is not the right one. The output from split is a unique _event_ for each value, not separate _fields_ added to the original event.

Using split on `domain\username` will give you **two** events: one for `domain` and a second for with `username`.

```
# split input: {"user": "localhost/reno"}
{
  "user": "localhost"
}
{
  "user": "reno"
}
```
Instead, you want a dissect filter:
https://www.elastic.co/guide/en/logstash/current/plugins-filters-dissect.html

```
filter {
  dissect {
    mapping => {
      "user" => "%{domain}\%{username}"
    }
  }
}
```

This will add separate `domain` and `username` fields on the same event, based on the value in the `user` field.

```
# dissect input: {"user": "localhost/reno"}
{
  "user": "localhost\reno",
  "username": "reno",
  "domain": "localhost"
}
```

**Comment by gwsales** [comment]
Is there a ruby equivalent for this? The gsub workaround doesn't work for me either.

**Comment by gwsales** [comment]
Ruby workaround:
```
ruby {
    code => '
          object = event.get("path_object")
          values = object .split("\\")
          event.set("values", values)
    '
}
```
