### ISSUE TITLE
java_pipeline_spec.rb "with multiple outputs correctly distributes events" Fails Randomly

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#8883]
The new spec I added in #8691 seems to be a little flaky (I have not seen this on Jenkins yet, but locally it failed twice for me now).
It seems at times this line:

```rb
      expect(output.events.size).to eq(60)
```

only sees `59` events. Will track this down and fix it :) 

Failure:

```sh

expected: 60
     got: 59

(compared using ==)

./logstash-core/spec/logstash/java_pipeline_spec.rb:682:in `block in (root)'
./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
./lib/bootstrap/rspec.rb:13:in `<main>'
-e:1:in `<main>'
```

**Comment by original-brownbear** [comment]
fixed by #8884
