### ISSUE TITLE
Test failure: secret_store spec failing

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#8973]
https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-integration-2/233/console

```
09:43:50 Failures:
09:43:50 
09:43:50   1) Test that Logstash expands secret store variables from settings
09:43:50      Failure/Error: expect(result).not_to be_nil
09:43:50 
09:43:50        expected: not nil
09:43:50             got: nil
09:43:50      # ./specs/secret_store_spec.rb:60:in `block in (root)'
09:43:50      # /opt/logstash/build/qa/integration/gems/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
09:43:50      # /opt/logstash/build/qa/integration/gems/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
09:43:50      # /opt/logstash/build/qa/integration/gems/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
09:43:50      # /opt/logstash/build/qa/integration/gems/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
09:43:50      # ./specs/secret_store_spec.rb:58:in `block in (root)'
09:43:50      # /opt/logstash/build/qa/integration/gems/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in (root)'
09:43:50 
09:43:50 Finished in 10 minutes 35 seconds (files took 4.23 seconds to load)
09:43:50 21 examples, 1 failure
09:43:50 
09:43:50 Failed examples:
09:43:50 
09:43:50 rspec ./specs/secret_store_spec.rb:53 # Test that Logstash expands secret store variables from settings
09:43:50 
09:43:50 Randomized with seed 36621
```

**Comment by colinsurprenant** [comment]
@jakelandis I think you were looking into this?

**Comment by jakelandis** [comment]
@colinsurprenant - fixes the issue: https://github.com/elastic/logstash/pull/8961 it just merged and landed slightly after this failure.  Closing this, please re-open if you see this again.

**Comment by original-brownbear** [comment]
This isn't fixed I think:

```
12:48:28 ERROR: Failed to load settings file from "path.settings". Aborting... path.setting=/tmp/studtmp-06ada286b39a2dc1bba946d7e3dbb54ba620e3a95bbffc26233e147d6d86, exception=Java::OrgLogstashSecretStore::SecretStoreException::AccessException, message=>Can not access Logstash keystore at /tmp/studtmp-06ada286b39a2dc1bba946d7e3dbb54ba620e3a95bbffc26233e147d6d86/logstash.keystore. Please verify correct file permissions and keystore password.
12:48:28 [ERROR] 2018-04-11 12:48:28.938 [main] Logstash - java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
12:48:30     with the wrong password when variables are in settings
12:48:30 Tearing down services
12:48:31 
12:48:31 Failures:
12:48:31 
12:48:31   1) Test that Logstash expands secret store variables from settings
12:48:31      Failure/Error: expect(result).not_to be_nil
12:48:31 
12:48:31        expected: not nil
12:48:31             got: nil
12:48:31      # ./specs/secret_store_spec.rb:60:in `block in /opt/logstash/qa/integration/specs/secret_store_spec.rb'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
12:48:31      # ./specs/secret_store_spec.rb:58:in `block in (root)'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
12:48:31 
12:48:31   2) Test that Logstash expands secret store variables from config
12:48:31      Failure/Error: expect(IO.read(File.join(File.join(test_path, "mypath"), "logstash_secretstore_test.output")).gsub("\n", "")).to eq("Hello world! mytag1,mytag2.mytag3" * 10)
12:48:31 
12:48:31      Errno::ENOENT:
12:48:31        No such file or directory - /tmp/studtmp-495e38baadbc4c0e50c15d3db71871eb01696fa2f6ae36457296330ed649/mypath/logstash_secretstore_test.output
12:48:31      # ./specs/secret_store_spec.rb:49:in `block in /opt/logstash/qa/integration/specs/secret_store_spec.rb'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
12:48:31      # ./specs/secret_store_spec.rb:47:in `block in (root)'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
12:48:31 
12:48:31   3) Test that Logstash will start with the wrong password and variables are NOT in settings
12:48:31      Failure/Error: expect(@logstash.exited?).to be(true)
12:48:31 
12:48:31        expected true
12:48:31             got false
12:48:31      # ./specs/secret_store_spec.rb:88:in `block in /opt/logstash/qa/integration/specs/secret_store_spec.rb'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:79:in `block in try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:95:in `block in try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:91:in `try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/stud-0.0.23/lib/stud/try.rb:123:in `try'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/logstash-devutils-1.3.5-java/lib/logstash/devutils/rspec/logstash_helpers.rb:18:in `try'
12:48:31      # ./specs/secret_store_spec.rb:87:in `block in (root)'
12:48:31      # /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/build/qa/integration/vendor/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
12:48:31 
12:48:31 Finished in 16 minutes 56 seconds (files took 6.14 seconds to load)
12:48:31 21 examples, 3 failures
12:48:31 
12:48:31 Failed examples:
12:48:31 
12:48:31 rspec ./specs/secret_store_spec.rb:53 # Test that Logstash expands secret store variables from settings
12:48:31 rspec ./specs/secret_store_spec.rb:41 # Test that Logstash expands secret store variables from config
12:48:31 rspec ./specs/secret_store_spec.rb:82 # Test that Logstash will start with the wrong password and variables are NOT in settings
```

still happening in https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-integration-pq-2/80/console
