### ISSUE TITLE
Test Failure: 6.X intermittent fails in logstash-core/spec/conditionals_spec.rb

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#9033]
[Jenkins Console](https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/309/os=debian/console)

Sometimes `subject` (event expected) is nil, doesn't have the correct tags or is an array.

```
12:17:58       1) conditionals in filter operators 7 == 7 "{"message":3}" when processed
12:17:58          Failure/Error: sample_one("message" => 3) {expect(subject.get("tags")).to include("success")}
12:17:58          
12:17:58          NoMethodError:
12:17:58            undefined method `get' for nil:NilClass
...
12:17:58          # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/debian/logstash-core/spec/conditionals_spec.rb:279:in `block in (root)'
```
And
```
12:17:58       2) conditionals in filter operators [message] == 5 "{"message":5}" when processed
12:17:58          Failure/Error: sample_one("message" => 5) {expect(subject.get("tags")).to include("success")}
12:17:58            expected ["failure"] to include "success"
12:17:58          # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/debian/logstash-core/spec/conditionals_spec.rb:268:in `block in (root)'
```
And
```
12:17:58       3) conditionals in filter operators [message] == 5 "{"message":3}" when processed
12:17:58          Failure/Error: sample_one("message" => 3) {expect(subject.get("tags")).to include("failure")}
12:17:58          
12:17:58          NoMethodError:
12:17:58            undefined method `get' for [#<LogStash::Event:0x68241759>, #<LogStash::Event:0x2218a73d>]:Array
...
12:17:58          # /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/debian/logstash-core/spec/conditionals_spec.rb:269:in `block in (root)'
```

**Comment by original-brownbear** [comment]
@guyboertje this is fixed by #9024

**Comment by guyboertje** [comment]
Great.

**Comment by original-brownbear** [comment]
#9024 merged => fixed :)
