### ISSUE TITLE
Test Failure, 6.X unix-compatibility oraclelinux only, "Wiping out workspace" fails

### ISSUE THREAD

**Issue by guyboertje** [elastic/logstash#9043]
[Jenkins Console](https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob-unix-compatibility/os=oraclelinux/310/console)

The **previous job 309** introduced some file permissions that made this job fail when trying to delete files in the workspace. The files are the core test resources e.g. `log4j2-test1.xml`

```
18:59:35 Wiping out workspace first.
18:59:35 java.nio.file.FileSystemException: /var/lib/jenkins/workspace/elastic+logstash+6.x+multijob-unix-compatibility/os/oraclelinux/logstash-core/build/resources/test/log4j2-test1.xml: Operation not permitted
18:59:35 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
18:59:35 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
18:59:35 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
18:59:35 	at sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:238)
18:59:35 	at sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:260)
18:59:35 	at java.nio.file.Files.setPosixFilePermissions(Files.java:2045)
18:59:35 	at hudson.Util.makeWritable(Util.java:303)
18:59:35 	at hudson.Util.tryOnceDeleteFile(Util.java:263)
18:59:35 	at hudson.Util.deleteFile(Util.java:238)
```

**Comment by jakelandis** [comment]
I jumped on the box and manually wiped the workspace.  I am pretty sure that is due to some manual testing on this box under an incorrect user.  

Optimistically closing...please re-open if this shows back up.
