### ISSUE TITLE
Test Failure: no implicit conversion from nil to integer on WrappedWriteClient

### ISSUE THREAD

**Issue by robbavey** [elastic/logstash#9098]
Intermittent test failures on [6.x](https://logstash-ci.elastic.co/job/elastic+logstash+6.x+multijob--ruby-unit-tests/278/console) and [master](https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-unix-compatibility/os=fedora/384/console):

```
 Failures:
07:23:01 
07:23:01       1) LogStash::WrappedWriteClient WrappedAckedQueue pushes batch to the `WriteClient`
07:23:01          Failure/Error: batch_size = read_client.read_batch.size
07:23:01          
07:23:01          TypeError:
07:23:01            no implicit conversion from nil to integer
07:23:01          Shared Example Group: "queue tests" called from ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:123
07:23:01          # org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java:127:in `read_batch'
07:23:01          # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:54:in `read_batch'
07:23:01          # org/logstash/ext/JrubyAckedReadBatchExt.java:42:in `initialize'
07:23:01          # org/logstash/ext/JrubyAckedReadClientExt.java:113:in `read_batch'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:26:in `block in threaded_read_client'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:22:in `block in threaded_read_client'
07:23:01 
07:23:01       2) LogStash::WrappedWriteClient WrappedAckedQueue pushes single event to the `WriteClient`
07:23:01          Failure/Error: batch_size = read_client.read_batch.size
07:23:01          
07:23:01          TypeError:
07:23:01            no implicit conversion from nil to integer
07:23:01          Shared Example Group: "queue tests" called from ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:123
07:23:01          # org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java:127:in `read_batch'
07:23:01          # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:54:in `read_batch'
07:23:01          # org/logstash/ext/JrubyAckedReadBatchExt.java:42:in `initialize'
07:23:01          # org/logstash/ext/JrubyAckedReadClientExt.java:113:in `read_batch'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:26:in `block in threaded_read_client'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:22:in `block in threaded_read_client'
07:23:01 
07:23:01       3) LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics records pipeline level `in`
07:23:01          Failure/Error: batch_size = read_client.read_batch.size
07:23:01          
07:23:01          TypeError:
07:23:01            no implicit conversion from nil to integer
07:23:01          Shared Example Group: "queue tests" called from ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:123
07:23:01          # org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java:127:in `read_batch'
07:23:01          # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:54:in `read_batch'
07:23:01          # org/logstash/ext/JrubyAckedReadBatchExt.java:42:in `initialize'
07:23:01          # org/logstash/ext/JrubyAckedReadClientExt.java:113:in `read_batch'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:26:in `block in threaded_read_client'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:22:in `block in threaded_read_client'
07:23:01 
07:23:01       4) LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics record input `out`
07:23:01          Failure/Error: batch_size = read_client.read_batch.size
07:23:01          
07:23:01          TypeError:
07:23:01            no implicit conversion from nil to integer
07:23:01          Shared Example Group: "queue tests" called from ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:123
07:23:01          # org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java:127:in `read_batch'
07:23:01          # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:54:in `read_batch'
07:23:01          # org/logstash/ext/JrubyAckedReadBatchExt.java:42:in `initialize'
07:23:01          # org/logstash/ext/JrubyAckedReadClientExt.java:113:in `read_batch'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:26:in `block in threaded_read_client'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:22:in `block in threaded_read_client'
07:23:01 
07:23:01       5) LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics records instance level events `in`
07:23:01          Failure/Error: batch_size = read_client.read_batch.size
07:23:01          
07:23:01          TypeError:
07:23:01            no implicit conversion from nil to integer
07:23:01          Shared Example Group: "queue tests" called from ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:123
07:23:01          # org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java:127:in `read_batch'
07:23:01          # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:54:in `read_batch'
07:23:01          # org/logstash/ext/JrubyAckedReadBatchExt.java:42:in `initialize'
07:23:01          # org/logstash/ext/JrubyAckedReadClientExt.java:113:in `read_batch'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:26:in `block in threaded_read_client'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:22:in `block in threaded_read_client'
07:23:01 
07:23:01       6) LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics recording of the duration of pushing to the queue records at the `pipeline` level
07:23:01          Failure/Error: batch_size = read_client.read_batch.size
07:23:01          
07:23:01          TypeError:
07:23:01            no implicit conversion from nil to integer
07:23:01          Shared Example Group: "queue tests" called from ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:123
07:23:01          # org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java:127:in `read_batch'
07:23:01          # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:54:in `read_batch'
07:23:01          # org/logstash/ext/JrubyAckedReadBatchExt.java:42:in `initialize'
07:23:01          # org/logstash/ext/JrubyAckedReadClientExt.java:113:in `read_batch'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:26:in `block in threaded_read_client'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:22:in `block in threaded_read_client'
07:23:01 
07:23:01       7) LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics recording of the duration of pushing to the queue records at the `plugin level
07:23:01          Failure/Error: batch_size = read_client.read_batch.size
07:23:01          
07:23:01          TypeError:
07:23:01            no implicit conversion from nil to integer
07:23:01          Shared Example Group: "queue tests" called from ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:123
07:23:01          # org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java:127:in `read_batch'
07:23:01          # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:54:in `read_batch'
07:23:01          # org/logstash/ext/JrubyAckedReadBatchExt.java:42:in `initialize'
07:23:01          # org/logstash/ext/JrubyAckedReadClientExt.java:113:in `read_batch'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:26:in `block in threaded_read_client'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:22:in `block in threaded_read_client'
07:23:01 
07:23:01       8) LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics recording of the duration of pushing to the queue records at the `global events` level
07:23:01          Failure/Error: batch_size = read_client.read_batch.size
07:23:01          
07:23:01          TypeError:
07:23:01            no implicit conversion from nil to integer
07:23:01          Shared Example Group: "queue tests" called from ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:123
07:23:01          # org/logstash/ackedqueue/ext/JRubyAckedQueueExt.java:127:in `read_batch'
07:23:01          # ./logstash-core/lib/logstash/util/wrapped_acked_queue.rb:54:in `read_batch'
07:23:01          # org/logstash/ext/JrubyAckedReadBatchExt.java:42:in `initialize'
07:23:01          # org/logstash/ext/JrubyAckedReadClientExt.java:113:in `read_batch'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:26:in `block in threaded_read_client'
07:23:01          # ./logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb:22:in `block in threaded_read_client'
07:23:01 
07:23:01     Finished in 5 minutes 14 seconds (files took 11.33 seconds to load)
07:23:01     2974 examples, 8 failures, 4 pending
07:23:01 
07:23:01     Failed examples:
07:23:01 
07:23:01     rspec './logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb[1:2:2]' # LogStash::WrappedWriteClient WrappedAckedQueue pushes batch to the `WriteClient`
07:23:01     rspec './logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb[1:2:1]' # LogStash::WrappedWriteClient WrappedAckedQueue pushes single event to the `WriteClient`
07:23:01     rspec './logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb[1:2:3:2]' # LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics records pipeline level `in`
07:23:01     rspec './logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb[1:2:3:3]' # LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics record input `out`
07:23:01     rspec './logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb[1:2:3:1]' # LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics records instance level events `in`
07:23:01     rspec './logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb[1:2:3:4:2]' # LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics recording of the duration of pushing to the queue records at the `pipeline` level
07:23:01     rspec './logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb[1:2:3:4:3]' # LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics recording of the duration of pushing to the queue records at the `plugin level
07:23:01     rspec './logstash-core/spec/logstash/instrument/wrapped_write_client_spec.rb[1:2:3:4:1]' # LogStash::WrappedWriteClient WrappedAckedQueue recorded metrics recording of the duration of pushing to the queue records at the `global events` level
07:23:01 
07:23:01     Randomized with seed 38730
```

**Comment by original-brownbear** [comment]
waiting on https://github.com/elastic/logstash/pull/9080 here

**Comment by original-brownbear** [comment]
This should've been fixed by https://github.com/elastic/logstash/pull/9080/files#diff-3aad96c704f13ff7cfc1905b4a172948R30 now :) Closing here.
