### ISSUE TITLE
Docker logstash + plugins-inputs-google_pubsub don't work

### ISSUE THREAD

**Issue by itielshwartz** [elastic/logstash#9150]
I'm trying to use logstash + the google pub sub plugin but fail...
Guide i follow:
https://www.elastic.co/guide/en/logstash/current/plugins-inputs-google_pubsub.html#plugins-inputs-google_pubsub

My docker file:
```
FROM docker.elastic.co/logstash/logstash-oss:6.2.1
RUN bin/logstash-plugin install logstash-input-google_pubsub
ADD pipeline/ /usr/share/logstash/pipeline/
ENV LOG_LEVEL debug
ADD gcp-key.json /usr/share/logstash/gcp-key.json
```

But i keep getting the following issue:
```
 {:pipeline_id=>"main", :exception=>#<Errno::EACCES: Permission denied - /usr/share/logstash/gcp-key.json>, :backtrace=>["org/jruby/RubyFile.java:366:in `initialize'", "org/jruby/RubyIO.java:1154:in `open'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_pubsub-1.0.4/lib/logstash/inputs/google_pubsub.rb:187:in `register'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:341:in `register_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:352:in `register_plugins'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:502:in `start_inputs'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:393:in `start_workers'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:289:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:249:in `block in start'"], :thread=>"#<Thread:0x1f538b36 run>"}
```

Seems like a permission issue, but i don't understand where should I put the file.

Thanks

**Comment by andrewvc** [comment]
Which version of Logstash is this with?

**Comment by itielshwartz** [comment]
NVM, thanksanyway :)
