### ISSUE TITLE
Wrong argument type Array (expected Hash)

### ISSUE THREAD

**Issue by scorsi** [elastic/logstash#9152]
Hi,

I'm actually trying to pull data from pubsub using the [logstash-input-google_pubsub](https://github.com/logstash-plugins/logstash-input-google_pubsub) plugin.

But the execution gave me a **TypeError** exception

- Version:
Logstash : 6.2.1
logstash-input-google_pubsub : 1.0.4
Java : 1.8.0_151
- Operating System:
Debian 9.3
- Config File:
```
input {
        google_pubsub {
                project_id => "something-valid"
                topic => "something-valid"
                subscription => "something-valid"
        }
}
output { stdout { codec => rubydebug } }
```
- Sample Data:
```
[{"timestamp" : "2018-02-16T10:20:30.994Z", "something-valid" : 42}]
```
- Steps to Reproduce:
I've installed Logstash using `apt`.
I just run my logstash as : `sudo bin/logstash -f test.conf`
- Stack trace:
```
[INFO ] 2018-02-16 09:43:00.526 [main] scaffold - Initializing module {:module_name=>"fb_apache", :directory=>"/usr/share/logstash/modules/fb_apache/configuration"}
[INFO ] 2018-02-16 09:43:00.538 [main] scaffold - Initializing module {:module_name=>"netflow", :directory=>"/usr/share/logstash/modules/netflow/configuration"}
[WARN ] 2018-02-16 09:43:01.107 [LogStash::Runner] multilocal - Ignoring the 'pipelines.yml' file because modules or command line options are specified
[INFO ] 2018-02-16 09:43:01.436 [LogStash::Runner] runner - Starting Logstash {"logstash.version"=>"6.2.1"}
[INFO ] 2018-02-16 09:43:01.663 [Api Webserver] agent - Successfully started Logstash API endpoint {:port=>9600}
[INFO ] 2018-02-16 09:43:03.520 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] pipeline - Starting pipeline {:pipeline_id=>"main", "pipeline.work
ers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[INFO ] 2018-02-16 09:43:05.887 [[main]-pipeline-manager] googlepubsub - Authorizing with application default credentials
[INFO ] 2018-02-16 09:43:06.028 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] pipeline - Pipeline started succesfully {:pipeline_id=>"main", :th
read=>"#<Thread:0x2c883fe3@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:246 sleep>"}
[INFO ] 2018-02-16 09:43:06.096 [Ruby-0-Thread-1: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:22] agent - Pipelines running {:count=>1, :pipelines=>["main"]}
[ERROR] 2018-02-16 09:43:09.655 [[main]<google_pubsub] pipeline - A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::GooglePubSub project_id=>"something-valid", topic=>"something-valid", subscription=>"something-valid", id=>"8a37988ce41469ac3c4dba7e646be543e60cbc103af721c
89bd7eccb3ccedb3e", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_544bccf8-c48f-463a-86a0-0cce8b248e0e", enable_metric=>true, charset=>"UTF-8">, max_messages=>5>
  Error: wrong argument type Array (expected Hash)
  Exception: TypeError
  Stack: org/logstash/ext/JrubyEventExtLibrary.java:71:in `initialize'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_pubsub-1.0.4/lib/logstash/inputs/google_pubsub.rb:261:in `block in run'
org/jruby/RubyArray.java:1734:in `each'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-google_pubsub-1.0.4/lib/logstash/inputs/google_pubsub.rb:253:in `run'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:516:in `inputworker'
/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:509:in `block in start_input'
^C[WARN ] 2018-02-16 09:43:10.430 [SIGINT handler] runner - SIGINT received. Shutting down.
[INFO ] 2018-02-16 09:43:10.803 [[main]-pipeline-manager] pipeline - Pipeline has terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x2c883fe3@/usr/share/logstash/logstash-core/lib/logstash/pipelin
e.rb:246 run>"}
```

**Comment by scorsi** [comment]
Ok I solved this.
Logstash can't handle JSON which starting with a Array, so
```[{"timestamp" : "2018-02-16T10:20:30.994Z", "something-valid" : 42}]```
Should be:
```{"data" : [{"timestamp" : "2018-02-16T10:20:30.994Z", "something-valid" : 42}]}"
But we choose to split our array before sending it to PubSub.
