### ISSUE TITLE
Test Failure: LogStash::Agent when we try to start one pipeline when we successfully reload a pipeline it clear previous metrics

### ISSUE THREAD

**Issue by colinsurprenant** [elastic/logstash#9191]
https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-unix-compatibility/os=ubuntu/6/console

```
18:24:48     Failures:
18:24:48 
18:24:48       1) LogStash::Agent when we try to start one pipeline when we successfully reload a pipeline it clear previous metrics
18:24:48          Failure/Error: expect(subject.converge_state_and_update.success?).to be_truthy
18:24:48          
18:24:48            expected: truthy value
18:24:48                 got: false
18:24:48          # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/ubuntu/logstash-core/spec/logstash/agent/metrics_spec.rb:211:in `block in (root)'
18:24:48          # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/ubuntu/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/ubuntu/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
18:24:48          # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/ubuntu/lib/bootstrap/rspec.rb:13:in `<main>'
18:24:48 
18:24:48     Finished in 4 minutes 46.4 seconds (files took 9.23 seconds to load)
18:24:48     3023 examples, 1 failure, 4 pending
18:24:48 
18:24:48     Failed examples:
18:24:48 
18:24:48     rspec /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/ubuntu/logstash-core/spec/logstash/agent/metrics_spec.rb:207 # LogStash::Agent when we try to start one pipeline when we successfully reload a pipeline it clear previous metrics
18:24:48 
18:24:48     Randomized with seed 65466
18:24:48 
```

**Comment by original-brownbear** [comment]
fixed at last in #9328 :)
