### ISSUE TITLE
Logstash Errors and Continuous Restart (PQ + Ext2 File System)

### ISSUE THREAD

**Issue by sanky186** [elastic/logstash#9220]
- Version: 6.x
- Operating System: Centos

While indexing i get this error 

This keeps repeating again and logstash is restarted every 15s.

Please help

[2018-03-09T09:58:18,447][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"IOError", :message=>"java.nio.file.NoSuchFileException: /var/lib/logstash/queue/main/checkpoint.3483", :backtrace=>["sun/nio/fs/UnixException.java:86:in `translateToIOException'", "sun/nio/fs/UnixException.java:102:in `rethrowAsIOException'", "sun/nio/fs/UnixException.java:107:in `rethrowAsIOException'", "sun/nio/fs/UnixFileSystemProvider.java:214:in `newByteChannel'", "java/nio/file/Files.java:361:in `newByteChannel'", "java/nio/file/Files.java:407:in `newByteChannel'", "java/nio/file/Files.java:3152:in `readAllBytes'", "org/logstash/ackedqueue/io/FileCheckpointIO.java:56:in `read'", "org/logstash/ackedqueue/Queue.java:186:in `open'", "org/logstash/ackedqueue/ext/AbstractJRubyQueue.java:88:in `open'", "org/logstash/ackedqueue/ext/AbstractJRubyQueue$INVOKER$i$0$0$ruby_open.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:39:in `with_queue'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:28:in `create_file_based'", "/usr/share/logstash/logstash-core/lib/logstash/queue_factory.rb:29:in `create'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:174:in `initialize'", "org/jruby/RubyClass.java:1022:in `newInstance'", "org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyArray$INVOKER$i$0$0$each.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:343:in `block in execute'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:273:in `call19'", "org/jruby/RubyProc$INVOKER$i$0$0$call19.gen:-1:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:246:in `call'", "java/lang/Thread.java:748:in `run'"]}

**Comment by andrewvc** [comment]
Can you let us know which exact version this is?

@original-brownbear do you have any idea why that file would be missing?

**Comment by sanky186** [comment]
I am using 6.1.3

**Comment by original-brownbear** [comment]
@andrewvc (sorry missed this one) there's a checkpoint file missing here (`checkpoint.3483`).
Hard to say how that got lost in hindsight :(

**Comment by sanky186** [comment]
Ah :), Now should we create a dummy file named checkpoint.3483 or delete contents of queue and reset logstash ?

**Comment by sanky186** [comment]
or any other suggestions to reset logstash so that it starts to process new data coming will be helpful.

**Comment by original-brownbear** [comment]
@sanky186 creating a dummy file will not work. If it's an option just deleting the contents of the queue is your best/cleanest way to go here.

**Comment by sanky186** [comment]
Thank you @original-brownbear ..

**Comment by original-brownbear** [comment]
@sanky186 no problem! Will close here since there isn't anything actionable I can do here, unfortunately. If this happens again, please let us know though so we can investigate potential causes.

**Comment by sanky186** [comment]
Hi @original-brownbear .. I cleared the contents of queue and restarted logstash. But, i see a different error 

And the same behavior, where logstash keeps restarting

[2018-03-22T00:00:15,898][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-03-22T00:00:16,035][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.3"}
[2018-03-22T00:00:16,131][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-03-22T00:00:20,485][ERROR][logstash.pipeline        ] Logstash failed to create queue {:pipeline_id=>"main", "exception"=>"java.io.EOFException: null", "backtrace"=>["org/logstash/common/io/InputStreamStreamInput.java:19:in `readByte'", "org/logstash/common/io/BufferedChecksumStreamInput.java:28:in `readByte'", "org/logstash/common/io/StreamInput.java:42:in `readShort'", "org/logstash/ackedqueue/io/FileCheckpointIO.java:104:in `read'", "org/logstash/ackedqueue/io/FileCheckpointIO.java:53:in `read'", "org/logstash/ackedqueue/Queue.java:186:in `open'", "org/logstash/ackedqueue/ext/AbstractJRubyQueue.java:88:in `open'", "org/logstash/ackedqueue/ext/AbstractJRubyQueue$INVOKER$i$0$0$ruby_open.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:39:in `with_queue'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:28:in `create_file_based'", "/usr/share/logstash/logstash-core/lib/logstash/queue_factory.rb:29:in `create'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:174:in `initialize'", "org/jruby/RubyClass.java:1022:in `newInstance'", "org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyArray$INVOKER$i$0$0$each.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:343:in `block in execute'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:273:in `call19'", "org/jruby/RubyProc$INVOKER$i$0$0$call19.gen:-1:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:246:in `call'", "java/lang/Thread.java:748:in `run'"]}
[2018-03-22T00:00:20,486][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"IOError", :message=>"java.io.EOFException: null", :backtrace=>["org/logstash/common/io/InputStreamStreamInput.java:19:in `readByte'", "org/logstash/common/io/BufferedChecksumStreamInput.java:28:in `readByte'", "org/logstash/common/io/StreamInput.java:42:in `readShort'", "org/logstash/ackedqueue/io/FileCheckpointIO.java:104:in `read'", "org/logstash/ackedqueue/io/FileCheckpointIO.java:53:in `read'", "org/logstash/ackedqueue/Queue.java:186:in `open'", "org/logstash/ackedqueue/ext/AbstractJRubyQueue.java:88:in `open'", "org/logstash/ackedqueue/ext/AbstractJRubyQueue$INVOKER$i$0$0$ruby_open.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:39:in `with_queue'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:28:in `create_file_based'", "/usr/share/logstash/logstash-core/lib/logstash/queue_factory.rb:29:in `create'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:174:in `initialize'", "org/jruby/RubyClass.java:1022:in `newInstance'", "org/jruby/RubyClass$INVOKER$i$newInstance.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:40:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:335:in `block in converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:332:in `block in converge_state'", "org/jruby/RubyArray.java:1734:in `each'", "org/jruby/RubyArray$INVOKER$i$0$0$each.gen:-1:in `call'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:319:in `converge_state'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:166:in `block in converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:141:in `with_pipelines'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:164:in `converge_state_and_update'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:343:in `block in execute'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:273:in `call19'", "org/jruby/RubyProc$INVOKER$i$0$0$call19.gen:-1:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'", "org/jruby/RubyProc.java:289:in `call'", "org/jruby/RubyProc.java:246:in `call'", "java/lang/Thread.java:748:in `run'"]}
[2018-03-22T00:00:34,110][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/usr/share/logstash/modules/fb_apache/configuration"}
[2018-03-22T00:00:34,114][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/usr/share/logstash/modules/netflow/configuration"}
[2018-03-22T00:00:34,352][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-03-22T00:00:34,482][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.3"}
[2018-03-22T00:00:34,598][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}

**Comment by original-brownbear** [comment]
@sanky186 interesting looks like your checkpoint file got truncated somehow.

What kind of file system do you run this on?

**Comment by sanky186** [comment]
I am running a centos machine on AWS.. using ext2 filesystem

**Comment by original-brownbear** [comment]
@sanky186 thanks, I don't think we tested ext2 a lot (if at all). Will keep this open and test ext2.

**Comment by sanky186** [comment]
@original-brownbear Any luck with this issue ?

**Comment by andrewvc** [comment]
@sanky186 have you had any force restarts of the instance? Also, may I ask why you're using Ext2 as opposed to a more modern journaled filesystem?

**Comment by original-brownbear** [comment]
@sanky186 no sorry, nothing yet.
@andrewvc It is my understanding that even with an empty queue dir LS doesn't start for @sanky186 right?

**Comment by sanky186** [comment]
Model: Xen Virtual Block Device (xvd)
Disk /dev/xvda: 107GB
Sector size (logical/physical): 512B/512B
Partition Table: msdos
Disk Flags:

Number  Start   End    Size   Type     File system  Flags
 1      1049kB  107GB  107GB  primary  xfs          boot


Error: /dev/xvdb: unrecognised disk label
Model: Xen Virtual Block Device (xvd)
Disk /dev/xvdb: 215GB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags:

Error: /dev/xvdf: unrecognised disk label
Model: Xen Virtual Block Device (xvd)
Disk /dev/xvdf: 322GB
Sector size (logical/physical): 512B/512B
Partition Table: unknown
Disk Flags:

**Comment by original-brownbear** [comment]
@sanky186 looks like we're not dealing with ext2 here, but with xfs?

**Comment by sanky186** [comment]
I see these logs now

[2018-04-02T07:20:22,290][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>https://admin:xxxxxx@10.16.11.172:9200/, :path=>"/"}
[2018-04-02T07:20:22,676][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"https://admin:xxxxxx@10.16.11.172:9200/"}
[2018-04-02T07:20:22,739][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>nil}
[2018-04-02T07:20:22,740][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}
[2018-04-02T07:20:22,744][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2018-04-02T07:20:22,748][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
[2018-04-02T07:20:22,770][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://10.16.11.172:9200"]}
[2018-04-02T07:20:23,102][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>250, :thread=>"#<Thread:0xedacb7b@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 run>"}
[2018-04-02T07:20:23,700][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2018-04-02T07:20:23,810][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:5000", :ssl_enable=>"false"}
[2018-04-02T07:20:23,956][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"main"}
[2018-04-02T07:20:23,987][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
[2018-04-02T07:20:23,996][INFO ][org.logstash.beats.Server] Starting server on port: 5044
[2018-04-02T07:24:34,868][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.16.11.67:41372] Handling exception: class java.lang.OutOfMemoryError
[2018-04-02T07:25:18,352][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/usr/share/logstash/modules/fb_apache/configuration"}
[2018-04-02T07:25:18,358][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/usr/share/logstash/modules/netflow/configuration"}
[2018-04-02T07:25:18,792][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-04-02T07:25:19,007][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.3"}
[2018-04-02T07:25:19,245][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-04-02T07:25:27,005][WARN ][logstash.outputs.elasticsearch] ** WARNING ** Detected UNSAFE options in elasticsearch output configuration!
** WARNING ** You have enabled encryption but DISABLED certificate verification.
** WARNING ** To make sure your data is secure change :ssl_certificate_verification to true
[2018-04-02T07:25:27,523][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[https://admin:xxxxxx@10.16.11.172:9200/]}}
[2018-04-02T07:25:27,525][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>https://admin:xxxxxx@10.16.11.172:9200/, :path=>"/"}
[2018-04-02T07:25:27,922][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"https://admin:xxxxxx@10.16.11.172:9200/"}
[2018-04-02T07:25:27,977][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>nil}
[2018-04-02T07:25:27,978][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}
[2018-04-02T07:25:27,979][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2018-04-02T07:25:27,982][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
[2018-04-02T07:25:27,997][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["https://10.16.11.172:9200"]}
[2018-04-02T07:25:28,308][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>2, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>250, :thread=>"#<Thread:0x288195b9@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 run>"}
[2018-04-02T07:25:28,793][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2018-04-02T07:25:28,900][INFO ][logstash.inputs.tcp      ] Starting tcp input listener {:address=>"0.0.0.0:5000", :ssl_enable=>"false"}
[2018-04-02T07:25:28,989][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"main"}
[2018-04-02T07:25:29,022][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
[2018-04-02T07:25:29,042][INFO ][org.logstash.beats.Server] Starting server on port: 5044

**Comment by original-brownbear** [comment]
@sanky186 I see:

```sh
[2018-04-02T07:24:34,868][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.16.11.67:41372] Handling exception: class java.lang.OutOfMemoryError
```

Are you running out of memory? What values do you have set for `Xmx` and `Xms` in `config/jvm.options`? Also how much physical memory does the box you're running this one have  available/free?

**Comment by sanky186** [comment]
[root@ip-10-16-11-222 logstash]# free -g
              total        used        free      shared  buff/cache   available
Mem:              7           2           4           0           0           4
Swap:             0           0           0

## JVM configuration

# Xms represents the initial size of total heap space
# Xmx represents the maximum size of total heap space

-Xms4g
-Xmx8g

@original-brownbear  What is OOM and how do i run it ?

**Comment by original-brownbear** [comment]
@sanky186 OOM is just short for out of memory.

Looking at your output, you're allocating at least 4GB and at the most 8 GB to LS while your system only has 4GB of free physical memory available out of a total of 7GB.
Since you shouldn't even be using all of your free memory just for the LS java process and also should have `Xmx` and `Xms` set to the same value I suggest setting `-Xms2g` and `-Xmx2g` and trying that out. 
Your problem clearly is running out of memory.

**Comment by sanky186** [comment]
Understood Armin :).. i have set the values as advised. Do you believe setting it to a lower number will resolve it ? and any suggestions on how i can avoid OOM ?

**Comment by original-brownbear** [comment]
@sanky186 yes I believe setting the memory usage to a lower value will likely resolve your issues.
The only way you can avoid running into this going forward is to not set `Xmx` and `Xms` values that are different from each other **any** higher than what your system has in free physical memory. 

Closing here, for now, there's no actionable bug in here as far as I can see. If you run into further issues please reopen (if still running into the same problem) or open a new issue if it's something different. thanks :)
