### ISSUE TITLE
Misleading error message due to bad log4j2 configuration

### ISSUE THREAD

**Issue by mgodlewski** [elastic/logstash#9221]
Hi,

I've experienced these logs:
```
[2018-03-08T14:29:30,455][ERROR][logstash.plugins.registry] Problems loading a plugin with {:type=>"input", :name=>"beats", :path=>"logstash/inputs/beats", :error_message=>"cannot load Java class org.logstash.beats.MessageListener", :error_class=>NameError, :error_backtrace=>["org/jruby/javasupport/JavaClass.java:204:in `for_name'", "org/jruby/javasupport/JavaUtilities.java:34:in `get_proxy_class'", "file:/usr/share/logstash/vendor/jruby/lib/jruby.jar!/jruby/java/core_ext/object.rb:27:in `java_import'", "org/jruby/RubyArray.java:2414:in `map'", "file:/usr/share/logstash/vendor/jruby/lib/jruby.jar!/jruby/java/core_ext/object.rb:22:in `java_import'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.24-java/lib/logstash/inputs/beats/message_listener.rb:4:in `(root)'", "org/jruby/RubyKernel.java:1040:in `require'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.24-java/lib/logstash/inputs/beats.rb:1:in `(root)'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.24-java/lib/logstash/inputs/beats.rb:51:in `Beats'", "org/jruby/RubyKernel.java:1040:in `require'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-beats-3.1.24-java/lib/logstash/inputs/beats.rb:46:in `(root)'", "/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:1:in `(root)'", "/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:156:in `legacy_lookup'", "/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:138:in `lookup'", "/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:180:in `lookup_pipeline_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/plugin.rb:140:in `lookup'", "org/jruby/RubyKernel.java:1079:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:103:in `plugin'", "(eval):8:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:75:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:165:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:286:in `create_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:95:in `register_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:313:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}
[2018-03-08T14:29:30,464][ERROR][logstash.agent           ] Cannot create pipeline {:reason=>"Couldn't find any input plugin named 'beats'. Are you sure this is correct? Trying to load the beats input plugin resulted in this error: Problems loading the requested plugin named beats of type input. Error: NameError cannot load Java class org.logstash.beats.MessageListener"}
```

The root cause was a wrong log4j2 configuration I made.
However, these errors messages didn't help me and I've lost an hour on a the misleading message, thinking the problem was due to a missing/badly installed plugin.

Is there any way to improve the error message ?
Or is it a marginal case ? In this case, the existence of this issue is sufficient to help clumsy people like me :)

- Version: 5.6.3
- Operating System: Debian 8
- Config File (if you have sensitive info, please remove it):
- Sample Data:
- Steps to Reproduce: 
sed 's/^status = error$/status = trace/' /etc/logstash/log4j2.properties
systemctl restart logstash

**Comment by yaauie** [comment]
@mgodlewski oy, that error message isn't helpful at all. Thanks for reporting, and for providing a reproduction steps.

**Comment by andrewvc** [comment]
This is a weird one, causes totally different errors on my box. I couldn't repro in 6.x, so it's likely 5.x only
