### ISSUE TITLE
Persitent queues: integer $int too big to convert to `int'

### ISSUE THREAD

**Issue by calve** [elastic/logstash#9229]
Hi there, 

Trying to set up a persistent queue of 5GB fails with the following exception : 

```
[2018-03-12T11:35:09,739][ERROR][logstash.pipeline        ] Logstash failed to create queue {"exception"=>"integer 5368709120 too big to convert to `int'", "backtrace"=>["org/logstash/ackedqueue/ext/JrubyAckedQueueExtLibrary.java:62:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/util/wrapped_acked_queue.rb:30:in `create_file_based'", "/usr/share/logstash/logstash-core/lib/logstash/queue_factory.rb:29:in `create'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:168:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:296:in `create_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:95:in `register_pipeline'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:313:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:204:in `run'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:71:in `(root)'"]}
```

The documentation does not mention any limit. It actually shows an example with 4gb https://www.elastic.co/guide/en/logstash/5.6/persistent-queues.html#configuring-persistent-queues.

On the other end, this user found a 1gb limit https://discuss.elastic.co/t/logstash-fail-to-start/96102/5

What is the maximum suppoted value ? Is this a bug in the documentation (missing the upper limit) or in the code ?

This is logstash 5.6 running on ubuntu 1604 with openjdk version 1.8.0_151.
Let me know if you need any extra informations.

**Comment by calve** [comment]
my tests showed an hard limit at 2048Mb, which match the range of `int` in java (-2,147,483,648 to 2,147,483, 647)

**Comment by calve** [comment]
Shame on me, I mixed up the `page_capacity` and `max_bytes`  parameters. Hope this help someone in the future thought
