### ISSUE TITLE
logstash unable to read data from Kafka topic

### ISSUE THREAD

**Issue by saurabhsharmaj** [elastic/logstash#9287]
Logstash version: 6.2.3
Java: 1.8_45

This is my yml file:
input {
     kafka {
            bootstrap_servers => 'localhost:9092'
            topics => ["Tomcat"]
            codec => json {}
          }
}

output {
    #Output result sent to elasticsearch and dynamically create array
    elasticsearch {
        index  => "tomcat"
        hosts => ["192.168.0.16:9200"]
        sniffing => false
    }
 
     #Sysout logs
     stdout
       {
         codec => rubydebug
       }
}

Getting following error:
[2018-03-24T12:00:02,329][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "" hasn't been registered>, :backtrace=>["C:/logstash-6.2.3/logstash-core/lib/logstash/settings.rb:37:in `get_setting'", "C:/logstash-6.2.3/logstash-core/lib/logstash/settings.rb:70:in `set_value'", "C:/logstash-6.2.3/logstash-core/lib/logstash/settings.rb:89:in `block in merge'", "org/jruby/RubyHash.java:1343:in `each'", "C:/logstash-6.2.3/logstash-core/lib/logstash/settings.rb:89:in `merge'", "C:/logstash-6.2.3/logstash-core/lib/logstash/settings.rb:138:in `validate_all'", "C:/logstash-6.2.3/logstash-core/lib/logstash/runner.rb:264:in `execute'", "C:/logstash-6.2.3/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "C:/logstash-6.2.3/logstash-core/lib/logstash/runner.rb:219:in `run'", "C:/logstash-6.2.3/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "C:\\logstash-6.2.3\\lib\\bootstrap\\environment.rb:67:in `<main>'"]}

**Comment by yaauie** [comment]
Issues like this are best handled in the [Logsash Forums](https://discuss.elastic.co/c/logstash); if the below doesn't help, please open a new thread over there (feel free to ping me if you do).

The problem is somewhere in your `logstash.yml`; Logstash is a reading the yaml config and coming up with an empty key.

I can replicate by adding this line to my `logstash.yml`:

~~~
"" : foo
~~~
