### ISSUE TITLE
Setting “xpack.monitoring.enabled” hasn’t been registered 

### ISSUE THREAD

**Issue by ompraash** [elastic/logstash#9306]
After upgrading to logstash 6.2.3,  with other elasticsearch, kibana at the same level started to see issue when x-pack is installed.

`[2018-04-01T10:06:01,660][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/usr/share/logstash/modules/netflow/configuration"}
[2018-04-01T10:06:01,673][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.elasticsearch.url" hasn't been registered>, :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/settings.rb:37:in `get_setting'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:70:in `set_value'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:89:in `block in merge'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:89:in `merge'", "/usr/share/logstash/logstash-core/lib/logstash/settings.rb:138:in `validate_all'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:264:in `execute'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/runner.rb:219:in `run'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/usr/share/logstash/lib/bootstrap/environment.rb:67:in `<main>'"]}`

When x-pack is disabled it works. In version 6.2.2 it works with x-pack.

Any change or this is an issue in this version?

**Comment by andrewvc** [comment]
Do you have x-pack installed on Elasticsearch and Logstash, or just Logstash?

**Comment by ompraash** [comment]
it is installed on Logstash, Elastic and Kibana.
I have the below configured in logstash.yml

xpack.monitoring.elasticsearch.username: logstash_system
xpack.monitoring.elasticsearch.password: "changeMe"
#xpack.management.enabled: true
#xpack.management.logstash.poll_interval: 5s
#xpack.management.elasticsearch.username: "logstash_internal"
#xpack.management.elasticsearch.password: "logstashInternal"
xpack.monitoring.elasticsearch.url: ["172.30.42.62:9200","172.30.32.29:9200","172.30.32.80:9200"]
xpack.management.elasticsearch.url: ["172.30.42.62:9200","172.30.32.29:9200","172.30.32.80:9200"]
xpack.monitoring.elasticsearch.sniffing: false

with the above settings do not get any error. After uncomment of lines, start to see the exception.

**Comment by andrewvc** [comment]
Ah, I see now, you're using a module (netflow) with central management. We don't currently support that, though we would like to in the future. In the next LS release we'll print a better error message.

Apologies for the confusion here.

**Comment by ompraash** [comment]
thanks @andrewvc .
We will need the documentation to be updated as well.
url: [https://www.elastic.co/guide/en/logstash/current/configuring-centralized-pipelines.html](https://www.elastic.co/guide/en/logstash/current/configuring-centralized-pipelines.html)
