### ISSUE TITLE
Webserver Spec randomly Fails on Concurrent Array Modification

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#9361]
https://logstash-ci.elastic.co/job/elastic+logstash+master+multijob-unix-compatibility/os=centos/46/console

```sh
05:31:44       1) LogStash::WebServer when an exception occur in the server thread should not log to STDERR
05:31:44          Failure/Error: status = RSpec::Core::Runner.run(ARGV.empty? ? ($JUNIT_ARGV || ["spec"]) : ARGV).to_i
05:31:44          
05:31:44          ConcurrencyError:
05:31:44            Detected invalid array contents due to unsynchronized modifications with concurrent users
05:31:44          # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/centos/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/centos/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
05:31:44          # /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/centos/lib/bootstrap/rspec.rb:13:in `<main>'
05:31:44 
05:31:44     Finished in 5 minutes 16 seconds (files took 8.89 seconds to load)
05:31:44     2745 examples, 1 failure, 4 pending
05:31:44 
05:31:44     Failed examples:
05:31:44 
05:31:44     rspec /var/lib/jenkins/workspace/elastic+logstash+master+multijob-unix-compatibility/os/centos/logstash-core/spec/logstash/webserver_spec.rb:55 # LogStash::WebServer when an exception occur in the server thread should not log to STDERR
```

Same spec also randomly fails on:

```sh
22:05:24     Failures:
22:05:24 
22:05:24       1) LogStash::WebServer when an exception occur in the server thread should not log to STDERR
22:05:24          Failure/Error: expect(IO).to receive(:select).and_raise(IOError).at_least(:once)
22:05:24          
22:05:24            (IO (class)).select(*(any args))
22:05:24                expected: at least 1 time with any arguments
22:05:24                received: 0 times with any arguments
22:05:24          # ./logstash-core/spec/logstash/webserver_spec.rb:68:in `block in (root)'
22:05:24          # ./vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /opt/logstash/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
22:05:24          # ./lib/bootstrap/rspec.rb:13:in `<main>'
22:05:24 
```

probably related.

**Comment by original-brownbear** [comment]
Phew, this test is really crazy and it seems impossible to even close the web-server cleanly here ... I'm gonna ignore this, for now, I think we'd be best served by moving the webserver code to Java eventually. The fact that you can't cleanly close the current Rack implementation makes it really hard to fix this kind of test without investing a lot of effort.

**Comment by original-brownbear** [comment]
nevermind back on it, found a few more cases of this happening, seems it's new ...

**Comment by original-brownbear** [comment]
Closing this, the test has been excluded and will "fix itself" once it has been ported to JUnit.
