### ISSUE TITLE
Compatibility Tests fail for 5.6 and 6.2 Branches

### ISSUE THREAD

**Issue by original-brownbear** [elastic/logstash#9365]
@jsvd FYI

seems that updating the lock files yesterday caused some problem.

see https://logstash-ci.elastic.co/job/elastic+logstash+5.6+multijob-unix-compatibility/os=debian/12/console (same failure for `6.2` branch).

Log:

```sh
00:35:33 Downloading http://jruby.org.s3.amazonaws.com/downloads/1.7.27/jruby-bin-1.7.27.tar.gz
00:35:46 Installing minitar 0.6.1 because the build process needs it.
00:35:46 mkdir -p build
00:35:46 mkdir -p build/bootstrap
00:35:46 [bootstrap] Fetching and installing gem: minitar (0.6.1)
00:35:47 The `minitar` executable is no longer bundled with `minitar`. If you are
00:35:47 expecting this executable, make sure you also install `minitar-cli`.
00:35:47 Successfully installed minitar-0.6.1
00:35:49 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:35:55 Installing bundler ~> 1.9.4 because the build process needs it.
00:35:55 [bootstrap] Fetching and installing gem: bundler (~> 1.9.4)
00:35:58 Successfully installed bundler-1.9.10
00:35:58 Invoking bundler install...
00:36:47 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:36:49 Error Bundler::InstallError, retrying 1/10
00:36:49 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:36:49 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:36:51 WARNING: can not set Session#timeout=(0) no session context
00:36:54 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:36:55 Error Bundler::InstallError, retrying 2/10
00:36:55 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:36:55 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:37:00 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:37:01 Error Bundler::InstallError, retrying 3/10
00:37:01 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:37:01 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:37:06 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:37:07 Error Bundler::InstallError, retrying 4/10
00:37:07 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:37:07 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:37:12 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:37:14 Error Bundler::InstallError, retrying 5/10
00:37:14 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:37:14 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:37:18 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:37:20 Error Bundler::InstallError, retrying 6/10
00:37:20 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:37:20 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:37:24 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:37:26 Error Bundler::InstallError, retrying 7/10
00:37:26 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:37:26 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:37:42 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:37:44 Error Bundler::InstallError, retrying 8/10
00:37:44 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:37:44 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:37:56 WARNING: can not set Session#timeout=(0) no session context
00:38:01 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:38:03 Error Bundler::InstallError, retrying 9/10
00:38:03 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:38:03 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:38:19 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:38:21 Error Bundler::InstallError, retrying 10/10
00:38:21 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:38:21 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:38:37 Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
00:38:39 Too many retries, aborting, caused by Bundler::InstallError
00:38:39 rake aborted!
00:38:39 An error occurred while installing logstash-core (5.6.9), and Bundler cannot continue.
00:38:39 Make sure that `gem install logstash-core -v '5.6.9'` succeeds before bundling.
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:145:in `install_gem_from_spec'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:126:in `install_gem_from_spec'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:269:in `install_sequentially'
00:38:39 org/jruby/RubyArray.java:1613:in `each'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:268:in `install_sequentially'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:90:in `run'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/installer.rb:18:in `install'
00:38:39 /var/lib/jenkins/.rbenv/rbenv.d/exec/gem-rehash/rubygems_plugin.rb:27:in `install'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli/install.rb:80:in `run'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:155:in `install'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/vendor/bundle/jruby/1.9/gems/bundler-1.9.10/lib/bundler/cli.rb:10:in `start'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/lib/bootstrap/bundler.rb:168:in `execute_bundler'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/lib/bootstrap/bundler.rb:139:in `execute_bundler_with_retry'
00:38:39 org/jruby/RubyKernel.java:1479:in `loop'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/lib/bootstrap/bundler.rb:137:in `execute_bundler_with_retry'
00:38:39 org/jruby/RubyProc.java:281:in `call'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/lib/bootstrap/bundler.rb:211:in `capture_stdout'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/lib/bootstrap/bundler.rb:136:in `execute_bundler_with_retry'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/lib/bootstrap/bundler.rb:126:in `invoke!'
00:38:39 /var/lib/jenkins/workspace/elastic+logstash+5.6+multijob-unix-compatibility/os/debian/rakelib/vendor.rake:122:in `(root)'
00:38:39 org/jruby/RubyProc.java:281:in `call'
00:38:39 org/jruby/RubyArray.java:1613:in `each'
00:38:39 org/jruby/RubyArray.java:1613:in `each'
00:38:39 org/jruby/RubyArray.java:1613:in `each'
00:38:39 org/jruby/RubyArray.java:1613:in `each'
```

**Comment by jsvd** [comment]
> same failure for 6.2 branch

On 6.2 things seem to be fine https://logstash-ci.elastic.co/job/elastic+logstash+6.2+multijob-unix-compatibility/24/ ?

**Comment by original-brownbear** [comment]
@jsvd argh my bad, `6.0` has the same problem https://logstash-ci.elastic.co/job/elastic+logstash+6.0+multijob-legacy/6/console

**Comment by original-brownbear** [comment]
`6.1` as well, but that's from 2 days ago so probably not from the lock file change https://logstash-ci.elastic.co/job/elastic+logstash+6.1+multijob-legacy/4/console

**Comment by jsvd** [comment]
Right, my guess is that 5.6 is also not directly related to the .lock change (only done in 5.9 and 6.2), investigating further.

**Comment by jsvd** [comment]
update: I logged into the ubuntu worker that ran this job and tried with my user to run a `rake test:install-core` on 5.6 branch and it worked correctly..

next step: triggering a jenkins build with the 5.6~2 commit hash to exclude the .lock file change

**Comment by jsvd** [comment]
update: confirmed 5.6 is failing on jenkins for ubuntu and debian before the .lock commit https://logstash-ci.elastic.co/job/elastic+logstash+5.6+multijob-unix-compatibility/

I tried on a local ubuntu vm and couldn't replicate yet.

Looking at the rubygems.org certificate it was refreshed recently:

```
Subject | f2.shared.global.fastly.net
Valid from 26/Mar/2018 to 06/Oct/2018
Issuer | GlobalSign CloudSSL CA - SHA256 - G3
```

I wonder if this is the cause..

**Comment by jsvd** [comment]
@original-brownbear Given all of this information so far and the fact that we were able to build a build candidate for 5.6.9 correctly I'd suggest not calling this a blocker.

**Comment by original-brownbear** [comment]
@jsvd yea def. so sorry for somehow projecting the wrong versions onto this initially :) removed the tag

**Comment by original-brownbear** [comment]
@jsvd I haven't see this happen anymore (at least not within the last week). Did anything change here?
