### ISSUE TITLE
xpack.[monitoring|management].elasticsearch.ssl.certificate_authority does not accept an array

### ISSUE THREAD

**Issue by elasticmachine** [elastic/logstash#9430]
*Original comment by @jpcarey:*

The `xpack.monitoring.elasticsearch.ssl.ca` is expecting an string. It should accept an array similar to the rest of our stack. `xpack.monitoring.elasticsearch.ssl.ca: []`

`
[2017-03-06T12:13:24,786][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<ArgumentError: Setting "xpack.monitoring.elasticsearch.ssl.ca" must be a String. Received: ["/Users/jared/Dev/cert_provisioning/certs/C=US;O=Carey Ltd;CN=Carey Ltd CA/certs/C=US;O=Carey Ltd;CN=Carey Ltd CA.cert.pem"] (Array)>, :backtrace=>["/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/settings.rb:208:in `validate'", "/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/settings.rb:384:in `validate'", "/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/settings.rb:394:in `validate'", "/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/settings.rb:171:in `set'", "/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/settings.rb:61:in `set_value'", "/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/settings.rb:80:in `merge'", "org/jruby/RubyHash.java:1342:in `each'", "/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/settings.rb:80:in `merge'", "/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/settings.rb:115:in `validate_all'", "/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/runner.rb:210:in `execute'", "/Users/jared/builds/logstash/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'", "/Users/jared/builds/logstash/logstash-5.2.2/logstash-core/lib/logstash/runner.rb:183:in `run'", "/Users/jared/builds/logstash/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'", "/Users/jared/builds/logstash/logstash-5.2.2/lib/bootstrap/environment.rb:71:in `(root)'"]}
`

**Comment by ppf2** [comment]
This applies to both:

xpack.monitoring.elasticsearch.ssl.certificate_authority
and
xpack.management.elasticsearch.ssl.certificate_authority

**Comment by knitterb** [comment]
This is a pretty old bug, would be nice to see this fixed.  The use case is where you have an intermediary and a root cert.  You need to specify the full cert chain for validation to occur.
