### ISSUE TITLE
Test Failure: common Filter remove_field with sprintf-declared field reference

### ISSUE THREAD

**Issue by yaauie** [elastic/logstash#9504]
A disconcerting [test failure on default filter functionality in 6.3](https://logstash-ci.elastic.co/job/elastic+logstash+6.3+multijob-unix-compatibility/os=opensuse/7/console) indicates that our wires are getting crossed in testing, and within a `sample_one` block, `subject` isn't always the result of the execution we are attempting to test.

In this case, when using `sample_one` with a config that does no event splitting, we would reasonably expect a single event to be bound to the `subject`, but the failure shows an array of 201 events:

Failing Test:

> ~~~ ruby
>   describe "remove_field with dynamic value in field name" do
>     config <<-CONFIG
>     filter {
>       noop {
>         remove_field => ["%{blackhole}"]
>       }
>     }
>     CONFIG
> 
>     sample_one("type" => "noop", "blackhole" => "go", "go" => "away") do
>       insist { subject }.include?("blackhole")
>       reject { subject }.include?("go")
>     end
>   end
> ~~~
> -- [logstash-core/spec/logstash/filters/base_spec.rb:298:311@6.3](https://github.com/elastic/logstash/blob/6.3/logstash-core/spec/logstash/filters/base_spec.rb#L298-L311)

Failure:

> ~~~
> 22:37:34       1) LogStash::Filters::NOOP remove_field with dynamic value in field name "{"type":"noop","blackhole":"go","go":"away"}" when processed
> 22:37:34          Failure/Error: insist { subject }.include?("blackhole")
> 22:37:34          
> 22:37:34          Insist::Failure:
> 22:37:34            Expected "blackhole" in [#<LogStash::Event:0x4390ad9c>, #<LogStash::Event:0x231b79fd>, #<LogStash::Event:0x4c4349bb>, #<LogStash::Event:0x13e2d5a3>, #<LogStash::Event:0x55d8660e>, #<LogStash::Event:0x2df439d9>, #<LogStash::Event:0x7baca34d>, #<LogStash::Event:0x7ee62e56>, #<LogStash::Event:0x6818df92>, #<LogStash::Event:0x64ae19b9>, #<LogStash::Event:0x7a0678aa>, #<LogStash::Event:0x35dd6d22>, #<LogStash::Event:0x1b97d044>, #<LogStash::Event:0xf60615e>, #<LogStash::Event:0x466a9b30>, #<LogStash::Event:0x18805aa2>, #<LogStash::Event:0x3d30bc06>, #<LogStash::Event:0x31d6506f>, #<LogStash::Event:0x2377fe7e>, #<LogStash::Event:0x3938e5f8>, #<LogStash::Event:0x1d0be55>, #<LogStash::Event:0x206c328>, #<LogStash::Event:0x1e1e5918>, #<LogStash::Event:0x60f76806>, #<LogStash::Event:0x6451405b>, #<LogStash::Event:0x50fad07a>, #<LogStash::Event:0x3cc085e4>, #<LogStash::Event:0x672c6d22>, #<LogStash::Event:0x991aa04>, #<LogStash::Event:0xfeec24c>, #<LogStash::Event:0x373999f0>, #<LogStash::Event:0x3378b748>, #<LogStash::Event:0x37bdeaa9>, #<LogStash::Event:0x4eb8a2b0>, #<LogStash::Event:0x3535448e>, #<LogStash::Event:0x43817797>, #<LogStash::Event:0x1b3135ec>, #<LogStash::Event:0x1017b918>, #<LogStash::Event:0xf998ea0>, #<LogStash::Event:0x47ec7d0b>, #<LogStash::Event:0x55e0be4f>, #<LogStash::Event:0x78120292>, #<LogStash::Event:0x3b3d7fbe>, #<LogStash::Event:0x1f1d59f7>, #<LogStash::Event:0x4fdf8e9d>, #<LogStash::Event:0x27b10366>, #<LogStash::Event:0x77a158a1>, #<LogStash::Event:0x2866543>, #<LogStash::Event:0x311eb8e8>, #<LogStash::Event:0x1e9b379e>, #<LogStash::Event:0x638210bc>, #<LogStash::Event:0x529fddf2>, #<LogStash::Event:0x1602f6b1>, #<LogStash::Event:0x51621428>, #<LogStash::Event:0x2296e948>, #<LogStash::Event:0xe4ac0a5>, #<LogStash::Event:0xffc08a3>, #<LogStash::Event:0x4e7e9e20>, #<LogStash::Event:0x5bb7e20e>, #<LogStash::Event:0x3a04e35>, #<LogStash::Event:0x6cf6e7f2>, #<LogStash::Event:0x56c3ebd2>, #<LogStash::Event:0x3280d496>, #<LogStash::Event:0x3350f515>, #<LogStash::Event:0x68c25dfa>, #<LogStash::Event:0x2116a64b>, #<LogStash::Event:0x1586f29b>, #<LogStash::Event:0x214a5563>, #<LogStash::Event:0x5b9df13d>, #<LogStash::Event:0x4fad30fb>, #<LogStash::Event:0x6d9d11bf>, #<LogStash::Event:0x1e0fa022>, #<LogStash::Event:0x2a2fbec7>, #<LogStash::Event:0xca36991>, #<LogStash::Event:0x9b69153>, #<LogStash::Event:0x6a5b2ef7>, #<LogStash::Event:0x3d556cfd>, #<LogStash::Event:0x2aad6527>, #<LogStash::Event:0x172c5528>, #<LogStash::Event:0x2433fdac>, #<LogStash::Event:0x32975f53>, #<LogStash::Event:0x7352807b>, #<LogStash::Event:0x6221e2c>, #<LogStash::Event:0x3dc74dd9>, #<LogStash::Event:0x3522f0f5>, #<LogStash::Event:0x5294ff72>, #<LogStash::Event:0x44d14872>, #<LogStash::Event:0x43ff6cb4>, #<LogStash::Event:0x61788966>, #<LogStash::Event:0x14629554>, #<LogStash::Event:0x5a3ecd72>, #<LogStash::Event:0x629c904d>, #<LogStash::Event:0x478a16c1>, #<LogStash::Event:0x47c2e351>, #<LogStash::Event:0x6b3bf386>, #<LogStash::Event:0x6da31854>, #<LogStash::Event:0x7a88273f>, #<LogStash::Event:0x2a808b54>, #<LogStash::Event:0x1e93ea41>, #<LogStash::Event:0x6b07207f>, #<LogStash::Event:0x500d43ff>, #<LogStash::Event:0x7ef9a881>, #<LogStash::Event:0x7f3994fd>, #<LogStash::Event:0x2d6f57bd>, #<LogStash::Event:0x17c7eb54>, #<LogStash::Event:0x2449f48d>, #<LogStash::Event:0x17e41285>, #<LogStash::Event:0x40e17d7b>, #<LogStash::Event:0x6854b378>, #<LogStash::Event:0x3d2df63>, #<LogStash::Event:0x349585a6>, #<LogStash::Event:0x7f543cea>, #<LogStash::Event:0x32d68f0b>, #<LogStash::Event:0x27ea67f5>, #<LogStash::Event:0x3f4a6e1b>, #<LogStash::Event:0x6127b674>, #<LogStash::Event:0x670fd38c>, #<LogStash::Event:0x13aec557>, #<LogStash::Event:0x7ff84b8f>, #<LogStash::Event:0x23b0c612>, #<LogStash::Event:0x3a3af25b>, #<LogStash::Event:0x5fdb1c36>, #<LogStash::Event:0x62c29071>, #<LogStash::Event:0x47674a6d>, #<LogStash::Event:0x2aa2c0f0>, #<LogStash::Event:0x2d9f533e>, #<LogStash::Event:0x5ba80fe4>, #<LogStash::Event:0x26e112de>, #<LogStash::Event:0x1a78f3b2>, #<LogStash::Event:0x4da95560>, #<LogStash::Event:0x5665b41e>, #<LogStash::Event:0x783c3bee>, #<LogStash::Event:0x2504a238>, #<LogStash::Event:0x2281f1ad>, #<LogStash::Event:0x59bf64a7>, #<LogStash::Event:0x4045c735>, #<LogStash::Event:0x4050b867>, #<LogStash::Event:0x6df12559>, #<LogStash::Event:0x4fc9fe1c>, #<LogStash::Event:0x21dbe4bf>, #<LogStash::Event:0x648df363>, #<LogStash::Event:0x32d946>, #<LogStash::Event:0xbee42>, #<LogStash::Event:0x7e0b1ce0>, #<LogStash::Event:0x7596eea9>, #<LogStash::Event:0x6378e1b4>, #<LogStash::Event:0x3cde7a67>, #<LogStash::Event:0x1a148d00>, #<LogStash::Event:0x58b5cb4d>, #<LogStash::Event:0x7ce4f4ae>, #<LogStash::Event:0x3326b417>, #<LogStash::Event:0xde453fe>, #<LogStash::Event:0x7bfd1eac>, #<LogStash::Event:0x20e7c4f9>, #<LogStash::Event:0x26e75afe>, #<LogStash::Event:0x9b3867f>, #<LogStash::Event:0x1aa8f19b>, #<LogStash::Event:0x4f63e3b>, #<LogStash::Event:0x18dab4f1>, #<LogStash::Event:0xdcf59eb>, #<LogStash::Event:0x50b655e0>, #<LogStash::Event:0x6584be2b>, #<LogStash::Event:0x28b4f356>, #<LogStash::Event:0x5fc3f7aa>, #<LogStash::Event:0x3d38b0e7>, #<LogStash::Event:0x7d0d348d>, #<LogStash::Event:0x72ac4639>, #<LogStash::Event:0x32929161>, #<LogStash::Event:0x4a55a05c>, #<LogStash::Event:0x5e685cc7>, #<LogStash::Event:0x4ee554bd>, #<LogStash::Event:0x685acd99>, #<LogStash::Event:0xfead78e>, #<LogStash::Event:0x13f82cd0>, #<LogStash::Event:0x775cd2ae>, #<LogStash::Event:0x49d4ffd9>, #<LogStash::Event:0x105b07ca>, #<LogStash::Event:0x421727bd>, #<LogStash::Event:0x53cf44f3>, #<LogStash::Event:0x3d0b5364>, #<LogStash::Event:0x75267658>, #<LogStash::Event:0xef78d8e>, #<LogStash::Event:0x2736b87f>, #<LogStash::Event:0x40415f8e>, #<LogStash::Event:0x6136568>, #<LogStash::Event:0x343a03d9>, #<LogStash::Event:0x265da061>, #<LogStash::Event:0x6c2a360b>, #<LogStash::Event:0x718f36c3>, #<LogStash::Event:0x15cfd7e0>, #<LogStash::Event:0x5e5a2390>, #<LogStash::Event:0x637dcc3e>, #<LogStash::Event:0x6b4cd7bc>, #<LogStash::Event:0x577de2>, #<LogStash::Event:0xf1e98db>, #<LogStash::Event:0x28fb93a>, #<LogStash::Event:0xf736fe0>, #<LogStash::Event:0x3470ab81>, #<LogStash::Event:0x4f533594>, #<LogStash::Event:0x30ea032d>, #<LogStash::Event:0x24f266bf>]
> 22:37:34          # /var/lib/jenkins/workspace/elastic+logstash+6.3+multijob-unix-compatibility/os/opensuse/vendor/bundle/jruby/2.3.0/gems/insist-1.0.0/lib/insist/assert.rb:8:in `assert'
> 22:37:34          # /var/lib/jenkins/workspace/elastic+logstash+6.3+multijob-unix-compatibility/os/opensuse/vendor/bundle/jruby/2.3.0/gems/insist-1.0.0/lib/insist/enumerables.rb:11:in `include?'
> 22:37:34          # /var/lib/jenkins/workspace/elastic+logstash+6.3+multijob-unix-compatibility/os/opensuse/logstash-core/spec/logstash/filters/base_spec.rb:308:in `block in (root)'
> 22:37:34          # /var/lib/jenkins/workspace/elastic+logstash+6.3+multijob-unix-compatibility/os/opensuse/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb:46:in `block in /var/lib/jenkins/workspace/elastic+logstash+6.3+multijob-unix-compatibility/os/opensuse/vendor/bundle/jruby/2.3.0/gems/rspec-wait-0.0.9/lib/rspec/wait.rb'
> 22:37:34          # /var/lib/jenkins/workspace/elastic+logstash+6.3+multijob-unix-compatibility/os/opensuse/lib/bootstrap/rspec.rb:13:in `<main>'
> ~~~
> -- [CI Failure Output](https://logstash-ci.elastic.co/job/elastic+logstash+6.3+multijob-unix-compatibility/os=opensuse/7/console)

**Comment by yaauie** [comment]
My first inclination was that `SpecSamplerInput` and `SpecSamplerOutput` that are the backbone of the `sample_one` helper (which store state on their classes) were causing state to leak from one spec to another, but (a) these specs do appear to be running correctly in series with no overlap and (b) in no case were 200 events processed by a single `sample_one` instance.

However, we instantiate the pipeline (and it builds its queue) from a clone of `::LogStash::SETTINGS`, which before each test is reset and overridden with a few specific settings; is it possible that we're picking up events that had been flushed to a PQ?

> ~~~ ruby
>     LogStash::SETTINGS.reset
> 
>     LogStash::SETTINGS.set("queue.type", "persisted")
>     LogStash::SETTINGS.set("queue.page_capacity", 1024 * 1024)
>     LogStash::SETTINGS.set("queue.max_events", 250)
> ~~~
> -- [spec/spec_helper.rb:58-62@6.3](https://github.com/elastic/logstash/blob/6.3/spec/spec_helper.rb#L58-L62)
