### ISSUE TITLE
Logstash crashes when parsing FieldReference from String `"["`

### ISSUE THREAD

**Issue by yaauie** [elastic/logstash#9524]
When we attempt to parse a user-defined field-reference that is the string `"["` (e.g., when setting a field dynamically, as with the KV Filter Plugin in logstash-plugins/logstash-filter-kv#56), Logstash crashes with an `java.lang.ArrayIndexOutOfBoundsException`.

This occurs in 6.2.2 release, as well as on the heads of `6.2`, `6.3`, `6.x`, and `master`; I have not validated with the 5.x series.

With the following pipeline config `crashme.conf:

~~~
input { generator { count => 1 } }
filter {
  mutate {
    add_field => {
      "[" => "boom"
    }
  }
}
output { stdout { codec => rubydebug } }
~~~

~~~
╭─{ yaauie@castrovel:~/src/elastic/discuss-scratch/unfiled-kv-issue-59 }
╰─○ ~/src/elastic/releases/logstash-6.2.2/bin/logstash -f crashme.conf
Sending Logstash's logs to /Users/yaauie/src/elastic/releases/logstash-6.2.2/logs which is now configured via log4j2.properties
[2018-05-03T22:49:44,672][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/Users/yaauie/src/elastic/releases/logstash-6.2.2/modules/fb_apache/configuration"}
[2018-05-03T22:49:44,690][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/Users/yaauie/src/elastic/releases/logstash-6.2.2/modules/netflow/configuration"}
[2018-05-03T22:49:44,884][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-05-03T22:49:45,394][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.2.2"}
[2018-05-03T22:49:45,817][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-05-03T22:49:48,567][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-05-03T22:49:48,671][INFO ][logstash.pipeline        ] Pipeline started succesfully {:pipeline_id=>"main", :thread=>"#<Thread:0x7fbdb02f run>"}
[2018-05-03T22:49:48,771][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
[2018-05-03T22:49:48,922][ERROR][logstash.pipeline        ] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash. {:pipeline_id=>"main", "exception"=>"-1", "backtrace"=>["java.util.ArrayList.elementData(ArrayList.java:422)", "java.util.ArrayList.remove(ArrayList.java:499)", "org.logstash.FieldReference.parse(FieldReference.java:167)", "org.logstash.FieldReference.parseToCache(FieldReference.java:142)", "org.logstash.FieldReference.from(FieldReference.java:74)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_includes(JrubyEventExtLibrary.java:123)", "org.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$1$0$ruby_includes.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$1$0$ruby_includes.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:739)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.util.decorators.RUBY$block$add_fields$2(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/util/decorators.rb:20)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.util.decorators.RUBY$block$add_fields$1(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/util/decorators.rb:18)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyHash$12.visit(RubyHash.java:1362)", "org.jruby.RubyHash$12.visit(RubyHash.java:1359)", "org.jruby.RubyHash.visitLimited(RubyHash.java:662)", "org.jruby.RubyHash.visitAll(RubyHash.java:647)", "org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1319)", "org.jruby.RubyHash.each_pairCommon(RubyHash.java:1354)", "org.jruby.RubyHash.each(RubyHash.java:1343)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.util.decorators.RUBY$method$add_fields$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/util/decorators.rb:15)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.util.decorators.RUBY$method$add_fields$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/util/decorators.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$filter_matched$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:184)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$filter_matched$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_mutate_minus_3_dot_2_dot_0.lib.logstash.filters.mutate.RUBY$method$filter$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:233)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_mutate_minus_3_dot_2_dot_0.lib.logstash.filters.mutate.RUBY$method$filter$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filter_delegator.RUBY$method$multi_filter$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:63)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$method$filter_batch$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$method$filter_batch$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$method$worker_loop$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$method$worker_loop$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)", "org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)", "Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_workers$2(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385)", "org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call(RubyProc.java:246)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)", "java.lang.Thread.run(Thread.java:748)"], :thread=>"#<Thread:0x7fbdb02f sleep>"}
Exception in thread "Ruby-0-Thread-8@[main]>worker0: :1" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.remove(ArrayList.java:499)
	at org.logstash.FieldReference.parse(FieldReference.java:167)
	at org.logstash.FieldReference.parseToCache(FieldReference.java:142)
	at org.logstash.FieldReference.from(FieldReference.java:74)
	at org.logstash.ext.JrubyEventExtLibrary$RubyEvent.ruby_includes(JrubyEventExtLibrary.java:123)
	at org.logstash.ext.JrubyEventExtLibrary$RubyEvent$INVOKER$i$1$0$ruby_includes.call(JrubyEventExtLibrary$RubyEvent$INVOKER$i$1$0$ruby_includes.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:739)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.util.decorators.RUBY$block$add_fields$2(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/util/decorators.rb:20)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
	at org.jruby.runtime.Block.yield(Block.java:165)
	at org.jruby.RubyArray.each(RubyArray.java:1734)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.util.decorators.RUBY$block$add_fields$1(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/util/decorators.rb:18)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
	at org.jruby.runtime.Block.yield(Block.java:165)
	at org.jruby.RubyHash$12.visit(RubyHash.java:1362)
	at org.jruby.RubyHash$12.visit(RubyHash.java:1359)
	at org.jruby.RubyHash.visitLimited(RubyHash.java:662)
	at org.jruby.RubyHash.visitAll(RubyHash.java:647)
	at org.jruby.RubyHash.iteratorVisitAll(RubyHash.java:1319)
	at org.jruby.RubyHash.each_pairCommon(RubyHash.java:1354)
	at org.jruby.RubyHash.each(RubyHash.java:1343)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.util.decorators.RUBY$method$add_fields$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/util/decorators.rb:15)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.util.decorators.RUBY$method$add_fields$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/util/decorators.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$filter_matched$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:184)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$filter_matched$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_mutate_minus_3_dot_2_dot_0.lib.logstash.filters.mutate.RUBY$method$filter$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb:233)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_filter_minus_mutate_minus_3_dot_2_dot_0.lib.logstash.filters.mutate.RUBY$method$filter$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.2.0/lib/logstash/filters/mutate.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$do_filter$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$block$multi_filter$1(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:164)
	at org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)
	at org.jruby.runtime.BlockBody.yield(BlockBody.java:114)
	at org.jruby.runtime.Block.yield(Block.java:165)
	at org.jruby.RubyArray.each(RubyArray.java:1734)
	at org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:498)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb:161)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filters.base.RUBY$method$multi_filter$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filters/base.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.filter_delegator.RUBY$method$multi_filter$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/filter_delegator.rb:47)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:314)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)
	at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)
	at org.jruby.runtime.Block.call(Block.java:124)
	at org.jruby.RubyProc.call(RubyProc.java:289)
	at org.jruby.internal.runtime.methods.ProcMethod.call(ProcMethod.java:63)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$method$filter_batch$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:447)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$method$filter_batch$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$method$worker_loop$0(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:426)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$method$worker_loop$0$__VARARGS__(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
	at org.jruby.ir.targets.InvokeSite.invoke(InvokeSite.java:145)
	at Users.yaauie.src.elastic.releases.logstash_minus_6_dot_2_dot_2.logstash_minus_core.lib.logstash.pipeline.RUBY$block$start_workers$2(/Users/yaauie/src/elastic/releases/logstash-6.2.2/logstash-core/lib/logstash/pipeline.rb:385)
	at org.jruby.runtime.CompiledIRBlockBody.callDirect(CompiledIRBlockBody.java:145)
	at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:71)
	at org.jruby.runtime.Block.call(Block.java:124)
	at org.jruby.RubyProc.call(RubyProc.java:289)
	at org.jruby.RubyProc.call(RubyProc.java:246)
	at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)
	at java.lang.Thread.run(Thread.java:748)
[2018-05-03T22:49:49,043][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"main", :thread=>"#<Thread:0x7fbdb02f run>"}
~/src/elastic/releases/logstash-6.2.2/bin/logstash -e   79.45s user 2.25s system 402% cpu 20.301 total
[success (20.000s)]
~~~

**Comment by yaauie** [comment]
Fixes Merged or Pending:
  - [x] 7.x/master: elastic/logstash#9543
  - [x] 6.x: elastic/logstash#9591
  - [ ] 6.3: elastic/logstash#9590
