### ISSUE TITLE
TEST FAILURE: "can communicate between pipelines"

### ISSUE THREAD

**Issue by jsvd** [elastic/logstash#9555]
test failure can be seen [here](https://logstash-ci.elastic.co/job/elastic+logstash+pull-request+multijob-integration-1/536/consoleFull)

The first error I think may be relevant here is:

```
20:32:48     [ERROR] 2018-05-09 20:32:48.296 [Converge PipelineAction::Create<test2>] agent - Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:test2, :exception=>"NameError", :message=>"uninitialized constant Gem::Specification\nDid you mean?  Gem::Specification\n               Gem::StubSpecification", :backtrace=>["org/jruby/RubyModule.java:3343:in `const_missing'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/util/plugin_version.rb:25:in `find_version!'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/util/plugin_version.rb:42:in `find_plugin_version!'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/config/mixin.rb:246:in `print_version_notice'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/config/mixin.rb:232:in `validate'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/config/mixin.rb:87:in `config_init'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/inputs/base.rb:61:in `initialize'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/plugins/plugin_factory.rb:70:in `plugin'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/plugins/plugin_factory.rb:33:in `buildInput'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/java_pipeline.rb:42:in `initialize'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/java_pipeline.rb:128:in `initialize'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/pipeline_action/create.rb:38:in `execute'", "/opt/logstash/build/logstash-7.0.0-alpha1-SNAPSHOT/logstash-core/lib/logstash/agent.rb:298:in `block in converge_state'"]}
20:32:48     [DEBUG] 2018-05-09 20:32:48.339 [Converge PipelineAction::Create<test>] javapipeli
```

**Comment by original-brownbear** [comment]
Picking this one up, seems to now happen in every IT1 run.

**Comment by kipras** [comment]
Any progress on this issue guys? I'm getting this when running pipelines as well.

**Comment by kares** [comment]
closing this one in favor of: https://github.com/elastic/logstash/issues/12077 (same underlying JRuby cause)
