### ISSUE TITLE
Logstasth pippeline error

### ISSUE THREAD

**Issue by ShaggyZG** [elastic/logstash#9599]
Logstash wont allow me to create a pipeline with my config, between him and search. I wanted to import some data into the db, but had no luck. 
Here's my config

> input{
	file{
		path=>"E:\Programi\Elastic\Server\File\test.csv"
		start_position=>"beginning"
		sincedb_path =>"/dev/null"
	}
}
filter{
	csv{
		separator =>";"
		columns =>["Bbl", "routine name", "correct count", "stopless", "startless", "averge", "min", "max", "sum", "%"]
	}
	mutate{convert =>["Bbl", "integer"]}
	mutate{convert =>["correct count", "integer"]}
	mutate{convert =>["stopless", "integer"]}
	mutate{convert =>["startless", "integer"]}
	mutate{convert =>["averge", "double"]}
	mutate{convert =>["min", "integer"]}
	mutate{convert =>["max", "integer"]}
	mutate{convert =>["sum", "integer"]}
	mutate{convert =>["%", "double"]}
}
output{
	elasticsearch{
	user => "logstash_internal" 
	password => "test"
	hosts=>"localhost:9200"
	index =>"test"
	document_type =>"tes_test"
}
stdout{}
}

And here's the log data from the error

> [2018-05-17T09:06:08,884][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"E:/Programi/Elastic/logstash-6.2.4/modules/fb_apache/configuration"}
[2018-05-17T09:06:09,019][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"E:/Programi/Elastic/logstash-6.2.4/modules/netflow/configuration"}
[2018-05-17T09:06:10,034][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (SystemExit) exit
[2018-05-17T13:03:34,675][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"E:/Programi/Elastic/logstash-6.2.4/modules/fb_apache/configuration"}
[2018-05-17T13:03:34,731][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"E:/Programi/Elastic/logstash-6.2.4/modules/netflow/configuration"}
[2018-05-17T13:03:35,260][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-05-17T13:03:36,828][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.2.4"}
[2018-05-17T13:03:38,075][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-05-17T13:03:49,759][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"document_type", :plugin=><LogStash::Outputs::ElasticSearch hosts=>[//localhost], index=>"test", document_type=>"tes_test", id=>"b0a547f1f55611379fe1e4534b0c726cfdff8e812231e0bcfa6d436b0d12f9c7", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_2c85641d-a265-40ca-985a-18bff3a54849", enable_metric=>true, charset=>"UTF-8">, workers=>1, manage_template=>true, template_name=>"logstash", template_overwrite=>false, doc_as_upsert=>false, script_type=>"inline", script_lang=>"painless", script_var_name=>"event", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, action=>"index", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>}
[2018-05-17T13:03:57,131][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-05-17T13:03:58,303][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2018-05-17T13:03:58,335][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[2018-05-17T13:03:58,829][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2018-05-17T13:03:59,078][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>6}
[2018-05-17T13:03:59,089][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}
[2018-05-17T13:03:59,142][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2018-05-17T13:03:59,208][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
[2018-05-17T13:03:59,330][INFO ][logstash.outputs.elasticsearch] Installing elasticsearch template to _template/logstash
[2018-05-17T13:03:59,697][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost"]}
[2018-05-17T13:03:59,866][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :plugin=>"#<LogStash::FilterDelegator:0x4fad9552 @metric_events_out=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: out value:0, @metric_events_in=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: in value:0, @metric_events_time=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: duration_in_millis value:0, @id=\"292ec2128bbb61404c4791954749043bb087c95a02a5f654ab097c5a4806ab03\", @klass=LogStash::Filters::Mutate, @metric_events=#<LogStash::Instrument::NamespacedMetric:0x6715baa0 @metric=#<LogStash::Instrument::Metric:0x4e24c555 @collector=#<LogStash::Instrument::Collector:0x1b38ea2 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x22978cc3 @store=#<Concurrent::Map:0x00000000000fb0 entries=3 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x1da0c483>, @fast_lookup=#<Concurrent::Map:0x00000000000fb4 entries=98 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :filters, :\"292ec2128bbb61404c4791954749043bb087c95a02a5f654ab097c5a4806ab03\", :events]>, @filter=<LogStash::Filters::Mutate convert=>{\"averge\"=>\"double\"}, id=>\"292ec2128bbb61404c4791954749043bb087c95a02a5f654ab097c5a4806ab03\", enable_metric=>true, periodic_flush=>false>>", :error=>"translation missing: en.logstash.agent.configuration.invalid_plugin_register", :thread=>"#<Thread:0x4c11138 run>"}
[2018-05-17T13:03:59,925][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<LogStash::ConfigurationError: translation missing: en.logstash.agent.configuration.invalid_plugin_register>, :backtrace=>["E:/Programi/Elastic/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:219:in `block in register'", "org/jruby/RubyHash.java:1343:in `each'", "E:/Programi/Elastic/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:217:in `register'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:342:in `register_plugin'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:353:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:353:in `register_plugins'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:731:in `maybe_setup_out_plugins'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:363:in `start_workers'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:290:in `run'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:250:in `block in start'"], :thread=>"#<Thread:0x4c11138 run>"}
[2018-05-17T13:04:00,031][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main, action_result: false", :backtrace=>nil}
[2018-05-17T13:06:38,860][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"E:/Programi/Elastic/logstash-6.2.4/modules/fb_apache/configuration"}
[2018-05-17T13:06:38,897][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"E:/Programi/Elastic/logstash-6.2.4/modules/netflow/configuration"}
[2018-05-17T13:06:39,607][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-05-17T13:06:41,928][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.2.4"}
[2018-05-17T13:06:43,965][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-05-17T13:06:53,291][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"document_type", :plugin=><LogStash::Outputs::ElasticSearch hosts=>[//localhost], index=>"test", document_type=>"tes_test", id=>"b0a547f1f55611379fe1e4534b0c726cfdff8e812231e0bcfa6d436b0d12f9c7", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_78ef62bd-69d5-4048-9a29-dce8a6394d6f", enable_metric=>true, charset=>"UTF-8">, workers=>1, manage_template=>true, template_name=>"logstash", template_overwrite=>false, doc_as_upsert=>false, script_type=>"inline", script_lang=>"painless", script_var_name=>"event", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, action=>"index", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>}
[2018-05-17T13:06:58,473][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-05-17T13:06:59,996][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2018-05-17T13:07:00,049][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[2018-05-17T13:07:00,615][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2018-05-17T13:07:00,777][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>6}
[2018-05-17T13:07:00,808][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}
[2018-05-17T13:07:00,883][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2018-05-17T13:07:00,969][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
[2018-05-17T13:07:01,295][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost"]}
[2018-05-17T13:07:01,647][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :plugin=>"#<LogStash::FilterDelegator:0x424f7d0b @metric_events_out=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: out value:0, @metric_events_in=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: in value:0, @metric_events_time=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: duration_in_millis value:0, @id=\"292ec2128bbb61404c4791954749043bb087c95a02a5f654ab097c5a4806ab03\", @klass=LogStash::Filters::Mutate, @metric_events=#<LogStash::Instrument::NamespacedMetric:0x546cc420 @metric=#<LogStash::Instrument::Metric:0x6ad4b1e9 @collector=#<LogStash::Instrument::Collector:0x23700f15 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x1a6e9955 @store=#<Concurrent::Map:0x00000000000fb0 entries=3 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x44ae17bc>, @fast_lookup=#<Concurrent::Map:0x00000000000fb4 entries=98 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :filters, :\"292ec2128bbb61404c4791954749043bb087c95a02a5f654ab097c5a4806ab03\", :events]>, @filter=<LogStash::Filters::Mutate convert=>{\"averge\"=>\"double\"}, id=>\"292ec2128bbb61404c4791954749043bb087c95a02a5f654ab097c5a4806ab03\", enable_metric=>true, periodic_flush=>false>>", :error=>"translation missing: en.logstash.agent.configuration.invalid_plugin_register", :thread=>"#<Thread:0xa4a720e run>"}
[2018-05-17T13:07:01,739][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<LogStash::ConfigurationError: translation missing: en.logstash.agent.configuration.invalid_plugin_register>, :backtrace=>["E:/Programi/Elastic/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:219:in `block in register'", "org/jruby/RubyHash.java:1343:in `each'", "E:/Programi/Elastic/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:217:in `register'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:342:in `register_plugin'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:353:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:353:in `register_plugins'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:731:in `maybe_setup_out_plugins'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:363:in `start_workers'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:290:in `run'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:250:in `block in start'"], :thread=>"#<Thread:0xa4a720e run>"}
[2018-05-17T13:07:01,832][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main, action_result: false", :backtrace=>nil}
[2018-05-17T13:13:12,204][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"E:/Programi/Elastic/logstash-6.2.4/modules/fb_apache/configuration"}
[2018-05-17T13:13:12,368][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"E:/Programi/Elastic/logstash-6.2.4/modules/netflow/configuration"}
[2018-05-17T13:13:13,343][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-05-17T13:13:15,632][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.2.4"}
[2018-05-17T13:13:18,220][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-05-17T13:13:30,196][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"document_type", :plugin=><LogStash::Outputs::ElasticSearch hosts=>[//localhost:9200], index=>"test", document_type=>"tes_test", id=>"603395f042c4209b7c8c23cf75166efae24b04c2309899a4f405073b736b7f56", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_c5a6f094-6c4c-45d6-891c-a64ea131a6bb", enable_metric=>true, charset=>"UTF-8">, workers=>1, manage_template=>true, template_name=>"logstash", template_overwrite=>false, doc_as_upsert=>false, script_type=>"inline", script_lang=>"painless", script_var_name=>"event", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, action=>"index", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>}
[2018-05-17T13:13:35,691][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>4, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-05-17T13:13:36,835][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2018-05-17T13:13:36,853][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[2018-05-17T13:13:37,262][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2018-05-17T13:13:37,387][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>6}
[2018-05-17T13:13:37,404][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}
[2018-05-17T13:13:37,463][INFO ][logstash.outputs.elasticsearch] Using mapping template from {:path=>nil}
[2018-05-17T13:13:37,575][INFO ][logstash.outputs.elasticsearch] Attempting to install template {:manage_template=>{"template"=>"logstash-*", "version"=>60001, "settings"=>{"index.refresh_interval"=>"5s"}, "mappings"=>{"_default_"=>{"dynamic_templates"=>[{"message_field"=>{"path_match"=>"message", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false}}}, {"string_fields"=>{"match"=>"*", "match_mapping_type"=>"string", "mapping"=>{"type"=>"text", "norms"=>false, "fields"=>{"keyword"=>{"type"=>"keyword", "ignore_above"=>256}}}}}], "properties"=>{"@timestamp"=>{"type"=>"date"}, "@version"=>{"type"=>"keyword"}, "geoip"=>{"dynamic"=>true, "properties"=>{"ip"=>{"type"=>"ip"}, "location"=>{"type"=>"geo_point"}, "latitude"=>{"type"=>"half_float"}, "longitude"=>{"type"=>"half_float"}}}}}}}}
[2018-05-17T13:13:37,697][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2018-05-17T13:13:37,945][ERROR][logstash.pipeline        ] Error registering plugin {:pipeline_id=>"main", :plugin=>"#<LogStash::FilterDelegator:0x3a6d4142 @metric_events_out=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: out value:0, @metric_events_in=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: in value:0, @metric_events_time=org.jruby.proxy.org.logstash.instrument.metrics.counter.LongCounter$Proxy2 -  name: duration_in_millis value:0, @id=\"55dface9f45128c30a80cc21c31de2a1364f4a1286981d7c0a284af3581ac1c1\", @klass=LogStash::Filters::Mutate, @metric_events=#<LogStash::Instrument::NamespacedMetric:0x2d0d03d2 @metric=#<LogStash::Instrument::Metric:0x3903b7d8 @collector=#<LogStash::Instrument::Collector:0x2d2b0ef9 @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x7d9c2d4f @store=#<Concurrent::Map:0x00000000000fb0 entries=3 default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x69fae6ae>, @fast_lookup=#<Concurrent::Map:0x00000000000fb4 entries=98 default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :filters, :\"55dface9f45128c30a80cc21c31de2a1364f4a1286981d7c0a284af3581ac1c1\", :events]>, @filter=<LogStash::Filters::Mutate convert=>{\"averge\"=>\"double\"}, id=>\"55dface9f45128c30a80cc21c31de2a1364f4a1286981d7c0a284af3581ac1c1\", enable_metric=>true, periodic_flush=>false>>", :error=>"translation missing: en.logstash.agent.configuration.invalid_plugin_register", :thread=>"#<Thread:0x182243ce run>"}
[2018-05-17T13:13:38,001][ERROR][logstash.pipeline        ] Pipeline aborted due to error {:pipeline_id=>"main", :exception=>#<LogStash::ConfigurationError: translation missing: en.logstash.agent.configuration.invalid_plugin_register>, :backtrace=>["E:/Programi/Elastic/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:219:in `block in register'", "org/jruby/RubyHash.java:1343:in `each'", "E:/Programi/Elastic/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/logstash-filter-mutate-3.3.1/lib/logstash/filters/mutate.rb:217:in `register'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:342:in `register_plugin'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:353:in `block in register_plugins'", "org/jruby/RubyArray.java:1734:in `each'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:353:in `register_plugins'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:731:in `maybe_setup_out_plugins'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:363:in `start_workers'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:290:in `run'", "E:/Programi/Elastic/logstash-6.2.4/logstash-core/lib/logstash/pipeline.rb:250:in `block in start'"], :thread=>"#<Thread:0x182243ce run>"}
[2018-05-17T13:13:38,091][ERROR][logstash.agent           ] Failed to execute action {:id=>:main, :action_type=>LogStash::ConvergeResult::FailedAction, :message=>"Could not execute action: LogStash::PipelineAction::Create/pipeline_id:main, action_result: false", :backtrace=>nil}

Plz help if u can :)

**Comment by andrewvc** [comment]
Github is for bug reports only. Please ask usage questions on https://discuss.elastic.co/c/logstash
