### ISSUE TITLE
Run logstash as a service and log stdout

### ISSUE THREAD

**Issue by btalebali** [elastic/logstash#9700]
Hello,

My Environement includes: 

- Logstash version: 6.2.4
- Operating System :  RedHat Entreprise Linux Server release 6.6

- **Config File :**
cat /etc/logstash/conf.d/tmp.test.conf

input {
  file {
    path => "/tmp/test.log"
  }
}
output {
  stdout {}
}

- Sample Data: echo "hello logstash13" >> /tmp/test.log

cat **/etc/init/logstash.conf**
description     "logstash"
start on filesystem or runlevel [2345]
stop on runlevel [!2345]

respawn
umask 022
nice 19
limit nofile 16384 16384
chroot /
chdir /

#limit core <softlimit> <hardlimit>
#limit cpu <softlimit> <hardlimit>
#limit data <softlimit> <hardlimit>
#limit fsize <softlimit> <hardlimit>
#limit memlock <softlimit> <hardlimit>
#limit msgqueue <softlimit> <hardlimit>
#limit nice <softlimit> <hardlimit>
#limit nofile <softlimit> <hardlimit>
#limit nproc <softlimit> <hardlimit>
#limit rss <softlimit> <hardlimit>
#limit rtprio <softlimit> <hardlimit>
#limit sigpending <softlimit> <hardlimit>
#limit stack <softlimit> <hardlimit>

script
  # When loading default and sysconfig files, we use `set -a` to make
  # all variables automatically into environment variables.
  set -a
  [ -r "/etc/default/logstash" ] && . "/etc/default/logstash"
  [ -r "/etc/sysconfig/logstash" ] && . "/etc/sysconfig/logstash"
  set +a
  exec chroot --userspec svcBoard-t:svcBoard-t / /usr/share/logstash/bin/logstash "--path.settings" "/etc/logstash" >> /var/log/logstash-stdout.log 2>> /var/log/logstash-stderr.log
end script

////////////////////////////

I have used the RPM installation of logstash.
As such, logstash is running as a linux service. I would like to debug a pipeline and need to view the output.

But, since I put data on the input file, I get this error and the the logstash service restart  and no data filled in the  /var/log/logstash-stdout.log  file !!!!!!

**error message**

[2018-06-01T16:23:25,918][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<NameError: undefined local variable or method `dotfile' for #<AwesomePrint::Inspector:0x6c36ee80>
Did you mean?  @@dotfile>, :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:163:in `merge_custom_defaults!'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb:50:in `initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/awesome_print-1.8.0/lib/awesome_print/core_ext/kernel.rb:9:in `ai'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-rubydebug-3.0.5/lib/logstash/codecs/rubydebug.rb:39:in `encode_default'", "org/jruby/RubyMethod.java:115:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-rubydebug-3.0.5/lib/logstash/codecs/rubydebug.rb:35:in `encode'", "/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `block in multi_encode'", "org/jruby/RubyArray.java:1734:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/codecs/base.rb:50:in `multi_encode'", "/usr/share/logstash/logstash-core/lib/logstash/outputs/base.rb:90:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:15:in `block in multi_receive'", "org/jruby/ext/thread/Mutex.java:148:in `synchronize'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator_strategies/single.rb:14:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/output_delegator.rb:49:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:477:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:476:in `output_batch'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:428:in `worker_loop'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:386:in `block in start_workers'"]}
[2018-06-01T16:23:26,006][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: org.jruby.exceptions.RaiseException: (SystemExit) exit

**Comment by yaauie** [comment]
It looks like you're hitting this same bug, which should be resolved by setting your `HOME` environment variable:

> :weary: it looks like the version of awesome_print we rely on has a long-standing bug where it throws an error trying to load its own configuration if your environment variable `HOME` is unset, and the clause that's meant to handle errors _also_ throws the above error
> 
>  - It was fixed in https://github.com/awesome-print/awesome_print/commit/62033856f8ff08347a9ae20fc0519b2d237e1a15
>  - Someone has already requested that they release a new version with the fix here: https://github.com/awesome-print/awesome_print/issues/338
>  - In the mean-time, can you set the `HOME` variable?
>
> -- https://github.com/logstash-plugins/logstash-filter-mutate/issues/120#issuecomment-388200850

**Comment by btalebali** [comment]
Thank you for your prompt reply.
The home variable is set to ''/root', but I still have the same error.

I can put a screnshot of **/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/awesome_print-1.8.0/lib/awesome_print/inspector.rb**

![image](https://user-images.githubusercontent.com/5453430/40908481-23bddf92-67e7-11e8-988d-6e3d2ed4ae48.png)

**Comment by yaauie** [comment]
argh; it appears that I had misinterpreted the root cause.

When awesome_print attempts to load its configuration at  `${HOME}/.aprc` and an exception is raised (e.g., the JVM not having permission to that portion of the filesystem), it attempts to squash the exception with a warning to stderr, but _that_ code references a variable that is no longer there.

I'll open a PR on the Rubydebug Codec to pin us to a previous version while we wait for the upstream project to push out a release, and will update here with steps to move forward shortly.

**Comment by yaauie** [comment]
@btalebali a workaround has been shared (see caveat below):

> I added this to /etc/logstash/startup.options:
> 
>     # workaround for https://github.com/logstash-plugins/logstash-output-stdout/issues/11
>     HOME=${LS_HOME}
> 
> then run /usr/share/logstash/bin/system-install
>
> -- https://github.com/logstash-plugins/logstash-output-stdout/issues/11#issuecomment-386210536

Caveat: the `system-install` script mentioned above will _regenerate_ the appropriate init scripts for your system, potentially overwriting your custom init scripts. However, you should be able to achieve the same result by exporting the `HOME` environment variable with a value equivalent to the path of Logstash just prior to launching Logstash; this will ensure that we avoid triggering the JVM's safeguards against reading files outside of the process's control, as we do when it attempts to read `/root/.aprc`.
