### ISSUE TITLE
ssl verification_mode for modules doesn't work as described in docs

### ISSUE THREAD

**Issue by HonzaKral** [elastic/logstash#9734]
The documentation explicitly states for ` var.elasticsearch.ssl.verification_mode ` to:

> Set to disable to turn off hostname verification. 

Yet setting that value to disable causes an exception:
```
[ERROR][logstash.config.sourceloader] Could not fetch all the sources {:exception=>LogStash::ConfigLoadingError, :message=>"Failed to parse the module configuration: [Invalid value for :verify. Valid values are (:all, :browser, :default)]", :backtrace=>["/tmp/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/manticore-0.6.1-java/lib/manticore/client.rb:614:in `ssl_socket_factory_from_options'", "/tmp/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/manticore-0.6.1-java/lib/manticore/client.rb:394:in `pool_builder'", "/tmp/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/manticore-0.6.1-java/lib/manticore/client.rb:402:in `pool'", "/tmp/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/manticore-0.6.1-java/lib/manticore/client.rb:208:in `initialize'", "/tmp/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/manticore.rb:58:in `build_client'", "/tmp/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/manticore.rb:49:in `initialize'", "/tmp/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:121:in `initialize'", "/tmp/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport.rb:26:in `new'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/elasticsearch_client.rb:50:in `initialize'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/elasticsearch_client.rb:21:in `build'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/config/modules_common.rb:74:in `block in pipeline_configs'", "org/jruby/RubyArray.java:1734:in `each'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/config/modules_common.rb:56:in `pipeline_configs'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/config/source/modules.rb:16:in `pipeline_configs'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/config/source_loader.rb:59:in `block in fetch'", "org/jruby/RubyArray.java:2481:in `collect'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/config/source_loader.rb:58:in `fetch'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/agent.rb:148:in `converge_state_and_update'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/agent.rb:90:in `execute'", "/tmp/logstash-6.2.4/logstash-core/lib/logstash/runner.rb:348:in `block in execute'", "/tmp/logstash-6.2.4/vendor/bundle/jruby/2.3.0/gems/stud-0.0.23/lib/stud/task.rb:24:in `block in initialize'"]}
```

to replicate just run `bin/logstash  --modules arcsight --setup -M 'arcsight.var.elasticsearch.ssl.verification_mode=disable' -M 'arcsight.var.elasticsearch.ssl.enabled=true'`

**Comment by toddferg** [comment]
could be related to https://github.com/cheald/manticore/issues/52

**Comment by guyboertje** [comment]
This is a docs bug sort of.

[This PR](https://github.com/logstash-plugins/logstash-mixin-http_client/pull/25) has obsoleted the setting, well it was reverted to deprecated in 5.2.0 and the latest version (6.0.1) shipping with LS 6.4.X has obsoleted it. But this applies to the elasticsearch output used in the modules when LS switches to running the module config. Before this, though, the module code does some kibana and ES housekeeping for templates and dashboards and in this stage we use client connectors for which this mode setting does exist and does take the settings from the command line or the yaml file. Logstash 6.4.0 and newer ships with conversion of the `verification_mode` to a Ruby Symbol which is the data type that Manticore is expecting. Logstash config, the command line and the yaml syntax does not have a means of specifying a Ruby Symbol, a plain word prefixed with a colon e.g. `:disable`.

Having said all that, even if one could disable the verification during the ES/Kibana housekeeping phase the module config would fail because the default in the ES output is `true` so the certs would be verified and fail.

/cc @karenzone

**Comment by piellick** [comment]
Hi everyone, news about it ? Could be use by the http / http_poller input to avoir SSL verification ?
