### ISSUE TITLE
Plugin: <LogStash::Inputs::Redis> A plugin had an unrecoverable error. 

### ISSUE THREAD

**Issue by itjwd-works** [elastic/logstash#9736]
Hi to All,

Please help, this is my first time try to setup Logtash and I wonder Kibana is not getting the data from Redis. When I check the the log this is what I found. Maybe this is the reason I cannot see the data on Kibana?

- ERROR:
[logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::Redis host=>"127.0.0.1:1313", data_type=>"pattern_channel", key=>"logstash", codec=><LogStash::Codecs::JSON id=>"json_54b1906f-c96d-4f54-9415-6479e6603f09", enable_metric=>true, charset=>"UTF-8">, id=>"5072a16f322be4fff8786cc64f482585a22422a099afbfaadde3f2eec0ef9b6c", enable_metric=>true, threads=>1, port=>6379, ssl=>false, db=>0, timeout=>5, batch_count=>125>
  Error: initialize: name or service not known
  Exception: SocketError

- Version: Logstash 6.24
- Operating System: Centos 7
- Config File (if you have sensitive info, please remove it):

> input

~~~
 {
  redis {
      host => "127.0.0.1:1313"
      data_type => "list"
      key => "logstash"
      codec => json
      }

       file {
         path => ["/var/log/nginx/*.log"]
         type => "nginx-log"
         start_position => "beginning"
         ignore_older => 0
         sincedb_path => "/dev/null"
         }
}

filter {
  grok {
    match => [ "message" , "%{COMBINEDAPACHELOG}+%{GREEDYDATA:extra_fields}"]
    overwrite => [ "message" ]
    }

        ruby {
          code => "
                event.set('index_name',event.get('path').split('/')[-1].gsub('.log',''))
               "
             }

       mutate {
         replace => ["host", "zbx.server"]
         convert => ["response", "integer"]
         convert => ["bytes", "integer"]
         convert => ["responsetime", "float"]
              }

       geoip {
         source => "clientip"
         target => "geoip"
         add_tag => [ "nginx-geoip" ]
             }
        ruby {
          code => "
                event.set('index_name',event.get('path').split('/')[-1].gsub('.log',''))
               "
             }

       mutate {
         replace => ["host", "zbx.server"]
         convert => ["response", "integer"]
         convert => ["bytes", "integer"]
         convert => ["responsetime", "float"]
              }

       geoip {
         source => "clientip"
         target => "geoip"
         add_tag => [ "nginx-geoip" ]
             }

       date {
         match => [ "timestamp" , "dd/MMM/YYYY:HH:mm:ss" ]
         remove_field => [ "timestamp" ]
            }

       useragent {
         source => "agent"
                 }
       }

output {
  elasticsearch {
    hosts => "127.0.0.1:9200"
  }
}
~~~
~~~
[2018-06-13T00:32:47,653][ERROR][logstash.pipeline        ] A plugin had an unrecoverable error. Will restart this plugin.
  Pipeline_id:main
  Plugin: <LogStash::Inputs::Redis host=>"127.0.0.1:1313", data_type=>"list", key=>"logstash", codec=><LogStash::Codecs::JSON id=>"json_99abd4a6-d31f-4c94-af5b-2137e4bf29d2", enable_metric=>true, charset=>"UTF-8">, id=>"4252dcfccd521764cc1b00972aa4c098010446bc38778cf46aeb3d02cd6b92b7", enable_metric=>true, threads=>1, port=>6379, ssl=>false, db=>0, timeout=>5, batch_count=>125>
  Error: initialize: name or service not known
  Exception: SocketError
  Stack: org/jruby/ext/socket/RubyTCPSocket.java:137:in `initialize'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/connection/ruby.rb:39:in `initialize'
org/jruby/RubyIO.java:875:in `new'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/connection/ruby.rb:151:in `block in connect'
org/jruby/ext/timeout/Timeout.java:117:in `timeout'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/connection/ruby.rb:150:in `connect'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/connection/ruby.rb:313:in `connect'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/client.rb:336:in `establish_connection'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/client.rb:101:in `block in connect'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/client.rb:293:in `with_reconnect'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/client.rb:100:in `connect'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/client.rb:364:in `ensure_connected'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/client.rb:221:in `block in process'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/client.rb:326:in `logging'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/client.rb:220:in `process'
/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/redis-3.3.5/lib/redis/client.rb:120:in `call'
~~~

**Comment by yaauie** [comment]
In future, you'll have a better response time when asking questions about usage by asking them in our [community forum](https://discuss.elastic.co/c/logstash). We reserve the issues on github to track confirmed issues with Logstash itself.

I can spot in your pipeline config, though, that you're specifying a string containing an  ip:port pair for the redis input plugin's `host` directive, but you should specify [`host`](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html#plugins-inputs-redis-host) and [`port`](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-redis.html#plugins-inputs-redis-port) separately. 

I'm closing this issue; please open a new thread in the  [community forum](https://discuss.elastic.co/c/logstash) if you have further questions.
