### ISSUE TITLE
Pipelines connected by new pipeline plugin do not shutdown in correct order leading to shutdown stalls

### ISSUE THREAD

**Issue by redbaron4** [elastic/logstash#9818]
**Background:**

We run a multiple pipeline setup in our organization. Our logstash instances writes to two different outputs (elasticsearch and hadoop). The ES output is managed by us and is supposed to run in tandem with logstash. The hadoop output is managed by another team and can be subject to intermittent outages outside our control. With a single pipeline, if WebHDFS is down events will clog the pipeline. Two pipelines allow us to (somewhat) isolate the two outputs so that events continue to be written to ES even if hadoop is not available. Allocating significantly large PQ to hadoop pipeline means we can absorb outages that last a few hours.

**Setup:**

We have defined two pipelines, `0_main` and `1_hadoop`. `0_main` is significantly more complex as it deals with ingesting the events, filtering/processing them and then writing them to ES. It also has a tcp output which sends the data to the `1_hadoop` pipeline. The `1_hadoop` pipeline receives the processed events from `0_main` (through TCP input plugin) and writes them to WebHDFS.

**Problem:**

Till 6.2.4, the pipeline startup/shutdown was ordered and one after the other. As long as we kept the pipeline IDs alphabetical, we could be sure of the order they would start/shutdown. Fixed ordering meant that the upstream `0_main` pipeline would be stopped first. Once it was closed and no more events were being sent to `1_hadoop`, the `1_hadoop` pipeline would be closed without any problems/data-loss.
After upgrading to 6.3.0, we have observed that pipelines appear to start/stop at the same time. This means that `1_hadoop` pipeline always starts/stops before `0_main` (as the latter requires more time to start due to more plugins). This is not a problem at startup but leads to a clogged shutdown (as the downstream TCP input closes first) and the upstream TCP output attempts to write to closed socket and goes into a retry loop before eventually timing out.
Replacing the TCP glue with the new `pipeline` plugin does not alleviate the problem. The downstream pipeline always closes first and the upstream pipeline throws errors like 

> [2018-06-29T16:29:51,085][WARN ][org.logstash.plugins.pipeline.PipelineBus] Attempted to send event to 'foo' but that address was unavailable. Maybe the destination pipeline is down or stopping? Will Retry.

Looking at the code, I found a [commit](https://github.com/elastic/logstash/commit/ea3474566f6ff24c42291844c14871d5dfd132fb) which probably made this change. I understand the motivation behind this change but I also feel logstash should atleast order the pipeline startup/shutdown when `pipeline` plugin is being used. This would mean we can control the downstream to start first and shutdown last so that logstash shutdowns are not stalled (and data is not lost if using in memory queues).
Is there a workaround in 6.3.0 to make this happen or atleast mimic the 6.2.4 beahviour?

Apologies if this is not the correct forum to bring this up but I have already tried to post this on discuss ([here](https://discuss.elastic.co/t/pipeline-ordering-when-using-the-new-pipeline-output/138116) and [here](https://discuss.elastic.co/t/pipeline-startup-shutdown-ordering-when-using-multiple-pipeline/113912))

**Comment by redbaron4** [comment]
Further information - I also came across https://github.com/elastic/logstash/commit/9311f8b8d03b639f7ec7867078f1a670f70954fd which further tackles most of the issues raised in this post. I upgraded to LS-6.3.1 (which contains this commit). My setup was the same but with the new pipeline plugin as the glue.

Upstream pipeline `0_main` had an output configuration like

```
output {
	if "hadoop" in [@metadata][outputs] {
        	pipeline {
	                send_to => hadoop_pipeline
	        }
	}
}
```

Downstream pipeline `1_hadoop` had an input configuration

```
input {
        pipeline {
                address => hadoop_pipeline
		add_field => {
                        "[@metadata][outputs]" => [ "hadoop" ]
                }
        }
}
```

Startup was OK and from the logs it looks like downstream pipeline is started first
```

[2018-07-13T15:13:38,736][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.3.1"}
[2018-07-13T15:13:40,048][INFO ][org.logstash.ackedqueue.QueueUpgrade] No PQ version file found, upgrading to PQ v2.
[2018-07-13T15:13:40,416][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"1_hadoop", "pipeline.workers"=>2, "pipeline.batch.size"=>2000, "pipeline.batch.delay"=>50}
[2018-07-13T15:13:41,126][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"1_hadoop", :thread=>"#<Thread:0x12384dd6@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 sleep>"}
[2018-07-13T15:13:51,339][INFO ][org.logstash.ackedqueue.QueueUpgrade] No PQ version file found, upgrading to PQ v2.
[2018-07-13T15:13:51,351][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"0_main", "pipeline.workers"=>5, "pipeline.batch.size"=>2000, "pipeline.batch.delay"=>50}
```

However on shutdown logstash again stalled and the logs had the following:

```
[2018-07-13T15:15:37,155][WARN ][logstash.runner          ] SIGTERM received. Shutting down.
[2018-07-13T15:15:38,018][WARN ][org.logstash.plugins.pipeline.PipelineBus] Attempted to send event to 'hadoop_pipeline' but that address was unavailable. Maybe the destination pipeline is down or stopping? Will Retry.
[2018-07-13T15:15:38,179][WARN ][org.logstash.plugins.pipeline.PipelineBus] Attempted to send event to 'hadoop_pipeline' but that address was unavailable. Maybe the destination pipeline is down or stopping? Will Retry.
[2018-07-13T15:15:38,625][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"1_hadoop", :thread=>"#<Thread:0x12384dd6@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 run>"}
[2018-07-13T15:15:39,019][WARN ][org.logstash.plugins.pipeline.PipelineBus] Attempted to send event to 'hadoop_pipeline' but that address was unavailable. Maybe the destination pipeline is down or stopping? Will Retry.
[2018-07-13T15:15:39,164][WARN ][org.logstash.plugins.pipeline.PipelineBus] Attempted to send event to 'hadoop_pipeline' but that address was unavailable. Maybe the destination pipeline is down or stopping? Will Retry.
```

**Comment by redbaron4** [comment]
Looking around the source code, the pipeline input plugin sets itself to `false` on shutdown _before_ the `unlisten` call. As soon as input pipeline is not running, it stops accepting new events sent by upstream pipeline and upstream pipeline hangs with the above mentioned error message.

https://github.com/elastic/logstash/blob/1124d799a8b4d5042bf6d98bfd2d6cc8606d114b/logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb#L55

Swapping the two lines in question appears to make the shutdown smooth (no more stalls and shutdown is in order) but throws a nullpointer exception sometimes.

**Comment by yaauie** [comment]
@redbaron4 thank you for this thorough bug report and analysis of both your original issue and the subsequent issues with shutdown ordering of the experimental inter-pipeline communication feature.

AFAIK, ordering of pipeline startup/shutdown when using multiple pipelines was never explicitly guaranteed, but it is rough that your experience was broken by a change in the 6.3 release.

I'm about to wrap up work for today, but I'll take a look at your proposed fix in the morning, and try to reason through any unintended consequences of swapping the order. If you have a stacktrace from the occasional NPE, I would appreciate that as well.

**Comment by redbaron4** [comment]
Thanks for looking at this @yaauie 

I understand that pipeline ordering was not a documented feature and my "trick" was more of a hack which was brittle. I like the idea of (beta) pipeline plugin which would provide a well documented durable fix for our use-case.

Looking back at the NPE, I see that it was raised by the input worker of `0_main` pipeline. We use this machine for netflow processing and the main pipeline receives netflow packets over UDP.

```
[2018-07-17T11:33:50,246][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"2_monitor", :thread=>"#<Thread:0x6d4a3f5a@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 run>"}
[2018-07-17T11:33:55,107][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{}}
[2018-07-17T11:33:55,110][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2018-07-17T11:33:55,118][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>35, "name"=>"[1_hadoop]<pipeline", "current_call"=>"[...]/logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb:26:in `sleep'"}], ["LogStash::Filters::Metrics", {"meter"=>["events"], "add_tag"=>["metric"], "flush_interval"=>60, "clear_interval"=>300, "rates"=>[1], "id"=>"3c6e4d811a8552d7a899c1369643f39ecf25303631574bb602e96b46466985e2"}]=>[{"thread_id"=>33, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/pipeline.rb:418:in `read_batch'"}, {"thread_id"=>34, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/pipeline.rb:418:in `read_batch'"}]}}
[2018-07-17T11:33:55,119][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2018-07-17T11:33:56,869][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"0_main", :thread=>"#<Thread:0x7981b9a5@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 run>"}
[2018-07-17T11:33:56,877][ERROR][logstash.inputs.udp      ] Exception in inputworker {"exception"=>java.lang.NullPointerException, "backtrace"=>["org.logstash.ackedqueue.Queue.write(Queue.java:339)", "org.logstash.ackedqueue.ext.JRubyAckedQueueExt.rubyWrite(JRubyAckedQueueExt.java:101)", "org.logstash.ext.JrubyAckedWriteClientExt.rubyPush(JrubyAckedWriteClientExt.java:53)", "org.logstash.ext.JrubyAckedWriteClientExt$INVOKER$i$1$0$rubyPush.call(JrubyAckedWriteClientExt$INVOKER$i$1$0$rubyPush.gen)", "org.logstash.ext.JRubyWrappedWriteClientExt.push(JRubyWrappedWriteClientExt.java:77)", "org.logstash.ext.JRubyWrappedWriteClientExt$INVOKER$i$1$0$push.call(JRubyWrappedWriteClientExt$INVOKER$i$1$0$push.gen)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_udp_minus_3_dot_3_dot_3.lib.logstash.inputs.udp.invokeOther5:push(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.3.3/lib/logstash/inputs/udp.rb:169)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_udp_minus_3_dot_3_dot_3.lib.logstash.inputs.udp.RUBY$method$push_decoded_event$0(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.3.3/lib/logstash/inputs/udp.rb:169)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:116)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:198)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_udp_minus_3_dot_3_dot_3.lib.logstash.inputs.udp.invokeOther0:push_decoded_event(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.3.3/lib/logstash/inputs/udp.rb:142)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_input_minus_udp_minus_3_dot_3_dot_3.lib.logstash.inputs.udp.RUBY$block$inputworker$0(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-udp-3.3.3/lib/logstash/inputs/udp.rb:142)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.MixedModeIRBlockBody.yieldDirect(MixedModeIRBlockBody.java:122)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:415)", "org.jruby.ir.targets.YieldSite.yield(YieldSite.java:87)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_codec_minus_netflow_minus_3_dot_14_dot_1.lib.logstash.codecs.netflow.RUBY$block$decode$1(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.14.1/lib/logstash/codecs/netflow.rb:115)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.ir.runtime.IRRuntimeHelpers.yield(IRRuntimeHelpers.java:415)", "org.jruby.ir.targets.YieldSite.yield(YieldSite.java:87)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bindata_minus_2_dot_4_dot_3.lib.bindata.array.RUBY$block$each$1(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/array.rb:208)", "org.jruby.runtime.CompiledIRBlockBody.yieldDirect(CompiledIRBlockBody.java:156)", "org.jruby.runtime.BlockBody.yield(BlockBody.java:114)", "org.jruby.runtime.Block.yield(Block.java:165)", "org.jruby.RubyArray.each(RubyArray.java:1734)", "org.jruby.RubyArray$INVOKER$i$0$0$each.call(RubyArray$INVOKER$i$0$0$each.gen)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:139)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:145)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bindata_minus_2_dot_4_dot_3.lib.bindata.array.invokeOther2:each(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/array.rb:208)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.bindata_minus_2_dot_4_dot_3.lib.bindata.array.RUBY$method$each$0(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/bindata-2.4.3/lib/bindata/array.rb:208)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:90)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:128)", "org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:328)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:141)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:145)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_codec_minus_netflow_minus_3_dot_14_dot_1.lib.logstash.codecs.netflow.invokeOther20:each(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.14.1/lib/logstash/codecs/netflow.rb:114)", "usr.share.logstash.vendor.bundle.jruby.$2_dot_3_dot_0.gems.logstash_minus_codec_minus_netflow_minus_3_dot_14_dot_1.lib.logstash.codecs.netflow.RUBY$method$decode$0(/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-codec-netflow-3.14.1/lib/logstash/codecs/netflow.rb:114)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)", "org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:100)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)", "org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:171)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:177)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:332)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:89)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)", "org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)", "org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)", "org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:193)", "org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:323)", "org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)", "org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132)", "org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148)", "org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73)", "org.jruby.runtime.Block.call(Block.java:124)", "org.jruby.RubyProc.call(RubyProc.java:289)", "org.jruby.RubyProc.call(RubyProc.java:246)", "org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104)", "java.lang.Thread.run(Thread.java:748)"]}
[2018-07-17T11:33:57,039][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"1_hadoop", :thread=>"#<Thread:0x1a54bac4@/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:245 run>"}

```

This is a production machine. The high volume of events made it easier for me to reproduce this issue on this machine than on a test machine. I ran the "modified" logstash-6.3.1 twice on this machine. I received the NPE only once, the other time logstash had a clean (and fast) shutdown. I have since reverted to 6.2.4 on this machine.

**Comment by berglh** [comment]
@yaauie @redbaron4 I've replicated this ~bug~ feature on Logstash 6.3.2 without any events actually coming through the pipeline. I haven't actually tested it with the modified code, I'd need to learn how to build the pipeline plugin/logstash from source first. I have a complicated Logstash configuration that would benefit greatly from this architecture; so I'm keen to see beta feature make final in future releases.

```shell
~/elastic/logstash-6.3.2$ ./bin/logstash
Sending Logstash's logs to /home/berglh/elastic/logstash-6.3.2/logs which is now configured via log4j2.properties
[2018-08-08T10:27:23,998][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.3.2"}
[2018-08-08T10:27:26,830][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"2-general", "pipeline.workers"=>3, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-08-08T10:27:26,833][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"3-ldap", "pipeline.workers"=>3, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-08-08T10:27:26,837][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"5-radius", "pipeline.workers"=>3, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-08-08T10:27:26,840][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"6-syslog", "pipeline.workers"=>3, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-08-08T10:27:26,841][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"4-dhcp-dns", "pipeline.workers"=>3, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-08-08T10:27:27,004][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"5-radius", :thread=>"#<Thread:0x3600b1a3@/home/berglh/elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline_action/create.rb:48 run>"}
[2018-08-08T10:27:27,042][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"4-dhcp-dns", :thread=>"#<Thread:0x30cecb3b run>"}
[2018-08-08T10:27:27,110][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"3-ldap", :thread=>"#<Thread:0x6c56535b@/home/berglh/elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline_action/create.rb:44 sleep>"}
[2018-08-08T10:27:27,113][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"6-syslog", :thread=>"#<Thread:0x44432346@/home/berglh/elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:245 sleep>"}
[2018-08-08T10:27:27,119][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"2-general", :thread=>"#<Thread:0x7cdfc38a@/home/berglh/elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline_action/create.rb:44 sleep>"}
[2018-08-08T10:27:28,400][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"7-outputs", "pipeline.workers"=>1, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-08-08T10:27:28,424][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"7-outputs", :thread=>"#<Thread:0x63ab6528 sleep>"}
[2018-08-08T10:27:28,770][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"1-inputs", "pipeline.workers"=>3, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50}
[2018-08-08T10:27:29,186][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5041"}
[2018-08-08T10:27:29,262][INFO ][logstash.pipeline        ] Pipeline started successfully {:pipeline_id=>"1-inputs", :thread=>"#<Thread:0x58a2a4aa@/home/berglh/elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline_action/create.rb:44 sleep>"}
[2018-08-08T10:27:29,473][INFO ][org.logstash.beats.Server] Starting server on port: 5041
[2018-08-08T10:27:29,489][INFO ][logstash.agent           ] Pipelines running {:count=>7, :running_pipelines=>[:"2-general", :"3-ldap", :"4-dhcp-dns", :"7-outputs", :"6-syslog", :"5-radius", :"1-inputs"], :non_running_pipelines=>[]}
[2018-08-08T10:27:29,787][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
^C[2018-08-08T10:29:04,838][WARN ][logstash.runner          ] SIGINT received. Shutting down.
[2018-08-08T10:29:05,099][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"2-general", :thread=>"#<Thread:0x7cdfc38a@/home/berglh/elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline_action/create.rb:44 run>"}
[2018-08-08T10:29:05,104][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"4-dhcp-dns", :thread=>"#<Thread:0x30cecb3b run>"}
[2018-08-08T10:29:05,105][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"3-ldap", :thread=>"#<Thread:0x6c56535b@/home/berglh/elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline_action/create.rb:44 run>"}
[2018-08-08T10:29:05,106][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"7-outputs", :thread=>"#<Thread:0x63ab6528 run>"}
[2018-08-08T10:29:05,106][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"6-syslog", :thread=>"#<Thread:0x44432346@/home/berglh/elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:245 run>"}
[2018-08-08T10:29:05,107][INFO ][logstash.pipeline        ] Pipeline has terminated {:pipeline_id=>"5-radius", :thread=>"#<Thread:0x3600b1a3@/home/berglh/elastic/logstash-6.3.2/logstash-core/lib/logstash/pipeline_action/create.rb:48 run>"}
[2018-08-08T10:29:09,841][WARN ][logstash.runner          ] Received shutdown signal, but pipeline is still waiting for in-flight events
to be processed. Sending another ^C will force quit Logstash, but this may cause
data loss.
```

**Comment by redbaron4** [comment]
@yaauie Have you had a chance to look through this yet?

**Comment by berglh** [comment]
@redbaron4 @yaauie I'm still experiencing this problem in logstash 6.4.1; I've been working through a bunch of other issues adapting my config so I've had plenty to do, but this will stop me utilising it in prod despite the obvious benefits with a config stack like I have.

**Comment by berglh** [comment]
@redbaron4 Is all I need to do to test the line switch to change the `logstash/logstash-core/lib/logstash/plugins/builtin/pipeline/input.rb` file in the logstash folder? Not sure I need to actually need to build a logstash-core gem for this to function. If I do, what process do you use?

I have a fairly complex multi-pipeline configuration with 7 pipelines of various worker sizes. 
```
  1-inputs -|- 2-general  -|- 7-outputs
            |- 3-dhcp-dns -|
            |- 4-radius   -|
            |- 5-ldap     -|
            |- 6-syslog   -|
```
With your code line switch, if I start the pipelines and stop it again before many events pass through the pipelines, everything appears to work correctly. However, if I let the pipelines run for ~12 hours, then try to `SIGTERM`, all my `inflight_counts` are zero, but a bunch of stalling threads in each pipeline prevent it from shutting down.

Thanks :pray:

**Comment by redbaron4** [comment]
@berglh Yes, all that is needed is to modify the file. No rebuilding is required.

I have experienced stalls with 0 events too (even without changing the code) so that is probably due to some other reason. Such stalls are short-lived (atleast in my case) and eventually the pipelines do shutdown.

**Comment by lucasmogari** [comment]
I'm also running into this error on version 6.5.4 when stopping or restarting logstash.

**Comment by danhermann** [comment]
Fixed in https://github.com/elastic/logstash/pull/10872.
