### ISSUE TITLE
Multiples Unknown Source : java.lang.NullPointerException

### ISSUE THREAD

**Issue by duylong** [elastic/logstash#9843]
Hi, 

I tried to migrate from version 5.x to the latest version 6 on RHEL7.

However, I have a blocking error:

```
[2018-07-19T05:34:39,564][ERROR][org.logstash.execution.WorkerLoop] Exception in pipelineworker, the pipeline stopped processing new events, please check your filter configuration and restart Logstash.
java.lang.NullPointerException: null
        at org.logstash.config.ir.compiler.EventCondition$Compiler.lambda$eq$8(EventCondition.java:367) ~[logstash-core.jar:?]
        at org.logstash.config.ir.compiler.EventCondition$Compiler.lambda$booleanCondition$5(EventCondition.java:141) ~[logstash-core.jar:?]
        at org.logstash.generated.CompiledDataset183.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset184.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset186.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset187.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset188.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset189.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset190.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset191.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset192.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset193.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset194.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset195.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset196.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset197.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset198.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset199.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset200.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset201.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset202.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset203.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset204.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset205.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset206.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset207.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset208.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset209.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset210.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset211.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset212.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset213.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset214.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset215.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset216.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset217.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset218.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset219.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset220.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset221.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset222.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset224.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset225.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset226.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset227.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset228.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset229.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset230.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset231.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset232.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset233.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset234.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset235.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset236.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset273.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset274.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset275.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset276.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset277.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset278.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset279.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset280.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset281.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset282.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset283.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset284.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset285.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset286.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset287.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset288.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset289.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset290.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset299.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset300.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset301.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset302.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset303.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset304.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset310.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset311.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset312.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset313.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset314.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset315.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset316.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset317.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset318.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset319.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset342.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset343.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset344.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset345.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset346.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset347.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset348.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset349.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset350.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset351.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset352.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset353.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset354.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset355.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset356.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset357.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset430.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset431.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset432.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset433.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset434.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset435.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset436.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset437.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset438.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset439.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset440.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset441.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset442.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset443.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset444.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset445.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset446.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset447.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset448.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset449.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset450.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset451.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset452.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset453.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset454.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset455.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset456.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset457.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset458.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset459.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset460.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset461.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset462.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset463.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset464.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset465.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset466.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset467.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset468.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset469.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset470.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset471.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset472.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset473.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset474.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset475.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset476.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset484.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset485.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset486.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset487.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset488.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset489.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset490.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset491.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset492.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset493.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset918.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset919.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset920.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset921.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset922.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset923.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset924.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset925.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset926.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset927.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset928.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset929.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset930.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset931.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset932.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset933.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset934.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset935.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset936.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset937.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset938.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset939.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset940.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset941.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset942.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset943.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset944.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset945.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset946.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset947.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset948.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset949.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset950.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset951.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset952.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset953.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset954.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset955.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset956.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset957.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset958.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset959.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset960.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset961.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset962.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset963.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset964.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset965.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset966.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset967.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset968.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset969.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset970.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset971.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset972.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset973.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset974.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset975.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset976.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset977.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset978.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset979.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset980.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset981.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset982.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset983.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset984.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset985.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset986.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset987.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset988.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset989.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset990.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset991.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset992.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset993.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset994.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset995.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset996.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset997.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset998.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset999.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1000.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1001.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1002.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1003.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1004.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1005.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1006.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1007.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1008.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1009.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1010.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1011.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1012.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1013.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1014.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1015.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1016.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1017.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1018.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1019.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1020.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1021.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1022.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1023.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1024.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1025.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1026.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1027.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1028.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1029.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1030.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1031.compute(Unknown Source) ~[?:?]
        at org.logstash.generated.CompiledDataset1035.compute(Unknown Source) ~[?:?]
        at org.logstash.execution.WorkerLoop.run(WorkerLoop.java:64) [logstash-core.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_91]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:438) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:302) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:36) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:131) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:339) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:132) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:148) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.runtime.IRBlockBody.call(IRBlockBody.java:73) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.runtime.Block.call(Block.java:124) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.RubyProc.call(RubyProc.java:289) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.RubyProc.call(RubyProc.java:246) [jruby-complete-9.1.13.0.jar:?]
        at org.jruby.internal.runtime.RubyRunnable.run(RubyRunnable.java:104) [jruby-complete-9.1.13.0.jar:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

Can you explain to me this exception? I can not publish my configuration.

**Comment by danhermann** [comment]
@duylong, it looks like you're running with a pretty old Java version (1.8.0_91). I'd suggest updating to 1.8.0_151 or later and see if that helps.

**Comment by danhermann** [comment]
@duylong, that looks like a bug in the experimental Java execution engine. Unless you can share some details about your config, we're unlikely to have enough information to fix it.
