### ISSUE TITLE
Logstash suddenly freezes with SSL Errors

### ISSUE THREAD

**Issue by mzominy** [elastic/logstash#9846]
Logstash with a tcp input protected with TLS will suddenly stop processing after some time. The only hint we have is that with debug activated we can see that suddenly there are about 20 SSL Error.
By "some time" I mean a range from 15 minutes up to two weeks.

Before this, everything works fine and we can see our data being processed, and after the only logs we see are the three lines concerning garbage collection over and over again, logstash stops receiving input.

First the logs indicate normal behavior:
```
[2018-07-20T09:48:17,383][DEBUG][logstash.pipeline        ] filter received *censored*
[2018-07-20T09:48:17,386][DEBUG][logstash.filters.json    ] Running json filter {:event=>#<LogStash::Event:0x14a6a715>}
[2018-07-20T09:48:17,387][DEBUG][logstash.filters.json    ] Event after json filter {:event=>#<LogStash::Event:0x14a6a715>}
[2018-07-20T09:48:17,422][DEBUG][logstash.util.decorators ] filters/LogStash::Filters::Mutate: adding value to field {"field"=>"[message][message][client_uid]", "value"=>[0]}
[2018-07-20T09:48:17,424][DEBUG][logstash.util.decorators ] filters/LogStash::Filters::Mutate: adding value to field {"field"=>"[message][message][client_uid]", "value"=>[0]}
[2018-07-20T09:48:17,427][DEBUG][logstash.pipeline        ] output received *censored*
```

Then the SSL Error: (we have several tens of these, not a fixed number, we had 75 before the last freeze)
```
[2018-07-20T09:49:20,815][DEBUG][logstash.inputs.tcp      ] SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Connection reset by peer>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:310:in `accept'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/jruby-openssl-0.10.0-java/lib/jopenssl23/openssl/ssl.rb:409:in `accept'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-tcp-5.0.9-java/lib/logstash/inputs/tcp.rb:206:in `run_ssl_server'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-tcp-5.0.9-java/lib/logstash/inputs/tcp.rb:155:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:512:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:505:in `block in start_input'"]}
```

And then nothing but periodically collecting garbage:
```
[2018-07-20T09:49:50,578][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2018-07-20T09:49:50,578][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}
[2018-07-20T09:49:52,864][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline {:pipeline_id=>"main", :thread=>"#<Thread:0x568bc2c3 sleep>"}
[2018-07-20T09:49:55,594][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ParNew"}
[2018-07-20T09:49:55,594][DEBUG][logstash.instrument.periodicpoller.jvm] collector name {:name=>"ConcurrentMarkSweep"}
[2018-07-20T09:49:57,865][DEBUG][logstash.pipeline        ] Pushing flush onto pipeline {:pipeline_id=>"main", :thread=>"#<Thread:0x568bc2c3 sleep>"}
```

- Version: Logstash 6.3.1
- Operating System: Ubuntu 16.04
- Config File (if you have sensitive info, please remove it):
(may not be the best as we're fairly new here)
```
input {
    tcp {
        port => 5959
        ssl_enable => true
        ssl_verify => false
        ssl_cert => "${LOGSTASH_TLS_CERT}"
        ssl_key => "${LOGSTASH_TLS_KEY}"
    }
}

filter {
    json {
        source => "message"
        target => "message"
    }
    json {
        source => "[message][message]"
        target => "[message][message]"
    }
    mutate {
        remove_field => [ "[message][extra][func_name]", "[message][extra][line]", "[message][extra][path]" ]
    }
    if !([message][message][client_uid]) {
        mutate {
            add_field => {"[message][message][client_uid]" => 0}
        }
        mutate {
            convert => ["[message][message][client_uid]", "integer"]
        }
    }
    if !([message][message][uid_mission_order]) {
        mutate {
            add_field => {"[message][message][uid_mission_order]" => 0}
        }
        mutate {
            convert => ["[message][message][uid_mission_order]", "integer"]
        }
    }
}

output {
    if "_jsonparsefailure" in [tags] {
        file {
            path => "/var/log/logstash/json_parse_failure.json"
        }
    } else if [message][message][looking_at_robot] == 0.0 or [message][message][looking_at_robot] == 1.0 {
        file {
            path => "/var/log/logstash/looking_at_robot_failure.json"
        }
    } else {
        elasticsearch {
            index => "%{[message][extra][logger_name]}_%{[message][message][client_uid]}"
            document_id => "%{[message][extra][logger_name]}_%{[message][message][client_uid]}_%{[message][message][uid_robot]}_%{[message][message][time]}"
        }
    }
}
```

- Sample Data: (pretty much sure that the data has nothing to do with the problem, if you're convinced otherwise and ask for it I'll try to provide some)
- Steps to Reproduce: We're not sure whether or not this can be reproduced easily, as it's hard to find other people online facing the exact same issue, and it happens randomly on our side (and we cannot link it to a specific event).

**Comment by Jonahoo** [comment]
Same error "SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Connection reset by peer>" anyone have a fix or workaround?

**Comment by jgzurano** [comment]
I'm experiencing a similar issue: I have fluentd 1.0 sending events to logstash 6.2.3 containers using tls.
After a while (could be a few minutes or hours) logstash stops responding to some requests on tcp port 4000 then it stops responding completely.

Theres lots of ssl errors like these in the log (log.level trace):

> [2018-10-02T15:58:50,069][DEBUG][logstash.inputs.tcp      ] SSL Error {:exception=>#<OpenSSL::SSL::SSLError: Socket closed>, :backtrace=>["org/jruby/ext/openssl/SSLSocket.java:283:in `accept'", "uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl23/openssl/ssl.rb:405:in `accept'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-tcp-5.0.3-java/lib/logstash/inputs/tcp.rb:203:in `run_ssl_server'", "/usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-tcp-5.0.3-java/lib/logstash/inputs/tcp.rb:152:in `run'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:516:in `inputworker'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:509:in `block in start_input'"]}

This is my tcp input:
```

input {
  tcp {
    port => 4000
    codec => fluent
    ssl_enable => true
    ssl_cert => "/etc/server.crt"
    ssl_key => "/etc/server.key"
    ssl_verify => false
    tags => [ "fluentd" ]
  }
}

output {

  stdout {
    codec => rubydebug {
      metadata => true
    }
  }

  elasticsearch {
    user => logstash
    password => logstash
    hosts => "elasticsearch:9200"
    manage_template => false
    index => "logstash-test"
  }

}
```

**Comment by jgzurano** [comment]
I found a workaround for this by disabling ssl in logstash and using nginx as ssl termination.
Seems like logstash tcp input has some problem with tls (the same certs worked great with the filebeat input).

**Comment by hanitsingh** [comment]
Did any one find solution for this.Bugging our development as well.

**Comment by mzominy** [comment]
Nope, we ended up disabling TLS.

**Comment by jsvd** [comment]
this seems related to tcp input's ssl layer, which [has recently been reworked and moved to netty](https://github.com/logstash-plugins/logstash-input-tcp/blob/master/CHANGELOG.md#520), can you upgrade to 5.2.0 and check?

**Comment by mzominy** [comment]
OK, we will upgrade and try, but it will probably take something like a week.

**Comment by hanitsingh** [comment]
That would be really helpful. I will share the error log soon that we have observed.

**Comment by ianomad** [comment]
Having this problem on logstash-2.3. What's the best version better to upgrade to? 

@zhaomizhi

**Comment by roaksoax** [comment]
I'm going to close this issue as it seems this issue is for an old Logstash version that's not currently supported. If this issue still exists in the latest version, please reopen.
